### ISSUE TITLE
error when uploading large-size competition bundle

### ISSUE THREAD

**Issue by shane-huang** [codalab/codalab-competitions#1002]
Error happens when I uploading my bundle (compressed size around 200MB, uncompressed around 1GB). 

The upload process is able to complete and then creating competition starts. After a while, I got a error message saying "There was an error uploading the file, please try again". But I still found a completion was created under my account... not sure if this link is still working. Is there any size limit for the bundle?

**Comment by lr292358** [comment]
There is some time limit in general (around 200MB).
You can upload datasets separately (e.g. a few smaller files), and link to them in the competition bundle.
