### ISSUE TITLE
Force sharing option

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1024]
add 'force sharing' (all submissions are public) option, block un-sharing.

**Comment by ckcollab** [comment]
Only show submissions that are on the leaderboard

**Comment by lr292358** [comment]
We want to share each submission automatically, and they cannot be un-shared.
It is not related to actual 'showing' (whether all or only leaderboard).

**Comment by ckcollab** [comment]
To me this is directly related to "showing the submissions" as we could have a list of 1000 submissions that are made public for a competition, making this feature unhelpful.
