### ISSUE TITLE
Find file size limits

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1050]
- [ ] Competition submission upload
- [ ] Competition upload
- [ ] Worksheet bundle

**Comment by lr292358** [comment]
It was between 200 and 300 MB from my experiments

**Comment by madclam** [comment]
I confirm, more than 300 MB cannot be uploaded. We need to make sure we can upload datasets of ~ 1GB.

**Comment by ckcollab** [comment]
On codalabtest or codalab.org?

**Comment by FlavioAlexander** [comment]
Confirmed, it is around 300 MB on production server. Testing server will handle around 400 MB or more.
