### ISSUE TITLE
Increase organizer dataset filesize

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1090]

**Comment by ckcollab** [comment]
If changing nginx settings doesn't work, take a look here: https://github.com/juliomalegria/django-chunked-upload

**Comment by lr292358** [comment]
Hi, Isabelle tried with 0.6gb and this is the error:

413 Request Entity Too Large

nginx/1.4.6 (Ubuntu)

**Comment by lr292358** [comment]
Problem: You cannot download any dataset on codalabtest (not only new big ones, all old ones too).

**Comment by ckcollab** [comment]
@FlavioAlexander please take a look at this when you have time, thanks!
