### ISSUE TITLE
action bar: long commands are rendered poorly

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1111]
If we type a long enough command that wraps, the start of the command gets shifted down to the second line, but then jumping to the beginning of the command takes part of the command to the first line, and things just get garbled.

**Comment by Raisins** [comment]
Might be a bug with jquery.term.

**Comment by Raisins** [comment]
Lower priority since issue #1171 is in place

**Comment by FlavioAlexander** [comment]
Fixed  https://github.com/codalab/codalab-worksheets/issues/11
