### ISSUE TITLE
Add max_submissions_per_week option

### ISSUE THREAD

**Issue by fyu** [codalab/codalab-competitions#1118]
Currently, in the form of defining competition phase, we can specify max_submissions and max_submissions_per_day. Given the practice of ImageNet challenge, it is also useful to specify max_submissions_per_week to avoid malicious submissions.

**Comment by FlavioAlexander** [comment]
@madclam Something to have in consideration for future development.

**Comment by jvlmdr** [comment]
+1 for this feature please!

We are using CodaLab to organise a challenge and it has been a great experience, thank you!! The only problem is that 1/day is too frequent. We would prefer something like 3 submissions every 3 months to allow people to develop new algorithms without having to create a new account.

@Tthomas63 @FlavioAlexander
