### ISSUE TITLE
Remove phase migrations, instead have better submission management?

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1180]
The idea is that phase migrations are wonky. There are a lot of cases where it'd be easier to have a list of all submissions and some added functionality to manage the individual submissions.
- [ ] re-run submissions in different phases
- [x] mark submissions failed
- [ ] re-run in place
- [ ] mark phases as private/no submissions???

**Comment by lr292358** [comment]
It seems that queueing does not work. Like when submissions at the hackathon of final1 phase were running, and next phase wanted to start, all failed. Same with Automl2 in July 2015.

**Comment by ckcollab** [comment]
Francis opinion: keep phase migrations around and add this option to potentially fix any problems that may happen.

**Comment by ckcollab** [comment]
@Tthomas63 let's note this idea for later -- replace phase migrations with nice submission management.
