### ISSUE TITLE
Make competition creation easier

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1188]
- [ ] Replace competition HTML pages with markdown ??
- [ ] Replace competition.yaml/etc. with simple form, validation would help lower the barrier to entry greatly
- [ ] Replace leaderboard somehow ??? that's a big problem

**Comment by logological** [comment]
Please don't remove the ability to use a `competition.yaml` file.  Being able to create the configuration offline is invaluable for automatically producing and deploying similar competitions.
