### ISSUE TITLE
Spec "Hall of Fame" View

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1196]
A list of top competitors, need to determine a way to label a participant as a "top competitor"

**Comment by ckcollab** [comment]
Related to #1198, which is how we'll determine scoring

**Comment by ckcollab** [comment]
Currently in Codalab we don't really have a consistent way of "scoring" or identifying successful participants. I propose we add the idea of "Badges" to users and based on how many "Badges" people have they can climb the ladder/leaderboards we could add. A product of this could be a Hall of Fame from the #1 user that month?

New things that would need to be added:
- Idea of "badges" and probably icons/cool things to match
    * A badge for participating in a competition earns you +10 point
    * A badge for making your submission public +10 points
    * A badge for participating in forum communication +10 points
    * A badge for winning a phase/competition +100 points
- Leaderboard page
- Hall of fame page (sorted by # of points from badges)

We could remove the badges idea and just replace it with a more simple points system, which may be what we need to do.

**Comment by madclam** [comment]
We'll do that as part of ChaHub for V2.
