### ISSUE TITLE
Multiple Tracks (Phases) for Competitions

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab-competitions#1201]
May be applicable to Computer Vision competitions.  Evelyne to spec.

**Comment by ckcollab** [comment]
Under one competition hat, have sub competitions within. For example, it is painful to make a new competition for each dataset we want to make a submission against.

**Comment by ErickWa** [comment]
Hi Eric, 

The priority sounds good to me.
However, #2 and #3 are important in the long run.

We are going to host a challenge by early October.
It would be good to know the feasibility of #4 so we can decide to have multiple pages for the challenge or we can condense all challenge into one page.

Once you have prototype for #4, we can help testing it!

Best, 
Tsung-Yi

On Wed, Sep 23, 2015 at 9:35 AM, Eric Carmichael <eric.carmichael@tivix.com> wrote:
Hey Tsung-Yi,

1) Technically yes you should be able to access this information, for example if you're using Python and requests you can use a Session to auth and download things -- I believe this should be possible anyway. Making this into a documented API would be perfect but I think in its current state it should work OK?
2) (updating leaderboard with metadata/groups)
3) Multiple entries in the leaderboard can be difficult, currently a lot of things are tied to the idea/assumption of 1 submission per user on the leaderboard.
4) This one could be one of the more simple issues to solve, maybe, I will need to put more thought into this. I could try to come up with a prototype, would you be able to test it extensively? Like make a competition with phase migrations but have phases open still, that kind of stuff
5) (email notifications on submission completion)

I believe priority is in this order: #1, #4, #5.. (not sure on other two)?


Also, when might you need these things completed by? What priorities would you give each of these issues?


Thanks,
Eric




On Mon, Sep 21, 2015 at 5:14 PM, Tsung-Yi Lin <tl483@cornell.edu> wrote:
Hi Eric, 

Sorry for the late reply.
My instinct is that we can first solve easy problems, e.g., #1, #4, and #5.
It will be great to catch up later this week.  Does Friday work for you?

Below is my comments:

1) There are information that is only accessible to organizer (e.g., Download all submissions on leaderboard).  Is there any API to login CodaLab so I can access organizer-only content?

2) The detailed results feature doesn't seem to solve the problem.  The idea is that leaderboard displays more information (see reference section here for example).  The participants can update the information when they want to.  This is extremely useful for research community to share and promote works.  The current leaderboard only displays user name which is quite confusing for which group did the work and what is the corresponding paper.

3) The same group would develop new algorithms over time.  We'd love to record the progress which needs to allow participants to display multiple entries.

4) The idea is that even after the challenge phase, the participants can still develop and evaluate algorithms using CodaLab.  The nice thing about this feature is that all information can be condensed into one page.

5) Awesome! :-)

Best, 
Tsung-Yi




On Wed, Sep 16, 2015 at 9:25 AM, Eric Carmichael <eric.carmichael@tivix.com> wrote:
Also, I replied to this issue with a solution to #5 potentially, let me know what you think!
https://github.com/codalab/codalab/issues/1233

On Wed, Sep 16, 2015 at 9:21 AM, Eric Carmichael <eric.carmichael@tivix.com> wrote:
Hey Tsung-Yi,

I was wondering if you had some time to talk on Skype soon? There are a couple features which may already be implemented and I'm wondering if they will meet your needs.

From Evelyne's email:
1.            Leaderboard API: create API for accessing data off leaderboard (so we can create our own custom leaderboard)
2.            Metadata: ability to edit and display metadata on leaderboard (allow users to update their metadata, and display)
3.            Leaderboard: allow multiple entries per user on leaderboard (people have multiple papers they may want to display)
4.            Multiple subtasks per competition that are always open
5.            Email notification when evaluation complete


And my responses:
1) This is already done, I messaged Tsung-Yi on skype about it, here's what I sent him:
https://github.com/codalab/codalab/wiki/User_CompetitionAPI — this should have the instructions to access the API
2) This will be particularly difficult, however they can already use the 'detailed results' option described here:
https://github.com/codalab/codalab/wiki/User_DetailedResultsPage -- this may be a good solution for their problem?
3) This would be very difficult, leaderboard code touches a lot of places and makes a lot of assumptions
4) Multiple phases open at once? This could be changed, but again, there are many assumptions made throughout the codebase that a competition will be in one phase at a time. I could make an example for this and we could test it thoroughly, but may run into a strange problem during phase migrations or some such.
5) That should be pretty easy



Do you think #1/2 will work for you? We can definitely talk on Skype if you're available!

Thanks, hope all is well,
Eric

**Comment by ErickWa** [comment]
Assigning to @FlavioAlexander , as this is getting merged to test

**Comment by madclam** [comment]
Would be good for V2.
