### ISSUE TITLE
Share buttons for worksheets. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-competitions#1211]

**Comment by percyliang** [comment]
Not clear what this does since by default things are public anyway.

**Comment by Raisins** [comment]
Add in social buttons similar to this to page for easy sharing. 
<img width="312" alt="screen shot 2015-09-26 at 3 36 02 pm" src="https://cloud.githubusercontent.com/assets/123099/10120196/1baa29ec-6465-11e5-872c-aa93edd2790b.png">

**Comment by FlavioAlexander** [comment]
Opened here https://github.com/codalab/codalab-worksheets/issues/13
