### ISSUE TITLE
Error in Leaderboard CSV File Creation

### ISSUE THREAD

**Issue by StanislawAntol** [codalab/codalab-competitions#1220]
I have noticed that not all competitions let you download the leaderboard results, due to an "Exception parsing scores!" error. One example is the [MICCAI Multimodal Brain Tumor Segmentation (BRaTS) Challenge](https://www.codalab.org/competitions/1#results).

**Comment by FlavioAlexander** [comment]
I am pretty sure we fixed this issue long time ago, can't even remember to be honest.
