### ISSUE TITLE
Add support@codalab.org email

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1224]
@ErickWa assigned this to you, let me know how to proceed on this one!

**Comment by FlavioAlexander** [comment]
@ErickWa @ckcollab Are we still discussing about this, or should I close it?

**Comment by ErickWa** [comment]
Don't close it - we need to add some A-Records to the DNS, set up email, etc.

The problem is that this DNS is registered under a former employee of the Outercurve Foundation, and he is no longer available.

I have a call in to the Engineering Director at MSR to get this fixed.

Best, -- Erick

**Comment by FlavioAlexander** [comment]
@ErickWa Just checking, not a problem.

Best,

Flavio
