### ISSUE TITLE
Codalab super-slow

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1227]
Codalab takes minutes sometimes to respond...

Sometimes we get:
The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

**Comment by ckcollab** [comment]
On what pages? What time of day? Can we get some more specifics?

I just added New Relic which can help us track performance, will push to production today.

**Comment by ErickWa** [comment]
@madclam Was this a transient problem? Please let us know when you experienced so that we can try to back-track and gather more info. 

@FlavioAlexander @ckcollab FYI.

**Comment by madclam** [comment]
The pages mostly affected are:
- competitions with a lot of participants
- https://competitions.codalab.org/competitions/2321 for example (main page and result table page).

**Comment by madclam** [comment]
We need to consider:
- problems with SQL queries
- upgrading the html server

**Comment by ErickWa** [comment]
Need to monitor performance and generate a line graph with New Relic so that we can see what is going on here...

**Comment by Spirinus** [comment]
@ErickWa @ckcollab I am currently preparing two competitions for CIKM2016 (http://cikm2016.org/) on CodaLab and the platform is also super slow for me. Especially, it is noticeable during the competition editing.

Is it possible to increase the power of the server to make sure that participants don't experience difficulties using the site and uploading their solutions?

We plan to go live at the end of this week/beginning of the next week. Thanks!

**Comment by FlavioAlexander** [comment]
Performance has improved with the new environments.
