### ISSUE TITLE
Sorting the submission table 

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab-competitions#1245]
In https://www.codalab.org/competitions/[competition_id]#participate , the submission table doesn't look ordered:

![image](https://cloud.githubusercontent.com/assets/15331/9592549/f1a60c22-4ff8-11e5-80ef-0fc4e14ee878.png)

Perhaps the submission table could be ordered by the submission time?

**Comment by madclam** [comment]
Moved to V2.
