### ISSUE TITLE
reduce vertical spacing between worksheet items

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1254]
Example 1:

    Before.
    [worksheet pliang-corenlp]{{0x7ec3601cbac441f49ec63cdeb5c61b48}}
    After.

Example 2:

    Before.

    [worksheet pliang-corenlp]{{0x7ec3601cbac441f49ec63cdeb5c61b48}}

    After.

Currently, both are rendered the same.  The spacing around the subworksheet should be much less for example 1.

**Comment by percyliang** [comment]
Issues clashing with markdown.

**Comment by percyliang** [comment]
This is not an issue just with worksheets but with all items.

**Comment by FlavioAlexander** [comment]
Opened here https://github.com/codalab/codalab-worksheets/issues/14
