### ISSUE TITLE
Viewing one's results of submissions that are not showed in the leaderboard

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab-competitions#1255]
Feature request: as a competition participant, it would be able to see the scores of my submissions that are not showed in the leaderboard. I know I can get them clicking on "Download evaluation output from scoring step", but it is a tedious process when one has several submissions.

**Comment by madclam** [comment]
This has been added and will be released with V1.5.
![image](https://user-images.githubusercontent.com/7594063/30734690-143651aa-9f31-11e7-97a0-aab7fa27f2af.png)
