### ISSUE TITLE
1. 2. 3. numbering not working

### ISSUE THREAD

**Issue by tonyyyang** [codalab/codalab-competitions#1268]
If you add a bundle between 1. and 2., the index starts over from 1..

Reference: https://www.codalab.org/worksheets/0x45cea1e33f734c2ba0d0ea85a585408e/

**Comment by Raisins** [comment]
:+1:  
Mark down syntax is clashing with your raw text. Added label and moved in to milestone

**Comment by FlavioAlexander** [comment]
Opened here https://github.com/codalab/codalab-worksheets/issues/15
