### ISSUE TITLE
Inconsistency between raw edit and cl upload

### ISSUE THREAD

**Issue by tonyyyang** [codalab/codalab-competitions#1270]
The following procedure may cause bundle without host worksheet

1. On website, you enter raw edit mode.
2. In command line, you upload a bundle. If you `cl ls` at this moment, you can see the bundle is successfully uploaded and appears at the bundle list.
3. You switch back to view mode. After updating according to plaintext in raw edit, the just-uploaded bundle is missing.

This inconsistency may cause bundle without host worksheet.

Reference bundle: https://www.codalab.org/bundles/0x8d63b4b6feb3433cae5b152623fa64e5/
Sidenote: `cl wedit` does not have this problem.

**Comment by FlavioAlexander** [comment]
Opened here https://github.com/codalab/codalab-worksheets/issues/16
