### ISSUE TITLE
dropdown for actions in side panel

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1292]
Have a dropdown box under a nice big button labeled 'Actions' under which we have:

- Upload bundle: performs 'cl upload'
- New worksheet: performs 'cl new' [popups up a search box for a name]
- Bookmark? worksheet: 'cl wadd . home_worksheet'
- Clone worksheet: performs 'cl clone' [applies to current worksheet]
- Delete worksheet: performs 'cl wrm' [applies to current worksheet]
- Search worksheet: performs 'cl wls' [popups up a search box]

Each action should issue a CLI command in the terminal.

**Comment by FlavioAlexander** [comment]
Opened here https://github.com/codalab/codalab-worksheets/issues/19
