### ISSUE TITLE
updating CodaLab

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab-competitions#1305]
What is the best way to update CodaLab instance running on Azure VM? thanks.

**Comment by ErickWa** [comment]
What sort of update are you attempting to make?  Can you provide a bit more context? Thanks!

**Comment by abmnv** [comment]
Sorry for a long delay. My issue is that when I update CodaLab with "git pull" and then trying to run CodaLab, I get error messages about missing packages. I guess in this case CodaLab has been updated with new packages and running "git pull" is not enough. Then the next solution is to clone a new version and install it from scratch. But In this case I have to deal with database migrations since I want to keep the competition database. It is not clear what is the best way to deal with it since CodaLab may not know at what migration stage the database is. Thanks for your help with this issue.

**Comment by kashizui** [comment]
Have you tried re-running `dev_setup.sh`?

**Comment by FlavioAlexander** [comment]
@abmnv Do you have any traceback to share? Thank you.

**Comment by abmnv** [comment]
@kashizui No, I didn't, I installed it from scratch. I will try next time.

**Comment by abmnv** [comment]
@kashizui How do I deal with database migration? Do I just run "./manage syncdb --migrate"? thanks.

**Comment by kashizui** [comment]
In the codalab directory, I think `./manage migrate` should work. (can the
others confirm this?)

**Comment by FlavioAlexander** [comment]
@abmnv You are correct, that should work. After you migrate,  run the command "python scripts/initialize.py" [More info here](https://github.com/codalab/codalab/wiki/Dev_Configure-Codalab-For-Development)
