### ISSUE TITLE
Problems with codalab

### ISSUE THREAD

**Issue by MehreenMehreen** [codalab/codalab-competitions#1317]
Hello

Codalab can be a great platform for teaching and learning.  It has many features and more flexibility when comparing with ikaggle as I can define my own scoring programs etc.  I would love to use it for my future class assignments but the development time makes it difficult for me to do so.

I just created a competition on codalab for an assignment for my class.  This was an extremely time consuming process.  I am listing down a few issues related to creating competition bundles.  These can be easily resolved by codalab developers to make it easy for us to create and launch competitions.  I think it is because of some these issues that ikaggle is more popular and easier to use.  Its development time is much quicker as compared to codalab:
1. Many features in the yaml file are not editable, e.g., the leaderboard is not editable from the web editor of codalab.  Everytime, I wanted to change it, I had to upload the entire bundle.
2. A change in solution files or scoring program also means we have to upload the entire bundle again.  If there is a way to do it from the 'my datasets' page, I couldn't figure it out as it didn't work for me.  Maybe this feature should be checked.
3. A phase keeps reappearing if it is there in the yaml file.  I cannot delete it from the web editor.  Again, the whole package has to be uploaded again.
4. We should be able to upload scripts and see their output properly as it is being done on Kaggle.
5. My version of firefox (18.0.1) on ubuntu does not allow me to upload competition bundles.  I had to install google chrome to do a simple upload.

Many thanks in advance for reading this and taking care of these problems.  

Mehreen

**Comment by FlavioAlexander** [comment]
@ErickWa @madclam I think these are points we should discuss when we get a chance.
