### ISSUE TITLE
Metadata on leaderboard

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1341]
It would be awesome to edit submission metadata after they have been submitted to attach footnotes to it like a reference to a paper.

Also, have this metadata information available in the "Download as CSV results" or whatever endpoint is being used to transfer data currently. So MSCOCO can use this information on a custom leaderboard.

**Also**, add some instructions to hit this endpoint and grab the information via Python/cURL/something.

NOTE: The leaderboard result endpoint does not need to be private, the actual submissions should be private.

**Comment by tylin** [comment]
Currently, the data is transferred by "Download All Submissions on the Leaderboard" button on the results page.
