### ISSUE TITLE
Command line text clipped on Worksheets page

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab-competitions#1375]
![image](https://cloud.githubusercontent.com/assets/4361560/10874654/fa305c0c-80dc-11e5-8789-fbbc4b6e12cb.png)

_Observed behavior_: First line of text in Worksheet Command Prompt is clipped horizontally, making text difficult to read.

_Expected behavior_: First line of text is not clipped and easily readable.

_Environment_: reproducible in both Chrome and Edge.

**Comment by FlavioAlexander** [comment]
Opened on worksheets https://github.com/codalab/codalab-worksheets/issues/23
