### ISSUE TITLE
Failures in Final2

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1390]
We had the following failures in AutoML phase Final2 that are worth investigating:
1) Forever “running”
Sergey 99531
akolesnikov 100081
alxndrkalinin 100561
abhishek4 100571
bihaqo 100581
tadej 101101
lukasz.romaszko	100391

2) Connection timed out:
anton.rodomanov	100101
skanajan	100321

By re-running them, they executed fine.

**Comment by FlavioAlexander** [comment]
Competition is over, closing this issue
