### ISSUE TITLE
Improve documentation of jquery terminal keyboard shortcuts

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1407]
Two options:
- allow alt-f and alt-b to jump across words in jquery terminal
- allow user to click in the middle of the command to bring the cursor there.

**Comment by kashizui** [comment]
There are already some shortcuts for jumping around (see "Keyboard shortcuts" here: http://terminal.jcubic.pl/api_reference.php)

**Comment by kashizui** [comment]
@percyliang @pbhatnagar3 

There are already some shortcuts for jumping around (see "Keyboard shortcuts" here: http://terminal.jcubic.pl/api_reference.php)

Do we want to override/change these?

Meanwhile, I don't see built-in functionality for setting the cursor with the mouse.

**Comment by percyliang** [comment]
Ah, this is useful.  Maybe we can link to the appropriate section from our
keyboard shortcuts help page and call it good for now?

**Comment by kashizui** [comment]
I'd vote for that!

Reorienting this ticket...

**Comment by FlavioAlexander** [comment]
Opened on worksheets https://github.com/codalab/codalab-worksheets/issues/26
