### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1419]
![image](https://cloud.githubusercontent.com/assets/7594063/11312762/1fa1d182-8f8d-11e5-87c4-430e4a287cd9.png)

![image](https://cloud.githubusercontent.com/assets/7594063/11313001/953b1556-8f8e-11e5-85b3-e760c94adf17.png)

**Comment by percyliang** [comment]
Can you clear the cache on your browser or try a new browser?
If I type www.codalab.org, it redirects to codalab.org just fine.  The key
is that the default is now http://www.codalab.org, not http://codalab.org.

**Comment by madclam** [comment]
Yes I can eventually work around but it does not look good.
