### ISSUE TITLE
opening files in bundles doesn't work

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1426]
Probably due to spaces in the file name?
https://worksheets.codalab.org/api/bundles/filecontent/0xe5fd1c6d1c424b958f5b9db4e58b78ee/wiki/A%20Bend%20in%20the%20River.txt

**Comment by kashizui** [comment]
yep the culprit is here
```
    url(r'^bundles/content/(?P<uuid>[A-Za-z0-9]+)/(?P<path>\S*)/$', views.BundleContentApi.as_view(), name='api_bundle_content'),
    url(r'^bundles/filecontent/(?P<uuid>[A-Za-z0-9]+)/(?P<path>\S*)$', views.BundleFileContentApi.as_view(), name='api_bundle_filecontent'),
```
we exclude whitespace in the regex

**Comment by kashizui** [comment]
@percyliang would it be unsafe to use `.*` instead of `\S*` here?

**Comment by FlavioAlexander** [comment]
Fixed
