### ISSUE TITLE
Secret key bugs

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1437]
1) Since we switched to competitions.codalab.org, the secret keys in the old format no longer work:
For example:
https://competitions.codalab.org/competitions/5211?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35
used to be called
https://codalab.org/competitions/5211?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35
no longer works.

2) Sometimes when you paste http://competitions.codalab.org/competitions/5211?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35 into your browser, it gets changed to 
https://competitions.codalab.org/competitions/5211?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35?secret_key=ac2e3853-24df-4d35-b389-d327a54d4d35

**Comment by FlavioAlexander** [comment]
fixed here: https://github.com/codalab/codalab-competitions/issues/1519
