### ISSUE TITLE
Several banners for the same competition

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1443]
In "competitions I am running" the organizers can see the banners of competitions they are organizing. Sometimes, a given competition has multiple copies of its banner. Deleting the competition results in the disappearance of all banners.

![image](https://cloud.githubusercontent.com/assets/7594063/11479554/7bc489ac-9747-11e5-9e59-a85d800ce091.png)

**Comment by FlavioAlexander** [comment]
@madclam I can't replicate this issue locally. Do you still have the repeated banners?
