### ISSUE TITLE
Public submissions checkbox

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1447]
In https://competitions.codalab.org/competitions/2321#public_submissions there is a very long list of submissions; the checkbox to restrict the list to the submissions currently on the leaderboard DOES NOT WORK.

It would be best to have buttons for each phase like in the Results tab:
![image](https://cloud.githubusercontent.com/assets/7594063/11495331/2969f50c-97bf-11e5-9337-79318ec14cd8.png)

**Comment by FlavioAlexander** [comment]
We have buttons for each phase now. Look at issue  #1503 which is closed
