### ISSUE TITLE
Configure CodaLab for Development (and associated link to this page)

### ISSUE THREAD

**Issue by cshneider** [codalab/codalab-competitions#1448]

**Comment by cshneider** [comment]
(1)  Following the instructions on https://github.com/codalab/codalab/wiki/Dev_Getting-Started-on-Windows, the url to the distribute_setup.py script at http://python-distribute.org/distribute_setup.py redirects to http://ww43.python-distribute.org/distribute_setup.py which is not the correct site.

(2) In the "next steps" section, there are no further instructions for actually setting up a Codalab server on a Windows system. The "next steps" section for a Unix system under Dev_Configure Codalab For Development is empty. 

Has Development assistance for CodaLab been discontinued? 

Thanks for your Assistance!

**Comment by FlavioAlexander** [comment]
@cshneider The links provided for Mac and Linux should work. I reviewed them, and made some changes.

**Comment by FlavioAlexander** [comment]
Closing this issue. I added a new ticket to update/add documentation. #1554
