### ISSUE TITLE
increase the space in the side panel between sections

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1479]
In the side panel of the worksheet interface, there should be more space between 'Contents', 'Metadata', and 'Host Worksheets' when the sections are collapsed.

Also, under 'Contents', if it's a file, no need to show the word 'contents' again.

Remember to edit the less files, not css.

**Comment by FlavioAlexander** [comment]
Opened on worksheets repo https://github.com/codalab/codalab-worksheets/issues/29
