### ISSUE TITLE
have graphing support JSON files

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1480]
Currently, we only support TSV files.  We'd like to support JSON files.  So for example, if the JSON file is like:

    [{a:3, b:5, c:9}, {a:9, b:1, c:6}]

Then if we have `x=a y=c` in the directive, then we should get points (3, 9) and (9, 6) to plot.

The relevant file is graph_bundle_interface.js.

**Comment by FlavioAlexander** [comment]
Opened on worksheets repo https://github.com/codalab/codalab-worksheets/issues/30
