### ISSUE TITLE
Metadata value for request_network should be of type , was false (type )

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-competitions#1484]
> When I try to edit metadata (e.g. change the description) of a run bundle from the bundle's webpage (something with url /bundles/<uuid>), I get an error at the top of the page saying, "Metadata value for request_network should be of type , was false (type )".

**Comment by FlavioAlexander** [comment]
Opened on worksheets repo https://github.com/codalab/codalab-worksheets/issues/32
