### ISSUE TITLE
Copy-paste from system clipboard to console doesn't work on some systems

### ISSUE THREAD

**Issue by kashizui** [codalab/codalab-competitions#1485]
I believe this is an ongoing issue for the jQuery terminal plugin:
https://github.com/jcubic/jquery.terminal/issues/3

**Comment by kashizui** [comment]
(In my experience on a Mac/Chrome, I just have to press Cmd+C/V a bunch of times until it works.)

**Comment by FlavioAlexander** [comment]
Opened on worksheets repo https://github.com/codalab/codalab-worksheets/issues/33
