### ISSUE TITLE
problems with empty titles

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1489]
1) If we delete the title, then there is an error: "Must have worksheet uuid and command"

2) Separately, typing a space as the title gets rendered as `<none>`.

3) Finally, when we 'cl work' to a new worksheet that doesn't have a title `<none>` doesn't show up.

**Comment by kashizui** [comment]
notes for future:

1) This is because CLI current doesn't even support deleting title (frontend tries to issue the command `cl wedit -t` which returns an error)

3) fixed in #1493

**Comment by FlavioAlexander** [comment]
Opened under worksheets repo https://github.com/codalab/codalab-worksheets/issues/36
