### ISSUE TITLE
no usage is printed out

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1491]
In the action bar, if we type something like `wperm`, only 'too few arguments' is printed out, whereas in the CLI, we get: 'usage: cl wperm [-h] worksheet_spec group_spec permission_spec', which is the desired behavior.

**Comment by FlavioAlexander** [comment]
Closing this issue here. Opened under worksheets repo now https://github.com/codalab/codalab-worksheets/issues/38
