### ISSUE TITLE
graphing: need to delete old lines

### ISSUE THREAD

**Issue by percyliang** [codalab/codalab-competitions#1504]
Here's how to reproduce the bug:

Create a worksheet with:

    % display graph /a.tsv
    [...bundle with a file inside called a.tsv...]

Save and look at the graph.  Now go back and change:

    % display graph /a.tsv display_name=summary

The bug is that there are two curves instead of one.  Basically, old items should be deleted.

Relevant file: graph_bundle_interface.js.

**Comment by FlavioAlexander** [comment]
Closing this issue here. Opened under worksheets repo now https://github.com/codalab/codalab-worksheets/issues/43
