### ISSUE TITLE
Bugs in leaderboad editor

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1527]
(1) The Learderboard title cannot be edited (called "label" in the YAML file)
(2) The column labels cannot be edited

**Comment by FlavioAlexander** [comment]
@madclam I can't replicate this error locally, can you post some screenshots? Thank you

**Comment by madclam** [comment]
and there is no "add column".

**Comment by madclam** [comment]
![image](https://cloud.githubusercontent.com/assets/7594063/14719526/039bf9ac-07fd-11e6-8a47-daba3f571fa0.png)
This is the issue (1)
