### ISSUE TITLE
Email support for forums

### ISSUE THREAD

**Issue by AishwaryaAgrawal** [codalab/codalab-competitions#1529]
How can I link an email account to the forums in challenges? I want that whenever someone posts in the forum, I get an email notification about it.

**Comment by FlavioAlexander** [comment]
@AishwaryaAgrawal We don't have this feature in place. However, I will keep it around, seems like a nice thing to have, specially for `admins` and `organizers`.

**Comment by FlavioAlexander** [comment]
Duplicate of #1566.
