### ISSUE TITLE
docker image for codalab competitions

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab-competitions#1530]
I am wondering if there is a docker image or there is a plan make one for CodaLab competitions.  We are looking into integration of CodaLab with other tools and running different software components in different docker containers talking to each other would be a nice way of integration. Thanks.

**Comment by FlavioAlexander** [comment]
@abmnv Currently, we do not have a docker image. Something I will take into account for future development. Thanks

**Comment by FlavioAlexander** [comment]
@lsenta You are the docker guy, you might want to take a look into this
