### ISSUE TITLE
Establish new Google Analytics Code for http://competitions.codalab.org

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab-competitions#1534]
Hi Flavio,

I have a Google Analytics Code for all of Codalab.org before Percy & Isabelle split the site in two, but it's no longer obvious what that code is tracking or how the two sub-sites are performing.  The code is UA-42847758-1.

Can you create and install a new Google Analytics code that is dedicated to the http://competitions.codalab.org sub-site, so that we can track it's performance independent of worksheets?

Thanks!, -- Erick

**Comment by FlavioAlexander** [comment]
@ErickWa Sure, I will take care of that

**Comment by FlavioAlexander** [comment]
resolved
