### ISSUE TITLE
Add new columns within Leaderboard

### ISSUE THREAD

**Issue by FlavioAlexander** [codalab/codalab-competitions#1555]
- Allow administrators to add new Leaderboard's columns from the editor

**Comment by cnap** [comment]
Has this functionality been added? It would be very useful!

**Comment by FlavioAlexander** [comment]
@cnap Unfortunately, I haven't had a chance to work on this feature yet.

**Comment by cnap** [comment]
thanks for the update

**Comment by pedrada88** [comment]
Any news on this feature? We are using CodaLab for SemEval and the site was already advertised. Unfortunately without this feature it seems that we are forced to create a new competition as we need to add a new column on the leaderboard... Any solution to this issue?

**Comment by j6mes** [comment]
+1 for this suggestion. Would be vey useful to have Agh.
