### ISSUE TITLE
CSV file header incorrect

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1557]
We would like to download and make available to all AutoML challenge organizers the data tables available from 
https://competitions.codalab.org/my/competition/2321/submissions/

There is a bug in the table: the header does NOT correspond to the columns. Below I am showing in RED the BAD values and in black the correct header.

![image](https://cloud.githubusercontent.com/assets/7594063/15618819/fe444f80-2404-11e6-823e-55192934e055.png)

**Comment by logological** [comment]
I'm experiencing a similar issue.  The header labels in the CSV file are "User,F1,recall,precision,coverage,Description,Date,Filename,Is on leaderboard?", but the actual columns are "User,coverage,precision,recall,F1,Description,Date,Filename,Is on leaderboard?"

**Comment by FlavioAlexander** [comment]
Hello @logological, 

I will try to look into this
