### ISSUE TITLE
Installation fails (164 errors during tests) Missing codalab.bundles?

### ISSUE THREAD

**Issue by Cerbal** [codalab/codalab-competitions#1560]
Hi. While following the instructions from [here](https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Competitions#user-content-get-the-source-code), I reach without problems to the test phase. (`python manage.py test`)

At this point the tests tell me "FAILED (errors=164)". A recurring message seems to be:
`from codalab.bundles import get_bundle_subclass
ImportError: No module named bundles`

Indeed there is no bundles.py in the directory codalab. Is there something that I have missed?

I precise that I ran it on a fresh ubuntu 14.04 install. (AWS)

**Comment by FlavioAlexander** [comment]
@Cerbal Did you fork codalab-competitions? There is a legacy `bundles.py`, but it should not cause any problem. Could you paste some traceback please?
