### ISSUE TITLE
Problem with submitting results using the compute_pi competition example

### ISSUE THREAD

**Issue by elliottd** [codalab/codalab-competitions#1562]
I have tried to [create a competition](https://competitions.codalab.org/competitions/10381?secret_key=ffb80a6d-6def-4e1f-9c09-2b32cc694fe8) on [competitions.codalab.org](CodaLab) using the [compute_pi example](https://github.com/irjudson/competition-examples/tree/master/compute_pi). 

I followed [the instructions on the wiki](https://github.com/codalab/codalab-competitions/wiki/User_Competition-Roadmap) about how to create a competition.

I formatted my submission data as a [zip file](https://github.com/codalab/codalab-competitions/files/314404/results.zip) but the server rejects the submission with an error message that I cannot understand.

>Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpFeuPOi/run'

What am I doing wrong?

**Comment by FlavioAlexander** [comment]
@elliottd This issue is not related with how you set up a competition. Probably your competition is set up properly. The error is coming from one of the servers, it was reported before by another user and I have put a fix in place. Please let me know if you continue to encounter the same problem.

**Comment by gautier-marti** [comment]
Exactly the same problem for me. While trying to set up a competition, I wanted to test the submission process, but I get the following:

`Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/codalabtools/compute/worker.py", line 255, in run
    shutil.rmtree(file_path)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/codalabtemp/tmpyOB1hw/run'`

Could you try to fix it again? Thank you.

**Comment by huskyjo** [comment]
I am having a similar problem while testing a submission

`Traceback (most recent call last):
  File "/home/azureuser/codalab-competitions/codalab/codalabtools/compute/worker.py", line 384, in run
    env=os.environ
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

@FlavioAlexander can you help me get this working?

**Comment by ckcollab** [comment]
Which server is this on @huskyjo ?

**Comment by FlavioAlexander** [comment]
@ckcollab Could it be zipping problems?

**Comment by FlavioAlexander** [comment]
Duplicate of #1607

**Comment by huskyjo** [comment]
I have been trying to make this work for days... I believe I have that part right. 

It's on the competition server.

**Comment by FlavioAlexander** [comment]
@huskyjo Do you mind if I get access to your competition?

**Comment by huskyjo** [comment]
That would be great... Should I add you as admin when I upload or share files with you

**Comment by FlavioAlexander** [comment]
@huskyjo If you don't mind adding me as an admin, that would be great. Try using `flavioAlexander` or `flavioZhingri`. You can just share the file

**Comment by huskyjo** [comment]
I added you. Do you now have access to the bundle or should I send you the zip I uploaded as well?

**Comment by huskyjo** [comment]
Also, if you know why the "Get Data" and "Submit" tab is at the bottom (instead of under Participate like most others) that would be nice to fix (less priority than the scoring of course, but in case it is something obvious)

**Comment by FlavioAlexander** [comment]
@huskyjo Thank you. What is the name of your competition? `Recognizing Families In the Wild` I think, just want to make sure.

**Comment by huskyjo** [comment]
Yes (i.e., RFIW 2017)... and no, thank you! :)

**Comment by FlavioAlexander** [comment]
@huskyjo np, allow me some time to do some troubleshooting :)

**Comment by huskyjo** [comment]
This is Track 1 of 2 (the other being classification, which basically will be same scoring program as it is now)... but the one we are working on actually has 7 categories, currently I have it set to only score a single category (figured better to try to get the simplest case working first), then it has to be updated to find average scores for 7 submissions (separate CSV files) and display separately (again, trying to walk before run... but time is not on our side, really wanted to have this launched a few days ago)

**Comment by huskyjo** [comment]
of course, thank you so much. Let me know if anything is needed

**Comment by FlavioAlexander** [comment]
@huskyjo Last thing, could you share the bundle with me please? Feel free to send it `fzhingri24@gmail.com`

**Comment by FlavioAlexander** [comment]
@huskyjo Try replacing your `metadata` file by `command: python $program/evaluate.py $input $output` and upload the competition again? You are invoking `evaluate.exe`, but executable does not exist.
