### ISSUE TITLE
Error trying to delete a submission

### ISSUE THREAD

**Issue by vponcelo** [codalab/codalab-competitions#1564]
Hi,

We need to delete a submission for removing/reset their team entries for the leaderboard results. However, I have tried the DEL option (red button) to delete different participant's submission and it is not available. The following error appear from the page https://competitions.codalab.org/competitions/submission_delete/240951 :

```
404

Could not find the page you requested. If this is in error, please file a bug report. For more information about CodaLab, check out the wiki.
```

Is it possible to do it?

Thank you in advance,

**Comment by FlavioAlexander** [comment]
@vponcelo It should work. I just tried the delete button and it works, please try again and let me know if you still have the same problem.

**Comment by vponcelo** [comment]
Yes, we still have the problem in the two competitions we manage:

https://competitions.codalab.org/competitions/9181
https://competitions.codalab.org/my/competition/10751

Also, I found a bug where submissions raise an "Unexpected Error", without specifying any more details. The solution was to change, in the phase options, the tag of the leaderboard from "hide_results" to "default". Just to inform about this issue so you can move it at the proper site.

**Comment by vponcelo** [comment]
Now it is working and I can delete the submissions in both competitions.

**Comment by FlavioAlexander** [comment]
@vponcelo What type of error do you get? Any traceback?

**Comment by vponcelo** [comment]
Hi @FlavioAlexander, just the 404 error I mention on my first post. Sorry, I cannot provide any traceback now since I am not running Codalab in a local server. Maybe it is related to the problem of those submissions that stuck in the "submitting" status and now is already solved. Thank you.
