### ISSUE TITLE
'Stuck' submissions on the 'Submitting' status

### ISSUE THREAD

**Issue by vponcelo** [codalab/codalab-competitions#1567]
Hi,

We are having some troubles in the submissions  of the following competitions:
https://competitions.codalab.org/my/competition/9181/submissions/
https://competitions.codalab.org/my/competition/10751/submissions/

They are stuck on the submitting status for more than 1 day, and it seems an internal error of the system that cannot retrieve the submission files properly. These are messages on the log files:

> There was an error retrieving file 'output.zip'. Please try again later or report the issue.
> There was an error retrieving file 'stdout.txt'. Please try again later or report the issue.
> There was an error retrieving file 'stderr.txt'. Please try again later or report the issue.

We should move on to the next phase of the competition in few hours, so we have to solve this as soon as possible. Please, can you tell us if it is an internal error and give some ideas on how to solve it?

Thanks a lot.

**Comment by FlavioAlexander** [comment]
@vponcelo Sorry to hear that, What happens when you try to submit a new submission? Do you face the same issue? I don't see any problem with any of the servers, but I am looking into the logs to find something unusual?

**Comment by vponcelo** [comment]
@FlavioAlexander  Yes it also happens with my own submissions, and I tried the scoring program locally and it works fine. It started to give this problem since the submissions of July 1st and it also happen in the second phase we just started today.
This is the scoring program we are using: https://competitions.codalab.org/my/datasets/download/c4ad7cdc-33fe-493a-82d5-4b2a665e961b

**Comment by FlavioAlexander** [comment]
@vponcelo Juts you know, I am looking into this problem, I will follow up with you once a solution is in place

**Comment by FlavioAlexander** [comment]
@vponcelo Things should be working now, please let me know if you encounter any other issue. The problem came from azure SDK, they added an extra header for security reasons and I did not realize that.

**Comment by vponcelo** [comment]
Thank you @FlavioAlexander for your message. I see now it is working!

**Comment by vponcelo** [comment]
It seems we are having the same issue again for the competition: 
https://competitions.codalab.org/competitions/10751
It happened just after submitting some changes in the edit section, in particular the changes I did were on the scoring program and keeping out the check box of "anonymous leaderboard"

**Comment by shervin64** [comment]
This seems to be happening again today. Any idea what is going on?

**Comment by alexmomeni** [comment]
This is happening to me right now - for this competition http://miccai.cloudapp.net/competitions/82#participate-submit_results

**Comment by ckcollab** [comment]
@alexmomeni miccai.cloudapp.net is not our instance, we run competitions.codalab.org
