### ISSUE TITLE
Stuck in the Submitting state

### ISSUE THREAD

**Issue by sergeytulyakov** [codalab/codalab-competitions#1572]
Hi,

Our participants are having troubles with getting their scores. The submissions are stuck in the "Submitting" state

https://competitions.codalab.org/competitions/10261

It was working couple of days ago, but now it does not. 

Our competition ends soon. Could you, please, assist us to fix the issue?

Possibly, duplicate of 
https://github.com/codalab/codalab-competitions/issues/1567

Thanks,
Sergey

**Comment by FlavioAlexander** [comment]
@sergeytulyakov Sorry about that, over the weekend our servers handle hundreds of submissions, meaning the waiting time to process one increased. Things should be working now, please let me know if you still have the same problem

**Comment by sergeytulyakov** [comment]
Thanks, indeed it works now.
