### ISSUE TITLE
Submission that breaks the competition site!

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1573]
I made a submission to:
https://competitions-test.codalab.org/competitions/1128?secret_key=e93d72ee-3217-4112-a804-7af6d3a3edf5

After that, the leader board showed this message:
Traceback (most recent call last):
  File "./apps/web/views.py", line 535, in get_context_data
    context['groups'] = phase.scores()
  File "./apps/web/models.py", line 940, in scores
    computed_values[id] = sum([ranks[d.id][id] for d in computed_deps[sdef.id]]) / float(cnt)
KeyError: 2852L

It is impossible to kill the guilty submission because the submission panel 
https://competitions-test.codalab.org/my/competition/1128/submissions/
shows:
500 Internal server error. Please file a bug report. For more information about CodaLab, check out the wiki.

I believe that this is a bug in the scoring program that may have caused that. However, it should not be possible that a bug in the scoring program messes up the whole competitions.
As can be seen, several submissions were successfully made before that, this was a functioning competition.

**Comment by FlavioAlexander** [comment]
@madclam Let me look into that. I can probably delete the submission manually.
