### ISSUE TITLE
link broken to terms and conditions

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1575]
When people register to a new competition they have to accept the rules. Unfortunately, when you click on the link you do not get to the rules
![image](https://cloud.githubusercontent.com/assets/7594063/17073705/242ae264-5028-11e6-99aa-3aa2436c6629.png)

For example, in competition
https://competitions-test.codalab.org/competitions/1052

It is strange because when you copy and past the link, it is correct, but not when you click on it:
https://competitions-test.codalab.org/competitions/1052#learn_the_details-terms_and_conditions

**Comment by FlavioAlexander** [comment]
fixed
