### ISSUE TITLE
"Unexpected Error" for a Hidden Leaderboard

### ISSUE THREAD

**Issue by vponcelo** [codalab/codalab-competitions#1576]
Hi, 

I found an error message where any submissions raise an "Unexpected Error" at the moment of clicking the submit button, without specifying any more details It happens when the tag option of the leaderboard is set to "hide_results" in the following competitions:

https://competitions.codalab.org/competitions/9181
https://competitions.codalab.org/competitions/10751

It does not happen when the tag option of the leaderboard is set to "default". 
I would like to know what the problem is in order to have a hidden leaderboard for the second phase of the second competition I linked above.

Thanks in advance,

**Comment by FlavioAlexander** [comment]
@vponcelo I will look into this issue, it would be great if you can give me admin access so I can play around with your competition and look at the logs.

**Comment by vponcelo** [comment]
@FlavioAlexander Thank you. You should have now access granted as a new admin for the competition https://competitions.codalab.org/competitions/10751

**Comment by vponcelo** [comment]
This is an example of the problem we are having both on the test server and the general server from Codalab.

![unexpected error](https://cloud.githubusercontent.com/assets/3542257/17560217/7fabe59a-5f21-11e6-85f7-d549102412da.png)

**Comment by FlavioAlexander** [comment]
@vponcelo I am currently looking into this issue

**Comment by FlavioAlexander** [comment]
@vponcelo You should be able to submit when Leaderboard is hidden.

**Comment by vponcelo** [comment]
@FlavioAlexander I tried now and it seems to work. Thank you very much for being so quick! 
Isabelle also told me that in the test server the leaderboard is visible for organizers even if it is set to "hidden". However, it is still completely hidden also for organizers in the global server. Could be also visible in this general server as for the test server? My apologies because I forgot to report this yesterday.

**Comment by FlavioAlexander** [comment]
@vponcelo It should be working now. Only competition creators had the ability to see the hidden Leaderboard. I made a small change and any admin/organizer should be able to see the Leaderoard.

**Comment by vponcelo** [comment]
@FlavioAlexander thanks a lot. I can see it now as an admin!
Best,

**Comment by FlavioAlexander** [comment]
@vponcelo  My pleasure!!!
