### ISSUE TITLE
Submissions stuck in "submitting" or "submitted"

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1595]
During the https://competitions.codalab.org/competitions/11711 competition, about 10% of the submissions got stuck in "submitting" or "submitted" mode.

**Comment by madclam** [comment]
This may be due to the program which zips the files (we noticed failures with Ubuntu), the type of browser used, and/or congestion of the server.

**Comment by FlavioAlexander** [comment]
Duplicate #1598
