### ISSUE TITLE
CSV not downloadable by organizers when leaderboard is hidden

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1596]
The leaderboard of https://competitions.codalab.org/competitions/11711#results for the "private" phase is hidden. There is an error when trying to download the CSV.

**Comment by madclam** [comment]
![image](https://cloud.githubusercontent.com/assets/7594063/20281750/0359db32-aab2-11e6-941a-adc245e1bc2f.png)

**Comment by jonmay** [comment]
Is there a workaround for this? I am having the same problem in my competitions (noted below) and am in need of acquiring my participants' submissions!

https://competitions.codalab.org/competitions/15437
https://competitions.codalab.org/competitions/15436

**Comment by FlavioAlexander** [comment]
@jonmay For some reason I did not pay close attention to this issue. It seems related to #1631. As a quick solution, I think you can make the Leaderboard public and download the csv, then you can make it private again. In the meantime, I will try to come up with a good/real solution
