### ISSUE TITLE
Show best submission

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1597]
It would be great to have the option to show the best submission (instead of the last) on the leaderboard.
Other information that cousl optionally be shown:
- number of submissions
- date of last submission

**Comment by ckcollab** [comment]
3 options:
1. Force latest to leaderboard
2. Allow setting any submission to leaderboard submission
3. Best submission pushed automatically to leaderboard

Find "main column" and ascending or descending, compare this way. It could be a score of 1 is better than a score of 100, or vice-versa.

**Comment by xbaro** [comment]
This must be an option for the phase

**Comment by ckcollab** [comment]
The column to sort by is the column with the lowest `Ordering`!
