### ISSUE TITLE
URGENT stuck in submission as "submitting" or "submitted"

### ISSUE THREAD

**Issue by AtousaTorabi** [codalab/codalab-competitions#1599]
Hi,

I am organizer of compition below:
https://competitions.codalab.org/competitions/11531

Our deadline is this week for submission and many people have submission problems and get server errors. Their submission once pass and submitting same file the next day it could stuck in "submitting" or "submitted" status. This happens most often.

Please advice how to solve the issue! It is very urgent since people can not submit...

Best,
Atousa

**Comment by FlavioAlexander** [comment]
Duplicate #1598
