### ISSUE TITLE
Elasticity

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1606]
Can we make it that compute workers are turned on and off as there are more or less jobs on the queue?

**Comment by FlavioAlexander** [comment]
@madclam We'll need to look into that. We need to dig more into [Autoscaling ](https://azure.microsoft.com/en-us/documentation/articles/best-practices-auto-scaling/)

**Comment by madclam** [comment]
Eric wanted to do that already for a while. For V2?
