### ISSUE TITLE
SBS_SHARED_ACCESS_KEY_NAME

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#1608]
Hi, 

I am trying to reinstall codalab for development. Today I received the following error message, when running the worker.py (from codalab-competitions/codalab/codalab):

Traceback (most recent call last):
  File "worker.py", line 79, in <module>
    start_worker()
  File "worker.py", line 36, in start_worker
    queue = getQueue()
  File "/home/juliojj/server/codalab-competitions/codalab/apps/jobs/models.py", line 37, in getQueue
    settings.SBS_SHARED_ACCESS_KEY_NAME,
  File "/home/juliojj/server/codalab-competitions/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'SBS_SHARED_ACCESS_KEY_NAME'

I noticed that the worker of the previous version doesn't have this 'SBS_SHARED_ACCESS_KEY_NAME' , as we can see below:

From the previous installation (which is compatible with my local.py file, under codalab-competitions/codalab/codalab/settings):

queue = AzureServiceBusQueue(settings.SBS_NAMESPACE,
                                     settings.SBS_ACCOUNT_KEY,
                                     settings.SBS_ISSUER,
                                     name)

From the current file:

queue = AzureServiceBusQueue(settings.SBS_NAMESPACE,
                                     settings.SBS_ACCOUNT_KEY,
                                     settings.SBS_ISSUER,
                                     settings.SBS_SHARED_ACCESS_KEY_NAME,
                                     settings.SBS_SHARED_ACCESS_KEY_VALUE,
                                     name)

Is there anything I can do to fix this?
Thanks, and sorry if I made any mistake.

**Comment by juliojj** [comment]
... in the previous message, the file which is different, from the previous version in relation to the newest one, is codalab-competitions/codalab/apps/jobs/models.py (and not the worker by itself)

**Comment by FlavioAlexander** [comment]
@juliojj With the latest changes some of the files have changed, `local.py` being one of them. We we have a PR open with the latest changes. Anyway, if you add `SBS_SHARED_ACCESS_KEY_NAME` and `SBS_SHARED_ACCESS_KEY_VALUE` to your `local.py` and pull the latest changes, things should work. You don't even need to provide values to them, just set them equal to empty strings. Azure SDK will still use your `SBS_ACCOUNT_KEY`to authenticate.

**Comment by juliojj** [comment]
Hi Flavio, if I include that in my local.py file, as below:

SBS_RESPONSE_QUEUE = 'response' # incoming queue for site worker
SBS_COMPUTE_QUEUE = 'compute'  # incoming queue for Windows compute worker
SBS_SHARED_ACCESS_KEY_NAME = ' '
SBS_SHARED_ACCESS_KEY_VALUE = ' '

and run:  ~/server/codalab-competitions/codalab/codalabtools/compute$ python worker.py

I receive the new error:

Traceback (most recent call last):
  File "worker.py", line 521, in <module>
    main()
  File "worker.py", line 507, in main
    config.get_service_bus_shared_access_key_name(),
  File "worker.py", line 75, in get_service_bus_shared_access_key_name
    return self._winfo['azure-service-bus']['shared-access-key-name']
KeyError: 'shared-access-key-name'

Best and thanks for your help.

Julio

**Comment by FlavioAlexander** [comment]
@juliojj I see what the problem is, you also need to update your worker configuration file. Have a look [here](https://github.com/codalab/codalab-competitions/wiki/Dev_Set-up-data-storage#create-a-local-compute-configuration-file). Add `shared-access-key-name` and `shared-access-key-value` to your `codalabconfig` under `azure-service-bus`.

Please let me know if you have any more questions, I will be happy to assist you

**Comment by juliojj** [comment]
Hi Flavio. I set up the variables with the correct values in my local.py and edited the codalabconfig as you suggested and it worked.
Thanks a lot.

**Comment by FlavioAlexander** [comment]
@juliojj I am glad it did. 👍
