### ISSUE TITLE
Error parsing `admin_names` when uploading new competition

### ISSUE THREAD

**Issue by muxspace** [codalab/codalab-competitions#1609]
Hello, I'm trying to upload a competition on codalabs.org. My user name is `profrowe`. When I upload my `competition.zip` I get the below error. Can someone tell me what is wrong and how to resolve?

```
Traceback (most recent call last):
  File "/home/azureuser/codalab/codalab/apps/jobs/models.py", line 231, in run_job_task
    result = computation(job)
  File "/home/azureuser/codalab/codalab/apps/web/tasks.py", line 98, in create_it
    competition = competition_def.unpack()
  File "/home/azureuser/codalab/venv/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/azureuser/codalab/codalab/apps/web/models.py", line 1404, in unpack
    admins = User.objects.filter(username__in=admin_names.split(','))
AttributeError: 'str' object has no attribute 'objects'
```

I copied my `competition.yaml` from the `compute_pi` example. Here is the first portion of the config:

```
title: User behavior prediction
description: This competition is a supplement to the Trumid Data Scientist interview process. If you are up to the challenge, please contact us and we will grant access.
image: logo-trumid-gray.svg
has_registration: True
#end_date: 
admin_names: profrowe
html:
  overview: overview.html
  evaluation: evaluation.html
  terms: terms.html
  data: data.html
```

I also have a `phases` and `leaderboard` section. FWIW, I removed the commented out `#end_date` and got the same error message. Here is also the structure of my `competition.zip`:

```
Archive:  competition.zip
    testing: competition.yaml         OK
    testing: data.html                OK
    testing: evaluation.html          OK
    testing: logo-trumid-gray.svg     OK
    testing: overview.html            OK
    testing: program.zip              OK
    testing: reference.zip            OK
    testing: terms.html               OK
    testing: submission/              OK
```

**Comment by FlavioAlexander** [comment]
@muxspace It seems like Django is treating `User` as a string instead of as a object which I need to dig more into the codebase to find the real problem. Anyway, if you want to have your competition running, I think you should ignore `admin_names` for now. You can always add admins in the editor once the competition is running.

**Comment by muxspace** [comment]
Thanks for the quick response. Removing that field did the trick.

**Comment by FlavioAlexander** [comment]
Keeping the issue open until a real solution is put in place
