### ISSUE TITLE
submissions page fail

### ISSUE THREAD

**Issue by jonmay** [codalab/codalab-competitions#1612]
on 15411 submissions page i clicked 'show' on one of the items and then on reload got a 500 error.

**Comment by jonmay** [comment]
this is what i see when i try to look at the front facing results page:

Traceback (most recent call last):
  File "./apps/web/views.py", line 574, in get_context_data
    context['groups'] = phase.scores()
  File "./apps/web/models.py", line 972, in scores
    overall_ranks = ranks[sdef.id]
KeyError: 50998L

**Comment by FlavioAlexander** [comment]
@jonmay Could you share the competition's link? Probably your submission did not finish properly, it seems it is failing while retrieving the score. You should try to make a new submission and check what the outcome is

**Comment by jonmay** [comment]
secret url is https://competitions.codalab.org/competitions/15411?secret_key=7893fe7b-ba3d-4be8-bc3f-9e132e0f1476

I think I figured out the problem: i had the wrong leaderboard column names. This is reported properly on the results page: I get the message "Are all of the leaderboard column names matched with scores saved in scores.txt?" The only bug then is that the submissions page gives the 500 error rather than failing gracefully. I can live with that :-)

**Comment by FlavioAlexander** [comment]
@jonmay Oh yeah, that is deff another reason, I am glad you found out what the problem was. Also,  you can always create another ticket for the 500 error. I have considered replacing that, been living with 500 error too long :). If you do, just link this issue as a reference, thanks.
