### ISSUE TITLE
show multiple submission results on the leaderboard

### ISSUE THREAD

**Issue by abmnv** [codalab/codalab-competitions#1614]
Hello,

I am wondering if there is an option to show multiple submission results on the Leaderboard. The default behavior is to show only one result.

thanks,
artem

**Comment by FlavioAlexander** [comment]
Hello @abmnv 

It does not relly makes sense to have multiple submissions on the Leaderboard. It is design to show only one result per participant, most likely the best of all submissions.  If participants want to see more submissions, they can always visit `public submissions` page. On the other hand, an administrator can always visit `submissions` page to see everyone's submissions. Let me know if you have any other question

Best,

Flavio
