### ISSUE TITLE
Cannot add new files to coopetition/ directory

### ISSUE THREAD

**Issue by LishengSun** [codalab/codalab-competitions#1618]
Hi,

I am building my competition bundle. In my scoring system, I would like to add some 'coopetition' scores to measure the contribution of a certain submission. To do so, I need to write a file and save it to the coopetition directory (ex /codalabtemp/tmpjG3Dqm/run/input/coopetition/). This file must be read and updated every time when we get a good submission.

The problem is, I found that codalab competition makes a temporary directory for each submission, and everything that are saved from other submissions are just lost. The only files that 'survive' are those made by default (i.e. '/codalabtemp/tmpjG3Dqm/run/input/coopetition/coopetition_phase_1.txt', '/codalabtemp/tmpjG3Dqm/run/input/coopetition/coopetition_scores_phase_1.txt', '/codalabtemp/tmpjG3Dqm/run/input/coopetition/current_user.txt', '/codalabtemp/tmpjG3Dqm/run/input/coopetition/coopetition_downloads.txt'). And those created by me (for example, '/codalabtemp/tmpjG3Dqm/run/input/coopetition/current_ensemble_score.txt') are not kept from one temporary instance to another.

Could you please tell me how to add files freely to this coopetition/? 

Thank you!!

**Comment by FlavioAlexander** [comment]
@LishengSun Were you able to find a work around for this issue?

**Comment by LishengSun** [comment]
Hi Flavio,

Yes. We finally moved the project to the see.4c server and served the
worksheet as our memory keeper. The main steps are:
1) Julio has created a module called 'codalabWsCompIntegration' (see
attached), inside which we can find functions that let you connect to
worksheet from competition side, and then upload everything you want to the
worksheet.

2) So every time when I receive a good model, I call 'connect_cli()' to
connect to the worksheet, then upload_prediction_file_to_memory() to save
the model in our memory worksheet.

I attach the module and a very simple example with this email. Maybe you
can implement this in the official Codalab instance?

If you have any question, please let me know!


Best regards,
Lisheng
