### ISSUE TITLE
Examples of competition bundles

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1621]
Many examples of
https://github.com/Tivix/competition-examples
no longer work. We need to update the examples in the documentation.

**Comment by FlavioAlexander** [comment]
@madclam What type of errors are you encountering? Could you paste tracebacks?

**Comment by ckcollab** [comment]
Here's the new link: https://github.com/codalab/competition-examples

**Comment by madclam** [comment]
Go over all examples, make sure they work. Add new ones to examplify new features.

**Comment by madclam** [comment]
Started new issue: https://github.com/codalab/codalab-competitions/issues/1975.
