### ISSUE TITLE
Error publishing competition

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1622]
I've created and tested several competitions.  Whenever I try to publish any of them by clicking on the "Publish" button in the "Competitions I'm Running" tab, I get the following error dialog:

> Error publishing competition, check your Internet connection. If problem persists contact an administrator.

I've tried in three different browsers (SeaMonkey, Firefox, and Chromium) with all add-ons (ad-blockers, etc.) disabled so I'm pretty sure it's not a problem on my end.

**Comment by FlavioAlexander** [comment]
@logological Let me look into this issue. I just tried a new competition in our test server and it seemed to work. 

Best,

Flavio

**Comment by logological** [comment]
Thanks.  In the meantime I've also tried deleting and recreating the competitions, but that didn't help.  I also tried other browsers (Konqueror and Internet Explorer 8) but got the same error message.

**Comment by FlavioAlexander** [comment]
@logological Thanks for the info. I have run more tests and can't replicate your problem. I used three different browsers with the same results (`Chrome, safari and Firefox`) Are you using one of our environments?

**Comment by logological** [comment]
What do you mean by "one of our environments"?

**Comment by logological** [comment]
If it's possible that there's something in my competition bundle that's causing a problem, I could upload it here for you to test yourself.  (There's nothing in it that I don't mind being made public.)

**Comment by FlavioAlexander** [comment]
@logological That works, I could try it myself.

**Comment by logological** [comment]
@FlavioAlexander OK, here's one of the competition bundles I'm trying to publish.
[competition.zip](https://github.com/codalab/codalab-competitions/files/632496/competition.zip)

**Comment by FlavioAlexander** [comment]
@logological I think I found what the problem is. Your competition phases` are missing the link to`reference_data`, at least 2 of them are. You can add them by using the editor. If you have already uploaded the data, just reference them within the editor. Otherwise, upload a dataset and then edit your competition. 

I hope that helps.

Let me know if you have more questions or if you run into more issues.

Best,

Flavio

**Comment by FlavioAlexander** [comment]
We should probably consider returning a more meaningful message. Blaming everything on the internet connection does not seem correct to me :).

**Comment by logological** [comment]
> I think I found what the problem is. Your competition phases are missing the link to `reference_data`

Well, that's by design – I had been informed by @bethard (in his [SemEval-2017 instructions](https://github.com/bethard/semeval-codalab#the-reference-data)) that it was not necessary to include a `reference_data` line in the competition bundle, and that the data could be added later via the web interface.  I omitted these lines because the reference data for my competitions is not ready yet.  Can I just provide dummy data for now and change it to the real data later via the web interface?

**Comment by FlavioAlexander** [comment]
@logological From the design perspective, you are correct. However, by looking at the `codebase`, a competition will fail to publish because of missing `reference data`. Yep, you can reference to any dummy data or even to the data you are using in the `current phase`. Later on, you can use the UI to change them.

**Comment by logological** [comment]
@FlavioAlexander Thanks for the information.  I'll try as you suggest first thing tomorrow.  (Oh, and I agree that the current error message is not very helpful – perhaps you could change it so that it better explains why the competition failed to publish.)

**Comment by FlavioAlexander** [comment]
@logological Let me know if it works

**Comment by logological** [comment]
@FlavioAlexander Yes, I was able to publish the competitions after adding `reference_data` lines to all phases in `competition.yaml`.
