### ISSUE TITLE
Document supported interpreters/runtime environments and how to select them

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1623]
I may have missed it, but I don't believe that the wiki (e.g., [User_Building a Scoring Program for a Competition](https://github.com/codalab/codalab-competitions/wiki/User_Building-a-Scoring-Program-for-a-Competition)) contains any documentation on what interpreters and runtime environments are available for use with scorers, and how these interpreters and runtime environments can be invoked.

For example, does `python` run Python 2 or Python 3?  Does `java` run Java 7 or 8 (or maybe an even earlier version)?  There seems to be no way for users to figure these things out other than by trial and error.

I recently wrote a scoring program in Java 8.  I found that CodaLab Competitions couldn't run it because it uses an older Java runtime environment.  I had to cross-compile the program to target Java 7 to get it to work.  It would have been nice to know the supported runtime environment version in advance—or better yet, it would have been nice to be able to select from a list of JREs.

**Comment by FlavioAlexander** [comment]
@logological Thanks for the detailed ticket. I will definitely add information regarding runtime environments. We currently support `Python 2`. Personally, I am not sure about Java, will find out.
