### ISSUE TITLE
Reference data error when publishing a competition

### ISSUE THREAD

**Issue by FlavioAlexander** [codalab/codalab-competitions#1627]
Ticket #1622 brought to my attention the following: 
- `Reference_data` is not required within the `yaml` file, meaning competition will be created properly. However, publishing the competition `throws` an error because of missing link to `reference_data`. We can't throw an error when publishing the competition if we bypass them during creation. Possible solutions:

- [ ] Make sure `yaml` file checks for `reference_data`
- [ ] Allow submission to be published withouth requiring `reference_data` to all phases. 
- [ ] I consider `first phase` should always have `reference_data`.  Check it during creating and when publishing.

**Comment by madclam** [comment]
Have we resolved that?
