### ISSUE TITLE
MS COCO caption challenge not allowing updated metadata (publication URL for example)

### ISSUE THREAD

**Issue by etiennem2** [codalab/codalab-competitions#1629]
It seems that in order to update something like the publication URL field on previously submitted result requires another upload of results? Is there someway to just update the information without having to resubmit (since we only get 5 total submissions it is costly).

**Comment by FlavioAlexander** [comment]
@etiennem2 Unfortunately, you can only update `description` for now. Adding the ability to update the rest of the fields will require some work on my end.

**Comment by etiennem2** [comment]
Thanks Flavio. Updating the description should be helpful, when I change that field (like putting an arxiv link in there https://arxiv.org/abs/1612.00563) through the Submit/View results, it doesn't seem to take the changes.

**Comment by FlavioAlexander** [comment]
Hey @etiennem2, 

Could you describe what steps are you taking? I just did some testing and it seems to be working. 

![codalab_-_competition](https://cloud.githubusercontent.com/assets/7468482/21428944/9585b720-c82a-11e6-9c06-0253ee1e9027.png)

**Comment by etiennem2** [comment]
Maybe I'm going to the wrong tab, what I'm doing is going to the Participate tab, then under the 
Submit/View Results just changing the description, my view doesn't show this "update description" tab, I must be missing something?

**Comment by FlavioAlexander** [comment]
@etiennem2 That seems correct. Make sure you click the `+` button on your right, this will display few options including the `update description` button. Feel free to post images, that would probably  help 😄

**Comment by etiennem2** [comment]
Great, now I see with the + button and have updated the description, thanks a lot.

**Comment by FlavioAlexander** [comment]
YAY, I am glad it worked.
