### ISSUE TITLE
incorrect message when attempting to view hidden leaderboard in future phase

### ISSUE THREAD

**Issue by jonmay** [codalab/codalab-competitions#1630]
originally reported to me by@jflanigan:

If the leaderboard is not going to be shown (leaderboard_management_mode: hide_results) and a phase of the competition has not started yet, when attempting to view the leaderboard this message is printed:

"This phase has not started yet. The leaderboard is still hidden to participants but visible to you as an organizer"

This is printed even if the user is not an organizer. The text appears to be the only thing that is buggy; no information that shouldn't be shown is shown.

**Comment by FlavioAlexander** [comment]
@jonmay A user will be able to see the above text only if they are an administrator or a creator. We can always refactor the text to be something like `This phase has not started yet. The leaderboard is still hidden to participants but visible to you as an organizer or administrator` or something along those lines.

**Comment by jonmay** [comment]
Unless I've misconfigured my competition it is viewable by non-administrators/creators. When logged in as a non-creator I see this message as do others in the competition.

**Comment by FlavioAlexander** [comment]
@jonmay You are correct. I am able to to see the text as well. Will try to add a fix when I get a chance.
