### ISSUE TITLE
anonymized leaderboard csv downloads contain user information

### ISSUE THREAD

**Issue by jonmay** [codalab/codalab-competitions#1631]
discovered and submitted to me by @jflanigan

If the leaderboard is anonymized (anonymous_leaderboard: True), shown (leaderboard_management_mode: show_results) and the phase is active, users can see an anonymized leaderboard and have the option to download a csv. The csv, however, is **not** anonymized; usernames are shown. 

The only workaround I currently have for this bug is to not show the leaderboard but this denies users the ability to view their own scores. Is there a suitable workaround available?

**Comment by FlavioAlexander** [comment]
@jonmay There is nothing in place that will allow that. Let me take a quick look in the codebase, I can probably think of a solution.
