### ISSUE TITLE
request: ability to download all submission contents

### ISSUE THREAD

**Issue by jonmay** [codalab/codalab-competitions#1632]
It would be handy to have an easy way to download all the submissions for a competition with one button. Right now I can get all submissions but it requires clicking the expansion button and the 'download your submission' button for each submission. "thankfully" i have a reasonable number of competitors but beyond 30 or so this would get really tiresome.

(sorry if this isn't the right place to make a feature request; i wasn't aware of another suitable location)

**Comment by madclam** [comment]
OK, added to wish list for V2.
