### ISSUE TITLE
Superfluous e-mail notifications when accepting participants

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1633]
For every participant I accept into one of my CodaLab competitions, I get two separate confirmation e-mails:

> From: CodaLab <info@codalab.org>
> Subject: SomeOtherUser accepted into your competition!
>
> Hello Logological,
> The user SomeOtherUser was accepted into your competition:
> SemEval-2017 Task 7, Subtask 1 Manage participants
>
> Thanks,
> CodaLab Team

> From: CodaLab <info@codalab.org>
> Subject: Accepted into SemEval-2017 Task 7, Subtask 1!
>
> Hello Logological,
> This is a message updating your access to the competition:
> SemEval-2017 Task 7, Subtask 1
> Your status has been accepted!
>
> Thanks,
> CodaLab Team

The first e-mail makes sense, but the second one doesn't.  Why do I always get a message telling me I've been accepted into my own competition?  I hope CodaLab isn't spamming all the other participants with a similar message whenever someone new joins the competition.

**Comment by FlavioAlexander** [comment]
@logological Giving more thought to this issue. I think the second email is meant for the participant which makes sense.
