### ISSUE TITLE
Nonsensical "reinstate" button after approving participant

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1634]
Immediately after I approve a new participant to a competition I'm running, CodaLab updates the participant table by adding a row for that participant.  In the "Status" column for that participant, there are two buttons: "reinstate" and "Revoke".  I think the "reinstate" button doesn't make sense here; surely this is something that should appear only after a participant has been revoked, not immediately after they are approved.  After reloading the page, however, the "reinstate" button disappears.

**Comment by madclam** [comment]
Has this been fixed?

**Comment by logological** [comment]
Problem is still reproducible on the production site at https://competitions.codalab.org/.

**Comment by Didayolo** [comment]
Still reproducible in the Python3 instance https://codalab.lisn.fr/
