### ISSUE TITLE
Rich text editor gobbles spaces around <samp>…</samp> tags

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1635]
The rich text editor in the web interface gobbles all whitespace before and after `<samp>`…`</samp>` HTML tags.  This makes it impossible to use these tags for their intended purpose of showing program input and output.  The whitespace-gobbling doesn't initially affect HTML files uploaded as part of competition bundles, but if the competition is ever edited in the web interface, the problem occurs.

Sample steps to reproduce:
1. Create a competition bundle containing an `evaluation.html` file containing, say, `<p>Your answer file must contain <samp>1</samp> in the second column.</p>`.
2. Create a new competition by uploading the competition bundle.
3. View the competition.  The evaluation page is correctly rendered as follows:
   > Your answer file must contain <samp>1</samp> in the second column.
4. Edit the competition in the web interface.  It's not necessary to make any changes; just click on the "Submit" button to save it as-is.
5. View the competition.  The evaluation page is now incorrectly rendered as follows:
   > Your answer file must contain<samp>1</samp>in the second column.
6. Edit the competition in the web interface. This time, try to re-add spaces around `1` and re-save the competition.
7. View the competition.  Despite the latest changes to the evaluation page, it is still rendered incorrectly.

**Comment by logological** [comment]
A workaround for this issue is to use the HTML source editor and add `&nbsp;` character entities before and/or after the `<samp>`…`</samp>` tags.

**Comment by FlavioAlexander** [comment]
@logological I was able to replicate the problem. Unfortunately, I am having a hard time adding a `patch` for this issue. I would recommend you to keep using the workaround in the meantime

**Comment by madclam** [comment]
Thank you for pointing that out. I am putting this issue in the ice box. We will revisit it when we address other related HTML editor issues. Thank you for finding a workaround.
