### ISSUE TITLE
support zip with top directory

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1636]
Many people zip the top directory with their submissions of competition bundles and get errors. Could we support both cases (with and without directory)?

**Comment by FlavioAlexander** [comment]
@madclam This is a nice thing to have. We have encountered some issues regarding `zipping` files

**Comment by ckcollab** [comment]
Problems with permissions? Compute workers may have been changed slightly. Also need to update 3rd compute worker on codalabtest!

**Comment by madclam** [comment]
Has this feature been implemented? Should it be tested?

**Comment by ckcollab** [comment]
This was implemented, Wade tested it many many times.
