### ISSUE TITLE
Feature request: e-mail notification on submission failure

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1637]
When a submission finishes successfully, CodaLab sends the following e-mail notification to the participant (provided the "Email on submission finished successfully" option is enabled in their user settings):

> From: CodaLab <info@codalab.org>
> Subject: Submission has finished successfully!
>
> Your submission to the competition "SemEval-2017 Task 7, Subtask 1" has finished successfully! View it here: https://competitions.codalab.org/competitions/15705

It would be even more helpful if it were possible to have CodaLab send an e-mail notification in the event that the submission *fails*, since this would alert the participant that something has gone wrong and needs to be fixed.

**Comment by FlavioAlexander** [comment]
@logological This is a good idea, I will have this in consideration for future enhancements. 

Thanks
