### ISSUE TITLE
Submission is failing regardless of scoring program or data

### ISSUE THREAD

**Issue by nmrinl** [codalab/codalab-competitions#1639]
* Submissions go from Submitted to Failed, but do not display any error message (nor are any of the stdout or stderr logs produced)
* It seems to happen regardless of what data or scorer are used by the competition.

I have also attached the competition.yaml in txt format below (as it does not support .yaml).
[competition_yaml.txt](https://github.com/codalab/codalab-competitions/files/664413/competition_yaml.txt)

**Comment by FlavioAlexander** [comment]
@nmrinl 🤔  I am trying to think what could be wrong. Without any `traceback` is really hard for me to hunt down the issue.  Here is something you should try:

- Upload a new `dataset/score` using the `My datasets` tab, then reference them as your `reference_data/score` using our editor.

Let me know if that helps. 

Best,

Flavio

**Comment by nmrinl** [comment]
Hi Flavio,
Thanks for looking into this. I have uploaded new dataset/scoring program and referenced them from the edit tab of my competition. Kindly let me know what else you need to from my side.

**Comment by FlavioAlexander** [comment]
Hi @nmrinl, 

Were you able to submit using the new score? If not, do you have any traceback to share?

Best,

Flavio

**Comment by nmrinl** [comment]
Scoring output log:
There was an error retrieving file 'stdout.txt'. Please try again later or report the issue.

Scoring error log is also same as above.

**Comment by FlavioAlexander** [comment]
@nmrinl I think the problem comes from your scoring program. When storing the results you need to make sure the `headers` matches the `labels` from your columns within the `.yaml` file. Please have a look at our [samples](https://github.com/Tivix/competition-examples). Have a closer look at [this](https://github.com/Tivix/competition-examples/blob/master/hello_world/competition/scoring_program/evaluate.py#L29-L31) and [this](https://github.com/Tivix/competition-examples/blob/master/hello_world/competition/competition.yaml#L26-Lundefined).

Aplogies for the delayed answer. I haven't been able to check github due to holidays celebrations. Please let me know if that helps. 

Best,

Flavio

**Comment by nmrinl** [comment]
Hi Flavio,
Matching keys with leaderboard did not help. I was thinking it may be failing there. 
But now I am getting the error even if I do not write anything in file. 
Do you want me to add you as an admin of our competition, then I think you can take a closer look.

**Comment by FlavioAlexander** [comment]
@nmrinl Sure, please do so. Let me know what the name of the competition is. 

Best, 

Flavio

**Comment by nmrinl** [comment]
Thanks, I have added you as an admin, please search for the following competition: 
SemEval 2017 Task 10 ScienceIE

**Comment by FlavioAlexander** [comment]
Thank you, let me do some debugging. So far I get nothing, traceback is empty. I will look into the logs. Is it possible to share your scoring program?

**Comment by nmrinl** [comment]
[program.zip](https://github.com/codalab/codalab-competitions/files/673405/program.zip)

I have attached the scoring program.
My email id is nmrinl@gmail.com

**Comment by Cyvhee** [comment]
Me too. I succeeded in evaluating one submission, but the status of all the following submissions is "Failed", without changing anything in the code. Downloading the evaluation output gives me "There was an error retrieving file 'output.zip'. Please try again later or report the issue".

Any thoughts or help on this would be greatly appreciated!

Kind regards
Cynthia

**Comment by hazirbas** [comment]
Hi,
I have the same problem. Any solution?
