### ISSUE TITLE
Organizers cannot see the leaderboard

### ISSUE THREAD

**Issue by xbaro** [codalab/codalab-competitions#1640]
On competition results page template (_results_page.html) line 11, there is an elseif case that prevents organizers and owners of a competition to see the leaderboard on active phases. The line is:

> 
> {% elif phase.is_future and  block_leaderboard_view and is_owner or request.user in competition_admins %}
>     <p>This phase has not started yet. The leaderboard is still hidden to participants but visible to you as an organizer</p>

The precedence order (https://docs.djangoproject.com/en/dev/ref/templates/builtins/#complex-expressions), this is interpreted as:

(phase.is_future AND block_leaderboard_view AND is_owner) OR (request.user in competition_admins)

therefore organizers only see this message instead of the leaderboard.

**Comment by FlavioAlexander** [comment]
@xbaro This will prevent `administrators` to see the Leaderboard, but creators would be able to see it. Anyway, adding a fix shortly 😄
