### ISSUE TITLE
"Publish" button should trigger a confirmation dialog

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1641]
At https://competitions.codalab.org/my/#competitions I tend to see an awful lot of dummy competitions that were clearly uploaded for testing purposes only, and never meant to be published.  I can't help but think that this is because the uploaders don't fully understand the implications of using the "Publish" button.  Can I suggest that the functionality of this button be changed so that, rather than immediately publishing the competition, it throws up a confirmation dialog similar to the following?

> **Publish competition**
>
> Are you sure?  Published competitions are featured on the CodaLab home page.  Registration will be open to the public.
>
> [ OK ]  [ Cancel ]

This sort of confirmation dialog is already in use for other competition actions, such as revoking a participant.

**Comment by FlavioAlexander** [comment]
@logological Your suggestion makes a lot of sense 👍 . However,  I am not really sure if that would prevent organizers for publishing testing competitions. Unfortunately, that is something we can't really control, but there is always room for improvement such as:

- Limit the amount of competitions a user can publish.
- Probably, also limit the amount of competitions a user can create within a period of time.  🤔  
- Keep track of inactive competitions and `unpublished/deleted` them after a certain amount of time.
- Featuring competitions, meaning we could put those testing competitions at the very bottom.

Those are just a few ideas.

Best,

Flavio

**Comment by madclam** [comment]
Thank you for these suggestions. Once we have attended to more pressing issues, we intend to put better order in the published competitions and perhaps introduce some level of checking by admins or peer review before a competition is published.
