### ISSUE TITLE
UPDATE Anacoda

### ISSUE THREAD

**Issue by ahmedmazari** [codalab/codalab-competitions#1644]
We used a more recent version of LinearSVC than in current on the server. Thus, when submitting our sample 
we get errors due to the version of LinearSVC.

**Comment by FlavioAlexander** [comment]
@ahmedmazari Not sure if that is possible since we have other competitions running as well. I just want to avoid having broken competitions because of updates. I think we can definitely update the package itself, if possible.

**Comment by madclam** [comment]
Let us stick to the version we have for the moment to avoid clashing with other competitions. We have several competitions starting soon. Ahmed: see the fix I proposed in the email I sent you to modify your stating kit. Try to be compatible with the current version on Codalab.
Alternatively: see whether your code runs on https://codalab.lri.fr/ (maybe a newer version of Anaconda was installed there).
