### ISSUE TITLE
allow organizers to submit to future phases

### ISSUE THREAD

**Issue by bethard** [codalab/codalab-competitions#1645]
For phases of a competition that have not yet started, even if you are an organizer of the task, the Participate / Submit / View Results page displays "This phase of the competition has not started yet. Please check back later."
<img width="951" alt="screen shot 2017-01-03 at 12 00 55" src="https://cloud.githubusercontent.com/assets/1118599/21619328/524843d4-d1ac-11e6-8bec-4e07eb3ccfce.png">
As an organizer, it would be really helpful for debugging purposes if I could submit results to phases that have not yet started, so I can test that the evaluation script, input data, etc. are all correct.

**Comment by madclam** [comment]
You can do that by either "migrating" your submission from phase to phase or by changing the dates manually. I am afraid that letting you do what you suggest would have other side effects difficult to anticipate.

**Comment by bethard** [comment]
I think the "migrating" will work for my purposes. Just in case anyone else has this same question, my solution was:
1. Go to the competition Edit page
2. Check Auto migration for each phase
3. Click Submit
4. Go to Participate / Submit / View Results
5. Submit my output for the future phase
6. Go to the competition Submissions page
7. Click Show by the output I just submitted
8. Refresh the page
9. Hit the Migrate button that now appears by the output I just submitted
10. Go back to the Edit page and disable the Auto migration
