### ISSUE TITLE
hidden leaderboard hides all scoring info

### ISSUE THREAD

**Issue by jonmay** [codalab/codalab-competitions#1646]
if leaderboard mode is set to 'default' the following options are available after submission:

Download your submission
View scoring output log
View scoring error log
Download evaluation output from scoring step
Download private output from scoring step

however, if the mode is set to 'hide results' only 'download your submission' is available. Hiding scoring results and declining to show a leaderboard are not the same thing. Either the mode should not change what options are available or the name of the mode should change.

**Comment by madclam** [comment]
Actually no: when the leaderboard is hidden, the participants should not be able to see their results, this is a feature, not a bug. There could be finer options, but this may be error prone.

**Comment by jonmay** [comment]
that's fine; i'd argue the name of the option should be changed to reflect this.
