### ISSUE TITLE
team names are not anonymized with "Anonymous leaderboard"

### ISSUE THREAD

**Issue by bethard** [codalab/codalab-competitions#1648]
If you turn on "Anonymous leaderboard" (i.e., anonymous_leaderboard: True), the leaderboard still displays team names. Assuming this is not intended behavior, I believe _results_page.html needs to be changed from:

    {% if phase.competition.allow_teams %}
    <td>{{scoredata.team_name|default_if_none:""}}</td>
    {% endif %}

to:

    {% if phase.competition.allow_teams %}
    <td>
        {% if phase.competition.anonymous_leaderboard %}
            <i>Anonymous</i>
        {% else %}
            {{scoredata.team_name|default_if_none:""}}
        {% endif %}
    </td>
    {% endif %}

**Comment by FlavioAlexander** [comment]
@bethard Something along those lines would do it. Feel free to create a PR with those changes 😄

**Comment by madclam** [comment]
I believe this is for "old style teams". We'll see whether with v1.5 people like more the new style teams and we'll try to get only one type of teams in v2.
