### ISSUE TITLE
Live competition phase incorrectly marked as closed

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1653]
We're currently running [a competition](https://competitions.codalab.org/competitions/15705#participate-submit_results) with the end date configured for 2017-01-15 23:59:59.  The competition has three phases: "Trial" was configured to start on 2016-12-05 00:00:00, "Test (Homographic)" was configured to start on 2017-01-09 00:00:00, and "Test (Heterographic)" was also configured to start on 2017-01-09 00:00:00.

The "Trial" and "Test (Heterographic)" phases are correctly accepting submissions.  However, in the front end, the "Test (Homographic)" phase is not accepting submissions; it displays the message, "This phase of the competition is closed."

**Comment by FlavioAlexander** [comment]
@logological 🤔  If I recall correctly a phase will be closed as soon as another phase starts, meaning you can have only one phase open at a given time. However, long time ago we implemented a feature called `phase never ends` or something along those lines that allows a competition to have multiple phases open. You could try using that.

Best, 

Flavio

**Comment by logological** [comment]
It would have been nice to know in advance that concurrent phases are prohibited. :(  Perhaps this could be added to the documentation; it also would have been nice if, when uploading or editing a competition, the system would check for concurrent phases and throw an error message.  In the absence of such notices, the current behaviour is completely unpredictable and unexplainable.  But in any case, what's the rationale for disallowing concurrent phases?

I will try the "phase never ends" option, but it sounds like this means I'll have to manually end the phases now.  (Or does the "competition end" date override the "phase never ends" option?)

**Comment by FlavioAlexander** [comment]
1. I agree, this should be added to the documentation. I added the `phase never ends` feature and forgot to add the corresponding documentation, apologies for that.  I am not sure why we don't allow concurrent phases, I came late to the project. 

2. You need to manually end the phases,  `competition end` date will not override `phase never ends`. 

Let me know if you have any more questions.
