### ISSUE TITLE
Dependency problems with dev_setup

### ISSUE THREAD

**Issue by piotrsobecki** [codalab/codalab-competitions#1656]
I'm trying to install fresh instance of codalab-competitions and encounter problems with django-configurations.

Problem occurs, when running "python manage.py validate" in configurations/base.py of django-configurations 0.8
Error:
- "No module named django.utils", also there is no module named django.conf in django 1.5.9

**Comment by ckcollab** [comment]
What is your output for `pip freeze` and also `env | grep -i Django`? Might just need to change ENV vars

**Comment by piotrsobecki** [comment]
I've added those env settings but without any results

grep

> DJANGO_SETTINGS_MODULE=codalab.settings
DJANGO_CONFIGURATION=Dev

pip freeze

> adal==0.4.4
alabaster==0.7.9
alembic==0.6.7
anyjson==0.3.3
argh==0.26.2
azure==0.7.1
Babel==2.3.4
certifi==2016.9.26
cffi==1.9.1
chardet==2.3.0
closure-linter==2.3.13
cryptography==1.7.1
Django==1.5.9
django-allauth==0.11.1
django-analytical==0.15.0
django-appconf==0.6
django-bootstrap-form==3.2
django-braces==1.2.2
django-compressor==1.3
django-config-gen==1.0.8
django-configurations==0.8
django-debug-panel==0.8.1
django-debug-toolbar==0.9.4
django-extensions==1.5.7
django-extra-views==0.6.3
django-filter==0.7
django-guardian==1.1.1
django-haystack==2.4.0
django-js-reverse==0.7.3
django-mptt==0.5.5
django-nose==1.4.1
django-oauth-toolkit==0.6.1
django-simple-captcha==0.4.5
django-storages==1.1.8
django-tinymce==2.0.5
djangorestframework==2.3.6
docutils==0.13.1
enum34==1.1.6
futures==3.0.5
idna==2.2
imagesize==0.7.1
ipaddress==1.0.18
isodate==0.5.4
Jinja2==2.9.4
keyring==10.2
Mako==1.0.6
MarkupSafe==0.23
meld3==1.0.2
mock==1.0.1
msrest==0.4.4
msrestazure==0.4.6
MySQL-python==1.2.5
newrelic==2.54.0.41
nose==1.3.7
oauthlib==0.6.1
olefile==0.44
pathtools==0.1.2
Pillow==4.0.0
psutil==2.1.1
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6
Pygments==2.1.3
PyJWT==1.4.2
python-dateutil==2.6.0
python-gflags==3.1.0
python-memcached==1.57
python-openid==2.2.5
python-ptrace==0.6.5
pytz==2013b0
PyYAML==3.10
requests==1.2.3
requests-oauthlib==0.3.2
SecretStorage==2.3.1
six==1.10.0
snowballstemmer==1.2.1
South==1.0.2
Sphinx==1.4.1
SQLAlchemy==0.9.7
supervisor==3.0
watchdog==0.8.1

**Comment by ckcollab** [comment]
Hmm, I'm not sure, it could be something with your paths/virtual environment?
