### ISSUE TITLE
Unable to change phases

### ISSUE THREAD

**Issue by mk351** [codalab/codalab-competitions#1657]
I'm testing the pages for a competition due to start next week, but any changes to phases made in the edit page are not reflecting in the competition pages.

**Comment by FlavioAlexander** [comment]
Hello @mk351, what type of changes are you making? Are the changes being saved properly or do you see some sort of error?

**Comment by mk351** [comment]
I'm trying to delete some phases. There's no error, it seems that the changes are accepted. I was not able to change the dates earlier, but that seemed to have worked this time.

**Comment by FlavioAlexander** [comment]
@mk351 It seems like there is a bug while deleting a phase. That's definitely something that needs to be taken care of. I am not sure what happened with the date, but I am glad it worked

**Comment by mk351** [comment]
Hi @FlavioAlexander thanks for letting me know. Do you think this will be fixed in the next couple of days? In case it will take longer, I'll have to figure out a way around this for now. Thanks!

**Comment by ckcollab** [comment]
What happens when you press save/submit on the form, any errors? Does it take you back to the competition?

**Comment by mk351** [comment]
@ckcollab I'm not getting any errors. It waits for some time and then stays on the edit page, it doesn't go back to the competition.

**Comment by mk351** [comment]
@ckcollab I tried it again. Now its taking me back to the competition page, but not deleting the phase.

**Comment by jponttuset** [comment]
I am encountering similar problems here. When I change the scoring program from the list and click save, it stays in the edit page with the old value.

**Comment by jponttuset** [comment]
Reading #1664 I saw that I could not have one of the phases without reference. Now it saves correctly.
