### ISSUE TITLE
can not download datasets 

### ISSUE THREAD

**Issue by Denybarros** [codalab/codalab-competitions#1658]
I tried downloading the dataset on MNIST digits challenge, but donwload link is broken. link is there any other alternatives?
https://competitions.codalab.org/competitions/4061?secret_key=5f73902b-9459-4ef9-b761-1ee00bc5df9c

**Comment by FlavioAlexander** [comment]
Hello @Denybarros In order to download datasets the competition needs to be published. Let me if the fixes your problem. 

Best,

Flavio
