### ISSUE TITLE
Azure replacement?

### ISSUE THREAD

**Issue by dkarasopi** [codalab/codalab-competitions#1660]
Is it possible to run CodaLab without Microsoft Azure?

Documentation doesn't mention this possibility and studying code reveals that Azure seems to be tightly-coupled with whole platform (for example: compute/worker.py uses BlobService to store blobs and replacing the functionality doesn't seem trivial).

Is there something I am missing?

**Comment by ckcollab** [comment]
That is true, the current version is tightly coupled. We may be designing a new version using the latest Django and Python versions and celery instead! Would that be fit your use case?

**Comment by dkarasopi** [comment]
It would indeed fit my case, but I am afraid I don't have that much time on my hands.

I should perhaps create separate issue for this, but I have a related question.
Is there an easy way to force CodaLab to use emulated Azure instead? 
From what I've seen in code (for example in azure_storage.py) I would have to find every service-related line like this:  

`self._connection = azure.storage.BlobService(
                self.account_name, self.account_key)`

Is there an easy way to achieve this without heavy modifications like this?

**Comment by ckcollab** [comment]
> Is there an easy way to achieve this without heavy modifications like this?

Again, no, unfortunately there is so much tight coupling in the code and so much spaghetti over the years that this would take a significant effort to do.. off the top of my head anyway. It could be more simple than I'm imagining, but I believe it'd be painful.

I'm hoping to do a significant refactor at some point, we'll see, what would the bare minimum specs be for your needs? User registration, competition CRUD, able to make submissions, leaderboard? I'm in the brainstorming stages for this right now so I'd love as much input as you'd like to give!

**Comment by dkarasopi** [comment]
Things that could be considered as bare minimum for my needs: user registration, competitions (including phases), custom evaluation scripts, leaderboards

**Comment by ckcollab** [comment]
> custom evaluation scripts

Like the "scoring program" in current codalab lingo, or something different?

**Comment by dkarasopi** [comment]
Yes, that'd be a "scoring program".

**Comment by ckcollab** [comment]
Thanks, appreciate the info! Think we can close this issue or do you have any more questions?

**Comment by dkarasopi** [comment]
That's all, thank you for your time.
