### ISSUE TITLE
Unable to edit competition

### ISSUE THREAD

**Issue by mk351** [codalab/codalab-competitions#1664]
Hi,

I'm unable to edit the pages in a competition. After submitting the changes, the page is not redirected to the competition page, and when I open the competition page, the changes are not reflected.

**Comment by FlavioAlexander** [comment]
@mk351 What happens when you press save, do you see any error? Does it take you back to the competition or stays in the form?

**Comment by mk351** [comment]
@FlavioAlexander Nothing happens, it appears to be working, but doesn't redirect to the competition page. When I open the competition page, it doesn't show the updates

**Comment by FlavioAlexander** [comment]
@mk351  🤔 So, it stays in the form. Try looking for some validation error within the form.

**Comment by mk351** [comment]
@FlavioAlexander I couldn't find anything directly, so I started removing elements to test. When I deleted one of the phases of the competition, I got this error:
Internal server error. Please file a bug report. For more information about CodaLab, check out the wiki.

**Comment by mk351** [comment]
I'm trying to build a multiple column leaderboard. Is there any possibility that that could be the issue?

**Comment by mk351** [comment]
@FlavioAlexander It worked. Thanks! I needed to add reference data to one of the phases. I was keeping the first phase for registration, so shouldn't the reference data and scoring algorithm be optional?

**Comment by FlavioAlexander** [comment]
@mk351 I am glad is working. Unfortunately, they are not. For some reason it does not throw errors during competition creation if you don't have a reference to any of them, but it would give you errors when editing the competition. Just keep in mind, you can always go back and change them.
