### ISSUE TITLE
Re-run all submissions button

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1665]
- [ ] Re-ran submissions have filename "Failed"?
- [x] Hitting back button while re-submitting dialogue "failed to re-run all submissions, make sure internet connection is working and if problem persists contact an admin" -- however when return to submissions shows new submissions successfully, no failure
- [ ] 'show/hide' buttons change file name to 'true/false', submission remains in view
- [ ] mark submission as 'failed' will show as failed in participation tab, however there is no way to 'pass' once it has already been failed. clicking 'failed' button again brings up dialogue "are you sure you want to mark this submission as failed?" again
- [ ] (user experience) after deleting a submission, brings back to the contest page intsead of back to the submissions pannel

**Comment by ckcollab** [comment]
Nice, good other bug finds but let's table those until we have time to get to them. Let's worry about bugs just related to re-running all submissions... these are good bugs though!

**Comment by ckcollab** [comment]
Merged to prod
