### ISSUE TITLE
Error 500 in submissions page

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1668]
Dear developers,
When I try to get into the submissions page: https://competitions.codalab.org/my/competition/16221/submissions/

I get a 500 error:
Internal server error. Please file a bug report. For more information about CodaLab, check out the wiki.

I also have a wrong submission that does not match the expected columns, as in: #1573 

Best,

**Comment by FlavioAlexander** [comment]
Hello @jponttuset I think the only way to bring the competition back to a normal state is by deleting the wrong submission. I can't think of anything else, @ckcollab do you have any other idea?

**Comment by jponttuset** [comment]
Hi @FlavioAlexander! Is this something I can do?
At this stage I don't mind deleting the whole competition and starting again (I already did a new one), but at later stages this could be problematic...

**Comment by FlavioAlexander** [comment]
In the long run, I think we should add the proper logic in the back-end to handle broken submissions.

**Comment by FlavioAlexander** [comment]
Hi @jponttuset Not really. I think you are better off by starting a new competition. Do not delete it for now, I would like to manually delete the submission and look into the logs to check how/why competition broke.

**Comment by jponttuset** [comment]
I think I know why it broke: I changed the key in the "scores.txt" without properly changing the expected column key in the competition.yaml. Same than #1573
