### ISSUE TITLE
Run Matlab in the scoring program?

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1670]
Is that possible?
If so, how should I call it?

Thanks!

**Comment by ckcollab** [comment]
You should be able to do pretty much anything in the scoring program, let me know if you have trouble!

**Comment by jponttuset** [comment]
I tried modifying the metadata file to:
`matlab -nodesktop -nosplash -nojvm -r "cd $program/..."`

And it told me it did not find the binary. How should I call matlab then?

**Comment by ckcollab** [comment]
Ah, I just assumed Matlab was installed, it does not appear to be installed on the compute workers... is this necessary to install for your competition?

**Comment by jponttuset** [comment]
Although it would be easier for us in Matlab, we can also run the evaluation in python, so if it's not installed, let's leave it like it is. I was just asking in case I had to simply change the call.
Thanks!

**Comment by ckcollab** [comment]
No problemo! Apologies it wasn't as easy as you were expecting :(
