### ISSUE TITLE
Results CSV should put ranks in separate fields

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1672]
CodaLab allows competition organizers to download a CSV containing the results of a phase.  The fields of this CSV contain a bunch of apparently extraneous numbers in parentheses.  For example:

```
User,F1,recall,precision,coverage,Description,Date,Filename,Is on leaderboard?
""
user001,1.0000 (1),0.2732 (14),0.2732 (14),0.2732 (14),,2017-01-18 03:15:03+00:00,homs_2.zip,True
user002,1.0000 (1),0.2775 (13),0.2775 (13),0.2775 (13),,2017-01-18 10:05:54+00:00,WSDse.zip,True
user003,1.0000 (1),0.3348 (11),0.3348 (11),0.3348 (11),,2017-01-20 11:09:21+00:00,output.zip,True
user004,1.0000 (1),0.4462 (6),0.4462 (6),0.4462 (6),,2017-01-20 15:34:03+00:00,answer.txt.zip,True
user005,1.0000 (1),0.3149 (12),0.3149 (12),0.3149 (12),,2017-01-21 17:03:21+00:00,hom2.zip,False
user006,1.0000 (1),0.3373 (10),0.3373 (10),0.3373 (10),,2017-01-21 18:38:38+00:00,answer.zip,True
user005,1.0000 (1),0.3410 (9),0.3410 (9),0.3410 (9),,2017-01-21 19:09:37+00:00,homw2v.zip,True
user007,1.0000 (1),0.4648 (5),0.4648 (5),0.4648 (5),Baseline,2017-01-22 14:11:13+00:00,answer.zip,False
user007,1.0000 (1),0.5215 (4),0.5215 (4),0.5215 (4),Baseline2,2017-01-22 19:01:50+00:00,answer.zip,True
user008,1.0000 (1),0.4400 (7),0.4400 (7),0.4400 (7),,2017-01-22 20:42:13+00:00,answer.txt.zip,False
user009,0.9994 (2),0.6526 (2),0.6521 (2),0.6523 (2),,2017-01-22 22:21:57+00:00,answer.zip,True
user010,0.9988 (3),0.6636 (1),0.6627 (1),0.6631 (1),,2017-01-22 13:12:35+00:00,answer.zip,True
user009,0.9975 (4),0.6519 (3),0.6503 (3),0.6511 (3),,2017-01-22 23:54:07+00:00,answer2.zip,False
user008,0.9913 (5),0.3679 (8),0.3647 (8),0.3662 (8),,2017-01-22 20:09:40+00:00,answer.txt.zip,True
```

Note all the extra `(1)`, `(14)`, etc. in the columns.  I'm not sure what the purpose of these numbers is, but they're not output by my scorer.  And they make it impossible to use the cell values as-is; I first need to remove them.

**Comment by logological** [comment]
From reading the source code in [`codalab/apps/web/views.py`](https://github.com/codalab/codalab-competitions/blob/master/codalab/apps/web/views.py) it looks like the number in parentheses is supposed to be the rank.  I guess this is useful information, but it really needs to go into its own comma-delimited field, not appended onto an existing one.

**Comment by FlavioAlexander** [comment]
Hello @logological Yeah, those numbers are supposed to be ranks. I have always found those parenthesis to be annoying, so I think I like the idea of adding an extra column for the ranking.

**Comment by ckcollab** [comment]
I believe you can turn this off via the setting:

![image](https://cloud.githubusercontent.com/assets/2185159/22902203/1f5c1880-f1e9-11e6-9bff-7c9bf6390d3c.png)
