### ISSUE TITLE
Results CSV contains extraneous header rows

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1673]
CodaLab allows competition organizers to download a CSV containing the results of a phase. The first row of the CSV consists of a single field, `Results`.  The third row of the CSV is the header row containing the column labels.  The fourth row is always `""`.  The actual results do not start until the fifth row.  Example:

```
Results

User,F1,recall,precision,coverage,Description,Date,Filename,Is on leaderboard?
""
user001,1.0000 (1),0.2732 (14),0.2732 (14),0.2732 (14),,2017-01-18 03:15:03+00:00,homs_2.zip,True
user002,1.0000 (1),0.2775 (13),0.2775 (13),0.2775 (13),,2017-01-18 10:05:54+00:00,WSDse.zip,True
```

The presence of this first, second, and fourth rows makes the file inconvenient to process with automated CSV processing tools, most of which assume that the header (if present) is always on the first row, and that the data begins immediately afterwards.

**Comment by FlavioAlexander** [comment]
Hello @logological,

What would be your recommendation here? Just removing the extra headers. I haven't really used this feature, not sure how it should work or how organizers are using the data

**Comment by logological** [comment]
From reading the source code in [`codalab/apps/web/views.py`](https://github.com/codalab/codalab-competitions/blob/master/codalab/apps/web/views.py):

* The first line of the CSV is `group['label']`.  It looks like this is supposed to account for the case where there is more than one group of scores.  I have no idea if this is ever the case.
* The second line is always blank.  (The code is just `csvwriter.writerow([])`.)
* The third line is the headers, but they're not always printed in the correct order.  See Issue #1557.
* The fourth line is supposed to be subheaders, but I have no idea what those are.  The code implies that every header can have 0 or more subheaders, but the way they are currently written out on separate lines, there is no obvious relationship between the two.  (That is, there is no guarantee that a subheader will appear in the same column as its header.)

I can't really recommend what to do as I have no idea what the subheaders are for, or where they are defined, and I have no idea whether it's even possible for there to be more than one set of results in the CSV.

**Comment by logological** [comment]
Also just noticed that the CSV contains several blank lines at the end.  These could also be eliminated.

**Comment by ckcollab** [comment]
Not the best solution, but maybe you could get decent CSV file usage just trimming off the unnecessary lines?

**Comment by logological** [comment]
Yes, that's what I'm currently doing as a workaround.  It would just be nice if it weren't necessary to preprocess the file.

**Comment by ckcollab** [comment]
> It would just be nice if it weren't necessary to preprocess the file.

I agree, you're right. 

Hopefully we're doing a revamp of Codalab soon, we'll definitely make the file formats easier to process. I'm not sure why it's setup the way it is, but to maintain backwards compatibility I'm hesitant to change it at this point.

**Comment by ckcollab** [comment]
Closing this issue for now, please let me know if you have more questions!
