### ISSUE TITLE
Pressing "+" on the Submissions page jumps to top of page

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1674]
In each row of the table on the Submissions page is a "+" button that, when pressed, reveals some download links for the submission.  Unfortunately, pressing it also causes the browser to jump back to the top of the page.  Along with Issue #1632, this makes it extremely inconvenient to download all the submission data.

The reason for the behaviour is that the target of the "+" link is `#`.  It would be better if the target were instead `#xxxxx`, where *xxxxx* is the value of the `id` attribute of the `tr` element containing the link.

**Comment by ckcollab** [comment]
That bug is very annoying! Thanks for fixing it.
