### ISSUE TITLE
"Download CSV" button returns blank page instead of CSV

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1676]
When a phase's "Leaderboard mode" is set to "Hide results", following the "Download CSV" link on the "Submissions" page returns a blank page instead of a CSV (even when there are several "Finished" submissions to that phase).  This behaviour is confusing.  I don't think it makes sense for "Hide results" to prevent the task organizer from downloading the results CSV.  But even if it does, the proper way of doing this would be to remove the "Download CSV" link altogether (or better yet, replace it with a message that results are not downloadable because "Hide results" has been set).

**Comment by ckcollab** [comment]
This should be fixed now, let us know if it's not
