### ISSUE TITLE
Baselines in the Leaderboard

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1678]
Dear developers,

Is there a way of adding some "baselines" to the Leaderboard by the organizers (as in Kaggle competitions). That is, multiple entries by the organizers that are marked differently and help participants to know how good are they. I could create one user per baseline, but that's not very elegant...

Thanks!

**Comment by ckcollab** [comment]
> I could create one user per baseline, but that's not very elegant...

Unfortunately, this may be your only option to display it *on* the leaderboard. You could modify one of the competition detail pages to display this information, though? 

For example: gold star for score > 1, bronze for < 1, or a lump of coal for < 0 😆

**Comment by jponttuset** [comment]
Ok, thank you!

**Comment by benbuleong** [comment]
@ckcollab : Is there a way to now actually have multiple entries by the same team displayed as different rows in the same results table with the latest, updated version of CodaLab?
