### ISSUE TITLE
Adding webpages in edit competition

### ISSUE THREAD

**Issue by felipebravom** [codalab/codalab-competitions#1690]
Hi,
I'm trying to add new webpages in the Edit competition menu but they are not being displayed after clicking the submit button.  Any feedback would be appreciated.
Regards,
Felipe

**Comment by FlavioAlexander** [comment]
Hello @felipebravom, 

Are you able to save? Does clicking in ```save/submit``` takes you the main page or stays in the edit page?

**Comment by felipebravom** [comment]
Thanks for your prompt reply. It stays in the edit page after submitting.

**Comment by ckcollab** [comment]
Is there an error somewhere @felipebravom? It should be forwarding you to the main competition page if there aren't errors.

**Comment by felipebravom** [comment]
Nop, I don't see any errors being displayed.

**Comment by ckcollab** [comment]
Not sure what the problem could be, if it's not saving there should be errors displayed somewhere? Are you sure you're not missing them? Often times they aren't styled well and don't stand out, so you have to read carefully.... we'll hopefully be changing this soon so the errors are more apparent.

**Comment by felipebravom** [comment]
I'm really don't seeing any errors. I tried adding a Webpage with an empty title and in that case the error is clearly displayed, but again when I add a valid page and press the submit button I'm staying in the Edit menu, the new page is still there, but is not observed when I come back to the main competition page.

**Comment by ckcollab** [comment]
@felipebravom Would you mind hopping in a chat where you can share your screen?

I'll be waiting in [here](https://appear.in/help-felipe) for the next ~15 minutes so you can show me the problem, thanks!

**Comment by FlavioAlexander** [comment]
@felipebravom, 

I don't know if you continue to see the problem. Could you verify that `Reference data` is pointing to something? If that is not the case, it will fail silently sometimes
<img width="1006" alt="codalab_-_edit_competition_" src="https://cloud.githubusercontent.com/assets/7468482/23592015/76923956-01c8-11e7-8a79-695c2559cc07.png">

**Comment by ckcollab** [comment]
@FlavioAlexander he showed me and all he did was add the page. If he clicks "submit" without adding the page, no problem is shown :(

I think django form errors just aren't being shown, I'll try to push a fix for future folks. I think the best answer now, unfortunately, is to just re-make the competition with this new page already added :(

**Comment by FlavioAlexander** [comment]
🤔 I still will double check if the reference mentioned above is missing, just in case. I have seen errors because of that and sometimes before of the scoring program. I haven't been able to find anything on the logs

**Comment by ckcollab** [comment]
So it looks like `Page`s were expecting some `PageContainer` when they were created, I removed that field on the staging server and that seems to have fixed it!

@felipebravom so unfortunately, the error is fixed but it may not end up on production for a little while, we already have a huge backlog of things to QA... but in the future it will be fixed!

**Comment by felipebravom** [comment]
Thanks @ckcollab and @FlavioAlexander ! I will create a new competition my the new pages then. 
Cheers.
