### ISSUE TITLE
Additional info for the submissions

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1692]
I've seen that in MS COCO, one has to add additional information such as "Team name", "Method name", etc. but I did not manage to see how to add them in my competition.
Is this feature documented somewhere?

**Comment by FlavioAlexander** [comment]
Hello @jponttuset, 

You have to enable this feature using the Editor. 
![codalab_-_edit_competition](https://cloud.githubusercontent.com/assets/7468482/23615343/14241ee2-0254-11e7-9c75-88296dcd60f8.png)

**Comment by jponttuset** [comment]
Ok, thanks!
Maybe you could consider putting a more descriptive name? :)

**Comment by FlavioAlexander** [comment]
Thanks for the suggestion. Probably @ckcollab could think of a better name because I can't think of anything 😉

**Comment by jponttuset** [comment]
Sorry if that did not sound constructive.
I can suggest adding a sentence in parentheses:
(Team name, Method name, Method description, etc.)

**Comment by ckcollab** [comment]
@jponttuset I will do this right now 👍

**Comment by FlavioAlexander** [comment]
Thanks Eric 👍

**Comment by ckcollab** [comment]
![image](https://cloud.githubusercontent.com/assets/2185159/23622299/f6c924d8-0252-11e7-8432-2cc9848072b9.png)

**Comment by jponttuset** [comment]
Thanks, I think it's clearer now 👍
