### ISSUE TITLE
leaderboard empty despite submissions

### ISSUE THREAD

**Issue by bethard** [codalab/codalab-competitions#1693]
I added a new phase, but the leaderboard is not displaying, despite the presence of submissions marked as True for display on the leaderboard. If you look at:

https://competitions.codalab.org/competitions/15621#results

You can see the leaderboards for the Trial, Unsupervised Domain Adaptation, and Supervised Domain Adaptation phases. But for the Post-Competition phase, for which I have 12 submissions (with 4 of them marked as to be posted to the leaderboard), nothing shows up.

I don't know if it's significant or not, but the Post-Competition phase was added via the web interface, while all other phases were added via the competition.yaml.

What can I do to get the leaderboard for the new phase to show up?

**Comment by ckcollab** [comment]
Does the problem persist if you create all of the phases via the yaml file? Unfortunately it's probably a bug deep within some old leaderboard code, would take me a bit to track it down and we've got a backlog already. In the next couple weeks I may take a look at this more deeply.

**Comment by bethard** [comment]
How can I upload a new yaml to an existing competition? The shared task has already run, so I can't delete and recreate the competition, or I'll lose all the participant data, right?

**Comment by ckcollab** [comment]
Apologies for the delayed response, you have to (unfortunately) create a whole new competition to apply `competition.yaml` changes :(

**Comment by bethard** [comment]
Okay, then since that's not possible, is there anything I can do with my competition to help debug where the old leaderboard code is going wrong?

**Comment by madclam** [comment]
We need to clean that up in version 2. Unfortunately we will not have time for V1.5.
