### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by gchrupala** [codalab/codalab-competitions#1701]
I have two competitions currently running on codalab. Everything worked until today, when submitting the result gives this error:
/home/azureuser/anaconda/bin/python: can't open file '/codalabtemp/tmpYDm3bo/run/program/evaluate.py': [Errno 13] Permission denied

Link to one of the affected competitions: https://competitions.codalab.org/competitions/16385?secret_key=ea1b548c-00b6-43b8-98c1-c702b386e07a

**Comment by ckcollab** [comment]
Is this still happening? It was due to a restart for configuration changes that another competition needed

**Comment by gchrupala** [comment]
Working now, thanks.

**Comment by ckcollab** [comment]
Woo! cool, thanks
