### ISSUE TITLE
Team creation

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1724]
- [ ] Allow request box still unsolved. See below. 

I tried on the following staging servers:
https://competitions-test.codalab.org
http://13.82.145.119/
http://13.90.249.6/

I could only get it to work on the See.4C server:
https://competitions.see4c.eu/

**Comment by ckcollab** [comment]
@xbaro any ideas on this one?

**Comment by madclam** [comment]
In re-testing that, I found another problem:
![image](https://user-images.githubusercontent.com/7594063/30732018-66013a56-9f25-11e7-8fd5-d3b6ecfdd5b2.png)
The check box "allow request" does not work.

**Comment by madclam** [comment]
Note: I closed this old issue about teams that seems obsolete https://github.com/codalab/codalab-competitions/issues/514

**Comment by ckcollab** [comment]
@madclam pushed a fix for this (I believe) to the 119 test server

Other improvements:
- Fixed up some code styling
- Changed redirect to go from "team edit" to "team list" page
- Changed form from manual table to `as_table` automatic generation

**Comment by ckcollab** [comment]
I believe this is fixed
