### ISSUE TITLE
submission rerun does not work

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1732]
In the new version of Codalab, e.g.
https://competitions.see4c.eu
it is impossible to re-run submissions from the submission panel.
The symptom is that the submission is replaced by "None".

![image](https://cloud.githubusercontent.com/assets/7594063/25293225/2cc73d26-26da-11e7-9480-e68e5747cb78.png)

**Comment by ckcollab** [comment]
Pushed a fix for this to the `develop`
