### ISSUE TITLE
Fail submission is sent back to the compute workers

### ISSUE THREAD

**Issue by xbaro** [codalab/codalab-competitions#1733]
When in the submissions view of a competition the organizer selects "Fail", the submission becomes "Failed", but the compute worker receives it again. It seems that is not removed from the queue.

**Comment by ckcollab** [comment]
> When in the submissions view of a competition the organizer selects "Fail"

What do you mean? Where does the organizer select that -- can you add a screenshot? Thanks!

**Comment by dragonlocke** [comment]
fail button on submissions admin page^

**Comment by ckcollab** [comment]
> "This bug was just that when you try to stop a running evaluation with the "administration fail button", it starts being evaluated again by a compute worker."

**Comment by Tthomas63** [comment]
@ckcollab and I talked about this, and I was unable to reproduce a bug/error with compute workers and submissions, even under high stress conditions and failing the submission before the compute worker receives it, or while it is running.

8 Submissions, failing submissions: 
http://i.imgur.com/iJuOILi.gifv

64 Submissions, failing submissions:
http://i.imgur.com/jBqV7Wi.gifv

128: Submissions, failing submissions: 
http://i.imgur.com/S4dQiqH.gifv

If you see something I have overlooked please let me know.
Thanks.
