### ISSUE TITLE
Queues selection changed because admin rights.

### ISSUE THREAD

**Issue by xbaro** [codalab/codalab-competitions#1734]
When a organizer A of a competition creates a new queue (not public) and assign it to a competition, if other organizer B of the competition modifies anything else, if the organizer B is not in the list of people that can use the queue, this is changed to default automatically.

Is it possible that when an organizer enters to the edit view of the competition, the current queue is added to the list of available queues temporally?  It should be something similar to the datasets for evaluation scripts and reference data.

**Comment by dominiquemb** [comment]
Pull request: https://github.com/codalab/codalab-competitions/pull/1773

**Comment by dragonlocke** [comment]
case closed
