### ISSUE TITLE
Error on submission visualization

### ISSUE THREAD

**Issue by xbaro** [codalab/codalab-competitions#1735]
After apply the last changes on the develop branch, when I try to show my submissions in a competition, there is an Error 500.  

The error is produced when the frontend calls the following url:
https://competitions.see4c.eu/competitions/3/submissions/5?_=1493193617508

The logs in the server are:
django            | 2017-04-26 08:00:08,997 ERROR Internal Server Error: /competitions/3/submissions/5
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
django            |     return bound_func(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
django            |     return view_func(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
django            |     return func(self, *args2, **kwargs2)
django            |   File "/app/codalab/apps/web/views.py", line 124, in dispatch
django            |     return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
django            |     return handler(request, *args, **kwargs)
django            |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 154, in get
django            |     context = self.get_context_data(**kwargs)
django            |   File "/app/codalab/apps/web/views.py", line 607, in get_context_data
django            |     'filename': submission.get_filename(),  # left as call for legacy update of readable_filename on subs.
django            |   File "/app/codalab/apps/web/models.py", line 1226, in get_filename
django            |     self.save()
django            |   File "/app/codalab/apps/web/models.py", line 1150, in save
django            |     self.readable_filename = split(self.s3_file)[1]
django            |   File "/usr/local/lib/python2.7/posixpath.py", line 85, in split
django            |     i = p.rfind('/') + 1
django            | AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by ckcollab** [comment]
I think this may be fixed?

**Comment by ckcollab** [comment]
Closing this one, as I am pretty sure this `readable_filename` bug should be fixed, let me know if it pops up again!
