### ISSUE TITLE
Submission failed without meaningful error

### ISSUE THREAD

**Issue by LishengSun** [codalab/codalab-competitions#1736]
Hi,

We have made a submission to this challenge (https://competitions.codalab.org/competitions/15525), it failed without outputting any meaningful message. Could you please see what happened? Thank you!

Here is the detailed information:
Number: 189
Submitted: April 28, 2017, 7:55 a.m.
Submitted by: cherry
Submission id: 399130
Filename: sample_submission_17-04-28-09-53.zip

**Comment by ckcollab** [comment]
Is this competition public yet? I couldn't access it.

Could you send me (eric@ckcollab.com) the submission that is broken, and if possible the competition bundle? 

Thanks!

**Comment by madclam** [comment]
Let's give up on this, the class is terminated.
