### ISSUE TITLE
create a virtual environment to mimic Codalab 

### ISSUE THREAD

**Issue by LishengSun** [codalab/codalab-competitions#1738]
Hi Eric,

I would like to create a virtual environment to mimic the Codalab environment that we have used for AutoML challenge (2016). Following is the platform information that I get from 'predict output log' associated with the AutoML submission (https://competitions.codalab.org/my/competition/submission/397790/predict_stdout.txt):

```
abstract-rendering==0.5.1
alabaster==0.7.6
anaconda-client==1.1.0
appdirs==1.4.0
argcomplete==1.0.0
astropy==1.0.5
babel==2.1.1
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.1
bitarray==0.8.1
blaze==0.8.3
bokeh==0.10.0
boto==2.38.0
bottleneck==1.0.0
cdecimal==2.3
cffi==1.2.1
clyent==0.4.0
colorama==0.3.3
conda-build==1.18.1
conda-env==2.4.4
conda==3.18.3
configobj==5.0.6
cryptography==0.9.1
cython==0.23.4
cytoolz==0.7.4
datashape==0.4.7
decorator==4.0.4
docutils==0.12
enum34==1.0.4
fastcache==1.0.2
flask==0.10.1
funcsigs==0.4
gevent-websocket==0.9.3
gevent==1.0.1
greenlet==0.4.9
grin==1.2.1
h5py==2.5.0
idna==2.0
ipaddress==1.0.14
ipykernel==4.1.1
ipython-genutils==0.1.0
ipython==4.0.0
ipywidgets==4.1.0
itsdangerous==0.24
jdcal==1.0
jedi==0.9.0
jinja2==2.8
jsonschema==2.4.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
jupyter==1.0.0
llvmlite==0.7.0+3.g1ec568f
lxml==3.4.4
markupsafe==0.23
matplotlib==1.4.3
medpy==0.2.2
mistune==0.7.1
multipledispatch==0.4.8
nbconvert==4.0.0
nbformat==4.0.1
networkx==1.10
nibabel==2.1.0
nltk==3.1
nose==1.3.7
notebook==4.0.6
numba==0.21.0
numexpr==2.4.4
numpy==1.12.0
odo==0.3.4
openpyxl==2.2.6
packaging==16.8
pandas==0.17.0
path.py==0.0.0
patsy==0.4.0
pep8==1.6.2
pexpect==3.3
pickleshare==0.5
pillow==3.0.0
pip==9.0.1
ply==3.8
psutil==3.2.2
ptyprocess==0.5
py==1.4.30
pyasn1==0.1.9
pycocotools==2.0
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.1
pyflakes==1.0.0
pygments==2.0.2
pyopenssl==0.15.1
pyparsing==2.1.10
pytest==2.8.1
python-dateutil==2.4.2
pytz==2015.6
pyyaml==3.11
pyzmq==14.7.0
qtconsole==4.1.0
redis==2.10.3
requests==2.8.1
rope==0.9.4
scikit-image==0.11.3
scikit-learn==0.16.1
scipy==0.16.0
setuptools==18.4
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.0
sockjs-tornado==1.0.1
sphinx-rtd-theme==0.1.7
sphinx==1.3.1
spyder==2.3.7
sqlalchemy==1.0.9
statsmodels==0.6.1
sympy==0.7.6.1
tables==3.2.2
terminado==0.5
theano==0.7.0
toolz==0.7.4
tornado==4.2.1
traitlets==4.0.0
ujson==1.33
unicodecsv==0.14.1
werkzeug==0.10.4
wheel==0.26.0
xlrd==0.9.4
xlsxwriter==0.7.7
xlwt==1.0.0

```

I prefer conda environment or virtualenv than docker, because docker is not installed on our server. Of course, if it is easier with docker, I can maybe contact the admin of our server to install docker?

If you need more information, please let me know.

Thank you in advance!

**Comment by madclam** [comment]
Hi Eric,

To translate what Lisheng is saying, following our teleconference of today: when we transition to the docker version of Codalab in production, we want to create a docker for the current version of the Codalab production compute workers. We want then to create a queue where all the old competitions with code submission get directed, using that docker.
Could you create such a docker. I believe we have the scripts that construct compute workers for the current production version of Codalab. Those could be used to create a docker image.
Best,

Isabelle

**Comment by ckcollab** [comment]
All of the things on the old version of Codalab, that I can think of and after going through the provisioning script:

1. Anaconda (Anaconda2-2.4.0)
2. Java (jdk-7)
3. KHIOPS (do you need this? not sure I even have it anymore)
4. MSCOCO (do you need this?)
5. R (which version would you prefer? we're just apt-get installing it so the version may vary..)

Is there anything I am missing? 

Thanks!

**Comment by LishengSun** [comment]
Hi Eric,

I am sorry but all I know about what I need is included in the list in the first post. However, there are some error in the package names. I am working on it now. I will update it once I fix it.

Thank you!

**Comment by LishengSun** [comment]
Hi Eric,

I closed this issue. Because I have built a conda env by myself on our server for this purpose. I have logged all steps here (https://sites.google.com/a/chalearn.org/modelselection/automl_paper) in the file 'create_Codalab-AutoML-env_on_tipi.txt'. You can take a look if it interests you.

Thank you !
