### ISSUE TITLE
Search Competitions not displayed for logged-in users

### ISSUE THREAD

**Issue by logological** [codalab/codalab-competitions#1740]
When visiting CodaLab Competitions while logged out, the navigation bar contains a "[Search Competitions](https://competitions.codalab.org/competitions/)" link.  Following this link takes you to a page where you can enter a search query to find competitions by keyword.

However, the "[Search Competitions](https://competitions.codalab.org/competitions/)" link is missing from the navigation bar once you log in.  As far as I can tell, this makes it impossible to search for competitions when logged in.

**Comment by madclam** [comment]
Thanks, we'll add that to version 2.
