### ISSUE TITLE
Turn on/off special style [see.4c]

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1747]
Admin editor can turn on/off special style. (special admin page to set up single competition mode)

**Comment by dragonlocke** [comment]
![image](https://cloud.githubusercontent.com/assets/25310715/26023996/4518910a-377d-11e7-8b94-edfc6cc72519.png)
Is this what is implied by special style? If not is it in the competition edit page? Also is it on 

https://competitions-test.codalab.org/ or http://docker-server.lri.fr/ ?

**Comment by dragonlocke** [comment]
Found in http://docker-server.lri.fr/

Page currently not functional, submitting a style change results in error page.

**Comment by ckcollab** [comment]
@dragonlocke I believe this is fixed now?

**Comment by dragonlocke** [comment]
-uploading image works
-uploading new image over previous image works

However:
-can't upload competitino still, therefore cannot test single competition mode
-clear image tickbox next to the uploaded image if checked and saved results in error page

![image](https://cloud.githubusercontent.com/assets/25310715/26080039/aed527d6-3979-11e7-84bf-81bb958cbee1.png)

**Comment by dragonlocke** [comment]
case closed
