### ISSUE TITLE
Fix old staging server for isabelle

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1748]
Fix old staging server for isabelle

**Comment by ckcollab** [comment]
@madclam finally fixed the problems on test server (reverted our attempt at fixing Azure problems), I believe it should be working fine now. Some things may be broken, not much time to click through and test all features.

**Comment by dragonlocke** [comment]
Its running.

if force best and force submission to leaderboard are both checked, submits most recent instad of best.

- refresh button (under submission upload) does not appear unless the page is refreshed. 

- Cannot delete queue, leads to server error page: https://competitions-test.codalab.org/queues/delete/8

-[instance of competition scoring broken] Could be something to do with the environment or the competition itself; however these files work on docker-stage) using the multiple answer competition bundle, the 'huge' and test files are not scoring. Will attach files.

**Comment by dragonlocke** [comment]
[competition.zip](https://github.com/codalab/codalab-competitions/files/998444/competition.zip)
[answer.zip](https://github.com/codalab/codalab-competitions/files/998445/answer.zip)
[answer.zip](https://github.com/codalab/codalab-competitions/files/998446/answer.zip)
[answer.zip](https://github.com/codalab/codalab-competitions/files/998447/answer.zip)
[answer.zip](https://github.com/codalab/codalab-competitions/files/998448/answer.zip)

**Comment by ckcollab** [comment]
> using the multiple answer competition bundle, the 'huge' and test files are not scoring. Will attach files.

Make sure you're using the right competition bundle -- didn't we just change the scoring program on an existing competition so it can handle the different kinds of answers?

**Comment by ckcollab** [comment]
> refresh button (under submission upload) does not appear unless the page is refreshed.

Fixed this, was using non-compressed JS without our changes -- removed that behavior so we shouldn't even need to compress JS any more, wahooo! @lotusgraham  :D

**Comment by dragonlocke** [comment]
- refresh button fixed

we changed the scoring program, yes, and made a new competition with the replaced program -- we were using this competition on docker earlier last week and the scoring was working fine. will know for sure once docker files are completing again to verify.

**Comment by dragonlocke** [comment]
- [ ] can't delete worker queues

**Comment by dragonlocke** [comment]
Case closed
