### ISSUE TITLE
Add a nice simple "top 3" type leaderboard,

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1752]
Add a nice simple "top 3" type leaderboard, like how Kaggle has. On competition detail page

**Comment by ckcollab** [comment]
# Some examples

Challenge winners, obviously not displayed until competition is over. Each dataset can have a winner.

![image](https://cloud.githubusercontent.com/assets/2185159/26219495/190a777c-3bc4-11e7-9c40-cb0f36d18848.png)

And some statistics

![image](https://cloud.githubusercontent.com/assets/2185159/26219486/09ee2f40-3bc4-11e7-82f5-5a37ee84115c.png)


This is more detailed than we want. All we really need is a Top 3 challengers and maybe another panel for some nice competition statistics.

**Comment by ckcollab** [comment]
Also, top is better than bottom! Maybe underneath the phase information:
![image](https://cloud.githubusercontent.com/assets/2185159/26219620/7ccc75e4-3bc4-11e7-8de2-3a2a4a0f3b95.png)
