### ISSUE TITLE
Add scheduling for phase-to-phase migrations via celery

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1756]
Add scheduling for phase-to-phase migrations via celery

**Comment by ckcollab** [comment]
There's already a view that gets pinged to execute this check, `/do_phase_migrations/` or some such

**Comment by ckcollab** [comment]
Overview:

1. Set celery to be in "beat" mode, I believe, which will cause it to execute scheduled task
2. Add a scheduled celery task that is ran every 5 minutes that calls the functions in the `do_phase_migration` view
3. Remove the `do_phase_migration` (people could call this and potentially DDoS codalab)

**Comment by Tthomas63** [comment]
#1824 PR is ready

![phase_migrations_celery_working](https://cloud.githubusercontent.com/assets/28552312/26748753/83162a74-47b5-11e7-922b-29682de5222d.png)

- Puts celery into beat mode
- Adds task to call phase migrations
- Schedules task every 5 minutes
- Removes old URL and view for phase migration check.

QA Instructions:
- [ ] Run docker
- [ ] Run `docker exec -it django python manage.py create_competition_zip --automigrate`
- [ ] Grab created competition from `codalab-competitions/codalab` and if necessary edit competition.yaml ( Dates/times of phases may help )
- [ ] Upload competition
- [ ] Run `docker logs -f worker_site`
- [ ] Submit to competition and watch logs.

**Comment by ckcollab** [comment]
@dominiquemb sorry should have asked earlier, where did you land on this one? Unable to test locally, but works on docker staging?

**Comment by dominiquemb** [comment]
@ckcollab Unable to test completely on my local, but @Tthomas63 said the logs looked correct, at least before the submission failed.  I believe it works on docker staging but @dragonlocke will have to confirm.

**Comment by ckcollab** [comment]
I'll say that's good enough for this one for now, thanks!
