### ISSUE TITLE
Merging changes into Codalab main branch.

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1759]
Incorporate all the changes made for the See.4C challenge into the Codalab main branch.
Merge See.4C new team registration and management (of quote #1).
Replacement of Azure service bus by open source queuing system.
Flexible choice of backend (not relying Azure, including See.4C, custom servers, Azure, AWS)
Flexible choice of storage (not relying on Azure)
Docker support (of quote #1 and 4)
UI improvements (of quote #2).
Personalized website (of quote #3).

**Comment by ckcollab** [comment]
This is basically already done, all that I'd like to do is fix whatever Team bugs are remaining -- I think that's it?

This is different from the push to production, right?

**Comment by ckcollab** [comment]
Believe this can be closed up with the team image fix by Dominique
