### ISSUE TITLE
Review benchmarks, stress test [see.4c]

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1760]
A. Run benchmarks provided by See4C on AWS servers equipped with GPUs.
B. Review the instructions and stress test the system end-to-end.

**Comment by dragonlocke** [comment]
coordinate when 3 or more of us can be hammering submissions at the same time

**Comment by ckcollab** [comment]
We need to wait until next sprint to do this, servers not ready yet

**Comment by ckcollab** [comment]
Got some details on this, ran some very very very simple stress tests.
