### ISSUE TITLE
Wrong link substitution by editor

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1761]
The competition editor does wrongly something "smart":
it replaces links of the type:
https://competitions.codalab.org/competitions/7471
by
../7471
automatically.
This is then interpreted as:
https://competitions.codalab.org/7471
by the web browser, which leads to a 404 error!

An example can be seen at
https://competitions.codalab.org/competitions/2321
in the overview page

<ul>
<li><a href="../7471">Round 0: Sample data.</a></li>
<li><a href="../7462">Round 1: Novice level. binary classification problems, dense data.</a></li>
<li><a href="../7461">Round 2: Intermediate level. Multi-class classification, dense data.</a></li>
<li><a href="../7451">Round 3: Advanced level. Multi-class and multi-label classification, dense and sparse data.</a></li>
<li><a href="../9031">Round 4: Expert level. Everything else plus regression.</a></li>
</ul>

**Comment by ckcollab** [comment]
I can't replicate this? I am able to put these values into the HTML editor:

* https://competitions.codalab.org/competitions/7471
* https://competitions.codalab.org/competitions/7471 (as an actual link)
* https://competitions.codalab.org/competitions/7471 (as a custom link via the link creation button)

**Comment by ckcollab** [comment]
@dragonlocke if you get some free time could you try replicating this error?

**Comment by dragonlocke** [comment]
Can confirm, essentially what is happening is that the links out are not inserting /competitions/.. before the competition phase address ex. /7471

 This could be the links were manually entered incorrectly, or if it relies on an algorithm to generate links, it needs to insert /competitions/.

**Comment by ckcollab** [comment]
How did you replicate this!? I couldn't make the problem happen.. hmm...

**Comment by ckcollab** [comment]
Added this to an HTML file uploaded in a competition bundle, this works as well....!

```html
<a href="https://competitions.codalab.org/competitions/7471">test link</a>
```
