### ISSUE TITLE
Move BeatSKLearn to prod

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1764]
- grab original bundles from Azure
- submissions/ resources/ etc

**Comment by ckcollab** [comment]
Competitions test server has many valuable competitions and submissions on it, we should preserve this information and move the old competition test server data to docker staging...?

**Comment by Tthomas63** [comment]
I believe this is currently the case @ckcollab?

**Comment by ckcollab** [comment]
Beat AutoSK Learn -- dump this and move it to production?

https://competitions-test.codalab.org/competitions/1133

Do as best as you can to match users to submissions?

**Comment by madclam** [comment]
Can we at least make sure we can save the competition dump (ie upgrade competition-tests to v1.5). Also this issue is related to: https://github.com/codalab/codalab-competitions/issues/1632. If we could download all the submissions, we could -re-upload them.
