### ISSUE TITLE
Worker queues broker URL should be public facing IP...

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1771]
![image](https://cloud.githubusercontent.com/assets/2185159/26075037/b3b2c22e-3968-11e7-83f2-88e5495b4aca.png)

Notice how the URL is `rabbit` (`@rabbit:20000`)  instead of `docker-server.lri.fr`

**Comment by dominiquemb** [comment]
Created a pull request: https://github.com/codalab/codalab-competitions/pull/1772
