### ISSUE TITLE
Ensure legacy competition stability

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1779]
Ensure legacy competitions work accordingly, and that dockers are set up for them if need be. Re-running entries of AutoML clones http://automl.chalearn.org/. (example clone: https://competitions.codalab.org/competitions/7471 -- can re-run submissions here and all the other Rounds; also download submission manually and re-run it; resubmit sample competition https://www.dropbox.com/s/g2looqmox3lxz5y/iris_bundle.zip?dl=0)

**Comment by ckcollab** [comment]
Also pending some Lisheng testing

**Comment by ckcollab** [comment]
We need to test Lisheng's candidate default docker to see whether it is suitable for the other competitions.

**Comment by ckcollab** [comment]
What is the name of the new docker image @LishengSun? Thanks!

**Comment by LishengSun** [comment]
Hi Eric,

My image is 'lisesun/codalab_automl2016' (https://hub.docker.com/r/lisesun/codalab_automl2016/). Please use the last version (3.0 for now), because I keep installing more packages as I test it on more submissions.

**Comment by ckcollab** [comment]
Thanks! Do you remember why that didn't work instead of this one:

https://github.com/codalab/docker-codalab-legacy-worker/blob/master/Dockerfile

That is how the actual servers were spun up (anaconda and Java wise, anyway, some other misc things not included like mscoco and khiops).

**Comment by madclam** [comment]
Need to prepare and test docker for release of v1.5. https://github.com/codalab/codalab-competitions/issues/1885. Support Java and Scala?

**Comment by LishengSun** [comment]
Hi Eric,

Sorry for the late reply. I found this email (August) where I described the problem of this docker (https://github.com/codalab/docker-codalab-legacy-worker/blob/master/Dockerfile): 

> 1) docker image: I have cloned the AutoML2016 competition (round 0 http://docker-server.lri.fr/competitions/1465#participate-submit_results) for testing. And I have chosen continuumio/anaconda:4.4.0 as docker image to run the submissions. I have tested this image locally it works fine, but it doesn't provide the same environment as AutoML2016, this can be one of the reasons that caused the test failures, even I don't think it's the main reason. I don't know if you have built any docker image that represent the AutoML2016 environment (https://competitions.codalab.org/competitions/7471), if you have, can you please share it with me and I will retest when I come back. 

> 2) Test failures: I have uploaded another submissions "brunoseznec-1-input.zip", but it failed because of the same error that Tyler pointed out last time:
`Traceback (most recent call last):
  File "/tmp/codalab/tmpO3JJy1/run/program/run.py", line 193, in 
    import data_io                       # general purpose input/output functions
ImportError: No module named data_io`

> But this submission, as well as the submissions I sent you before, are downloaded directly from the AutoML2016 competition, and they didn't have this error there. I can of cause change the code of submissions, but I am afraid that this is not the real cause. I will test more when I come back.


I don't know exactly why it didn't work as expected, I just rebuild my docker with exactly the same version of package as in AutoML2016 (for example, sklearn=0.16 and some special packages required by some participants' submissions.)

**Comment by madclam** [comment]
**From Lisheng:** 
There are 2 docker images: 
1) https://hub.docker.com/r/mfeurer/auto-sklearn/: this is the auto-sklearn official docker image, built by the auto-sklearn team (the auto-sklearn team, who is the winner of AutoML2016 challenge, has released their solution as a python package, easier to use than their original submission, it works with python3)

2) https://hub.docker.com/r/lisesun/codalab_automl2016/: this is the docker image I created to rerun all submissions of AutoML2016 challenge. It's python2. And it mimics the challenge environment, meaning it has elder scikit-learn (0.16), elder numpy, .... installed.

**Comment by ckcollab** [comment]
This image is what we've been using, and should be the default (I believe): `ckcollab/codalab-legacy`

I believe the `data_io` missing error is due to a misconfigured competition?
