### ISSUE TITLE
Front-end Improvement: Offset 'confirm' button in delete submission

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1785]
[cosmetic] Submission management: delete submission button is offset

When deleting a submission, the confirm button is offset, and looks unattractive

![delete submission](https://cloud.githubusercontent.com/assets/25310715/26237264/4a0e0554-3c29-11e7-8594-e87651159b77.png)

**Comment by dominiquemb** [comment]
Pull request: https://github.com/codalab/codalab-competitions/pull/1804

**Comment by dragonlocke** [comment]
case closed
