### ISSUE TITLE
Front-end Imporvement: resizable text boxes

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1786]
[Cosmetic] Text-boxes: Not locked to width of the container

Several of the text boxes on the site are not restricted to a width, and therefore the user is able to mess with the size/shape of them.
![txtbox](https://cloud.githubusercontent.com/assets/25310715/26237336/919e81c8-3c29-11e7-9574-e70017e0a9bc.png)

Textboxes that have this issue:
- [x] submission description on participate tab

- [x] forums page

- [x] teams description

- [x] participants manager - email participants

- [x] edit competition

**Comment by dominiquemb** [comment]
Pull request: https://github.com/codalab/codalab-competitions/pull/1803

**Comment by dominiquemb** [comment]
Use this PR instead: https://github.com/codalab/codalab-competitions/pull/1812

**Comment by dragonlocke** [comment]
Case closed
