### ISSUE TITLE
Front-end Improvements: competition editor pop-up ask to save changes when exiting page

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1787]
[Improvement] Competition editior: Ask to save changes upon exit

The change submit button is not conveniently located, and often i forgot to save the changes made to a competition via the editor several times before I realized the changes had not been applied. Upon trying to exit the page, it would be ideal to receive a confirmation if you would like to save these changes.

**Comment by ckcollab** [comment]
Pushing this change to docker test server

**Comment by dragonlocke** [comment]
case closed!
