### ISSUE TITLE
Front-end Improvement: Link back to competition page from all submenus

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1788]
[Improvement] Link back to competitions page from certain menus

There are a number of pages that do not have a link back to the competition. Pages that do not have this link are:

- [x] Participants manager

- [x] Edit competition

- [x] Team manager

**Comment by Tthomas63** [comment]
Return to competition link added to each page. 

282f8f6

![go_back_all](https://cloud.githubusercontent.com/assets/28552312/26273294/e3f61ef0-3ce1-11e7-9b93-9d4e3549d874.gif)

**Comment by ckcollab** [comment]
Also pushing to docker test server

**Comment by dragonlocke** [comment]
case closed
