### ISSUE TITLE
Front-end Improvements: Differentiate color between show/hide in submission manager

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1789]
[Improvement] Submission management: highlight shown or hidden status in different colors

it can be difficult to determine whether something is shown or hidden (A) until the page is refreshed if a selection is made. Also the filename of the submission is replaced with true/false, which may misrepresent what is happening there. Refer to (B) for suggested change. It may also be useful to auto refresh the page upon a selection.

A)
![showhide](https://cloud.githubusercontent.com/assets/25310715/26237517/55bca972-3c2a-11e7-892b-14b08a6e07ce.png)

B)
![showhide2](https://cloud.githubusercontent.com/assets/25310715/26237526/5cd5d986-3c2a-11e7-91e5-3048eba76c1c.png)

**Comment by dragonlocke** [comment]
True/ False naming

**Comment by dominiquemb** [comment]
See https://github.com/codalab/codalab-competitions/pull/1815

**Comment by dragonlocke** [comment]
Case closed!
