### ISSUE TITLE
Front-end Improvement: Fix 'clear' tickbox in teams feature

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1790]
[Bug] Teams edit: clear image tickbox does not clear image

After uploading an image in the teams tab, a large tickbox appears and the text 'clear' also appears a line below it (A). If the box is checked, and click submit, it leads to a dead page (B)

A)
![teams checkbox1](https://cloud.githubusercontent.com/assets/25310715/26237600/ad2eb9c0-3c2a-11e7-8dbc-4a5f8313ecba.png)
B)
![teams checkbox2](https://cloud.githubusercontent.com/assets/25310715/26237610/b824e552-3c2a-11e7-8dad-bc35006afeaf.png)

**Comment by dominiquemb** [comment]
See https://github.com/codalab/codalab-competitions/pull/1818

**Comment by dominiquemb** [comment]
I replaced the checkmark with a button that says "Remove Image". If you click it, it'll remove the image and show some text that says the image has been removed.  You still have to click submit in order to permanently remove the image, though.

I also added a small image preview so that people can see what the current image looks like.

**Comment by dragonlocke** [comment]
Case closed, great work!

**Comment by ckcollab** [comment]
Reopening this for QA

**Comment by dragonlocke** [comment]
<tested on docker stage>
selecting 'remove image' button does not remove image; however uploading a new image will change the image to the upload.

-cleared cache
-refreshed page, does not clear image
-ctrl+f5 does not clear image

**Comment by dominiquemb** [comment]
@dragonlocke Did you try saving after clicking "remove image"?

**Comment by dragonlocke** [comment]
Never got prompted, nor was there a button to do so, only a 'submit' button.

**Comment by dragonlocke** [comment]
Thought I had mentioned this before, but this is on the docker stage; was I supposed to be re-testing this on your private url @dominiquemb?
