### ISSUE TITLE
Front-end Improvement: Fix multiple submissions to leaderboard bug

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1791]
[Bug] submission management: capable of having multiple submissions from user on leaderboard if edits made in submissions to show score

when selecting to show a score from the submission management page, showing multiple scores will result in the most recent being selected, overriding anything else that was submitted previously (i believe this is normal behavior) however, if a submission is shown from the sub management page, and an additional submission is made to the leaderboard via participate tab, 2 submissions appear on the leaderboard for the same user. If return to submission manager and show/hide another item, will return to expected behavior

![mult sub leader](https://cloud.githubusercontent.com/assets/25310715/26237666/f7d2f9e6-3c2a-11e7-8f88-1a3dcd898ce1.png)

**Comment by Didayolo** [comment]
Is this still reproducible?
