### ISSUE TITLE
Front-end Improvement: Fix clearing organizers when editing a worker queue

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1792]
When editing a worker-queue, if organizers were designated, they are no longer and the entry space is blank, they need to be manually re-added. Organizers should persist in the organizer field.

**Comment by Tthomas63** [comment]
PR: #1817

Added one line to save many to many fields in the form. Fixes issue.

**Comment by dragonlocke** [comment]
As it appears, I see not an issue with this issue. Case closed.
