### ISSUE TITLE
Front-end Improvement: Top 3 leaderboard displayed

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1795]
Top 3 from leaderboard displayed on competition detail page, like Kaggle does or other similar “top 3” panels/cards like from Material UI

**Comment by ckcollab** [comment]
Duplicates #1752

**Comment by Tthomas63** [comment]
Pull Request: #1813

**Comment by Tthomas63** [comment]
New Pull Request: #1823 

Passed all tests and has no apparent bugs.

Pull Request #1813 has possible issues with branch history.

**Comment by dragonlocke** [comment]
If competition settings are set to ascending, graph only visualizes top score. 
https://ibb.co/gHfW7a

Top scores DO appear to the side (looks good!) 

On participate tab, graph is shown twice, (where it originally was, and also in its new place; should remove original place above uploaded submissions)

https://ibb.co/kK7ptF

**Comment by Tthomas63** [comment]
@dragonlocke
