### ISSUE TITLE
Add frontend feature to have "?"'s next to confusing features

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1797]
Create a user manual (manual is for end users: competition organizers, not participants) For example, how to create a competition and use the admin tools -- avoid verbose, have “?”’s on the site people can click to go straight to more details. Also do some documentation/mentioning of Chalab.

**Comment by madclam** [comment]
The user manual, I am taking care of it as part of documentation.

**Comment by madclam** [comment]
related to https://github.com/codalab/codalab-competitions/issues/1971. We need to check for broken documentation links.
