### ISSUE TITLE
V1.5 Test: Stress test and debug production

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1801]
Stress test and debug production to ensure that it is iron clad.
Adding here everything that has to do with backward compatibility, legacy competitions, and stress testing.

- [x] Move AutoSKLearn to prod server. https://github.com/codalab/codalab-competitions/issues/1764

- [x] Legacy competition stability https://github.com/codalab/codalab-competitions/issues/1779

**Comment by madclam** [comment]
We are now doing this jointly with developing the new See.4C testing tools. Eric is using "Beat AutoSKLearn" and "Round 3" of AutoML.

**Comment by ckcollab** [comment]
We were able to run ~1500 submissions in a couple hours across 4 workers

http://codalabprod-v15.eastus.cloudapp.azure.com/competitions/2
