### ISSUE TITLE
Figure out stress testing particulars

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1811]
- [x] What server?
- [x] What time (any un-opportune times?)
- [x] contact julio
- [x] contact xavier

**Comment by ckcollab** [comment]
Shot an email to get details on this -- blocked until response

**Comment by ckcollab** [comment]
Xavier replied, waiting on some billing stuff I think.

**Comment by ckcollab** [comment]
9-10th June says Xavier
