### ISSUE TITLE
Submission Errors 

### ISSUE THREAD

**Issue by kdportillo** [codalab/codalab-competitions#1816]
I am trying to run the following example as a trial of Codalab:

[https://github.com/bethard/semeval-codalab](https://github.com/bethard/semeval-codalab)

When I zip the submission folder and upload it, I get the following error: 
`Could not find submission file /codalabtemp/tmpdjvzsg/run/input/res/answer.txt`

I even made the path and placed answer.txt in `input/res` but am still getting the same error. Any suggestions are greatly appreciated. 

**FIXED: My original competition bundle had subdirectories in it that through off the path for finding my files**

**Comment by FlavioAlexander** [comment]
Closing because the issue is fixed
