### ISSUE TITLE
Submit to leaderboard: New submission does not stick

### ISSUE THREAD

**Issue by dragonlocke** [codalab/codalab-competitions#1827]
When selecting a new submission to submit to the leaderboard, it will mark that it has been submitted to the leaderboard. If there was already a submission on the leaderboard, however, if a new submission is marked to be submitted, the selection does not hold -- the original submission remains on the leaderboard and the new one does not get submitted. This is the case regardless of score.

**Comment by Tthomas63** [comment]
Unable to reproduce locally, discussing with @ckcollab
