### ISSUE TITLE
Running multiple tracks of a competition simultaneously

### ISSUE THREAD

**Issue by nkaushik1** [codalab/codalab-competitions#1828]
Hello,

We are trying to run a computer vision challenge with two possible tracks participants may enter-- is it possible to host both of these tracks from the same CodaLab competition? i.e. is it possible for participants to select a track to enter and submit their results to, and to have two leaderboards running simultaneously which both use different evaluation programs?

Thanks!

**Comment by ckcollab** [comment]
I believe we do have some functionality for multiple tracks as well as multiple leaderboards, but it is rather confusing to use and isn't well documented. It may be more simple in your case to have two separate competitions?
