### ISSUE TITLE
Using 'force_best_submission_to_leaderboard'

### ISSUE THREAD

**Issue by NLITASK** [codalab/codalab-competitions#1832]
When attempting to use "'force_best_submission_to_leaderboard" in a phase I get this error when creating the competition:

`Cannot resolve keyword 'force_best_submission_to_leaderboard' into field.`

Any idea how this can be used? 

Thanks!

**Comment by FlavioAlexander** [comment]
Hello @NLITASK, 

Try creating the competition without this flag, you can always change it from the editor. 

Best,

Flavio

**Comment by NLITASK** [comment]
Thanks for the quick reply @FlavioAlexander.

Unfortunately the option is not there in the editor.

The competition has "Force submission to leaderboard" which I already have enabled.

The problem is that if a user makes a worse submission, this is forced to the leaderboard and replaces their previous (better) submission.

Any solutions?

Thanks!

**Comment by ckcollab** [comment]
@NLITASK where are you trying to use this feature? I don't believe this is on production yet.

**Comment by NLITASK** [comment]
@ckcollab I'm using it on a competition we are running on CodaLab.org next week.

We have an anonymous leaderboard and would like each participant's best submission to stay on there.

Is there any chance this might go live soon?

Thanks!

**Comment by ckcollab** [comment]
Potentially by the end of next month this feature should be merged into production, we are doing sweeping changes and moving servers then.

**Comment by NLITASK** [comment]
Thanks for letting me know. It's also a good idea to include this in the documentation as the information was not easy to find.
