### ISSUE TITLE
Customizing submission metadata fields

### ISSUE THREAD

**Issue by nkaushik1** [codalab/codalab-competitions#1833]
Hello,

Is it possible to customize the submission page to include mandatory fields/a yes-no checkbox that participants must answer? Additionally, is it possible to publicly display this information and other metadata from the participants' submission, perhaps somehow in the "detailed results" column of the leader board?

Thanks!

**Comment by nkaushik1** [comment]
Additionally, how can we access each submission's metadata? The metadata file in output.zip only contains elapsed_time, but where can we see info about team name, method description, etc?

**Comment by ckcollab** [comment]
> Is it possible to customize the submission page to include mandatory fields/a yes-no checkbox that participants must answer? 

Unfortunately I don't think this will be possible, unless you self-host the competition and modify it that way.

> Additionally, is it possible to publicly display this information and other metadata from the participants' submission, perhaps somehow in the "detailed results" column of the leader board?

Potentially, the detailed results is a rather old feature that isn't very well documented -- to be honest I haven't touched it in quite a while, you may be able to get some interesting output this way though.

> Additionally, how can we access each submission's metadata? The metadata file in output.zip only contains elapsed_time, but where can we see info about team name, method description, etc?

If you download leaderboard results, they should contain this data, found this in the code:

```python
            user_profile_data = {
                'Organization': submission.participant.user.organization_or_affiliation,
                'Team Name': submission.participant.user.team_name,
                'Team Members': submission.participant.user.team_members,
                'Method Name': submission.participant.user.method_name,
                'Method Description': submission.participant.user.method_description,
                'Contact Email': submission.participant.user.contact_email,
                'Project URL': submission.participant.user.project_url,
                'Publication URL': submission.participant.user.publication_url,
                'Bibtex': submission.participant.user.bibtex,
            }
            user_profile_data_string = '\n'.join(['%s: %s' % (k, v) for k, v in user_profile_data.items()])
```

Hope this was helpful! :(
