### ISSUE TITLE
Creating Teams in Competition

### ISSUE THREAD

**Issue by huskyjo** [codalab/codalab-competitions#1842]
I am hosting competitions through Codalab and participants have been asking how to make teams. In other words, make it so more than a single account can make submissions on behalf of a Team (or however that would be done).

I did do a little digging around myself, but it still is not entirely clear to me how it works (and or if this is an option/ feature).

For instance, If you go into your account setting you are able to setup a team by specifying a team name and list members of the team. However, not clear how this links to specific competitions.

Also, when you attempt to make a submission it prompts you for the team name, but still need to figure out if this links back to the settings. If so, how does it work (like can all members access submissions, make a submission, etc.)?

The competitions links are the following:
https://competitions.codalab.org/competitions/16742
https://competitions.codalab.org/competitions/16745

Any information and or reference you can provide would be much appreciated. We plan on using Codalab more in the future, so learning such details would be of value to our participants + future competitions that we plan to host.

Best regards,
Joe

**Comment by Tthomas63** [comment]
Hello!

I’m new to this project, but after a bit of research it seems like using the teams section in your profile and downloading the submissions via `download all submission` is the best way to use teams right now.

In the zip file from `download all submissions` there should be a file named `team_names_and_members.text` which lists all teams setup this way, and their members. This does not limit submissions to one team-member, or anything other restrictions. 

![teams_zip](https://user-images.githubusercontent.com/28552312/27398816-cbcde90a-566f-11e7-840f-ee6b29fb6095.png)


Please let us know if you have any further questions
