### ISSUE TITLE
Installing Perl modules for evaluation script

### ISSUE THREAD

**Issue by devanshujain919** [codalab/codalab-competitions#1849]
Hey,

I am trying to run my evaluation script for my competition but the script requires some additional perl modules (XML::DOM). Can someone tell me how to install such additional modules in the compute worker nodes ?

Thanks

**Comment by devanshujain919** [comment]
Hey, 

I would really appreciate any help! I am running on a tight schedule.

Thanks

**Comment by ckcollab** [comment]
@devanshujain919 is there a way you can include this dependency inside of the evaluation script?

**Comment by devanshujain919** [comment]
Hi, I can include install commands like: `perl -MCPAN -e 'force install XML::Parser'`, but it requires sudo access !

Will it be okay to include this in the evaluation script ?

**Comment by ckcollab** [comment]
I'm not quite sure that will work -- could try it! Do you have any other options, could you maybe parse it in Python or something else with XML support?

**Comment by devanshujain919** [comment]
No, I am trying to use a summarization tool : [ROUGE](https://github.com/summanlp/evaluation/tree/master/ROUGE-RELEASE-1.5.5), which requires these perl modules. 

Is there any other way like if the owners/admins could install these modules on the worker nodes if the above method does not work ?

@ckcollab I really appreciate the help.

**Comment by ckcollab** [comment]
> Is there any other way like if the owners/admins could install these modules on the worker nodes if the above method does not work ?

**Comment by devanshujain919** [comment]
What's the ETA on the docker image feature ? That sounds perfect !

**Comment by ckcollab** [comment]
> What's the ETA on the docker image feature ? That sounds perfect !

Like 2 months :( 1 month at the earliest...

**Comment by devanshujain919** [comment]
Hey, 

I got an error: `mkdir /root/.cpan: Permission denied at /usr/share/perl/5.18/CPAN/HandleConfig.pm line 590.`, when I included the statement: `perl -MCPAN -e 'install XML::DOM'` in the script.

I think I will be needing your help after all. 😅 

Do you think if it would be possible to run the command with root permissions on compute worker nodes ? 

Thanks

**Comment by ckcollab** [comment]
Looks like I can get this done with `sudo apt-get install libxml-parser-perl`

https://stackoverflow.com/questions/9693031/how-to-install-xmlparser-without-expat-devel

When do you need this done by?

**Comment by devanshujain919** [comment]
By this weekend ?

**Comment by ckcollab** [comment]
OK, I'll do this tomorrow morning, please get your competition setup [here](https://competitions-test.codalab.org/) for testing.

**Comment by devanshujain919** [comment]
Hey, something is weird. When I am setting up the competition on the link mentioned above, I get the error that my script does not have permission for execution: `/codalabtemp/tmphWkB4O/run/program/run.sh: line 5: /codalabtemp/tmphWkB4O/run/program/rouge/ROUGE-1.5.5.pl: Permission denied`. 

However, it had permission to run [here](https://competitions.codalab.org/competitions) !

**Comment by ckcollab** [comment]
Yeah we see that sometimes on the test server, permissions get messed up and need to be reset. Should be ready to test tomorrow.

**Comment by FlavioAlexander** [comment]
@ckcollab I still wonder why permissions get messed up sometimes 🤔

**Comment by ckcollab** [comment]
I've updated the test servers with that command and I have reset them so hopefully the permissions bug is gone. Which is your competition? Please add me as an admin (eric is my user) and I'll test it.

**Comment by devanshujain919** [comment]
I don't know how to add ppl as admins ?

I can provide you the secret url though ? Would that work ?

**Comment by ckcollab** [comment]
Goahead and test yourself as well. It's under "Edit" for your competition.

**Comment by devanshujain919** [comment]
Hey @ckcollab , I am so sorry for replying so late. But, I was out of station for these past few days. I tried testing the system today, but it fails for some reason. I am unable to view the error/output logs. Can you help me regd this. I am making the same submission as I did when I got the permission errors.

**Comment by devanshujain919** [comment]
I see that the above issue is resolved. But, still I am getting this error: `Can't locate XML/DOM.pm in @INC`. Can you please try and run the command `perl -MCPAN -e 'install XML::DOM'` instead ?

**Comment by ckcollab** [comment]
I ran this command on the staging servers... it looks like it sets quite a few new defaults and makes quite a few changes... I am hesitant to push this to production. Let me know how it works for you.

**Comment by devanshujain919** [comment]
Its just a perl module. The evaluation software requires that dependency. Its just creating new variables for setting up the environment. Its pretty old module and I don't see any issues on StackOverflow related to it being incompatible with anything common. I guess installing it should be fine.

**Comment by ckcollab** [comment]
Did you get a chance to test it?

**Comment by devanshujain919** [comment]
Yes. I created a competition and tried to run the software. But, it again threw the same error: `Can't locate XML/DOM.pm in @INC`.

**Comment by ckcollab** [comment]
Not sure about those problems, we are in the process of transitioning to the new docker setup though, so hopefully this lands in time to help you out.

**Comment by Tthomas63** [comment]
We have not received any feedback in a while, so we are closing this issue. If you run into more problems please open a new issue.
