### ISSUE TITLE
Evaluation for DAVIS is slow

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1859]
Dear Codalab admins,

Last-hours submissions to our DAVIS Challenge (https://competitions.codalab.org/competitions/16526) are making the evaluation very slow (hours instead of the usual ~20 minutes). 

Is there any way you could allocate more resources for these last 10 hours?
We would be willing to pay the cost of adding some extra AWS machines.

Best,

**Comment by FlavioAlexander** [comment]
Hello @jponttuset, 

Sorry to hear that. Are we expecting tons of submissions? Not sure how many compute workers we have at this very moment. For instance, if we have 5 compute workers and we have tons of submissions, they will accumulate in the queue until one of the workers becomes available, but eventually they will submit. cc @ckcollab for further decisions.

**Comment by jponttuset** [comment]
Thanks for the quick reply!

Right now we have 12 submissions in queue + 4 running. The deadline is in ~10 hours.
I do not expect a huge amount of submissions, but it could get to the order ~100 during these last hours. If we have a way to add workers for these last hours, we would appreciate it, and as said, we would be willing to pay for the extra cost.

Best,
