### ISSUE TITLE
"An unexpected error occurred" in DAVIS

### ISSUE THREAD

**Issue by jponttuset** [codalab/codalab-competitions#1860]
Dear Codalab admins,

A couple of users have found that they cannot submit results and receive "An unexpected error occurred" as in the image attached:
![screenshot](https://user-images.githubusercontent.com/4990362/27749514-29e690bc-5dd4-11e7-9d8e-b3416b3ce8e1.jpg)

"ltnghia" is one of the users having this error. 
Could you please check it?

Best,

**Comment by FlavioAlexander** [comment]
@jponttuset,

Has she attempted to submit again? Could you add me as an admin? My username is `flavioAlexander`. I am checking the logs on the web server and can't find anything, error is probably coming from one of the compute workers

**Comment by jponttuset** [comment]
Hi FlavioAlexander, 
Thanks for the quick reply. 👍 
Just added you as admin, let's hope you find something.

**Comment by jponttuset** [comment]
Hi again FlavioAlexander,

The user "debugged" the system and it seems that the problem was in the length of the description or some of the characters, they managed to submit now.

Thanks a lot!

**Comment by FlavioAlexander** [comment]
Hi @jponttuset, 

Could you elaborate a little more on that? I found some issues with retrieving `scores.txt` which causes the submission to fail, not sure why some submissions failed to create this file.

**Comment by jponttuset** [comment]
Hi @FlavioAlexander!
According to them, they shortened the field "Method description" of the submission metadata and then it worked, it seems it's the only thing they changed.
