### ISSUE TITLE
Add Starting Kit to competition bundles

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1862]
- Add argument to YAML file
- Add model field to **competition phase** for starting kit zip
- Add new dataset type (input data, scoring program, reference data, add new one **Starting Kit**)
- Add a link to starting kit to competition detail page -- where to put this? We could have a nice large call to action button "Get the starting kit!" or something?

**Comment by Tthomas63** [comment]
See PR #1870 for details.
