### ISSUE TITLE
Add ability for competition bundles to contain relative static files

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1863]
Add a `static` magic directory to competition bundles, any files in here are uploaded to a `<competition-id>/static/` directory which can be relatively referenced in the HTML files... the `{{STATIC}}` string will be replaced by the static url.

**Comment by ckcollab** [comment]
- [ ] Limit # of static files to `MAX_NUMBER_COMPETITION_STATIC_FILES`

**Comment by ckcollab** [comment]
Consequences:
- Will require changes to competition dump
- How can we edit assets after they were uploaded...? What if someone wants a new asset...

**Comment by Tthomas63** [comment]
See #1886
