### ISSUE TITLE
my CIKM phase 2 submission is stuck in the status of "submitted"

### ISSUE THREAD

**Issue by peter1412** [codalab/codalab-competitions#1873]
in the CIKM phase 2, my submission is stuck in the status of "submitted", since the phase only has 10 submission in total, please help me to fix that

**Comment by FlavioAlexander** [comment]
Hello @peter1412,

Eventually submissions will run. It seems like servers are receiving tons of submissions which are process in the order they get. Apologies for the inconvenience. Let me know if you have any other questions.

Best,

Flavio

**Comment by lupantech** [comment]
I meet the same case

**Comment by FlavioAlexander** [comment]
Hey @lupantech,

Sorry to hear that. We can just handle certain amount of submissions at a given time. The rest go to the queue and wait until one of the compute workers is free. Not only that, we have to take in consideration aspects such as: time needed for a submission to run, type of submission, etc

**Comment by peter1412** [comment]
so should I submit again, so it can be fine? but will it waste one of my submission? because the CIKM competition should only submit 10 times, I strongly suggest this one should not be counted in

**Comment by peter1412** [comment]
wait, you mean your server can't afford right now, and I should wait for a while, right? hope it will not be too late

**Comment by FlavioAlexander** [comment]
Yep, they should eventually run. Let me know if that is not the case.

**Comment by quanghieu-vu** [comment]
Still issue after a day @FlavioAlexander. A similar report for this issue https://github.com/codalab/codalab-competitions/issues/1878

**Comment by lupantech** [comment]
![2017-07-27 4 48 35](https://user-images.githubusercontent.com/17663606/28662077-749c802c-72eb-11e7-9d4e-81c50416eee1.png)

**Comment by xiaoyong** [comment]
Same problem for another competition (COCO Detection Challenge). Seems that the computation resource is shared across different competitions :-)

**Comment by hadylauw** [comment]
Hello @FlavioAlexander,

I am one of the organizers for the CIKM2017 competition.  I raised a similar issue at https://github.com/codalab/codalab-competitions/issues/1878.

We understand that some delay may occur as a submission is waiting for available computational resource.   However, it's been 24 hours since the last time a submission was processed.

Would it be possible to have a look at the situation, and see if any resolution could be done?  We'd really appreciate it, especially as we are in the final few days of the competition.

Best regards,
Hady

**Comment by FlavioAlexander** [comment]
Hello @hadylauw, 

🤔 submissions should have been submitted by now. 24 hours seems a long period of time. I will definitely take a look, Do you mind adding me as a admin to your competition, my username is `flavioAlexander` or `flavioZhingri`

Best,

Flavio

**Comment by FlavioAlexander** [comment]
@xiaoyong That is correct, resources are shared among all competitions.

**Comment by hadylauw** [comment]
Hello @FlavioAlexander,

I have added both usernames as admin to our competition.  Thank you for your help!

Best,
Hady

**Comment by hadylauw** [comment]
@FlavioAlexander By the way, our competition is https://competitions.codalab.org/competitions/16652.
