### ISSUE TITLE
Reorder items in the vertical menu

### ISSUE THREAD

**Issue by filipdbrsk** [codalab/codalab-competitions#1880]
Hi guys,
I see that the codalab model requires the first three tabs in the vertical menu to be Overview, Evaluation and Terms & conditions. Is there any way to change the order of these three pages? We have a lengthy data description and would prefer having that as a second tab.
Thanks!
Filip

**Comment by Tthomas63** [comment]
Hello,

I do not believe this is possible at the moment without accessing the Codalab instance's python shell, and manually changing the objects values. 

When the competition is unpacked and created, those fixed pages are created with that fixed order. There is currently not a feature to edit the `rank` of the pages either. This is a feature idea we will add to our backlog.

Thanks, Tyler
