### ISSUE TITLE
The docker in competitions doesn't seem to be updated. 

### ISSUE THREAD

**Issue by EgoLaparra** [codalab/codalab-competitions#1885]
According to the docker registery, the standard enviroment contains Java 1.8 and Scala 2.11.2. However, running a scorer in competitions I get that scala is not found and the java version is 1.7.  I downloaded the docker and everything seemed to be updated. In fact, my scorer worked fine.
Would it possible to update the docker in competitions? Or is it possible to use a different enviroment?

**Comment by ckcollab** [comment]
The current production version of Codalab isn't using docker yet -- or are you using the docker staging server? 

In the future you will be able to specify a docker image you want to use to run your scoring/submission program in! :)

**Comment by EgoLaparra** [comment]
No, I'm not using the staging server.
In any case, the java version in competitions is 1.7, right? Could you update it to 1.8?

**Comment by ckcollab** [comment]
@EgoLaparra late reply... yes, that server :)

**Comment by madclam** [comment]
On Oct 31 we will push "dockers" to the production public instance.
