### ISSUE TITLE
Add a new dataset type for public datasets (organizer dataset)

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1901]
Should appear above starting kit in the competition editor

![image](https://user-images.githubusercontent.com/2185159/29224142-e496e9b0-7e7d-11e7-8939-adda009e1f4b.png)

More specs here: 
https://sites.google.com/a/chalearn.org/platform/specifications/chalab

**Comment by madclam** [comment]
Test that.
