### ISSUE TITLE
Codalab displays datasets from other tasks when adding a new phase

### ISSUE THREAD

**Issue by felipebravom** [codalab/codalab-competitions#1902]
Hi,
I was trying to add a new phase to my existing competition from the Edit Competition Menu, and Codalab is listing  ALL existing datasets (not only the ones associated with my user) when trying to select the Reference Data and the scoring program.  I think that this should be changed and only my datasets should be shown here.
Bests,
Felipe

**Comment by madclam** [comment]
Test it on staging server.
