### ISSUE TITLE
cannot sign in

### ISSUE THREAD

**Issue by geliuhao** [codalab/codalab-competitions#1909]
I signed up an account today. But I have not received any confirmation email. When I try to sign in, the webpage shows an error: "500 Internal server error. ...".

**Comment by se4u** [comment]
same here.

**Comment by ckcollab** [comment]
It appears our sendgrid account has run out of credits..

Trying to contact the right people now to get this refilled. Apologies for the inconvenience. Shoot me an email eric@ckcollab.com and I'll find the account with the same email and activate it.

**Comment by geliuhao** [comment]
Thanks!
