### ISSUE TITLE
500 internal sever error when sign up in codalab

### ISSUE THREAD

**Issue by afantideng** [codalab/codalab-competitions#1911]
Internal server error. Please file a bug report. For more information about CodaLab, check out the wiki.

**Comment by hazirbas** [comment]
Try to login with email and confirm it. Then login with username.

**Comment by FlavioAlexander** [comment]
Sorry for the late response. 

I just went through the whole process and did not see any error. After you sign up, you will receive a confirmation link, confirm it, then you will be able to log in.

**Comment by hazirbas** [comment]
Confirmation email was not sent until I logged in with email, not username.

**Comment by FlavioAlexander** [comment]
🤔 it should be send after sign up. You won't be able to log in without confirming it

**Comment by hazirbas** [comment]
Well, it didnt.  This error is thrown when you sign up. After that I tried to login with my username and it throw an exception and today i tried to login with my email and then it sent confirmation email.

**Comment by FlavioAlexander** [comment]
When did you create the account Not sure what the issue was, only thing I can think of is an issue with our SMTP provider.

**Comment by hazirbas** [comment]
Yesterday, 31. August 2017.

**Comment by FlavioAlexander** [comment]
Not really sure what happened, can't find anything within the log files. Will keep an eye on it
