### ISSUE TITLE
Always "Failed" when submit my answers.

### ISSUE THREAD

**Issue by anbangleo** [codalab/codalab-competitions#1915]
Dear friend, I meet the problem recently, when I submit my answers(zip) to my local competition, after showing t "submitting" the status is always "failed". But when I try it on the website Codalab.org it will be fine.
1)the "View scoring output log" showed "Standard output for submission by me" without any other errors
2)the "View scoring error log" showed "Standard error for submission by me" without any other errors
3)no other error information from browsers or background
4)Is it relevant about "Compute worker (only) setup", I didn't start the worker because it may meet some other issues...
Thanks for your time:)

**Comment by anbangleo** [comment]
Here is the error log I found

> [2017-09-04 06:14:45,056: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:14:55,958: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:05,978: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:14,829: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:22,875: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:32,187: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:42,639: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:51,541: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:15:59,479: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:16:02,208: INFO/Beat] Scheduler: Sending due task phase_migrations (apps.web.tasks.do_phase_migrations)
> [2017-09-04 06:16:02,210: INFO/MainProcess] Received task: apps.web.tasks.do_phase_migrations[69d540e6-4c07-4ff0-8381-385f80537deb]
> [2017-09-04 06:16:02,242: INFO/Worker-3] Checking 3 competitions for phase migrations.
> [2017-09-04 06:16:02,251: INFO/Worker-3] Checking 3 competitions for phase migrations.
> [2017-09-04 06:16:02,257: INFO/Worker-3] Checking 3 competitions for phase migrations.
> [2017-09-04 06:16:02,258: INFO/MainProcess] Task apps.web.tasks.do_phase_migrations[69d540e6-4c07-4ff0-8381-385f80537deb] succeeded in 0.0457351841033s: None
> [2017-09-04 06:16:05,714: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:16:05,733: WARNING/Worker-2] Saving competition submission.
> [2017-09-04 06:16:05,750: ERROR/Worker-2] evaluate_submission dispatch failed (job_id=19, submission_id=17)
> Traceback (most recent call last):
>   File "/app/codalab/apps/web/tasks.py", line 754, in evaluate_submission
>     task_func(submission, job_id)
>   File "/app/codalab/apps/web/tasks.py", line 491, in score
>     _prepare_compute_worker_run(job_id, submission, is_prediction=False)
>   File "/app/codalab/apps/web/tasks.py", line 222, in _prepare_compute_worker_run
>     docker_image = submission.phase.scoring_program_docker_image or settings.DEFAULT_WORKER_DOCKER_IMAGE
>   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
>     return getattr(self._wrapped, name)
> AttributeError: 'Settings' object has no attribute 'DEFAULT_WORKER_DOCKER_IMAGE'
> [2017-09-04 06:16:05,773: INFO/MainProcess] Received task: apps.web.tasks.update_submission[cdb05cab-e6b2-4671-95a9-dc0f94814e00]
> [2017-09-04 06:16:05,775: INFO/MainProcess] Task apps.web.tasks.evaluate_submission[f026d41f-b036-4d9a-86ea-f2851416653e] succeeded in 88.536152415s: None
> [2017-09-04 06:16:05,800: WARNING/Worker-3] Saving competition submission.
> [2017-09-04 06:16:05,825: INFO/Worker-3] Changed submission status from submitting to failed (id=17).
> [2017-09-04 06:16:05,835: INFO/MainProcess] Task apps.web.tasks.update_submission[cdb05cab-e6b2-4671-95a9-dc0f94814e00] succeeded in 0.0584117174149s: None

**Comment by anbangleo** [comment]
This is the error what I think, could you please tell me what happened? I will be very grateful

> AttributeError: 'Settings' object has no attribute 'DEFAULT_WORKER_DOCKER_IMAGE'

**Comment by ckcollab** [comment]
I believe if you pull the latest it should fix that problem?
