### ISSUE TITLE
Documentation: Update: What are queues?

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1917]
1. Move 'How do I setup a worker to process submissions' documentation to
http://codalab-competitions.readthedocs.io
at http://ec2-107-20-12-237.compute-1.amazonaws.com/queues/

2. Update point 3. and other to allow people to test it

**Comment by ckcollab** [comment]
Added docs here:
https://github.com/codalab/codalab-competitions/wiki/Worker-Queues
