### ISSUE TITLE
Remove horizontal scrollbars

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1926]
In Codalab (main page) competitions list, can we remove horizontal scrollbars? (as ugly and not used)

![hori](https://user-images.githubusercontent.com/4463818/30209691-a9409c8a-9499-11e7-947c-f4f4c4405e9a.jpg)

**Comment by ckcollab** [comment]
Acceptance criteria:
- Go to the front page
- Scroll bars should be removed
