### ISSUE TITLE
Dev_Getting Started on Windows [minor]

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1927]
1. Can we avoid this Dev_ prefix in each title?

2. Getting started for UNIX ends with
'Configure CodaLab for Development' link,
but not the other OSs.

**Comment by Tthomas63** [comment]
1. Some of the current links in the wiki reference the local page names instead of actual URLS. This is planned but I'm unsure how many of the links in the wiki reference by local page name right now.

2. Fixed. Thanks for catching this.
