### ISSUE TITLE
Dev_Getting Started on Windows [main]

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1928]
I have win8 and would like to know explicitly what shall I do. 
As Docker for Win is for Win10Pro, I searched and there are many topics (like https://forums.docker.com/t/docker-for-windows-or-docker-toolbox/30387 ) stating that Docker Toolbox can be used instead (although it uses VMBox).
Can this be used? If not please tell on wiki why.

**Comment by Tthomas63** [comment]
Added this to the note about Windows Requirements for Docker:

*In the future Docker will support more versions of Windows 10. If your windows system does not meet these requirements, install Docker toolbox instead:* [Docker Toolbox Instructions](https://docs.docker.com/toolbox/overview/).

Also included this snippet from the Docker Toolbox page:

*Docker Toolbox is an installer for quick setup and launch of a Docker environment on older Mac and Windows systems that do not meet the requirements of the new Docker for Mac and Docker for Windows apps.*
