### ISSUE TITLE
Fix "Privacy" policy link in footer

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1936]
- [ ] REVIEW

https://github.com/codalab/codalab-competitions/wiki/Privacy

Currently has Outercurve privacy statement, should have a new one from University lawyers.

see also https://github.com/codalab/codalab-competitions/issues/1952

**Comment by ckcollab** [comment]
Related to #1952

**Comment by madclam** [comment]
New version at https://github.com/codalab/codalab-competitions/wiki/Privacy, please review.
When we release the new version of Codalab, we should inform users about the change in terms.
