### ISSUE TITLE
I can see the input data/reference data/scoring program of all users

### ISSUE THREAD

**Issue by nightrome** [codalab/codalab-competitions#1944]
Hi,
I think there is a security issue with Codalab. I created my own competition, deleted all phases, added a new phase and then if I specify input data/reference data/scoring program, I can select any file from any user. 
After submitting that, I receive an error "Select a valid choice. That choice is not one of the available choices", which is good. However, I think that even the fact that I can see the files of all users listed in a Dropdown list already hints to some security issues.
This is 100% reproducible for me..

**Comment by ckcollab** [comment]
This should be fixed in a version of Codalab we are deploying soon.
