### ISSUE TITLE
Create Evaluation With Dependencies

### ISSUE THREAD

**Issue by kdportillo** [codalab/codalab-competitions#1948]
For the evaluation script of my competition, I'd like to use sklearn, numpy and scipy. These packages require pip installations. How should I write my script so that it recognizes these libraries and won't spit out ImportErrors?

**Comment by ckcollab** [comment]
Hey @kdportillo, we are working on a new version of Codalab where organizers and participants can specify the docker image their scoring program/submissions run in. This means you can modify the [base codalab docker image](https://github.com/codalab/docker-codalab-legacy-worker) to add your own `pip` packages/etc.


You can test these features out here:
http://13.90.249.6/

We'd love more testers on this new version of Codalab, we want to deploy it soon but one of our big bottlenecks is getting testing from real world organizers/participants. Would love some input! Also, if things aren't clear let me know and we'll try to add documentation and little `?`'s in relevant spots to reveal more details.

**Comment by kdportillo** [comment]
Will do! 

Do I need to create a new account? Where do I run my pip install's? Do I need install packages for every submission?

**Comment by ckcollab** [comment]
Yeah you'll create a new account on that "staging server" which is just our test server. 

What you'll do is make a new docker image on dockerhub and specify that in your competition settings or as you upload your submissions. Here's an example:

* Image on dockerhub -> https://hub.docker.com/r/ckcollab/codalab-legacy/ 
* I built it using this github repo -> https://github.com/codalab/docker-codalab-legacy-worker

There are a ton of tutorials for making a docker image... it is pretty confusing if you haven't done it before. Maybe we can add some extra features to the base docker image to look for a `requirements.txt` and auto-install those on boot? We could even get fancy and allow switching between python versions with pyenv, to help support py2/3.

Let me know if any of this sounds useful for you, feel free to drop me an email as well! eric@ckcollab.com
