### ISSUE TITLE
License, disclaimers, terms

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1952]
- [ ] REVIEW.

https://github.com/codalab/codalab-competitions/edit/develop/LICENSE.TXT

See also https://github.com/codalab/codalab-competitions/issues/1936

**Comment by madclam** [comment]
I simplified (removed redundancies) and updated (according to French law) the https://github.com/codalab/codalab-competitions/wiki/Privacy. Please review.
I modified https://github.com/codalab/codalab-competitions/edit/develop/LICENSE.TXT.
The Governance https://github.com/codalab/codalab-competitions/blob/master/docs/Community-Governance.md seems OK to me.
I asked Evelyne, Percy and Sergio about modifying https://github.com/codalab/codalab-competitions/wiki/Project_About_CodaLab.

**Comment by madclam** [comment]
http://codalab.org/ points to https://github.com/codalab/codalab-competitions/wiki/Privacy.
We should remove that from the footer.
The About link is OK.
