### ISSUE TITLE
Urgent: Leaderboard contents not visible

### ISSUE THREAD

**Issue by nightrome** [codalab/codalab-competitions#1955]
Hi,
I have a running competition at https://competitions.codalab.org/competitions/17415#results . According to the submissions page, I have valid submission for the examples and val2017 phases, that also claim to be displayed on the leaderboard. However, the leaderboard is empty and even the button "Download CSV" is missing!

Digging deeper I found that my initial YAML file had an issue: All metrics for the leaderboard had the same label. I tried to change the labels back and forth on the "Edit" page, but that doesn't solve the problem. I even tried creating another competition with valid labels and there it works. Is it possible that an admin could change my account to fix that? And probably it would be good to fix that in the code as well..
Thanks!

**Comment by ckcollab** [comment]
>  Is it possible that an admin could change my account to fix that?

What would you need fixed? Unfortunately, we probably won't be able to easily fix it by hand. 

Could you move your competition to the new working one?

**Comment by nightrome** [comment]
Actually the labels are correct the way they are now. I just guess that whatever is stored for the leaderboard  is broken.. Is there a way too purge that and reset the leaderboard?

Moving the competition would be  a annyoing for the users, unless there is a way to redirect the old page.

**Comment by nightrome** [comment]
Okay, I moved it now. But it is really a pity that things that are initially broken cannot be recovered. It should be possible at any time to download the current YAML and upload a new one..

**Comment by ckcollab** [comment]
You are absolutely right. We have a whole bunch of improvements backed up waiting for more testing and approval. If you have any free time please let me know and I'd love to get your input on these changes and any other pain points: eric@ckcollab.com
