### ISSUE TITLE
Cookies: funky link

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1957]
In
![image](https://user-images.githubusercontent.com/7594063/30732168-155e1654-9f26-11e7-924b-4b601c9ed919.png)
learn more links to:
http://www.wimagguc.com/?cookie-policy
It should link to our page:
https://github.com/codalab/codalab-competitions/wiki/Privacy

**Comment by Tthomas63** [comment]
See PR #1959

**Comment by Tthomas63** [comment]
Merged with #1959
