### ISSUE TITLE
Test Worker Queues

### ISSUE THREAD

**Issue by Tthomas63** [codalab/codalab-competitions#1961]
Add acceptance criteria

**Comment by ckcollab** [comment]
Acceptance criteria for worker queues:



- [ ] Add a queue, should generate a new queue with `broker_url`
- [ ] When you add another organizer to queue, they should be able to see the queue in their competitions
- [ ] Connect with the queue connection string `broker_url`
- [ ] Running a submission runs it on the selected queue
- [ ] View the queue options in a competition, should see:
    1. Public queues
    2. Queues you've made
    3. Queue's that have been shared with you

**Comment by FinLouarn** [comment]
issue #1985: Non public Queue listed as if it was public + Dublicates
https://github.com/codalab/codalab-competitions/issues/1985

**Comment by FinLouarn** [comment]
How can we make sure that the Re-Runned submission has been processed on the new selected queue, and not the former one?

**Comment by ckcollab** [comment]
For now: if you have access to the queue you should see it be processed. In the future, it'd be nice to have this queue-per-submission metadata displayed somewhere like on Submissions admin page?

**Comment by ckcollab** [comment]
To be more specific, you can watch the logs with `docker-compose logs -f worker_compute` -- this command will probably change soon as we're moving the compute worker to its own repo.

**Comment by madclam** [comment]
Sebastien created an AMI to test queues: AMI-Codalab-compute-workers.
