### ISSUE TITLE
UserSwitchMiddleware authentication bug

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1962]
The fix I made to only allow admins caused another small problem

**Comment by madclam** [comment]
Related to https://github.com/codalab/codalab-competitions/issues/1951?

**Comment by ckcollab** [comment]
@madclam I don't think we can keep `UserSwitchMiddleware` and only allow admins.. the logic breaks all over the place, it will be difficult to somehow store your previous user and detect that the same logged in user is no longer an admin.

I think we can get a similar benefit from switching some behaviors to allow admins to override...? But this may be easy or rather time consuming to find all of the places that need this check added. Maybe I could make it so admins get a button "make me an admin of this competition" that forces them into the admin list, that way all of the existing permissions checks will work, but you will now appear in the admin list -- is that OK?

**Comment by ckcollab** [comment]
Add a env flag `USER_SWITCH_MIDDLEWARE`

**Comment by ckcollab** [comment]
Added the flag, closing
