### ISSUE TITLE
V1.5 testing: Hosting codalab problems topic

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1965]
i  tried to test my own Codalab webpage, it looks OK, there are 1 problems so far:

I could register but uploading the Iris bundle does not work (says: wrong extension), although it is .zip.
You can make a user in 10 seconds on website and see this by yourself.
The server is here:
http://ec2-54-153-46-119.us-west-1.compute.amazonaws.com/

**Comment by madclam** [comment]
I have tested and have a similar problem. Uploading a bundle give me:
![image](https://user-images.githubusercontent.com/7594063/30925704-9aa56872-a367-11e7-9580-b72d78acfe00.png)

**Comment by ckcollab** [comment]
Can you give me SSH access to this server? The error is actually probably due to the file not being found, although it says it's not a zip--it's just not found.

**Comment by lr292358** [comment]
![image](https://user-images.githubusercontent.com/4463818/30925960-856ca594-a3ab-11e7-9f81-793acc34909f.png)

**Comment by lr292358** [comment]
my error

**Comment by lr292358** [comment]
I sent the access via email, can you test it in the next 2 hours? This is important to be able to create a competition.

**Comment by Tthomas63** [comment]
I'm taking a look now.

We identified a bug that was causing an issue on my local setup that seems to be affecting you your instance as well so I'm currently fixing that.

Eric is unsure that this would cause the other errors you are seeing though, so we will do some more digging.

**Comment by Tthomas63** [comment]
There seemed to be an issue with your storage settings in the `.env` file. For now we commented out yours so you may tweak them, and put ours in below.

We were able to successfully upload a competition, so hopefully all works for you.

Thanks,

**Comment by lr292358** [comment]
There were actually 3 different problems and they went into separate consideration/issues, closing.
