### ISSUE TITLE
Organization styling for competitions

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1966]
Currently you can assign a logo to a competition but it would be nice to set a custom ORGANIZATION logo to display instead of the Codalab logo in the top left.

![image](https://user-images.githubusercontent.com/2185159/30872510-30cb737e-a29f-11e7-9134-7985fca8bb5c.png)

Most logical approach:

- Add "organization logo" to profile edit page
- If single competition mode is set and an organization logo is set, set it in the top left

**Comment by madclam** [comment]
related to https://github.com/codalab/codalab-competitions/issues/1932

**Comment by ckcollab** [comment]
Have a rough draft for this working, but I am concerned about how it will look..

![image](https://user-images.githubusercontent.com/2185159/31352624-3ef9b6fa-ace4-11e7-850f-51726d5f989b.png)


Images will have to be the perfect ratio and such to fit well... hmm... right now it just clips off any extra bits of the image. I could have it shrink the image to fit that, but many many logos will be too big.

**Comment by ckcollab** [comment]
- [ ] Add organization URL to model
- [ ] Link organization logo to organization URL
- [ ] Figure out some way to get the right size organization logo
    * File size limit
    * Don't limit height/width
