### ISSUE TITLE
Replace Outercurve logo

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#1968]
Remove outercurve logo:

https://github.com/codalab/codalab-competitions/wiki/Project_About_CodaLab

Add this logo:

https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Logo_Universit%C3%A9_Paris-Saclay.svg/1280px-Logo_Universit%C3%A9_Paris-Saclay.svg.png

**Comment by madclam** [comment]
Done.
