### ISSUE TITLE
Staging server does not process submissions

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1973]
I am using the Hello World competition:
https://github.com/codalab/competition-examples/tree/master/hello_world
on the staging server.
http://13.82.145.119/competitions/38
After 1/2 hour it is still in the "submitted" stage.
![image](https://user-images.githubusercontent.com/7594063/30939377-127185f0-a392-11e7-82e4-0235372a4391.png)

![image](https://user-images.githubusercontent.com/7594063/30939290-c9926c8c-a391-11e7-8dd9-c677492612ca.png)

I have the same problem with the other staging server: http://13.90.249.6/competitions/1

**Comment by lr292358** [comment]
I also have this problem on my server -- Lukasz
