### ISSUE TITLE
Cannot delete competition

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1977]
Testing staging server http://13.82.145.119/.
Tried to delete several competitions, including: 43 and 46.
Delete does not work. I get:
![image](https://user-images.githubusercontent.com/7594063/30949280-3e6ab3c4-a3ca-11e7-81c7-02fc71e68d5a.png)

---
However "delete" works in http://13.90.249.6/.

**Comment by ckcollab** [comment]
This should be fixed now, pushed to http://13.82.145.119/ and tested

**Comment by madclam** [comment]
Thanks.
