### ISSUE TITLE
Cannot upload .zip files on Windows (bundles/solutions)

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#1979]

**Comment by ckcollab** [comment]
More details, please? I was able to upload on Windows 10 with no problems?

**Comment by lr292358** [comment]
Win 8, error (both for bundles or submissions)
![image](https://user-images.githubusercontent.com/4463818/31040513-0d160c4e-a580-11e7-85e5-d85744015c4a.png)

**Comment by ckcollab** [comment]
What browser? Which server is this on, http://13.82.145.119/? Google doesn't show any results for `codalab "invalid file type"`... let me know if you maybe find an old issue with more details about it.

**Comment by lr292358** [comment]
any browser, any server. Only I have this problem so far, I think it is from Python, this error is when submitting a bundle, I think it said a zip is not a zip when handling a submission zip. We will see later, I remove P1 as nobody has this problem..

**Comment by ckcollab** [comment]
Hmm, it could be from Python but I doubt it? Python error would probably be displayed in that red box when the competition fails to process.

It is probably from something clientside... wonder what, though...

**Comment by TaihuLight** [comment]
You may be need to compress the *json file on Linux OS rather than Windows OS.
