### ISSUE TITLE
Dump fails

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1982]
![image](https://user-images.githubusercontent.com/7594063/30999002-11ece430-a487-11e7-8327-f648ce4d4489.png)

**Comment by Tthomas63** [comment]
Fixed this bug and pushed the changes to the staging servers. Tested and working.

<img width="1437" alt="screen shot 2017-10-04 at 11 32 13 am" src="https://user-images.githubusercontent.com/28552312/31193046-cf70db64-a8f7-11e7-8f50-623dc86b5dad.png">
