### ISSUE TITLE
Non public Queue listed as if it was public + Duplicates

### ISSUE THREAD

**Issue by FinLouarn** [codalab/codalab-competitions#1985]
The organizer of a competition can view more than: his Queues + public Queues +  Queues shared with him.
Some non public Queues, not shared with him are nevertheless visible through the "Edit" of Admin feature of the competition. It can be because of the "Edit" function of the Queue. The queue has been edited from public to non public, but is still visible as if it was public, even if the public option box is unchecked.

More over the Queue is duplicated 3 times with the same name in the drop-down(or up) menu of Queue selection.

![screenshot from 2017-09-29 22-36-43](https://user-images.githubusercontent.com/6131050/31035871-f327ed90-a569-11e7-95c4-f1cd43beb89b.png)

**Comment by ckcollab** [comment]
I believe this is fixed now, please let me know if you have any more problems and thank you for the thorough testing!

**Comment by FinLouarn** [comment]
I retested it. It seems to be fixed.

**Comment by FinLouarn** [comment]
I retested it. It seems to be fixed.

**Comment by ckcollab** [comment]
Wahoo! Thanks :)
