### ISSUE TITLE
Switch user security

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1986]
Find a solution to switch user security issue.

**Comment by ckcollab** [comment]
I believe the solution we arrived at today was to put some flag on servers where this should be allowed, and enable it that way?

**Comment by ckcollab** [comment]
- [ ] Add documentation to "Admin docs" for the `USER_SWITCH_MIDDLEWARE` env var (lookup the proper variable name)

**Comment by ckcollab** [comment]
I added more docs to this inside the actual `.env`, I think that will fit into [the docs](https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Competitions#user-content-get-the-source-code) for it well enough..?
