### ISSUE TITLE
Ingestion program 

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#1987]
1) **In custom ingestion programs.**

Nothing is available in $hidden: the **reference data** should be available.

2) **In default ingestion program**

When performing a result submission, the **reference data** is not made available to the scoring program.

In competition http://13.82.145.119/competitions/55 I made submitting a result submission:
http://13.82.145.119/my/competition/submission/521/input.zip
It has no metadata, so the ingestion program should call the scoring program directly. So it does. But the result submission is not available to the scoring program in the res/ directory. Instead, the input data has been copied there:
/tmp/codalab/tmpbPHB3H/run/input/ref/iris_valid.solution
/tmp/codalab/tmpbPHB3H/run/input/res/iris_feat.name
/tmp/codalab/tmpbPHB3H/run/input/res/iris_label.name
/tmp/codalab/tmpbPHB3H/run/input/res/iris_test.data
/tmp/codalab/tmpbPHB3H/run/input/res/iris_train.data
/tmp/codalab/tmpbPHB3H/run/input/res/iris_train.solution
/tmp/codalab/tmpbPHB3H/run/input/res/iris_valid.data
See http://13.82.145.119/my/competition/submission/521/stderr.txt

What we should see is:
/tmp/codalab/tmpbPHB3H/run/input/ref/iris_valid.solution
/tmp/codalab/tmpbPHB3H/run/input/res/iris_valid.predict
/tmp/codalab/tmpbPHB3H/run/input/res/iris_test.predict

**Comment by madclam** [comment]
Suggestion of changes:

There are 2 philosophies for the naming of the environment variables:

1) **Each program has 3 environment variables:**
$program: where the code of this program is.
$input: the inputs to the program (read only).
$output: the outputs to this program (writable).
This is what in implemented in Codalab version 1.

2) **All programs use the same environment variable naming with different permissions:**
This may be more dangerous but less confusing:
$ingestion_program: the ingestion program.
$scoring_program: the scoring program.
$submission: the submission of the participants (result or code; always read only)
$input_data: the input data (always read only)
$reference_data: the reference data (always read only)
$predictions: the output of the prediction step (writable by submission and ingestion programs, readable by scoring program)
$scores: the output of the scoring step (writable by scoring program)
$shared: a directory shared between the ingestion program and the submission (read/writable by both)
So we would have:
**Ingestion program metadata:**
- command: $ingestion_program/ingestion.py $input_data $reference_data $predictions $submission $ingestion_program $shared
The ingestion program has access to all environment variables, except $scoring_program and $scores (and that would not bee too bad if it had access to it too).
**Participant submission metadata:**
- command: $submission/submittedcode.py $input_data $predictions $submission $shared
The participant code has ONLY access to $input_data $predictions $submission $shared. Mostly, it should not have access to $reference_data.
**Scoring program metadata:**
- command: $scoring_program/scoring.py $predictions $scores $scoring_program

**Comment by ckcollab** [comment]
In our meeting Isabelle demonstrated that it looks like the `input_data` is ending up in the `res` (result) directory... instead of the submission result!?

**Comment by ckcollab** [comment]
Instead of

```
import sys

argument_1 = sys.argv[1]
```

We can do

```
import os

something = os.environ.get("NAME_OF_VARIABLE")
```
