### ISSUE TITLE
Feature request: E-mail notification to organizers on new forum entries

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#1996]
Hello, I'm running a CodaLab competition on SemEval 2018 Task 12 ( https://competitions.codalab.org/competitions/17327 ) and rely on the provided discussion forum.

Is there any chance to get e-mail notifications when participants post in the forum?

Thanks,

Ivan

**Comment by habernal** [comment]
I just posted a comment and got an e-mail directly... So it seems to be working.

**Comment by ckcollab** [comment]
Cool! :)

**Comment by habernal** [comment]
Reopening again. There were two new forum threads in the competition (8 and 2 hours back, respectively), but no e-mail was delivered.
