### ISSUE TITLE
Can not download database

### ISSUE THREAD

**Issue by peterrot** [codalab/codalab-competitions#2001]
Hi, 
I signed up to your site and wanted to download databases from Digital Pathology -- Segmentation of Nuclei in Images competition (http://miccai.cloudapp.net/competitions/57), but download links are not accessible anymore. I know that the competition is over but I would still like to try solving that problem.
Is there a way to get database? Thank you for your response!

**Comment by ckcollab** [comment]
We only run *.codalab.org sites -- I think you'll need to contact someone else to potentially recover these?
