### ISSUE TITLE
Update Python Modules

### ISSUE THREAD

**Issue by kdportillo** [codalab/codalab-competitions#2008]
Hello, 

I am writing an evaluation script that uses nltk in python. When uploading a submission, I receive as error:

`Traceback (most recent call last):`
`  File "/codalabtemp/tmpMCViux/run/program/eval-ts.py", line 56, in `
    `BLEUscores += [nltk.translate.bleu_score.sentence_bleu([tru.split()], te.split())]`
`AttributeError: 'module' object has no attribute 'sentence_bleu'`

Could you guys do an update on the nltk package? I've read that this may be the reason for the error. 

Thanks, 
Kevin

**Comment by kdportillo** [comment]
Let me know if you need any other information. We are want to deploy this competition this week.

**Comment by ckcollab** [comment]
Is it possible to include this new version along with your submissions?

**Comment by kdportillo** [comment]
I don't believe so since the nltk library should be ran from the environment's lib path since its a pip installed package. Do you know of any other work arounds?

**Comment by ckcollab** [comment]
I believe if you put it in the same directory that should be the module used, let me know if that doesn't work and we'll think of something. A new version of Codalab, coming out soon (Nov 6th), allows you to specify a docker image to run your submissions in..!

**Comment by kdportillo** [comment]
We tried placing the wanted module in the same directory as the evaluation script, but that in turn requires other modules within the library and so on. I received the following error when I tried it. 

`Traceback (most recent call last):
  File "/codalabtemp/tmpZCzEQA/run/program/eval-ts_v2.py", line 40, in 
    from nltk.compat import Fraction
ImportError: cannot import name Fraction`

**Comment by ckcollab** [comment]
What is the output of `import nltk; print(nltk.__file__)`? Maybe you need to append `$program` to `sys.path`?

**Comment by kdportillo** [comment]
We ended creating a workaround within the evaluation script and got it to work. Thank you for your help! I look forward to the version :)

**Comment by ckcollab** [comment]
Woo! :)
