### ISSUE TITLE
Evaluation for DAVIS failed

### ISSUE THREAD

**Issue by ankhoreva** [codalab/codalab-competitions#2014]
Dear Codalab admins,

While evaluation for DAVIS the following error occurrs:

/home/azureuser/anaconda/bin/python: can't open file '/codalabtemp/tmpJitz96/run/program/evaluation.py': [Errno 13] Permission denied

Thanks,
Anna

**Comment by FlavioAlexander** [comment]
Hello @ankhoreva, 

We will look into it.

Best, 

Flavio

**Comment by ckcollab** [comment]
Is the problem persisting? Is it happening on every compute worker? Could you link us to the competition? Thanks!

**Comment by ankhoreva** [comment]
It was happening on every compute worker. Now it seems to be running.
https://competitions.codalab.org/competitions/16526

**Comment by ankhoreva** [comment]
The same error occurred again:
/home/azureuser/anaconda/bin/python: can't open file '/codalabtemp/tmpzdn2bO/run/program/evaluation.py': [Errno 13] Permission denied

**Comment by ankhoreva** [comment]
Again today, seems like it's happening in a certain time of the day.

**Comment by ankhoreva** [comment]
it fails every day in a certain time frame, like in the morning and evening it's working and then fails during the day time (CEST time)

**Comment by sirius64** [comment]
i have never succeeded when upload my results to the server, sometimes it says permission denied as you mentioned before, sometimes it says none in case that i even don't know how to modify my operation, i think i will be crazy.......
