### ISSUE TITLE
Evaluation COCO2017 detection test-dev failed

### ISSUE THREAD

**Issue by sirius64** [codalab/codalab-competitions#2015]
After i uploaded the zip file to the server, the result is failed, i have tried four times but it doesn't work, is the coco 2017 detection server closed? the error log is nothing so i don't know how to solve this issue, is anyone meet with this problem? Can the administrator help me ?

**Comment by ckcollab** [comment]
@sirius64 is it still failing? Potentially related to #2014, which seems to be fixed now?

**Comment by sirius64** [comment]
@ckcollab i have tried but an error still happens, it is the same as #2014  
"/home/azureuser/anaconda/bin/python: can't open file '/codalabtemp/tmpoMnjtc/run/program/run.py': [Errno 13] Permission denied"
so would you please to see what happens to the server?  i am looking forward for your help.

**Comment by FlavioAlexander** [comment]
Hey @sirius64, 

Can you try now?

**Comment by sirius64** [comment]
@FlavioAlexander i try again and it still fail, the error log says none, i don't know how to modify, how can i get the results?
