### ISSUE TITLE
Document admin features

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2017]
For example:

* How do you make someone an admin? (add `ClUser` to admin.py btw)

Maybe make a "managing your own instance" section

**Comment by Tthomas63** [comment]
https://github.com/codalab/codalab-competitions/wiki/Developers-Instance-Hosts---Commands-and-Reference-Guide

**Comment by ckcollab** [comment]
@Tthomas63 did you link to this from anywhere in the Wiki?

**Comment by Tthomas63** [comment]
<img width="854" alt="screen shot 2017-11-06 at 8 50 36 am" src="https://user-images.githubusercontent.com/28552312/32452867-9c06b93c-c2cf-11e7-8b24-1cf589ebba21.png">

I added it to the developer section with the title `Developer/Instance Host Command & Ref Guide`. I was looking for a place where it would fit nicely into the `Instance` documentation but did not see where it would fit well. Possibly include it with a snippet explaining?

**Comment by ckcollab** [comment]
Thanks!
