### ISSUE TITLE
Bugs in v1.5 LRI server

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2019]
1) Secret key of https://codalab.lri.fr/competitions/45
says https://localhost/competitions/45?secret_key=3d7fe423-594f-415f-ae55-eda7c64ddd32

**REPLACE localhost**

2) In testing that same competition, I broke:
https://codalab.lri.fr/my/competition/45/submissions/

![image](https://user-images.githubusercontent.com/7594063/32139292-5bb4d1d4-bbf9-11e7-826e-187aa05f4df2.png)

3) The grouping of datasets in My Datasets does not work as before: the datasets are group but not unzipped in sub-directories. For example:
https://codalab.lri.fr/my/datasets/download/43f4602a-07e4-4823-a24d-6bc8b4a59c08
is a dataset created from 2 separate uploads of
https://codalab.lri.fr/my/datasets/download/93462efe-242a-42d5-83a5-b03111383ae2
and
https://codalab.lri.fr/my/datasets/download/92b0b951-2f90-4d2b-9090-ed0f68c1f559
then grouping. When unzipping the file, I would expect:
ada/
arcene/
I get:
ada.zip
arcene.zip

4) The datasets in the Files tab cannot be downloaded when they are referred to by their key in the YAML file: 
![image](https://user-images.githubusercontent.com/7594063/32202497-7597be84-bd9a-11e7-9278-34f9f1d78191.png)
The file downloaded is metadata that contains:
madeline: dataset_data_file/None/d7038/madeline.zip
adult: dataset_data_file/None/1f7f0/adult.zip
cadata: dataset_data_file/None/f7778/cadata.zip
dorothea: dataset_data_file/None/dd105/dorothea.zip
newsgroups: dataset_data_file/None/da4ff/newsgroups.zip
Not the actual data
https://codalab.lri.fr/competitions/47?secret_key=e925c625-e983-40e4-9afa-311a7721063b
I also made you admins.

5) Detailed results:
The results of the last column cannot be downloaded.
![image](https://user-images.githubusercontent.com/7594063/32203830-06f48b16-bda3-11e7-8e3c-9b83a88fe130.png)
https://codalab.lri.fr/competitions/48
I made you admins.

**Comment by ckcollab** [comment]
#1 should be fixed now, #2 @Tthomas63 and I will look at and #3 I'm not sure we've touched multiple datasets, I believe it always worked this way? I could be wrong, but I don't think we've messed with it.

**Comment by ckcollab** [comment]
another new bug "The proxy server received an invalid response from an upstream server." when ____ (uploading, to where?) ~120mb file.

**Comment by madclam** [comment]
I now tested more bug number 3. It is true that on competitions.codalab.org, when you download grouped datasets they are like multiple zips. BUT, to the code, as input_data, they appear un-zipped.

On the LRI server, I get an error in my code when I use datasets grouped with my_datasets:
Traceback (most recent call last):
  File "/worker/worker.py", line 265, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 134, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 134, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 91, in get_bundle
    urllib.urlretrieve(url, bundle_file.name)
  File "/usr/local/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/usr/local/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'dataset_data_file/None/dd105/dorothea.zip'

If I upload the datasets as a bunch of directories zipped together, I have no problem.

**Comment by Tthomas63** [comment]
Issue 2. should be solved with pr #2023 

Updating the servers to the latest develop should  allow the pages to render, and present the user with errors pointing them in the correct direction ( Checking leaderboard definition in comp.yaml, and the scoring program ) along with listing the bad `submissions`.
