### ISSUE TITLE
Make compute worker unzip any zip files passed as input, etc.

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2021]

**Comment by ckcollab** [comment]
Acceptance criteria @madclam:

- [ ] Multi-dataset when handled by compute worker is unzipped, where the unzipped folder is the name of the zip file without the `.zip` extension

**Comment by ckcollab** [comment]
The new server to test this is: http://codalab15-azure.eastus.cloudapp.azure.com

**Comment by Tthomas63** [comment]
Tested locally, appears to be working as expected:
Included 3 zips inside my submission all of which were unzipped with their names. 

<img width="1211" alt="screen shot 2017-11-07 at 1 57 42 pm" src="https://user-images.githubusercontent.com/28552312/32520116-b9bc16da-c3c3-11e7-9e58-b3b80da42dea.png">
<img width="773" alt="screen shot 2017-11-07 at 1 57 23 pm" src="https://user-images.githubusercontent.com/28552312/32520117-b9d1ccfa-c3c3-11e7-9e86-40170a0d1075.png">

**Comment by ckcollab** [comment]
@madclam have you had a chance to test this yet?

**Comment by madclam** [comment]
I retested and have the same problem. See: http://codalab15-azure.eastus.cloudapp.azure.com/competitions/80

I made Eric an admin.

### Good datasets
This competition was loaded with dataset AutoDL_input_data_1_1_80 (also found in my_datasets under key fd59905a-01fb-4598-9a57-5fcce4a9e796). It contains a group of 5 datasets.

### Bad datasets
I then uploaded these 5 datasets one by one and merged them into input_data_1 (key 0925f6c5-a717-4829-8f2b-a80e5a16d93e)
and replaced the first input_data by the second one.

### Successful submission
With the first dataset, the sample submission finished fine:

2 | Nov. 5, 2017, 12:57 a.m. | guyon | 697 | AutoDL_sample_code_submission.zip | Finished | True | 0.8140
-- | -- | -- | -- | -- | -- | -- | --

### Failed submission
With the merge dataset, the SAME submission failed:


4 | Nov. 11, 2017, 3:48 a.m. | guyon | 704 | AutoDL_sample_code_submission.zip | Failed
-- | -- | -- | -- | -- | --



Error: 
Traceback (most recent call last):
  File "/worker/worker.py", line 272, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 141, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 141, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 92, in get_bundle
    urllib.urlretrieve(url, bundle_file.name)
  File "/usr/local/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/usr/local/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'dataset_data_file/None/3c10b/dorothea.zip'

**Comment by madclam** [comment]
Tested on http://codalab15-azure.eastus.cloudapp.azure.com/competitions/80
