### ISSUE TITLE
Detailed results empty

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2027]
So you can download a detailed result, but the zip is empty...? 

https://codalab.lri.fr/competitions/48

**Comment by Tthomas63** [comment]
See PR #2039 

Pushed to `http://codalab15-azure.eastus.cloudapp.azure.com/`. Working, and displays as follows for the following competition/submission: 

- Doesn't download
- Displays in iFrame

http://codalab15-azure.eastus.cloudapp.azure.com/competitions/49#results

<img width="1250" alt="screen shot 2017-11-07 at 1 41 25 pm" src="https://user-images.githubusercontent.com/28552312/32519453-ab021c18-c3c1-11e7-87c3-31ea3b48842f.png">
<img width="1197" alt="screen shot 2017-11-07 at 1 41 16 pm" src="https://user-images.githubusercontent.com/28552312/32519454-ab1d6b12-c3c1-11e7-8aec-386814cbc4ba.png">

**Comment by ckcollab** [comment]
@madclam we believe this should be working now on staging-azure
