### ISSUE TITLE
Docker testing

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2031]
## Participant dockers:
We should disable completely until fixed or at least disable them by default when we upload a new competition.

* docker images containing underscores cause errors.
* submitting with docker madclam/codalab:anaconda.4.4.0 consistenly crashes the LRI server.
(but seems that it is not a real crash, it just stops responding while it is downloading the image and starting up the new container).
* auto-migration ignores participant dockers

**Comment by ckcollab** [comment]
Resolved in #2032

**Comment by madclam** [comment]
Underscore in docker works:
![image](https://user-images.githubusercontent.com/7594063/32527894-01840c4a-c3e5-11e7-9c4d-ee2343e1d4be.png)
https://codalab.lri.fr/competitions/41
![image](https://user-images.githubusercontent.com/7594063/32527923-290609da-c3e5-11e7-9fa0-b91c12a5bd7e.png)

**Comment by madclam** [comment]
madclam/codalab:anaconda.4.4.0 no longer crashes LRI server. We checked the code actually runs in the prescribed docker by listing the '/' directory, which contains a special file.
