### ISSUE TITLE
Zip files references from YAML file cannot have underscores

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2035]
In Codalab v1, zip file names with underscores for datasets, scoring program, etc. were accepted. This is no longer the case.
https://www.dropbox.com/s/bsrxgkz4pxgka1m/competition_mscoco_OpenEnded.zip?dl=0

This is the fixed archive:
https://www.dropbox.com/s/wck8ougv1dnlfvc/Archive.zip?dl=0
and the fixed competition:
https://codalab.lri.fr/competitions/edit_competition/72

**Comment by ckcollab** [comment]
I believe this is actually due to a bad file format problem, was fixed by editing the yaml and re-saving it.
