### ISSUE TITLE
Ingestion program bugs

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2047]
1) When an ingestion program is loaded in a competition bundle, it gets entered in "My datasets" as "Reference data"
Example:
AutoDL_ingestion_program_1_80 | 9605932a-bac1-427e-b206-e49e5cae454a | None | Reference Data
-- | -- | -- | --

It should be "Ingestion program" otherwise is cannot be accessed from the correct menus in the editor.
See: http://codalab15-azure.eastus.cloudapp.azure.com/competitions/80

**Comment by ckcollab** [comment]
Fixed this on develop, is there a particular server you'd like me to deploy to?
