### ISSUE TITLE
Missing values in leaderboard

### ISSUE THREAD

**Issue by felipebravom** [codalab/codalab-competitions#2048]
Hi,
I'm hosting a competition that has multiple subtasks (one learderboard per subtask) in one single competition. We are allowing participants to participate in any subtask they want (they basically submit the predictions associated with the substaks they are participating). I'm planning to handle incomplete submissions this by assigning missing values to the unsubmitted metrics. Is there a way to set leaderboard metrics to Nan or something equivalent?

I tried the following:

r_05_1_ei_anger_05_1_es:nan
r_ei_joy_es:nan
r_oc_macro_avg_es:nan
r_ei_sadness_en:1.0
r_ei_joy_ar:nan
r_05_1_ei_joy_es:nan
r_05_1_ei_joy_en:1.0

but codalab is converting the nan values to 0.0.

Thanks
Felipe

**Comment by ckcollab** [comment]
Could you maybe set the value to something outside your expected range, like -10? I believe the way it's stored in the database is decimal?

**Comment by felipebravom** [comment]
Thanks! I'll do that then!
Cheers.

**Comment by ckcollab** [comment]
No problemo, hope that works :)
