### ISSUE TITLE
Set a competition-wide docker, instead of fine-grained dockers

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2049]
Instead of having a docker image for:

 - participant code
 - scoring program
 - ingestion program

Just have 1 default docker image for the competition.

**Comment by Tthomas63** [comment]
See pull request #2050

**Comment by Tthomas63** [comment]
Currently on http://codalab15-azure.eastus.cloudapp.azure.com/ for QA/Review

**Comment by madclam** [comment]
I ran the following tests:
1) In competition http://codalab15-azure.eastus.cloudapp.azure.com/competitions/87
- changed with editor Competition docker image: madclam/codalab:anaconda.4.4.0
- re-ran submission 729 in the "Submissions" admin panel (this gave submission 738).
As can be seen, submission 738 did NOT get run into docker madclam/codalab:anaconda.4.4.0
![image](https://user-images.githubusercontent.com/7594063/32864239-34474b5e-ca13-11e7-83b4-ac02611c60c0.png)

2) In the same competition, I re-uploaded the same submission directly from "Submit/View results" WITH madclam/codalab:anaconda.4.4.0 as participant docker [NOTE: THIS FEATURE SHOULD BE DISABLED!] This ran fine in the docker specified as:
![image](https://user-images.githubusercontent.com/7594063/32864321-94d465e2-ca13-11e7-94fb-440038c1b6bf.png)

3) I redid the same thing WITHOUT specifying a participant docker and got:
![image](https://user-images.githubusercontent.com/7594063/32864431-f426997a-ca13-11e7-90ed-7b369c7fcfb3.png)

4) I changed again the organizer docker with the editor to:
- Competition docker image: lisesun/codalabautoml2016:3.0
- I made again the sample submission via "Submit/View results"
it failed with 
Unable to find image 'lisesun/codalabautoml2016:3.0' locally
docker: Error response from daemon: pull access denied for lisesun/codalabautoml2016, repository does not exist or may require 'docker login'.
See 'docker run --help'.

5) Replaced Lisheng's docker by continuumio/anaconda:latest
- Competition docker image: continuumio/anaconda:latest
- I made again the sample submission via "Submit/View results"
This ran in the correct docker
![image](https://user-images.githubusercontent.com/7594063/32865540-6b06115c-ca18-11e7-905c-11374178eca9.png)

6) I ran the same thing, but this time:
- Different dockers for organizer (continuumio/anaconda:latest) and participant madclam/codalab:anaconda.4.4.0)
- However the scoring program and the participant submission both got run into
madclam/codalab:anaconda.4.4.0. THIS IS INCORRECT.
![image](https://user-images.githubusercontent.com/7594063/32865568-85163edc-ca18-11e7-8099-6358a739c3dc.png)

Summary: Please DISABLE participant dockers:
![image](https://user-images.githubusercontent.com/7594063/32865688-064f561e-ca19-11e7-90fe-21880c36e89e.png)

**Comment by madclam** [comment]
All done including testing YAML competition_docker_image.
