### ISSUE TITLE
Duration zero

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2052]
When we submit code that is run by an ingestion program, the duration is that of the code submitted, not that of the ingestion program:
![image](https://user-images.githubusercontent.com/7594063/32907556-3d268d6e-cab5-11e7-8ec5-a4f62f99c619.png)

Can we recuperate the duration of the ingestion program to display on the leadeboard?

**Comment by ckcollab** [comment]
Should we count both the time for the ingestion program and the time for the submission program as the same? So if either is running, it keeps ticking the duration? Or, we could track them separately?

**Comment by madclam** [comment]
Let's track them separately. It will be different needs for different scenarios.

**Comment by madclam** [comment]
Which staging server?

**Comment by ckcollab** [comment]
Note to self: just need to merge + push this to staging
