### ISSUE TITLE
Detailed results

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2055]
Why do we need the scroll bar in the left?
Can we just show the whole page as before?

![image](https://user-images.githubusercontent.com/7594063/32916064-c7385950-cacf-11e7-8e71-4ba3078689a1.png)

**Comment by Tthomas63** [comment]
I am unsure why this is. Looking at the code the IFrame should be full height?

**Comment by ckcollab** [comment]
Which competition is this on? I reverted to old styling on lri and new prod

**Comment by madclam** [comment]
I do not know whether this is related, but now detailed results are busted.
From https://competitions.codalab.org/competitions/7451

![image](https://user-images.githubusercontent.com/7594063/32963686-a503cdd6-cb85-11e7-8609-ddc30519e6f7.png)

**Comment by Tthomas63** [comment]
The issue with detailed results on that competition seems to be specific to the submission. Not all of those submissions generated `detailed_results` it looks like. However when I created a new competition from scratch I was able to retrieve detailed results. We can add a check here to prevent the user from being given a 404.

Also in regards to the styling, I believe I may have a fix, as it seems the styling we have now should be working, but is not. Specifying height as `100vh`, or 100% view height seems to give us the correct behavior.

**Comment by madclam** [comment]
Competitions before nov 16, 2017, restyle detailed results with <pre> tag:

**Comment by madclam** [comment]
Detailed results disappeared from AutoML competition:
https://competitions.codalab.org/competitions/2321

**Comment by ckcollab** [comment]
NOTE: Eric try to get `<pre>` in there

**Comment by madclam** [comment]
The field is now bigger but still we have this scroll bar and cannot see all the results at once, can we just get rid of it?
![image](https://user-images.githubusercontent.com/7594063/33109377-02e848c8-cef6-11e7-9b92-4da176c592c2.png)

**Comment by ckcollab** [comment]
After attempting for a while it is not-so-easy to remove that scrollbar. Also, forcing in `<pre>` is fairly difficult.

It shouldn't be too terrible for each competition using `detailed_results` to add in `<pre>` to the HTML? This covers the case where people *don't* want `<pre>` which we'd have to handle, if we somehow forced it in...
