### ISSUE TITLE
Clean up old branches

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2056]
There are quite a few old branches left behind from merged/deleted/closed pull requests, we should get rid of as many as we can.

**Comment by Tthomas63** [comment]
Seems that branches that have already been deleted are still displaying.

Charts-js was deleted here: https://github.com/codalab/codalab-competitions/pull/1731 but is still displaying, and a few other examples of this are available. 

Might not be a bad idea to use:

```git remote prune origin```

**Comment by Tthomas63** [comment]
@ckcollab Review any left over branches?

**Comment by ckcollab** [comment]
![image](https://user-images.githubusercontent.com/2185159/33102956-26b7db6e-ced4-11e7-8e05-319bac0e372b.png)

Feels good! Thanks again Ty-bro
