### ISSUE TITLE
Script to re-write multidataset metadata

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2057]
Call `write_multidataset_metadata` if `sub_data_files` count > 0. This replaces `metadata` with SAS urls.

After that we need to replace references to this metadata file, i.e. if replacing `input_data`:

```
>>> # Sign metadata urls
>>> phase.input_data_organizer_dataset.write_multidataset_metadata()
>>>
>>> # Actually point to this new metadata
>>> phase.input_data = phase.input_data_organizer_dataset.data_file.file.name
>>> phase.save()
```

This needs to be done for:

 - input data
 - reference data

**Comment by ckcollab** [comment]
I'd say this is very low priority since very few competitions used this, may be a better use of time to manually call the `write_multidataset_metadata` as needed.

**Comment by LishengSun** [comment]
Hi Eric,

I just tried to submit a solution to AutoML Round0 (https://competitions.codalab.org/competitions/7471#participate-submit_results) and it failed with error: 

`Traceback (most recent call last):
  File "/worker/worker.py", line 272, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 141, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 141, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 92, in get_bundle
    urllib.urlretrieve(url, bundle_file.name)
  File "/usr/local/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/lib/python2.7/urllib.py", line 469, in open_file
    return self.open_local_file(url)
  File "/usr/local/lib/python2.7/urllib.py", line 483, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'datasets/None/74e58f33-2272-4aac-b436-0f0c89d3ce60/dorothea.zip'`

**Comment by ckcollab** [comment]
I will correct this ASAP thanks for reporting it!

**Comment by ckcollab** [comment]
@LishengSun I was able to re-run submissions and they made it to "Running" so I believe this is fixed now
