### ISSUE TITLE
Team participation in SemEval-2018 Task 9: Hypernym Discovery

### ISSUE THREAD

**Issue by lalchand-pandia** [codalab/codalab-competitions#2058]
Hi,
I created a team in this competition . Previously I added myself as single participant and was accepted . Now when I tried to register team it is showing content not available. Please help in this regard. Sorry I did not read the FAQ first, as initially I was not sure about team.
![codalab](https://user-images.githubusercontent.com/20551584/32988648-497b78b0-cd2e-11e7-9087-2920dc6d10f1.png)
![codalab1](https://user-images.githubusercontent.com/20551584/32988649-4ef95460-cd2e-11e7-95c0-65274ac68b0e.png)

**Comment by Tthomas63** [comment]
Hello,

This appears to have been a bug with teams, triggered by not having an `active` phase for the competition. This should be working correctly now!

Thanks and best regards.

**Comment by lalchand-pandia** [comment]
Thanks it is working
