### ISSUE TITLE
Competitions test site is down

### ISSUE THREAD

**Issue by felipebravom** [codalab/codalab-competitions#2062]
Hi,
The competitions-test site is down: https://competitions-test.codalab.org/  ?
Can you please give me an estimate time when will be up again. Debugging competitions on the official version of Codalab is much slower.
Cheers,
Felipe

**Comment by ckcollab** [comment]
I was able to connect to it just now? We will probably be pulling this server down soon, a better option is to test on:
http://codalab15-azure.eastus.cloudapp.azure.com

**Comment by felipebravom** [comment]
Thanks!
