### ISSUE TITLE
New posts in forums are put on the top instead of the bottom

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#2064]
Hello,

Recently I observed that a post in a forum topic is not shown at the bottom but at the top, so the discussion doesn't make any sense now.

See a screenshot from https://competitions.codalab.org/forums/14067/2179/ below

![bildschirmfoto_2017-11-21_08-13-29](https://user-images.githubusercontent.com/11850778/33059431-6f1e4b6c-ce94-11e7-96d5-a8405f7bb085.png)

**Comment by Tthomas63** [comment]
Hello thanks for bringing this to our attention,

This appears to be an issue with no explicit ordering given to the associated posts. A fix for this will be pushed soon!
