### ISSUE TITLE
New participant's numbers start from "1"

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#2065]
In the list of participants, all items were sorted chronologically (as organizer, I had number "1", for instance).

Recently, new members are added on the beginning the list and shifting the existing number (which are perhaps not IDs)

See the screenshot:

![bildschirmfoto_2017-11-21_08-12-41](https://user-images.githubusercontent.com/11850778/33059555-fba71e74-ce94-11e7-9caa-4d8140122483.png)

**Comment by ckcollab** [comment]
Participants should be added to the end of the list now, thanks for reporting this!
