### ISSUE TITLE
Page too narrow

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2070]
The frame of a page is narrower than the table:
![image](https://user-images.githubusercontent.com/7594063/33109493-ae6fa128-cef6-11e7-95c4-ea06771ca5be.png)

**Comment by Tthomas63** [comment]
Which competition was this on, or is it currently affecting all competitions?

**Comment by ckcollab** [comment]
This is on every competition if you have long filenames uploaded I believe.
