### ISSUE TITLE
Output zip files broken

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2072]
It is no longer possible to download meaningful zip file containing the results of prediction step, scoring step, etc. The zipfiles are corrupted.
![image](https://user-images.githubusercontent.com/7594063/33109778-61d6b804-cef8-11e7-9d82-0a4443639ff7.png)

**Comment by ckcollab** [comment]
Which ones are broken? I was just able to download each one from the last submission in this competition:

https://competitions.codalab.org/my/competition/2321

**Comment by madclam** [comment]
You can download but the contents of the zipfile is corrupted.

**Comment by yuantailing** [comment]
It's not a .zip file, It's accually a 4 bytes file with raw text `None`.
