### ISSUE TITLE
Wrong score showing in various places

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2077]
In competitions having several scores such as https://competitions.codalab.org/competitions/17616
there is one score that serves as ranking score in the leaderboard.

In this example, it is the column with rank 1, called label: `<Rank>`
Here is the YAML for the leaderboard:
leaderboard:
    leaderboards:
        Results: &RESULTS
            label: RESULTS
            rank: 1
    columns:
        set1_score:
            leaderboard: *RESULTS
            label: Set 1
            numeric_format: 4
            rank: 2
        set2_score:
            leaderboard: *RESULTS
            label: Set 2
            numeric_format: 4
            rank: 3
        set3_score:
            leaderboard: *RESULTS
            label: Set 3
            numeric_format: 4
            rank: 4
        set4_score:
            leaderboard: *RESULTS
            label: Set 4
            numeric_format: 4
            rank: 5
        set5_score:
            leaderboard: *RESULTS
            label: Set 5
            numeric_format: 4
            rank: 6
        ave_score:
            leaderboard: *RESULTS
            label: `<Rank>`
            numeric_format: 4
            rank: 1
            computed:
                operation: Avg
                fields: set1_score, set2_score, set3_score, set4_score, set5_score
        Duration:
            leaderboard: *RESULTS
            label: Duration 
            numeric_format: 2
            rank: 7

In the RESULTS tab the leaderboard functions properly.
![image](https://user-images.githubusercontent.com/7594063/33112787-ce408540-cf09-11e7-8c51-e5d267227454.png)

But, in the admin SUBMISSIONS panel, what is shown as score is "set1_score" (wrong column):
![image](https://user-images.githubusercontent.com/7594063/33112697-653295b6-cf09-11e7-9fba-6a1e10bebb0a.png)

The CSV is also messed up:
![image](https://user-images.githubusercontent.com/7594063/33112727-85d45ed0-cf09-11e7-90be-7fab532bf33c.png)

and the summary panel of top ranking leaders:
![image](https://user-images.githubusercontent.com/7594063/33112757-a98160a8-cf09-11e7-8b14-5a9ec7522b26.png)

all show set1_score instead of `<rank>`

**Comment by Tthomas63** [comment]
- Removing arbitrary tabs and make sure outputted CSV's columns/tabs match. 

- Also fix what scoring column we use in `top-three` and `submissions` admin page.

**Comment by hazirbas** [comment]
Hi @Tthomas63 
Can you please explain more how to set this?.
Thanks,
Caner

**Comment by Tthomas63** [comment]
Hello Caner(@hazirbas),

The main `scoring` metric is the metric with the lowest ordering. Currently there is an issue with top three, and the submissions page for admins not grabbing the correct metric on which to score. 

Thanks, and best regards,
Tyler

**Comment by hazirbas** [comment]
Hi @Tthomas63 ,
Thanks for the response. Does this mean, if I have many column_groups and leaderboards, metrics' rank should be unique and different than each other?

Because, when I use rank starting from 1 to number of metrics, the order of the column groups was wrong on the leaderboard. For example, I have column groups errors-accuracy-runtime, and I have two metrics for errors, 2 for accuracy and 1 for runtime. When I rank them with order 1 to 5, in the leaderboard, runtime was before accuracy although I put rank for column groups too.

Thanks,
Caner

**Comment by Tthomas63** [comment]
Hello @hazirbas,

Yes, I believe this should be the case. If this is not the case, would you be able to setup a competition that shows this so we can try to reproduce and debug it? I believe the competition YAML references this as `rank` while the `edit` page for a competition references this as `Ordering`. 

Please see: [Wiki: Competition Yaml Setup](https://github.com/codalab/codalab-competitions/wiki/Organizer_Codalab-competition-YAML-definition-language#section-3-leaderboard-properties) for more info.

**Comment by ckcollab** [comment]
To fix:
- [ ] Submissions page
- [ ] CSV

**Comment by Tthomas63** [comment]
@madclam Concerning the CSV format, it appears to be a client side issue with excel.

Viewing the CSV's as plain text in VIM from large competitions looks fine. It appears there are no added tabs or formatting.  

<img width="870" alt="screen shot 2017-12-13 at 1 42 29 pm" src="https://user-images.githubusercontent.com/28552312/33963971-b81cf952-e00b-11e7-81bc-2b3c9e901edb.png">

Thanks,
