### ISSUE TITLE
Queues creation broken

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2079]
The following is broken on both 
- Public server: https://competitions.codalab.org
- LRI server
But works on staging server http://xx.90.xxx.x/

When going into "Worker Queue Management"

![image](https://user-images.githubusercontent.com/7594063/33142299-cd9899be-cf6a-11e7-99a7-ead767abdb8d.png)

When clicking on save, we get:

![image](https://user-images.githubusercontent.com/7594063/33142277-b4fe421e-cf6a-11e7-8a87-94a382e8a8ba.png)

**Comment by ckcollab** [comment]
Should be fixed now, SSL problem
