### ISSUE TITLE
[Object detection(bounding box)] submission fail without any information to fix the submission

### ISSUE THREAD

**Issue by chunfuchen** [codalab/codalab-competitions#2081]
Hi, I follow the instructions on COCO website to prepare my submission for both test-dev2017 and val2017.
I have checked my filename several times and I confirm that the file names are correct.

I was able to evaluate val2017 on my local machine based on COCO API; however, after I upload the same file (package it as a zip) to the server, the status becomes failed.
I also upload my results on test-dev2017, and it also fails to evaluate my submission.

When I try to retrieve the log to see what is wrong with my submission, I will the message like "There was an error retrieving file 'stderr.txt'. Please try again later or report the issue."
No idea how to revise my submission...

Does anyone have the similar experience and how do you resolve it? Thanks.

**Comment by ckcollab** [comment]
Could you link me to the competition, please? Thanks!

**Comment by chunfuchen** [comment]
how do I get the link? 
Here is the link when I try to retrieve the log.
https://competitions.codalab.org/my/competition/submission/425069/stdout.txt

**Comment by chunfuchen** [comment]
Does anyone counter the same issue?

**Comment by Tthomas63** [comment]
I think this problem is typically due to grabbing output from a failed or currently processing submission, can you confirm that's the situation in your case?

**Comment by chunfuchen** [comment]
my submission are all failed; however, I also try to submit one job that succeeded before.
