### ISSUE TITLE
Add new columns in the leaderboard

### ISSUE THREAD

**Issue by pedrada88** [codalab/codalab-competitions#2087]
Is it possible to add new columns (new measures, etc.) in the leaderboard once a competition is set? It seems it is not possible from the Edit page, and I was wondering if there is some workaround to modify this, or if otherwise the only solution is to remove the competition and create a new one (which would be a great problem as our competition has been open for a few months already...)

**Comment by ckcollab** [comment]
Unfortunately it appears that is not an option currently; unfortunately, you're right the only way to do this would be to re-create the competition. In version 2, when we re-do things from the ground up, this will definitely be capable.
