### ISSUE TITLE
There was an error retrieving file 'stdout.txt'. Please try again later or report the issue.

### ISSUE THREAD

**Issue by geekvc** [codalab/codalab-competitions#2088]
https://competitions.codalab.org/competitions/5181#participate
The test-dev2017 boxes evaluation failed.
I have submit several times recently.
Thank you very much.

**Comment by geekvc** [comment]
![image](https://user-images.githubusercontent.com/10766005/33221852-cc2c7f9e-d18d-11e7-9e45-5c7861573326.png)

**Comment by ckcollab** [comment]
The stdout may not have been generated because the program was unable to start? Did the submission work previously and then suddenly start failing?

**Comment by geekvc** [comment]
Yes, I used the chrome and firefox browser to upload my detection result, the evaluation program seems not start, the status change from "submitting" to "failed" quickly.
The error log as follows:
`There was an error retrieving file 'stderr.txt'. Please try again later or report the issue.`
The output log as: 
`There was an error retrieving file 'stdout.txt'. Please try again later or report the issue.`
Thank you for your attention!

**Comment by geekvc** [comment]
I submitted the val2017 bbox evaluation successfully in November 11th. 
However,  when I submit the val2017 bbox evaluation again recently, the evaluation failed. 
I think there is something wrong with the evaluation program.

**Comment by Tthomas63** [comment]
@geekvc are you potentially submitting to the wrong phase?
