### ISSUE TITLE
LITS Challenge Error in Leaderboard

### ISSUE THREAD

**Issue by PatrickChrist** [codalab/codalab-competitions#2090]
Hey Codalab Team,

I am organizer of the LITS Challenges www.lits-challenge.com. Since your new update the leaderboard shows the following message:
```
ERROR: Improperly configured leaderboard or scoring program. Some scores have NaN! Please check your leaderboard configuration and scoring program for the competition!
Bad Scores:
```
Could you help me with this issue?
Thanks,
Patrick

**Comment by ckcollab** [comment]
@Tthomas63 will take a look at this tomorrow

**Comment by Tthomas63** [comment]
We added a feature to try and help some organizers debug leaderboard issues, which checks for NaN scores. Your competition works with these scores, which is causing it to throw warnings. Your competition should not be affected really, it will just display these warning messages. 

I am working on making these into a smaller accordion element on the page, and it will also be removed from the results page so only organizers or admins will see this under `submissions` in the new accordion design. This should be on it's way shortly!

**Comment by Tthomas63** [comment]
This change has been pushed to production, please let us know if this correctly addresses your issue!

**Comment by ckcollab** [comment]
Thanks @tthomas63 :)
