### ISSUE TITLE
XSS in detailed results

### ISSUE THREAD

**Issue by yuantailing** [codalab/codalab-competitions#2091]
Detailed results page is provided by user (competition organizer). Arbitrary JavaScript may be injected to steal user (competitor) cookies. I think it should be provided in a different domain (or port), or be provided as a download link.

**Comment by ckcollab** [comment]
Good point, looking into this more.. this seems like a good option as well:
https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

So just adding `sandbox` as an attribute could fix this?

**Comment by ckcollab** [comment]
I tested this locally and it appears to be fine, let me know if `sandbox` causes any problems.

**Comment by yuantailing** [comment]
I want to use JavaScript ([d3js](https://d3js.org/), [chartjs](http://www.chartjs.org/samples/latest/charts/bar/vertical.html), etc.) to show detailed results, isn't it a good idea?
Could you please help me to add `sandbox="allow-scripts"`? In my tests, user cannot access cookie from sandbox without an `allow-same-origin` option, so `allow-scripts` is safe.

**Comment by ckcollab** [comment]
Should had `allow-scripts` now as well, please let me know if this doesn't work for you and thanks for the help!

**Comment by yuantailing** [comment]
I noticed that `sandbox allow-scripts` doesn't work, it should be `sandbox="allow-scripts"`.

**Comment by ckcollab** [comment]
Should be fixed now, thanks
