### ISSUE TITLE
Remove Outercurve from messages

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2092]
Hello ,

This is a message from the organizer for the competition:

XXX
Message:

YYY
Thanks,

CodaLab Team
Unsubscribe or manage notification settings | Privacy policy

The Outercurve Foundation 
401 Edgewater Place, Suite 600, Wakefield, MA 01880

**Comment by madclam** [comment]
When we do mass mailing as admin, we should add:
CodaLab Team
Unsubscribe or manage notification settings | Privacy policy

**Comment by Tthomas63** [comment]
- Verify what `unsubscribing` does when using that feature. Where does this information go?

- Whenever we send mass mail, send an `unsubscribe` option. Have a uniform mass mailing option.

**Comment by Tthomas63** [comment]
Remove reference to outer-curve completely
