### ISSUE TITLE
Permission to detailed results

### ISSUE THREAD

**Issue by yuantailing** [codalab/codalab-competitions#2093]
In current codalab, `detailed_results.html` is treated equivalently to other **file_type**s, only competition organizer and submission owner can download it.

I noticed that user can see links to `detailed_results.html` from leaderboard, so I think everyone should have the access to all **detailed results** on the leaderboard, as if **detailed results** and **results** has the equivalent permission. Detailed results is not a secret indeed, it's a kind of results.

I think this feature would help participants to share their results to others, and the others have no necessary to login. I wonder whether my above thoughts are correct? Here is some code to implement this feature (I have not tested this code):

In [web/views.py](https://github.com/codalab/codalab-competitions/blob/67d20a29d4c59cab95d194e5175c0cde08676c6a/codalab/apps/web/views.py#L1145) class MyCompetitionSubmissionOutput

```
published_by_leaderboard = False
if filetype == 'detailed_results.html' and PhaseLeaderBoardEntry.objects.filter(result=submission).exists():
    # check whether user can access this competition
    if competition.published or competition.secret_key == request.GET.get("secret_key", None):
        published_by_leaderboard = True
    elif request.user:
        if competition.creator == request.user or request.user in competition.admins.all() or \
                        competition.participants.filter(user=request.user).exists():
            published_by_leaderboard = True

if not submission.is_public and not published_by_leaderboard:
    if not request.user:
        raise Http404()  # or redirect to login
    if (competition.creator != request.user and request.user not in competition.admins.all()) and \
                    request.user != submission.participant.user:
        raise Http404()
```

and remove `LoginRequiredMixin`

**Comment by Tthomas63** [comment]
@madclam What is your opinion on this? Currently they are downloadable for users if the submission owner has set the submission as public. This allows for what is described here; Users can still see a link to the detailed results for other's submissions, but they cannot access them. Should these be public by default or should users control the permissions of their detailed results?

**Comment by ckcollab** [comment]
BLL! :)

**Comment by ckcollab** [comment]
Isabelle says these should be see by everyone, so this change is OK

**Comment by ckcollab** [comment]
@yuantailing I just implemented this, please let me know if you see any logic errors! thanks for your psuedo code :)

**Comment by yuantailing** [comment]
Oh, no! Since `filetype == 'detailed_results.html'` is not verified, we can download other's `input.zip`.

**Comment by yuantailing** [comment]
And there is an potential BUG:

In the future, we may allow users to remove accounts ( #2006, #1958 ), then `submission.participant.user` may be set NULL. We have not decided whether to delete all submissions of that user. If submissions are not deleted, all submissions of that user will be accessible to anonymous users (whose `request.user` is NULL).

So I think this check is necessary:
```
    if not request.user:
        raise Http404()  # or redirect to login
```

**Comment by ckcollab** [comment]
@yuantailing thanks for double checking this, I believe latest commit should fix this?

**Comment by yuantailing** [comment]
I tested it, all permissions are OK, thank you!

I'm sorry that I made a mistake. User not login is `AnonymousUser`, not `NULL`, so `request.user != submission.participant.user` is always `False`, this check is not necessary:

```
    if not request.user:
        raise Http404()  # or redirect to login
```

**Comment by ckcollab** [comment]
Cool, removed the check... thanks so much! :)
