### ISSUE TITLE
it failed when I submitted to test-dev2017.

### ISSUE THREAD

**Issue by shouwangzhe134** [codalab/codalab-competitions#2106]
There was an error retrieving file 'stdout.txt'. Please try again later or report the issue.
There was an error retrieving file 'stderr.txt'. Please try again later or report the issue.
There was an error retrieving file 'output.zip'. Please try again later or report the issue.

**Comment by shouwangzhe134** [comment]
can anyone help me?It bothers me all the day.

**Comment by ckcollab** [comment]
Was the submission marked as "Finished" successfully but you still could not download details?

**Comment by ckcollab** [comment]
Let me know if you are experiencing this on submissions that "Finished" properly, I think this may only happen on failed submissions?

**Comment by shouwangzhe134** [comment]
The submission was marked as "Failed".

**Comment by shouwangzhe134** [comment]
Can you tell me what I should submit in my result.zip?

**Comment by shouwangzhe134** [comment]
![result](https://user-images.githubusercontent.com/19248726/33832079-8794d0f4-deb5-11e7-98b3-cbde42e6afdf.PNG)

**Comment by shouwangzhe134** [comment]
The submission was marked as "Failed".
The JSON file was named "detections_test-dev2017_faster-RCNN_results.json".I place the JSON file into a zip file named "detections_test-dev2017_faster-RCNN_results.zip".
I cannot submit my result successfully. Can you help me? Thank you very much!

**Comment by shouwangzhe134** [comment]
![result](https://user-images.githubusercontent.com/19248726/33835363-341a70d0-dec1-11e7-89bf-e5476aef300f.PNG)

**Comment by ckcollab** [comment]
If your submission fails you won't be able to grab stdout stderr sometimes, we're looking into ways to pass the stderr/stdout even if submission fails early.

Can you run the code on your own machine and see if you can find any error messages this way?

**Comment by FlavioAlexander** [comment]
@ckcollab I think this is related to the issue I was working on which should be fix by now, but we need to install the missing package #2119

**Comment by ckcollab** [comment]
Should be fixed via #2119 ty @FlavioAlexander

**Comment by shouwangzhe134** [comment]
It is okay now, I can test my result on the servers.
Thank you!
