### ISSUE TITLE
cannot delete the competitions

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2107]
Hi,
I cannot delete the competitions, I have created. I get the following error.

The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

**Comment by ckcollab** [comment]
Which competitions are these and what is your username and email? Thanks, we've seen this problem reported a few times -- trying to find the consistency between broken competitions.

**Comment by ckcollab** [comment]
You can send me this information eric@ckcollab.com so it's not public :)

**Comment by hazirbas** [comment]
Hi @ckcollab ,
Did you find anything yet? It would be nice to get rid of all trash competition I have created :P.
Thanks,
Caner

**Comment by ckcollab** [comment]
It should be working now, let me know if it doesn't thanks!
