### ISSUE TITLE
Plot showing high scores

### ISSUE THREAD

**Issue by Cyvhee** [codalab/codalab-competitions#2108]
Hi

When participants upload their submissions, a plot is displayed showing the highest scores and the total daily submissions. Some things are not entirely clear to me:
- The leaderboard displays participants’ scores according to four metrics (precision, recall, F1, accuracy). Can I somehow define which metric should be presented in the plot?
- The plot's y-axis has values ranging from -0.2 to 1.2. I was wondering how that is possible, since it displays scores and no error rates?
- When editing the Leaderboard, one can set a “Selection default”, what does this parameter exactly mean?

Any clarifications are very welcome.

Regards,
Cynthia

**Comment by hazirbas** [comment]
Hi, I also need to know this urgently. Can anyone help us?
Thanks.

**Comment by Tthomas63** [comment]
Hello Cynthia and @hazirbas,

The default `main` metric is the metric with the lowest ordering. This is the main metric which we rank other submissions against. 

The y-axis should have 2 different scales, one for submission count, and one for the main scoring metric.

Also concerning `selection default`, I am unsure as this is an old feature. I will try to find out more in regards to this.

Best regards,
Tyler

**Comment by Cyvhee** [comment]
Hi Tyler

Thank you for your response! Will you keep us informed about the `selection selection` default parameter? Also, it is not entirely clear to me yet why the y-axis showing submission scores ranges from -0.2 to +1.2, instead of going from 0 to 1.

Thank you and kind regards,
Cynthia

**Comment by Cyvhee** [comment]
Hi Tyler

Thank you for your response!

What do you mean exactly by "metric with the lowest ordering"?
Also, it is not entirely clear to me yet why the y-axis showing submission scores ranges from -0.2 to +1.2, instead of going from 0 to 1, is it meant to display error rate?

Will you keep us informed about the selection selection default parameter? 

Thank you and kind regards,
Cynthia

**Comment by Tthomas63** [comment]
Hello Cynthia,

No problem, and thank you for asking questions!

In the edit page, under the leaderboard sections, there is an `ordering/ranking` field for each metric. The metric with the lowest ordering should be the `default`.

Also in regards to the chart, could you post a link to your competition or the ID so we could take a look? Perhaps it is using a different metric than intended?

As far as the selection default parameter, I believe changing the default 0 to a 1 makes this metric the default sorting/scoring for the results table. Please see [WIki: Leaderboard Features](https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard#2-leaderboard-features) for more information in regards to the leaderboard. 

Please let us know if we can offer any further clarification.

Thanks and best regards,
Tyler

**Comment by Cyvhee** [comment]
Hi Tyler

Thanks for your quick response!

Ok, the ordering of the leaderboard metrics is clear to me now :-).

This is the link to our competition:
https://competitions.codalab.org/competitions/17468, but I also attached a
print screen of the chart. In fact, I think it is strange that the min and
max of the y-axis are 0.2 and 1.2, but perhaps it is not something bit to
worry about.

Thank you and kind regards
Cynthia



2017-12-21 4:35 GMT+01:00 Tyler <notifications@github.com>:

**Comment by Tthomas63** [comment]
Hello Cynthia,

After reviewing the code for the chart, these y-scale values are hard-coded in as suggested mins/maxs for the table itself. If your competition sees values within this range, this is probably the default scale that you will see. So for the metric scoring y-axis, values of -0.1 to 1.2 should be normal, and for submissions the default suggested max is 25. The chart itself should be responsive enough to handle values slightly within or out of this range. 

If this is not satisfactory, it is possible we can tweak these values or look into it, as this is currently the default behavior. Please let us know if you have any further questions!

Best regards,
Tyler

**Comment by Cyvhee** [comment]
Hi Tyler

Ok, this is clear to me now. Thank you very much for the clarification!

Kind regards
Cynthia

2017-12-21 21:13 GMT+01:00 Tyler <notifications@github.com>:

**Comment by Tthomas63** [comment]
Hi Cynthia,

No problem! Glad I could help out.

Best regards,
Tyler
