### ISSUE TITLE
"Submit / View Results" columns titles mismatch

### ISSUE THREAD

**Issue by FinLouarn** [codalab/codalab-competitions#2109]
In the "Submit / View Results" section, there is a bug in the way submission results are displayed.
A second "Score" label is introduced as a column title, which create a mismatch between columns titles and values.
![submit_score_display_bug](https://user-images.githubusercontent.com/6131050/33694971-c18ad11e-daaf-11e7-8562-da23acdcb538.png)

**Comment by ckcollab** [comment]
Is this on the See4C version? We may have fixed that in our latest code here?

**Comment by hazirbas** [comment]
I also have it on a competition I have created on https://competitions.codalab.org

**Comment by ckcollab** [comment]
I see what you're saying now:

![image](https://user-images.githubusercontent.com/2185159/33741051-bd7b7382-db57-11e7-9fac-7fbf80b3403a.png)

**Comment by ckcollab** [comment]
@Tthomas63 will push this today
