### ISSUE TITLE
How can to change the name?

### ISSUE THREAD

**Issue by tuonglc** [codalab/codalab-competitions#2110]
Dears,

How can I change the name to show in my competitions?

Thank you

**Comment by ckcollab** [comment]
Do you mean your username that appears in competitions, or the title of a competition?

**Comment by tuonglc** [comment]
I mean the username appears in competitions. I cannot change it.
Sorry, the question is not clear.

**Comment by ckcollab** [comment]
There is no way to change usernames, unfortunately.
