### ISSUE TITLE
cannot create a competition

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2111]
When I upload my competition.zip file, I get the following error:

duplicate key value violates unique constraint "idx_22420_web_submissionscoreset_key_18c9fa0c10f2fcd0_uniq"
DETAIL:  Key (key, competition_id)=(disp_runtime, 17789) already exists.

And each time the competition_id increases by 1

duplicate key value violates unique constraint "idx_22420_web_submissionscoreset_key_18c9fa0c10f2fcd0_uniq"
DETAIL:  Key (key, competition_id)=(disp_runtime, 17790) already exists.

**Comment by ckcollab** [comment]
How did you resolve this?

**Comment by hazirbas** [comment]
There was repeat of multiple keys, named as "disp_runtime". I removed one of them and it worked.
