### ISSUE TITLE
Submission failed error

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2112]
Hi,
I have created a private competition with id 17796 (username hazirbas). I have uploaded program and reference datasets and linked it to the competition "Test" phase from the Edit. However, I keep getting submission failed error without any stdout.txt or stderr.txt.

program.zip has program/evaluate.py script and in metadata I put the line as follows:
command: python $program/evaluate.py $input $output

What might be wrong? It was working before.
Thanks.

**Comment by ckcollab** [comment]
Is this related to MSCOCO, by the way? If you re-create the competition does it get the same problems?

**Comment by hazirbas** [comment]
No not MSCOCO, dataset is self-created and it repeated many times after I tried to re-create the competition.
I am actually surprised but it mainly started after you guys solved the following issue: 
#2107

**Comment by ckcollab** [comment]
That is interesting, I do not think they are directly related though -- maybe something else around that time was changed?

Could you add me as an admin "eric2"?

**Comment by hazirbas** [comment]
Sure, i added now. It is ok when I run the code locally having the folder structure as:
input/ref/
inout/res/
output/

**Comment by ckcollab** [comment]
Thanks, taking a look now -- warning I may be changing/re-running/messing with stuff!

**Comment by ckcollab** [comment]
The submission never even makes it to processing:

```
worker_site       | 2017-12-12 21:20:53,528 ERROR evaluate_submission dispatch failed (job_id=450351, submission_id=430034)
worker_site       | Traceback (most recent call last):
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 777, in evaluate_submission
worker_site       |     task_func(submission, job_id)
worker_site       |   File "/app/codalab/apps/web/tasks.py", line 377, in score
worker_site       |     score_csv = submission.phase.competition.get_results_csv(submission.phase.pk)
worker_site       |   File "/app/codalab/apps/web/models.py", line 474, in get_results_csv
worker_site       |     csvwriter.writerow(sub_headers)
worker_site       | UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 5: ordinal not in range(128)
worker_site       | 2017-12-12 21:20:53,583 INFO Changed submission status from submitting to failed (id=430034).
```

**Comment by hazirbas** [comment]
Oh that is interesting, I can't think of any reason I may have caused that. Would that relate to my settings in any way?

**Comment by ckcollab** [comment]
I believe I am handling that correctly now, your submissions make it to "Running" at least so far! :)

**Comment by hazirbas** [comment]
Excellent! But I see that the score is not on the top-three and the score on the graph is plotted wrong, but I believe that is because of the ordering mistake I did in the competition.yaml. I will check that later.

Thanks again!

**Comment by ckcollab** [comment]
No problem -- let us know if there any problems, scores/leaderboard have been finicky.
