### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by skrish13** [codalab/codalab-competitions#2115]
I'm sure you guys might have thought about these things but just putting it out there so that anyone interested (including me) can get guidelines on how to contribute to implement these features

- Filtering based on a very simple, generic tag. Ex: NLP, CV, BioMedical etc!
  - we can give the tags to all the competitions manually, not a big task.
- Sorting (which works with filtering options as well) wrt End Date!
  - To start off, just a boolean is also cool, active competitions vs ended competitions.

I can see that there's plenty of other important [stuff](https://github.com/codalab/codalab-competitions/issues/1958) to concentrate on. Are you guys planning on implementing these anytime soon? If not someone can reply with starting points or guidelines such that anyone interested can go ahead and try it. Thanks for the great platform :)

**Comment by ckcollab** [comment]
Thanks for the kind words :)

We're basically feature-freezing v1.5 for now to work on v2, I think we already have similar suggestions to these on that list? If you don't mind, you could close this issue and append ideas that are not already mentioned to the existing thread for v2 ideas? It's OK if there's a duplicate suggestion, just want to avoid that if we can and it's becoming quite large.

Have a good one!

**Comment by skrish13** [comment]
Ah, right. Yeah thats cool. I had checked for similar suggestions but wasn't really able to find it actually. Will append to the existing thread (Y).

**Comment by skrish13** [comment]
quick question @ckcollab , there isnt a way to open a competition webpage on a new tab right? or am i missing something? would it be okay to add this to that list?

Ex: (explaining more if that wasn't put clearly). Someone is browsing through for interesting contests, they'd want to open few competitions each on different tabs rather than view one and come back to home page and view the next and so on.

**Comment by ckcollab** [comment]
Like, you click to view competition in new tab and it doesn't open in the new tab? This is when you click the competition tiles, like so:

![image](https://user-images.githubusercontent.com/2185159/33851899-55f5584a-de6d-11e7-9bf8-f8a171a4f7f8.png)

I've noticed this as well.. would be a nice change potentially but I think it may not be as simple as we'd like given the legacy codebase spaghetti-ness. Will take a look at this quickly!

**Comment by skrish13** [comment]
I'm on firefox and there's no option of opening a competition entry in new tab, no matter where you click, i tried in all obvious places

**Comment by ckcollab** [comment]
I pushed a fix wrapping these containers in plain old links... they should work much more nicely, I tested it myself -- would you mind confirming it's working 100%?! Thanks!

**Comment by skrish13** [comment]
woohoo! Yes. I'll treat you if I ever come to "Coeur d'Alene" (fancy city name).
