### ISSUE TITLE
worker_offline state?

### ISSUE THREAD

**Issue by YikSanChan** [codalab/codalab-competitions#2117]
https://worksheets.codalab.org/bundles/0x2beb0962a9e34732b4ee44de43b87e03/

I try to run above bundle and get worker_offline state. What does it mean and how to solve this? Thank you!

**Comment by FlavioAlexander** [comment]
Hello @YikSanChan, 

This seems like a `worksheets` issue, please create the ticket under their repo [worksheets](https://github.com/codalab/codalab-worksheets)
