### ISSUE TITLE
show_rank in competition.yaml

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2118]
Hi,
`show_rank: False` variable in the comptetition.yaml is not recognized. When the competition is created, all `show_rank` variables of all fields are set to `True` by default.

**Comment by ckcollab** [comment]
This is how Python interprets these I believe, if you remove it completely it should be null (False)?

**Comment by hazirbas** [comment]
Actually show_rank is always set to True, even without putting it in the yaml.

**Comment by ckcollab** [comment]
That is annoying... it looks like it should handle it:

http://yaml.org/type/bool.html

Looking at the code I'm seeing this:

```
                    sdefaults = {
                                    'label' : "" if 'label' not in vals else vals['label'].strip(),
                                    'numeric_format' : "2" if 'numeric_format' not in vals else vals['numeric_format'],
                                    'show_rank' : True,
                                    'sorting' : 'desc' if 'sort' not in vals else vals['sort'],
                                    'ordering' : index if 'rank' not in vals else vals['rank']
                                    }
```

I believe I could change `show_rank` to be set to `True if 'show_rank' not in vals else vals['show_rank']`.. but I'm wondering why this was set to be forced to `True`...

**Comment by hazirbas** [comment]
Hm, couldnt find any clue, maybe better to add if-clause for now.

**Comment by ckcollab** [comment]
@hazirbas are you still having problems with this, should we implement the if statement change? I think we should leave it "as is" for now?

**Comment by hazirbas** [comment]
Yes, I had the problem again, but it is ok to leave it as it is right now.

**Comment by ckcollab** [comment]
Apologies :(
