### ISSUE TITLE
Participant ordered in wrong order

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2127]
In https://competitions.codalab.org/competitions/17767

The column by which the participants should be sorted is average Rank
![image](https://user-images.githubusercontent.com/7594063/33909025-0943f754-df3f-11e7-9541-d656ac208241.png)

but they are wrongly sorted by Set 1

![image](https://user-images.githubusercontent.com/7594063/33908967-e6814564-df3e-11e7-8ffa-c8fda96f63a3.png)

**Comment by ckcollab** [comment]
Setting `selection_default` to 1 for `<Rank>` seems to have fixed it?

![image](https://user-images.githubusercontent.com/2185159/33909883-e21f0eea-df41-11e7-90fb-5feb5e4c4eeb.png)
