### ISSUE TITLE
not found scoring program

### ISSUE THREAD

**Issue by hazirbas** [codalab/codalab-competitions#2129]
Hi,
I am uploading my scoring program and linking it in the phase setting of the competition, but it keeps giving the following error:

`python: can't open file '$scoring_program/evaluate.py': [Errno 2] No such file or directory`

I tried to upload the scoring_program.zip file without having any folder structure and putting metadata as follow: `python $evaluate.py $input $output`, however, I still got error saying that the script is not found.

competition ID: 17807
my username: hazirbas

**Comment by Tthomas63** [comment]
Hello @hazirbas,

Your metadata file references the tag `$scoring_program`, it should just be `$program`. If you found this from the docs, please let us know so we can correct it!

Thanks and best regards,
Tyler
