### ISSUE TITLE
Research Google Cloud Storage vs S3

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2140]

**Comment by ckcollab** [comment]
Took a look at this, looks like we'll have to bump `django-storages` from our weird `django-storages-redux` version (to support Azure problems). To use new `django-storages` we'll have to migrate to Django > ~1.7.

**Comment by AndreaMichi** [comment]
Hi Eric,

Do you have an idea of the amount of work required to migrate to Django > 1.7? Or if there is another way to support Google Cloud Storage without migrating to a newer Django version.

**Comment by ckcollab** [comment]
@AndreaMichi sorry just seeing this now. It's certainly a non-trivial amount of work. There are quite a few things that can break. I believe the shortest/easiest way, still, is upgrading to > 1.7, though.
