### ISSUE TITLE
"Permission denied" running the scorer

### ISSUE THREAD

**Issue by EgoLaparra** [codalab/codalab-competitions#2144]
Hi,

The scorer of our competition (https://competitions.codalab.org/competitions/17286) needs java 1.8 because it uses the time library included in this version. As the java version in codalab is 1.7, the only solution I could find was to include in the scorer the runtime enviroment of the 1.8 version. I know that this is a terrible solution but, at least, it worked before the upgrade. Now, it seems that the scorer does not have access to the enviroment anymore and I get "Permission denied" errors everytime I make a submission. 

Could you please help me with this issue? Could you give me an alternative?

Thanks.

**Comment by ckcollab** [comment]
There are a couple options:

1. What is the problem with the current runner? Permission denied, but the file exists for sure?
2. You could update the docker image used to run the submission here: https://github.com/codalab/docker-codalab-legacy

All you would need to do for #2 is maybe change [this line](https://github.com/codalab/docker-codalab-legacy/blob/master/Dockerfile#L29) to use `openjdk-8-jre`? Then push that docker image to a docker hub account and point your competition to that docker image. These are all relatively new features, but should hopefully be a nicer solution than including the runtimes with your scorer -- let me know if you need help!

**Comment by EgoLaparra** [comment]
The scorer is a python script but it has two steps and for the second one it must launch a external process calling a jar file that needs java1.8. I have included the enviroment for that version in the directory of the scorer.  I have tried to access the java command using ls and it is there, but the execution permissions have been removed.

**Comment by ckcollab** [comment]
I see, can you `chmod +x` within your script .. maybe?

**Comment by EgoLaparra** [comment]
I have thought the same thing. I'm trying now.

**Comment by EgoLaparra** [comment]
It worked! Thank you, Eric.

**Comment by ckcollab** [comment]
It was all you ;) have a good one!
