### ISSUE TITLE
Submissions stuck in "submitted" status

### ISSUE THREAD

**Issue by gchrupala** [codalab/codalab-competitions#2145]
In a competition I'm running there are a number of submissions which aren't being run: they are stuck at the "Submitted" status for a long time. The competition is this one:  https://competitions.codalab.org/competitions/17770?secret_key=fad15020-67a0-4923-ac91-7aaa42c086c8

**Comment by FlavioAlexander** [comment]
Hello @gchrupala, 

How long does a submission normally takes to run? have you had any successful submission? Maybe they are running but queue is full, so it is understandable it will take some time to finish

**Comment by gchrupala** [comment]
It should take a few seconds at most to run. Some of these submissions have been in the "Submitted" status for many hours now.

**Comment by arunmallya** [comment]
Same problem here, for a different competition.

**Comment by ckcollab** [comment]
Are the submissions getting through now for everyone? I see submissions getting through the queue.. but there are quite a few.

**Comment by arunmallya** [comment]
Still the same issue. Previously submissions have not gone through.

**Comment by arunmallya** [comment]
New submissions seem to be working though.

**Comment by ckcollab** [comment]
OK, I'll close this as new submissions seem to be going through.
