### ISSUE TITLE
Hiding scores to participants

### ISSUE THREAD

**Issue by SimonOst** [codalab/codalab-competitions#2150]
Hi,

I wanted to test if leaderboard hiding works properly in our competition (https://competitions.codalab.org/competitions/17184 - I actually created an identical copy of it for the testing). While the leaderboard as such seems to be hidden, and the "Top 3" window seems not to be updated, participants are apparently still able to see their own score: When checking their own submissions, participants see a table containing information about the file name, date, and status of their submission, but also a field with the score of their submissions (screenshot attached). I also tested submitting as a non-admin, but the problem seems to be the same. Can you help?

Cheers!

![screen](https://user-images.githubusercontent.com/6973169/34558753-9c2253f6-f13f-11e7-8365-06170323a976.png)

**Comment by Tthomas63** [comment]
Hello @SimonOst,

This was a bug in the code as there was no check for whether the phase was `blind`. Users should no longer be able to see their own scores when a phase is blind. 

Were there any concerns with the top three not being hidden?

Thanks,
Tyler

**Comment by SimonOst** [comment]
Hi @Tthomas63,

at least for our competition, the problem still persists. As I just realized after checking, the top 3 window also displays the score, but - what is more critical - also scores of other participants, even if the leaderboard is private.

Cheers
Simon

**Comment by Tthomas63** [comment]
Hello @SimonOst,

These changes had not yet been pushed to production, but they have been now! Top Three will also not display any data if the active phase is `blind`.

Please let us know if you need any more help!

Thanks, and best regards,
Tyler
