### ISSUE TITLE
Unknown error thrown when attempting to start competition

### ISSUE THREAD

**Issue by visionjo** [codalab/codalab-competitions#2155]
The following error message is displayed when attempting to upload competition bundle:

'ascii' codec can't decode byte 0xe2 in position 1984: ordinal not in range(128)

Any idea what could cause this?

**Comment by ckcollab** [comment]
Could you email me the bundle so I can try to debug this?

eric@ckcollab.com

Thanks!

**Comment by ckcollab** [comment]
This should be resolved now (see email) let me know if you have more problems, thanks!
