### ISSUE TITLE
Leaderboard not updating

### ISSUE THREAD

**Issue by visionjo** [codalab/codalab-competitions#2158]
For some reason, scores are not getting posted to the leaderboard. Upon loading ground-truth, and opting to post on the leaderboard, results in the following:

<img width="785" alt="screen shot 2018-01-09 at 6 04 47 pm" src="https://user-images.githubusercontent.com/4220645/34747761-a7c12ca6-f567-11e7-991d-6f11b6e09235.png">

Here is a snippet of YAML file (which is the same as done previously):
<img width="663" alt="screen shot 2018-01-09 at 5 59 13 pm" src="https://user-images.githubusercontent.com/4220645/34747784-bb72a946-f567-11e7-98be-941b7e7ce4dc.png">

Here are screenshots of the eval script:

<img width="468" alt="screen shot 2018-01-09 at 6 01 43 pm" src="https://user-images.githubusercontent.com/4220645/34747814-cd7f43b0-f567-11e7-8d9a-1da3b9a434e5.png">

<img width="401" alt="screen shot 2018-01-09 at 6 01 53 pm" src="https://user-images.githubusercontent.com/4220645/34747824-d50122a2-f567-11e7-8d2a-6754b554ad7d.png">

Also, the metadata file:
<img width="641" alt="screen shot 2018-01-09 at 6 01 29 pm" src="https://user-images.githubusercontent.com/4220645/34747843-ee069c32-f567-11e7-8b29-cd03d0ef76b5.png">

Finally, the output file from scoring (which seems to be properly scoring, but not displaying):

<img width="643" alt="screen shot 2018-01-09 at 6 02 49 pm" src="https://user-images.githubusercontent.com/4220645/34747860-fb4734ec-f567-11e7-9112-3097c242399c.png">

Any ideas why this is not working?

**Comment by ckcollab** [comment]
I believe case matters? Should `Accuracy` be `ACCURACY`? Could you screenshot your leaderboard configuration from the Edit competition area?

**Comment by visionjo** [comment]
Hi Eric,

Thanks (as always) for getting right back.

Here is a screenshot (I tried matching case by editing this field, but didn't work... I will try again to be sure):  

<img width="788" alt="screen shot 2018-01-10 at 1 57 02 pm" src="https://user-images.githubusercontent.com/4220645/34790010-5496fe32-f60e-11e7-8f30-7ce0638ef11a.png">

**Comment by ckcollab** [comment]
You may need to make a fresh competition if you have results that are breaking the leaderboard? Or you can delete the old submissions and that may fix it?

**Comment by visionjo** [comment]
Yes, you are exactly right (it did not work when updated via 'Edit', but worked when I modified YAML file... Thank you so much, now ready to go live :)

**Comment by ckcollab** [comment]
Wooooooooo! :shipit:
