### ISSUE TITLE
I cannot download the file 

### ISSUE THREAD

**Issue by isalirezag** [codalab/codalab-competitions#2160]
https://competitions.codalab.org/competitions/1630300

**Comment by ckcollab** [comment]
Is the competition published to the public?

**Comment by isalirezag** [comment]
It is on the cvpr website, I cannot find any link to register for it, so I guess it should open to public.
please let me know if I am wrong or I should fill some forms for it or register somewhere.

**Comment by ckcollab** [comment]
What's CVPR? Can you link to the page with a link to the competition? Are you sure it's a problem on Codalab's end?

**Comment by isalirezag** [comment]
In this link http://www.vision.ee.ethz.ch/en/ntire18/ when I clicked on it it connected me to the Codalab's end and said that there is a bug.
I just tried it now.. sounds like the linked is fixed and it is working now...
