### ISSUE TITLE
register 

### ISSUE THREAD

**Issue by lichongyigithub** [codalab/codalab-competitions#2161]
I am Chongyi Li. Our team would like to participate this dehazing challenge.

**Comment by ckcollab** [comment]
Hello Chongyi Li, you may be looking for this?
https://competitions.codalab.org/competitions/

I don't see any "dehazing" competition listed? Could it be under something else?

**Comment by lichongyigithub** [comment]
Thanks. I am looking for the training data for image dehzing. But I could not find it. "3rd New Trends in Image Restoration and Enhancement workshop and challenges" should provide the link for data download. It might be under something else.
