### ISSUE TITLE
Broken submission counts against submission limit

### ISSUE THREAD

**Issue by Cyvhee** [codalab/codalab-competitions#2163]
Hi

A participant uploaded a broken submission and this is counting against the submission limit. As I understood from some Q&A, deleting the submission still counts against the limit, but marking the submission as "FAILED" should allow the participant to resubmit, however, this is not the case. Is there another way that task organisers can 'subtract' certain failed submissions from the submission count?

Thank you!

Cheers
Cynthia

**Comment by ckcollab** [comment]
Cynthia,

Hmm, I believe if you delete the submission it should change the count? And failed shouldn't be counted as well...

Can you manually re-run the submission, if you changed the reference data or some such between runs?

Thanks,
Eric

**Comment by Cyvhee** [comment]
Hi Eric

Thanks for the prompt response!
Marking the submission as "failed" (the submission ID changes to "failed") does not seem to work, when refreshing the page, the submission gets its ID back and I am still not able to upload a new submission... Removing the submission seems to work after changing the reference data, I will ask the participant in question to try again. Thanks for the suggestion!

I also have experience another issue: although the leaderboard is disabled, participants are able to see the scores through the graph displayed below the leaderboard. Have you any ideas about why it is still displayed?

Thank you!!

Kind regards
Cynthia

**Comment by Tthomas63** [comment]
Hello Cynthia,

Could you provide us with a link to the competition or the ID of it so we can take a look at it? Also for the leaderboard issue, is it the top three next to the graph you are referring to or the graph itself? The top three should not display any data if the current phase is `blind`. 

Thanks,
Tyler

**Comment by Cyvhee** [comment]
Hi Tyler

No, there is no top three displayed (as should be, since I disabled the leaderboard), but the graph itself is still visible.

What relates to the max. number of submissions: sometimes deleting a few submissions works allows to upload others in the place, but other times I had to remove all submissions to be able to upload again, I do not see any consistency in this.

This is the link to our competition: https://competitions.codalab.org/competitions/17468. Thank you for having a look at it!

Kind regards
Cynthia

**Comment by Tthomas63** [comment]
Hello Cynthia,

The latest changes to this code should fix the issue. Deleted or failed submissions do not count towards the maximum allowed submissions. 

There was some bugs in the code's previous logic, that was preventing it from grabbing the correct amount of `failed` submissions.

Please let us know of any further problems!

Thanks,

**Comment by Cyvhee** [comment]
Dear Thomas

That is very good news, thank you!

Kind regards
Cynthia
