### ISSUE TITLE
 ISBI 2018 challenge unaccessible (No signup or login possible) 

### ISSUE THREAD

**Issue by MissTinger** [codalab/codalab-competitions#2167]
Signing up or logging in from the URL: [http://isbichallenges.cloudapp.net/](http://isbichallenges.cloudapp.net/) to join the ISBI 2018 - Lung Nodule Malignancy Prediction, Based on Sequential CT Scans challenge organized by artem does not work. The help suggests to signal this as an issue.

**Comment by ckcollab** [comment]
That is not an "official" codalab server. Codalab is open source, you'll have to find who is hosting that server?
