### ISSUE TITLE
Reply to messages of competition organizers

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2168]
When organizers bulk email their participants, the return address is "noreply@codalab.org", which gets directed to the admins. Could it be directed instead to the competition organizers?

**Comment by ckcollab** [comment]
We could specify the organizers address as the "From" address, but do we want to reveal this email to everyone in the competition? I think we'd want to use some kind of relay to hide the email, but I'm not sure that's easily do-able.

I believe we want to feature freeze 1.5, so maybe we can consider this for v2?

**Comment by ckcollab** [comment]
Remade here: https://github.com/codalab/competitions-v2/issues/68
