### ISSUE TITLE
Competition dumps fail on LRI server

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2171]
The dump feature is not working on (last tried Jan 20)
https://codalab.lri.fr/competitions/111/dumps/
![image](https://user-images.githubusercontent.com/7594063/35182297-085a8f9a-fdd2-11e7-90ba-b40236d40b08.png)

**Comment by Tthomas63** [comment]
Hello Isabelle,

This issue is specific to this competition and we could not find a specific cause for this behavior. Competition Dumps are still working for other competitions on LRI.

See: https://github.com/codalab/codalab-competitions/issues/2105

Best regards,
