### ISSUE TITLE
Column naming messed up in participant panel (LRI server)

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2172]
This is an error on http://codalab.lri.fr

![image](https://user-images.githubusercontent.com/7594063/35183156-953b0a2a-fde1-11e7-81ec-2858fd4e7c1f.png)
The column headings should be 
"#" Score Filename Date Status

We could add the description field.

Note that the score does not refresh well, we need to reload the page.

**Comment by madclam** [comment]
This problem seems fixed on competitions.codalab.org, so the changes must not have been pushed to the LRI server.
![image](https://user-images.githubusercontent.com/7594063/35183814-636054d2-fdec-11e7-80b1-f8a69bf5a1c2.png)

**Comment by Tthomas63** [comment]
Updated the LRI servers, and this seems to have fixed it! 

<img width="844" alt="screen shot 2018-01-22 at 11 21 13 am" src="https://user-images.githubusercontent.com/28552312/35239820-686c2f84-ff66-11e7-8d54-a81234087198.png">
