### ISSUE TITLE
'Failed' submissions count against the submissions limit

### ISSUE THREAD

**Issue by gkata** [codalab/codalab-competitions#2175]
competition nb 17422
Submissions with the status 'failed' (either set manually or the scoring script exits with error) are still counted against the limit of submissions.

**Comment by Tthomas63** [comment]
Hello,

This issue should be resolved. Failed or deleted submissions should not count towards the max amount of allowed submissions. 

Please let us know if you encounter anymore issues!

Thanks, and best regards,
