### ISSUE TITLE
Dataset names in editor disappearing

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2177]
In the editor on the LRI website, dataset names in menus disappear, e.g.
![image](https://user-images.githubusercontent.com/7594063/35470976-2c278a28-0353-11e8-91eb-12cbd3999ba6.png)

in competition 100.
This does not see to affect the well functioning of the website.

**Comment by ckcollab** [comment]
Which competition is this on? Is it on every competition?

**Comment by ckcollab** [comment]
Is this still a problem after the updates we did recently, this is still occuring?

**Comment by ckcollab** [comment]
Since we are moving away from lri.fr I'll close this

**Comment by madclam** [comment]
This is still a problem, for example in competition
https://codalab.lri.fr/my/competition/111/
Also, there are no logs for the ingestion program
Download your submission
View scoring output log
View scoring error log
View predict output log
View predict error log
Download evaluation output from prediction step
View detailed results
Download evaluation output from scoring step

**Comment by ckcollab** [comment]
This should be fixed again
