### ISSUE TITLE
Submissions stuck in "submitted" or "running" status

### ISSUE THREAD

**Issue by miracle24** [codalab/codalab-competitions#2179]
See the following screenshot:
![20180130151058](https://user-images.githubusercontent.com/10026242/35552759-30bcc952-05d0-11e8-8ef1-5aa979749acd.png)
The second submission was run a few months ago, but the status is still 'Running'.
The Third submission was submitted one hour ago, and the results.zip of the fourth submission is a copy of the third submission. New submission does not work. 
I don't know what the problem is, because I cannot get the error file.

**Comment by ckcollab** [comment]
Are they still stuck? It seems like submissions are being processed (thanks to @Tthomas63's nice tracking!)

**Comment by miracle24** [comment]
No. They have been processed. Thanks a lot. But the status of the second submission is still 'Running'.

**Comment by ckcollab** [comment]
That could be due to running during a compute worker reset or some such, maybe in the future we will have a worker clean up tasks > 1 week old, or something?

**Comment by miracle24** [comment]
Ok
