### ISSUE TITLE
The number of members doesn't include the first member

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab-competitions#2180]
For example, in the following screenshot, at the top right it says that the group has 3 members, but the table contains 4 members:

![image](https://user-images.githubusercontent.com/15331/35606438-0ad26cea-0604-11e8-9192-18afb46ca875.png)

**Comment by Tthomas63** [comment]
Hello,

This has been fixed and pushed to production! Please let us know if you see any more issues regarding teams.

Thanks,
