### ISSUE TITLE
Test submission automatically re-submitted to Post-Competition

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#2181]
Hello, we found a rather surprising behavior: All submission submitted in the test phase are automatically re-submitted to the post-competition phase (only some five minutes after the original submission). Since our post-comptetition is not configured yet (the main purpose was SemEval with the deadline), the second submission fails which frightened some participants.

See screenshots:

![bildschirmfoto_2018-01-31_11-34-59](https://user-images.githubusercontent.com/11850778/35618472-6217f8b8-067b-11e8-96b7-626889a8b867.png)

![bildschirmfoto_2018-01-31_11-35-25](https://user-images.githubusercontent.com/11850778/35618478-68c098f0-067b-11e8-9f76-4b778929c801.png)

Is this configurable somehow?

**Comment by ckcollab** [comment]
Do you have migrations enabled? That is rather strange...

**Comment by habernal** [comment]
Thanks, yes - I had "auto migration" enabled, rather unintentionally. Is there any documentation about this setting?

**Comment by ckcollab** [comment]
Phew! That explains it :)

https://github.com/codalab/codalab-competitions/wiki/User_Enable-Auto-Submit-Phase-Migration
