### ISSUE TITLE
Line breaks are dropped in e-mails sent to all participants

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#2187]
We send e-mails to all participants, sometimes these are quite long. Unfortunately, the entire text is squeezed into a single paragraph, as line breaks are ignored.

**Comment by Tthomas63** [comment]
Hello @habernal,

Thank you for the suggestion! Unfortunately we are trying to feature freeze v1.5 and only roll out bug fixes/improvements. This is a feature we will definitely look into implementing with v2!

Thanks, and best regards
