### ISSUE TITLE
top-three table doesn't display anything when using the column_groups tag

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2189]
Hi @ckcollab ,

I've created a leaderboard using the column_groups tag to achieve a leaderboard similar to this one: https://competitions.codalab.org/competitions/3221#results. I managed to get the format I aimed for but the Top Three table doesn't show the submissions anymore. It's just an empty table, although I've submitted some runs (the same bug appears in the above link).

Another bug is that when using the specified tag, the csv file that is available for downloading is broken. To understand what I'm trying to explain, just take a look at the above link, and download the csv to see how the results are displayed.

If I do not group the columns using the column_groups tag, everything looks OK. If I group some columns and leave the column which is set for rank1, everything is OK. Maybe these information help.

Any suggestion to solve this issue?

Thank you,
Best regards

**Comment by Tthomas63** [comment]
Hello @liviust,

Would you be able to give us a link to your competition or the ID so we can look into this?

Thanks,

**Comment by liviust** [comment]
Hi @Tthomas63 ,

I've created a sample competition with some dummy data. It uses the same configurations so the bug is still there. Here is the link: https://competitions.codalab.org/competitions/18271?secret_key=84e2444e-c72c-49a3-9f72-0b99780a8b30

We are launching the competition on Monday. Hopefully we can find a solution for the issue in time (fingers crossed).

Thank you!
Best regards,
liviust

**Comment by liviust** [comment]
Coming back on this. I've done multiple tests and and checked other competitions that used the above leaderboard format and it seems that the problem occurs in all of them. Is there any quick fix/workaround for this issue while keeping the leaderboard format as is in my sample competition?

Best regards,
liviust

**Comment by Tthomas63** [comment]
Hello @liviust,

After doing quite a bit of debugging regarding this issue, it seems that the leaderboard not showing is actually a symptom of a bug we're trying to track-down. It appears your leaderboard is disassociated with your competition. Creating a new competition from a competition "dump" should create a working competition with the leaderboard layout you desire.

The exact symptoms of this bug are usually:
 - Submissions get processed, but checking the "submissions" admin page on a competition shows no scores were assigned, even if scores are showing in "results"
 - Top-Three not displaying
 - Results not displaying

The causes seem to include:
 - Editing phases/phase indexes/phase ordering after initial upload (Start at 0)
 - Editing leaderboard keyes/relations after upload ( Especially with a complex leaderboard involving column_groups, multiple leaderboards and or columns )

Local-host with Competition Dump:
![screen shot 2018-02-21 at 9 40 46 am](https://user-images.githubusercontent.com/28552312/36495847-705720f4-16eb-11e8-8498-d215088b5a4f.png)

Linked Example Competition Displaying Bug:
![screen shot 2018-02-21 at 9 40 39 am](https://user-images.githubusercontent.com/28552312/36495848-706bdaa8-16eb-11e8-8690-17387f9ae277.png)

Linked Example Competition Displaying Bug:
![screen shot 2018-02-21 at 9 40 26 am](https://user-images.githubusercontent.com/28552312/36495849-708108f6-16eb-11e8-8cbf-62583686d496.png)

Local-host with Competition Dump:
![screen shot 2018-02-21 at 9 40 06 am](https://user-images.githubusercontent.com/28552312/36495851-7092490e-16eb-11e8-97d5-e5303400acaf.png)

Would you be able to detail what changes/edits led up to the problem with the scoreboard/leaderboard so we have a better understanding of what is causing this?

Thanks, and best regards,
Tyler

**Comment by liviust** [comment]
Hi @Tthomas63 ,

If I remove the column grouping it works. The bug appears when I group the columns as in my layout. If I use one of the Competition Dump, it ignores the column_groups tag.

Hopefully, this will help more to track the bug:
`
leaderboard:

    leaderboards:
        Ranking: &RANKING
            label: Ranking
            rank: 1
            
    column_groups:
        Average testsets: &AVERAGE_TETSETS
            label: A
        Testset topics_1: &TESTSETS1
            label: B
        Testset topics_2: &TESTSETS2
            label: C
    columns:
        CR:
            leaderboard: *RANKING
            column_group: *AVERAGE_TETSETS
            label: CR@20
            # Order of the CR@20
            rank: 1
            numeric_format: 4
        P:
            leaderboard: *RANKING
            column_group: *AVERAGE_TETSETS
            label: P@20
            rank: 2
            numeric_format: 4
        F1:
            leaderboard: *RANKING
            column_group: *AVERAGE_TETSETS
            label: F1@20
            rank: 3
            numeric_format: 4
        CR_1:
            leaderboard: *RANKING
            column_group: *TESTSETS1
            label: CR@20
            rank: 4
            numeric_format: 4
        P_1:
            leaderboard: *RANKING
            column_group: *TESTSETS1
            label: P@20
            rank: 5
            numeric_format: 4
        F1_1:
            leaderboard: *RANKING
            column_group: *TESTSETS1
            label: F1@20
            rank: 6
            numeric_format: 4
        CR_2:
            leaderboard: *RANKING
            column_group: *TESTSETS2
            label: CR@20
            rank: 7
            numeric_format: 4
        P_2:
            leaderboard: *RANKING
            column_group: *TESTSETS2
            label: P@20
            rank: 8
            numeric_format: 4
        F1_2:
            leaderboard: *RANKING
            column_group: *TESTSETS2
            label: F1@20
            rank: 9
            numeric_format: 4
`

**Comment by Tthomas63** [comment]
Hello @liviust 

`group_columns` does not appear to be related to this issue, as far as I can tell from testing. The only issue with it that I am aware of is that it is an un-documented and possibly a depreciated feature (This is why Competition Dump ignores it, and there is not a field in edit for it). I have not been able to get the competition to format it the expected way, but all of them have a top three and results displaying, albeit without the grouping (Even if it was formatted in the YAML).

<img width="1440" alt="screen shot 2018-02-21 at 12 37 20 pm" src="https://user-images.githubusercontent.com/28552312/36504028-fcf6a530-1703-11e8-8309-e3b6136962cd.png">


In regards to MSCOCO not displaying the top three, I believe that is because they use `computed_scores` instead of assigned scores. I can do some more digging and provide more info about this if you would like

**Comment by liviust** [comment]
Well, could you take a look at the csv file then? There are columns that are not exported when using the group_columns. The bug appears also in the MSCOCO competition.

So, from what I understand, the official answer would be that codalabs doesn't support group columns.

**Comment by ckcollab** [comment]
It looks like here's another example with busted Top 3 and the Leaderboard working:
https://competitions.codalab.org/competitions/15595#results

> So, from what I understand, the official answer would be that codalab doesn't support group columns.

It's a rather old undocumented feature, we still support it but it's a bit hard to figure out what the problem is relating to top 3. We were able to make a competition using `column_groups` locally that did display the top 3. 

There may be something else going on here, the leaderboard code is pretty spaghetti'd. We're probably going to refactor top 3 to use exactly the same scores code as leaderboard and that should hopefully resolve most problems with top 3 display.

**Comment by ckcollab** [comment]
Looks like top three is fixed for your competition now! Thanks @tthomas63
