### ISSUE TITLE
Submission fails and then works when re-running the same file

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2190]
Hi,

When I upload a submission file it randomly fails with the error listed bellow (In the first instance I thought that it was because of a tag that I used but after some more tests it looks random).

```Error: 
Traceback (most recent call last):
  File "/worker/worker.py", line 445, in run
    stderr=stderr,
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
```

If I go to the Submission tab as admin and re-run the same submission that failed in the first instance, It runs.

1 | Feb. 18, 2018, 8:23 a.m. | ##### | 441396 | res1.zip | Failed | False | 
2 | Feb. 18, 2018, 8:25 a.m. | ##### | 441397 | res1.zip | Finished | True | 

Any idea what the problem could be?

**Comment by liviust** [comment]
Digging more, here is a screenshot where I uploaded exactly the same file.

![capture](https://user-images.githubusercontent.com/25505723/36350037-c869c62a-1498-11e8-8675-4506e0c433cf.PNG)

**Comment by MKFMIKU** [comment]
meet same err 🐛

**Comment by Tthomas63** [comment]
Hello,

@ckcollab took a look and this should be fixed.

Thanks, and best regards,
Tyler

**Comment by SuperIRabbit** [comment]
We're seeing the 'OSError: [Errno 7] Argument list too long' again in competition 18467. Could you take a look at it again?
