### ISSUE TITLE
New account on LRI server

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2191]
When we create an new account on the LRI server, when we sign in the first time we get redirected to codalab.lri.fr rather than https://codalab.lri.fr/competitions/. This is a bit confusing since codalab.lri.fr directs to https://competitions.codalab.org/.

Could it be possible that all redirects are always to https://codalab.lri.fr/competitions/?

**Comment by ckcollab** [comment]
Login/new user redirect -> https://codalab.lri.fr/competitions/

NO redirect to `/` should be allowed

**Comment by Tthomas63** [comment]
This should be fixed on LRI
