### ISSUE TITLE
E-mail notification to organizers on new forum entries not working

### ISSUE THREAD

**Issue by habernal** [codalab/codalab-competitions#2192]
Hello, this is re-opening #1996 - unfortunately does not work for new posts in the forum (no e-mails delivered).

**Comment by ckcollab** [comment]
Heyo, I added a feature so if you have "Organizer Direct Message Updates" enabled in your profile (it's on by default) you will get notified of new threads.

Please let me know if this isn't working properly for you, quickly implemented/tested it, but may be buggy! :)

**Comment by habernal** [comment]
@ckcollab Thanks! If you don't hear from me, it's probably working. Just leave the issue open for a while so I can report back.

**Comment by ckcollab** [comment]
Closing as this feature is hopefully working properly ;)
