### ISSUE TITLE
large file uploads

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2193]
Codalab won't let participants upload large files. This is a locking factor to launch the 2018 ChaLearn LAP competition (March 1).

Meysam did the following tests:

File size | Upload time | status
-- | -- | --
520MB | -- | Never finishes uploading properly, perhaps because of poor connection
520MB | 15-20min | Uploaded successfully with good connection, Failed to unzip
320MB | 15min | Failed to unzip
182MB | 10min | Failed to unzip
104MB | Less than 10min | Failed to unzip
40MB | 2min | Zip is ok

**Comment by ckcollab** [comment]
NOTES: We were able to upload by turning on Results Only scoring. The issue probably has to do with the Prediction step, maybe default ingestion program.

**Comment by dongfengxijian** [comment]
@ckcollab Is the file smaller than 40MB before zip or after zip？ I didn't get it.

**Comment by nathantsoi** [comment]
Hi! I am trying to submit a 50MB file (zipped) for scoring to https://competitions.codalab.org/competitions/5181#participate, but get the error "Sorry, failed to upload file." Please advise

**Comment by Tommymhz** [comment]
Hi! https://competitions.codalab.org/competitions/5181#participate, but get the error "Sorry, failed to upload file." Please give me advice as well, thank you.

**Comment by Didayolo** [comment]
Merged.
