### ISSUE TITLE
metadata from submissions missing from organizers page

### ISSUE THREAD

**Issue by benbuleong** [codalab/codalab-competitions#2194]
Hi, though the metadata requested i.e. team name, method name, method description are being enforced (I tested it as a bogus participant myself), such data are not available anywhere in the organizer's portal. I tried downloading the zip files and looking at the metadata via "View all submission's metadata", but found nothing. Can you please let me know how to access the metadata requested?

**Comment by ckcollab** [comment]
If you go to the Submissions page in your competition, do either of these buttons give you the correct results?

![image](https://user-images.githubusercontent.com/2185159/36612613-f28d3cb0-188b-11e8-9640-cd0d784ebe5c.png)

![image](https://user-images.githubusercontent.com/2185159/36612705-3458f1ca-188c-11e8-9087-8c08434c6c17.png)

**Comment by benbuleong** [comment]
The "Download CSV" gives me an empty CSV file; the "Download all submissions on leaderboard" file when unzipped did give me the metadata I want i.e. method name, description and team name. However, I could not find any submission IDs which I could use to directly cross reference to results on the organizer's submission page. I guess I would need to do some parsing here using the unzipped contents to sort out the submission person, team name (not always the same to the submission person), method name and method description. Thanks anyways!

**Comment by ckcollab** [comment]
> Thanks anyways!

No problem, apologies it's not working 100% as desired :(
