### ISSUE TITLE
Problem adding accounts to administrator if they have a dot in their username

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2196]
Hello,

I've noticed that, if an user has a dot in his username, for example: test.user, the following tag doesn't work:
```
admin_names: admin1, test.user
```
It will ignore test.user. It will only add admin1. After I create the competition I can add the user from the site.

Best regards

**Comment by liviust** [comment]
Digging more, It also ignores users having "_" in their name.

**Comment by ckcollab** [comment]
I think spaces might mess it up? Try without spaces maybe?

**Comment by ckcollab** [comment]
(note: I just pushed some code that will strip whitespace from admin names, so it should work with spaces now if you do use them!)

**Comment by liviust** [comment]
Hi @ckcollab ,

Thank you! I shall close this issue since it was more a problem of not understanding how the arguments should be passed. The hint should exist in the WIKI as well, I don't remember finding any clue about white spaces :-). I will check again.

Best regards,
liviust
