### ISSUE TITLE
The website's editor removes the html styles

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2197]
#Hi,

I've noticed that if I edit the competition after I upload it to Codalab, it removes my htmls styling. The issue is that I'm not even editing the content of the htmls, I'm just adding more users as admin.

Best regards.

**Comment by liviust** [comment]
To describe better the issue, if I have in my html a styling code

```
<style>
p {
	text-align: justify;
}
```
</style>
If I edit the competition online, the styling goes away.

I expect some constraints since the editor lets user edit the htmls online, but maybe have different sections, so I one needs to edit the htmls online, then losing the styling might be OK since the user wants to change it, but for other reasons maybe it would be better to not convert the htmls to a simpler version that the editor can understand.

**Comment by ckcollab** [comment]
Although it's annoying can you put the style inline with the elements? I think the editor doesn't allow it because it could break site styling? Kind of like myspace?

**Comment by liviust** [comment]
I see. Thank you!
