### ISSUE TITLE
"The CodaLab site is currently unavailable" - error when trying to use the forum

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2202]
Hello,

We're trying to open a thread in the forum of our competition and we get the following error:

```
The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
```
ID: https://competitions.codalab.org/competitions/18419

Best regards,
liviust

**Comment by ckcollab** [comment]
Try now, apologies for the problems

**Comment by liviust** [comment]
Hi @ckcollab ,

It works now.

Thank you!
Best regards,
liviust

**Comment by zhuqianbin** [comment]
Hi, @ckcollab, @liviust 

I met the same error, can you tell me how to solve this issue?

Thanks!
Best regards
