### ISSUE TITLE
Participants do not get notifications when a new thread appears in the forum

### ISSUE THREAD

**Issue by liviust** [codalab/codalab-competitions#2205]
Hello,

I've noticed that the participants do not get notified that a new thread is opened in the forum. Also, the administrators do not get a notification when a participant applies for the competition. Only the one that created the competition gets notifications. Is this how it was supposed to be or is just a bug?

ID: https://competitions.codalab.org/competitions/18419

Thank you!
Best regards,
liviust

**Comment by Didayolo** [comment]
Hello,

Sorry for the late reply.
I haven't notice this bug in other challenges, so I close this old issue.
If you get a chance to try again and still gets the error, please re-open it.
