### ISSUE TITLE
Error when trying to upload previously acceptable Competition Bundle

### ISSUE THREAD

**Issue by dlindenbaum** [codalab/codalab-competitions#2215]
Hello,

I'm currently trying to work on a new competition bundle and am receiving the below error.  After an attempt to  upload the bundle through this webpage: https://competitions.codalab.org/competitions/create  the following error occurs.

```
'Page' object has no attribute 'description'
```

This error just occurred on Friday March 9th.  The same bundle was able to be successfully uploaded earlier in the week without problem.  
I deleted that previous competition because of some errors as it seemed easier to upload an entirely new bundle. Now neither the old bundle or a new slightly modified bundle is accepted.

Thank you for any help,

*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Competition fails to upload
2. Please post a link to your competition
Competition fails to upload

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
Chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://competitions.codalab.org/competitions/create

**Comment by ckcollab** [comment]
This problem should be fixed now, could you please re-open if not?
