### ISSUE TITLE
'Page' object has no attribute 'description'

### ISSUE THREAD

**Issue by goolig** [codalab/codalab-competitions#2216]
I'm trying to create a competition using the simple sample bundle "[yellow world](https://github.com/codalab/competition-examples/tree/master/basic-competition-bundles/Yellow_world)" and get a 
> 'Page' object has no attribute 'description'

I suspect it has something to do with "description" attribute in "competition.yaml", so I tried removing it.
Now I get: 

> 'utf8' codec can't decode byte #xbd: invalid start byte
  in "", position 37

Actually, wasn't able to upload any definition, not even the ones I created with [chalab](https://chalab.lri.fr/wizard/). I get similar errors.

**Comment by ckcollab** [comment]
This problem should be fixed now, could you please re-open if not?
