### ISSUE TITLE
Wrong score in different places

### ISSUE THREAD

**Issue by scaelles** [codalab/codalab-competitions#2218]
Hello,

I have hosted the following competition in Codalab for some time now: [https://competitions.codalab.org/competitions/16526](url) 

First of all, it's great to see how the platform gets better and better every day! However, I have seen that some of the new features related with scores, they are not working properly for my competition:
- The score in the top three table is not correct.
- The score displayed in Submit/View results on the Participate tab is also not the correct one.
- In the Submission section of the admin mode, in the Results column nothing is displayed.
- Is it possible to change the y axis of the chart? Right now, it starts at -0.2 and go to positive numbers. I think it would make more sense if the main metric is defined as descending to do the opposite. Also, when you hover with the mouse it would be nice to see more digits in the decimal part rather than just one.

PD: I have added your two usernames as admin so you can check if I am configuring something wrong.

Best,
Sergi

**Comment by ckcollab** [comment]
Apologies for the problems.

A couple quick questions come to mind:

1) Are you using "computed" scores?
2) Is your "main score" the one with the "lowest ordering"? Do you have many scores with the same rank/ordering conflicting with each other?

I checked your competition (I don't want to tweak anything) and it seems like many scores share the same ranking -- this could cause the wrong one to be picked as the main score? I can't tell from the edit form whether you're using computed scores as well.

Thanks!

**Comment by scaelles** [comment]
Thanks a lot for your fast reply! 
I have searched in the documentation, but for me it is still unclear what exactly means some fields in the Leaderboard section, specifically Ordering, Show rank, Selection Default.
Also, what do you mean by computed scores?

**Comment by ckcollab** [comment]
It is very confusing, I know :( and because it is rather old spaghetti code, when we try to fix or improve something, some magical side effect we didn't understand will break something else.

https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard

Selection default, if > 0, will make that column the default sorted column when viewing the leaderboard. Ordering and rank I believe are the same, where the lowest rank/order is the "default score" that will show on the top 3 leaderboard.

Computed scores are scores which are the result of a computation on many other columns. Like, "Average" which computes on keys "SET1" and "SET2".

**Comment by scaelles** [comment]
I have done the following action:
- Set "Selection default" to 1 in my main metric and to 0 in all the other metrics.
- Set "Ordering" from 1 to the number of columns, setting my main metric as 1.
- Disable the check box "Show rank" for all the columns except for my main metric.
- I don't have any column with a "computed" score.

The results are the following:
- :x: The top three table has disappeared (I have double checked and the checkbox "Hide Top Three Leaderboard" is disabled).
- :heavy_check_mark: The Score in Submit/View results on the Participate tab is now the correct one.
- :x: In the Submission section of the admin mode, there is still "---" in the Results column.

Is there something else that I am doing wrong?

Thanks

**Comment by ilkedemir** [comment]
We are having the same problem. The ordering of the results in the result table is correct, however the top three table shows incorrect results (correct ordering). Please see the attached image. 

Competition link: https://competitions.codalab.org/competitions/18467#results
![capture](https://user-images.githubusercontent.com/9616478/37687066-4edb4a46-2c57-11e8-86d8-27373cc155ac.PNG)

**Comment by ckcollab** [comment]
@ilkedemir I believe we fixed this for your competition, do you get incorrect scores on the "Submissions" admin page?

@scaelles we are still having trouble with yours, no top 3 is showing -- are all your key names correct? maybe there are some submissions with invalid key names and that is breaking things.. looking into this further, if you can double check all keys that may help

**Comment by ilkedemir** [comment]
Thanks a lot! Now the results look as expected.

**Comment by scaelles** [comment]
I guess that by key names you mean the keys on the score.txt output and the key names in the tables. I have downloaded all the entries in the test-dev phase using "Download all submission on leaderboard". They all look correct to me, like in this example:
![image](https://user-images.githubusercontent.com/11146411/37725164-9fc4b358-2d32-11e8-90c0-41812b77c5d3.png)
Also, if you have multiple phases and one of them never ends, how is defined which one should appear in the chart and the top 3 table?
Thanks a lot!

**Comment by ilkedemir** [comment]
I would like to follow up with changing the leaderboard keys. We have run into the same problem in another competition, it is not possible to change the original key in the .yaml file ("set1_score" in this case). We needed to change the output in the eval script to match the key, however it would be better if we can change the keys from the "Edit" feature.

Competition: https://competitions.codalab.org/competitions/18544

**Comment by Tthomas63** [comment]
We're closing this issue for now due to a lack of activity.

If you do encounter these problems, feel free to re-open the issue.

Thanks,
Tyler

**Comment by akutuzov** [comment]
Hi,

I checked the discussion above, and it is still not clear for me whether it is possible at all to change what scores are used as "main" in different places of the competition. We have 4 scores, and one of them ("Average score") is the main one. But Codalab still uses the score from the first column in the "Submissions" page and in the table below the Leaderboard. How to change this behavior?
Here's the competition: https://competitions.codalab.org/competitions/28340#results

Any help will be much appreciated
