### ISSUE TITLE
Error when uploading submission. BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by tomkee** [codalab/codalab-competitions#2219]
When uploading `zip` file with solution for DeepGlobe Road Extraction Challenge i am getting error:

`
Traceback (most recent call last):
  File "/worker/worker.py", line 275, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 142, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 101, in get_bundle
    with ZipFile(bundle_file.file, 'r') as z:
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 813, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
`

File size is 277MB, I opened it succesfully both on linux and windows.

**Comment by ckcollab** [comment]
did you try zipping and uploading from both windows and linux? Does your zip contains zips or a metadata file?

**Comment by tomkee** [comment]
My zip contains 1243 png files, in `/` directory of zip file. I tried uploading and zipping only from linux.

**Comment by tomkee** [comment]
I also tried uploading again, with zipped directory:
submission.zip
 ./submission/first_mask.zip
 ...
 ./submission/last_mask.zip

Now status is "submitted", but score column is empty. (`---`)

**Comment by ckcollab** [comment]
Can you contact the organizer to make sure you are formatting things properly, if you aren't the organizer?

Can you try uploading from Windows or Mac or zipping differently?

**Comment by tomkee** [comment]
Ok, it seems zip file was too big. After tresholding predicted values it was significantly smaller and working.

**Comment by mlopezantequera** [comment]
This is still happening to me, even on tiny zipfiles. This is on a competition that I manage (34623).

The zipfiles are fine, contain a single .csv file inside, and are about 11kb.

I tried downloading the submission to check if there was any error during upload but it's all ok.

Any ideas?

**Comment by Didayolo** [comment]
- Related to #2353
