### ISSUE TITLE
Unable to upload competition bundle

### ISSUE THREAD

**Issue by Kaveri-Pradhan** [codalab/codalab-competitions#2220]
I am trying to upload a competition bundle from the competitions page(competitions.codalab.org>My competitions > Competitions I'm Running > Upload definition) & AWS AMI codalab-instance-clear and I think it's not able to locate images, html files etc. in the zipped competition bundle(<name>.zip).

For validation I tried uploading some sample competitions bundles given in the below links:

_Please note that I am receiving the same errors in both AWS AMI and Codalab website._

1.
https://github.com/codalab/competition-examples/tree/master/basic-competition-bundles
For yellow-world & pi example, I received the error _"Oops! There was a problem creating the competition: 
Could not find file in archive, make sure scoring_program, reference_data and logo are set to correct file paths."_ 

2.
https://github.com/bethard/clinical-tempeval. 

Clinical-tempeval competition is already live but its bundle is not getting uploaded.
https://competitions.codalab.org/competitions/15621 

Error - _"There is no item named 'overview.html' in the archive"_

Are there any changes in the format / file structure of a competition bundle?

**Comment by siddbhatia** [comment]
Same here , I was trying to upload 
[compute_pi_competition_bundle.zip](https://github.com/codalab/codalab-competitions/files/1812125/compute_pi_competition_bundle.zip)


`Oops! There was a problem creating the competition: 
Could not find file in archive, make sure scoring_program, reference_data and logo are set to correct file paths.`

**Comment by ptschandl** [comment]
Hi @Kaveri-Pradhan , since you closed this issue, can you tell us how you resolved that issue?
Thanks!

**Comment by Kaveri-Pradhan** [comment]
Hi Phillip,

We directly edited one of their existing sample competition folder named Iris.

Best regards,
Kaveri Pradhan
Mob - +91 953860 9488

♻️ Save natural resources
