### ISSUE TITLE
Got error when submitting testing result

### ISSUE THREAD

**Issue by zhangzsmg** [codalab/codalab-competitions#2222]
Hi,

I encountered a problem when submitting my testing result about Track 1. 
After I submitted my .zip archive, I got an error information as:

"Traceback (most recent call last):
File "/tmp/codalab/tmpCoHAdQ/run/program/evaluation.py", line 107, in 
raise Exception('Expected 100 .png images, got %d'%len(res_pngs))
Exception: Expected 100 .png images, got 0
"
My submitted .zip archive includes 100 HR images with names like "0901x8.png" and a readme.txt file. There is no folder in the archive.

I apologize for not raising this problem in validation stage. Thanks for your help in advance.

**Comment by ckcollab** [comment]
Can you contact the competition organizer?
