### ISSUE TITLE
feed-back on search

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2228]
This is feed-back on chahub
https://codalab.lri.fr/competitions/

**Bug:** the same competition shows multiple times
<img width="964" alt="screen shot 2018-03-22 at 1 39 48 pm" src="https://user-images.githubusercontent.com/7594063/37771077-cb2b4a30-2dd6-11e8-89c6-efcf2fe5766b.png">

**Menus/header:** 
"Producer" is kind of a weird name. Maybe use "Provider"
By default, make the "Producer/Provider" the correcponding website, e.g. LRI if this is the LRI website.
Add in header: the current number of:
* competitions
* competition organizers
* registered users
* active users (made entries in the last 3-6 months or so)

**Competition banners:** 
Add 
* the name of the organizer and 
* when created.

**Comment by ckcollab** [comment]
What search did you do to cause the duplicates?

We made some issues to track these other changes, thanks for the feedback!

**Comment by madclam** [comment]
I get duplicates for example with:
https://codalabchahub.herokuapp.com/?q=biomed
![image](https://user-images.githubusercontent.com/7594063/37878688-3f5d309c-306d-11e8-9d83-035136d25f4c.png)


New bugs:
(1) A query asking to sort with number of participants:
https://codalabchahub.herokuapp.com/?q=chalearn&producer=1&date_flags=any_time&sorting=participant_count

The top competition is not the one with most participants.

(2) After clearing the query with the button
![image](https://user-images.githubusercontent.com/7594063/37878613-2f3af344-306c-11e8-8e01-3b77f4cf2e35.png)
Chahub keeps the old producer ID
https://codalabchahub.herokuapp.com/?producer=2
It is NOT possible to return to "Any producer", even with the menu.

**Comment by ckcollab** [comment]
For participant count, the chalearn results are undesireable:

![image](https://user-images.githubusercontent.com/2185159/37986566-aa6fc798-31b0-11e8-9fc9-ccade46b3c0d.png)


The higher participant with similar titles should appear above the lower participant. With VQA we get what we want, VQA on top with the Chalearn 700 participant underneath.

Maintain the VQA behavior while fixing the Chalearn behavior, the 700 participant count one should appear on top

**Comment by Tthomas63** [comment]
Duplicates were caused by LRI not sending a producer, and creating new competitions instead of updating existing ones. 

TODO:
 - Disallow producer being null/blank.

**Comment by ckcollab** [comment]
We found the source of duplicates, we believe, and also fixed some of the problems with not clearing producer and such. Whenever you change the search, the URL should update, and if you come to the page the page should show proper filters based on the URL.

**Comment by ckcollab** [comment]
I think we hit everything on here, also we should put this in:
https://github.com/codalab/chahub
