### ISSUE TITLE
Issue about "The competition has ended. No more submission are allowed" in MSCOCO keypoints challenge.

### ISSUE THREAD

**Issue by GloryDream** [codalab/codalab-competitions#2246]
I'm using safari on macOS. 

I've got into trouble when I start a new submission on [MSCOCO keypoints challenge](https://competitions.codalab.org/competitions/12061#participate) . After uploading my zipped json file in test-dev2017, a dialogue box will appear saying that 
>"The competition has ended. No more submission are allowed".  

I'm wondering what has happened.

**Comment by FlavioAlexander** [comment]
I believe this issue should be fixed, please confirm

**Comment by GloryDream** [comment]
@FlavioAlexander Thx!
