### ISSUE TITLE
Codalab VQA evaluation servers no longer accepting submissions

### ISSUE THREAD

**Issue by AishwaryaAgrawal** [codalab/codalab-competitions#2247]
Hi @FlavioAlexander,

The test-dev2015 and test2015 phases in the below competitions are throwing the following error when participants try to upload submissions -- "The competition has ended. No more submissions are allowed". These phases are set to "Phase never ends", so they should be accepting submissions (and they were, until a few days ago). 

The links to the competitions are below --

https://competitions.codalab.org/competitions/6961
https://competitions.codalab.org/competitions/6971
https://competitions.codalab.org/competitions/6981 (this one does not have test-dev2015 phase)
https://competitions.codalab.org/competitions/6991 (this one does not have test-dev2015 phase)

Could you please look into this as soon as possible? The participants have upcoming deadlines for which they need to evaluate their submissions.

Thanks,
Aishwarya

**Comment by AishwaryaAgrawal** [comment]
The issue is fixed. Thanks!

**Comment by FlavioAlexander** [comment]
All the glory should go to @Tthomas63, I just delivered the message 😄
