### ISSUE TITLE
Multi-dataset problem on competitions.codalab.org

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2257]
In competition https://competitions.codalab.org/competitions/7461
We are using as input data datasets that were created by "My datasets" by combining multiple datasets:
albert.zip
dilbert.zip
fabert.zip
robert.zip
volkert.zip

the combined dataset is called data2_v2 (by user automl.chalearn)

The submissions of the participants expect to find in $input the following data directory:
albert/
dilbert/
fabert/
robert/
volkert/

but they find unzipped datasets instead.

We encountered this problem before, I thought it was fixed. Maybe the changes were pushed only on LRI. We did not have this problem in V1.

There is the same problem for round 0 https://competitions.codalab.org/competitions/7471'
round3 https://competitions.codalab.org/competitions/7451
round4 https://competitions.codalab.org/competitions/9031'
In addition in these 2 last rounds one dataset is missing.

However, there is no problem for round 1 https://competitions.codalab.org/competitions/7462. Here the dataset data_1 when unzipped yields:
christine/
jasmine/
madeline/
philippine/
sylvine/

**Comment by madclam** [comment]
We need this feature for the google project. 
We tried it on http://35.193.242.121/competitions/8 and it does not work.

**Comment by ckcollab** [comment]
> AND DOES NOT WORK

OK

What are the contents of your data directory during submission processing?

**Comment by zhengying-liu** [comment]
Hi Eric, sorry for late reply. The content of the one zip file that I  is 5 zip files, each being a dataset. 

It seems that the backend does not unzip these 5 zip files when one tries to create dataset using several existing datasets.

**Comment by zhengying-liu** [comment]
Hello Eric! I found the reason why this wasn't working!

In the input_dir, the zip files ARE unzipped but they aren't deleted, see:
![image](https://user-images.githubusercontent.com/20074659/39200054-54325c64-47eb-11e8-97e7-fc4572ac8607.png)
so the ingestion program will take these as dataset directories but they are not! Ergo errors.

Now I add a line in ingestion.py to handle this situation. And now everything works!! Yeah!
