### ISSUE TITLE
'If submission beats old score, put submission on leaderboard' does not work

### ISSUE THREAD

**Issue by SuperIRabbit** [codalab/codalab-competitions#2258]
Even if this option is enabled, when a user makes a worse submission, it is forced to the leaderboard and replaces their previous (better) submission.

**Comment by ckcollab** [comment]
What is the scoring key and ranking for that score? Maybe the score it's using to determine which entry is better is the wrong score?

**Comment by SuperIRabbit** [comment]
Thanks for the quick reply!

It's the following competition: 
https://competitions.codalab.org/competitions/18467#results
There are two keys: Duration (which we don't really use and it's always 0 - could you help us remove it?), and set1_score. The leaderboard should be using set1_score, but it always migrates the latest submission.

**Comment by ckcollab** [comment]
We are completely swamped right now, is it urgent to remove this key? We could try that, although it could make your competition unusable if the keys aren't matched up properly, and the code that handles all of this is rather fragile legacy code.

Would it be possible to re-create the competition with proper keys? I believe the keys may be the problem?

**Comment by SuperIRabbit** [comment]
It's totally not urgent to remove that key, but is it the reason why 'If submission beats old score, put submission on leaderboard' doesn't work? set1_score is ordered correctly on the leaderboard now and we just want to see if it's possible to always show the best score on the leaderboard.

On the other hand, if the reason is because the showing_best_score feature only looks at one key (and that's Duration in this case) instead of a set of keys and it's hard to fix, then we'll just leave it as it is because competition has already started for a while. Thanks!

**Comment by ckcollab** [comment]
> On the other hand, if the reason is because the showing_best_score feature only looks at one key (and that's Duration in this case) instead of a set of keys and it's hard to fix, then we'll just leave it as it is because competition has already started for a while. Thanks!

That *sounds* like what is happening, but I could be wrong. If you have some free time, could you attempt making a fresh competition and confirming that the best score works with proper keys? If not, please email me an example submission and competition so I can poke around: eric@ckcollab.com
