### ISSUE TITLE
Fail to submit results to detection 2017test-dev bbox !

### ISSUE THREAD

**Issue by liye228** [codalab/codalab-competitions#2262]
Hello!

I participate in  detection 2017test-dev bbox.
https://competitions.codalab.org/competitions/5181#participate

I have try several times to submit my results to 2017test-dev bbox but failed.
And I tried the scoring programs locally (using minival2014) and they work fine.
Please give me some help!
thanks!

error message:
Error: 
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpjZ8joP/run/program/run.py", line 72, in 
    resFile = os.path.join(resDir, resFiles[0])
IndexError: list index out of range

**Comment by ckcollab** [comment]
I see other people making successful submissions which leads me to believe it may be something wrong with your submission? Have you contacted the organizers of this competition?

**Comment by liye228** [comment]
No , I have not.
AND I want to know is it ok to use images of 2015test-dev to get the results and submit to the 2017test-dev server. OR can you send me a detection results which was submit to 2017test-dev server successfully, then I can check what's wrong with mine . 
Thank you !

**Comment by liye228** [comment]
@ckcollab 
hello!
I just found something strange.
I sent a 2017val result to 2017test-dev.
I deliberately submitted a wrong result. Even the naming method was wrong, but it still reported the same mistake as when I submitted the correct result!


14 | --- | detections_val2017_kssd_results.zip | 04/15/2018 00:58:15 | Failed |   |  
-- | -- | -- | -- | -- | -- | --
Description: update descriptionTeam name: sysu_liyeMethod name: MSSDMethod description:multi-flow sub-net and multi-connectionError: /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.   warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') Traceback (most recent call last):   File "/tmp/codalab/tmpWhl6wf/run/program/run.py", line 72, in      resFile = os.path.join(resDir, resFiles[0]) IndexError: list index out of range

**Comment by ckcollab** [comment]
@liye228 can you please contact the competition organizers about this?

This repo is for the Codalab website itself, not specific competitions. Although there could very well be a problem with the platform, please first contact the specific organizers to rule out anything else. Thanks
