### ISSUE TITLE
UI AutoDL request 1

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2268]
In Participate tab:
![image](https://user-images.githubusercontent.com/7594063/39070753-d8f7b9bc-44e4-11e8-896c-fb3b6d4b1e59.png)

The button to download should NOT show the phase name (this is already in the phase column). Name the button after the "File Type" and suppress the File Type column.

![image](https://user-images.githubusercontent.com/7594063/39070962-921b3fcc-44e5-11e8-88a4-4a99c54258c9.png)

**Comment by ckcollab** [comment]
Make sure this is on the Google branch as well as Dev

**Comment by Tthomas63** [comment]
Pushed this on `develop` and `google-cloud-storage` yesterday

**Comment by Tthomas63** [comment]
I believe this is fixed
