### ISSUE TITLE
the submitted file was kept "submitted" status for a long time

### ISSUE THREAD

**Issue by liye228** [codalab/codalab-competitions#2270]
hello!

I had submittd my results to coco detections test-dev 2017 successfully.
And todday I submit a bigger file to coco detections test-dev 2017, but either success nor fail. 
The status of the file is always "submitted" ! 
please help me.

27 | --- | detections_test-dev2017_MSSD_results.zip | 04/24/2018 00:58:34 | Submitted |   |  
-- | -- | -- | -- | -- | -- | --
Description: update descriptionTeam name: sysu_liyeMethod name: MSSDMethod description:multi-flow sub-net and multi-connectionDownload your submissionView scoring output logView scoring error logDownload output from scoring stepRefresh status
28 | --- | detections_test-dev2017_MSSD_results.zip | 04/24/2018 01:26:01 | Submitted |   |  
Description: update descriptionTeam name: sysu_liyeMethod name: MSSDMethod description:multi-flow sub-net and multi-connectionDownload your submissionView scoring output logView scoring error logDownload output from scoring stepRefresh status

**Comment by shervin64** [comment]
There seems to be an issue with the server, see #2269 

We are really hoping someone will take a look and see if it can be resolved.

**Comment by liye228** [comment]
thanks for your reply!
let us wait for someone to sovle it

**Comment by maxaalexeeva** [comment]
Three of my submissions got scored a couple of hours ago, but then it stopped scoring again.

**Comment by ckcollab** [comment]
Duplicate issue, closing for the other one.

The queue is quite backed up, ~300 submissions were added suddenly, maybe someone re-running a large batch.
