### ISSUE TITLE
Google Cloud Storage - Detailed results LESS problems?

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2277]
![image](https://user-images.githubusercontent.com/2185159/39326053-bb072042-4948-11e8-8f94-17734ade9d7b.png)

For some reason on Detailed results we get these problems using AutoDL competition + Starting Kit we already have

**Comment by Tthomas63** [comment]
This should be fixed on the `google-cloud-storage` branch I believe
