### ISSUE TITLE
Submission fails and then works when re-running the same file

### ISSUE THREAD

**Issue by SuperIRabbit** [codalab/codalab-competitions#2282]
Competition link: https://competitions.codalab.org/competitions/18467

The last few submissions from bgong with the same content sometimes gets a score and sometimes gets the 'OSError: [Errno 7] Argument list too long'.

Might be related to: https://github.com/codalab/codalab-competitions/issues/2190

**Comment by piaozhx** [comment]
same problem

**Comment by shervin64** [comment]
Same issues for over 2 days now!

**Comment by monaj07** [comment]
Today all my submissions get failed and I keep getting this error:
``OSError: [Errno 7] Argument list too long``. 
This happens even for my previous successful submission files.

**Comment by ckcollab** [comment]
Submissions *seem* to be flowing through properly now, please let me know if not
