### ISSUE TITLE
Cannot edit anything in Competition 18467

### ISSUE THREAD

**Issue by SuperIRabbit** [codalab/codalab-competitions#2285]
Competition link:
https://competitions.codalab.org/competitions/18467
Edit link:
https://competitions.codalab.org/competitions/edit_competition/18467

We were able to edit the details of the competition a couple hours ago. But when we tried to add (and delete) a new phase, the competition suddenly became un-editable, no matter what we change in the edit page. I guess there've been some error message that's caught and hidden from the user interface. Could you look into this problem?

**Comment by ckcollab** [comment]
Did you look towards the top of the form, there may be an error there? Could you give me the details or screenshot the details of the phase you're trying to add, so I can replicate it exactly?

**Comment by ckcollab** [comment]
Closing for now, please let me know if the error is persisting
