### ISSUE TITLE
No confirmation email

### ISSUE THREAD

**Issue by Lithimlin** [codalab/codalab-competitions#2288]
I have just created an account for CodaLab but have not recieved my confirmation email yet although half an hour has already passed. It's neither in my inbox nor in my spam folder.

**Comment by ckcollab** [comment]
Have you still not received it? I just tested and was able to receive mail?

**Comment by Lithimlin** [comment]
I'd prefer the email I already submitted, if possible.

**Comment by ckcollab** [comment]
Have you tried re-sending the confirmation? (I believe you can do this by attempting to login again)

If you have tried and still aren't receiving it for whatever reason, that email may just not work...?
