### ISSUE TITLE
Urgent ISSUE about status remains in "submitting"!!!

### ISSUE THREAD

**Issue by GloryDream** [codalab/codalab-competitions#2290]
I'm using safari on macOS.

I've got into trouble when I start a new submission on [MSCOCO keypoints challenge](https://competitions.codalab.org/competitions/12061#participate) . After uploading my zipped json file in test-dev2017, the status keeps showing "submitting".

And below the submit button is showing:

> "Creating new submission".

Could you please help me fix it, cause it is really important to me at this time.

**Comment by Pony-Kelei** [comment]
I also met this problem, status remains in submitting not changed.

**Comment by shuangjiexu** [comment]
met the same problem too in [The DAVIS Challenge on Video Object Segmentation](https://competitions.codalab.org/competitions/16526). All submit remain a "submitting" state.

**Comment by ckcollab** [comment]
Apologies for the problems, things should be going smoothly now -- please wait ~45 minutes and re-open if not!
