### ISSUE TITLE
[Urgent] Result not visible in the Leaderboard

### ISSUE THREAD

**Issue by scaelles** [codalab/codalab-competitions#2294]
Hello,
I am currently running the final phase of a competition which should end in 5 days. You can find the competition [here](https://competitions.codalab.org/competitions/16526). I have added your usernames as admins so you can check what's wrong.
The submissions to `Test-Challenge 2018` don't appear in the leaderboard even though I do not have the private mode activated. Interestingly, if I click to download the results on the learderboard, the results that should be there are downloaded. I would appreciate if you could take a look as soon as possible.
Thanks a lot!

**Comment by ckcollab** [comment]
Which results aren't appearing in the leaderboard? I see many results in the leaderboard?

Please feel free to contact me eric@ckcollab.com due to urgency, maybe a Google Hangouts video chat where you can show me the problem will be helpful?

**Comment by ilkedemir** [comment]
We have a similar problem, the leaderboards are not visible [here](https://competitions.codalab.org/competitions/18468#results) and [here](https://competitions.codalab.org/competitions/18467#results), for the "Final" phases. However we can download the results and see the scores under "Submissions". We would appreciate if you can take a look, hopefully before June 1st. Thanks!

**Comment by scaelles** [comment]
Thanks for your quick reply. The leaderboard for the Test-Challenge 2018 is the one that does not display the correct results. Let me know if there is something else I can do from my side.

**Comment by Tthomas63** [comment]
Hello @scaelles,

Was the leaderboard always broken -- what changes have you made to the phases recently? We just saw the dates for the phases change, they *were* equal, but now they aren't. Did you just recently change this, or have the dates always been equal for Phase 2 & 3?

<img width="970" alt="screen shot 2018-05-22 at 12 28 22 pm" src="https://user-images.githubusercontent.com/28552312/40385532-bbd4581e-5dbb-11e8-9eda-116819ea5018.png">

Thanks,
Tyler

**Comment by ckcollab** [comment]
We fixed the problem with neverending phases and displaying them in the top, but there may be a deeper problem with your last phase.

Have you changed/tweaked the leaderboard keys for your final phase? It seems like it cannot grab the scores properly. Apologies for the problems...

**Comment by scaelles** [comment]
I have checked and the leaderboard keys are different. However, now I have lost the admin rights and I cannot change the evaluation script. Could you add me as an admin again? 

Also now it is not possible to submit to the never ending phase.

Is there an easy way to debug this kind of problems for future reference?

Thanks for everything

**Comment by ckcollab** [comment]
I re-added you as an admin -- scaelles I assume? Apologies for that mistake!

I re-enabled never ending phase flag as well.

> Is there an easy way to debug this kind of problems for future reference?

Unfortunately, not currently. In version 2 we hope to handle problems like this much more clearly. The current system gives you too many opportunities to shoot yourself in the foot and few ways to figure out which toe is shot off.

**Comment by ilkedemir** [comment]
Hello Eric,

Apologies for interrupting, is there any update about our case? Did you have a chance to check?

Thanks,
Ilke
________________________________

**Comment by ckcollab** [comment]
@ilkedemir probably a problem with keys, as well? Can you verify you are properly matching submission scoring keys to leaderboard keys?

**Comment by ilkedemir** [comment]
Yes, it is the same as development phase, which shows the correct leaderboard and scores. For the final phase, there is no leaderboard at all.

**Comment by ckcollab** [comment]
We'll have to look more into this one if the keys match perfectly @ilkedemir, could you email me a bundle and submission to test with so we can replicate this locally if it's not too much trouble?

**Comment by scaelles** [comment]
My competition ends tomorrow so I would prefer that you don't try to debug anything for now. I have already implemented a leaderboard myself by downloading automatically the results and parsing them.
However, I can send you what you requested to try locally. What do you mean by bundle?

**Comment by ckcollab** [comment]
Sorry  was talking to @ilkedemir -- unless I am confused? @ilkedemir we should probably open a separate issue and I am bogged down with other tasks :(

**Comment by scaelles** [comment]
Hello,
The competition has now finished, but it would be nice to have the learderboard for future reference. Could you check why is it not displayed?
Thanks

**Comment by ckcollab** [comment]
The leaderboard is not displayed, probably, because the keys in submissions do not match keys on leaderboard, so there are errors referencing which scores to display.
