### ISSUE TITLE
How to get the split of COCO 2017 test set?

### ISSUE THREAD

**Issue by Szy-Young** [codalab/codalab-competitions#2307]
Hi,
    I'd like to test my model on COCO2017 test-dev set. However I think only the whole test set (containing dev and challange) is available on the official set. Test on all the 40K images in the test set cost too much time. How can I get the split of COCO2017 test set?
    Thanks in advance.

**Comment by ckcollab** [comment]
Hello, we do not organize the competitions (typically) we just run the website the competitions are hosted on, you probably want to get ahold of the competition organizer.

**Comment by Szy-Young** [comment]
Thanks for your instructions. I've got answers from the competition organizer.


发自 iPhone 版 Yahoo 邮箱


星期五, 六月 1, 2018, 02:59 于 Eric Carmichael <notifications@github.com>写道：


Hello, we do not organize the competitions (typically) we just run the website the competitions are hosted on, you probably want to get ahold of the competition organizer.
