### ISSUE TITLE
Pagination Links on Submissions Page broken

### ISSUE THREAD

**Issue by mbugert** [codalab/codalab-competitions#2312]
The pagination links on the submissions page should point to `https://competitions.codalab.org/my/competition/xxx/submissions/?phase=xxx&page=xxx`. Right now, they point to `https://competitions.codalab.org/my/competition/xxx/submissions/?page=xxx`. This leads to the following problem:

In a competition with two phases (or more), if a user is on page 1 of the submissions of the first phase and clicks "Next", the user lands on page 2 of the second phase. If the second phase has less submissions (and therefore less pages) than the first phase, the user ist greeted with a 404 message.

**Comment by Tthomas63** [comment]
Hello @mbugert,

I have pushed a fix for this to production. Please let us know if you're still encountering this bug.

Thanks and best regards,
Tyler

**Comment by mbugert** [comment]
Thank you for the quick fix. :+1: 

Best,
Michael
