### ISSUE TITLE
Transition of public instance to LRI + Minio

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2316]
Test on Minio server, according to [master test plan ](https://docs.google.com/spreadsheets/d/1my6Fscjx_JUOKqL-52EmIEKkhPbE2F4oqHkkDPqJiTo/edit#gid=0)

- [x] Upload [Iris sample competition](https://github.com/codalab/competition-examples/tree/master/basic-competition-bundles/Iris)
- [x] Make changes with editor (change date of second phase)
- [x] Upload sample code submission
- [x] Upload sample result submission
- [x] Upload new dataset in "My datasets" (scoring program)
- [x] Re-run previous submission

**Comment by ckcollab** [comment]
I believe this is completed + working?
