### ISSUE TITLE
RVD

### ISSUE THREAD

**Issue by LoveTuanZi** [codalab/codalab-competitions#2318]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by Tthomas63** [comment]
Hello @LoveTuanZi,

In order to take a look at what issue you are experiencing, please describe the problem in detail, and answer the questions on the issue template.

Best regards,
Tyler
