### ISSUE TITLE
Redirecting to a new competition

### ISSUE THREAD

**Issue by zoharai** [codalab/codalab-competitions#2325]
Hi,

I have a competition in CodaLab already published and with participants.
I want to change the columns of the leaderboard and I understood that I need to open a new competition to do that.
My question:
Is there any way to create the new competition with the same id as the old one or to redirect the old url to the new one ?

Many thanks,
Zohar

**Comment by Tthomas63** [comment]
Hello @zoharai,

Sorry unfortunately that is not currently possible with Codalab at this time. However this could be a feature we implement in the future.

Thanks, and best regards,
Tyler
