### ISSUE TITLE
Dump creation failed

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2331]
I tried creating a dump for:
https://competitions.codalab.org/competitions/19365/dumps/

got

Download link | Status | Size | Publish Date | Delete
-- | -- | -- | -- | --

  | Failed |   | July 8, 2018, 1:55 p.m. | Delete
  | Failed |   | July 8, 2018, 1:54 p.m. | Delete

**Comment by ckcollab** [comment]
Did you change anything or do anything special to this bundle? A few other competitions I tested worked.

Did you remove scoring program/ref data, or anything like that?

**Comment by Didayolo** [comment]
We didn't do anything special to this challenge. We based it on another challenge which works well (https://competitions.codalab.org/competitions/18751).

By the way, the scoring program is giving weird results when submiting:
- When submiting the solution it returns 1.0 with all metrics (which is normal)
- When submiting a prediction that gives a 0.80 balanced accuracy and a 0.96 accuracy when tested locally (with the exact same scoring program, downloaded from the challenge), it returns a 0.52 balanced accuracy and near 0.50 accuracy on Codalab (which is less normal).

I've tried my best but couldn't figure out what was the problem.

**Comment by Didayolo** [comment]
I have re-created the scoring program from scratch and it's working.

Dumps are still failing.

**Comment by madclam** [comment]
Not sure what changed but this is working now.
