### ISSUE TITLE
submission  Error

### ISSUE THREAD

**Issue by cxyjy** [codalab/codalab-competitions#2334]
when I submitted the results of the competition, the format of the submission was correct, 
but I have been experiencing this problem. How can I solve it? Thank you!

Traceback (most recent call last):
  File "/tmp/codalab/tmp7zYan_/run/program/evaluate.py", line 67, in 
    "Missing volume: {}".format(submission_volume_path))
ValueError: Submission volume not found - terminating!
Missing volume: /tmp/codalab/tmp7zYan_/run/input/res/test-segmentation-0.nii

**Comment by ckcollab** [comment]
Hello! Please contact the competition organizer. Codalab (the repo this issue is posted on) is the platform the competition is running on, but it looks like the error is coming from the competition's "scoring program"

**Comment by FeiLyu** [comment]
> when I submitted the results of the competition, the format of the submission was correct,
> but I have been experiencing this problem. How can I solve it? Thank you!
> 
> Traceback (most recent call last):
> File "/tmp/codalab/tmp7zYan_/run/program/evaluate.py", line 67, in
> "Missing volume: {}".format(submission_volume_path))
> ValueError: Submission volume not found - terminating!
> Missing volume: /tmp/codalab/tmp7zYan_/run/input/res/test-segmentation-0.nii

Hello, I meet the same error, I am wondering whether you have solved the problem?
