### ISSUE TITLE
Leaderboard edits not taking place

### ISSUE THREAD

**Issue by nkaushik1** [codalab/codalab-competitions#2337]
Hello,

I have been trying to make a change to my one of my labels on the leaderboard on the "Edit" tab, and although it looks like the edit has been made successfully (redirects to home page and the change is reflected when viewing the Edit tab again) the changes are not showing up on the leaderboard. Do you know what might be causing this problem, or be able to manually override it? The competition is [here](url) and I am trying to change the label associated with "knife_main" to "knife" (it currently displays as "horse"). I've added the requested users as admin if that helps.

Thanks!

**Comment by Tthomas63** [comment]
Hello @nkaushik1,

Could you please post a link to your competition? The link you posted directs to ```https://github.com/codalab/codalab-competitions/issues/url```.

Thanks,
Tyler

**Comment by nkaushik1** [comment]
@Tthomas63 sorry about that! Link [here](https://competitions.codalab.org/competitions/19113).

**Comment by Tthomas63** [comment]
Hello @nkaushik1,

Sorry for the very late reply. We looked into this and could not determine a specific cause of why the changes were not being reflected on the UI.

I checked the database entries for the leaderboard objects of your competition and they show the reflected changes correctly.

Are you still currently experiencing this issue with your competition?

Best regards,
Tyler
