### ISSUE TITLE
All the submissions report 'submitted' rather than showing results

### ISSUE THREAD

**Issue by dzzhou0409** [codalab/codalab-competitions#2341]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

I am one of the organizers of WIDER Challenge and the link to our three tracks are:

WIDER Face https://competitions.codalab.org/competitions/19053
WIDER Pedestrian https://competitions.codalab.org/competitions/19118
Person Search https://competitions.codalab.org/competitions/19055

We just found that the states of all the new submissions are 'submitted' rather than showing any results. The situations are all the same in our three tracks. Could you help us solve the problem?  
I am looking forward to your reply.

Best regards,
Dongzhan Zhou

**Comment by ckcollab** [comment]
Were many submissions made at once? That may leave them queued up for some time. I was able to make a submission just now -- were they working then stopped?
