### ISSUE TITLE
Data/scorer dropdowns show uploads by other organizers

### ISSUE THREAD

**Issue by mbugert** [codalab/codalab-competitions#2344]
**Steps to reproduce:**
* Edit any competition (confirmed to happen with fresh sample competition)
* Add new phase
* Try selecting a starting kit, test dataset, scoring program, ...

**What happens:** The selection dropdowns show tons of uploads by other users. The competition can't be saved when selecting a scorer by someone else ("select a valid choice"). After failing once it will correctly show only the organizer's uploads.

**What should happen:** Only the organizer's uploads are shown, first try.

**Comment by Tthomas63** [comment]
Hello @mbugert,

Thank you for notifying us! We have temporarily removed this button, and we'll try to have this fixed by the end of the week.

Sorry for any inconvenience, and best regards,
Tyler

**Comment by Tthomas63** [comment]
Just an update, this feature is being disabled for the foreseeable future as there are more issues than just this case with it. We need to evaluate a re-write of this feature to fix bugs such as this.

Best regards,
Tyler
