### ISSUE TITLE
"submitted" state for the submissions

### ISSUE THREAD

**Issue by zoharai** [codalab/codalab-competitions#2355]
Hi,

I am developing a new competition and checking my scoring program.
I am using my own Competition docker image.
URL - https://competitions.codalab.org/competitions/19463?secret_key=af96c0dc-c119-4055-a2ce-b8c2f836a64f

Today, every submission I submitted remained in "submitted" state for quite a lot of time (an hour or so) and then began to run. I canceled some of them and then reran them and the behavior remained the same for most of the times.

Could you help me solve the problem?
Thanks!

**Comment by ckcollab** [comment]
We might have just had quite a bit of congestion, are you still experiencing this?

**Comment by zoharai** [comment]
Yes, the behavior is still the same.

**Comment by ckcollab** [comment]
With new submissions, or with the old ones? It could be during a restart or tweaking of workers your jobs were lost somewhere?

**Comment by zoharai** [comment]
both old and new submissions. Is there any way I can check what went wrong? or what is the status of the workers?

**Comment by ckcollab** [comment]
The submissions may have been lost when tweaking/restarting workers to fix some problems -- they seem to be working at this time, closing this issue for now.
