### ISSUE TITLE
Managing forum posts as a competition admin

### ISSUE THREAD

**Issue by idanbarak** [codalab/codalab-competitions#2357]
Hi, 
Wanted to know if theres is a way to delete/edit posts of the forum? i mean that as an admin i would like to have the ability to delete offensive/unrelated messages for example.
Couldn't find any information on FAQ or previous issues.
Thanks!

**Comment by Tthomas63** [comment]
Hello @idanbarak,

I do not believe we have any sort of forum management system for organizers/admins at the moment, but this is definitely a feature we would like to implement in v2.

Best regards,
Tyler
