### ISSUE TITLE
My job shows "preparing" status for more than a day

### ISSUE THREAD

**Issue by freesunshine0316** [codalab/codalab-competitions#2360]
My submitted decoding job shows "preparing" status for more than a day. 
The uuid is 0xcd131f, my username is freesunshine0316

**Comment by ckcollab** [comment]
If you try submitting a new job, does that go through?

**Comment by freesunshine0316** [comment]
@ckcollab I submitted another job 12 hours ago. It still shows "staged" status

**Comment by freesunshine0316** [comment]
My job has finished successfully.
