### ISSUE TITLE
CodaLab migration dates query

### ISSUE THREAD

**Issue by willprice** [codalab/codalab-competitions#2361]
Hi,

We're planning on launching a competition hosted on CodaLab at ECCV (European Conference on Computer Vision) on September 9th where we'll be demoing how to submit results from 9:35-9:50 CET (http://www.eyewear-computing.org/EPIC_ECCV18/program.html)

We're a little nervous about the CodaLab migration the day before in case something goes wrong and the platform will be down on the day. What is the scale of the planned changes and how confident are you that the down time will only be during the hours specified?

Many thanks for your excellent platform and help to the community!
Cheers,

**Comment by ckcollab** [comment]
The migration shouldn't be too terrible, but there are always unforeseen potential problems...

**Options:**
1. If there are problems we could roll back the changes so Codalab is usable for your event. After your event we could try the deployment again. I think this is an alright option, but hopefully we do not have to do this!
1. Move the date back a couple days, September 5th? Should give us some time to fix most potential problems, but we may bump into someone else's event.

I'd prefer the first option, a simple rollback and re-try at a better time.

> Many thanks for your excellent platform and help to the community!

Appreciate it :)

**Comment by willprice** [comment]
Hi @ckcollab,

Thanks for the quick response. Both sound like good options, and at worst we could always run our own instance of CodaLab for the event as it'll be primarily for demonstration purposes rather than people submitting results.

Thanks again!
