### ISSUE TITLE
Using a custom Docker image: "no space left on device"

### ISSUE THREAD

**Issue by MarvinLer** [codalab/codalab-competitions#2362]
Hello,

I am using a custom Docker image for my hosted competition (at https://codalab.lri.fr/competitions/178). The Docker image is available at https://hub.docker.com/r/marvinler/pypownet/.

When I try to submit a sample submission, the image is pulled during the ingestion phase (I use an ingestion program) but raises an error (part of _ingestion error log_ screenshot below):

![image](https://user-images.githubusercontent.com/14179877/44051190-726403ae-9f39-11e8-8223-f4aaddde1768.png)

Some details about the image:
- roughly, it is based on python:3.6-stretch, with 2 additional git clones, software installations (Octave) and python libraries installations
- the compressed size of the image is 744MB (taken from https://hub.docker.com/r/marvinler/pypownet/tags/), and its extracted size should be 1.94GB (obtained using `docker image ls`)

I could probably reduce the size of the image, although I am not sure if it is too big, or if I did something wrong in my competition hosting process (I used the _Competition docker image_ field in the edit mode on Codalab).

Do you know what should I do to correct this ? Please tell me if you need extra information.

Best and thanks,
ML

**Comment by ckcollab** [comment]
Please try this on production instead of LRI, the compute workers attached to that instance of Codalab are probably rather underpowered?

**Comment by ckcollab** [comment]
I updated and cleared these workers, then received this ingestion program `stderr`:


```python
Traceback (most recent call last):
  File "/tmp/codalab/tmpKYCYPP/run/ingestion_program/ingestion.py", line 83, in <module>
    main()
  File "/tmp/codalab/tmpKYCYPP/run/ingestion_program/ingestion.py", line 38, in main
    from env import RunEnv
  File "/tmp/codalab/tmpKYCYPP/run/ingestion_program/env.py", line 1, in <module>
    from src.game import IllegalActionException, LoadCutException
ModuleNotFoundError: No module named 'src'
```

**Comment by ckcollab** [comment]
Please let me know what other problems you run into!
