### ISSUE TITLE
New Competition Query

### ISSUE THREAD

**Issue by abhijeetchauhan** [codalab/codalab-competitions#2363]
Hello,

I am Abhijeet currently working at SBI LAB at IITD. We would like to host a competition on codalab. There will be two phases:
1. Development
2. Final

During development phase, we would have a result based scoring and a live leaderboard. But during the final phase, we would like to first freeze the leaderboard. Then take as input a writeup, opensource code and results. Using the result a private leaderboard is to be generated. Then, we will personally check the code to find cheaters from leaderboard toppers and remove them from the leaderboard. Finally, making the final leaderboard public.

We have the following queries:
1. How to change the input types between phases?
2. How to freeze the leaderboard in the second phase?

Warm Regards,
Abhijeet Chauhan
http://sbilab.iiitd.edu.in/

**Comment by ckcollab** [comment]
Hello!

1. Not sure I 100% follow "change input types between phases", but if I am understanding you: you can pass whatever you'd like as input/reference data to each phase, and your submissions/scoring program can handle it any way you'd like. Again, maybe misunderstanding?
2. You could freeze the leaderboard by setting an appropriate end date for the phase/competition?
