### ISSUE TITLE
codalab submission taking a lot of time to run. Even Submitted to Running phase is taking time. 

### ISSUE THREAD

**Issue by megjoshi** [codalab/codalab-competitions#2365]
codalab submission taking a lot of time to run. Even Submitted to Running phase is taking time.

**Comment by ckcollab** [comment]
For what competition? The submissions may be running slow as many people are participating in Codalab and we have limited resources. If you'd like to create a queue of workers just for your competition, you can do that [here](https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers).
