### ISSUE TITLE
support for numpy in evaluation script

### ISSUE THREAD

**Issue by rajarsheem** [codalab/codalab-competitions#2369]
Hi, I am trying to organize a  competition in Codalab. In my evaluation script (aka scoring program), I need to use numpy to produce the score. Looks like the import is not possible. Is there any workaround? 

Also, what is the best way to display stack-trace from any exception inside the evaluation script?

Thanks.

**Comment by ckcollab** [comment]
Stack trace should be in the stdout/stderr for scoring, submission or ingestion programs? You should be able to import `numpy`? That's surprising because it's one of our most popular libraries

**Comment by rajarsheem** [comment]
Hey, looks like it's my bad! The imports passed actually. Since it takes too long to finish (even for sample trials), I smelled a false alarm!

Do you mean checking the "View scoring output log"/"View scoring error log" to check for stdout/stderr ?

**Comment by ckcollab** [comment]
> Do you mean checking the "View scoring output log"/"View scoring error log" to check for stdout/stderr ?

Yep!
