### ISSUE TITLE
when submitting answer.txt but cannot get the score

### ISSUE THREAD

**Issue by blcunlp** [codalab/codalab-competitions#2373]
hello,
I am the organizer for CNLI: https://competitions.codalab.org/competitions/19911. Likes the Yellow World, our competition only need result submission. When I want to submit an answer.txt for testing, the output file shows that "accuracy: 0.0000". However, the evaluate.py works on my local environment, and return a score:" accuracy:0.6889". I tried many times, but nothing changes. 

How can i do with this problem?

**Comment by Tthomas63** [comment]
Hello @blcunlp,

Sorry for the difficulties, are you still experiencing this problem? It looks like your newest submission to the competition was evaluated correctly with a score of `0.3528`

![image](https://user-images.githubusercontent.com/28552312/44493030-62fee580-a61b-11e8-8652-58c92e8c722d.png)

Thanks, and best regards,
Tyler

**Comment by blcunlp** [comment]
It's the python version problem!!! LOL
I wrote evaluate.py in python3.6 at frist, then I rewrote it in python2.7 and finally got a score.
Anyhow, thanks for you replay.

**Comment by Tthomas63** [comment]
Hi @blcunlp,

Ah that would make sense! Glad you were able to solve it! Please let us know if you run into anymore issues.

Best regards,
Tyler
