### ISSUE TITLE
Change CodaLab competition admin?

### ISSUE THREAD

**Issue by Cyvhee** [codalab/codalab-competitions#2374]
Hi

I want to define another person as the (main) admin of our CodaLab competition. I already entered her name via Edit > Admins, but it seems that she does not receive an email when a new participants applies to the competition, while I still do. Can this be changed somehow?

Thank you!

**Comment by Tthomas63** [comment]
Hello @Cyvhee,

It is not currently possible on Codalab to transfer ownership of competitions, however we can change this manually. All we would need is the competition ID or URL, and the username of the user you are wanting to transfer ownership to.

Best regards,
Tyler

**Comment by Cyvhee** [comment]
Dear Tyler

Thank you for your prompt response. The URL of our competition is the following: https://competitions.codalab.org/competitions/17468. Could you please transfer ownership to the user "Eslefeve"? 

Thank you very much!

Kind regards
Cynthia

**Comment by Tthomas63** [comment]
Hi Cynthia,

No problem! Ownership should be transferred to the user `Eslefeve` now, and I have added you as a competition admin.

Please let us know if there are any issues.

Thanks, and best regards,
Tyler
