### ISSUE TITLE
Smart bug

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2377]
When we create links in HTML pages, eg page
https://competitions.codalab.org/competitions/2321

<ul>
<li><a href="../7471">Round 0: Sample data.</a></li>
<li><a href="../7462">Round 1: Novice level. binary classification problems, dense data.</a></li>
<li><a href="../7461">Round 2: Intermediate level. Multi-class classification, dense data.</a></li>
<li><a href="../7451">Round 3: Advanced level. Multi-class and multi-label classification, dense and sparse data.</a></li>
<li><a href="../9031">Round 4: Expert level. Everything else plus regression.</a></li>
</ul>

The smart editor replaces absolute link by RELATIVE links which are WRONG.

For example, I write:
a href="https://competitions.codalab.org/competitions/7471"

the editor replaces it by:
a href="../7471"

which gets translated into:
https://competitions.codalab.org/7471

INSTEAD OF

https://competitions.codalab.org/competitions/7471

I wrote about this bug multiple times. Somehow the Github issues always disappear but the bug remains.

**Comment by smdalton** [comment]
Hi, could I get some clarification on the "smart editor"? I'm not familiar with that and am looking into this problem.

**Comment by Krashcan** [comment]
Is this issue still open and can I work on it?

**Comment by ckcollab** [comment]
Yes, please!

**Comment by madclam** [comment]
Any update on this?

**Comment by Didayolo** [comment]
Merged.
