### ISSUE TITLE
when will the submission counter reset?

### ISSUE THREAD

**Issue by krumo** [codalab/codalab-competitions#2379]
I am working on a competition held on codalab and the organizer sets the max submission per day. I wonder when the submission counter reset so that I could fully utilize every chance to submit my results. Thanks!

**Comment by krumo** [comment]
I don't think my question is answered have no idea why this issue is closed. If you would like to spend time closing my issue, why not give me a short answer?

**Comment by ckcollab** [comment]
The submission counter resets every day, the server time should be listed on the competition page I believe? Apologies for closing it without an answer, I assumed you figured it out!

**Comment by krumo** [comment]
@ckcollab I see. I just want to verify that it resets at 0:00 UTC everyday. Thanks for your answer!
