### ISSUE TITLE
More information of the dataset

### ISSUE THREAD

**Issue by lancexiang** [codalab/codalab-competitions#2381]
Can I ask for the more description of the Dataset, such as what's the distribution of the lesion or liver cases and the size of lesion and so on. By the way, which period are the CT enhanced scans at?

**Comment by Tthomas63** [comment]
Hello @lancexiang,

For more information regarding the dataset please contact the competition organizer. As the developers of Codalab we do not have access to this type of information.

Thanks and best regards,
Tyler
