### ISSUE TITLE
Codalab maintenance : expected consequences

### ISSUE THREAD

**Issue by victor-estrade** [codalab/codalab-competitions#2386]
The TrackML challenge will start shortly. The maintenance of the Codalab public instance will happen during the challenge.
This challenge will be using code submission. The code will run on a dedicated cluster separated from Codalab (we are using a custom Queue and custom workers).

I wonder what will be the consequences of this migration for the participants in order to warn them.

1. Code submitted before the migration but that are still running will be shut down or will keep running on the cluster ?
2. Submitted code that will complete their task during the migration will wait for the server to be up again or be lost ?
3. Will the workers need to be restarted at the end of the migration ?

**Comment by ckcollab** [comment]
Jobs running during the migration will probably be lost, we'll have to shut things down completely so they may be in the middle of running. The workers should be pointing to the domain name, so when we change where the domain name points things should still work.
