### ISSUE TITLE
Team creation issue

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2388]
```python
File "/app/codalab/apps/teams/views.py", line 282, in form_valid
  form.save()

...

IntegrityError: duplicate key value violates unique constraint 
“teams_team_name_3146a213afbaca4e_uniq” 
    DETAIL: Key (name, competition_id)=(NAM, 321) already exists.
```

I believe we fixed this..? Strange it's popping up again..

# Todo

- [ ] Write a test that exhibits the broken behavior, and fails
- [ ] Fix the behavior, test passes now

**Comment by smdalton** [comment]
def form_valid(self, form):

        if form.instance.image:
            a=form.instance.image

        form.save()
        return super(TeamEditView, self).form_valid(form)

variable { a } doesn't appear to do anything here, it looks like the form is getting saved twice like a double submission from the error message.

**Comment by ckcollab** [comment]
@smdalton good eye! Yeah that looks funky... 

There may be some changes recently pushed to `develop` that touch that, btw!

**Comment by smdalton** [comment]
Additionally, from what I have read, form_valid should autosave the form, so the extra form.save() call doesn't do anything however this is on Django 2.0 docs.


from myapp.forms import ContactForm
from django.views.generic.edit import FormView

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)

**Comment by ckcollab** [comment]
Hopefully fixed, pulled extra save
