### ISSUE TITLE
Renaming of leaderboard keys is not updated on the leaderboards

### ISSUE THREAD

**Issue by jjyap** [codalab/codalab-competitions#2390]
Competition URL: https://competitions.codalab.org/competitions/20100

On my leaderboard I have a key named "j_Footprint" which I have renamed to "j_Foundation".  If I go to the edit page I see it named as "j_Foundation" however when I look at the leaderboard it is still named as "j_Footprint".

Also currently there is no way to add or remove columns from the leaderboard without creating a whole new challenge?

**Comment by MarcCote** [comment]
@ckcollab I have the same issue. We are about launch a competition what's our options to update the leaderboard column names?
https://competitions.codalab.org/competitions/20595#results

**Comment by Didayolo** [comment]
Merged.
