### ISSUE TITLE
Number of the Participants on the "Competitions I'm Running" page are doubled

### ISSUE THREAD

**Issue by TDaudert** [codalab/codalab-competitions#2395]
The number of participants per competition as shown in "https://competitions.codalab.org/my/#my_managing" is not correct. All figures are doubled.

**Comment by ckcollab** [comment]
Is this problem persisting? I've had a couple complaints about this but I see the right numbers, I believe anyway... which competition is causing the problems for you?

**Comment by TDaudert** [comment]
Yes, it's persisting for all 5 competitions I'm running. My account is "TDaudert".
The issue only occurs on the "Competitions I'm Running" [1] interface, the "Competitions I'm In" [2] interface displays the correct number of participants for each competition.

[1] https://competitions.codalab.org/my/#my_managing
[2] https://competitions.codalab.org/my/#my_participating

**Comment by madclam** [comment]
There is a strange bug in the number of competitions, e.g.
![image](https://user-images.githubusercontent.com/7594063/46124202-89461100-c1d7-11e8-895e-4cee6a96c487.png)

Competition https://competitions.codalab.org/competitions/2321
has only 694 participants.

**Comment by ckcollab** [comment]
Finally this should be fixed, was a very weird query problem... apologies for the delay in finding the problem!
