### ISSUE TITLE
Error when trying to "Download all submissions on leaderboard"

### ISSUE THREAD

**Issue by richardaecn** [codalab/codalab-competitions#2396]
Hi,

I am the organizer for COCO Detection Challenge: https://competitions.codalab.org/competitions/5181 . I always get the following error message when clicking "Download all submissions on leaderboard" in certain phase of the challenge.

"There was an error retrieving the file. Please try again later or report the issue."

Specifically, the "test-challenge2018 (segm)" phase only has one entry on the leaderboard but still get the error.

Thanks!

@ckcollab

**Comment by ckcollab** [comment]
Apologies for the problem, this should be fixed now!
