### ISSUE TITLE
How to get team info and description for each entry?

### ISSUE THREAD

**Issue by richardaecn** [codalab/codalab-competitions#2397]
Hi,

I am the organizer for COCO Detection Challenge: https://competitions.codalab.org/competitions/5181 . I am wondering, are there any easy ways to get team info and description for each entry, other than "download all submissions on leaderboard"?

Context: We are migrating the CodaLab leaderboard to our own leaderboard here http://cocodataset.org/#detection-leaderboard that contains team information, description, and detailed results. However, I cannot get the team information and description for a given entry.

Specifically, is there a way to download team info, descriptions and private outputs from scoring step for all entries on the leaderboard?

Thanks!

@ckcollab

**Comment by ckcollab** [comment]
@richardaecn unfortunately, if not provided in the current feature, it is probably not available easily. I know there are a few ways to dump submissions/participants, but I don't think one includes all of the information you want. May have to write a simple parser (I suggest `lxml` in Python) to interpret your Participant/team page?

I may be misunderstanding, apologies if so!
