### ISSUE TITLE
The website shows a decision is pending.

### ISSUE THREAD

**Issue by wcy0319** [codalab/codalab-competitions#2398]
I want to participate the bone age challenge, but I recieved the message that Your request to participate in this challenge has been received and a decision is pending.

**Comment by minesh1291** [comment]
same issue with me. it's pending for me for more than a week. and my mails are not getting delivered to "team@mafatchallenge.com"

**Comment by Tthomas63** [comment]
Hello all,

Competition organizers are the one's who approve/disapprove participants for their competitions, so unfortunately we cannot interfer. It would probably be best to contact the competition organizer for more information.

Best regards,
Tyler
