### ISSUE TITLE
When I sign up，I can‘t get a verifying email.

### ISSUE THREAD

**Issue by lsy641** [codalab/codalab-competitions#2405]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using? chrome
2. We have sent an e-mail to siyang-l18@mails.tsinghua.edu.cn for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.

**Comment by Tthomas63** [comment]
Hello @lsy641,

Could you please check your spam/junk folder to make sure it did not get flagged as spam? If it is not there we should be able to re-send an activation code to your email.

Thanks, and best regards,
Tyler
