### ISSUE TITLE
'NoSuchKey' error for one of the files for downloading

### ISSUE THREAD

**Issue by SuperIRabbit** [codalab/codalab-competitions#2417]
In one of our competitions (https://competitions.codalab.org/competitions/18467), whenever someone clicks on the "public data" file under "participate->files" tab, a key error occurs (it was working before). 

Link: https://competitions.codalab.org/competitions/18467#participate-get_starting_kit

The error msg says: 
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key/>
<BucketName/>
<Resource>
/prod-private/dataset_data_file/None/e3163/road-train-2 valid.v2.zip
</Resource>
<RequestId>3L137</RequestId>
<HostId>3L137</HostId>
</Error>
```

**Comment by ckcollab** [comment]
I believe we fixed this, let me know if not!
