### ISSUE TITLE
No Sign Up Email Recieved

### ISSUE THREAD

**Issue by abi-aryan** [codalab/codalab-competitions#2418]
Haven't received a signup verification email for CodaLab, waited for around 20 mins. 

![signup](https://user-images.githubusercontent.com/7281944/45928007-36abf100-bf5a-11e8-9d80-7fefe7bda5e5.PNG)

Hi Eric (@ckcollab ), could someone from the team please check?

Email : learningrockstars@googlegroups.com

**Comment by Tthomas63** [comment]
Hello @abi-aryan,

Would you be able to check your spam/junk folder to make sure it was not flagged as spam? If not we should be able to re-send an activation code to your email.

Thanks, and best regards,
Tyler

**Comment by abi-aryan** [comment]
Hi @Tthomas63 haven't yet.. Can you please resend?

**Comment by ckcollab** [comment]
I think you can resend by attempting to sign in again. Or you can try registering with a different address potentially?

**Comment by abi-aryan** [comment]
Let me try both the options @ckcollab - will update in a minute

**Comment by abi-aryan** [comment]
So, tried multiple times, I think the codalab platform isn't configured to work with a google groups email (very fishy) - didn't find any email in spam either - the group's email ID receives all other emails though. 

Anyway, tried configuring the account with a Gmail ID and it worked. Thanks for all the suggestions.

**Comment by ckcollab** [comment]
Could you email me eric@ckcollab.com from the non-working address? Is it something like... `name+suffix@gmail.com`?
