### ISSUE TITLE
Change template to make all 5 popular/featured competitions appear without scrolling

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2425]
![image](https://user-images.githubusercontent.com/2185159/46097108-d72a2d00-c175-11e8-9249-ccdac6af7ff0.png)

Change the above template to show all 5 popular/featured competitions without scrolling -- make competition tiles wider?

**Comment by Tthomas63** [comment]
@ckcollab Did this get implemented with featured competition changes?

**Comment by ckcollab** [comment]
Unfortunately no, I did try to make it take up less vertical space but I ended up causing some bugs with award amounts not showing properly and such, probably needs more TLC to get compressed vertically:

![image](https://user-images.githubusercontent.com/2185159/47033426-a06a8580-d129-11e8-900a-45860e350e95.png)
