### ISSUE TITLE
Immediate failure of submissions

### ISSUE THREAD

**Issue by HolyBayes** [codalab/codalab-competitions#2426]
Hi all! 

**Problem:** I have launched Data Science [competition](https://competitions.codalab.org/competitions/edit_competition/19818) on CodaLab platform at August and during last (private) competition phase we've met some issues with submissions processing. 

On the [screenshot 1](https://ibb.co/jnm0mz) You can see that all participants submissions are in "Failed" status. I've tried to explicitly re-run all submissions, but it goes to the same status immediately. I've also tried to see failure details, but after clicking on any corresponding button (like "View scoring output log" button etc.) I'm getting [404 error](https://ibb.co/cCyVmz). Finally, to find what the problem is, I've launched my personal worker queue, but it didn't help too. That's interesting fact, that I'm using common scoring backend for both 2 last phases (current and previous phases), and both of them are evaluated on equal sized answers datasets with absolutely the same structure. But the first one was successfully completed, while the current one not. It makes me to suppose that it is not my failure and could be caused on CodaLab server side.

**Question:** How to make all submissions from the last step be processed ?

**Appendix**
Ingestion program enabled, but empty (it doesn't takes any effect and can be disabled).

[competition.yml](https://pastebin.com/4zV3zTyW)

**Comment by anaderi** [comment]
I'd ask to look into this since it is a showstopper - we cannot finalize a competition (grade final private phase).

**Comment by ckcollab** [comment]
Could you add `eric2` as an admin to this competition so I can poke around, if that's alright?

**Comment by HolyBayes** [comment]
Now it is really works, thanks a lot!
