### ISSUE TITLE
Grand-challenges indexed on ChaHub

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2427]
From: James.Meakin
Subject: Listing grand challenge challenges on chahub

I lead the development of grand-challenge (both the framework and instance at grand-challenge.org) and Bram has forwarded your email about the chahub competitions search engine to me. It would be great if we could get the challenges hosted there listed on chahub - we could also extend this to the external challenges that we index. What would we need to do? We currently do not list the challenges in our REST API, but we can add it and give you access.

**Comment by ckcollab** [comment]
Moved to Chahub https://github.com/codalab/chahub/issues/107
