### ISSUE TITLE
Safari weird layout

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2428]
This concerns the Google staging server for AutoDL, competition 40.
Using Safari, the menu ins UNDER the separation bar of the header, instead of below. Chrome, Explorer, and Firefox OK.

<img width="1384" alt="screen shot 2018-10-05 at 4 57 31 pm" src="https://user-images.githubusercontent.com/7594063/46565010-2c75e500-c8c0-11e8-9829-6db5f8e2c757.png">
<img width="1162" alt="screen shot 2018-10-05 at 4 57 45 pm" src="https://user-images.githubusercontent.com/7594063/46565011-2c75e500-c8c0-11e8-917c-99521129a70c.png">

**Comment by Tthomas63** [comment]
I found the issue with this and have pushed a fix to the staging server. It slightly alters the styling of the tabs but it should fix the issues with the Safari display:

Chrome:
![image](https://user-images.githubusercontent.com/28552312/46635792-74884800-cb0a-11e8-8478-337a22560115.png)

Safari:
![image](https://user-images.githubusercontent.com/28552312/46635836-984b8e00-cb0a-11e8-8748-8a4fadde9ada.png)

**Comment by madclam** [comment]
Using Safari I cannot upload files: There was an error uploading the file. Please try again.

**Comment by Tthomas63** [comment]
I think this may have been caused by something else like a momentary drop in connection or slow upload speed. When testing today between Zhengying, Ted and myself we were able to successfully make submissions from Safari.
