### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2429]
This concerns the Google staging server for AutoDL, competition 40.

When I make a submission, there are immediately those links

Detailed Results
Output Log
Error Log
Download Output

But clicking on them yields 404 errors

<img width="1199" alt="screen shot 2018-10-05 at 5 26 59 pm" src="https://user-images.githubusercontent.com/7594063/46565477-a740ff00-c8c4-11e8-8505-eaf0643d6f82.png">
<img width="1211" alt="screen shot 2018-10-05 at 5 27 07 pm" src="https://user-images.githubusercontent.com/7594063/46565478-a740ff00-c8c4-11e8-98e1-b7a050d948f2.png">
<img width="1249" alt="screen shot 2018-10-05 at 5 28 19 pm" src="https://user-images.githubusercontent.com/7594063/46565479-a740ff00-c8c4-11e8-94cc-2703554dab4d.png">

**Comment by Tthomas63** [comment]
I've pushed a small fix to the staging server to prevent this race condition.

While testing I did not encounter any 404's for the files, but it may still be possible due to it being a race condition.

Please let me know if there are any issues with this fix!

Best regards,
Tyler

**Comment by madclam** [comment]
When I submit and it works, if I click “detailed results”
Pasted image at 2018-10-09, 2:47 PM 

Same for
   Detailed Results
   Output Log
   Error Log
   Download Output
Interestingly, if I refresh, then I cannot see the table anymore, it just says “Submitting”. I cannot update the description either.

**Comment by Tthomas63** [comment]
Sorry for the late reply,

The fix for this should have been pushed with the file-name length validation fix for the issue Zhengying found.
