### ISSUE TITLE
Curve refresh

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2430]
This concerns the Google staging server for AutoDL, competition 40.

Even after the submission has terminated executing, the learning curves keep refreshing.

**Comment by Tthomas63** [comment]
I believe this is due to the outputted detailed results page having this meta property at the top of the file:

`<meta http-equiv="refresh" content="5">`

This should be changed on the competition bundle side of things I believe.

**Comment by madclam** [comment]
Fixed by Zhengying. Thanks.
