### ISSUE TITLE
How to create sub/multi-columns in a leaderboard

### ISSUE THREAD

**Issue by kovvalsky** [codalab/codalab-competitions#2431]
I failed to find a guide on how to create sub/multi-columns in a leaderboard.
What I mean in sub/multi-columns is this:
![this](https://cloud.githubusercontent.com/assets/1713511/9235934/3629c612-4118-11e5-9e05-ea63af7e336d.png)

It would be nice if such a guide is part of this wiki page: https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard#leaderboard-nuts-and-bolts

**Comment by madclam** [comment]
Is this competition still on https://competitions.codalab.org/? Can you tell us the number? Some features have been implemented for the needs of special competitions and never documented...

**Comment by kovvalsky** [comment]
https://competitions.codalab.org/competitions/1#results
Another, recent one:
https://competitions.codalab.org/competitions/17751#results

**Comment by wenyiw** [comment]
I'm trying to do the same thing (sub columns). Have anyone figured this out?

**Comment by anderskm** [comment]
@kovvalsky and @wenyiw 
I ran into the same problem, but after a bit of searching for "SemEval-2018 competition.yaml", I found [this example](https://github.com/danielhers/semeval-ucca/blob/master/competition/competition.yaml#L42), which helped me figure it out the correct format. It includes both multiple leaderboards and multiple grouped columns in at least one of the leaderboards.
