### ISSUE TITLE
Chahub sharing on facebook (And other social media)

### ISSUE THREAD

**Issue by ieee8023** [codalab/codalab-competitions#2433]
I wanted to share the Chahub project on facebook but it doesn't have a good preview picture or text. I think without this it won't be as popular as it could be. You can debug what the preview looks like here:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fchahub.org%2F

You should add the following tags to control what the preview looks like.

<meta property="og:title" content="..
<meta property="og:description" content="..
<meta property="og:image" content="url to image

**Comment by ckcollab** [comment]
Thanks!

Moved this issue here: https://github.com/codalab/chahub/issues/106
