### ISSUE TITLE
Adding a new phase?

### ISSUE THREAD

**Issue by shervin64** [codalab/codalab-competitions#2436]
I have an exiting competition and would like to add a new phase.

However, there is no such option on the edit competition page.

From what I recall, it was previously possible to add new phases via the web interface. Was it removed?

**Comment by shervin64** [comment]
Bump

**Comment by ckcollab** [comment]
Yes, unfortunately we removed this feature as it was causing bugs in existing competitions. A slightly tedious solution in the mean time would be to create a new competition for this new phase -- is that an OK option for you?
