### ISSUE TITLE
Competition Originally in Old YAML Format

### ISSUE THREAD

**Issue by rsharma441** [codalab/codalab-competitions#2437]
Hi,

I am managing a competition The Story Cloze Test [https://competitions.codalab.org/competitions/15333] and it was created in October of 2016, which used the old YAML formatting style for datasets. Within our initial YAML file are links to download datasets that are displayed in our Participate/Get Data. These represent the data from phase 1 and 3 of our 3 phases and I want to edit phase 2 to feature a new dataset and have it show on the Get Data page. I am not sure I am able to still do so. So two things:

A. I don't know if there is any way to add a dataset as an external download link anymore. It was easy with the old YAML file, but doesn't seem possible within the "Create Dataset" menu. 

B. Every time I try to edit the competition and add a dataset for my Phase 2, nothing changes. I assume this is because this comp is made with an outdated format and the Get Data tabs are not around anymore, and the new style uses the "File" tab. 

Is there anything I can do to initiate a new phase on my current competition, with a download Link for phase 2 on the current Get Data Page, or is the only option to create a new competition and thereby lose all the results from my earlier phases?

**Comment by madclam** [comment]
If you want to point to datasets with external download links, I think the old-style YAML format still works, but you can also put links in the HTML pages, anywhere you want. They can be edited even while the competition is running.

The old-style manner of including pointers to data is NOT editable from the editor. SO I think it si preferable to just put links in the HTML pages.

In the new style, here is what you can do:
1) Upload your datasets in My Datasets, under the tag "public data", with a name easily recognizable and a meaningful description.
2) In your phases, choose for "Public data" the name of the dataset you want people to be able to download. Then the dataset will be downloadable from the "Files" tab.
