### ISSUE TITLE
Please stop some submissions

### ISSUE THREAD

**Issue by yuantailing** [codalab/codalab-competitions#2440]
I'm sorry that I made a infinite loop when I'm debugging scoring program. Please stop these submissions since they are still running and consuming computing resources, thanks.

Competition:
https://competitions.codalab.org/competitions/20341

Submission ID:
 - 487573
 - 487574
 - 487583
 - 487595

**Comment by Tthomas63** [comment]
Hello @yuantailing,

Thanks very much for letting us know! Fortunately it looks like these submissions did get killed successfully when hitting the execution time limit, just the status didn't change.

Thanks, and best regards,
Tyler
