### ISSUE TITLE
site is down?

### ISSUE THREAD

**Issue by ng-Laser** [codalab/codalab-competitions#2443]
https://competitions.codalab.org

"This site can’t be reached competitions.codalab.org took too long to respond."
Could not reach on chrome [version 70.0.3], firefox [60.0.3], explorer

codalab.org and https://worksheets.codalab.org work fine

**Comment by unnir** [comment]
+ 
cannot open competitions page.

**Comment by maksimovkonstantin** [comment]
same problem
