### ISSUE TITLE
data challenge

### ISSUE THREAD

**Issue by SiZHANG0303** [codalab/codalab-competitions#2444]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by Didayolo** [comment]
This is just the template for writing issues with the title "data challenge".

Please create a more informative entry if you need help.
