### ISSUE TITLE
AutoML3 failures

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2445]
This issue concerns competition https://competitions.codalab.org/competitions/19836.

There are frequent failures, which may be coming from faulty workers.

762 | Oct. 26, 2018, 2:35 a.m.
764 | Oct. 26, 2018, 3:30 a.m.
767 | Oct. 26, 2018, 8:45 a.m.
768 | Oct. 26, 2018, 9 a.m.
771 | Oct. 26, 2018, 1:38 p.m.

Traceback (most recent call last):
  File "/worker/worker.py", line 322, in run
    if input_rel_path not in bundles:
TypeError: argument of type 'NoneType' is not iterable

**Comment by ckcollab** [comment]
For my understanding, what is the difference between all of the AutoML3 competitions? What are all of the active ones?

**Comment by ckcollab** [comment]
This error hasn't popped up again, it seems to have been isolated to one worker...

**Comment by willprice** [comment]
I've been getting the same issue on my competition using the `codalab/codalab-legacy:py37` docker image

```
Traceback (most recent call last):
  File "/worker/worker.py", line 330, in run
    if input_rel_path not in bundles:
TypeError: argument of type 'NoneType' is not iterable
```
