### ISSUE TITLE
Not receiving verification email to finalize signup process

### ISSUE THREAD

**Issue by ramaMukundan** [codalab/codalab-competitions#2446]
I was trying to sign up for the SPIE Challenges competition, and I am not getting the verification email despite several attempts.  The user name and email used are as follows:
User name: cgmia
Email:  mukundan@canterbury.ac.nz

A screenshot of the website is attached below.
![image](https://user-images.githubusercontent.com/44602982/47707818-9d2ada00-dc91-11e8-850e-348db4e044b8.png)

**Comment by ckcollab** [comment]
That website is hosted on some server `*.cloudapp.net`, we run `competitions.codalab.org` -- you'll have to contact the folks running the SPIE challenge :)
