### ISSUE TITLE
Submssions stuck in "submitted" status

### ISSUE THREAD

**Issue by idanbarak** [codalab/codalab-competitions#2450]
Hi, Im running MAFAT Challenge competition
(https://competitions.codalab.org/my/competition/19854)

In the last 24 hours about 30 percent of submissions are stuck in "submitted" status. I've checked some of the submission files and they are fine.
Is there any known issue regarding this problem on the platform?

Thanks!

**Comment by ckcollab** [comment]
Codalab is experiencing unusually high volumes of usage, let's see if it dies down soon..

The tasks stuck as "submitted" _should_ eventually be picked up, but we're getting > 100 submissions per hour right now. We may want to add some kind of popup or warning to let people know they should make submissions a bit slower!

**Comment by nathantsoi** [comment]
ok, thank you for the update!

**Comment by nathantsoi** [comment]
submissions were working for a moment, but now i am seeing just "Submitted" again

**Comment by rajarsheem** [comment]
I am facing the same issue. It's been hours.
Competiton id: 19790

**Comment by rajarsheem** [comment]
@Tthomas63 , can you please look into it?

**Comment by nathantsoi** [comment]
also, for reference, none of my submitted tasks ever processed

**Comment by rajarsheem** [comment]
That is shocking to hear! @ckcollab , @Tthomas63 please look into this issue. Our submissions are still pending. Even with high traffic like the one you described, queuing time should not be this high.

**Comment by rajarsheem** [comment]
That is shocking to hear! Looks like queuing time is exceptionally high. 
@ckcollab @Tthomas63

**Comment by madclam** [comment]
There seems to have been a faulty compute worker picking jobs and abandoning them without processing them. Eric is still troubleshooting the problem.
Old jobs stuck in the “submitted” mode will not be processed, but the queue seems to be now processing jobs normally.
Please let us know if you are experiencing more problems.

**Comment by nathantsoi** [comment]
thanks for the update @madclam, things were working great last night, but I tried again this morning and my submission is stuck in `Submitted` again

**Comment by nathantsoi** [comment]
and, things are working again!

**Comment by gchrupala** [comment]
I am also seeing this problem with this competition: https://competitions.codalab.org/my/competition/20584/submissions/
A submission has been stuck in the submitted state for ~6 hours.

**Comment by ckcollab** [comment]
Should be fixed, apologies for the sporadic problems
