### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by Tommymhz** [codalab/codalab-competitions#2453]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------
https://competitions.codalab.org/competitions/5181#participate
test-dev2018(segm)

If you are having trouble using the site:
-----------------------------------------
safari
I upload 300M zipped file, but get error(Sorry, failed to upload file.)

In last month for competition, uploading  is ok

**Comment by julvo** [comment]
I get the same error 'Sorry, failed to upload file' when uploading the ~100mb submission for: https://competitions.codalab.org/competitions/11161

Tried on both Firefox and Chrome.

The POST to https://newcodalab.lri.fr/prod-private returns a status 400 and it seems to happen after the file is transferred.

**Comment by KeqiWangSXuniversity** [comment]
Have you sloved this problem?

**Comment by Didayolo** [comment]
This issue is sometimes due to bad connection (e.g. low upload speed).

#2512 
#2654

Try to upload files with a fast and stable connection. Hopefully we'll improve stability of uploading files in the future.

I close this issue as it is old, feel free to re-open it if needed.
