### ISSUE TITLE
Featured challenges obsolete

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2454]
On the front page of Codalab:
https://competitions.codalab.org/

The list of featured competitions is bogus, it shows old competitions.

<img width="920" alt="screen shot 2018-11-08 at 9 45 42 pm" src="https://user-images.githubusercontent.com/7594063/48246642-0ce14900-e3a5-11e8-8aa0-90e66ebd3566.png">

**Comment by madclam** [comment]
This is strange that no competition met the criterion: when I noted this problem there were A LOT of competitions that met the criteria of being active, recently started and/or having a deadline soon. NONE of the one showed in the featured list met such criteria. This is obviously a bug. Featured competitions that should have showed up include TrackML that paid for that feature.

**Comment by Didayolo** [comment]
This has not been updated.

**Comment by Didayolo** [comment]
Close because of duplicates.
