### ISSUE TITLE
Changes in edit mode are not getting reflected

### ISSUE THREAD

**Issue by rajarsheem** [codalab/codalab-competitions#2458]
1. What browser and version are you using? Chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using! https://competitions.codalab.org/competitions/18912

Hi, 
I am making changes in edit mode like removing phases, changing public and input data for a particular phase but they are not getting reflected after saving.

Can you please help ?

**Comment by carlgogo** [comment]
Same problem here.

**Comment by Didayolo** [comment]
This sometimes happens when an error prevents the changes from being applied.

#2546 
#2665 

Try to scroll down in edit page to spot an error message.

**Comment by Didayolo** [comment]
Merged.
