### ISSUE TITLE
failed to upload file 

### ISSUE THREAD

**Issue by caiqi** [codalab/codalab-competitions#2459]
1. What browser and version are you using?
Chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

I met `Sorry, failed to upload` error when uploading results. The competition is https://competitions.codalab.org/competitions/18892#participate .  Could you please have a check? Thanks.!

**Comment by LuoweiZhou** [comment]
Hi @caiqi, I had a similar issue. How did you solve the problem?
