### ISSUE TITLE
Run a container inside the competition docker

### ISSUE THREAD

**Issue by dominicmorin** [codalab/codalab-competitions#2463]
Url: https://competitions.codalab.org/competitions/20595 (**not public yet**, `eric2` and `tthomas63` are admins)

We are hosting a competition on CodaLab using a VM in Azure. I see that for each submission, the docker “codalab/competitions-v1-compute-worker:latest” ("_worker container_") starts the docker that we specified in our configurations (the "_competition container_"). I would like the _worker container_ to start the _competition container_ with the “-v /var/run/docker.sock:/var/run/docker.sock” option. Our goal is to run an evaluation step in a distinct container, isolated from our hidden data, with possible participant-defined dependencies. 

Is it possible?
If not, do you have any alternative to offer?

**Comment by tavianator** [comment]
We modified https://github.com/codalab/competitions-v1-compute-worker/blob/master/worker.py#L551 and the other similar set of lines to add the `-v /var/run/docker.sock:/var/run/docker.sock`.
