### ISSUE TITLE
Sign up 

### ISSUE THREAD

**Issue by anantiitml** [codalab/codalab-competitions#2465]
I have a serious problem with completing sign up using username -- "msaic_anan_3391" which is required to enter into competion but i have used the mail id "jtm162085@bst.iitd.ac.in" which is not existed now. Please can you delete that account so that i can re-register with different email id with same username.
Please reply ASAP.

**Comment by ckcollab** [comment]
Here is a solution to your problem:
- create an account with a different email
- contact your competition organizers to make sure they remove the old account from the list of participants so you are not accused of cheating by having multiple accounts.
