### ISSUE TITLE
Can't edit any of my datasets in the UI

### ISSUE THREAD

**Issue by MarcCote** [codalab/codalab-competitions#2472]
If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
**eric2 is already added**
2. Please post a link to your competition
**https://competitions.codalab.org/my/datasets/#**

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
**Chrome Version 70.0.3538.110 (Official Build) (64-bit)**
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
**https://competitions.codalab.org/my/datasets/#**

**Comment by MarcCote** [comment]
To be more precise I'm trying to follow this section of the wiki
https://github.com/codalab/codalab-competitions/wiki/User_Dataset-Management#modifying-datasets

**Comment by ckcollab** [comment]
I believe we removed dataset modifying some time ago (so I've removed that from the Wiki). If you need to re-name a dataset, you'll have to upload it again -- I believe.

**Comment by MarcCote** [comment]
Alright. Thanks for the feedback.
