### ISSUE TITLE
Question: Can I authenticate users with AD

### ISSUE THREAD

**Issue by oysteijo** [codalab/codalab-competitions#2478]
Just a sort question: I've managed to set up an company internal codalab, however, instead of having user registration by signing up and email verification, I would love it if users can be identified and authorized with out internal active directory service? Is that possible? Is it as simple(?) as having django configured with AD?

**Comment by Tthomas63** [comment]
Hello @oysteijo,

Yes this should be possible with Django, however it would probably require some new libraries, and changes to the code in order to use AD.

Best regards,
Tyler
