### ISSUE TITLE
missing volume

### ISSUE THREAD

**Issue by lancexiang** [codalab/codalab-competitions#2480]
when I submit my results, there is an error happened like following:
```python
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpGVzkTt/run/program/evaluate.py", line 67, in 
    "Missing volume: {}".format(submission_volume_path))
ValueError: Submission volume not found - terminating!
Missing volume: /tmp/codalab/tmpGVzkTt/run/input/res/test-segmentation-0.nii
```
Can you help me solve this problem?

**Comment by ckcollab** [comment]
From the looks of it, it could be the competition scoring program, have you showed this to the competition organizers?

**Comment by lancexiang** [comment]
Uh..., I don't konw how to get contact with the official organizers about LITS, is there any e-mail address or other ways to report this problem to organizers? BTW, I have failed four times or total time...

**Comment by ckcollab** [comment]
https://competitions.codalab.org/competitions/17094#learn_the_details-organizer

**Comment by lancexiang** [comment]
OK, I see. But there are so many "organizer", so who should I get contact with. Can you help me report this bug to them? Thanks very much.

**Comment by ckcollab** [comment]
I don't know, actually, we run the website and not this competition. I would go down the list and try contacting people, maybe? Not sure.

I know Patrick has posted on GitHub before, did you Google that name?

Closing this for now..
