### ISSUE TITLE
Can the score can be hidden?

### ISSUE THREAD

**Issue by lancexiang** [codalab/codalab-competitions#2483]
There some score that I have seen yesterday, but when I want to search it today, I can't find it. So that means the score can be hidden or like 'undo'? if so, how to do it?

**Comment by Didayolo** [comment]
We need more information to help you.

What is the competition? 
What is the submission you are referencing to ?
Was it on the leaderboard or on your submissions?

I close the issue as it is outdated.
Feel free to re-open it and answer if needed.
