### ISSUE TITLE
Change username or delete account

### ISSUE THREAD

**Issue by nanobyte-dg** [codalab/codalab-competitions#2484]
I want to change my username on CodaLab. I registered the account for a team contest and the account detail is shared amongst three members. I want to either change my username or delete the account associated with my email id (so I can create new account from the same id but different username). 

Please suggest on how I can do the same.

**Comment by Tthomas63** [comment]
Hello @nanobyte-dg,

Apologies for the late response, what would be the new user-name you would like and what is your current user-name?

Thanks and best regards,
Tyler

**Comment by nanobyte-dg** [comment]
Hello @Tthomas63,

Thanks for the response. 
My current username is : msaic_deva_anki_vish_4425

I would like it to be changed to either of the following based on the availability:
1. nanobyte
2. nanobyte-dg

Thanks and best regards,
Devansh

**Comment by Tthomas63** [comment]
Hello @nanobyte-dg,

No problem! The username `nanobyte` was unavailable so I changed the username to `nanobyte-dg`.

Please let me know if there are any more issues!

Best regards,
Tyler

**Comment by spurscoder** [comment]
Hello @Tthomas63,
I want to change my username on CodaLab, too. A long time ago, I signed up for this account for myself at school. But recently, this account is not only for myself, but also for the team of the company. So I really want to change it.

Below is my registration information:
My current username is : `BUAA_WJP`
I would like it to be changed to : `spur_yd`

Thanks and best regards,
SPUR

**Comment by hlsrekhamu** [comment]
Hello, 
I want to change my username on Codalab or delete my codalab account.
My user name: Shashi  (in fact there are 2 user ids with the same name but different email id and both are mine). 
I would like to change it to: Shashirekha.

Thanks and regards
Shashirekha

**Comment by aniskacem** [comment]
Hi @Didayolo, 

It seems that the e-mail address info@codalab.org is not valid anymore, any clues? 

Thanks in advance! 
Anis

**Comment by Didayolo** [comment]
@aniskacem Sorry for the late reply, I missed the comment as this issue is closed.

We are still receiving emails at info@codalab.org regularly, I don't see any problem with it.

**Comment by lxezxc** [comment]
Hi @Didayolo,
    I wanna change my codalab's username, but i'cant change it by myselg, could you please help me to deal it?
        my current username is lxe
        the wanted username is NJUST-KMG or NJUST-KMG1(an alternative)
        and my register's email is 865069924@qq.com
    many thanks !
Best regards 
Transirnt

**Comment by Didayolo** [comment]
@lxezxc 

Please send your request to info@codalab.org, using your account email. Thanks!
