### ISSUE TITLE
Compétition HADACA : "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."

### ISSUE THREAD

**Issue by HADACA** [codalab/codalab-competitions#2490]
Bonjour,

Pour l'organisation de la compétition HADACA (https://codalab.lri.fr/competitions/333?secret_key=5a2afb10-c5a0-49f2-a8b5-2a57370e39f6), nous obtenons l'erreur suivante lorsque nous soumettons un code comme résultat : "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."

Exemple : regarder "View ingestion error log" de la soumission 6417.

Cordialement,
L'équipe HADACA

**Comment by madclam** [comment]
From challenge 399
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpT6Foek/run/ingestion_program/ingestion.py", line 229, in <module>
    Y_train = M.predict(D.data['X_train'])
  File "/tmp/codalab/tmpT6Foek/run/program/model.py", line 138, in predict
    X = self.process_data(X)
  File "/tmp/codalab/tmpT6Foek/run/program/model.py", line 113, in process_data
    X = (X - mean) / std
MemoryError

**Comment by jayleicn** [comment]
Hi @Tthomas63 ,

Two of my challenges, 20687 and 20686 are also experiencing this problem, which makes all the submissions fail. Is there a quick fix for this? (Even dirty ones, on the organizer side.)

Best,
Jie

**Comment by gibsonbailey** [comment]
In this [Stack Exchange post](https://unix.stackexchange.com/questions/342735/docker-warning-no-swap-limit-support), instructions are posted to enable swap.

<img width="661" alt="Screen Shot 2019-04-12 at 6 12 04 PM" src="https://user-images.githubusercontent.com/21694127/56072716-9333f980-5d4e-11e9-9f13-22b6a3539b0a.png">

**Additionally**, the machine must be rebooted. Use `sudo reboot`.

This got rid of the warning shown with `docker info` on an ubuntu image I just spun up and tested.

**Comment by surajiiitd** [comment]
Can anyone fix this issue ? 
I am also getting the "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap." while submitting.

I need the quick help.

**Comment by ckcollab** [comment]
This is just a warning, not an error.

**Comment by Didayolo** [comment]
But still this is not very convenient to have a warning on every submission...

**Comment by tanuj2212** [comment]
Dear Organisers,

We tried submitting the results for taskA - English of SemEval Task 6.  We followed the instructions given, by creating a zip file name "task_a_en.zip" containing a text file named "task_a_en.txt".

However, we are not able to see any feedback on the submission. When we tried to open any of the links "View scoring output log, Download output from scoring step, Download private output from scoring step", we got "Access to codalab.lisn.upsaclay.fr was denied". Moreover, when we open the link "View scoring error log", we got "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."

kindly let us know what is the issue.

Regards

**Comment by Didayolo** [comment]
@tanuj2212 

Hi, thank you for reporting this issue. We are trying to fix it as soon as possible. I'm tracking it in the following issue: #3074.

By the way, the `WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.` error message is not concerning.

**Comment by hyejwon** [comment]
@Didayolo I get the same error. Help me.#3087
