### ISSUE TITLE
Website is not responding - submission on pause

### ISSUE THREAD

**Issue by mpalrocks** [codalab/codalab-competitions#2494]
I am participating in SemEval 2019 under Task 6. I just have a hours left for my submission for Sub-Task:B. But the website [https://competitions.codalab.org/competitions/20011](https://competitions.codalab.org/competitions/20011) is not responding. Please help!

1. What browser and version are you using?
I have tried using Mozilla Firefox and Google Chrome- none of them is responding.
2. What is the URL of the problem? 
https://competitions.codalab.org/competitions/20011

**Comment by MarcCote** [comment]
Same here. It seems the whole https://competitions.codalab.org/ website is down.

**Comment by mpalrocks** [comment]
Everything is perfect now.
I am closing this issue.
