### ISSUE TITLE
failed to upload file

### ISSUE THREAD

**Issue by antonia329** [codalab/codalab-competitions#2495]
problem:
failed to upload 350M+ zipped file.(Sorry, failed to upload file.)
1. browser: chrome
2. URL of the problem: https://competitions.codalab.org/competitions/21475#participate-submit_results

**Comment by ckcollab** [comment]
Related to #2497

**Comment by antonia329** [comment]
> Related to #2497

Is the issue solved? I can not upload. Thank you!

**Comment by antonia329** [comment]
hi @ckcollab @Tthomas63 , I can not upload my result and I am very worried, pls help me! Thanks!

**Comment by Didayolo** [comment]
This issue seems to be redundant:

#2654 
#2512 
#2453 

Having a good and stable internet connection seems to help in those cases.
We need to find what causes the fails.

**Comment by YanHuiGUO** [comment]
> This issue seems to be redundant:
> 
> #2654
> #2512
> #2453
> 
> Having a good and stable internet connection seems to help in those cases.
> We need to find what causes the fails.

I also met this problem. I have a very good internet connection
![image](https://user-images.githubusercontent.com/13925414/64306525-aed1c200-cfc5-11e9-85ad-290c4c592667.png)

**Comment by Didayolo** [comment]
Merged.
