### ISSUE TITLE
[URGENT] Cannot create competition: "Could not find a suitable TLS CA certificate bundle"

### ISSUE THREAD

**Issue by mmmaat** [codalab/codalab-competitions#2496]
Hi, I'm trying to create a competition but I get this error when uploading my bundle:
```
Could not find a suitable TLS CA certificate bundle, invalid path: /app/certs/codalab-godaddy-bundle.crt
```

This may be related (or not), just before I deleted a former version of my competition but it is still visible in *Competitions I'm In* but points to a 404 error (https://competitions.codalab.org/competitions/21508).

Very strange I did the same operation several times and never had problems before today...

Any idea?
Thank you!

**Comment by kedharn** [comment]
I am also facing the same issues, I downloaded the dump from existing competition and tried to upload the bundle to create a clone competition and I am also getting the same error as above. Can you please look into it?

**Comment by mmmaat** [comment]
This issue is urgent for us as we announced the opening of out competition for today (Feb 4) : https://zerospeech.com/2019/index.html#timeline.

I tried several things : create a new user, publish the example [yellow_world_competition_bundle.zip](https://github.com/codalab/competition-examples/blob/master/basic-competition-bundles/Yellow_world/yellow_world_competition_bundle.zip), but I always end with the same error message about TLS CA certificate.

Any idea or suggestion? Thank you.

**Comment by ckcollab** [comment]
Looking into this right now, will hopefully have a solution soon. This is a rather unusual problem..

**Comment by ckcollab** [comment]
Please try now?

**Comment by ecoto** [comment]
Hi @ckcollab, are you sure this is closed ? I am having exactly the same problem right now with a new competition that I am trying to create.

I also have several non-existent competitions in "Competitions I'm in". They all point to 404.

**Comment by ckcollab** [comment]
@ecoto could you open up a new thread about that issue, with screenshots of your "Competition's 
 I'm In" potentially? Does it say 404 or something about a "TLS CA Certificate bundle?"

**Comment by ecoto** [comment]
@ckcollab you are right, there are two separate issues. I will create a new one about the 404 problem. However, the one that is really stopping me from creating the competition is exactly the same one described in the thread above. See the screenshot below.

![screenshot_2019-02-07 codalab - create competition](https://user-images.githubusercontent.com/4931748/52409038-373dc200-2acc-11e9-9b14-3faeaba38272.png)

**Comment by ckcollab** [comment]
You're right, the fix got reverted somehow -- apologies, fixing this now.. please try again?

**Comment by ecoto** [comment]
Ok, @ckcollab, it works again. Thanks !!!!
