### ISSUE TITLE
submission 

### ISSUE THREAD

**Issue by miloudi2439** [codalab/codalab-competitions#2507]
hello , when i submit our file , i can't see the result of submission , so what is wrong ! ?

 

1.  i am using Chrom and fire fox 
2.  https://competitions.codalab.org/my/competition/submission/541289/detailed_results/
     https://competitions.codalab.org/my/competition/submission/541291/detailed_results/

**Comment by Didayolo** [comment]
I close this issue because it is old and the competition does not exists anymore (or maybe I can't see it?).

Sorry for the late reply, feel free to re-open the issue if needed.
