### ISSUE TITLE
submission failed : Invalid file type (text/plain)

### ISSUE THREAD

**Issue by Hansoluo** [codalab/codalab-competitions#2520]
I joined in this Competition [WIDER Face & Pedestrain Challenge](https://competitions.codalab.org/competitions/19118#participate-submit_results), even thought Competition Ended. But it said you can also submit result. 

So, I tried to submit my result, it always failed and warning: Invalid file type (text/plain).

I checked my result file, it's OK. Even I submitted the official  submit file sample, It also failed and warning: Invalid file type (text/plain). 

Can anyone help ? Thanks!

**Comment by kovvalsky** [comment]
Usually you need to submit `.zip`that will contain a `.txt` file (without any internal directories)

**Comment by Hansoluo** [comment]
@kovvalsky Thanks. It works.
