### ISSUE TITLE
Send message to participants broken?

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2526]

**Comment by ckcollab** [comment]
Just tested and I was able to receive participant updates after fixing my profile email settings

**Comment by wetay** [comment]
Hi @ckcollab. I'm wondering if the functionality still works for a competition with more than 150 participants. I tried out this functionality again early this week for the competition https://competitions.codalab.org/my/competition/20865 (with over 200 participants) and none of my colleagues or I received the message, even though we had the profile settings for "Organizer direct message updates" checked. We did receive the message for a test competition we set up (with only ~8 people on it). Do you know what might be the issue?
