### ISSUE TITLE
Submitting Same Model but Got Different Score

### ISSUE THREAD

**Issue by 491506870** [codalab/codalab-competitions#2527]
@tthomas63 @eric2

hi, some days ago i submitted my result, which got about score 51, but today i submitted the same result with nothing changed, and the score is only about 40, i don't know why it happened, is there anything wrong with the score evaluation? thanks so much!

1. i am using Chrome
2. https://competitions.codalab.org/competitions/21258#participate

**Comment by Didayolo** [comment]
It could be something wrong with the scoring program. Or maybe the reference data or scoring metric got changed between the two submissions.

Unfortunately, this challenge doesn't exist anymore.
