### ISSUE TITLE
Can't reinstate team?

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2532]
Wendy is having this problem:

> We're running into this issue where we can't approve a team:
> I've tried clicking on the "Reinstate" button but nothing happens. Do you know what might be happening? This is for https://competitions.codalab.org/competitions/20865.

![image](https://user-images.githubusercontent.com/2185159/54224138-1e9f3e00-44b6-11e9-8c6e-5329fd3332ff.png)

**Comment by Tthomas63** [comment]
Hello,

The issue seems to be that the user soft-deleted the team themselves after being revoked. If you'd like we can permanently delete the team so it will no longer show.

Best regards,
Tyler

**Comment by Didayolo** [comment]
Merged.
