### ISSUE TITLE
Allow formatting in participant emails

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2537]
Currently "Send message to all participants" emails do not keep formatting -- whitespace isn't respected in HTML. 

For example, this message:

```
Hello students,

Lorem ipsum..
```

Becomes
```
Hello students,Lorem ipsum...
```

Wrapping the message section of the email with `<pre>` is an OK solution.

**Comment by wetay** [comment]
Could we also support formatting in terms of colours and fonts? This formatting is so that the message sent out can be made more visually appealing (and hence more palatable for participants to read).
