### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

### ISSUE THREAD

**Issue by echosum** [codalab/codalab-competitions#2538]
I currently submit my predict the result,but the test score is always 0. I look at the error log "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap." please help me.....I want to submit my result

**Comment by echosum** [comment]
oh the error occurs in the image super-resolution challenges of  NTIRE

**Comment by lr292358** [comment]
Duplicate issue
