### ISSUE TITLE
issue with "Cancellation of Submission"  

### ISSUE THREAD

**Issue by shangeth** [codalab/codalab-competitions#2542]
1. Cancelling of competition did not respond , it worked after multiple attempts to cancel the submission.
2. Even after the submission status changed to cancelled, the Compute Time is still counting.

Competition - http://autodl.lri.fr/competitions/75

**Comment by madclam** [comment]
This is for competition http://autodl.lri.fr/competitions/75

**Comment by ckcollab** [comment]
I believe this works @Tthomas63, should we close this?
