### ISSUE TITLE
issue when updating a competition

### ISSUE THREAD

**Issue by dweissen** [codalab/codalab-competitions#2546]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

Hi,

I am organizing the SMM4H competition https://competitions.codalab.org/competitions/22262 and I have the same issue described in https://github.com/codalab/codalab-competitions/issues/2308

I tried to update the reference data for one of my subtask. On submitting, I go back on the edit page with the changes apparently taken into account but when clicking on go back to competition the change is not applied (going back then to the edit page will give me the reference data before changes). Idem with changing dates or admin. If I understand the previous post correctly, there is an issue with one of the parameters in my competition preventing the system to compile the competition but which one?  

Thanks for your help.

**Comment by dweissen** [comment]
I found the reason: the length of the labels of the phases should be equal or less than 50 characters in the yaml file. Otherwise, although the competition is created normally and the labels are correctly displayed, one may not be able to edit it anymore as the competition will not recompile from the web interface.
D.

**Comment by Didayolo** [comment]
Thank you for coming back with the solution.

In my opinion: 
- The EDIT web interface should display it clearly when something prevent it to update the competition.
- This interface should allows what the YAML file allows.
