### ISSUE TITLE
BadZipfile error

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2552]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition
https://autodl.lri.fr/competitions/94

A trivial submission that should work got following BadZipfile error:
<img width="1161" alt="Screenshot 2019-04-04 at 14 29 29" src="https://user-images.githubusercontent.com/20074659/55556232-541afe00-56e7-11e9-98b0-145a5564ca0b.png">

**Comment by madclam** [comment]
We have not seen that one recently.

**Comment by rafariva** [comment]
Hi, could anyone fixed this bug?
