### ISSUE TITLE
[feature request] Working parent scoring even when some child tasks failed

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2553]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Done

2. Please post a link to your competition
https://autodl.lri.fr/my/competition/75/

We would like following feature for AutoDL/AutoCV challenge: even when some child tasks failed during a submission and others finished, the parent scoring program can still give a score for this submission, at least for some reasonable cases. So we'd like that parent scoring program is still executed.

And here we have a bad example where the parent scoring program is not even executed:
The status for parent scoring program is 'Running':
<img width="1089" alt="Screenshot 2019-04-04 at 14 51 33" src="https://user-images.githubusercontent.com/20074659/55558059-8b8ba980-56eb-11e9-88d2-e037721238ff.png">
But all 5 child task terminated (although all failed):
<img width="1125" alt="Screenshot 2019-04-04 at 15 01 02" src="https://user-images.githubusercontent.com/20074659/55558072-91818a80-56eb-11e9-83cc-7c677bf98f26.png">
<img width="1087" alt="Screenshot 2019-04-04 at 15 00 54" src="https://user-images.githubusercontent.com/20074659/55558073-91818a80-56eb-11e9-8700-b90d28121e11.png">
<img width="1105" alt="Screenshot 2019-04-04 at 15 00 47" src="https://user-images.githubusercontent.com/20074659/55558074-921a2100-56eb-11e9-8139-93803b865aab.png">
<img width="1094" alt="Screenshot 2019-04-04 at 14 52 14" src="https://user-images.githubusercontent.com/20074659/55558075-921a2100-56eb-11e9-9c12-5050b6b83eb7.png">
<img width="1088" alt="Screenshot 2019-04-04 at 14 51 45" src="https://user-images.githubusercontent.com/20074659/55558076-921a2100-56eb-11e9-94eb-9b649a85a29b.png">

**Comment by madclam** [comment]
This should have been addressed now. We'll keep monitoring if we see undesirable behavior.
