### ISSUE TITLE
GPU preparation for autodl

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2554]
This issue concerns server autodl.lri.fr.
We are conducting systematic [tests](https://docs.google.com/spreadsheets/d/16B0ZPSXRP8iTadt4wxlYhIXUsmhhuw9HpuhzjT3r-Ps/edit#gid=0) with Shangeth Rajaa.

When submitting baseline 1 (linear model), we are getting error 
``Traceback (most recent call last):
  File "/worker/worker.py", line 616, in run
    ingestion_process.kill()
  File "/usr/local/lib/python2.7/subprocess.py", line 1279, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/local/lib/python2.7/subprocess.py", line 1269, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process``

both with the default and the AutoDL-test queue, on dataset 1, using the docker shangeth/autodl.

Using docker evariste/autodl works fine for baseline 1.
Using docker shangeth/autodl works fine for baseline 0.

**Comment by zhengying-liu** [comment]
Repeated issue: https://github.com/codalab/codalab-competitions/issues/2577
