### ISSUE TITLE
Submissions stuck on submitted

### ISSUE THREAD

**Issue by nacstoklas** [codalab/codalab-competitions#2555]
I ran a dummy competition just to check if the scoring program is OK and it seems to work, the problem being the submissions are often stuck in submitted. The actual competition launch is very soon, so this is somewhat urgent. It is also not as if they are waiting in a queue, because it seems that every third submission or so runs normally. I've had this problem for a few days now and eventually the submissions do go through, it just takes hours if not days. Is this normal behaviour?

**Comment by ckcollab** [comment]
The queue for submissions is congested right now, can you spin up your own [compute workers and queue for this competition?](https://github.com/codalab/codalab-competitions/wiki#22-organizers-providing-custom-compute-workers)

**Comment by nacstoklas** [comment]
I can try but I don't think it will be done in time. Thanks for the quick reply.

**Comment by nacstoklas** [comment]
Also, I can't seem to find the option to add a queue (worker queue manager tab)

**Comment by MarcCote** [comment]
We also have the same problem (i.e. submissions stuck on either running or submitted) but we are running our own workers. Also, even though some of the submissions are stuck, they seem to actually be finished as we can see their final result on the leaderboard.

@ckcollab is there a way to refresh the status of every submission?

Our competition is https://competitions.codalab.org/my/competition/20865
