### ISSUE TITLE
Cannot upload submission: stuck saying select active parent phase

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2559]
This concerns: https://autodl.lri.fr/competitions/115

After trying to upload a submission in one of the dataset phases, I cannot make submissions anymore, even when going to the parent phase:

<img width="1013" alt="Screen Shot 2019-04-11 at 9 00 09 AM" src="https://user-images.githubusercontent.com/7594063/55937167-989f2000-5c38-11e9-985c-adc5cce548a3.png">

**Comment by zhengying-liu** [comment]
Same issue

**Comment by madclam** [comment]
Submissions for individual datasets has be re-activated. But there are still problems.
We need to make this work properly.
I propose:
- allow "per dataset" submission (for individual dataset)
- post a warning asking users whether this is really what they want to do

<img width="1021" alt="Screen Shot 2019-05-10 at 9 40 12 AM" src="https://user-images.githubusercontent.com/7594063/57543775-29d1e700-730a-11e9-8bbe-faf0dfebf9b7.png">

**Comment by madclam** [comment]
Problem solved: we should always uncheck "auto-migration", particularly when we have only one phase.
