### ISSUE TITLE
Weird layout for failed submission

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2564]
About competition https://autodl.lri.fr/competitions/115, got weird page layout for "Failed" submission:

<img width="1239" alt="Screenshot 2019-04-11 at 15 04 52" src="https://user-images.githubusercontent.com/20074659/55959509-37447480-5c6b-11e9-9b50-e70fe3bc862e.png">
<img width="1265" alt="Screenshot 2019-04-11 at 15 05 02" src="https://user-images.githubusercontent.com/20074659/55959514-39a6ce80-5c6b-11e9-80e7-6ab2ee97f0c5.png">

The submission 2479 failed and got an error message, but the message is not wrapped.

**Comment by Tthomas63** [comment]
This should be fixed now:

![screencapture-localhost-competitions-1-2019-04-12-16_19_53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594802f30ac590001a3ca1a3/125516c66e82c728ace21e0d46fb978826878daa8ef9ab56b658bd982645267f210bb03f3d86ec25af476f081b0611f202455e59fef98822bbb6386d8b5e16ecd7025e7da93812bea4905ffd5ee075d80b97bcae8f1e93ef3b76e08e8e1c374b531c89ff5534f59d4bca5df459fd5f17f54d623cbb2f7c29058614672d6c6d27aef9da57868464a0b8172950daae.png)
