### ISSUE TITLE
Auto-migration not disactivated

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2565]
This concerns https://autodl.lri.fr/competitions/115

Auto-migratrion in phase 2 disabled but jobs keep being forwarded to phase 2.

**Comment by Tthomas63** [comment]
Auto-migration was still enabled on children phases causing this issue I believe.

Auto-migration does not currently take into account the parent phase migration setting. I'm still verifying this is the cause of the issue.
