### ISSUE TITLE
Forum gone

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2566]
<img width="505" alt="Screen Shot 2019-04-11 at 7 27 17 PM" src="https://user-images.githubusercontent.com/7594063/55978278-f14dd780-5c8f-11e9-9483-1bb4f88e8829.png">

Forum button created in https://autodl.lri.fr/competitions/115 but not active.

**Comment by Tthomas63** [comment]
This should be fixed now. There was a syntax error in the HTML.
