### ISSUE TITLE
Create new pages does not work

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2567]
Competition 
https://autodl.lri.fr/competitions/115

New page button creates a new page with the editor, but then after submitting, the page does not actually get created.

**Comment by Tthomas63** [comment]
Something is currently broken in the in-line formsets for `Pages`. There's no clear error as to what's causing this so it will take some time to fix.

**Comment by madclam** [comment]
Closing for now, we found work arounds.
