### ISSUE TITLE
Learning curve not shown correctly 

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2569]
On competition: https://autodl.lri.fr/competitions/115

Some submissions (2500, 2502, 2503, 2504) are run successfully, but their learning curve is stuck at the **first prediction** (and still with auto-refresh, naturally). 

In the output of scoring step, we see that we indeed have had 18 predictions successfully made:
<img width="1308" alt="Screenshot 2019-04-11 at 22 30 09" src="https://user-images.githubusercontent.com/20074659/55991359-6201ed80-5caa-11e9-887a-e782a2ad090b.png">

But when we go to the learning curve page, the learning curve is stuck at the first prediction:
<img width="1409" alt="Screenshot 2019-04-11 at 22 30 32" src="https://user-images.githubusercontent.com/20074659/55991464-9ecde480-5caa-11e9-91b3-8f0311153263.png">

**Comment by ckcollab** [comment]
Could be workers restarting?

**Comment by zhengying-liu** [comment]
Yes. 

(Unrelated) It seems that after restarting workers, we never encountered the Docker error anymore but I got following error on Dataset 2:

<img width="1187" alt="Screenshot 2019-04-12 at 11 50 49" src="https://user-images.githubusercontent.com/20074659/56028888-76310380-5d19-11e9-8828-bbf392826cda.png">
