### ISSUE TITLE
Failed submission

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2572]
Competition: https://autodl.lri.fr/competitions/115
Baseline linear
**Two submissions failed**

Dataset 2:
Submission: 2687

Dataset 5:
Submission: 2690

Same error:

Traceback (most recent call last):
  File "/worker/worker.py", line 653, in run
    ingestion_process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process

The strange thing is that the learning curves were generated, but all the logs are empty.

![causase_linear](https://user-images.githubusercontent.com/7594063/56065229-904bff80-5d74-11e9-9f46-55af0c0bc7b7.png)
![hyppocrate_linear](https://user-images.githubusercontent.com/7594063/56065230-904bff80-5d74-11e9-9bdd-cc19fa76389f.png)
![saturn_linear](https://user-images.githubusercontent.com/7594063/56065232-904bff80-5d74-11e9-990e-79969cbd420a.png)
![beatriz_linear](https://user-images.githubusercontent.com/7594063/56065233-90e49600-5d74-11e9-97ce-604e58f78de7.png)
![ukulele_linear](https://user-images.githubusercontent.com/7594063/56065234-90e49600-5d74-11e9-8043-43a130d26c8f.png)

I ran it with the GPU queue AutoDL-test and docker  nehzux/autodl.
But it has consistently failed similarly on other runs, including in CPU queues.
It does not seem to be making use of GPUs. The learning curves are the same with CPU and GPU.

**Comment by Tthomas63** [comment]
That error happens when a submission hits the time-limit, is killed through one method, and then another back-up method to ensure that the submission is killed still fires, but cannot find the process ID.

We can look into catching the exception and making the output nicer, but I believe these submissions failed due to hitting the time-limit.

**Comment by madclam** [comment]
Zhengying should now be catching most exceptions. This particular error no longer occurs. We'll keep watching if we see abnormal behaviors.
