### ISSUE TITLE
Master scoring program fails

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2575]
This issue concerns: https://autodl.lri.fr/competitions/115

When one of the children tasks fail, the master program fails with:

```Traceback (most recent call last):
  File "/worker/worker.py", line 325, in run
    bundles = get_bundle(cache_dir, root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 184, in get_bundle
    metadata[k] = get_bundle(cache_dir, bundle_path, k, v)
  File "/worker/worker.py", line 184, in get_bundle
    metadata[k] = get_bundle(cache_dir, bundle_path, k, v)
  File "/worker/worker.py", line 143, in get_bundle
    with ZipFile(cached_bundle_file_path, 'r') as z:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file```

Examples of such failure are found in submissions:
2709, 2715, 2733, 2787, 2793

**Comment by zhengying-liu** [comment]
This error is also pointed out [here](https://github.com/codalab/codalab-competitions/issues/2552). The error is got when the worker is setting up , before the scoring program begins.

The parent scoring program (`evaluate.py`) was already updated and put into use for competition 115. This should fix following error:
```
Traceback (most recent call last):
  File "/tmp/codalab/tmpIE8PAC/run/program/evaluate.py", line 78, in 
    with open(submission_score_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpIE8PAC/run/input/res_3/scores.txt'
```
encountered in 2475, 2487 and 2499.

**Comment by Tthomas63** [comment]
This issue should be resolved now.

When a child submission failed, timed-out, or got cancelled, the resulting output zip would be corrupted (Due to cut connection on write).

The master/parent scoring programs only get the results of `finished` submissions now, not `failed` or `cancelled` submissions (It assumes a score of 0 on Codalab's side if passed N/A)

**Comment by Didayolo** [comment]
Now that the failed datasets aren't reported, it is ambiguous for the Parent Scoring Program to deduct which dataset failed.

We don't need to write the res folder for failed dataset but it would be useful that a line still got written in the **metadata** file.

For example:
res_6: failed.
