### ISSUE TITLE
Driver problem again

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2578]
This issue concerns
https://autodl.lri.fr/competitions/115

Submission 2823 was launched with a linear model that succeeded in the AutoDL queue (i.e. this is a re-launch of the successful submission made under number 2661, with evariste/autodl). We are now using a new docker called evariste/autodl:gpu.

DATASET 1:
Pavao | 2019-04-14 07:04 | c8100e9699e5 | evariste/autodl:gpu | AutoDL-Test | 2824 | **Failed**

DATASET 3:
Pavao | 2019-04-14 07:04 | 137dc03ef487 | evariste/autodl:gpu | AutoDL-Test | 2826 | **Finished**

The failed submission has error:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=6935 /var/lib/docker/overlay2/e4edfb93a6ba8d11d7cb734a94144e9d82162c24dad2e1dd383cfe74a8bd7392/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
```
Thus it seems that we have non identical workers in the queue.

**Comment by zhengying-liu** [comment]
Two instances seem to be different from the others:
<img width="328" alt="Screenshot 2019-04-14 at 10 38 51" src="https://user-images.githubusercontent.com/20074659/56090347-94297000-5ea1-11e9-9531-0bcb7f468f7f.png">

Maybe we should stop these two?

**Comment by madclam** [comment]
solved.
