### ISSUE TITLE
Learning curves of children processes not fully updated

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2579]
This concerns:

https://autodl.lri.fr/my/competition/115

Adrien made one successful submission with evariste/autodl:
https://autodl.lri.fr/my/competition/submission/2661/detailed_results/

For this SAME submission we get for dataset 3:
https://autodl.lri.fr/my/competition/submission/2664/detailed_results/
THE LEARNING CURVE IS NOT COMPLETE.
We do not get the full learning curve in the children jobs.

**Comment by zhengying-liu** [comment]
Repeated issue: https://github.com/codalab/codalab-competitions/issues/2569

However the fact that the submission 
https://autodl.lri.fr/my/competition/submission/2661/detailed_results/ 
succeeded is a bit surprising...

**Comment by zhengying-liu** [comment]
Closed for repetition.
