### ISSUE TITLE
Parent scoring program stuck in submitting mode

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2580]
The queue of https://autodl.lri.fr/competitions/115
has flushed but parent scoring programs of the master phase remain in Submitting even though all the children terminated.
Only baseline0 jobs terminate.

38	April 12, 2019, 11:43 a.m.	Pavao	2673	mysubmission.zip	Submitting	False	---						
39	April 12, 2019, 5:27 p.m.	guyon	2679	baseline0_all_zero (1).zip	Finished	False	2.0000						
40	April 12, 2019, 5:30 p.m.	guyon	2685	baseline1_linear (1).zip	Submitting	False	---						
41	April 12, 2019, 5:32 p.m.	Pavao	2691	baseline_zero.zip	Finished	True	2.0000						
42	April 12, 2019, 5:32 p.m.	guyon	2697	baseline0_all_zero (1).zip	Finished	True	2.0000						
43	April 12, 2019, 5:33 p.m.	guyon	2703	baseline2_scnn (2).zip	Submitting	False	---						
44	April 12, 2019, 5:35 p.m.	Pavao	2709	linear_model.zip	Failed	False	---						
45	April 12, 2019, 5:36 p.m.	Pavao	2715	baseline2_scnn.zip	Failed	False	---						
46	April 12, 2019, 5:36 p.m.	Pavao	2721	pytorch_zero.zip	Submitting	False	---						
47	April 12, 2019, 5:36 p.m.	Pavao	2727	pytorch_linear.zip	Submitting	False	---						
48	April 12, 2019, 5:37 p.m.	Pavao	2733	resnet.zip	Failed	False	---						
49	April 12, 2019, 7:49 p.m.	eric	2739	Pavao-6-input.zip	Submitting	False	---						
50	April 12, 2019, 7:49 p.m.	eric	2745	Pavao-6-input.zip	Failed	False	---						
51	April 12, 2019, 7:49 p.m.	eric	2751	Pavao-6-input.zip	Failed	False	---						
52	April 12, 2019, 11:24 p.m.	finlouarn	2757	ST-1st-submission.zip	Submitting	False	---						
53	April 13, 2019, 4:10 a.m.	finlouarn	2763	ST-1st-submission.zip	Submitting	False	---						
54	April 13, 2019, 4:11 a.m.	eric	2769	Pavao-6-input.zip	Submitting	False	---						
55	April 13, 2019, 11:08 a.m.	Beaker	2775	baseline0_all_zero.zip	Finished	True	2.0000						
56	April 13, 2019, 11:13 a.m.	Beaker	2781	baseline1_linear.zip	Submitting	False	---						
57	April 13, 2019, 11:47 a.m.	Beaker	2787	baseline2_scnn.zip	Failed	False	---						
58	April 13, 2019, 12:10 p.m.	Zhengying	2793	linear_log_device.zip	Failed	False	---						
59	April 13, 2019, 3:24 p.m.	Zhengying	2799	baseline2_scnn.zip	Submitting	False	---						
60	April 13, 2019, 5:45 p.m.	Zhengying	2805	linear_log_device.zip	Submitting	False	---						
61	April 13, 2019, 6:47 p.m.	Pavao	2811	linear_model.zip	Submitting	False	---						
62	April 13, 2019, 6:52 p.m.	Pavao	2817	linear_model.zip	Submitting	False	---						
63	April 14, 2019, 7:30 a.m.	Pavao	2823	Pavao-6-input.zip	Submitting	False	---

**Comment by madclam** [comment]
These are the latest jobs showing this symptom:


Participant | Submitted | Status | Run time
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Finished | 1:10:27.881928
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Finished | 1:53:58.287257
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Finished | 0:32:23.913156
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Failed | 7:47:36.495698
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Failed | 9:48:15.560120
AutoCV Challenge :: test under real conditions | Pavao | 9 hours, 48 minutes ago | Submitting | 5:30:48.369598


Those correspond to
**Master job: 2823**

63 | April 14, 2019, 7:30 a.m. | Pavao | 2823 | Pavao-6-input.zip | Submitting | False

**Children jobs:**

- 2824 : failed
Pavao | 2019-04-14 07:04 | c8100e9699e5 | evariste/autodl:gpu | AutoDL-Test | 2824 | Failed | Scoring
Pavao | 2019-04-14 07:04 | 99d512eba3c7 | evariste/autodl:gpu | AutoDL-Test | 2824 | Failed | Prediction
``` docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --require=cuda>=10.0 brand=tesla,driver>=384,driver<385 --pid=6935 /var/lib/docker/overlay2/e4edfb93a6ba8d11d7cb734a94144e9d82162c24dad2e1dd383cfe74a8bd7392/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
```

- 2825 : failed
Pavao | 2019-04-14 07:04 | 99d512eba3c7 | evariste/autodl:gpu | AutoDL-Test | 2825 | Failed | Scoring
Pavao | 2019-04-14 07:04 | 624ebc753fa3 | evariste/autodl:gpu | AutoDL-Test | 2825 | Failed | Prediction
```
Traceback (most recent call last):
  File "/worker/worker.py", line 653, in run
    ingestion_process.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
```

- 2826 : finished

Pavao | 2019-04-14 07:04 | 137dc03ef487 | evariste/autodl:gpu | AutoDL-Test | 2826 | Finished | Scoring
Pavao | 2019-04-14 07:04 | 8baccc5cf1b7 | evariste/autodl:gpu | AutoDL-Test | 2826 | Finished | Prediction

- 2827 : finished

Pavao | 2019-04-14 07:04 | 624ebc753fa3 | evariste/autodl:gpu | AutoDL-Test | 2827 | Finished | Scoring
Pavao | 2019-04-14 07:04 | 0fcfcdd03764 | evariste/autodl:gpu | AutoDL-Test | 2827 | Finished | Prediction

- 2828 : finished

Pavao | 2019-04-14 07:04 | 8baccc5cf1b7 | evariste/autodl:gpu | AutoDL-Test | 2828 | Finished | Scoring 
Pavao | 2019-04-14 07:04 | 80bf4ee3d2fc | evariste/autodl:gpu | AutoDL-Test | 2828 | Finished | Prediction

**Comment by zhengying-liu** [comment]
As the parent scoring program has not even been run (the status stuck at 'Submitting'), the problem comes from the logic of CodaLab. So we need @ckcollab or @Tthomas63 .

Possible bugging reasons:
1. Parent scoring program isn't assigned with any workers;
2. Or when certains child tasks failed, the conditions for triggering parent scoring program are not satisfied (maybe related to metadata? or scoring output?).

**Comment by madclam** [comment]
This behavior seem gone. Check again later.
