### ISSUE TITLE
Jobs marked running when they are not started yet

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2586]
We were running a single instance of GPU on 
https://autodl.lri.fr/competitions/118

Several jobs are started simultaneously:
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Running | 0:11:11.599988
-- | -- | -- | -- | --
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Running | 0:11:13.602448
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Running | 0:11:21.013420
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Running | 0:11:32.239170
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Running | 0:11:22.740883
AutoCV Challenge | Pavao | 2 hours, 51 minutes ago | Submitting

**Comment by Tthomas63** [comment]
A quick prediction step can cause it to look like this is the case, but it should be working fine. Please let us know if this issue persists

**Comment by ckcollab** [comment]
NOTE: If you turn on "result scoring only" it will remove an extraneous prediction step.
