### ISSUE TITLE
Ingestion and scoring processes running on same or separate workers?

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2588]
https://autodl.lri.fr/competitions/

As can be noticed "Prediction" and "Scoring" are sometimes run in the same worker and sometimes not. Zhengying says that both "ingestion program" and "scoring program" are run as part of the "Scoring" process. Is that true? If so, what is the "Prediction" process doing? It is just bloking a worker?

Submitted by | Date | Compute worker | Docker image | Queue name | Submission ID# | Status | Prediction/Scoring? | Running processes (in temp dir) | Ingestion program duration | Start RAM | End RAM | Start CPU | End CPU | Start swap | End swap
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Zhengying | 2019-04-16 08:04 | 690eaf57fe01 | evariste/autodl:gpu | AutoDL-Test | 3360 | Finished | Scoring | <DISABLED> | 2438.53 | 3.0% | 0.0% | 8.8% | 35.2% | 3.0% | 0.0%
Zhengying | 2019-04-16 08:04 | 690eaf57fe01 | evariste/autodl:gpu | AutoDL-Test | 3360 | Finished | Prediction | <DISABLED> |   | 3.1% | 0.0% | 8.5% | 9.8% | 3.1% | 0.0%
Zhengying | 2019-04-16 08:04 | 96de1896ff8b | evariste/autodl:gpu | AutoDL-Test | 3354 | Finished | Scoring | <DISABLED> | 3336.33 | 3.8% | 0.0% | 10.7% | 33.7% | 3.7% | 0.0%
Zhengying | 2019-04-16 08:04 | 690eaf57fe01 | evariste/autodl:gpu | AutoDL-Test | 3354 | Finished | Prediction | <DISABLED> |   | 3.1% | 0.0% | 6.3% | 9.5% | 3.1% | 0.0%
Zhengying | 2019-04-15 08:04 | 0fcfcdd03764 | evariste/autodl:gpu | AutoDL-Test | 3149 | Finished | Scoring | <DISABLED> | 1225.27 | 8.4% | 0.0% | 94.5% | 99.7% | 8.4% | 0.0%
Zhengying | 2019-04-15 08:04 | 80bf4ee3d2fc | evariste/autodl:gpu | AutoDL-Test | 3149 | Finished | Prediction | <DISABLED> |   | 8.3% | 0.0% | 29.0% | 59.1% | 8.4% | 0.0%

**Comment by madclam** [comment]
ingestion program is run during scoring.

What is prediction doing? Can we get rid of it? Should we check "is scoring only".

**Comment by NehzUx** [comment]
It seems that we check "is scoring only" now and there is no prediction program. It is exactly what we expect? Shall we close it now? @madclam

**Comment by madclam** [comment]
Clarified. We are running both on the same worker when we use the following options:

**PARENT PHASE**
Results Scoring Only => YES
Auto migration => NO
If submission beats old score, put submission on leaderboard => NO
Ingestion program only during scoring => NO
Is parallel parent => YES

**CHILDREN PHASES**
Results Scoring Only => YES
Auto migration => NO
If submission beats old score, put submission on leaderboard => NO
Ingestion program only during scoring => YES 
Is parallel parent => NO
