### ISSUE TITLE
Cancelled jobs are set to running by some workers for a long time

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2589]
In Challenge **118**, we observe that some jobs cancelled long time ago are rerun sometimes and the total time spent on these jobs are much more than this challenge limits, as seen from the figure attached, **3079** and **3085** last for 3 days.

Such jobs consumes thus much recourses of the workers and new submissions can hardly be processed.

<img width="1193" alt="challenge_118" src="https://user-images.githubusercontent.com/12370705/56370653-e6e58d80-61fb-11e9-986a-f34d3647210b.png">

**Comment by Tthomas63** [comment]
During testing it seems if a parent is cancelled while a child submission is updating it's status, it fails to terminate and or update it's status, or it is terminated but it's status isn't updated. 

We pushed some changes that should address some of these issues. Please let me know if this issue continues.

**Comment by NehzUx** [comment]
I think we should fix https://github.com/codalab/codalab-competitions/issues/2594 first. otherwise, it will be hard to track task IDs. Could you verify if you could reproduce the issue https://github.com/codalab/codalab-competitions/issues/2594? Thank you!
