### ISSUE TITLE
Prefix all error messages with name of the program

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2590]
In all programs that issue error messages, each message should be prefixed by the name of the program for debug purposes. For instance, in the line here,
https://github.com/codalab/competitions-v1-compute-worker/blob/master/worker.py#L623

the `stderr.write("Execution time limit exceeded!")` error is not prefixed and we shall not know where this message from stderr comes from. Instead, write `stderr.write("worker.py :: Execution time limit exceeded!")`

**Comment by madclam** [comment]
Hi all: Let's make this a general "best practice" so we facilitate debug for everybody in ALL parts of the code.

**Comment by madclam** [comment]
Zhengying did that in his code: make this also a "best practice" on Codalab side.
