### ISSUE TITLE
Inconsistence of queue name between health page and challenge submission metadata page

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2591]
This concerns autodl.lri.fr.

There is an inconsistence of queue name between health page and challenge submission metadata page.

For submission 3971, from challenge 116's submission metadata page, we see that it was assigned to queue "AutoDL-GPU-debug", which was **correct**

<img width="1422" alt="challenge" src="https://user-images.githubusercontent.com/12370705/56421258-f28b8f80-62a1-11e9-9ec9-6db60971e1d7.png">

And from the overall health page( autodl.lri.fr/health/simple_status), we see that it was assigned to a queue (GPU-Test-Zhen) newly created after that submission, which was **wrong**.
<img width="1116" alt="health" src="https://user-images.githubusercontent.com/12370705/56421305-1f3fa700-62a2-11e9-8dbc-6adf091d80de.png">

**Comment by Tthomas63** [comment]
The metadata page uses a field set on the submission for the queue name, while the health status was displaying the competition's queue.

The reason for the difference was the health page updated to show the new queue, while those jobs had already been sent out to the old queue.

They should now both display the same thing.
