### ISSUE TITLE
Duplicated submission on dataset 1

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2593]
In challenge 116 (https://autodl.lri.fr/competitions/116), we observe that once we upload a submission, **for dataset 2/3/4/5, it is fine. But for dataset 1**, we have duplicated submission, as shown in the figure, **task 3869, 3927, 3975, 3977, 3984, 4078, 4079** are believed to be the duplicates.
<img width="1140" alt="Screen Shot 2019-04-19 at 18 07 27" src="https://user-images.githubusercontent.com/12370705/56432541-1238ad00-62ce-11e9-8093-7e8afd7012f6.png">

**Comment by Tthomas63** [comment]
Would you be able to remove the empty master-phase (#7, Test Datasets) and see if the problem persists?
Auto-migration was also on for children phases which may have been causing some issues, but I disabled it.

I have not been able to reproduce this issue in my tests so far.

**Comment by NehzUx** [comment]
I didn't remove the test phase in challenge 116. i.e., I didn't change anything. But strangely enough, I haven't encountered this issue again. So I close it.
