### ISSUE TITLE
Task ID inconsistent

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2594]
In the private queue: GPU-Test-Zhen, from the submission page, the maximum task ID is 4203 but from the docker log, it is showing that  "[2019-04-22 12:21:23,912: INFO/Worker-1] Updating task=4204 status to running". i.e. there is no task 4204 from the dashboard of codalab. After searching a while, I think it is instead task 4178 who is running.

This happens always and I believe there might be in consistency in the system of task ID counting or so.

**Comment by Tthomas63** [comment]
Internally, Job IDs can be different from the ID of the submission object it is running, and I think that this is the case.

Logs for workers should use the Job ID, while the health pages, submission pages, etc show the submission's ID.

**Comment by NehzUx** [comment]
Hi, do you mean that from docker's log, info like "Updating task=4203 status to running", this task ID 4203 is Job ID and in the website dashboard,  e.g. https://autodl.lri.fr/competitions/118#participate, the ID column is submission ID for All datasets / dataset 1/2/3/4/5 ? And the Job ID is probably not consistent from the submission ID?

**Comment by Tthomas63** [comment]
Yes, the submission result table for participants shows the Submission ID, and the Task/Job ID is not the same thing. For example here's the Job you saw updating:

![image](https://user-images.githubusercontent.com/28552312/56518833-535ed600-64f5-11e9-920b-69035c54be33.png)

Checking it we can see it was tied to the submission you observed.

If you'd like we can add this information to the submission metadata page to better be able to track submissions, as I believe those are already listing jobs for submissions.

**Comment by NehzUx** [comment]
Thank you! Yes for sure. Metadata only contains submission ID now. Please add this information, otherwise it's hard for us to know which (submission) job is running from the docker log.

**Comment by Tthomas63** [comment]
![image](https://user-images.githubusercontent.com/28552312/56533555-bad45000-650c-11e9-911b-a7f13ceb535f.png)

No problem, the submission metadata page should now display the Job ID(s) for submissions.

**Comment by NehzUx** [comment]
Thanks a lot!! I close this issue.
