### ISSUE TITLE
cancel functionality doesn't seem to work

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2595]
In competition 118, each task is set to run for 2h. For the task 4174, dataset 1/2/3/5 are in status "submitted" and dataset 4 is running. 

But if I want to cancel it from all datasets tag, first, only the current running dataset 4 is cancelled and the rest datasets are still in status "submitted", also the parent "All datasets" is still in status "submitting". second, it seems that dataset 4 is not really terminated, because from the log of docker, it is still running and no new job is processed.

**Comment by Tthomas63** [comment]
This is due to limitations of cancelling tasks for Celery/RabbitMQ.

When the job is started/executed, we store the Task ID to be able to cancel it. If the job has has not yet been started/executed then we do not have the Task ID to cancel it yet. I believe we also now currently try to revoke it on RabbitMQ's side as well, but this issue would persist still.

As for a solution, we'd have to re-write some poritions of how the current tasks/jobs system works and probably use something like `django-celery-results` which has just recently been updated for use with the current version of celery we are using.

**Comment by NehzUx** [comment]
Thanks for the feedback. Does it mean that we shall not use "cancel" for any purpose now and have to wait for 10 hours (2 h on 5 datasets) to have the feedback of submission?

**Comment by ckcollab** [comment]
> Does it mean that we shall not use "cancel" for any purpose now and have to wait for 10 hours (2 h on 5 datasets) to have the feedback of submission?

Not from my understanding of what @Tthomas63 said..?

> *If the job has has not yet been started/executed then we do not have the Task ID to cancel it yet.*

If the job has been started it is relatively easy to cancel. It is more difficult to cancel a job that has not been started yet -- and a large part of why that is difficult is the legacy system itself.

**Comment by Tthomas63** [comment]
No you should still be able to use cancel. It means that if a submission has not been picked up (IE: It is in submitting/submitted or does not have a Task ID stored) it cannot be cancelled yet as we don't have the ID to kill it on Celery's side. 

No processing of the submission takes place until this happens, so no run/execution time should be lost.

**Comment by NehzUx** [comment]
@Tthomas63 said that once a job is running, it should be easy to be cancelled. However, in the example of task 4174 at the beginning, I saw that on dataset 4, it is in status "running" and others are in status "submitted". Once I cancel from the "All datasets" tag, though in dataset 4, it shows "cancelled" status, from the docker log, nothing shows and no new jobs are processed. (i.e. no other datasets turns from "submitted" to "running"). From the log, I saw 

[2019-04-22 12:21:23,912: INFO/Worker-1] Updating task=4204 status to running
.......
[2019-04-22 14:21:39,434: ERROR/Worker-1] Run task timed out (task_id=4204).

which was exactly 2h.

task_id=4204 is the job on dataset 4.

**Comment by ckcollab** [comment]
To make things a bit clearer: a submission marked "Running" it may be between the Prediction and Scoring steps, meaning no task is currently running. To make the task cancel for any subsequent steps is a bit more difficult than cancelling an _actually_ running task; we may need to install `django-celery-results` or some similar module to help with persistence of this cancelling.

**Comment by madclam** [comment]
Closing for now, we'll revisit if needed.
