### ISSUE TITLE
Finished on all datasets but failed on parent

### ISSUE THREAD

**Issue by NehzUx** [codalab/codalab-competitions#2596]
In challenge 116, some submissions failed of no reason / no error log. 

Note that this doesn't always happen.

For example, task 4138, task 4168. They are finished on all datasets but failed on parent All datasets. Their results could be downloaded and the scores and learning curves are normal. 

<img width="1131" alt="Screen Shot 2019-04-22 at 14 43 51" src="https://user-images.githubusercontent.com/12370705/56500931-19013300-650d-11e9-8253-0092605cd4cd.png">

Here is the result downloaded from task 4168 parent.

scores.txt
<img width="243" alt="Screen Shot 2019-04-22 at 14 45 41" src="https://user-images.githubusercontent.com/12370705/56500990-55cd2a00-650d-11e9-9e85-0ac0052cbafe.png">

detailed_results.html
![screencapture-file-Users-zhen-Downloads-Zhen-50-output-detailed-results-html-2019-04-22-14_46_32](https://user-images.githubusercontent.com/12370705/56501025-7eedba80-650d-11e9-9889-a2e97b883500.png)

**Comment by NehzUx** [comment]
Thanks to the Job ID new feature on submission metadata dashboard, there are some new observations. For the mentioned task 4138, task 4168, it can be seen that they both correspond to multiple parent jobs instead of one. 

<img width="1426" alt="Screen Shot 2019-04-23 at 10 24 31" src="https://user-images.githubusercontent.com/12370705/56566012-0260e780-65b2-11e9-9e51-eaee0c31d5fc.png">

Note that these two task, task 4138, task 4168, are normal submissions without bug program, without cancel. Their parents just end up with this status, although each dataset is finished with a valid score.

Btw, from the picture below, for the cancelled parent, some has a list of many Job IDs. Is this showing that the job is not really cancelled and is reassigned another Job ID many times.

<img width="1420" alt="Screen Shot 2019-04-23 at 10 26 51" src="https://user-images.githubusercontent.com/12370705/56566194-5e2b7080-65b2-11e9-8d95-2b6ee4b2501c.png">

**Comment by zhengying-liu** [comment]
At the moment of 5 May 2019, this problem still persists: everything works fine (ingestion + scoring for 5 datasets, parent scoring), got 'Finished' for all 5 datasets. Everything in Download Output is perfectly normal, but got 'Failed' on parent scoring.

The submission that got 'Failed':
<img width="1149" alt="Screenshot 2019-05-05 at 19 16 12" src="https://user-images.githubusercontent.com/20074659/57197721-081fdb00-6f6b-11e9-8846-c023024a8430.png">

But everything was working normally in ingestion + scoring + parent scoring:
<img width="1543" alt="Screenshot 2019-05-05 at 19 16 35" src="https://user-images.githubusercontent.com/20074659/57197747-52a15780-6f6b-11e9-8b1e-0b7d5b7b313a.png">

**Comment by Tthomas63** [comment]
This issue seems to have been from a race condition, where a task checking for parent submissions that have not started, starts the offending submission even after it has already been picked up, causing the submission to fail.

I added a delay, and checks to both functions that should prevent this. I have not yet encountered this error in testing, so please let me know if this issue is still persisting.

**Comment by madclam** [comment]
We seem to still have such race problems. In the example below, the parent program 5549 finished before the child 5550. Furthermore, the other children programs for other datasets were never started.

<img width="983" alt="Screen Shot 2019-05-09 at 10 39 08 PM" src="https://user-images.githubusercontent.com/7594063/57547966-a8338680-7314-11e9-97ad-6d9bd375602c.png">

**Comment by madclam** [comment]
This seems fixed, thanks!
