### ISSUE TITLE
Results not showing

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2597]
This concerns competition:
https://codalab.lri.fr/competitions/398

The user "Electricity" does not have its results showing on the leaderboard:
https://codalab.lri.fr/competitions/398#results

**Comment by Didayolo** [comment]
The user Electricity does not appear in the "Final phase" leaderboard but it has only a **failed** submission in this phase.
It appears only in the "Development phase" leaderboard where it has successful submissions.
Everything seems fine.
