### ISSUE TITLE
Learning curve page not long enough

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2600]
This concerns the competition: https://autodl.lri.fr/competitions/118
Submission number: 4729

When one clicks on the button Learning Curve for parent scoring, the page is not long enough to show the whole page:
<img width="1042" alt="Screenshot 2019-04-27 at 21 21 14" src="https://user-images.githubusercontent.com/20074659/56854169-a9d37680-6932-11e9-8047-4ac2e3e9ce9c.png">

**Comment by madclam** [comment]
Would be good to fix but lower priority for now.

**Comment by lr292358** [comment]
I checked and all is fine

**Comment by zhengying-liu** [comment]
Still has this problem

<img width="1543" alt="Screenshot 2019-05-22 at 12 06 28" src="https://user-images.githubusercontent.com/20074659/58166418-115ab880-7c8a-11e9-9d8f-9c9290acc41c.png">

**Comment by lr292358** [comment]
It's Chrome? I checked Firefox.

**Comment by lr292358** [comment]
Still not long enough. 
Tyler please increase the height by 40%, and the minimum in pixels by 40%.
Confirm when this is done so as e can later close it finally.

**Comment by Didayolo** [comment]
I checked for Chrome and Firefox on several competitions and I think this issue is solved.
