### ISSUE TITLE
Learning curve page not shown when clicking on 'Learning Curve'

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2603]
This concerns the competition https://autodl.lri.fr/competitions/118

For some submission, the learning curve page is not shown in parent phase:

The submission 5051 terminated normally:
<img width="1145" alt="Screenshot 2019-05-05 at 20 16 18" src="https://user-images.githubusercontent.com/20074659/57198444-402b1c00-6f73-11e9-896d-067194cedb76.png">

But the learning curve page is empty:
<img width="1543" alt="Screenshot 2019-05-05 at 20 16 24" src="https://user-images.githubusercontent.com/20074659/57198454-576a0980-6f73-11e9-995b-1238fe08699a.png">

And when checking Download Output, there is a learning curve page well generated:
<img width="1543" alt="Screenshot 2019-05-05 at 20 19 48" src="https://user-images.githubusercontent.com/20074659/57198472-6fda2400-6f73-11e9-916b-d69bc834ffbf.png">

**Comment by Tthomas63** [comment]
Would you be able to take a look at the code for detailed results on the parent scoring program? There seems to be some differences in the scoring program of how parents are handled for detailed results, versus children.

I took a look at this and I'm not sure what could be preventing parents from pushing detailed results on Codalab's side, specifically if children are still able to push detailed results then parents should be able to as well as it uses the same logic.

**Comment by Tthomas63** [comment]
I've pushed an updated worker image/tag (`codalab/competitions-v1-nvidia-worker:parent-lc`) that should resolve this issue.

`autocv-worker-10` is currently on the queue `Test-GPU` for debugging if you'd like to test that this resolves the issue for you.

**Comment by madclam** [comment]
Looks OK so far.
