### ISSUE TITLE
How to find others' worksheet or code?

### ISSUE THREAD

**Issue by Feiyu-Zhang** [codalab/codalab-competitions#2604]
I'm using chrome browser. But I can't find others' code. Can you tell how to do? Thanks.

**Comment by madclam** [comment]
Is this a worksheet question? Then post in https://github.com/codalab/codalab-worksheets/issues

**Comment by Feiyu-Zhang** [comment]
> Is this a worksheet question? Then post in https://github.com/codalab/codalab-worksheets/issues

Not only worksheet. I also want to read others' code.

**Comment by Feiyu-Zhang** [comment]
> Is this a worksheet question? Then post in https://github.com/codalab/codalab-worksheets/issues

![image](https://user-images.githubusercontent.com/34130100/58457684-df4dc880-8159-11e9-9b9e-a882f2dc97bd.png)
He said it is a competition question. Please, can you help me? Thanks.

**Comment by ckcollab** [comment]
Can you please be more specific with what you need? Please contact the competition organizers for questions specific to a competition.

**Comment by Feiyu-Zhang** [comment]
> Can you please be more specific with what you need? Please contact the competition organizers for questions specific to a competition. We don't generally provide code for submissions, but please check to see with the organizer if there is public code.

That's all right. Thanks anyway.
