### ISSUE TITLE
After I delete a competition in "Competitions I'm Running", I can still see it in "Competitions I'm In".

### ISSUE THREAD

**Issue by hqqasw** [codalab/codalab-competitions#2606]
*** After I delete a competition in "Competitions I'm Running", I can still see it in "Competitions I'm In". ***

I am an organizer and I found that 
after I delete a competition in "Competitions I'm Running", I can still see it in "Competitions I'm In".
And when I click that competition in "Competitions I'm In", it would show a bug-reporte page.
------------------------------------------------------------------

**Comment by Didayolo** [comment]
Solved in develop branch.
