### ISSUE TITLE
Erratic compute time

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2608]
In https://autodl.lri.fr/

The "compute time" is erratic in the main leaderboard. Some values shown are up to several days. It should not exceed the sum of compute times of the children phases. The compute time of the scoring program of the parent phase is largely immaterial (short).

In the children phases, we have large differences between duration and compute time.

Finally, in the main leaderboard, some compute times show : Submission failed. What does this account for?

<img width="923" alt="Screen Shot 2019-05-10 at 9 13 14 AM" src="https://user-images.githubusercontent.com/7594063/57541653-5be04a80-7304-11e9-8c97-5505de21e489.png">
<img width="918" alt="Screen Shot 2019-05-10 at 9 12 58 AM" src="https://user-images.githubusercontent.com/7594063/57541654-5c78e100-7304-11e9-85fd-3cfbfa767020.png">

**Comment by madclam** [comment]
I will keep monitoring that. Closing for now.

**Comment by madclam** [comment]
Reopening because we are having a new issue: The time elapsed in the parent phase, which is used to compute whether we are going over time compared to the max time, seems to be computed since the job was submitted, not since it was running. This cause the problem that Jim reported on the forum.

<img width="412" alt="Screen Shot 2019-05-10 at 12 22 25 PM" src="https://user-images.githubusercontent.com/7594063/57565444-db0c6780-7372-11e9-9b76-f2234fcc3f92.png">

**Comment by madclam** [comment]
We see also in this example that the last submission took 34 minutes of execution time (bottom), but what is used to compute the time used is 1:29 (top)

<img width="949" alt="Screen Shot 2019-05-10 at 11 09 15 PM" src="https://user-images.githubusercontent.com/7594063/57565805-cb901d00-7378-11e9-9d74-eb42bead6a8e.png">

**Comment by madclam** [comment]
Part of the problem may be when we restart the servers. Codalab never sees the jobs terminating and the time keeps running.

**Comment by Tthomas63** [comment]
Parent submission compute time should currently be a sum of the total run-times of it's children. We do not calculate it's time based on the same data because as noticed, it is in the submitting status for much longer.

Also I believe that screenshot shows the last two submissions being counted towards the total with run times of 54 seconds, and 34 seconds, for a total of 1 minute and 29 seconds.

**Comment by madclam** [comment]
Lukasz made a single submission today and is already out of time.
I explain it as follows:
- when model.py goes out-of-time in one dataset, the ingestion program gets killed (and possibly the scoring program? verify) but then the counter used for Execution Time Used: does not stop.
You corrected that problem for Total Compute Time
but not for Execution Time Used

**Comment by madclam** [comment]
There are more problems reported by Lukasz
- I actually could not submit (again, error: The maximum amount of compute time for submissions has been reached.)
- model6.zip (submission 5942) changed the time used from 2:47 (your screenshot) to 6:55 now
- Dataset 1, 5943, says it used 4:20 for a single submission now! 

[lukasz_may15.xlsx](https://github.com/codalab/codalab-competitions/files/3184876/lukasz_may15.xlsx)

**Comment by madclam** [comment]
I believe this happens when workers die before they finish a job. Codalab never hears from the anymore and the submission stopwatch keeps running. Now that we have 5 workers all the time, hopefully this will not happen again. We are putting on hold the implementation of elastic cloud.
