### ISSUE TITLE
Submission failure

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2610]
https://autodl.lri.fr/competitions/118#participate

Participant Zhengying
dataset 2
submission 5787
pretrained_inception.zip

```
Traceback (most recent call last):
  File "/worker/worker.py", line 731, in run
    put_blob(stderr_url, stderr_file)
  File "/worker/worker.py", line 222, in put_blob
    'x-ms-version': '2018-03-28',
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /codalab-gcs-private/submission_stderr/728321de-009c-42df-801c-193407b95d77/stderr.txt?Expires=1557682070&GoogleAccessId=1037344820372-compute%40developer.gserviceaccount.com&Signature=GUfHGvSSaJZsncOeHC8HSRFU6FstwCAISIGOZGbtDrJl9%2FpvXznNd1knYLZhVEetPtiQOHUm42L3CoAFYDfsKzysolEQ3BqtVk6Pj6TCSOE7h45IssmUhKlNG36EAMkSPuVDAYZFdiw%2FAsY6x5t1hI6QzIkrD%2BEWKYTgXnOsTGoy1vaPwmzw6XGoSIjvqc%2FxNYdiMw%2BmkYSrm6BPbs01HyeTXrZ4ibK1BV0QGrMjJOGAqiQROjUA8OJciU6gXKLgGwZSLqED3TPA2BM%2F9CRanTs%2B5L7BK83FjWL8Yai8Ka1%2FaI%2FzRD7HLK8%2BqYzPcQ9QLA%2FWJg2HQMTjyWzFKQXs0w%3D%3D (Caused by : [Errno 99] Cannot assign requested address)
```
However on 5817 the same submission finished.

**Comment by madclam** [comment]
Also something wrong with dataset 4
See submissions
5789
and
5819
--



```
2019-05-11 20:22:05,581 INFO score.py: Detected the start of ingestion after 1 seconds. Start scoring.
2019-05-11 20:22:15,528 INFO score.py: Detected ingestion program had stopped running because an 'end.txt' file is written by ingestion. Stop scoring now.
2019-05-11 20:22:16,786 INFO score.py: Final area under learning curve for Saturn: 0.0000
2019-05-11 20:22:16,788 ERROR score.py: [-] Some error occurred in ingestion program. Please see output/error log of Ingestion Step.
2019-05-11 20:22:16,788 INFO score.py: [Scoring terminated]
```

**Comment by zhengying-liu** [comment]
> https://autodl.lri.fr/competitions/118#participate
> 
> Participant Zhengying
> dataset 2
> submission 5787
> pretrained_inception.zip
> 
> ```
> Traceback (most recent call last):
>   File "/worker/worker.py", line 731, in run
>     put_blob(stderr_url, stderr_file)
>   File "/worker/worker.py", line 222, in put_blob
>     'x-ms-version': '2018-03-28',
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 99, in put
>     return request('put', url, data=data, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 327, in send
>     raise ConnectionError(e)
> ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /codalab-gcs-private/submission_stderr/728321de-009c-42df-801c-193407b95d77/stderr.txt?Expires=1557682070&GoogleAccessId=1037344820372-compute%40developer.gserviceaccount.com&Signature=GUfHGvSSaJZsncOeHC8HSRFU6FstwCAISIGOZGbtDrJl9%2FpvXznNd1knYLZhVEetPtiQOHUm42L3CoAFYDfsKzysolEQ3BqtVk6Pj6TCSOE7h45IssmUhKlNG36EAMkSPuVDAYZFdiw%2FAsY6x5t1hI6QzIkrD%2BEWKYTgXnOsTGoy1vaPwmzw6XGoSIjvqc%2FxNYdiMw%2BmkYSrm6BPbs01HyeTXrZ4ibK1BV0QGrMjJOGAqiQROjUA8OJciU6gXKLgGwZSLqED3TPA2BM%2F9CRanTs%2B5L7BK83FjWL8Yai8Ka1%2FaI%2FzRD7HLK8%2BqYzPcQ9QLA%2FWJg2HQMTjyWzFKQXs0w%3D%3D (Caused by : [Errno 99] Cannot assign requested address)
> ```
> 
> However on 5817 the same submission finished.

This should be some connection error of the worker. Assigned @ckcollab to investigate.

**Comment by zhengying-liu** [comment]
> ## Also something wrong with dataset 4
> See submissions
> 5789
> and
> 5819
> ```
> 2019-05-11 20:22:05,581 INFO score.py: Detected the start of ingestion after 1 seconds. Start scoring.
> 2019-05-11 20:22:15,528 INFO score.py: Detected ingestion program had stopped running because an 'end.txt' file is written by ingestion. Stop scoring now.
> 2019-05-11 20:22:16,786 INFO score.py: Final area under learning curve for Saturn: 0.0000
> 2019-05-11 20:22:16,788 ERROR score.py: [-] Some error occurred in ingestion program. Please see output/error log of Ingestion Step.
> 2019-05-11 20:22:16,788 INFO score.py: [Scoring terminated]
> ```

This is due an error in the baseline method (pretrained inception). The submission an old version of the code and doesn't deal with variable number of channels. So it's not an error of the competition bundle (ingestion or scoring).
