### ISSUE TITLE
[Urgent] Renaming of leaderboard keys is not updated on the leaderboards

### ISSUE THREAD

**Issue by siabar** [codalab/codalab-competitions#2613]
Hi,

In my leaderboard of my yaml, the order of the parameters are:

        Subtask1_Precision:
            leaderboard: *RESULTS1
            label: Precision
            rank: 2
            numeric_format: 5
        Subtask1_Recall:
            leaderboard: *RESULTS1
            label: Recall
            rank: 3
            numeric_format: 5
        Subtask1_F1:
            leaderboard: *RESULTS1
            label: F1
            rank: 1
            numeric_format: 5

The first rank is Subtask1_F1 parameter. But in the competition results, Three tops participates are ranked based on the Subtask1_Precision. I think the reason is I wrote it first in the yaml file.

When I change the order in the competition editor. It does not update. 
I could not delete the competition and upload it again.

What is the solution?!

@ckcollab @madclam
With Best Wishes,
Siamak

**Comment by siabar** [comment]
@tthomas63 Now one can answer my question?

**Comment by siabar** [comment]
Dears,

I want to show the best result of participates on the leaderboard based on a specific metric?

I could not do it manually for all users. How can I solve it automatically?

**Comment by siabar** [comment]
As you see based on my YAML file, top 3 results (green ones) are based on Precision but I want the result base don F1 (Rank 1). As you can see there are big gaps between them. How can Solve it?

![IMG_2254](https://user-images.githubusercontent.com/20933986/57919901-14286880-789a-11e9-96f5-28a738074f73.JPG)

**Comment by siabar** [comment]
Your codalab has very **big bug**

It is a result of a participate based on CSV file (downloaded from Submission page):


User   | F1               | Precision      | Recall

XXX   | 0.98128 (3) | 0.96886 (4)  | 0.97503 (1)

--------------
But It is results of that participate based on score.txt (output of programming score)

Subtask1__Precision : 0.9818562456385206

Subtask1_Recall : 0.9641939352407058

Subtask1_F1 : 0.9729449390612845

Also, my YAML file as I explained before, it is:

'''
    Subtask1_Precision:
        leaderboard: *RESULTS1
        label: Precision
        rank: 2
        numeric_format: 5
    Subtask1_Recall:
        leaderboard: *RESULTS1
        label: Recall
        rank: 3
        numeric_format: 5
    Subtask1_F1:
        leaderboard: *RESULTS1
        label: F1
        rank: 1
        numeric_format: 5
'''

**Comment by Didayolo** [comment]
Hi,

Indeed, it seems that the leaderboard cannot be edited efficiently with the web interface.

Unfortunately, the best way to handle this is to edit the YAML file and to re-upload the challenge.

We need to address this issue in future updates.

Issue merged.
