### ISSUE TITLE
Wrong score of area under the learning curve

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab-competitions#2618]
For submission #5916 the score is 0.89 but should be around 0.81 based on the plot and in general the baseline's performance. I will look into it.

**Comment by lr292358** [comment]
The bug is that the method still uses a trapezoidal method, 
because actually it uses trapezoidal function for step, and step for trapezoidal,
lines 352 and 356 should be swapped.

**Comment by zhengying-liu** [comment]
Fixed. Thanks for being so careful. :)

For similar bugs in ingestion or scoring program, please report issues in the repo:
https://github.com/zhengying-liu/autodl_starting_kit_stable
