### ISSUE TITLE
Warn user or disallow setting first phase to Auto Migration

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2620]
It could be confusing to new users if we allow enabling auto migration on first phase, which makes no sense, because auto migration takes submissions from previous phase leaderboard and moves them into current phase.

**Comment by Didayolo** [comment]
The warning could be a text added next to the option if its the first phase.

![automigrationissue](https://user-images.githubusercontent.com/11784999/64897110-89f2e400-d682-11e9-91e6-1ea1af655a68.png)
