### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2621]
This concerns the competition: https://autodl.lri.fr/competitions/118

When clicking on 'Upload a Submission' with large zip files, one gets error very frequently.

Test results (MacOS 10.14, Chrome 74):
Success: 27MB, 54MB, **107MB**
Failure: **107MB**, 133MB, 213MB, 472MB, 943MB
For 107MB, sometimes it worked but sometimes it didn't -> unstable behavior

Screenshots when uploading a 133MB submission:
The uploading process went to 43% complete:
<img width="439" alt="Screenshot 2019-06-06 at 11 37 11" src="https://user-images.githubusercontent.com/20074659/59023420-11dd7c80-8850-11e9-93ed-765e858b7776.png">
Then error happened:
<img width="461" alt="Screenshot 2019-06-06 at 11 37 19" src="https://user-images.githubusercontent.com/20074659/59023468-2a4d9700-8850-11e9-8b94-dc79a18184af.png">
The reason of the error is not clearly indicated in the error message.

This should be fixed as the competition rule says participants can upload submissions up to **300MB**. Following feature is also considered to be added:
Add a pre-upload step for 'Upload a Submission' button, where it fetches the size of the uploaded zip file and check whether it's less 300MB. If the submission exceeds 300MB, it will send an error "Maximum size exceeded! A submission should be less than 300MB in this challenge." and stop the uploading immediately.

**Comment by Didayolo** [comment]
Merged.
