### ISSUE TITLE
[AutoDL] Uploading size limit: 2GB

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2625]
We can't upload datasets bigger than 2GB. When trying, it still waits for ~30-60 minutes after reaching 100% and then the upload stops the webpage prints the following message:

> The CodaLab site is currently unavailable.
> Sorry, the page you are looking for is currently unavailable.
> Please try again later.

It is on the AutoDL LRI instance. The issue is the same with Firefox and Chrome.

I talked with Tyler and he wasn't aware of a voluntary limitation.

**Comment by Didayolo** [comment]
This may be due to a timeout that occurs for big files.

Indeed, I've just had the issue with a smaller dataset (1.5GB) but with a slower internet connection.

**Comment by ckcollab** [comment]
@Didayolo can you confirm this is fixed now? IIRC this was fixed in December

**Comment by Didayolo** [comment]
I need to check it out.

**Comment by Didayolo** [comment]
I just tried with a 3GB dataset, on [autodl.lri.fr](autodl.lri.fr) and it **didn't work**.

**Comment by Didayolo** [comment]
Merged.
