### ISSUE TITLE
AutoDL Auto-Migration Competition Demo

### ISSUE THREAD

**Issue by Tthomas63** [codalab/codalab-competitions#2626]
#### Testing Auto-Migration
1) First upload a new competition using this bundle:
(Will re-include link after talking to Isabelle)

2) Using the editor change the Queue to use a test queue.

3) Using the editor change the second parent phase's start date, and it's children phases' start_dates, to be ~30 minutes in the future. (Phasenumbers 7-12) (You can see the server time on the detail page. EG: If it shows 9:00pm UTC, set the start date to the same date, and 21:30:00 for time.

4) Upload a submission to the first parent phase, and let it finish. (Baseline should work)

By the time the second phase starts, the submission should be migrated onto the second parent phase.

Here is an example competition where I have performed these steps:
https://autodl.lri.fr/competitions/140#participate

**Comment by madclam** [comment]
As per instructions I created competition http://autodl.lri.fr/competitions/141 to test.
I changed the queue and date as per instructions.

I submitted baseline 0. It ran fine except on dataset 5.
I migrated by hand: it said "migrated" but did not migrate anything.

I submitted 2 more baseline 0 and waited for migration.
Neither submissions terminated before the phase change and they never finished nor got migrated.

The desired behaviors are:
1) It should be possible to migrate submissions by hand (very important)
2) When there is a phase change, all submissions made before the deadline should finish being processed; then only should we start migration

**Comment by madclam** [comment]
One submission that did not finish and should take only a few seconds has been stuck in the running mode for 35 min

11536 | AutoCV Challenge :: beta tests | guyon | baseline0_all_zero.zip | 35 minutes ago | Running | GPU-temp | 7696b8c12889 | 0:35:27.078557
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by madclam** [comment]
The I changed the date in the future again.
I tried to make a submission and it said I exhausted my number of submissions. I launched a parent submission though. Then someting migrated (though we were in the feed-back phase).

**Comment by Didayolo** [comment]
Do we still want to implement auto-migration?

**Comment by RaghuSpaceRajan** [comment]
Sorry if I missed something but were the following desiderata by @madclam added to CodaLab?

> The desired behaviors are:
>
> 1. It should be possible to migrate submissions by hand (very important)
> 2. When there is a phase change, all submissions made before the deadline should finish being processed; then only should we start migration

I feel like they were not (see below) and I also cannot find any open issue for them.

We're hosting the competition: [https://codalab.lisn.upsaclay.fr/my/competition/3727/]() and when I intially turned on auto-migrate for phase 2, it did not wait for phase 2 to begin but started migrating immediately and this was causing the error "Failed, competition phase is being migrated, please try again in a few minutes" for participants trying to submit. So, I turned off auto-migrate and waited for phase 2 to start and then turned on auto-migrate again but this did not lead to any auto-migration nor can I find a way to migrate (all) submissions on the phase 1 leaderboard manually to phase 2.

As a workaround, I decided to hide the phase 1 leaderboard and to change the datasets and ingestion for phase 1 to use the phase 2 datasets and ingestion and re-run submissions manually. Is there a better way to achieve this, i.e. the 2 desiderata mentioned by @madclam above?
