### ISSUE TITLE
How to approve all participants for the competition

### ISSUE THREAD

**Issue by YeDeming** [codalab/codalab-competitions#2628]
Hi, 

I am running a competition [DocRED](https://competitions.codalab.org/competitions/23392).

When people want to  take part in the the competition, I need to approve their application in the participant page.  Could you teach me how can I make all the application approved automatically? In other word, how can I cancel the application processing. Everyone can directly take part in the competition without approval.

Best Wishes,
Deming Ye

**Comment by ymcui** [comment]
`Admin features` -> `edit` -> untick the checkbox `Organizers need to approve the new teams`

**Comment by YeDeming** [comment]
It works, thank you!
