### ISSUE TITLE
Weird 'Submission Failed' of parent phase

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2629]
This concerns following competitions: 
https://autodl.lri.fr/competitions/118
https://autodl.lri.fr/competitions/136

**Issue description**:
For certain submissions, all the 5 child phase tasks for 5 datasets AND the parent phase terminated successfully (with a score and a learning curve page), but the parent phase 'All datasets' is marked as 'Submission Failed'. And these submissions even appear on the leaderboard of https://autodl.lri.fr/competitions/118...
<img width="1202" alt="Screenshot 2019-06-24 at 15 45 51" src="https://user-images.githubusercontent.com/20074659/60024311-db995d00-9697-11e9-8e50-c85fa811d702.png">

This issue happens even more often on the competition https://autodl.lri.fr/competitions/136:
<img width="1164" alt="Screenshot 2019-06-24 at 15 42 23" src="https://user-images.githubusercontent.com/20074659/60024378-f966c200-9697-11e9-8215-73ddafde966d.png">

Maybe this is only be a problem of display? Please investigate.

**Comment by madclam** [comment]
This problem keeps recurring. We really need it fixed because this prevents us from getting the results from perfectly fine submissions and it a big waste of computer resources.
Also it is very unfair to the participants.
1) In https://autodl.lri.fr/my/competition/118/submissions/
this happened to submissions 955, 956, 961.
2) In https://autodl.lri.fr/my/competition/136/submissions/
this happened to MANY submissions made on June 29
3) In https://autodl.lri.fr/my/competition/146/submissions/
this happened to one submission so far.

**Comment by Didayolo** [comment]
Is this issue still happening?

**Comment by YanHuiGUO** [comment]
> Is this issue still happening?

Yes, I can't submit the zip file. It shows that I submit unsuccessfully.

**Comment by Didayolo** [comment]
> > Is this issue still happening?

> Yes, I can't submit the zip file. It shows that I submit unsuccessfully.

If you can't submit a file then this is a different issue.

In the case Zhengying was talking about, the submissions got computed well but then got the "Submission failed" status.

**Comment by YanHuiGUO** [comment]
> > > Is this issue still happening?
> 
> > Yes, I can't submit the zip file. It shows that I submit unsuccessfully.
> 
> If you can't submit a file then this is a different issue.
> 
> In the case Zhengying was talking about, the submissions got computed well but then got the "Submission failed" status.

Yes，you are right. However, how could I solve my problem? I cannot submit my result to the leaderboard(COCO 2019 DensePose Challenge) for about half a month. I affirm that I have a good internet connection.

**Comment by Didayolo** [comment]
@YanHuiGUO feel free to open your own issue if needed.
