### ISSUE TITLE
When can the CodaLab site finish its updation?

### ISSUE THREAD

**Issue by GuangyongChen** [codalab/codalab-competitions#2631]
We have been hosting a contest on Codalab, but when we logged in the CodaLab system this morning, it shows that the CodaLab site is being upgraded. Thus, our contestants can not upload their results and check the leadboard. Could you inform us when the CodaLab service can be available?

**Comment by ckcollab** [comment]
We're currently having some trouble with servers and have to wait for EU support staff to wake up and check on it :(

Apologies for the delays, things should be back up soon.

**Comment by YBei2** [comment]
Is there any latest news about the upgrades?

**Comment by YBei2** [comment]
> We're currently having some trouble with servers and have to wait for EU support staff to wake up and check on it :(
> 
> Apologies for the delays, things should be back up soon.

Is there any news about the upgrades?

**Comment by ckcollab** [comment]
It's back, thanks to our server admin the server was fixed. Thanks for your patience!
