### ISSUE TITLE
Cannot add admin with short username

### ISSUE THREAD

**Issue by danielhers** [codalab/codalab-competitions#2632]
I'm trying to add `oe` as an admin in competition 20129, but when I try to add it in the Edit page, the search box finds only other usernames _containing_ this string. How can I add it?

**Comment by LanaSina** [comment]
I am having the same issue.
I contacted the Codalab team and they said to submit a github issue, so here is a more complete description of the bug:

The search box to look for people when granting admin rights shows 5 results and you cannot scroll down to find the people you're looking for.

**Comment by LanaSina** [comment]
Same issue as this: https://github.com/codalab/codalab-competitions/issues/2639#issue-470669160

**Comment by Didayolo** [comment]
Merged.
