### ISSUE TITLE
Failed, competition phase is being migrated, please try again in a few minutes

### ISSUE THREAD

**Issue by YeDeming** [codalab/codalab-competitions#2634]
Hi, 

When summit to my dataset https://competitions.codalab.org/competitions/23392, I will get 
Failed, competition phase is being migrated, please try again in a few minutes. Do you have some ideas with it?

Best,
Deming Ye

**Comment by pedrada88** [comment]
I am assuming this is prior to the fatal error in the website, but I'm also still getting the same message now in our competition.

**Comment by YeDeming** [comment]
I have transfer it to  https://competitions-new.codalab.org
