### ISSUE TITLE
Server is down and cannot access the website

### ISSUE THREAD

**Issue by bcmi220** [codalab/codalab-competitions#2636]
Hi,

We can not access the server: https://competitions.codalab.org/.  Could you please help to check it? Thank you!

**Comment by geyuying** [comment]
Same problem.

**Comment by yl1991** [comment]
Same

**Comment by sheqi** [comment]
same

**Comment by jokieleung** [comment]
same,Please fix it

**Comment by DLluopf** [comment]
same

**Comment by abhinav28071999** [comment]
please fix it

**Comment by Didayolo** [comment]
Hi everyone,

We are doing our best to fix this as soon as possible.

Thank you for your comprehension.

**Comment by YBei2** [comment]
same issue

**Comment by USTClj** [comment]
Please fix it :)

**Comment by YupengGao** [comment]
same issue

**Comment by USTClj** [comment]
Have any plan when the server is online again? :(

**Comment by Didayolo** [comment]
Our administrators have created a new instance of Codalab https://competitions-new.codalab.org and restored an older backup. Recent competitions may be gone. We are very sorry about this unfortunate event and we are taking steps so this problem will not recur.

You may start using it now, and report to us if you experience any problems. In a few days, if nobody reports problems, we will link it again to the old URL.

Best regards,

The Codalab Team

**Comment by abhinav28071999** [comment]
@Didayolo  I am not able to sign in the codalab. And the sorghum head detection challenge is not there, it's deadline is 21st july. Please add this competition as i have yet to make a submission.

**Comment by YBei2** [comment]
@Didayolo I am not able to sign in the codalab too. And the SegTHOR challenge which I participated in is not there. Can you add competition again?

**Comment by AALEKH** [comment]
@Didayolo I think there is an issue with Sign-in with https://competitions-new.codalab.org

**Comment by dingye18** [comment]
> Our administrators have created a new instance of Codalab https://competitions-new.codalab.org and restored an older backup. Recent competitions may be gone. We are very sorry about this unfortunate event and we are taking steps so this problem will not recur.
> 
> You may start using it now, and report to us if you experience any problems. In a few days, if nobody reports problems, we will link it again to the old URL.
> 
> Best regards,
> 
> The Codalab Team

I can't sign in with this new  codelab website too......
And I can't search the Alchemy-Contest competition in this website too, it looks like that you lost the data for Alchemy-Contest competition.....

**Comment by adriancampos** [comment]
@Didayolo how old is the backup? The last posts I see on some of the forums are from September 2018. If we created our accounts after that date, should we sign up again?

**Comment by ckcollab** [comment]
@abhinav28071999 @YBei2 @AALEKH @adriancampos @dingye18 yes you'll need to re-register unfortunately

**Comment by YBei2** [comment]
@ckcollab How about the disappeared competition? Do we need to inform the competition organizer to reopen the competition?

**Comment by ckcollab** [comment]
@YBei2 The competition organizer may already been attempting to re-create the competition, but yes you could check with them if the competition is still not up.

**Comment by willprice** [comment]
@ckcollab is the restored backup at https://competitions-new.codalab.org/ the newest you have? Or is there any further data recovery planned?

**Comment by ckcollab** [comment]
That's the newest data we have

**Comment by willprice** [comment]
Thanks for the confirmation.

**Comment by 18721258653** [comment]
@Didayolo  the Alchemy Contest which I participated in is not there( https://competitions-new.codalab.org/ ). Can you add competition please?

**Comment by ckcollab** [comment]
@18721258653 you will need to contact that competition's organizer

This repository is for the Codalab Competition's website itself, not the competitions on it which are ran by individual organizers.

**Comment by 18721258653** [comment]
@ckcollab Thank you very much~~  I'll try to contact the organizer

**Comment by zhenxing9968** [comment]
@Didayolo I am not able to sign in the codalab(https://competitions-new.codalab.org/competitions/20132#participate).  Do I need to re-register my account?

**Comment by ckcollab** [comment]
@zhenxing9968 yes, you will need to re-register

**Comment by zhenxing9968** [comment]
@ckcollab thanks

**Comment by John-Yao** [comment]
@ckcollab 
Is the website is one of the backup of Codalab Competition's website?
https://codalab.lri.fr/
Another question is whether the account registried in https://codalab.lri.fr/ can login in the other :https://competitions-new.codalab.org/

**Comment by ymcui** [comment]
I am a competition organizer and very sorry to hear about this news.
Maybe we should have more frequent backups, or competition-wise backups for the competition organizers to achieve faster re-build.

**Comment by Diyago** [comment]
is there a way to get back access to datasets from prev competitions?

**Comment by ecoto** [comment]
Hi, https://competitions-new.codalab.org/ is also down right now. I am the organizer of two competitions that were actually created yesterday. Please take a look at this problem.

**Comment by Didayolo** [comment]
@ecoto 
Hi, personally I can access the website so now it is not down.

**Comment by Didayolo** [comment]
@John-Yao 
http://codalab.lri.fr / is another independent instance of Codalab.

Therefore the accounts and competitions are not shared between codalab.org and codalab.lri.fr

**Comment by Didayolo** [comment]
@ymcui 
Thank you for your message.
Indeed, we have setup a more robust server administration with backups everyday.

**Comment by ajing** [comment]
Will https://competitions.codalab.org/ be back in the future?

**Comment by Didayolo** [comment]
@ajing 
Yes, as soon as we've finishedtesting.

**Comment by pedrada88** [comment]
Will it be eventually possible to recover the data that has been lost? Are you still trying to solve the issue? Our competition is now basically as we created for the first time, with everything being added for the last months lost :(

**Comment by siabar** [comment]
Dear @Didayolo and @ckcollab I am an organizer and we had two competition with the award on the Codalab that the submission has been finished but we were checking the results to give the winners the awards and publish their results on a coming conference! What we can do know to have the submission?! Is there any chance?

- https://competitions.codalab.org/competitions/22834 PharmaCoNER - Pharmacological substances, Compounds and proteins and Named Entity Recognition Track

- https://competitions.codalab.org/competitions/22643  MEDDOCAN - Medical Document Anonymization task

Thanks

**Comment by zhenxing9968** [comment]
@ckcollab  How to Remove Members from Teams?
