### ISSUE TITLE
Can't delete phases

### ISSUE THREAD

**Issue by bbearce** [codalab/codalab-competitions#2637]
Hi Codalab,
First excellent site! Still learning the infrastructure, but in general, all is fine. I can't delete phases and as quoted here (#1444, #1657, #1664):

"
@FlavioAlexander It worked. Thanks! I needed to add reference data to one of the phases. I was keeping the first phase for registration, so shouldn't the reference data and scoring algorithm be optional?

@mk351 I am glad is working. Unfortunately, they are not. For some reason it does not throw errors during competition creation if you don't have a reference to any of them, but it would give you errors when editing the competition. Just keep in mind, you can always go back and change them.
"
It would seem I need reference data and or scoring algorithm. The problem is I have reference data and still, the competition phase remains post delete. Is there any way someone has time to look at this? I really appreciate all the work you all have done so far. If someone helps me figure out if there is indeed a bug, I'd love to learn how to fix it and make contributions to this project.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
_I think they need to register first..I will make them admins asap when they are registered._
2. Please post a link to your competition: _http://miccai2019.eastus.cloudapp.azure.com/_

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
_Chrome: Version 75.0.3770.100 (Official Build) (64-bit)_
2. What is the URL of the problem? _http://miccai2019.eastus.cloudapp.azure.com/competitions/edit_competition/2_

**Comment by ckcollab** [comment]
> > What is the URL of the problem? 
> http://miccai2019.eastus.cloudapp.azure.com

We do not run this server, we run the main Codalab competitions website. Please contact the people who run this miccai2019 server :)

**Comment by bbearce** [comment]
Hi Eric,
 I am the site maintainer for the above-mentioned URL. So I have full
access to the site and its configurations. If I have all the rights and
privileges, is there something I can do on my end?

**Comment by ckcollab** [comment]
My mistake, are you running the latest master code?

**Comment by bbearce** [comment]
So I pulled the latest from github about a month or 6 weeks ago. I was latest at the time. Definitely after these issues (#1444, #1657, #1664). I'm running on a VM in Azure and cloned the https://github.com/codalab/codalab-competitions repo. Theoretically, I can probably update it by pulling master code. I wanted to seek your advice before making any drastic changes.

**Comment by ckcollab** [comment]
Can you give any error logs/output as you're experiencing this problem?

**Comment by bbearce** [comment]
So the "$docker-compose up" starts a running log output for all components of the site as I'm sure you're aware. When having that open, it doesn't change when I attempt to delete a phase. The javascript console logs no issues. What I do see is a javascript alert saying "Are you sure you want to delete this phase?". If I click ok then click "Submit" at the bottom of the edit screen, I'm redirected to the competition homepage.

It doesn't seem to me that the application thinks anything wrong happened. Can you direct me to some other logs or diagnostic for me to get more info?

**Comment by ckcollab** [comment]
Do you experience this same problem on production?

**Comment by bbearce** [comment]
So do you mean https://codalab.org; if so when I go to https://competitions.codalab.org/ it is unavailable? My plan was to upload my competition bundle and test the same functionality. Thoughts? Should I try merging master into this instance? I'm worried about the competition being live. There could be unknown issues.

**Comment by bbearce** [comment]
Sorry, I can't pull master code to this environment because it is live at
the moment. What I am doing is spinning a VM and installing from scratch
and will let you know.

**Comment by bbearce** [comment]
Hi,

Sorry it took so long, but as part of my assignment, I had to create a new instance of the site and document the process. I now have it and it is the latest code as of last week. 

New url: http://medici-codalab-master.eastus.cloudapp.azure.com/
user: test_admin 
pass: password

I made a test phase and added a scoring program and reference data set. Afterwards, I cannot delete the phase (test phase). Seeing as this is not a site used for any comps right now, I can try anything on this and if it breaks, no big deal. I even backed up the code as is with my current settings in the .env file. 

Do you think someone has time to validate what I'm seeing using the above credentials?
