### ISSUE TITLE
Impossible to leave/delete a team

### ISSUE THREAD

**Issue by chrisjbryant** [codalab/codalab-competitions#2643]
Since the big outage last week, we lost our recent competition and wanted to recreate the leaderboard with the system output we collected. 

Since it's impractical to ask all participants to create new accounts and submit the same output, we were hoping to add it all to the competition ourselves manually. One idea was to submit output ourselves as every team so the team name and results will be the same, even if the username isn't.

The problem we ran into is that we cannot remove ourselves from a competition specific team once we have created it. The only way around it would seem to be to create a new user account for each out our participating submissions, but naturally we don't want to make 40 new accounts...

Can you help us with this, or more generally make the "revoke" button in a team work?

Thanks!

------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Done.
2. Please post a link to your competition
https://competitions.codalab.org/teams/20229/

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
Chrome and Opera

2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://competitions.codalab.org/teams/20229/

**Comment by Garrafao** [comment]
I have a similar problem, I can't revoke any teams. When I click on the relevant button, nothing happens. I can't post a link, because we are still testing the competition. I use the latest version of Mozilla Firefox on a Mac.

**Comment by Didayolo** [comment]
Merged.
