### ISSUE TITLE
Memory limited without swap

### ISSUE THREAD

**Issue by seddik11** [codalab/codalab-competitions#2644]
After running for a couple of hours my submission failed due to this error << Your kernel does not support swap limit capabilities or the cgroup is not mounted >> is this related to the recent issues on codalab ?

**Comment by ckcollab** [comment]
This is a warning I believe, can you paste the full output?

**Comment by seddik11** [comment]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpuHXWVu/run/program/helpers/surface.py:234: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if None == self.__mask_reference_nn:
/tmp/codalab/tmpuHXWVu/run/program/helpers/surface.py:253: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if None == self.__reference_mask_nn:
Execution time limit exceeded!

**Comment by seddik11** [comment]
yes it is a warning but why my submission failed then ?

**Comment by ckcollab** [comment]
You exceeded the time limit, it looks like? Closing this for now.

**Comment by seddik11** [comment]
can you extend the time limit then so that the judges could evaluate my submission ?

**Comment by ckcollab** [comment]
This GitHub repo is for the website itself, you'll have to contact the competition organizer or make your submission execute under the time limit.

**Comment by seddik11** [comment]
I believe the problem is not in my submission [https://github.com/Confusezius/unet-lits-2d-pipeline/issues/1](url)
