### ISSUE TITLE
All competitions I was running have disappeared except one

### ISSUE THREAD

**Issue by kovvalsky** [codalab/codalab-competitions#2647]
All my competitions have disappeared except one.
For example, the competition at 
https://competitions.codalab.org/competitions/20220 
doesn't exist any more.

How I can get them back?
```
404
Could not find the page you requested. If this is in error, please file a bug report. For more information about CodaLab, check out the wiki. 
```

**Comment by Didayolo** [comment]
Following a major crash of our system, we restored Codalab from an older backup. Some competitions and some user accounts could not be restored. 

We sincerely apologize for the inconvenience. We have put in place better backup and recovery procedures so this problem will not recur.

If we get a chance to restore the deleted competitions we'll let you know.
