### ISSUE TITLE
Competitions Disappeared

### ISSUE THREAD

**Issue by ilkedemir** [codalab/codalab-competitions#2649]
Some of my competitions are missing, the competition links are not working, and the imported leaderboards are not found. 

Links to competitions:
https://competitions.codalab.org/competitions/21697
https://competitions.codalab.org/competitions/21775
https://competitions.codalab.org/competitions/21685

Page with leaderboards:
http://ubee.enseeiht.fr/skelneton/challenge.html

**Comment by Didayolo** [comment]
Following a major crash of our system, we restored Codalab from an older backup. Some competitions and some user accounts could not be restored.

We sincerely apologize for the inconvenience. We have put in place better backup and recovery procedures so this problem will not recur.

If we get a chance to restore the deleted competitions we'll let you know.
