### ISSUE TITLE
Forum Posts Disappeared

### ISSUE THREAD

**Issue by ilkedemir** [codalab/codalab-competitions#2650]
One year of forum posts are missing in my competitions. These competitions had messages almost every week, now the ones between July 11 2018 and July 11 2019 have disappeared. 

Link to competition forums:
https://competitions.codalab.org/forums/15208/
https://competitions.codalab.org/forums/15207/
https://competitions.codalab.org/forums/15284/

Image for reference:
<img width="1415" alt="Screen Shot 2019-07-22 at 11 19 29 AM" src="https://user-images.githubusercontent.com/9616478/61655142-c998e300-ac72-11e9-8f04-4314e90f014c.png">

**Comment by Didayolo** [comment]
Following a major crash of our system, we restored Codalab from an older backup. Some competitions and some user data could not be restored.

According to the dates it makes sense: old messages (from before the backup) has been restored and new messages (from after the crash) are here. There is, sadly, a gap in between.

We sincerely apologize for the inconvenience. We have put in place better backup and recovery procedures so this problem will not recur.
