### ISSUE TITLE
Issue Regarding Admin Addition

### ISSUE THREAD

**Issue by ardakdemir** [codalab/codalab-competitions#2653]
I can not add admins using usernames using the edit option on the competition.
I enter the username and submit and nothing will get updated. I do not get any errors as well.

I would be glad to have this issue solved.

Best

**Comment by Didayolo** [comment]
Hi,

Is the username short as in #2632, #2639 ? (typically 3 letters or less).

Are you sure you don't have any errors preventing the competition from getting updated? 
Such as in #2546.

Related issues: #2665, #2458.

**Comment by Didayolo** [comment]
Merged.
