### ISSUE TITLE
LiTS Challenge Submitted Results Disappeared

### ISSUE THREAD

**Issue by xuw080** [codalab/codalab-competitions#2656]
I just checked the LiTS challenge I participated a few months ago, it seems like that my submitted results are removed and my account was also removed... Curious about why and how to get submitted results back?

**Comment by Didayolo** [comment]
Following a major crash of our system, we restored Codalab from an older backup. Some competitions and some user accounts could not be restored.

Unfortunately you'll have to re-create an account and re-submit results.

We sincerely apologize for the inconvenience... We have put in place better backup and recovery procedures so this problem will not recur.
