### ISSUE TITLE
Getting "Sorry, failed to upload file." on upload of ~170MB file.

### ISSUE THREAD

**Issue by tutelarix** [codalab/codalab-competitions#2657]
1. Firefox and Opera on Linux PC
2. https://competitions.codalab.org/competitions/17356#participate-submit_results

2-3 days before I was able to upload the files. Now, I can't.
Could you please provide some information about why this issue can happen.

Thank you.

**Comment by Didayolo** [comment]
I can see that your last entry was today so I guess the issue does not recur.

Sorry for the late reply.
