### ISSUE TITLE
Docker image or shebang line seems to be ignored

### ISSUE THREAD

**Issue by danielhers** [codalab/codalab-competitions#2660]
Since this morning, the scoring program in my [competition](https://competitions.codalab.org/competitions/20129) fails due to Python 3 syntax, even though I'm using the docker image `continuumio/anaconda3` and specifying `#!/usr/bin/env python3` at the top of the file. I'm not sure what's making it run the program with Python 2 instead of Python 3, especially since yesterday it worked with Python 3, and I hadn't changed the scoring program.

**Comment by Didayolo** [comment]
Hi,

Sorry for the late reply. Is your issue still happening?

**Comment by danielhers** [comment]
I just changed the scoring program to a Python 2-compatible script (compromising on some of its features). Is there a way to check which interpreter is actually running?

**Comment by Tthomas63** [comment]
Hello,

It seems that was a known issue with that image that should be addressed now:
https://github.com/ContinuumIO/docker-images/issues/153

Best regards,

**Comment by Tthomas63** [comment]
Also as a followup, to check the python version at runtime, use the `sys` standard library and call `version` for a string or `version_info` for a tuple.

```
import sys
if sys.version_info[0] < 3:
    raise Exception("Must be using Python 3")
```

https://docs.python.org/3/library/sys.html#sys.version_info
