### ISSUE TITLE
URLs for REDS in error

### ISSUE THREAD

**Issue by ObeliskChoi** [codalab/codalab-competitions#2664]
If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
    Chrome.

2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

    The following URLs used to download video dataset REDS are in error: 
https://competitions.codalab.org/competitions/21482#participate-get-data
https://competitions.codalab.org/competitions/21483#participate-get-data
https://competitions.codalab.org/competitions/21475#participate-get-data
https://competitions.codalab.org/competitions/21476#participate-get-data

    The message below are shown:
“”“”“”“”“”
404
Could not find the page you requested.
If you are the challenge organizer and this URL previously pointed to a valid competition and it is now missing please contact us at info@codalab.org for more information.

If this is in error, please file a bug report. For more information about CodaLab, check out the wiki.
“”“”“”“”“”

    Thanks for your help.

**Comment by Didayolo** [comment]
Hi,

This competition (21482) does not exist anymore so the link to download the data won't work. 
It is possible that the dataset is still somewhere on the server under another URL.

Good news, I think you can still find this dataset online:
[](https://seungjunnah.github.io/Datasets/reds.html)
