### ISSUE TITLE
Edit Competition Does not Work

### ISSUE THREAD

**Issue by ardakdemir** [codalab/codalab-competitions#2665]
I am trying to make some changes to our competition : https://competitions.codalab.org/competitions/20288

None of the updates I make on the edits tab get reflected. Is it only me that is having this major problem?

**Comment by Didayolo** [comment]
Did you managed to solve your issue?

When you try to validate your changes, are you redirected to the competition webpage or are you stuck in the EDIT mode?

This sometimes happens when an error prevents the changes from being applied.
Try to scroll down in edit page to spot an error message.

**Comment by Didayolo** [comment]
Merged.
