### ISSUE TITLE
Submission Status and Logging

### ISSUE THREAD

**Issue by dustalov** [codalab/codalab-competitions#2668]
Our competition hosted on CodaLab has recently [stopped processing](https://github.com/umanlp/tg2019task/issues/7) any submissions. We made no changes to the scoring program. Every new submission receives the *Submitted* status, but gets stuck in this status for quite a long time.

As far as I see, this problem occurred before (#1567, #2145, #2179). Could you please provide the organizers with the more verbose logging so they can understand the status of the submission system better?

* Browser: Safari 12.1.2 (14607.3.9)
* URL: https://competitions.codalab.org/competitions/20150

**Comment by ckcollab** [comment]
Currently the queue is heavily congested, there are a few submissions in the public queue that have been running for 4 hours and we have only 4 compute workers. It will take a while to chew through all of the queued submissions.

If you need better performance, you can setup your own queue + compute workers:
https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers

Please re-open this if the problem persists or maybe I am misunderstanding the problem!
