### ISSUE TITLE
Add a simple button "Request Chahub Access"

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#2669]
- Send the hostname to Chahub API and a new "pending Chahub access request" is there.
- An email will be sent to info@codalab.org
- We can have a table on Chahub listing these servers with an "accept" or "deny" button
- When an application is "accepted" send the hostname `/chahub/accepted` the new API key

When sending to Chahub save to local memory the API key, or get from database if not found in local memory

**Comment by Tthomas63** [comment]
Closing and merging into wishlist
