### ISSUE TITLE
Weird compute time

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2674]
This issue concerns the competition AutoCV 2: https://autodl.lri.fr/competitions/3

Some submissions terminated normally but the compute time is extremely long:
<img width="1156" alt="Screenshot 2019-08-14 at 14 50 03" src="https://user-images.githubusercontent.com/20074659/63023384-52d3bc00-bea5-11e9-8a0d-fdcdc85caa5a.png">
<img width="1047" alt="Screenshot 2019-08-14 at 14 50 25" src="https://user-images.githubusercontent.com/20074659/63023390-55361600-bea5-11e9-9590-ea2a937d8bcd.png">
<img width="1044" alt="Screenshot 2019-08-14 at 14 50 31" src="https://user-images.githubusercontent.com/20074659/63023396-57987000-bea5-11e9-8c82-d715b1b9b0d6.png">
<img width="1075" alt="Screenshot 2019-08-14 at 15 01 33" src="https://user-images.githubusercontent.com/20074659/63023711-ec9b6900-bea5-11e9-8ba6-60a6e33fc97d.png">

This prevents the participant from making more submissions since a limit of total execution time per day is applied.

What is the logic of this **Compute Time** column? And where can we find the corresponding code block implementing this logic? Please share the info and we can make pull requests to fix.

Some participants are guessing we got weird compute because of many submissions in parallel and there is interference of different runs which makes the run lag. Is this possible?

In some cases, ingestion and scoring terminated normally but the run seems to terminate only after the execution time limit (which is set to 1800s = 30min):
<img width="1036" alt="Screenshot 2019-08-14 at 14 59 56" src="https://user-images.githubusercontent.com/20074659/63023401-59faca00-bea5-11e9-8ee5-91d2aea81fba.png">
<img width="1037" alt="Screenshot 2019-08-14 at 15 13 56" src="https://user-images.githubusercontent.com/20074659/63023807-28363300-bea6-11e9-99db-63139b36dddc.png">

Some other questions are:
- On AutoDL instance of CodaLab, is Ingestion an independent (sub-)process that can be killed by Scoring according to Ingestion's PID? (We'd like to have Scoring to kill Ingestion when the 20min time budget is used up)
- What is the logic of terminating a run? Why does the run continue to run even though Ingestion and Scoring have both terminated?

Please share the reference of the code block of CodaLab concerning this issue. Thanks!

**Comment by zhengying-liu** [comment]
Issue still open. Recent screenshot from [AutoDL challenge](https://autodl.lri.fr/competitions/162):

<img width="1333" alt="Screenshot 2020-02-02 at 20 20 26" src="https://user-images.githubusercontent.com/20074659/73613820-b1c6f200-45f9-11ea-802e-ccdca73000c2.png">

**Comment by Didayolo** [comment]
Merged.
