### ISSUE TITLE
Teams page not available after re-upload

### ISSUE THREAD

**Issue by Garrafao** [codalab/codalab-competitions#2679]
after building various teams in various re-uploads of our competition the team page is not reachable anymore and my user seems to be still member of teams from previously uploaded competitions (clear from team names displayed for submission on the leaderboard.) Thanks for your help in advance!

competition: https://competitions.codalab.org/competitions/20947?secret_key=4b3ff785-5206-4dd6-9b58-3ccb423a3394

**Comment by Didayolo** [comment]
Merged.
