### ISSUE TITLE
Not receiving password reset mails nor verification mails

### ISSUE THREAD

**Issue by IamAdiSri** [codalab/codalab-competitions#2680]
I'm on https://competitions.codalab.org and initially tried to log in, which failed. On seeing the information about the lost backup on CodaLab, I tried to recreate my account. I have not received any email verification mail however. I then tried to reset my password and have not received the password reset mail either.

I'm using Firefox. I have already checked my spam folder. 

Any help would be appreciated.

**Comment by pablogarridofernandez** [comment]
I have the same issue. In fact it seems that my account was deleted.

**Comment by IamAdiSri** [comment]
Well, I found the mails were going to another email account and getting tagged as spam.
