### ISSUE TITLE
Submission stuck at "Running" for a long time

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2681]
This issue concerns the competitions: 
https://autodl.lri.fr/competitions/3
https://autodl.lri.fr/competitions/32

For some submissions, the status is stuck at "Running" for more than 10 hours, without being killed. For example:
<img width="1257" alt="Screenshot 2019-08-22 at 17 44 02" src="https://user-images.githubusercontent.com/20074659/63529262-b2187880-c504-11e9-821f-5f02de752e79.png">
<img width="1253" alt="Screenshot 2019-08-22 at 17 44 08" src="https://user-images.githubusercontent.com/20074659/63529279-b80e5980-c504-11e9-8a36-e44f70f63208.png">

For other submissions, the status was stuck at "Running" for several hours then finally got killed. The exception message is:
<img width="1319" alt="Screenshot 2019-08-22 at 17 47 59" src="https://user-images.githubusercontent.com/20074659/63529643-47b40800-c505-11e9-901f-00d508aabc75.png">

What's really annoying is that, in this case, **all output logs are empty**.

This opinion could be useful: " the cause seems to be the `entr` process not closing with submissions."

**Comment by zhengying-liu** [comment]
Having this issue means that the system experiences two-fold (at least) failure:
1. Firstly, either the scoring program didn't manage to kill ingestion within time budget (20min) or it did kill ingestion but the run doesn't terminate anyway;
2. Secondly, the run is not killed within the hard execution time limit (30min).

The second failure should happen very rarely. But we ran into it anyway...

**Comment by Tthomas63** [comment]
Are we still seeing this issue?
