### ISSUE TITLE
Codalab Signup Verification failed

### ISSUE THREAD

**Issue by Jason1017** [codalab/codalab-competitions#2684]
After signing up, I received the verification email. However, the link in the email seems not working, shows 'this site can't be reached'.
I tried again with other email accounts, none of them worked.
I don't know if there is any solutions to this problem.

**Comment by Didayolo** [comment]
Mmh, this is strange. I just tried and everything worked fine.

I guess you didn't wait before clicking on the link?

**Comment by Jason1017** [comment]
I tried it the next day and this problem was gone. Thx!
