### ISSUE TITLE
submission only works on one dataset and stuck in 'submitting' status

### ISSUE THREAD

**Issue by vergilgxw** [codalab/codalab-competitions#2690]
This issue is related to this competition:
https://autodl.lri.fr/my/competition/48/submissions/
and others.

we submit here and only on dataset (parent phase/dataset 1) receive the submission
![image](https://user-images.githubusercontent.com/4407991/64800576-66b03200-d5b9-11e9-9d20-48a09109859c.png)

datasset2-5 did not receive this submission
![image](https://user-images.githubusercontent.com/4407991/64799973-4fbd1000-d5b8-11e9-98f2-e360c5794685.png)

and statuses of parent/dataset1  are 'submitting'.

Zhengying submits to another competition and the same case occurs.

**Comment by zhengying-liu** [comment]
@vergilgxw : Please confirm that the issue is solved.
@Didayolo : no it's not the code since as I mentioned, everything worked fine days ago with the same code and the same competition.

**Comment by vergilgxw** [comment]
@Tthomas63 @Didayolo @zhengying-liu 
The competition became normal on sep 13 and we can submit successfully. However the same issue occurs today (sep 14). There’s still the problem.

**Comment by vergilgxw** [comment]
@Tthomas63  In our competion, we uploaded 5 datasets with an average size > 1.4GB, is it caused by this ?

**Comment by Didayolo** [comment]
It seems to be working now.
