### ISSUE TITLE
Can not activate my account.

### ISSUE THREAD

**Issue by CQLLL** [codalab/codalab-competitions#2695]
![图片](https://user-images.githubusercontent.com/33657750/64939004-54244a00-d892-11e9-93b3-0dcef7c70db6.png)
I clicked the link in my mailbox, but it did not work yet.

**Comment by tbc01204** [comment]
Hi,
I have same problem.

**Comment by Didayolo** [comment]
Hi,

You are trying to create an account in "Codalab worksheets" branch.

This repository is dedicated to "Codalab competitions".

I tried to activate an account in both and it indeed didn't work for [Codalab worksheets](https://worksheets.codalab.org/).

You should open issues in this repository: https://github.com/codalab/codalab-worksheets

**Comment by tbc01204** [comment]
@Didayolo Thank you for your help

**Comment by CQLLL** [comment]
@Didayolo Thank you!
