### ISSUE TITLE
Question About test-challenge 2019

### ISSUE THREAD

**Issue by RomanticWithoutStatus** [codalab/codalab-competitions#2697]
hello,the competition we join is COCO Keypoint Challenge.I have download the dataset of test-dev 2017(image_info_test-dev2017.json),and submit our test_dev2017's results on keypoint competition website.now, we want to try our method on test-challenge2019's dataset, but we hard to find the .json file about test-challenge2019(just like image_info_test-dev2017.json).So where can we download the .json file about test-challenge2019?

**Comment by Didayolo** [comment]
Hi,

It seems that the datasets can be downloaded here: http://cocodataset.org/#download

If this doesn't answer your question, please contact the challenge organizers. 
This repository is dedicated to the platform itself.

**Comment by RomanticWithoutStatus** [comment]
oh，we can not find test-challenge2019's json on http : //cocodataset.org/#download
