### ISSUE TITLE
For same score, earlier entries should be ranked higher on leaderboard

### ISSUE THREAD

**Issue by jennifermarsman** [codalab/codalab-competitions#2699]
![Screenshot (1926)](https://user-images.githubusercontent.com/10062762/66038581-d196be00-e512-11e9-89b6-93f77c6767a8.png)
I'm participating in the competition for the Climate Informatics hackathon: https://competitions.codalab.org/competitions/21527

They provided a baseline solution to the challenge, and several people submitted that to CodaLab to ensure that we could submit without challenges.  

I also submitted the baseline solution as a test, and I was placed in the #1 slot on the "Results" leaderboard.  All participants who had submitted so far (before me) all submitted the same base solution as well, and everyone had the same score of RMSE = 22.20.  

The bug: if multiple people submit and receive the same score, the person who submits first should remain highest on the leaderboard.  Someone who gets the same score later shouldn't be able to knock down someone who had already obtained that score.

**Comment by Didayolo** [comment]
Hi,

This is a very good remark. Thank you for reporting.

**Comment by Didayolo** [comment]
Merged.
