### ISSUE TITLE
Why post evaluation requires 20000 molecular?

### ISSUE THREAD

**Issue by MilkshakeForReal** [codalab/codalab-competitions#2704]
Submission failed:
dismatched shapes: submission shape (15760, 13), required shape (20000, 13)

**Comment by Didayolo** [comment]
Hi,

This repository is about Codalab platform itself. Therefore we don't know which competition you are trying to participate in.

In any case, your error is clear: your submission file as 15760 examples but the test reference data has 20000. Remember to predict the solution for the **test set**: the one for which you don't have the solution and which should contains 20000 examples.

If you are sure that the error comes from the challenge itself (which seems unlikely), please contact the challenge organizers themselves.

Feel free to re-open this issue if needed. In this case, please give more information (challenge URL, etc.)
