### ISSUE TITLE
Large competition bundle uploads fail

### ISSUE THREAD

**Issue by JVillella** [codalab/codalab-competitions#2707]
Hello,

This may be related to #2687.

I'm on `Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)`. I'm uploading a competition bundle (when creating a new competition) that is ~250MB (contains some large dataset files) that seems to silently fail. If I remove some of those files from the bundle (now the zip is 66KB) it uploads just fine. It's possible that the upload works w/ large files but I don't see the upload going on in the UI, or in the `Chrome Developer Tools > Network` view.

**Comment by JVillella** [comment]
Scratch this. It _does work_, but the UI doesn't update until much later.

**Comment by Didayolo** [comment]
Thank you for reporting. Indeed, I think I've already seen this for big bundle uploads.
