### ISSUE TITLE
The CodaLab site is currently unavailable.

### ISSUE THREAD

**Issue by zhuqianbin** [codalab/codalab-competitions#2708]
Hello,

After I've installed codelab-competitions on ubuntu 18.04, I get the following error:

```
The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later.
```

It seems that nginx cannot access django 

Best regards

**Comment by Didayolo** [comment]
Hi,

Can you report the logs you get by running `docker-compose logs -f` ?

Best regards,
Adrien

**Comment by Didayolo** [comment]
I close this issue for inactivity. Feel free to re-open it if you need help.
