### ISSUE TITLE
submission failed on Codalab site, Davis 2019 unsupervised 

### ISSUE THREAD

**Issue by JanySunny** [codalab/codalab-competitions#2709]
when I submit to the site https://competitions.codalab.org/competitions/20515#participate-submit_results, failed and output like this:
Error: 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpRKmJl5/run/program/evaluation_codalab.py", line 56, in 
    'The folders containing all the frames for each sequence should be placed directly inside the zip without any subfolder.'
AssertionError: The folders containing all the frames for each sequence should be placed directly inside the zip without any subfolder.

I check my zip file, it is like Annotations.zip, inside is Annotations/each_video_folder/frame*.png

**Comment by Didayolo** [comment]
Hi,

As the error message suggests, it seems that you need to zip the folders "each_video_folder" directly without any subfolder.

Maybe:
`each_video_folder/frame*.png`
instead of 
`Annotations/each_video_folder/frame*.png`

Let me know if it works or if you still have an issue.
It is possible that Annotations.zip itself won't work?

**Comment by JanySunny** [comment]
> Hi,
> 
> As the error message suggests, it seems that you need to zip the folders "each_video_folder" directly without any subfolder.
> 
> Maybe:
> `each_video_folder/frame*.png`
> instead of
> `Annotations/each_video_folder/frame*.png`
> 
> Let me know if it works or if you still have an issue.
> It is possible that Annotations.zip itself won't work?

Thank you. I did as you said, submitting a nano.zip, inside which is each_video_folder/frame*.png. Failed again and output the same error.  Besides,I also tried anon.zip/each_video_folder.zip/frame*.png, it cannot work. Any other ways? Please.

**Comment by Didayolo** [comment]
When zipping the saliency maps, make sure no parent directory in included. For instance, try using something like:
`cd path_to_maps; zip ../submission.zip *.png`
The zip file will be like:
```
submission.zip/COCO_test2014_000000000001.png
submission.zip/COCO_test2014_000000000063.png
...
submission.zip/COCO_test2014_000000581808.png
```
(without folders)

**Comment by JanySunny** [comment]
Thank you! I tried and  failed,  same error.  I do not know why.

**Comment by JanySunny** [comment]
Besides, I also read the davis17-evaluation code [https://github.com/davisvideochallenge/davis2017-evaluation/blob/master/evaluation_codalab.py](https://github.com/davisvideochallenge/davis2017-evaluation/blob/master/evaluation_codalab.py) , if the evaluation_codalab.py is right, it should be submission.zip/videoFd/frame*.png, and no matter what is the name of zip file, it will be unzipped in the 'res' directory, then the structure will become res/videoFd/frame*.png. 
I am not sure whether the code in Codalab are same the evaluation_codalab.py in the [https://github.com/davisvideochallenge/davis2017-evaluation/blob/master/evaluation_codalab.py](https://github.com/davisvideochallenge/davis2017-evaluation/blob/master/evaluation_codalab.py).

**Comment by JanySunny** [comment]
Moreover, for DAVIS dataset, if without video folder (namely sequence folder ) , we cannot distinguish the frames from different videos, because in each video folder, the frame names are like 00000.png, 00001.png, 00002.png,  ... .   If just like submission.zip/*.png,  and we rename the frame names to distinguish them , then it will cannot match with the original frame names.

**Comment by Didayolo** [comment]
Did you try asking on the challenge's forum?

**Comment by JanySunny** [comment]
Thank you.  I have sent an email to davisvideochallenge@gmail.com, waiting for the reply.

**Comment by Didayolo** [comment]
There is also a forum here: [https://competitions.codalab.org/forums/13876/](https://competitions.codalab.org/forums/13876/)

Someone got an answer about a failing submission.
