### ISSUE TITLE
Is it possible to re-create a CodaLab shared task while keeping previous participants?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab-competitions#2710]
We may have to re-create a CodaLab shared task because currently there is no way to add or remove columns from the leaderboard without creating a whole new challenge (https://github.com/codalab/codalab-competitions/issues/2390). 

Is it possible to re-create a CodaLab shared task while keeping previous participants?

**Comment by Didayolo** [comment]
Hi,

What do you mean by Codalab shared task?

**Comment by Franck-Dernoncourt** [comment]
A competition hosted on https://competitions.codalab.org/

**Comment by Didayolo** [comment]
You can download the leaderboard (in CSV format) and all submissions to avoid losing this information.

Unfortunately, I think there is currently no way to re-upload it into a new competition. 

This could indeed be a useful feature for the cases where the organizers need to re-upload a challenge. The disadvantages of this feature would be the possibility of creating "fake" leaderboards.

Regarding the issues with updating leaderboard columns without re-uploading (#2686), they are currently being tackled with high priority. Hopefully this will be resolved soon.

**Comment by Franck-Dernoncourt** [comment]
Got it, thanks!

**Comment by Didayolo** [comment]
You are welcome!
