### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by happywu** [codalab/codalab-competitions#2711]
Hi,

I'm trying to reset my password for https://competitions.codalab.org/, however it says
'The e-mail address is not assigned to any user account'
But I do use that email address for the account and I could find the confirmation email for signing up for that email address.

Thanks

**Comment by Didayolo** [comment]
Hi,

What was the date of your inscription?

A disaster occurred this year, deleting all accounts. You may need to re-create it.

We have put in place new administration and backups to avoid loosing data again. Sorry for the inconvenience.

**Comment by juliojj** [comment]
I have the same problem... password reset is not working (recover email never comes) and when I try to create a new account it says the email is already in use. Do you have any suggestion so that I don't need to use another email?
