### ISSUE TITLE
Result page shows Learning Curves of first 5 dataset only.

### ISSUE THREAD

**Issue by shangeth** [codalab/codalab-competitions#2712]
The result page shows only first 5/25 learning curves, but the submission page shows learning curves of all 25/25 datasets.

**Comment by Didayolo** [comment]
Ok I get it in fact in some competitions it works in submission page and in result page and in some other competitions only 5 datasets are shown everywhere.

It is because I've put the usual parent scoring program instead of the parent scoring program for 25 datasets.

**Comment by Didayolo** [comment]
Corrected! Please re-run your submissions.
