### ISSUE TITLE
I can't submit to this page：https://competitions.codalab.org/competitions/17136#participate-submit_results

### ISSUE THREAD

**Issue by weiyiferonia** [codalab/codalab-competitions#2713]
I followed the tips on the web page, but it still remind like that: 'invalid file type()' ?
so, what should I can do?

**Comment by Didayolo** [comment]
Do you have any submission file which worked? (from a starting kit or something)

If the error comes from your file, the organizers should be able to help you. I saw you opened a topic on the competition's forum, hopefully you'll get an answer.
