### ISSUE TITLE
CodaLab cannot be installed!

### ISSUE THREAD

**Issue by Mahsalo** [codalab/codalab-competitions#2715]
Hi

I'm not able to install CodaLab command line on Mac terminal. 
This is what I write in the terminal and I try with both pip and pip3:

pip install virtualenv
pip install codalab
pip install codalabworker

I have already installed Fuse as well. All of these are installed with no issue but when I try : cl work

it says: cl: command not found

I think there is something wrong with the location where CodaLab is installed. right now it is in: 
/Users/../Library/Python/3.7/lib/python/site-packages 

But I guess it must be somewhere else or I should export a path in the bash_profile.
please let me know if you know how to fix this.
thanks

**Comment by Didayolo** [comment]
Hi,

I didn't even know that Codalab had a PyPi package. Unfortunately, I think it doesn't have the latest updates.

To install Codalab, you should follow the instructions on [the repo's README](https://github.com/codalab/codalab-competitions/blob/develop/README.md).

The source code is downloaded using `git clone`.

**Comment by acletournel** [comment]
The PyPi codalab package is related to the codalab/codalab-worksheet part of the codalab project, not codalab-competitions.
Please, open an issue in the codalab-worksheet repository.
