### ISSUE TITLE
Unable to access data on Docker worker

### ISSUE THREAD

**Issue by yahiaali** [codalab/codalab-competitions#2716]
I am trying to set up a competition that has a large image dataset (~30 GB). We are running the submissions on CodaLab workers on AWS. These images are on the AWS instance and we just pass the list of their absolute paths to the CodaLab submissions. I have set up a bindmount between the docker container and the directory in which the images are stored on AWS. When I open a bash shell in the Docker container that has the CodaLab worker, I have no trouble accessing the images, but my test submissions to the competition are all failing with the following error:
```
Traceback (most recent call last):
  File "/tmp/codalab/tmp6Eiujn/run/program/submission.py", line 28, in 
    with open(file_list[0], 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/track2public/Sub-1.nii.gz'
```
Is there some sandboxing that prevents CodaLab submissions from accessing data on the filesystem?

**Comment by Didayolo** [comment]
I have not heard of sandboxing that prevents Codalab submissions from accessing the file system. 

@ckcollab @Tthomas63 
Any insights?

@yahiaali
Are you sure the submissions are running in the same docker container you tested?
Maybe Codalab is opening a new Docker?
When testing the access to the data from the Docker, did you run your actual **scoring program** or did you just try to access the images?

**Comment by Didayolo** [comment]
I close this issue due to the lack of activity and answers.

Feel free to re-open it if needed.
