### ISSUE TITLE
Password Reset is not working

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#2718]
Password reset is not working (recover email never comes) and when I try to create a new account it says the email is already in use. I know you had a kind of disaster few months ago, which may caused this... Anyway, do you have any suggestion so that I can use the same email/user as before, without requiring me to create another account with a different email?

*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by Didayolo** [comment]
Hi Julio,

Do you remember having created a new account after the disaster?

The fact Codalab says that the email is already in use shows that it is registered in the database. And I guess you are the only one that could have used your address. 

So I think there is indeed an issue with the password reset...

Did you forget your password or it is not working anymore?
Did you have a look at your spam folder?

Adrien

**Comment by juliojj** [comment]
Hi Adrien,
thanks for the quick reply. I don't remember if I created a new account after the big disaster or not. And I didn't receive the recover email (I have already checked the spam folder).
Can you force such email to be sent?

**Comment by juliojj** [comment]
oh, sorry. The email was in "promotions" folder... kind of another spam folder on gmail.
Thanks again

**Comment by Didayolo** [comment]
OK, I'm happy to see that it worked!

You're welcome.
