### ISSUE TITLE
Upload large size file issue

### ISSUE THREAD

**Issue by jbles** [codalab/codalab-competitions#2719]
Hello,

Depending on the stability of the connection and the size of the zip file, the submission upload failed very often with the message "Sorry! Failed to upload file".
I created a competition on a private CodaLab plateform, and users have to upload there own trained models. The size of those models is arround 500MB.

So, i am able to upload them with a very good connection (up to 15Mb/s), but fail with a lower connection.
The maximum i were able to upload with a 10Mb/s connection is a 200MB file.

I made many modifications on different buffers and ttimeouts of my browser and of the proxy server without success.

It seems to directly come from the CodaLab instance.
I had tested the upload on a public codalab session. The issue is the same.

I know there is many issues on the CodaLab github without bugfix : 
https://github.com/codalab/codalab-competitions/issues/2497
https://github.com/codalab/codalab-competitions/issues/2495
https://github.com/codalab/codalab-competitions/issues/2654
https://github.com/codalab/codalab-competitions/issues/2512
https://github.com/codalab/codalab-competitions/issues/2453

Perhaps you find one.

Thanks for your help.

**Comment by Didayolo** [comment]
Hi,

Indeed this is a concerning issue. We merged the related issues into this one: #2687.
There is also this one: #2625.

This is a **priority 1** issue that will soon be tackled by Codalab's main developers.

Thank you for your patience.

**Comment by Didayolo** [comment]
Apparently, this error got corrected. 

If you face it again, please report it.

**Comment by Didayolo** [comment]
I close this issue but keep #2687 open for now.
