### ISSUE TITLE
How many detections can be calculated per image in test-dev2019(bbox)？

### ISSUE THREAD

**Issue by QuietDeer** [codalab/codalab-competitions#2722]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by QuietDeer** [comment]
Notice that evaluation metrics are computed allowing for at most 100 top-scoring detections per image (across all categories).
Does 'at most 100 top-scoring detections per image (across all categories)' mean ' 100 top-scoring detections per image per category' ?

**Comment by Didayolo** [comment]
Hi,

Can you please provide the URL of the challenge you are referring to?
Did you try using the challenge's forum or contact the organizers?

This repository is about Codalab platform itself.

**Comment by Didayolo** [comment]
I close this issue due to the lack of activity.

Feel free to re-open it if needed.
