### ISSUE TITLE
Need to uncomment some lines by default in .env_sample

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2724]
In **develop** (and lri-master) branch, the **.env_sample** file contains the following commented lines:

```
#CHAHUB_API_URL=https://chahub.org/api/v1/
#CHAHUB_API_KEY=some-secret-key
#SOCIAL_AUTH_CHAHUB_BASE_URL=https://chahub.org
```

But when `CHAHUB_API_URL` (and maybe also `SOCIAL_AUTH...`) variables are not defined, we get the following error when trying to run the instance:

![error_lri-master_chahub_env](https://user-images.githubusercontent.com/11784999/69876316-940aa300-12bf-11ea-968a-693c5766728b.png)

Basically, the error shows that a `CHAHUB_URL` variable is `None`.

**Uncomment the line solve the issue.** We should uncomment them by default if it does not cause any other issue (e.g. with Chahub).

**Comment by Didayolo** [comment]
Or maybe the code itself should try/catch the presence of this variable?

**Comment by Didayolo** [comment]
It seems that the problem is solved in the Python3 version.
@loicsarrazin In your local instance, did you let these variables commented (they are located at the end of the `.env` file)?

**Comment by loicsarrazin** [comment]
I do not have these variables declared locally. I must have deleted them. Should we add a test related to these variables or something?

**Comment by Didayolo** [comment]
Thanks for your answer.

If you don't have them I think it means this issue is not a problem anymore.

In the old `develop` branch, you got a critical error if you did not declare these variables.
If now you can safely delete them, then we can just close this issue and recommend always using the Python3 version in the future.
