### ISSUE TITLE
2019 challenge1: B-ALL diagnostics---- 404

### ISSUE THREAD

**Issue by rscv5** [codalab/codalab-competitions#2726]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by rscv5** [comment]
link: https://competitions.codalab.org/competitions/20429

**Comment by Didayolo** [comment]
Hi,

You need to provide more information.

Are you the organizer of the competition? 

If yes, did you make the challenge publicly available?
If the challenge is still private, you can only access it with the secret URL. You can manage your competitions in "my competitions".

If you are not the organizer, was the website up in the past?
