### ISSUE TITLE
submissions all stuck in "Submitted"

### ISSUE THREAD

**Issue by bethard** [codalab/codalab-competitions#2727]
All submissions since Dec. 10, 2019 12:00am UTC are stuck in the "Submitted" state. Are there any known issues going on with the servers?

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it

Done.

2. Please post a link to your competition

https://competitions.codalab.org/competitions/20980?secret_key=5cba3f22-a7d8-4744-8d07-85b01e604967

**Comment by ckcollab** [comment]
The queue is rather congested right now, but appears to be churning through jobs. I would expect the current backlog of jobs to be done in approximately 10 hours. Please don't make multiple submissions.

**Comment by bethard** [comment]
Great, thanks for the update.

**Comment by bethard** [comment]
Yes, everything went through eventually.
