### ISSUE TITLE
Results submission problem for COCO Detection Challenge (Bounding Box)

### ISSUE THREAD

**Issue by xiongsiheng** [codalab/codalab-competitions#2733]
I am participating COCO Detection Challenge (Bounding Box) https://competitions.codalab.org/competitions/20794#results and can not evaluate my results on test-dev 2019(bbox). The error information is given below. Can anyone tell me how to solve the problem or just give me a fake result example? Thanks so much! 

Traceback (most recent call last):
  File "/worker/worker.py", line 302, in run
    root_dir = tempfile.mkdtemp(dir=temp_dir)
  File "/usr/local/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 30] Read-only file system: '/tmp/codalab/tmpYQeYha'

**Comment by whwu95** [comment]
I received the same error: https://competitions.codalab.org/competitions/22217#participate-submit_results for NTIRE 2020 Perceptual Extreme Super-Resolution Challenge. Can anyone tell me what the issue is and how to fix it?

**Comment by LuoweiZhou** [comment]
Got the same issue here. Could anyone please advise? https://competitions.codalab.org/competitions/20537#participate-submit_results
