### ISSUE TITLE
Help needed to setup challenge

### ISSUE THREAD

**Issue by jayleicn** [codalab/codalab-competitions#2741]
Hi @ckcollab,

I am trying to set up our challenge in Codalab, could you help me to identify/resolve the issue below? I am using a docker image built by myself instead of the codalab-legacy as my scoring program needs java 1.8. I can run my scoring problem flawlessly with the docker image on my local machine, but it fails on codalab, I have no clue how to further debug it. Any idea?

I have added you as the admin of my challenge, thanks!

Competition link: https://competitions.codalab.org/competitions/22814
Error:
```
PTBTokenizer tokenized 675380 tokens at 237719.49 tokens per second.
PTBTokenizer tokenized 143781 tokens at 175620.61 tokens per second.
Traceback (most recent call last):
  File "/tmp/codalab/tmpxIjsZJ/run/program/evaluate.py", line 172, in <module>
    start_eval()
  File "/tmp/codalab/tmpxIjsZJ/run/program/evaluate.py", line 157, in start_eval
    evaluator.evaluate()
  File "/tmp/codalab/tmpxIjsZJ/run/program/evaluate.py", line 98, in evaluate
    score, scores = scorer.compute_score(gts, preds)
  File "/tmp/codalab/tmpxIjsZJ/run/program/meteor.py", line 37, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/tmp/codalab/tmpxIjsZJ/run/program/meteor.py", line 55, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
IOError: [Errno 32] Broken pipe
Execution time limit exceeded!
```

**Comment by Didayolo** [comment]
Hi,

How did you code the scoring program? 
Did you take inspiration from an existing one? ([example](https://github.com/codalab/competition-examples/tree/master/basic-competition-bundles/Iris/iris_competition_bundle/scoring_program_1_2))

Are you sure you are writing the results in the right way and in the right place?

I am not sure ckcollab will have time to help you. I can try.

**Comment by jayleicn** [comment]
Thanks @Didayolo ,

I have shared my competition bundle with you in this address adrien.pavao@gmail.com. I think I am writing them correctly, as I have created 3 challenges in the past. The docker image I use is `jayleicn/codalab-tvc:fix` . I can also add you to the admin list if you want to. Thanks!

**Comment by jayleicn** [comment]
Hi @Didayolo, Do you have any idea how to fix this?
