### ISSUE TITLE
Docker image: No space left on device

### ISSUE THREAD

**Issue by scaelles** [codalab/codalab-competitions#2745]
Hello,

Since three days ago many submission to the [competition](https://competitions.codalab.org/my/competition/20516) I host are failing with the error shown below. The submissions used to run correctly before that and no configuration change has been done. I use my own Competition docker image: scaelles/codalab:anaconda3-2018.12

Unable to find image 'scaelles/codalab:anaconda3-2018.12' locally
anaconda3-2018.12: Pulling from scaelles/codalab
ff4229790957: Pulling fs layer
d2a3b85993ea: Pulling fs layer
388da27c8816: Pulling fs layer
271b153e4221: Pulling fs layer
381ecf3648aa: Pulling fs layer
d5c134fc2997: Pulling fs layer
271b153e4221: Waiting
381ecf3648aa: Waiting
d5c134fc2997: Waiting
d2a3b85993ea: Verifying Checksum
d2a3b85993ea: Download complete
ff4229790957: Verifying Checksum
ff4229790957: Download complete
381ecf3648aa: Verifying Checksum
381ecf3648aa: Download complete
271b153e4221: Verifying Checksum
271b153e4221: Download complete
ff4229790957: Pull complete
d2a3b85993ea: Pull complete
d5c134fc2997: Verifying Checksum
d5c134fc2997: Download complete
388da27c8816: Verifying Checksum
388da27c8816: Download complete
docker: failed to register layer: Error processing tar file(exit status 1): write /.pyenv/versions/anaconda3-2018.12/pkgs/python-3.7.1-h0371630_7.tar.bz2: no space left on device.
See 'docker run --help'.

Thanks

**Comment by Didayolo** [comment]
This should be resolved.

**Comment by Harvey5678** [comment]
I have the same issue now, how did you fix it before?

**Comment by habiakl-yseop** [comment]
Hello, I have the same urgent issue on a competition running live: [FinCausal-2022](https://codalab.lisn.upsaclay.fr/competitions/3802)

Can someone please help me resolve this?
