### ISSUE TITLE
Submission status stuck with "Submitting"

### ISSUE THREAD

**Issue by Geoinformatics2018** [codalab/codalab-competitions#2746]
We are currently running our competition of the DFC 2020 on your platform.
Here is the link to our competition: https://competitions.codalab.org/competitions/22289

The status of several submissions is "Submitting" for half a day. Could you help us to solve this issue?

**Comment by alloky** [comment]
I faced the same problem yesterday evening and today.

**Comment by mmmaat** [comment]
Maybe related, I cannot create a new competition. When uploading the bundle stuck on "loading". Normally this takes few seconds.

**Comment by distillation-dcf** [comment]
I have the same problem today. I tried to submit a previous successful submission again, but the status remain "Submitting" even after 8 hours.

**Comment by jbehley** [comment]
We experiencing similar problems with the SemanticKITTI challenge (ID: 20331). It seem to start on the February 6th and the last submission was on coda-lri-worker-2.

Hope that helps and thanks in advance.

**Comment by ckcollab** [comment]
2 compute workers are down at the moment (out of 4 total) so the submission queue is getting overloaded. It seems like things are starting to catch up. In the next few hours things should be back to normal.

Please do not make multiple submissions!

**Comment by Didayolo** [comment]
Please give an update if your submissions worked (or not). Thank you in advance!

**Comment by jbehley** [comment]
Seems to worked out us; the pending submission got now through. Thanks for the quick response! :)

**Comment by Geoinformatics2018** [comment]
All the pending submissions were successfully evaluated now. Many thanks for your help!

**Comment by ckcollab** [comment]
cool :)

**Comment by Didayolo** [comment]
Awesome.
