### ISSUE TITLE
Can't access competitions.codalab.org using Firefox. Certificate revoked error.

### ISSUE THREAD

**Issue by victorbocharov** [codalab/codalab-competitions#2748]
SEC_ERROR_REVOKED_CERTIFICATE in Firefox.

1. What browser and version are you using?

Firefox 72.0.2

2. What is the URL of the problem?

https://competitions.codalab.org/competitions/

It works if I turn off OCSP in the browser. It works in Chrome because it doesn't check OCSP by default.

**Comment by Didayolo** [comment]
Thank you for reporting. I'll try to solve this ASAP.

**Comment by Didayolo** [comment]
We identified the problem, we are in the process of solving it.
