### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by pierard** [codalab/codalab-competitions#2750]
Hello,

We have quite often the error "No space left on device" when submitting results to the "Exoplanet imaging data challenge" (https://competitions.codalab.org/competitions/20693). The error seems to happen randomly, but quite often. Here is a typical case:

Unable to find image 'carlgogo/exoimagingchallenge:latest' locally
latest: Pulling from carlgogo/exoimagingchallenge
c5e155d5a1d1: Pulling fs layer
221d80d00ae9: Pulling fs layer
4250b3117dca: Pulling fs layer
3b7ca19181b2: Pulling fs layer
425d7b2a5bcc: Pulling fs layer
d7a526a3eca5: Pulling fs layer
73a96b82cd2c: Pulling fs layer
63e5b6830bb3: Pulling fs layer
811d2b8ea37b: Pulling fs layer
2afa0daefd89: Pulling fs layer
0302e32e7ca3: Pulling fs layer
94e1135fd1a0: Pulling fs layer
3b7ca19181b2: Waiting
63e5b6830bb3: Waiting
425d7b2a5bcc: Waiting
d7a526a3eca5: Waiting
73a96b82cd2c: Waiting
0302e32e7ca3: Waiting
94e1135fd1a0: Waiting
811d2b8ea37b: Waiting
2afa0daefd89: Waiting
4250b3117dca: Verifying Checksum
4250b3117dca: Download complete
221d80d00ae9: Verifying Checksum
221d80d00ae9: Download complete
c5e155d5a1d1: Verifying Checksum
c5e155d5a1d1: Download complete
3b7ca19181b2: Verifying Checksum
3b7ca19181b2: Download complete
d7a526a3eca5: Verifying Checksum
d7a526a3eca5: Download complete
63e5b6830bb3: Verifying Checksum
63e5b6830bb3: Download complete
73a96b82cd2c: Verifying Checksum
73a96b82cd2c: Download complete
811d2b8ea37b: Verifying Checksum
811d2b8ea37b: Download complete
2afa0daefd89: Download complete
0302e32e7ca3: Verifying Checksum
0302e32e7ca3: Download complete
docker: write /var/lib/docker/tmp/GetImageBlob313536264: no space left on device.
See 'docker run --help'.

Can someone fix this issue or explain how to avoid this problem ? I see a few other issues related to "No space left on device"; most of them being closed now. However, I did not get any insight from those.

Thanks !

**Comment by Didayolo** [comment]
Hi,

This error occurs when a compute worker is full, usually because it has to many docker images.

We have cleaned the workers and add a recurrent script for deleting docker images. I guess one or more worker still have the issue, so when your job goes into it it fails.

I'll try to find out and solve the issue.

**Comment by pierard** [comment]
Thanks a lot for your help. I hope you'll find a solution :-)

**Comment by Didayolo** [comment]
We believe that the issue is solved now. Please report if you still face it.

**Comment by pierard** [comment]
Many thanks :-D
