### ISSUE TITLE
How can one set a maximum number of submissions per team?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [codalab/codalab-competitions#2751]
How can one set a maximum number of submissions per team?

I see how to set the maximum number of submissions  per user but not per team:

![image](https://user-images.githubusercontent.com/15331/75493663-47db0780-596f-11ea-893b-1616f43c8093.png)

**Comment by Didayolo** [comment]
This is a excellent question. I am not sure if this feature is implemented.

@ckcollab Any insight?

**Comment by Didayolo** [comment]
Merged.
