### ISSUE TITLE
The email confirmation link expired or is invalid

### ISSUE THREAD

**Issue by LHDuan** [codalab/codalab-competitions#2753]
The confirmation email in my mailbox is invalid, could you please resend me a confirmation email?
When I click "Resend confirmation email" on the website, it always pops up the promt, "Please wait 5 minutes and attempt logging in again to resend confirmation email."
My email address is lhduan@whu.edu.cn .
Thanks.

**Comment by Didayolo** [comment]
Hi,

Sorry for the delayed reply. 

Were you finally able to register?
