### ISSUE TITLE
submission is failed

### ISSUE THREAD

**Issue by ninesun127** [codalab/codalab-competitions#2754]
1.Google browser
![image](https://user-images.githubusercontent.com/15954463/76701242-7a6c5a80-66fa-11ea-9a8f-8535273881cf.png)

**Comment by ninesun127** [comment]
url:https://competitions.codalab.org/competitions/22236#participate-submit_results

**Comment by ninesun127** [comment]
![image](https://user-images.githubusercontent.com/15954463/76701396-c075ee00-66fb-11ea-9bc4-42f0694ae644.png)

**Comment by Didayolo** [comment]
Hi,

The competition you are referring to seems to be working well. Only your submission is failing. It seems that you are supposed to include several image files but some are not present in your submission.

Anyway, this issues are for reporting problems with the Codalab platform itself. You need to contact the challenge organizers themself. I see that the forum is enabled in this competition.

Good luck!
