### ISSUE TITLE
can not sign in "The CodaLab site is currently unavailable."

### ISSUE THREAD

**Issue by oujieww** [codalab/codalab-competitions#2761]
i want to sign in and submit my result,but there always are 
"The CodaLab site is currently unavailable.

Sorry, the page you are looking for is currently unavailable.

Please try again later."

**Comment by RaptorMai** [comment]
same here

**Comment by Didayolo** [comment]
I don't experience any issue. 

Is the issue still occurring?

If yes, can you please be more specific?

**Comment by RaptorMai** [comment]
Yes
when I tried to log in with the following link
https://competitions.codalab.org/accounts/login/

I got this message:

The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later.

**Comment by alexgain** [comment]
Whenever I try to sign up, it gives me the same message. I tried to sign up again and it now says username with email already exists. But I never received an email.

**Comment by ckcollab** [comment]
Please try again, are they arriving now?

**Comment by RaptorMai** [comment]
it works now

**Comment by ckcollab** [comment]
Cool, let us know if you have any more problems
