### ISSUE TITLE
Message to all participants not working?

### ISSUE THREAD

**Issue by jbehley** [codalab/codalab-competitions#2764]
I tried yesterday to write a message to all registered participants (via "Send message to all participants?" under Participants). Unfortunately, I did not receive any email. (I also checked my spam folder.)

This problem occurred with https://competitions.codalab.org/my/competition/20331

**Comment by ckcollab** [comment]
Apologies, would you mind trying again? I made a test account to make sure this feature was working on my end, maybe this occurred while we were having email problems recently.

**Comment by jbehley** [comment]
Works now. Thanks for the quick response.
