### ISSUE TITLE
Feature request: Include rejection reason also in email

### ISSUE THREAD

**Issue by jbehley** [codalab/codalab-competitions#2765]
The reason for rejection of a registration to a competition is currently only communicated in the competition (under "#participate"). It would be nice to also communicate this also in the email. It currently only reads "Your participation privileges have been suspended." 

It would be also sufficient to have the link in the email pointing directly to the participate website. And have it something "See <link> for more information."

**Comment by Didayolo** [comment]
You are right. Thank you for reporting this!

**Comment by fenfenglitech** [comment]
i have submit my request for semntickitti compeitition,when can i get the reply?and my email is 2020110184@ecut.edu.cn

**Comment by Didayolo** [comment]
> i have submit my request for semntickitti compeitition,when can i get the reply?and my email is [2020110184@ecut.edu.cn](mailto:2020110184@ecut.edu.cn)

Please contact directly the organizers of the competition for this kind of request.

**Comment by Didayolo** [comment]
Merged.
