### ISSUE TITLE
bundles not working

### ISSUE THREAD

**Issue by jincli** [codalab/codalab-competitions#2768]
I tried to create a dump from the previous competition and uploaded it to create a new competition. Then, I encountered the following error:

**_Could not find file in archive, make sure scoring_program, reference_data and logo are set to correct file paths._**

Creating a completion using this approach worked well around half a year ago, but when I tried it recently, it could not work.

**Comment by Didayolo** [comment]
Hi,

This may be due to a very recent server error #2769 

Try to re-upload it, maybe it'll work fine now. You can also re-do the dump before uploading.
