### ISSUE TITLE
competitions.codalab.org down?

### ISSUE THREAD

**Issue by lzhbrian** [codalab/codalab-competitions#2769]
Chrome, Firefox, Safari.
I cannot access https://competitions.codalab.org/ from time to time since abt 2 hours ago.

**Comment by ironbar** [comment]
Hi, 
I can access to the website but cannot make submissions to https://competitions.codalab.org/competitions/22472#learn_the_details-overview

Tried both with Chrome and Firefox

**Comment by lzhbrian** [comment]
I can't make submission now either.

**Comment by oujieww** [comment]
yes, i can not make submission now. Getting "Sorry, failed to upload file."

**Comment by Didayolo** [comment]
Hi,

Are you all trying to participate to the same competition? "Short-duration Speaker Verification (SdSV) Challenge 2020"?

I have no issue uploading submissions on other challenges. 

Did you already success in uploading submissions into this specific competition?

**Comment by lzhbrian** [comment]
Just now, I managed to make my submission after waiting a very long time.

btw, I am participating https://competitions.codalab.org/competitions/22966.

**Comment by Didayolo** [comment]
Ok, thanks. So I guess it is a general problem, and maybe it just got solved.

**Comment by oujieww** [comment]
solved? you can make submission now?

**Comment by oujieww** [comment]
i still got "Sorry, failed to upload file."...

**Comment by ironbar** [comment]
I was able to do the submission but it took for maybe an hour when normally takes a few seconds.

**Comment by lzhbrian** [comment]
similar situation for me.

**Comment by oujieww** [comment]
i still can not make submission...

**Comment by ironbar** [comment]
Today the uploading speed is higher, but submissions fail after running for a long time. 

Moreover I cannot access to the output or the log of the submission. When I click on those I get an error "newcodalab.lri.fr took too long to respond.".

**Comment by Didayolo** [comment]
Hi all,

We have identified the issue, due to a maintenance operation on our servers. We're currently working to solve it. Sorry for the inconvenience.

**Comment by lzhbrian** [comment]
@Didayolo Please feel free to close this issue if the problem is solved.
