### ISSUE TITLE
error during result submission 

### ISSUE THREAD

**Issue by aloksinghnits** [codalab/codalab-competitions#2772]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpwJXvdc/run/program/evaluation.py", line 85, in 
    res = measure(ref_file, pred_file)
  File "/tmp/codalab/tmpwJXvdc/run/program/evaluation.py", line 61, in measure
    cocoRes = reference.loadRes(tmp_file)
  File "/tmp/codalab/tmpwJXvdc/run/program/xinpycocotools/coco.py", line 279, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by ckcollab** [comment]
```
'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
```

That looks like it could be your error? Looks specific to the competition/your submission, if you find an error with the Codalab platform will you re-open this?

**Comment by aloksinghnits** [comment]
Thank you so much  for your response. Yes it was my mistake sorry form my side.
