### ISSUE TITLE
error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by zhengying-liu** [codalab/codalab-competitions#2774]
For the competition (private, AutoDL challenge final phase):
https://autodl.lri.fr/competitions/169
Recent submissions encounter following error:
```
Traceback (most recent call last):
  File "/worker/worker.py", line 334, in run
    bundles = get_bundle(cache_dir, root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 188, in get_bundle
    metadata[k] = get_bundle(cache_dir, bundle_path, k, v)
  File "/worker/worker.py", line 188, in get_bundle
    metadata[k] = get_bundle(cache_dir, bundle_path, k, v)
  File "/worker/worker.py", line 137, in get_bundle
    urllib.urlretrieve(url, cached_bundle_file_path)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 273, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 756, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 643, in read
    v = self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```
This happens for both child phase (e.g. submission 34251) and parent phase (submission 34336).

Notice that the same submissions worked completely fine days ago.

From the error message, maybe there is some concurrent use of the queue `main` we're using?

**Comment by Didayolo** [comment]
Message from Sébastien:

> By searching for possible explanations I found this blog where they explain their issue and debugging investigation process for something that looks very similar to us. 

> Have a look and let me know if it can be helpful?

> ¨It seemed it was only occurring on downloads from Google (https://dl.google.com) on our workers running in GCP, and only with relatively large artifacts. This led us to initially blame some bit of infrastructure outside of Taskcluster but we found the issue to be with how Docker was handling networking on our worker machines.¨

http://code.v.igoro.us/posts/2020/05/debugging-docker-connection-reset-by-peer.html

**Comment by Didayolo** [comment]
It seems to be related with Google Cloud Platform's GPU compute workers because I've never faced this issue with our laboratory's GPUs.

**Comment by Didayolo** [comment]
Merged.
