### ISSUE TITLE
cloning from this repo has postgres errors and won't load properly

### ISSUE THREAD

**Issue by bbearce** [codalab/codalab-competitions#2776]
Link to site: http://miccai.westus2.cloudapp.azure.com/. I will have to take it down shortly as I'm going to try different code.

1. What browser and version are you using? Answer: Chrome

It seems like upon running ```docker-compose up``` I automatically have database errors.

Steps I took:

* Created new VM (Azure)
* Installed docker and docker-compose
* git cloned this repo (I noticed it is in develop mode and tests are failing. I don't know if that matters, but doesn't seem good. I cloned a different branch that had the little green check meaning tests passed, but had issues still.)
* Edited a copy of .env_sample copied to .env
* Configured blob storage
* Made sure ports: 80, 443 and 22 were open
* ran ```docker-compose up```

Everything seemed fine but I get the bellow issues to the terminal. 

![codalab_issue](https://user-images.githubusercontent.com/7649007/80105758-ff8f2e80-8546-11ea-810d-b64ae7abf422.png)

Technically I'm using a blob from another project, but I don't know if that should matter. Do you have any hints on what could be wrong? I'd love for this to be user error and simple ;). Anyways any help is appreciated and love the product.

**Comment by ckcollab** [comment]
What is the output of `docker-compose exec django python manage.py migrate`?

**Comment by bbearce** [comment]
bbearce@miccai2019:~/src/codalab-competitions$ docker-compose exec django python manage.py migrate
WARNING: The SSL_CERTIFICATE variable is not set. Defaulting to a blank string.
WARNING: The SSL_CERTIFICATE_KEY variable is not set. Defaulting to a blank string.
/usr/local/lib/python2.7/site-packages/django_extensions/db/fields/__init__.py:425: DeprecationWarning: Django 1.8 features a native UUIDField, this UUIDField will be removed after Django 1.7 becomes unsupported.
  warnings.warn("Django 1.8 features a native UUIDField, this UUIDField will be removed after Django 1.7 becomes unsupported.", DeprecationWarning)

Running migrations for captcha:
- Nothing to migrate.
 - Loading initial data for captcha.
Installed 0 object(s) from 0 fixture(s)
Running migrations for authenz:
- Nothing to migrate.
 - Loading initial data for authenz.
Installed 0 object(s) from 0 fixture(s)
Running migrations for jobs:
- Nothing to migrate.
 - Loading initial data for jobs.
Installed 0 object(s) from 0 fixture(s)
Running migrations for api:
- Nothing to migrate.
 - Loading initial data for api.
Installed 0 object(s) from 0 fixture(s)
Running migrations for web:
- Nothing to migrate.
 - Loading initial data for web.
Installed 0 object(s) from 0 fixture(s)
Running migrations for health:
- Nothing to migrate.
 - Loading initial data for health.
Installed 0 object(s) from 0 fixture(s)
Running migrations for forums:
- Nothing to migrate.
 - Loading initial data for forums.
Installed 0 object(s) from 0 fixture(s)
Running migrations for coopetitions:
- Nothing to migrate.
 - Loading initial data for coopetitions.
Installed 0 object(s) from 0 fixture(s)
Running migrations for queues:
- Nothing to migrate.
 - Loading initial data for queues.
Installed 0 object(s) from 0 fixture(s)
Running migrations for teams:
- Nothing to migrate.
 - Loading initial data for teams.
Installed 0 object(s) from 0 fixture(s)
Running migrations for customizer:
- Nothing to migrate.
 - Loading initial data for customizer.
Installed 0 object(s) from 0 fixture(s)
Running migrations for newsletter:
- Nothing to migrate.
 - Loading initial data for newsletter.
Installed 0 object(s) from 0 fixture(s)
Running migrations for socialaccount:
- Nothing to migrate.
 - Loading initial data for socialaccount.
Installed 0 object(s) from 0 fixture(s)
Running migrations for oauth2_provider:
- Nothing to migrate.
 - Loading initial data for oauth2_provider.
Installed 0 object(s) from 0 fixture(s)
Running migrations for django_extensions:
- Nothing to migrate.
 - Loading initial data for django_extensions.
Installed 0 object(s) from 0 fixture(s)
Running migrations for guardian:
- Nothing to migrate.
 - Loading initial data for guardian.
Installed 0 object(s) from 0 fixture(s)

**Comment by ckcollab** [comment]
@bbearce  ty!

@Tthomas63 if you're doing a fresh install soon, can you see if you encounter this error?

**Comment by bbearce** [comment]
To be honest I had to ditch the VM and start a new and and it all works. :) 

So on that new VM and the old VM I tried
```
sudo docker-compose up
```
and things seem to work. Is this normal? For now it is a good solution, but I feel like I'm doing something wrong if I need sudo. I am the root user. Have I configured permissions wrong for docker or maybe even codalab?

**Comment by ckcollab** [comment]
You shouldn't need to sudo, probably something misconfigured or someone accidentally used sudo before. Closing this issue for now. 

Please don't hesitate to comment if you have more troubles, we'll try to help where we can.
