### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by jbehley** [codalab/codalab-competitions#2777]
Participants informed that currently submissions fail and that error logs just reports "No space left on device". I'm organizing the SemanticKITTI Semantic Segmentation Competition (https://competitions.codalab.org/competitions/20331).

Thanks in advance.

**Comment by Didayolo** [comment]
Is the issue still ocuring?

There is one worker that I can't access. Maybe it is because the disk is full even if we automatically purge Docker images every 15 days. I'll check that more in depth.

Are you using Codalab's default queue, not your own workers?

**Comment by jbehley** [comment]
The problem seems to be solved, since recently submissions got correctly evaluated again.

Thanks for your quick response.

**Comment by acletournel** [comment]
Next time you got the problem, could you mention in the issue the exact timestamp for the problem so that we can catch the corresponding logs in the docker container ?
