### ISSUE TITLE
Duplicate submission

### ISSUE THREAD

**Issue by YaraAlnaggar** [codalab/codalab-competitions#2779]
I'm using Firefox browser and submitting to this competition https://competitions.codalab.org/competitions/20331
When I was uploading my submission, I uploaded the zip file but nothing showed up for multiple seconds then I tried to resubmit the file. Then I got that I've submitted two files . The two submissions are identical and was uploaded on the same second as in the image . Is there anyway to discard the second submission as I have limited number of submission per competition.
Thank you

![image](https://user-images.githubusercontent.com/10332110/80366594-d0035d80-8889-11ea-8168-25e14b412c5e.png)

**Comment by Didayolo** [comment]
Hi,

Only the competition administrators can remove your submission.

Try to contact them if you really need to discard it.

**Comment by YaraAlnaggar** [comment]
thanks ! @Didayolo
