### ISSUE TITLE
CSRF verification failed

### ISSUE THREAD

**Issue by bbearce** [codalab/codalab-competitions#2780]
If you are having trouble using the site:
-----------------------------------------
1. What browser and version are you using?
--> Chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
--> http://miccai2020.eastus.cloudapp.azure.com/competitions/1

--? Do you know how to add eric2 and tthomas63 to the admins without them registering first?

Hi all,
I'm having a silly issue I can't figure out. When I try to login to my site I'm getting CSRF errors. However when using incognito mode it works.

Left: Normal
Right: Incognito
![image](https://user-images.githubusercontent.com/7649007/80512992-5f714500-894c-11ea-9b57-9e89184240a3.png)

Why would it behave differently in incognito mode? Also I had this issue, deleted all docker images and started a fresh pull using ```sudo docker-compose up```. Would someone mind tell me what setting I perhaps have enabled that would cause this?

**Comment by ckcollab** [comment]
Clear cache? Clear cookies? Did you change secret key or anything?

**Comment by bbearce** [comment]
Ok so I apologize for asking this question as it's so basic, but if it helps anyone in the future **clearing the cache wasn't enough**. I had to go to clear history settings in chrome and specifically **delete the cookies**. Thank you @ckcollab!!!!
