### ISSUE TITLE
Can't find user to assign admin rights

### ISSUE THREAD

**Issue by aymenmir1** [codalab/codalab-competitions#2781]
I want to assign a user admin rights to a competition I have created but I can't find the user's username in the drop down list in admins tab. I am absolutely sure that I have the users' correct username. Link to competition: https://competitions.codalab.org/competitions/24580?secret_key=1f62bbbf-aaf0-492f-adfe-8284972c6325

**Comment by Didayolo** [comment]
You are typing the ID and the name is not showing up?

Maybe you need to wait a bit. The search is going through every users and it can take some time before showing names.

**Comment by aymenmir1** [comment]
Even if I wait for about 15 minutes, the user does not show up in the list. Its quite weird that I can't assign this specific user admin rights as I have managed to assign admin rights to a couple of other users without problems

**Comment by Didayolo** [comment]
Are you sure the account still exists? Did its owner confirm you that if can connect to Codalab with this ID?

**Comment by DrShushen** [comment]
I'm experiencing the same issue. The user I'm trying to add has a short username. When attempting to add this user to a competition as admin, the search results show 5 usernames which all _include_ this username within their names. Could it be an issue with the lookup of users? For example, it's limited to 5 results, so if a username is a substring in 5+ other usernames it does not show up?

**Comment by Didayolo** [comment]
> I'm experiencing the same issue. The user I'm trying to add has a short username. When attempting to add this user to a competition as admin, the search results show 5 usernames which all include this username within their names. Could it be an issue with the lookup of users? For example, it's limited to 5 results, so if a username is a substring in 5+ other usernames it does not show up?

This looks like a good explanation to me. This is indeed very constraining.

**Comment by Didayolo** [comment]
I've merged this issue with the other issues pertaining to the editor, especially as this problem preventing to add new admins has been reported several times. Hopefully we'll be able to tackle it soon.
