### ISSUE TITLE
UI improvements for instructors: sort order on participant page

### ISSUE THREAD

**Issue by bennek2** [codalab/codalab-competitions#2783]
https://competitions.codalab.org/competitions/22892

I would like to be able to find submissions of a participant easily.  I tried to sort by participant by clicking the Submitted by.  But it does not reorder by submitted by.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

https://competitions.codalab.org/my/competition/22892
<img width="1264" alt="Screen Shot 2020-05-07 at 5 01 18 PM" src="https://user-images.githubusercontent.com/12432288/81344375-a7971280-9084-11ea-8292-89d2fccdcff0.png">

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?

chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://competitions.codalab.org/my/competition/22892/submissions/?phase=38293&order=%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20submitted_by

**Comment by madclam** [comment]
Various UI ideas:
- show the submission number in participant submission panel and in leaderboard.
- make it possible in submission page to search by submission ID
- make columns sortable

**Comment by madclam** [comment]
In submission panel: have a big button: "share this submission", which creates a link to a zip file containing:
* the submission made
* all the log files

**Comment by madclam** [comment]
The submission ID in the participant submission panel was implemented in v1.8. We want such changes in the main branch too.
<img width="977" alt="Screen Shot 2020-05-07 at 9 59 57 PM" src="https://user-images.githubusercontent.com/7594063/81372078-44ba7100-90ae-11ea-91e6-67086e0d9661.png">

**Comment by madclam** [comment]
Table sorting works in neither branch

**Comment by Didayolo** [comment]
Issue related: #2782

**Comment by Didayolo** [comment]
This is now working on `develop` branch. [codalab.lisn.fr](https://codalab.lisn.fr/)
