### ISSUE TITLE
Codalab competitions is down

### ISSUE THREAD

**Issue by jontypage** [codalab/codalab-competitions#2785]
https://competitions.codalab.org/

The URL times out and doesn't connect - on Chrome Version 81.0.4044.138

**Comment by bicbrv** [comment]
Same problem

**Comment by acletournel** [comment]
Yes, there is currently a power outage on production infrastructure. We are taking care of the problem.
Sorry for the inconvenience !

**Comment by z-x-yang** [comment]
Will the data be lost this time? I remember that Codalab lost all the data after one collapse in last year.

**Comment by edessa** [comment]
Is there an ETA on when it'll be back up?
