### ISSUE TITLE
EPIC-Kitchens Object Detection - Memory Limits

### ISSUE THREAD

**Issue by dimadamen** [codalab/codalab-competitions#2786]
We have a server problem. The same submission file can fail in one attempt and succeed in another. Looks like it's a memory limitation at times in the server.

Competition URL: https://competitions.codalab.org/competitions/20111

Submissions fail with this warning:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by Didayolo** [comment]
Hi,

The following warning is not related to your issue: 
```WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.```
Indeed, it is present in quite every Codalab submissions.

Anyway, the same submission file should not fail sometimes and success sometimes.

Can you show 2 past submissions that are exactly similar but get different outputs?

**Comment by dimadamen** [comment]
These two submissions are exact (not similar). They are exactly the same file. The first failed, the second succeeded

VCL-ITI | 2020-05-23 05:05 | 19f84d3c77af | codalab/codalab-legacy:py3 | None | 622448 | Failed | Scoring | <DISABLED> |   | 7.5% | 0.0% | 0.1% | 16.7% | 2.3% | 0.0%
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
VCL-ITI | 2020-05-23 06:05 | coda-lri-worker-2 | codalab/codalab-legacy:py3 | None | 622450 | Finished | Scoring | <DISABLED> |   | 5.9% | 0.7% | 0.2% | 26.3% | 1.5% | 0.9%

The failure reports exit code 137. No further errors are shown.

**Comment by Didayolo** [comment]
Closing as the competition is over. Feel free to re-open if needed.
