### ISSUE TITLE
Uploading bundle on local server

### ISSUE THREAD

**Issue by RaquelBentimHarrison** [codalab/codalab-competitions#2787]
Trying to upload a competition bundle on a Linux machine and using local server. I get a "Failed to upload" every time with any bundle. I'm using the sample one and haven't made any changes to it. 

1. What browser and version are you using?
Firefox and Chrome

**Comment by Didayolo** [comment]
Did you create the public and private storage buckets and linked them to your instance?

https://github.com/codalab/codalab-competitions/wiki/Storage

**Comment by yobibytes** [comment]
@Didayolo we decided to run our own instance of codalab on a local server due to some corporate regulations that forbid the use any cloud providers. (That means our data have to be stored on local instances.) Is it possible to run codalab for our constellation? If I understand the wiki correctly we need either AWS or Azure as our "storage" system. Correct? (Then that would be a no-go for us...)

**Comment by yobibytes** [comment]
I see that we can run a local minio storage server to mimic AWS S3. I'll try it tomorrow. (https://github.com/codalab/codalab-competitions/wiki/Minio-storage)

**Comment by MTC-ETH** [comment]
@yobibytes Did you have any success? I am stuggeling with my local deployment with minio.

**Comment by MTC-ETH** [comment]
#2810

**Comment by yobibytes** [comment]
@MTC-ETH hi, yes. We had a similar setup. Everything installed as docker containers on one physical server. Now after some struggles we got it working with or without SSL (both self-signed or official). But we had to modifiy some codes in different packages: e.g.

* tasks.py._make_url_sassy: add support for https/http, port, generate_url
*.env: add env variables: AWS_S3_PORT, AWS_S3_DOCKER_HOST, AWS_S3_SECURE_URLS, AWS_S3_USE_SSL
* boto/competitions-v1-compute-worker/django-s3direct: replace urllib with urllib2, support for HTTP and self-signed certificate
* configure docker networks for running minio and codalab on one server

**Comment by MTC-ETH** [comment]
@yobibytes Nice, thank you, that helped me a lot. I also had to add: region_name manually (set `BundleStorage.connection.auth_regin_name` in apps/web/utils)

**Comment by Didayolo** [comment]
I close this issue as it is old and related to a specific local instance setup. Feel free to re-open it if needed.

**Comment by ademasi** [comment]
> @MTC-ETH hi, yes. We had a similar setup. Everything installed as docker containers on one physical server. Now after some struggles we got it working with or without SSL (both self-signed or official). But we had to modifiy some codes in different packages: e.g.
> 
>     * tasks.py._make_url_sassy: add support for https/http, port, generate_url
>       *.env: add env variables: AWS_S3_PORT, AWS_S3_DOCKER_HOST, AWS_S3_SECURE_URLS, AWS_S3_USE_SSL
> 
>     * boto/competitions-v1-compute-worker/django-s3direct: replace urllib with urllib2, support for HTTP and self-signed certificate
> 
>     * configure docker networks for running minio and codalab on one server

Hi @yobibytes  and @Didayolo , would it be possible to upload your changes on github, please ? We are having the same issues at my lab with Minio and codalab. However, all my changes have been unsuccessful until now.

**Comment by loicsarrazin** [comment]
@ademasi I have updated the [wiki](https://github.com/codalab/codalab-competitions/wiki/Minio-storage) with some details on how to setup codalab using the python 3 (branch convert-python3).

**Comment by ademasi** [comment]
@loicsarrazin  Thank you for the wiki update. In the end, we decided to manage our data challenges manually. The minio integration was really troublesome as we wanted everything on the same server. I may try again to deploy codalab for a future one, with minio integrated inside the docker-compose file.

**Comment by Didayolo** [comment]
> @ademasi I have updated the [wiki](https://github.com/codalab/codalab-competitions/wiki/Minio-storage) with some details on how to setup codalab using the python 3 (branch convert-python3).

Note that from now on the updated Python3 branch is the `develop` branch.
