### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2790]
This relates to the main public server codalab v1.5.

In submission https://competitions.codalab.org/my/competition/24774/submissions/#620617
We got the error message:

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 136, in get_bundle
    metadata_folder = _find_only_folder_with_metadata(bundle_path)
  File "/worker/worker.py", line 44, in _find_only_folder_with_metadata
    files_in_path = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmpdYCU7O/run/hidden_ref'

After quite some work, we figured the error came from empty input_data.zip and reference_data.zip. But this was quite hard to figure out. Is there a way to get more explicit error messages?

**Comment by Didayolo** [comment]
Actually this error message is very common in various situations and, indeed, need to be more explicit.

**Comment by Didayolo** [comment]
Another issue featuring the same error message:  #2802

**Comment by Didayolo** [comment]
Merged.
