### ISSUE TITLE
plot/summary of user activity

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#2792]
I see some competitions on codalab showing a plot (graph) about the activity of the users (number of submissions per day, submission scores, etc). In some challenges I co-organized, this plot was included in the competition page automatically. However, our current (and running) challenge does not include this plot. Challenge link: https://competitions.codalab.org/competitions/24184
How can I enable such plot in our competition?
Thanks

**Comment by Didayolo** [comment]
This is the kind of plot in question:

![participation_plot](https://user-images.githubusercontent.com/11784999/83204468-32cb6b80-a14c-11ea-9f9c-df081ce9443a.png)

By looking at the competitions I organized, some have it and some don't... I'll try to find what could make it disappear and how to re-enable it.

**Comment by Didayolo** [comment]
There is a "hide chart" option in the EDIT menu but it is disabled in all my competitions so this doesn't explain the issue.

![hide_chart](https://user-images.githubusercontent.com/11784999/83204697-c0a75680-a14c-11ea-8f9f-ec0f0d6ca35f.png)

**Comment by Didayolo** [comment]
OK, I think I get it.

It can only be enabled when you have a single score (not a multitask/multiscore competition).

I think it is because the plot shows the scores of entries. But this is an unwanted limitation.

**Comment by juliojj** [comment]
Thanks for your quick feedback. It makes some sense that the plot is not shown for multiscore competitions. Maybe a nice feature to be included in future improvements of Codalab could be an option to select one particular variable/column from the leaderboard to be used in such plot.

**Comment by Didayolo** [comment]
Merged.
