### ISSUE TITLE
Leaderboard is not displayed correctly

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2793]
Hello, I am having some problem with the display of the leaderboard.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Codalab does not allow me to do this at the moment (stuck in some kind of "infinite loop" when it searches for person registered in codalab)

2. Please post a link to your competition
https://competitions.codalab.org/competitions/edit_competition/24902

If you are having trouble using the site:
-----------------------------------------
I am not having particular problem with the website.

Describe your issue
---------------------------
A picture often speaks a thousand words:

![codalab_leaderboard_bug](https://user-images.githubusercontent.com/9463182/83230414-00406380-a18a-11ea-890d-cee2cd580164.png)

So basically, the figure on the right is correct. The submission are ranked accordingly with highest score being on top (here highest score is 55.26, second highest is 8.69 and third highest is 0.00).

Bug the leaderboard itself (on the left then) shows a completely different story. It says the highest score is 0.00 then 55.26 and then 8.69. Which is not correct.

I tried to modify in the admin panel the different parameters, but i could not get it to work properly. I think the issue comes from:
- to ensure there will be no tie, there are 2 things used for ranking:
  1. the score (as showed here)
  2. the duration (hidden here)
- as far as i understand (see images below) The ordering is first to rank people based on the score ("ordering=1") with highest score being better ("sorting=ascending") and then to use the duration ("ordering=2") with lowest being better ("sorting=descending"):
![codalab_leaderboard_bug2](https://user-images.githubusercontent.com/9463182/83230959-f8cd8a00-a18a-11ea-9172-92c06f5178d9.png)
![codalab_leaderboard_bug3](https://user-images.githubusercontent.com/9463182/83230969-fcf9a780-a18a-11ea-851e-20354a72d8cd.png)

I tried all the other configuration, and i think the leaderboard  (left part on the first figure i showed) is displayed using always the duration as primary score whereas the temporal evolution (right part of the first figure) is modified properly according to the values put in the part above.

Thank a lot for your help

Benjamin

ps. I tried to look for similar issues but i didn't find any. Let me know if this problem has already been fixed.

**Comment by BDonnot** [comment]
EDIT: apparently setting the "selection default" to 1 for the "score" leader-board "solved the issue".

However, i don't get what it does, nor why it's acting like that. Can you give me some insight about it ? 
There were nothing on the documentation page located at https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard#leaderboard-nuts-and-bolts

One way to do so would be to have question mark near the text, and when someone click on it or pass the mouse on it it shows a short description of what it does.

**Comment by Didayolo** [comment]
Merged.
