### ISSUE TITLE
Leaderboard also displays score of "private submission" when autmigration happens

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2794]
*** This is a template for an issue, please remove any non-relevant details to your issue ***
Hello again, i have another issue with the leaderboard which is not related to the other issue I posted this morning #2793 

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
Codalab does not allow me to do this at the moment (stuck in some kind of "infinite loop" when it searches for person registered in codalab)

2. Please post a link to your competition
    https://competitions.codalab.org/competitions/edit_competition/24902

If you are having trouble using the site:
-----------------------------------------
NA

Describe your issue
-----------------------------

The problem is the following, after recommendation from Isabelle Guyon, we decided to enable auto migration of one phase to the successive one.

This causes a new issue to appear:
![codalab_leaderboard_bug4](https://user-images.githubusercontent.com/9463182/83277531-81234d80-a1d2-11ea-9b7d-54681a1f5359.png)

As you can see, the score on the leaderboard (on the right) is not correct. Actually it's the score computed with the auto migration on the phase that has not started reported there. This is some kind of "data leak" even though it's not really informative.

**Comment by BDonnot** [comment]
Hello,
Any update on this issue ?

Thanks a lot

Benjamin

**Comment by Didayolo** [comment]
Merged.
