### ISSUE TITLE
Verification mail not received

### ISSUE THREAD

**Issue by jPPuetz** [codalab/codalab-competitions#2797]
Hello,

I'm trying to register since some days and still have not received a verification mail. I have disabled SPAM detection and tried two different mail hoster/providers. On both I'm still waiting for the verification mail and even requested is again multiple times.

1. What browser and version are you using?
- Edge, Firefox

2. What is the URL of the problem?
- https://competitions.codalab.org/accounts/signup/?next=/

**Comment by Didayolo** [comment]
Hi,

This is surprising... I just try to sign up and I could receive the confirmation e-mail.

Most of the time this issue arises, the e-mail is just in spam folder:
#2239
#2405

Can you please double-check this?

**Comment by jPPuetz** [comment]
Yes I double checked it. I did not find a mail in the spam folder. I registered now with a spam mail provider (byom.de) this worked... So there seem to be really an issue with big providers like gmail.com and t-online.de not accepting mails from codalab.

**Comment by Didayolo** [comment]
Thank you for your feedback and glad you could finally register.
