### ISSUE TITLE
Can't add phases to a competition

### ISSUE THREAD

**Issue by sdurfort-yseop** [codalab/codalab-competitions#2800]
Hello,

We would like to add additional phases to a [competition ](https://competitions.codalab.org/competitions/23748 ) we are running on codalab.

We did some tests on our end using our own instance of codalab to ensure it was working fine but we eventually realized the "Add Phase" button is missing from the Edit competition page on https://competitions.codalab.org/.

Is it a bug or is this feature disabled on codalab.org ?

Thanking you in advance for your support

**Comment by Didayolo** [comment]
Hi,

Is the "Add Phase" button present in you own Codalab instance?

**Comment by sdurfort-yseop** [comment]
Yes it is. I cloned this repos a couple month ago to create and test our competition before publishing it on codalab.org.

I could find the 'Add Phase' button in this template https://github.com/codalab/codalab-competitions/blob/727676239aea9af81ddfe52c129b80e5fd77ba07/codalab/apps/web/templates/web/competitions/edit.html#L249
It worked rather ok on my end when I tested adding a couple more phases but couldn't do it on codalab.org as the feature seems to be missing.

**Comment by sdurfort-yseop** [comment]
Note that we are going to follow another route and publish a new competition with additional phases

**Comment by sdurfort-yseop** [comment]
We finally published a new competition for post-eval tasks. 
Closing this issue.

**Comment by sopankhosla** [comment]
Suffering from similar issues! I am able to add phases on my own instance of codalab. But not able to do so on codalab.org.
