### ISSUE TITLE
Problem with computer workers running on AWS

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2802]
If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition
https://competitions.codalab.org/competitions/24902

If you are having trouble using the site:
-----------------------------------------
Not applicable

Bug description
----------------------
When starting some computer worker on AWS, we are encountering some trouble with the codalab official images, that from time to time lead to this error:
```
File "/worker/worker.py", line 302, in run
    root_dir = tempfile.mkdtemp(dir=temp_dir)
  File "/usr/local/lib/python2.7/tempfile.py", line 339, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmpTamW0S'    
```

We are not really sure why the "/tmp/codalab/" folder is deleted, nor by "whom" (whether it's the docker deamon, the AWS console or the docker image) but an easy fix, i think, is that in the docker image from codalab for example by checking before `root_dir = tempfile.mkdtemp(dir=temp_dir)` is called a change that the "temp_dir"  (ie "/tmp/codalab") exists and if not to create it, with for example this snippet:
```python
if not os.path.exists(temp_dir):
    os.mkdir(temp_dir)
root_dir = tempfile.mkdtemp(dir=temp_dir)
```
replacing the `root_dir = tempfile.mkdtemp(dir=temp_dir)` line.

This problem has been troubling us for every competitions we have organized with compute workers hosted on AWS.

Thanks for your help

Benjamin

**Comment by Didayolo** [comment]
Merged.
