### ISSUE TITLE
Experimenting with the testing version of Codalab

### ISSUE THREAD

**Issue by ncg-task** [codalab/codalab-competitions#2806]
Hello,

I'm having trouble accessing the site: https://competitions-test.codalab.org/, provided under `Test Drills for Codalab` here: https://codalab-competitions.readthedocs.io/en/latest/Drills/.

I'm using Firefox 77.0.1 (64-bit)

Thank you in advance for any resolution pointers.

**Comment by Didayolo** [comment]
Hello,

I don't think this server exists. You can just upload the bundle to [https://competitions.codalab.org/](https://competitions.codalab.org/) and do your tests here.
