### ISSUE TITLE
Unable to upload competition bundle to codalab.org website

### ISSUE THREAD

**Issue by ncg-task** [codalab/codalab-competitions#2807]
Hello,

I've tried separately to upload different example competitions (https://github.com/bethard/semeval-codalab and https://github.com/felipebravom/EmoInt/tree/master/codalab) on Codalab with no success on either. Below are the messages shown.

1. Uploading file competition.zip 0% complete.
2. There was an error uploading the file. Please try again.

I'm using the competition bundles as is from the original providers.
Not sure how to track the problem with no error log shown

Could you please assist with these errors?
Thank you.

Seen a similar issue reported earlier https://github.com/codalab/codalab-competitions/issues/438

**Comment by Didayolo** [comment]
Hello,

The competition bundle needs to be archive in ZIP format. Also, the ZIP should contains directly the files without useless folder.


Like this:
```
bundle.zip
  | competition.yaml
  | scoring_program
  | etc.
```

Not:

```
bundle.zip
  | competition
      | competition.yaml
      | etc.
```

It is what you are doing?

**Comment by ncg-task** [comment]
Many thanks for your reply. It's working! Thank you. Although, I don't remember doing anything different between earlier and now. It seems the root folder name doesn't really matter. The examples offer 'competition.zip' and you have 'bundle.zip'. Both seem to work fine :)

**Comment by Didayolo** [comment]
Yes, I named it `bundle.zip` in my example but any name is fine.

Great it's working!
