### ISSUE TITLE
Local deployment with MinIO. 

### ISSUE THREAD

**Issue by MTC-ETH** [codalab/codalab-competitions#2810]
We are trying to deploy Codalab on a local server with MinIO. MinIO runs on the same server.
The website runs but I get the "Sorry, failed to upload file." when I try to upload a competition. I know this is very hard to debug, but I hope you can help me anyway. I see in the browser that the request gets sent to Minio and I see in Minio that it receives the request. However I get this error message:

> 127.0.0.1 400 Bad Request
> 127.0.0.1 Accept-Ranges: bytes
> 127.0.0.1 Content-Length: 279
> 127.0.0.1 Content-Type: application/xml
> 127.0.0.1 Server: MinIO/RELEASE.2020-07-02T00-15-09Z
> 127.0.0.1 <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /competition-test-private</Message><Resource>/competition-test-private</Resource><RequestId></RequestId><HostId>b25d0cc0-f92c-4b93-9022-f55ccc067c0e</HostId></Error>
> 127.0.0.1 
> 127.0.0.1 [REQUEST errorResponseHandler] 13:14:09.929
> 127.0.0.1 OPTIONS /competition-test-private
> 127.0.0.1 Host: 127.0.0.1:xxxx
> 127.0.0.1 Access-Control-Request-Method: POST
> 127.0.0.1 Connection: keep-alive
> 127.0.0.1 Content-Length: 0
> 127.0.0.1 User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
> 127.0.0.1 Accept-Encoding: gzip, deflate, br
> 127.0.0.1 Accept-Language: en-US,en;q=0.5
> 127.0.0.1 Origin: https://0.0.0.0
> 127.0.0.1 Referer: https://0.0.0.0/competitions/s3_create_competition
> 127.0.0.1 Accept: */*
> 127.0.0.1 
> 127.0.0.1 [RESPONSE] [13:14:09.929] [ Duration 103µs  ↑ 126 B  ↓ 409 B ]
> 127.0.0.1 400 Bad Request
> 127.0.0.1 Content-Type: application/xml
> 127.0.0.1 Server: MinIO/RELEASE.2020-07-02T00-15-09Z
> 127.0.0.1 Accept-Ranges: bytes
> 127.0.0.1 Content-Length: 279
> 127.0.0.1 <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>XMinioUnknownAPIRequest</Code><Message>Unknown API request at /competition-test-private</Message><Resource>/competition-test-private</Resource><RequestId></RequestId><HostId>b25d0cc0-f92c-4b93-9022-f55ccc067c0e</HostId></Error>
> 127.0.0.1 

Even though the bucket `competition-test-privat` exists. 

This is my .env:

> DEFAULT_FILE_STORAGE=storages.backends.s3boto.S3BotoStorage
> AWS_ACCESS_KEY_ID=xxxxxxx
> AWS_SECRET_ACCESS_KEY=xxxxxx
> AWS_STORAGE_BUCKET_NAME=competition-test-public
> AWS_STORAGE_PRIVATE_BUCKET_NAME=competition-test-private
> AWS_S3_CALLING_FORMAT=boto.s3.connection.OrdinaryCallingFormat
> 
> AWS_S3_HOST=127.0.0.1:xxxx
> 
> AWS_QUERYSTRING_AUTH=False
> S3DIRECT_REGION=us-east-1
> S3_USE_SIGV4=True
> 

From the doc it is not clear at all to me what to put on AWS_S3_HOST. I have the feeling this could be related to [this](https://github.com/minio/minio/issues/8746).

**Comment by MTC-ETH** [comment]
I setup proper non-self-signed SSL for Minio and the upload worked.

However, I am getting following error now:

> worker_site       | [2020-07-14 14:58:26,312: ERROR/Worker-6] Failed unpacking competition
> worker_site       | Traceback (most recent call last):
> worker_site       |   File "/app/codalab/apps/web/tasks.py", line 126, in create_competition
> worker_site       |     logger.info("Creating competition for competition bundle (bundle_id=%s)", comp_def_id)
> worker_site       |   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 431, in inner
> worker_site       |     return func(*args, **kwargs)
> worker_site       |   File "/app/codalab/apps/web/models.py", line 1721, in unpack
> worker_site       |     url = _make_url_sassy(self.s3_config_bundle)
> worker_site       |   File "/app/codalab/apps/web/tasks.py", line 331, in _make_url_sassy
> worker_site       |     bucket=settings.AWS_STORAGE_PRIVATE_BUCKET_NAME,
> worker_site       |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 387, in generate_url
> worker_site       |     response_headers=response_headers, version_id=version_id)
> worker_site       |   File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 378, in generate_url_sigv4
> worker_site       |     iso_date=iso_date)
> worker_site       |   File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 743, in presign
> worker_site       |     region = self.determine_region_name(req.host)
> worker_site       |   File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 666, in determine_region_name
> worker_site       |     return region_name
> worker_site       | UnboundLocalError: local variable 'region_name' referenced before assignment

**Comment by MTC-ETH** [comment]
I also added region_name manually (set `BundleStorage.connection.auth_regin_name` in apps/web/utils), then it worked.

**Comment by 160610101** [comment]
@MTC-ETH 
Hello, did you succeed? Now I have successfully configured Minio with SSL, but the same problem has occurred. In fact, I'm still confused about the changes because I didn't find `BundleStorage.connection.auth_regin_name` in apps/web/utils.  Is it convenient to leave your email? I'd like to learn about your changes to this project code. Esteem it a favor！

**Comment by MTC-ETH** [comment]
@160610101  Hi, yes it worked. To be a bit clearer i changed the code of apps/web/utils to:

`import re

import logging
import requests
from django.conf import settings
from django.core.files.storage import get_storage_class

logger = logging.getLogger(__name__)

StorageClass = get_storage_class(settings.DEFAULT_FILE_STORAGE)

if hasattr(settings, 'USE_AWS') and settings.USE_AWS:
    BundleStorage = StorageClass(bucket=settings.AWS_STORAGE_PRIVATE_BUCKET_NAME)
    PublicStorage = StorageClass(bucket=settings.AWS_STORAGE_BUCKET_NAME)

    BundleStorage.connection.auth_region_name = 'us-east-1'

    PublicStorage.connection.auth_region_name = 'us-east-1'
elif hasattr(settings, 'BUNDLE_AZURE_ACCOUNT_NAME') and settings.BUNDLE_AZURE_ACCOUNT_NAME:
    BundleStorage = StorageClass(account_name=settings.BUNDLE_AZURE_ACCOUNT_NAME,
                                 account_key=settings.BUNDLE_AZURE_ACCOUNT_KEY,
                                 azure_container=settings.BUNDLE_AZURE_CONTAINER)

    PublicStorage = StorageClass(account_name=settings.AZURE_ACCOUNT_NAME,
                                 account_key=settings.AZURE_ACCOUNT_KEY,
                                 azure_container=settings.AZURE_CONTAINER)
else:
    # No storage provided, like in a test, let's just do something basic
    BundleStorage = StorageClass()
    PublicStorage = StorageClass()`

So added the two lines with the region_name.

**Comment by 160610101** [comment]
@MTC-ETH Thanks a lot for your help, but I'm sorry that this problem has not been solved. Is there any other code that needs to be modified, or is there any configuration that is different from the official document [https://github.com/codalab/codalab-competitions/wiki/Minio-storage](url)? My email address is [1160610101@stu.hit.edu.cn](url). If it is convenient, I can provide my configuration file and other operation information in detail. Thank you for your support.
