### ISSUE TITLE
Users appear twice in the leaderboard after joining the team

### ISSUE THREAD

**Issue by yidingjiang** [codalab/codalab-competitions#2812]
I am hosting a competition (https://competitions.codalab.org/competitions/25301). We noticed that one participant (**cadurosar**) is appearing twice in the [leader board](https://competitions.codalab.org/competitions/25301#results).

![image](https://user-images.githubusercontent.com/13373825/87577220-670cd400-c687-11ea-9c9a-93b422377d98.png)

I believe the bug might be due to the participant submitting a solution before joining a competition-level team and later joining that team, since the team name only shows up in one of the leaderboard lines for that user.

**Comment by Didayolo** [comment]
Wow, good catch.

Thank you for reporting this issue.

**Comment by Didayolo** [comment]
Merged.
