### ISSUE TITLE
Have some trouble in Submitted result

### ISSUE THREAD

**Issue by zz10001** [codalab/codalab-competitions#2817]
Hi，

Thanks for  great work, but i get some errors like this in SegTHOR challenge, 
![image](https://user-images.githubusercontent.com/39954774/88003182-d1fe5500-cb36-11ea-83f1-ebea96c7825c.png)
How can I fix it?

**Comment by ncg-task** [comment]
Disclaimer: I'm not from the codalab dev team, just one using the site. 

I had a similar error, then renamed my zip file as submission. Submitted the submission.zip result bundle and the error went away.

**Comment by zz10001** [comment]
> Disclaimer: I'm not from the codalab dev team, just one using the site.
> 
> I had a similar error, then renamed my zip file as submission. Submitted the submission.zip result bundle and the error went away.

Thanks for your kind help, But it still have some problems
![image](https://user-images.githubusercontent.com/39954774/88763201-512e0180-d1a5-11ea-912d-3f85b6003f30.png)

**Comment by Didayolo** [comment]
Hi, I'm closing this issue as it is old and specific to a competition. Feel free to re-open it if needed.
