### ISSUE TITLE
Codalab Competition site is down?

### ISSUE THREAD

**Issue by Or1005** [codalab/codalab-competitions#2818]
Hi Codalab team,

I am admin member of the Mafat Challange competition (1200 participants worldwide) - https://competitions.codalab.org/my/competition/25389

Do you have maybe a status about the connectivity of the global site?

Appreciate it if you can notice me for further details.

Or (MAFAT Challenge Team)
team@mafatchallenge.com

**Comment by bertjiazheng** [comment]
Hi,

First of all, thanks for providing such a platform.

I am one of the organizers of the Holistic 3D Vision Challenge, including [room layout estimation](https://competitions.codalab.org/competitions/24183) and [street-view plane detection](https://competitions.codalab.org/competitions/24942). 

The deadline for our competitions is approaching (in a week). Any reason that the server goes down? 

Best,
Jia

**Comment by Or1005** [comment]
Hi,
We can see that the server is up 👍 
We would truly appreciate receiving status about the situation.
Best,
Or 
(MAFAT Team Challenge)

**Comment by Didayolo** [comment]
Thank you for your comprehension. We'll try to give more updates about server status in the future.
