### ISSUE TITLE
What is the yaml config attribute for specifying which score goes to the Leaderboard?

### ISSUE THREAD

**Issue by ncg-task** [codalab/codalab-competitions#2820]
Greetings,

I have a task with a fine-grained per-task evaluation. At the moment, I'm not sure which attribute in the yaml config specifies the score that is used for the Leaderboard ranking. Would appreciate help with this.

My yaml file is 
[competition.yaml.txt](https://github.com/codalab/codalab-competitions/files/4985932/competition.yaml.txt) I renamed it with .txt extension otherwise it wouldn't upload here...

Thank you in advance for any helpful pointers.

**Comment by ncg-task** [comment]
As I understand it, there is no yaml attribute.

It is merely the first evaluation item. So given my config yaml in the earlier message, it would select  `column_groups: Sentences` and then `columns: SENT_f1` as the first column under `Sentences.`

**Comment by Didayolo** [comment]
Hi,

Sorry for the late reply...

If you still needing this, have a look here: [https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard](https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard)

I hope it helps. Contact me if needed.
