### ISSUE TITLE
I have the same issue too

### ISSUE THREAD

**Issue by YisuZhou** [codalab/codalab-competitions#2823]
I have the same issue too

> Traceback (most recent call last):
>   File "/worker/worker.py", line 330, in run
>     if input_rel_path not in bundles:
> TypeError: argument of type 'NoneType' is not iterable

_Originally posted by @YossiCohen in https://github.com/codalab/codalab-competitions/issues/2814#issuecomment-664142717_

**Comment by Didayolo** [comment]
I close this issue because #2814 is sufficient.
