### ISSUE TITLE
Failed submission to test-dev2019 (bbox) with KeyError

### ISSUE THREAD

**Issue by YiG-SUN** [codalab/codalab-competitions#2826]
1. Image 581295 is in our json but the evaluation script does seem to find it, any ideas? Thanks
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmphFgY2I/run/program/run.py", line 111, in 
    res = cut_res(res, maxDet=100)
  File "/tmp/codalab/tmphFgY2I/run/program/run.py", line 75, in cut_res
    r_img = res[start_end[image_id][0]:start_end[image_id][1]]
KeyError: 581295
2. However,when I was upload my results to  test-dev2019 (segm),it works, I can download output from scoring step.The output_file.zip The output file.zip contains the scores I received.

**Comment by Didayolo** [comment]
Hi,
Sorry for the late reply. I close the issue because it seems stale.
Feel free to open it again if needed.
