### ISSUE TITLE
I use coco2017 trian+val 2017set to train my model？ I want to test my model on test-dev2017? But I cannot find test-dev2017. I only find test-dev2019(bbox)?

### ISSUE THREAD

**Issue by XieXing018** [codalab/codalab-competitions#2827]
![image](https://user-images.githubusercontent.com/18532996/89125432-11527b80-d511-11ea-9582-ef4be07c6f12.png)

**Comment by qncsn2016** [comment]
Have you tried submitting to this competition?

**Comment by XieXing018** [comment]
> Have you tried submitting to this competition?

no, i have not.

**Comment by Didayolo** [comment]
This is not related to the platform.
