### ISSUE TITLE
If is possible to reopen the evaluation server of CHALEARN Face anti-spoofing Attack Detection@CVPR 2020?

### ISSUE THREAD

**Issue by SeanLin0603** [codalab/codalab-competitions#2828]
Dear organizer,

This message is writing to ask about if is possible to reopen the evaluation server of CHALEARN Face anti-spoofing Attack Detection@CVPR 2020? We are the team from National Taiwan University of Science and Technology, we are very interested in Face anti-spoofing issues, and also doing some research in this field. For the self-evaluation demand, we hope to use your evaluation server to show our performance.

If you need any further information, please feel free to  contact me, you can reach me at M10815096@gapps.ntust.edu.tw, Thank you very much.

Respectfully,
Sean Lin

**Comment by Didayolo** [comment]
Dear Sean Lin,

Thank you for your interest in this Codalab competition. We are not the organizers of it ; we manage the platform itself.

You should contact directly the organizers of this competition. You should be able to find them here:

http://www.chalearn.org/contact-us.html or http://chalearnlap.cvc.uab.es/
