### ISSUE TITLE
Question: CodaLab support multiple custom compute workers?

### ISSUE THREAD

**Issue by JVillella** [codalab/codalab-competitions#2829]
Hello,

1. Does CodaLab support having multiple custom compute workers connected to the same broker URL?
2. Additionally, can I update the `CELERYD_CONCURRENCY` in https://github.com/codalab/competitions-v1-compute-worker/blob/master/celeryconfig.py to be >= 1?

Thanks,
Julian

**Comment by Didayolo** [comment]
Hello,

1. **Yes.** You can have as much compute workers as you want connected to the same queue broker URL.
2. I don't really know what this refers to (maybe @ckcollab knows?). But essentially you can update the Docker image as you want, build it and push it to your own DockerHub. Then if it works well and does what you want, it's perfect!
