### ISSUE TITLE
Upload Competition Definition Bundle Fails

### ISSUE THREAD

**Issue by bbearce** [codalab/codalab-competitions#2832]
1. What browser and version are you using? _Chrome_
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using! _http://mgh-azure-covid-collab.eastus.cloudapp.azure.com/competitions/create_

##Summary:
Using the ```convert-python3``` branch and upon fresh install, CodaLab rejects the "yellow_world" competition bundle with error:
![image](https://user-images.githubusercontent.com/7649007/90257421-28e50a80-de15-11ea-916a-45861cdf4f2a.png)

more detail:
![image (1)](https://user-images.githubusercontent.com/7649007/90257873-bd4f6d00-de15-11ea-8a60-f62eebc05185.png)

### First attempts to fix:
The error mentions that max_length is unexpected in method ```get_available_name()```. So based on the error we go to "/usr/local/lob/python3.8/site-packages/django/core/files/storage.py" (https://github.com/django/django/blob/632ccffc49658de5348c51a8918719364be54f37/django/core/files/storage.py#L71) and we see that get_available_name() does in fact have max_length defined as a kwarg and defaults to ```None```. Eric Carmichael reminded me that instead of default storage, CodaLab has its own implementation and it's defined by DEFAULT_FILE_STORAGE.

### Second attempts to fix:
My DEFAULT_FILE_STORAGE=codalab.azure_storage.AzureStorage and traversing CodaLab's code to the "AzureStorage" class definition /home/bbearce/src/codalab-competitions/codalab/codalab/azure_storage.py, I notice that above mentioned django package is imported and used through inheritance to create ```AzureStorage(Storage)``` and that class re-implements the breaking method get_available_name(), but without "max_length", (https://github.com/codalab/codalab-competitions/blob/2ae2a78b3b9d2a8803be67935980d8199c69e380/codalab/codalab/azure_storage.py#L96). So I added it. 

My new error is:
![image](https://user-images.githubusercontent.com/7649007/90258895-2a173700-de17-11ea-884d-165b10757122.png)

### Third attempt to fix:
So now I can call and get inside get_available_name(). It returns ```name```which so far is a logo path: logos/0b694080-eb84-4ec7-99f3-eb66371e7221/logo.jpg. The error that comes up next is sort of from tasks.py, but ultimately models.py. Under ```def create_competition(job_id, comp_def_id):``` in tasks.py (https://github.com/codalab/codalab-competitions/blob/2ae2a78b3b9d2a8803be67935980d8199c69e380/codalab/apps/web/tasks.py#L84) the 
```CompetitionDefBundle``` model is queried and then "unpacked" with ```unpack()```. This takes us to models.py (https://github.com/codalab/codalab-competitions/blob/2ae2a78b3b9d2a8803be67935980d8199c69e380/codalab/apps/web/models.py#L1854) and you can see this line: ```comp.image.save(comp_base['image'], File(io.BytesIO(zf.read(comp_base['image']))))```. Now I've printed the type of zf.read(comp_base['image']) and it is of type "Bytes". So it seems we are feeding in a bytes object to io.BytesIO.

Does anyone have a suggestion. I'm pretty stuck.

**Comment by Didayolo** [comment]
Hi,

I think the `convert-python3` branch is unstable because it is currently under development (@Tthomas63).

You should re-do the install with `master` or `develop` branch.
