### ISSUE TITLE
submission stuck at submitting.

### ISSUE THREAD

**Issue by expectopatronm** [codalab/codalab-competitions#2833]
*** This is a template for an issue, please remove any non-relevant details to your issue ***

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it
2. Please post a link to your competition

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by zihaomu** [comment]
same issue

**Comment by campustian** [comment]
+1

**Comment by tienthanhdhcn** [comment]
We have the same issue. Hopefully, it will get fixed soon.

**Comment by dougpsg** [comment]
+1

**Comment by BDonnot** [comment]
As orginizer of the competitions L2RPN we are encountering the same issue unfortunately :-(

**Comment by JaesungHuh** [comment]
+1

**Comment by Didayolo** [comment]
It seems that the queue is a bit congested because there is currently a lot of usage.

We'll try to moderate this asap.

**Comment by expectopatronm** [comment]
Thank you!
