### ISSUE TITLE
Can't load log files / Can't submit files

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2838]
# Can't load log files

When clicking on any log files such as:

- View ingestion output log
- View ingestion error log
- etc.

The page is doesn't load. We have this issue on all competitions.

# Can't submit files

When trying to submit a file (e.g. a submission), the loading never complete and results in `Sorry, failed to upload file.` message.

**Comment by Troy-Cao** [comment]
Same problem for me. I can't submit my result file, also can't view the output scoring log.

**Comment by Didayolo** [comment]
It's working again.
