### ISSUE TITLE
Team name not visible in the leaderboard

### ISSUE THREAD

**Issue by ajaynagesh** [codalab/codalab-competitions#2840]
Our competition link is  https://competitions.codalab.org/competitions/21430

We are using the docker image: codalab/codalab-legacy:py37 (we need Python3 for our evaluation script)

The issue is: team name is not visible in the generated leaderboard. We know that this issue has been resolved ([here](https://github.com/codalab/codalab-competitions/issues/1838)). But we are still encountering this. Can you please help us out here. 

Thanks
Ajay
DiDi Labs

**Comment by Didayolo** [comment]
Hi,

Are you sure the user is part of a team?

**Comment by ajaynagesh** [comment]
Hi, 

Thanks, I did not realize that in the settings of the user I should mention the team name (settings (top right) --> competition settings --> team name). Then it appears in the leaderboard.
