### ISSUE TITLE
AssertionError: Results do not correspond to current coco set - testdev2019

### ISSUE THREAD

**Issue by deeplearner93** [codalab/codalab-competitions#2844]
I get the follwoing Error. I used the test2017.zip file as my Dataset for running the Inference. I saved the final Predictions as .json file. Renamed is as **detections_test-dev2019_yolovv_results.json** and compressed it as **detections_test-dev2019_yolovv_results.zip**
**Uploaded it to the Evaluation server under the competetion of test-dev2019 (highlighted in Orange in Codalab)**
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpST8DXl/run/program/run.py", line 117, in 
    cocoDt=cocoGt.loadRes(resFile)
  File "/opt/conda/lib/python2.7/site-packages/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
```
Tried uploading more than 8 times by signing up on 2 accounts, as one of the solution was to try resubmitting again.

If there is really a wrong Dataset issue, request to share the direct link, as there is no dataset i found other than test2017 to be used for the challenge.

Competition link used.:
https://competitions.codalab.org/competitions/20794#

Dataset used: - 2017 Test images [41K/6GB]
https://cocodataset.org/#download 

Request some clarity, and support to solve this.
Thank you in Advance.

**Comment by Didayolo** [comment]
Hi,

You should contact directly the competition organizers. This repository concerns Codalab platform itself and has no direct relation to the competitions.

ps. Make sure you've zipped the files directly, without having included any folder structure.

**Comment by deeplearner93** [comment]
@Didayolo 
Thank you for the Quick Response.
The Zipped file contains a Single .json file. No Folder Tree structure or extra files in the Zip file. It is really confusing given the Competition and no clear documentation on one-to-one dataset and corresponding competition, files.

Request support to link this issue to the Competition organisers.
Thank you

**Comment by AlgorithmicIntelligence** [comment]
I got the same issue, did you address this?
