### ISSUE TITLE
I keep seeing my deleted competitions

### ISSUE THREAD

**Issue by gentaiscool** [codalab/codalab-competitions#2846]
I created some competitions and deleted them, but I can still see them in the "Competitions I'm in" tab. Is there any way to hide or delete them permanently?

This is one of them https://competitions.codalab.org/competitions/26519 

Thank you

**Comment by Didayolo** [comment]
Hi,

Thank you for reporting this issue. It actually has been already addressed by this pull request: [https://github.com/codalab/codalab-competitions/pull/2693](https://github.com/codalab/codalab-competitions/pull/2693)

I guess the feature is still in `develop` branch and needs to be merged to `master`.

**Comment by gentaiscool** [comment]
thank you @Didayolo
