### ISSUE TITLE
New scoring program and reference input data isn't updating on competition page

### ISSUE THREAD

**Issue by ncg-task** [codalab/codalab-competitions#2847]
Hello,

I'm Jennifer organizing the NLPContributionGraph Shared Task (https://competitions.codalab.org/competitions/25680) that started yesterday. At the moment we are in the Practice Phase. I'm trying to upload a scoring program, input dataset, and reference dataset. However, these changes are not reflecting. I kindly request your help to resolve this. At the moment we have about 40 participants registered.

The steps I use to update the competition are:
1. Under Admin Features, `Edit`
2. For the pertinent phase (Practice), I add Input Data, Reference Data, and Scoring Program

<img width="570" alt="screen1" src="https://user-images.githubusercontent.com/67460089/94916794-9d503780-04af-11eb-8000-15f13ed44082.png">

3. Click Submit. The update seems okay.
4. I return to my competition.
5. But then on returning to the `Edit` page, the updates don't reflect.
<img width="565" alt="screen2" src="https://user-images.githubusercontent.com/67460089/94917931-d5f11080-04b1-11eb-885e-3bcff9dec464.png">

Separately, after updating the competition, I even tried making submissions, however, it appears the scoring program and reference data are still the old versions.

Please help as I have no idea how to resolve this. I've added `eric2` and `tthomas63` as admins to my competition (or at least tried to in case they can't access it). Generally, even if I try to edit the Webpages on the competition, the changes don't reflect, but this problem isn't as critical.

Again, sharing link to the competition https://competitions.codalab.org/competitions/25680

Thank you very much in advance!

**Comment by ncg-task** [comment]
I've seen this related issue ['How to upload and update a new scoring program and a "truth" file after creating a competition #2795'](https://github.com/codalab/codalab-competitions/issues/2795), however, my competition isn't updating.

**Comment by hmubarak** [comment]
based on your note:
"Separately, after updating the competition, I even tried making submissions, however, it appears the scoring program and reference data are still the old versions."

I suggest that:
you delete all old files (Edit/My Datasets/then delete old scorer and old reference data), press "Submit", then quit the competition.
Open the competition again and make sure that it doesn't have neither a scorer nor a reference data.
Now upload the new scorer and new reference data and link them to the competition as you did before. The files should appear then!

Please make sure that you use the correct versions of the files and link them to the correct phase.

We found strange behaviors like this in our previous competitions!

**Comment by ncg-task** [comment]
Hi,

thank you very much for your reply. Were you'll able to get it to work more recently? I did give your solution a try, however, it still isn't accepting the newly uploaded input data post deleting all old datasets. The following error line shows up: `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpzRKSSZ/run/input/ref/machine-translation/0/sentences.txt'`

Also, I share below a screenshot of how the competition appears post carrying out the following steps: 1) uploading new data; 2) submit; 3) quit competition; and 4) re-enter edit page of the competition.

![screen](https://user-images.githubusercontent.com/67460089/97839176-ec250300-1ce1-11eb-9d22-17acc908be41.jpg)

Thank you again, and would be most appreciative of any further tips or workarounds to resolve the situation.

**Comment by Didayolo** [comment]
Hi,

This issue seems new to me, and I've never faced it.

* In the EDIT menu, you made no other changes that could have failed?
* Did you try to re-upload your scoring program, etc. in the `My Datasets` webpage?
* Is the competition using **results submission** or **code submission**? The `Input Data` is supposed to be the data passed to the "ingestion program", in the case of code submission. If you plan to use only results submission and wish to provide the data to the participants, I think it should be given under `Public Data` field. If you plan to use code submission then I think you should put an ingestion program in addition to the scoring program.

**Comment by ncg-task** [comment]
Hello,

Thank you for your response.

So basically I'm trying to edit an existing competition with a new evaluation dataset and a scoring program for the Practice Phase which is given a date range from present until January 2021. So the only things I tried to edit was literally against the corresponding drop-down boxes to select the new uploaded data (which was first uploaded to the My Datasets section). I assume these are the steps to follow, so I didn't do anything unusual.

In this thread, someone suggested above that I needed to delete all old data/programs, etc., and reupload new ones. I did this. Please see below a screenshot of the My Datasets page.

![my-datasets-page](https://user-images.githubusercontent.com/67460089/98384065-98058000-204d-11eb-957d-8d3b853b0cb2.jpg)

After which, I simply go to the corresponding competition page --> Edit.

Below I show a screenshot of selecting the Input Data from the dropdown list

![add-input-data](https://user-images.githubusercontent.com/67460089/98384431-0d715080-204e-11eb-97b1-0c59b1bfac5f.jpg)

I did the same for Reference Data and Scoring Program

<img width="519" alt="selected-input-fields" src="https://user-images.githubusercontent.com/67460089/98384646-55907300-204e-11eb-94ad-500de00d72f9.png">

Then "Submit" at the bottom of the page.

The 'Edit Page screenshot' is pretty much the same as above.

However, if I go back to the Competition Homepage, try to make a submission (Participate tab -> Submit / View Results -> Submit), I see the error message below

![make-a-submission](https://user-images.githubusercontent.com/67460089/98385289-19a9dd80-204f-11eb-9528-15003411de4a.jpg)

Going back to the competition 'Edit' page, I scroll to the corresponding phase that I tried to update and see the screen below.

<img width="563" alt="blank-competition-edit" src="https://user-images.githubusercontent.com/67460089/98385577-68577780-204f-11eb-9970-fb8d5dd09c4b.png">

It shows no selected values for Input Data, Reference Data, and Scoring Program.

I'm aware at least one other person within the SemEval 2021 series of competitions is also facing the same problem.

Additionally, any edits we make on the remaining web pages also such as Overview, Terms and Conditions, etc., also do not save. However, this latter thing is less of an issue than not being able to update a competition with new dataset and scoring program. Would appreciate help.

**Comment by ncg-task** [comment]
Hello,

I would like to report that my problem is resolved.

As it turned out one of the Web page titles was longer than the permitted character limits (54 and not 50). It showed the error before but I didn't register that as the problem. I wonder if it had to do with the Error message showing up in gray rather than red.

The competition site is updating fine now after addressing this error.

Many thanks!
