### ISSUE TITLE
[CodalabPy3 - feature request] add computation time in the submission metadata

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2851]
Hello,

I made this morning a clone of the competition on the "new" codalab that run using "CodalabPy3" and i encountered some issue with the execution time of the submission. 

It's hard for me to say if it's due to the submission taking too long to process because of the changes made in codalab, or because the worker in the queue are really slow compared to the worker we used in the main competition.

I think a nice addition would be to report the computation time in the submission "metadata" there

Today there are: 

| \# | Score  | Filename | Submission date | Size (bytes) | Status |
|--------|--------|----------|-----------------|--------------|--------|
|1 | .. |wcci_2020_donothing.zip | 10/23/2020 06:31:09 | 90942007 | Failed |   |  
|2 |.. | wcci_2020_donothing.zip | 10/23/2020 12:29:15 |  90942007 | Submitting | |

It would be really nice, also from a participants point of view to get also the computation time, for example with a table like this one

| \# | Score  | Filename | Submission date | Size (bytes) | Time (s) | Status |
|--------|--------|----------|-----------------|--------------|--------|--------|
|1 | ..| wcci_2020_donothing.zip | 10/23/2020 06:31:09 | 90942007 | 301 | Failed |  
|2 | 0.0 | wcci_2020_donothing.zip | 10/23/2020 12:29:15 |  90942007 | .. | Submitting |

**NB** this table is from the "participate" tab

**Comment by Didayolo** [comment]
Merged.
