### ISSUE TITLE
Server Down?

### ISSUE THREAD

**Issue by JialianW** [codalab/codalab-competitions#2852]
Hi there,

Is the server down now? It has been 12 hours since I submitted my last result file, while it is still under 'submitted' status. May I know when the server will start working?

Thanks!

**Comment by zack624** [comment]
I have the same problem with you. It it wasting my time and I hate the server!

**Comment by BeiNNOnAir** [comment]
Same here. It has not worked for more than 12 hours

**Comment by EndlessSora** [comment]
Any updates about this? It looks the status is still "Submitted" for quite a long time.
