### ISSUE TITLE
Testing the Py3 version of Codalab

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#2853]
Hi colleagues,

I created a testing competition at: http://134.158.75.49/competitions/11?secret_key=99d14f53-e160-4b15-8a3d-689cb8c0a3db
It is a copy of our ECCV'20 challenge, with result submission. The submission file has around 15mb.
I performed the following tests:

1) "Max submission size in megabytes" 
I have set it to 16Mb and submitted a bigger file and got the message: "The submission is over the max size of 16 megabyte(s). Size: 30.59 megabyte(s)" -> TEST PASSED!

2) "Max megabyte usage for each participant" I have set it to 40mb and have submitted random predictions (of 15mb each) multiple times. As expected, the two first submissions were ok (as they sum ~30mb) but it failed in the third try as it passed the usage limits (~45mb in total). However, I got the following error: "An unexpected error occurred." ->  The test was " partially OK" as it didn't allow the user to submit when memory usage achieved the limit, but the user feedback needs to be improved, as the given message is not informative. Check test number (4) below, which may help to fix this.

  -> I like that the memory usage is shown: i.e., "Remaining Storage Use: 9.39 megabyte(s) out of 40 megabyte(s) remaining. 30.61 megabyte(s) used"

Up to this stage, I did not make use of the "Delete all submissions except latest and or best. (Use with caution)" feature. Maybe, it would be interesting (in case you find relevant) to allow participants to remove/clean old submission files so that they can manage their memory in order to make new submissions. Otherwise, I imagine they will be stuck if they achieve the limit and this feature is not enabled. 

3) After the above tests, I have set "Delete all submissions except latest and or best. (Use with caution)" feature to on. - Here I was expecting a decrease in user memory usage, as it should remove the submission file that was not the best one, but it didn't happen. That is, Codalab was still showing "Remaining Storage Use: 9.39 megabyte(s) out of 40 megabyte(s) remaining. 30.61 megabyte(s) used"

4) later with another user, and after setting the above feature to on, I repeated test (2) and got the message "The submission would exceed the participant's max storage use of 40 megabyte(s). Space used after: 41.30 megabyte(s)", which seems to be OK... so maybe the user feedback only shows an informative message if "Delete all submissions except latest and or best. (Use with caution)" feature is enabled (to be checked).

5) I have also noted that when I click on "submissions", I cannot see the Results for each submission. Maybe because our competition has multiple scores and codalab may not know what score should be shown (not sure about this). I remember we had a similar problem during the challenge as the history plot was not appearing in the main page, it it seems this was one of the causes. Note, this challenge has 3 scores (positive and negative bias, and accuracy) and the ranking is given by the average ranking on each variable.

I hope these quick tests can help you to further improve this amazing tool which is Codalab.

**Comment by Didayolo** [comment]
Hi Julio,

Thanks again for your help.

To sum up:

- [ ] When reaching the user's storage limit with submissions, the error message is unclear: `An unexcepted error occured` instead of `The submission would exceed the participant's max storage [...]`.
- [ ] This first issue seems to be corrected when the option `Delete all submissions except latest and or best` is enabled.
- [ ] The option `Delete all submissions except latest and or best` doesn't seem to be working: there is no decrease in memory usage when enabling it.

@juliojj About point "5.", yes, as **only one score** is shown in "Submissions" tab it is usually not very satisfying. Is the behaviour you observed different than in Python2 Codalab for this competition?

**Comment by Didayolo** [comment]
Merged.
