### ISSUE TITLE
[CodalabPy3] Bogus submissions - as in codalab py 2

### ISSUE THREAD

**Issue by BDonnot** [codalab/codalab-competitions#2855]
Hello,

I tested some more the python3 version of codalab, and i Encounter the same bug reported in #2842 

In some rare cases, some submissions are stuck at "running" forever, even despite the timeout of 30 mins (1800s)
In the new version I could submit a few of them, and i have this log (which we didn't have in the previous version, so that's nice):

```
Unable to find image 'bdonnot/l2rpn:neurips.2020.4' locally
neurips.2020.4: Pulling from bdonnot/l2rpn
419e7ae5bb1e: Pulling fs layer
848839e0cd3b: Pulling fs layer
de30e8b35015: Pulling fs layer
[lots of docker logs i will not write for clarity]
3736fac7618a: Pull complete
23c1b9f90558: Pull complete
78688e49dba0: Pull complete
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/python3.6/site-packages/atari_py/ale_interface/src/emucore/TIA.cxx: no space left on device.
See 'docker run --help'.
```

This is on the regular queue for the test version of codalabPy3

**Comment by Didayolo** [comment]
For me this is a specific worker issue (no space left on device).
