### ISSUE TITLE
[CodalabPy3] Specific tests to perform

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2858]
For the organizers (e.g. the admin features) :
- [ ] adding a phase
- [ ] changing the end date of the competition after the end (extending the limit date) 
- [ ] the increase of size limit for submissions
- [ ] the decrease of size limit for submissions
- [ ] increase of limit in time for submissions
- [ ] decrease limit in time for submissions
- [ ] modifying the leaderboard features (ordering, numeric format, sorting etc) 
- [ ] change a dataset (so 3 tests: for ingestion, scoring and input_data) 
- [ ] change the queue 
- [ ] change the docker image 
- [x] upload a working bundle
- [ ] upload a failing bundle
- [ ] dump a competition then re-upload the dump (with files and with URI keys)

And for the participants (e.g. the submission) :
- [x] test a working submission
- [ ] test a submission that times out
- [ ] test a submission too heavy (size limit) 
- [ ] test a failing submission

**Comment by BDonnot** [comment]
For the people like me that did not know how to make "tick box" in github, you can try this text
```
-  [ ] adding a phase
```
This will be displayed as this:
-  [ ] adding a phase

And this text:
```
-  [X] adding a phase
```
will be displayed like this:
-  [X] adding a phase


For the organizers (e.g. the admin features) :
-  [ ] adding a phase
-  [X ] changing the end date of the competition after the end (extending the limit date) (this do not work for me when i tried to modify both competition deadline and the deadline of a phase, see #2856 )
-  [ ] the increase of size limit for submissions
-  [ ] the decrease of size limit for submissions
-  [ ] increase of limit in time for submissions
-  [ ] decrease limit in time for submissions
-  [ ] modifying the leaderboard features (ordering, numeric format, sorting etc)
-  [ ] change a dataset (so 3 tests: for ingestion, scoring and input_data)
-  [ ] change the queue
-  [X ]  change the docker image (it's working for me, but i need to resubmit it, i can't use "re run")

And for the participants (e.g. the submission) :

-  [ ] test a working submission
-  [ ] test a submission that times out
-  [ ] test a submission too heavy (size limit)
-  [ ] test a failing submission

**Comment by Didayolo** [comment]
Merged.
