### ISSUE TITLE
Negative coefficient of determination r2

### ISSUE THREAD

**Issue by gianlab** [codalab/codalab-competitions#2865]
Hello,
in this competition https://competitions.codalab.org/competitions/27482  the coefficient of determination R2 assumes negative values but it can assume values between 0 and 1. Why does it assume negative values?

**Comment by Didayolo** [comment]
Hello,
R2 can be negative: [https://en.wikipedia.org/wiki/Coefficient_of_determination](https://en.wikipedia.org/wiki/Coefficient_of_determination)
