### ISSUE TITLE
Your request to participate in this challenge has been received and a decision is pending.

### ISSUE THREAD

**Issue by Akshat978** [codalab/codalab-competitions#2867]
We opted for a competition, Constraint@AAAI2021 - Hostile Post Detection in Hindi. We are getting this message Your request to participate in this challenge has been received and a decision is pending. Please admit us to the competition.
Thanks
Akshat Sharma

**Comment by Didayolo** [comment]
Hi,
You need to contact the competition organizers themselves. 
Here, we manage Codalab platform, we are not responsible of the competitions.
