### ISSUE TITLE
python: can't open file '/tmp/codalab/tmpOHQPwk/run/program/evaluate.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by FeiLyu** [codalab/codalab-competitions#2868]
Hi, I am using Google Chrome.
URL: https://competitions.codalab.org/competitions/17094#participate-submit_results

**Comment by Didayolo** [comment]
Hi,

We need more information in order to help you.

Please re-submit and confirm that you still face the issue.

**Comment by Didayolo** [comment]
I close the issue as it is staling. Feel free to re-open it if needed.

**Comment by leemanyu** [comment]
Hi, I am also facing this problem. 
I've set up our own compute worker based on this tutorial(https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers) using the latest tag of docker image.
However, I keep getting this error of " python: can't open file '/tmp/codalab/tmp5WdI0A/run/program/evaluation.py': [Errno 2] No such file or directory" if I set up the queue to our own docker worker.
I've checked that our scoring program does include the evaluation.py file.

This is our competition page: https://competitions.codalab.org/competitions/28054

**Comment by FeiLyu** [comment]
> Hi, I am also facing this problem.
> I've set up our own compute worker based on this tutorial(https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers) using the latest tag of docker image.
> However, I keep getting this error of " python: can't open file '/tmp/codalab/tmp5WdI0A/run/program/evaluation.py': [Errno 2] No such file or directory" if I set up the queue to our own docker worker.
> I've checked that our scoring program does include the evaluation.py file.
> 
> This is our competition page: https://competitions.codalab.org/competitions/28054

Hi, I just waited a while and retried, and then it works. I think you can retry later, if it still does not work, you can open a new issue or I can reopen this issue. Thank you.

**Comment by leemanyu** [comment]
Hi FeiLyu,
I've tried several times with different submissions and still getting the same error.
I would be most grateful if you can reopen this issue.  
Thank you.

**Comment by FeiLyu** [comment]
> I close the issue as it is staling. Feel free to re-open it if needed.

hi, I have reopened this issue since @leemanyu  also encountered the same issue and it is solved yet. Thank you.

**Comment by FeiLyu** [comment]
> I close the issue as it is staling. Feel free to re-open it if needed.

I am sorry that I can not reopen this issue because it is closed by myself.

**Comment by leemanyu** [comment]
I will open a new issue then. Thank you very much for the effort!
