### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by Tobias-Fischer** [codalab/codalab-competitions#2869]
Hi there,
First of all many thanks for this great open source project!

I'd like to change my username on Codalab from "TobiasRobotics" to "TheLocalizer".

Many thanks in advance!

**Comment by Didayolo** [comment]
Hi,

Please send your request by e-mail to info@codalab.org so we can confirm that it's your own account. 
Use the same e-mail address that the one you used to sign up to Codalab.

Best regards
