### ISSUE TITLE
failed to upload file

### ISSUE THREAD

**Issue by bethard** [codalab/codalab-competitions#2876]
When trying to upload submission.zip files that are around 20K, using Google Chrome, I and my participants are seeing a "Sorry, failed to upload file." error since about 12:00 MST on 5 Dec 2020. This is the following competition:
https://competitions.codalab.org/competitions/26269#participate-submit_results
And as instructed, I have added `eric2` and `tthomas63` as admins to the competition.
(I tried the same via Safari, but everything just hung, rather than getting a error message.)

**Comment by zbwxp** [comment]
Hi I got the same problem.
I have the same problem when entering the:
https://competitions.codalab.org/competitions/19507
using Chorme  about 12:00 ACDT on 6 Dec 2020. 
submitting zip file to:
https://competitions.codalab.org/competitions/19507#participate
It also pop a:
"sorry, failed to upload file." megbox.   

Also, I cannot check the log report that I previously uploaded anymore. It just timeout.

**Comment by wqdfj** [comment]
The same problem here.

**Comment by ChenJoya** [comment]
Unfortunately, I got the same problem. Always timeout.

**Comment by bethard** [comment]
It is working again for me now, so hopefully it was just a transient issue for that half day or so. Our evaluation phase begins in less than a day, so I'll continue to monitor this closely.

**Comment by Didayolo** [comment]
The service seems to be working slowly. We're looking into it.

**Comment by Didayolo** [comment]
Are you still facing the issue?

**Comment by bethard** [comment]
No, uploads seem to be working now. I was going to close this issue at the end of our competition tonight, but feel free to close it now.

**Comment by Didayolo** [comment]
OK. I hope your competition will go well.
