### ISSUE TITLE
LRI server: bug in saving edits

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2878]
Competition:
https://codalab.lri.fr/competitions/783

When changes are made with the editor, they take effect, but we get the following message when we save changes:

<img width="724" alt="Screen Shot 2020-12-10 at 4 40 18 PM" src="https://user-images.githubusercontent.com/7594063/101846846-ad674180-3b06-11eb-9456-94fe6af2b7a5.png">

**Comment by madclam** [comment]
Sometimes the changes are saved ans sometimes not.

**Comment by madclam** [comment]
This is the same bug as https://github.com/codalab/codalab-competitions/issues/2874

**Comment by Didayolo** [comment]
The issue is solved now.

TODO:

- Merge the working code into the right Github branch
- Documentation about migrating from Python2 to Python3?

**Comment by Didayolo** [comment]
Merged.

**Comment by Didayolo** [comment]
This issue still happens in [codalab.lisn.fr](codalab.lisn.fr)

**Comment by Didayolo** [comment]
Remark: the changes are taken into account even if there is an error message

**Comment by Didayolo** [comment]
This issue is resolved!
