### ISSUE TITLE
LRI Server: cannot submit, because says migrating

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2879]
In competition:
https://codalab.lri.fr/competitions/784

<img width="501" alt="Screen Shot 2020-12-10 at 6 59 14 PM" src="https://user-images.githubusercontent.com/7594063/101856607-7e5acb00-3b1a-11eb-871a-655bec739348.png">
<img width="928" alt="Screen Shot 2020-12-10 at 6 59 40 PM" src="https://user-images.githubusercontent.com/7594063/101856653-9599b880-3b1a-11eb-8ebb-ebc833c64f25.png">

**Comment by madclam** [comment]
Interestingly, the competition
https://codalab.lri.fr/competitions/783
which was working just fine now shows the same symptom.

**Comment by Didayolo** [comment]
Merged.
