### ISSUE TITLE
Cannot accept teams requests

### ISSUE THREAD

**Issue by ricber** [codalab/codalab-competitions#2880]
Hello,
We are the organizers of the "1st ACRE Cascade Competition" (https://competitions.codalab.org/competitions/27176). We are having problems accepting some of the teams' requests. Indeed, we cannot either click on Reinstate or Revoke buttons. Could you help us?

**Comment by Didayolo** [comment]
Hi,

Do you mind adding me as an admin of the competition so I can see the problem by myself?

My Codalab ID is "pavao". I won't change anything on the competition without asking you first.

**Comment by ricber** [comment]
Ok, I've added you. Thanks!

**Comment by ricber** [comment]
@Didayolo did you manage to find the problem?

**Comment by Didayolo** [comment]
Hi, 

Sorry for the late reply. I currently can't find a solution for the issues with the team system.
Did you find a way to carry out your competition?

Sorry for the inconvenience.

**Comment by ricber** [comment]
No problem. We asked the participants to create new teams and it worked.
