### ISSUE TITLE
bugs in uploading files from terminal

### ISSUE THREAD

**Issue by ozyyshr** [codalab/codalab-competitions#2882]
Hi, I came across a problem when  uploading files from terminal on Linux to codalab site. Each time I tried to upload files, it stops at around 70 MiB and will never move again. 

Any help would be highly appreciated.

**Comment by Didayolo** [comment]
Hi,

I don't think [Codalab competitions](https://competitions.codalab.org/) can receive uploads from command line.

You may be trying to use [Codalab worksheets](https://worksheets.codalab.org/).

If you really wanted to use Codalab **competitions**, then use directly the web interface. 

If you wanted to use Codalab **worksheets**, please open an issue in the corresponding [repository](https://github.com/codalab/codalab-worksheets).
