### ISSUE TITLE
setting the start time of a challenge

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#2884]
Hi codalab team,
Imagine that I want to start my challenge at day 22/12/2020. Then, I set it on codalab to start on 2020-12-22 00:00:00. The result is that it will be set to start on day 22 but at the midnight (at least, this is what is shown on "Phases" tab). Trying to solve this issue, I change the start day/time to 2020-12-21 00:00:00. Now, it says the challenge will open on the midnight of 2020-12-21, which would be reasonably. However, it seems the "Phases" tab is showing a message that is not consistent with the defined time, as after changing the start date/time to 2020-12-21 00:00:00, the Challenge opened many hours before midnight on that day (probably on hour 00:00:00). I guess the start-time shown on "Phases" (and "Current") tab does not reflect the defined time. Do you mind to check this issue? 
Apologize if I made any mistake.
Best

**Comment by Didayolo** [comment]
Hi Julio,

Sorry for not checking in, it was the Christmas break. 

I hope everything went well for your competition.

Thank you for reporting this issue, I'll keep it open as it is of interest for future competitions.
