### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2885]
On server https://codalab.lri.fr/ it is impossible to create a new user.

For form:

<img width="716" alt="Screen Shot 2020-12-27 at 12 40 13 PM" src="https://user-images.githubusercontent.com/7594063/103179419-c844f000-4840-11eb-8230-eaea207c488d.png">

We get:
<img width="936" alt="Screen Shot 2020-12-27 at 12 38 42 PM" src="https://user-images.githubusercontent.com/7594063/103179401-8d42bc80-4840-11eb-96fc-5f1f82be4d80.png">

This bug was reported by several student users and it is a blocking factor.

**Comment by Didayolo** [comment]
Merged.
