### ISSUE TITLE
failed to upload submission "Image format should be tiff"

### ISSUE THREAD

**Issue by whuldr** [codalab/codalab-competitions#2886]
I use Pillow /opencv/gdal to save my results in 8-bit unsigned integer TIFF.
I have already checked all TIFF files are readable by Pillow, while I failed when I submit my results.
![image](https://user-images.githubusercontent.com/67770208/103641537-dacfcf80-4f8c-11eb-8881-4924ec303ea5.png)

In the 2021 IEEE GRSS Data Fusion Contest Track DSE competition, how did you save the tiff image and submit it successfully?
https://competitions.codalab.org/competitions/27943#learn_the_details

**Comment by Didayolo** [comment]
Hi,

I think you'll get the answer you wan by directly contacting the organizers of this competition or other participants.

You can also directly use the **[forum](https://competitions.codalab.org/forums/24639/)** of the competition. I can see that the organizers answer on it.

**Comment by whuldr** [comment]
> Hi,
> 
> I think you'll get the answer you want by directly contacting the organizers of this competition or other participants.
> 
> You can also directly use the **[forum](https://competitions.codalab.org/forums/24639/)** of the competition. I can see that the organizers answer on it.

Thanks for the reply！I have raised this question on the forum, but have not received a reply
