### ISSUE TITLE
[CodalabPy3/LRI] No detailed results page

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2887]
Even when enabling detailed results, the page remains blank instead of showing `detailed_results.html`

![detailed_issue](https://user-images.githubusercontent.com/11784999/103795604-7a04cd80-5046-11eb-965a-54a0d12a590b.png)

This is an important feature for our competition starting the 1st of February.

**Comment by swook** [comment]
The showing of detailed results (as an HTML iframe) worked a few days ago, but is no longer working. For your reference, here is a sample page: https://competitions.codalab.org/my/competition/submission/803987/detailed_results/

And this attached screenshot of Chrome's DevTools shows that XSS protection was triggered.
![image](https://user-images.githubusercontent.com/755922/107750198-f9f41680-6d1b-11eb-8348-b3dc49cb2bfb.png)

In addition, I found the following error message:
```
Resource interpreted as Document but transferred with MIME type application/octet-stream: "https://newcodalab.lri.fr/prod-private/submission_detailed_results/803987/b0654/detailed_results_file.html?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=ec457e0a45f9bc7e2f9a5a7745cc613bd27c5a56b5a33b3b5c2bc25b68beb498&X-Amz-Date=20210212T091848Z&X-Amz-Credential=AZIAIOSAODNN7EX123LE%2F20210212%2Fnewcodalab%2Fs3%2Faws4_request".
```

It seems to be a webserver misconfiguration on `newcodalab.lri.fr` - but I'm not 100% sure.

**Comment by swook** [comment]
Here is one page that does work... but has the same webserver:
https://competitions.codalab.org/my/competition/submission/801755/detailed_results/

![image](https://user-images.githubusercontent.com/755922/107750531-74249b00-6d1c-11eb-8d1e-2ca1609dfb95.png)

**Comment by swook** [comment]
Hullo, just wanted to bump this issue...

I of course appreciate all of the efforts towards maintaining and developing this awesome platform and do not assume that this issue can be addressed quickly, however, if it turns out to be a user misconfiguration I'd be very happy to be told so as we are now running our competition, and are using this feature.

For your reference, here's a sample page: https://competitions.codalab.org/my/competition/submission/804480/detailed_results/

Thanks!

**Comment by konbick** [comment]
@Didayolo Hi Adrien, do you have a chance to influence the behavior of the 'detailed results'?
What I found is:
- it works on older browsers (e.g. Internet Explorer version 1809)
- it doesn't work for newer browsers (like Chrome, current version)

I saw that the detailed results are supposed to open in an iframe:

<iframe sandbox="allow-scripts" style="width:100%; height:90vh;" src="/competitions/competition/submission/845456/detailed_results.html"></iframe>

Recently, downloads are by default disabled for iframes (see the discussion here: https://stackoverflow.com/questions/61961729/trouble-downloading-files-in-google-apps-script-web-app-after-chrome-update) 

The fix seems simple: adding 'sandbox="allow-downloads"' is supposed to work (see the first and second comment on stackoverflow). 

All effort here is appreciated, as our competition also wants to make use of detailed results.
Thanks! Konstantin

**Comment by jbehley** [comment]
We are experiencing the same problem recently.

https://competitions.codalab.org/competitions/26369#results

For the older submission it works (see rank 2 submission: https://competitions.codalab.org/my/competition/submission/728794/detailed_results/), but for the new submission it apparently doesn't work: https://competitions.codalab.org/my/competition/submission/888691/detailed_results/

Hope that helps to figure out the problem.

**Comment by juliojj** [comment]
same problem here... "when enabling detailed results, the page remains blank". 
Indeed, is the detailed results page automatically generated from the outputs of the evaluation script file or do we need to "manually" generate the "detailed_results.html". In any case, what paths should be used to shown images/plots, links to .csv outputs and text in this detailed results page?

**Comment by jbehley** [comment]
one has to generate the html file yourself. for showing images you need to encode it as base64 and embed it in the html file. Same i think should be necessary to provide a csv. everything must go in this html file.

**Comment by loicsarrazin** [comment]
Detailed results now available in the python 3 version following this commit : 
https://github.com/codalab/codalab-competitions/commit/e6bbf48eebfbf884b93e7f7d7f66ad3465a86393

**Comment by mfelice** [comment]
Could this be patched on [competitions.codalab.org](https://competitions.codalab.org) too please? We have a very active competition and people have been unable to report their detailed results in their papers. Thank you.

**Comment by Didayolo** [comment]
As mentioned above, this issue has been addressed and the detailed results page is working on the new server [codalab.lisn.fr](https://codalab.lisn.fr/).

This PR #3009 aimed at pushing the fix to master and deploy it to [competitons.codalab.org](https://competitons.codalab.org/). However, master has been updated in the meantime, and the change may be risky. Please use the new server.

**Comment by mfelice** [comment]
Thanks for looking into this. Aren't there any plans to import the old competitions and all their submissions to the new server? Re-uploading using dumps only re-creates an empty competition. How do we preserve all the submissions? This is really important for us because our competition is used as a benchmark in our field. Can you advise? Thanks.

**Comment by Didayolo** [comment]
> Thanks for looking into this. Aren't there any plans to import the old competitions and all their submissions to the new server? Re-uploading using dumps only re-creates an empty competition. How do we preserve all the submissions? This is really important for us because our competition is used as a benchmark in our field. Can you advise? Thanks.

This is good question.

We don't plan to migrate the old competitions, user accounts and submissions to the new server.

However:
1. The old server will be kept open. The possibility to create new competitions will be disabled soon, but old competitions will remain accessible, so your benchmark won't disappear.
2. We plan to upgrade the old server to Python3 (the new version of CodaLab). We are not sure if this will be possible, so we cannot promise.
