### ISSUE TITLE
Can't upload competition bundle to localhost installation

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#2890]
When I attempt to verify my installation by uploading the iris competition bundle, I see the following fail:

![image](https://user-images.githubusercontent.com/358649/103910400-c72e8100-50d2-11eb-8eac-76e54ddaa9cd.png)

**Comment by Didayolo** [comment]
Hi John,

As you mentioned in #2889, the README.md doesn't contain all explicit instructions needed to deploy your own local instance.

I think you should try to follow those guides from the Wiki:

- [Configure CodaLab from scratch](https://github.com/codalab/codalab-competitions/wiki/Setup-Local-Competitions)
- [Setup Data Storage](https://github.com/codalab/codalab-competitions/wiki/Storage)

Your issue may come from the fact you didn't setup data storage buckets.

There is more information in the [Wiki](https://github.com/codalab/codalab-competitions/wiki) under the 2.3 section.

Best regards,

Adrien

**Comment by olyerickson** [comment]
Thanks Adrien!

It appears to be working properly on our VM-based install (which I just refreshed...)

**Comment by Didayolo** [comment]
Happy to hear it!
