### ISSUE TITLE
how to withdraw a Competition

### ISSUE THREAD

**Issue by qnamqj** [codalab/codalab-competitions#2892]
I have participate  a Competition, but want withdraw , how to operate?

**Comment by Didayolo** [comment]
Hi,

What do you mean by withdraw?

**Comment by qnamqj** [comment]
> Hi,
> 
> What do you mean by withdraw?

give up Competition

**Comment by Didayolo** [comment]
I am not sure if there is an option to officially leave a competition.
It would be a good feature though.
