### ISSUE TITLE
Cannot approve/reinstantiate new teams

### ISSUE THREAD

**Issue by norahollenstein** [codalab/codalab-competitions#2893]
Hi, I have an issue regarding this competition: https://competitions.codalab.org/my/competition/28176 

As an admin/owner I cannot approve or reinstantiate new teams. In the participant page (https://competitions.codalab.org/my/competition/28176/participants/) nothing happens when I click on "reinstantiate" for team ETLab-HITS (see screenshot). I'm using Chrome.

I have added `eric2` and `tthomas63` as admins to our competition.

Thanks for helping!

![Screenshot 2021-01-26 at 15 11 13](https://user-images.githubusercontent.com/17772234/105855901-e42ae580-5fe8-11eb-96dd-504839882e3d.png)

**Comment by Didayolo** [comment]
Hi,

Thank you for reporting. 

It seems indeed that we have issues with the team system but I currently can't help you.
Can you find a work-around for what you want to achieve?

Sorry for the inconvenience.

**Comment by norahollenstein** [comment]
Thanks for the reply. Yes, for now we just made forming teams optional and let individual users also make submission. I'll close the issue.
