### ISSUE TITLE
how to reset username?

### ISSUE THREAD

**Issue by Whateverandwhereever** [codalab/codalab-competitions#2894]
When i take part in a comprtition, i want to reset my username,please tell me what i should do?

**Comment by Didayolo** [comment]
Hi, please send an email to [info@codalab.org](mailto:info@codalab.org) with a clear username change request:
* Send the email with the the same address you used to register to Codalab
* Tell your current username
* Tell your desired new username (and maybe an alternative in case it's already taken)

Thanks!
