### ISSUE TITLE
Showing results from different submissions in the leaderboard

### ISSUE THREAD

**Issue by luischir** [codalab/codalab-competitions#2895]
Hi,

Our competition (https://competitions.codalab.org/competitions/27446) has 4 substaks and we added several leaderboard tables to show the results for each subtask. However, participants can only show the result of one submission, so if they show the submission that has the top result for task 1, it does not necessarily shows their best result for task 2 (which might be in another submission). We can see these differences comparing the results from the submissions CSV and the leaderboard.

We could not find a way to configure the leaderboard so that it shows the best results for some task in any submission for the same participant. Is there a way to do it?

Thanks!

**Comment by Didayolo** [comment]
Hi,

I know it's possible to configure the leaderboard to rank submissions by the average rank on all tasks.

However, I'm not sure if you can combine results from several submissions. 
It is results or code submissions? What prevent participants to group their best output from all tasks in one submission?

Maybe you could solve this by using several phases, one phase for each task.

**Comment by luischir** [comment]
We already have completed the evaluation phase of the competition that included all four subtasks, so we cannot change the phases now.

We suggested the participants to create a final submission with the best results for each subtask, but not all of them did, so the top scores for participants in the leaderboard are different from the top scores considering all their submissions.

**Comment by Didayolo** [comment]
I don't think so.

Sorry for replying so late; I guess it's already passed.
Of course you can always compute your post-challenge analysis locally.
Feel free to re-open the issue if needed.
