### ISSUE TITLE
Main queue congested

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2896]
The production queue is congestion. We'll flush it as soon as possible.

**Comment by YiqunChen1999** [comment]
![Screenshot 2021-02-06 151413](https://user-images.githubusercontent.com/47789930/107111830-0d236400-688e-11eb-8353-187aca93c30b.png)

Hi, did you solve it? The status of my submission is still Submitting.

**Comment by Parskatt** [comment]
Same here

**Comment by Didayolo** [comment]
Solved, now we just need to wait.
