### ISSUE TITLE
Website security certificate of Codalab  has expired

### ISSUE THREAD

**Issue by YYlvsy** [codalab/codalab-competitions#2897]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant:
-----------------------------------

1. This Github repository is about the **platform** itself.
2. If you problem is specific to a competition, **please contact directly its organizers**.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `eric2` and `tthomas63` as admins to your competition so they may access it.
2. Please post a link to your competition.

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!

**Comment by RenYang-home** [comment]
I am an organizer of the competitions https://competitions.codalab.org/competitions/28033, https://competitions.codalab.org/competitions/28034, https://competitions.codalab.org/competitions/28035

1. I am experiencing "Website security certificate of Codalab has expired" when opening the webpage;
2. All submissions from yesterday are stuck into "submitting" for a long time. 

Are there some errors in the Codalab server and is there any suggestion to fix it?

Thanks a lot.

**Comment by akutuzov** [comment]
The HTTPS certificate for the `competitions.codalab.org` server has indeed expired two days ago.
@ckcollab any hope of updating the certificate?

**Comment by Didayolo** [comment]
Solved.

**Comment by akutuzov** [comment]
Now the certificate is revoked.
As a result, Codalab works in Chromium, but not in Mozilla Firefox.

What is happening? :)
