### ISSUE TITLE
Stuck at "submitting"

### ISSUE THREAD

**Issue by LukeKeywalker** [codalab/codalab-competitions#2898]
Hello, 

I might have broken the submission queue - I was sending my first submission from Linux system and I have uploaded a gzip file which had been renamed to .zip, and the status is stuck in "submitting" for few hours now. Now I don't know if I should eventually get the "wrong format" status or it is stuck due to congestion.

Should I wait? Could this queue be somehow flushed so I can at least upload file in a correct format?

Thanks and best regards,
Lucas

EDIT: username ecstatic_shockley

**Comment by zx1239856** [comment]
Same here. It seems the issue is related to congestion since I uploaded valid zip files yet still stuck at submitting.

**Comment by RenYang-home** [comment]
The same here. Stuck in submitting for more than 1 day

**Comment by weiyaowang** [comment]
Same here

**Comment by fajri91** [comment]
Same here. Get stuck.

**Comment by YiqunChen1999** [comment]
Same here.

**Comment by GingerCohle** [comment]
same here.

**Comment by last-one** [comment]
same here.

**Comment by KailinLi** [comment]
Same here.

**Comment by ZhouJunyu9102** [comment]
Same here.

**Comment by z-x-yang** [comment]
Same here.

**Comment by dahiyaaneesh** [comment]
Same here.

**Comment by YYlvsy** [comment]
Same here.

**Comment by chiyuzhang94** [comment]
Same here.

**Comment by caihaunqai** [comment]
same here .from 2.6

**Comment by Hansxsourse** [comment]
same as me

**Comment by csEntr** [comment]
same here .from 2.5

**Comment by wuch15** [comment]
+1

**Comment by YanLiang1102** [comment]
same here.

**Comment by YanLiang1102** [comment]
@Didayolo could you please give us any updates on the flushing of queue? thanks a lot.

**Comment by chenwydj** [comment]
Same here

**Comment by Didayolo** [comment]
During the week-end the queue was staling. Now the problem is solved.
One hour after the resolution the queue was entirely flushed but then ~ 6000 jobs were launched...
Therefore, the submissions are getting processed now, please be patient.

**Comment by Didayolo** [comment]
It's totally solved, thank you for your patience.

**Comment by caihaunqai** [comment]
YES，but it changed to stuck at "submitted". Sad




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codalab/codalab-competitions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 晚上9:33
收件人:&nbsp;"codalab/codalab-competitions"<codalab-competitions@noreply.github.com&gt;;
抄送:&nbsp;"蔡焕洽"<369454780@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [codalab/codalab-competitions] Stuck at "submitting" (#2898)





 
It's totally solved, thank you for your patience.

**Comment by u1095279221321** [comment]
Has this problem been solved？

**Comment by caihaunqai** [comment]
Yes，thank you



---Original---
