### ISSUE TITLE
Email system doesn't work

### ISSUE THREAD

**Issue by boyuanzheng010** [codalab/codalab-competitions#2899]
I am one of the organizers of SemEval-2021 Task-4: https://competitions.codalab.org/competitions/26153
I can not send email to all participants using the email system of codalab. I can successfully sent email to all participants before Feb 5th and I mainly use this function to communicate with participants. However, the email system doesn't work when I tried to sent email to all participants on Feb 5th and Feb 7th, Feb 8th, but it seems all my emails can not be sent successfully. 

I am wondring could you please fix this problem?

**Comment by Didayolo** [comment]
I think this was due to the SSL certificate error we've solved today.
Please re-try and keep us updated.
