### ISSUE TITLE
Download csv option

### ISSUE THREAD

**Issue by ncg-task** [codalab/codalab-competitions#2902]
Greetings

I would like to report this issue. The excel sheet download option isn't downloading the precise leaderboard for us. 

This is our competition https://competitions.codalab.org/competitions/25680 . As an example and for data comparison purposes, I attach the downloaded file in a zipped folder for our Evaluation Phase 1: End-to-end Pipeline.

[Evaluation-phase1.zip](https://github.com/codalab/codalab-competitions/files/5957114/Evaluation-phase1.zip)

Happy to receive any tips on how we can download our leaderboard data otherwise.

Best wishes

**Comment by Didayolo** [comment]
Hi,

Sorry for the late reply. Thank you for reporting this bug. 

> Happy to receive any tips on how we can download our leaderboard data otherwise.

Unfortunately, I don't have much idea about how to do this.

**Comment by Didayolo** [comment]
Merged issue.
