### ISSUE TITLE
Revoking teams/team members does not work

### ISSUE THREAD

**Issue by rbouadjenek** [codalab/codalab-competitions#2903]
Hi,

I'm the organizer of a competition (admin 'rbouadjenek'): 
https://competitions.codalab.org/competitions/27191?secret_key=f0a7cc3e-7f78-4bb1-8564-95bc2fadafa5

I allow teams in my competition, but I noticed that the team "Revoke" button does not work. Is it possible to check if that's a bug? I have also noticed many issues with the team feature that I can detail later.

<img width="1237" alt="Screen Shot 2021-02-11 at 10 47 59 am" src="https://user-images.githubusercontent.com/7735263/107587879-b4214a80-6c56-11eb-9693-ad25bb7e6220.png">

Similarly, the "Revoke" team member does not work properly:

<img width="1214" alt="Screen Shot 2021-02-11 at 10 51 34 am" src="https://user-images.githubusercontent.com/7735263/107588107-25f99400-6c57-11eb-90f4-6a1b0727b6c3.png">

Cheers,
reda

**Comment by Didayolo** [comment]
It's seems like it is a bug, also reported here #2893 and here #2880

Some work-around were done:
* > We asked the participants to create new teams and it worked.
* > For now we just made forming teams optional and let individual users also make submission. I'll close the issue.

The bug still needs to be corrected.
