### ISSUE TITLE
How to change the username?

### ISSUE THREAD

**Issue by jiangzhengkai** [codalab/codalab-competitions#2905]
Hi, I want to ask how to change the username? or How can i delete the account?

**Comment by Didayolo** [comment]
Hi,
To request a username change or an account deletion, please send an email to: [info@codalab.org](mailto:info@codalab.org)

Be specific in your request (include your current username, the wanted username, maybe an alternative in the case it's already taken...). Also, you must send the email with the address you used to register to Codalab.
