### ISSUE TITLE
Certificate is revoked

### ISSUE THREAD

**Issue by xinsu626** [codalab/codalab-competitions#2906]
If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using? MacOS: Safari and Chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using! I couldn't access the https://competitions.codalab.org website. And got the following error: This connection is not private. It seems the certificate is revoked.

**Comment by dimartinot** [comment]
Chrome Desktop seems to work for me. Firefox Nightly & Safari don't.

**Comment by almeidaraul** [comment]
Same issue on Firefox

**Comment by dustalov** [comment]
Same issue on Safari and Firefox. I reported this in the mailing list a few days ago.

<img width="1888" alt="CodaLab Google Group" src="https://user-images.githubusercontent.com/40397/108631258-fc701200-7479-11eb-8c6b-8110d2de7970.png">

...but only now after accidental scrolling of the top `div` I noticed that the bugs should be reported on GitHub.

<img width="1888" alt="CodaLab Google Group" src="https://user-images.githubusercontent.com/40397/108631277-16a9f000-747a-11eb-95f5-5c750d37ea03.png">

**Comment by JustGlowing** [comment]
Chrome and Safari desktop don't allow me to see the website while Chrome on my phone does.

**Comment by Didayolo** [comment]
We should be able to resolve this tomorrow (Monday). In the meantime you can use Chrome. Thank you for your patience!

**Comment by lxtGH** [comment]
I meet the same error.

**Comment by ShiKangdi** [comment]
I can't visit the website on my MAC os. but it works on the windows. Both use Chrome.

**Comment by yangchris11** [comment]
All browsers failing to visit the site on mac (safari, firefox, chrome).

**Comment by hehao13** [comment]
Same issue on Safari and Chrome, both Mac and pad.

**Comment by RuiTan** [comment]
Same issue using Safari and Chrome on Mac..
And HTML page can be loaded using Maxthon, but some `.css` and `.js` resources fail to load.
![image](https://user-images.githubusercontent.com/10294391/108798646-4287bb80-75c9-11eb-920b-2abb159e0529.png)

**Comment by Didayolo** [comment]
This should be solved now. Please re-open if needed.
