### ISSUE TITLE
Secure connection failed: Error code: SEC_ERROR_REVOKED_CERTIFICATE

### ISSUE THREAD

**Issue by manuvinakurike** [codalab/codalab-competitions#2907]
Hi, 

We're creating a shared task and are having access issues for some users. While, some of us can access the competitions page a few are facing issues opening the link. Please find the snapshot of the error some users are facing. 

![Screenshot from 2021-02-22 19-57-10](https://user-images.githubusercontent.com/24532990/108803453-8ccc5680-754f-11eb-8431-531816b334be.png)

Please let me know how to resolve this issue. I could resolve this error by disabling the certificates option as shown below, our participants might not want to do that. Any help will be appreciated. Thanks. 

![sa](https://user-images.githubusercontent.com/24532990/108803636-02d0bd80-7550-11eb-9f2c-e8cf2a5269a1.png)

Competition link is : https://competitions.codalab.org/competitions/28109

**Comment by Didayolo** [comment]
The issue should be solved now.

**Comment by dimartinot** [comment]
I confirm, working for me on Firefox Nightly Desktop
