### ISSUE TITLE
The CodaLab site is currently unavailable.

### ISSUE THREAD

**Issue by norahollenstein** [codalab/codalab-competitions#2911]
Hi,

I was trying to editing our competition site and now I cannot access it anymore. I get the following error with this URL: https://competitions.codalab.org/competitions/28176 

```
The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.

Please try again later.
```

As we are currently in the evaluation phase, I would appreciate your help as soon as possible.
Thanks,
Nora

**Comment by bomb2peng** [comment]
Hi,
We are facing the same problem. We are currently preparing a competition. Hope the Codalab team solve this soon.
Thanks!

**Comment by bomb2peng** [comment]
> Hi,
> We are facing the same problem. We are currently preparing a competition. Hope the Codalab team solve this soon.
> https://competitions.codalab.org/competitions/29339?secret_key=6d3709ab-26df-4d26-88c0-2277ec2cfc91
> Thanks!

Actually, we are experiencing this error more early, at about 3 hours ago. The initial cause is changing the compute worker queue in the editor. After that any submit of editor change causes "unavailable". Moreover, even creating a new competition by uploading a bundle causes failures. I conjecture this bug is triggered by modifying worker queue, or some problem in worker queue caused this.
best regards!

**Comment by akutuzov** [comment]
Same here:
https://competitions.codalab.org/competitions/28340

We are also in the evaluation phase, so this is really unfortunate.

@Didayolo can we expect this to be solved soon, or is it safer for us to extend the evaluation phase?

**Comment by hsd31196** [comment]
Same here:
https://competitions.codalab.org/competitions/26979

We are not able to edit the competition and shows following error:

> The CodaLab site is currently unavailable.
> Sorry, the page you are looking for is currently unavailable.
> 
> Please try again later.

**Comment by Didayolo** [comment]
Dear all,

It should be back now. However, we are still doing the data migration to the bigger storage so you may still face issues in the near future.

Thank you for your comprehension!
