### ISSUE TITLE
Unable to download dataset

### ISSUE THREAD

**Issue by shoumikdey** [codalab/codalab-competitions#2912]
Hi, I am unable to download the SIDD dataset (https://competitions.codalab.org/competitions/22230#participate) given at this link. I get the following error message, "There was an error retrieving the file. Please try again later or report the issue." Is there any problem with the server?

I tried downloading the files both via Chrome and Firefox, no luck.

I could download the files yesterday, but I am unable to do so today.

**Comment by Didayolo** [comment]
Hi,

We were running a big maintenance operation. Please try again and come back to us.
