### ISSUE TITLE
Detailed results not showing. What is correct directory to put the detailed results html file?

### ISSUE THREAD

**Issue by bomb2peng** [codalab/codalab-competitions#2916]
Hello. It seems the detailed results feature is not working. When I click on the detailed results link, the open webpage gives blank contents.
I also found two different saving directories for the html file in the examples or documentations. One is the "output_dir/scores.html" as shown in the [iris competition example](https://github.com/codalab/competition-examples/blob/master/basic-competition-bundles/Iris/iris_competition_bundle/scoring_program/score.py), and the other one is "output_dir/html/detailed_results.html" as shown in[ this documentation](https://github.com/codalab/codalab-competitions/wiki/User_DetailedResultsPage).  I have tried the two directories to save my detailed result html file, but none is working. Please shed some light one this problem. Thanks!
https://competitions.codalab.org/competitions/29586#results

**Comment by swook** [comment]
It should still be `scores.html` but due to the duplicate issue at #2887 the page is currently not visible.

I too am waiting for a solution...
