### ISSUE TITLE
Unable to download submission ZIP file

### ISSUE THREAD

**Issue by norahollenstein** [codalab/codalab-competitions#2917]
Hi,

As an organizer of our competition, I cannot download some of the submission ZIP files.
Competition link: https://competitions.codalab.org/competitions/28176 
Example of a working download link: https://competitions.codalab.org/my/competition/submission/813117/input.zip
Example of a broken download link: https://competitions.codalab.org/my/competition/submission/815286/input.zip 

I am using the lates version of the Chrome browser. I get the same issue in Safari.
I am not able to download approx. 60% of all submission.

Thanks for addressing this,
Nora

**Comment by norahollenstein** [comment]
They are all recent, from yesterday or today.

**Comment by norahollenstein** [comment]
This seems to be resolved, was able to download all files now.

**Comment by Didayolo** [comment]
Great :-)
