### ISSUE TITLE
Unable to Edit Existing Competitions or Upload New Bundles

### ISSUE THREAD

**Issue by alexlascelles** [codalab/codalab-competitions#2925]
I have been trying to edit two competitions that I have set up here:
https://competitions.codalab.org/competitions/30317?secret_key=6d47e98f-2b9f-47d2-8662-b0c99f8714b7
https://competitions.codalab.org/competitions/30316?secret_key=63bb175f-3e18-4ded-8453-61d6feaa5985

When I click Edit under Admin Features, I am able to change and submit some edits to the page, but these changes are not updated when I return to the competition page. Additionally, I have not even been able to upload a new competition bundle with the changes to the htmls that I wanted to make (I get an error popup saying:"competitions.codalab.org says: Sorry, failed to upload file."). 

I am using Chrome Version 89.0.4389.90 (Official Build) (64-bit).

Might it be related to the alert on the homepage saying Codalab is short on storage space?

Thanks, let me know if you need any more information, hope to hear back soon!

**Comment by Didayolo** [comment]
Sorry for the lack of reply. 

This is sometimes due to a problem in the setting of the competition, thus preventing to save the edits.

The only way to trouble-shoot this is to double-check everything in your competition bundle / editor.
