### ISSUE TITLE
File upload not working.

### ISSUE THREAD

**Issue by Pranshu-Bahadur** [codalab/codalab-competitions#2926]
Hey,
I've been trying to upload a submission for a while now but I keep getting a "Sorry, failed to upload file" dialog box.
This happened yesterday around this time as well. However, later in the day it worked fine. 
Is there a problem with the servers during this time?

(I have tried Firefox and google-chrome browsers on multiple systems.)

Thank you!
PS: sorry for not following the template...

**Comment by 232525** [comment]
+1

**Comment by alexlascelles** [comment]
+1

**Comment by Philharmy-Wang** [comment]
+1

**Comment by Didayolo** [comment]
Thanks for reporting, please re-open if you face the issue again.
