### ISSUE TITLE
Submission stuck on submitted

### ISSUE THREAD

**Issue by Pranshu-Bahadur** [codalab/codalab-competitions#2931]
Hey,
I have tried to submit my results on a competition dataset using firefox & chrome browsers, however my submission is stuck on submitted for more than an hour now.
Kindly advise.

(PS: Sorry again for not following template, I will provide any additional details you need)

Thank you!

**Comment by hareshg** [comment]
I am facing same issue, seems some problem with codalab.

**Comment by Ayushk4** [comment]
I am also facing the same issue. My submission is showing at `submitted` for since about four hours when it takes less than a minute to run the script.

**Comment by hwh-hit** [comment]
Save issue here.

**Comment by Pranshu-Bahadur** [comment]
Did it work for anyone yet?

**Comment by hwh-hit** [comment]
No, It still doesn't work. Maybe three hours later, I guess.

**Comment by christianayala10** [comment]
Same issue here!

**Comment by hwh-hit** [comment]
The bug may has been fixed, It works now.

**Comment by christianayala10** [comment]
The "submitted" solutions will change to "finished" or should I upload the solution another time?

**Comment by hwh-hit** [comment]
submitted->running.>finished

**Comment by Pranshu-Bahadur** [comment]
It very slow though. Submission I did in the morning just ran. I did another now...don't know how long it'll take.
