### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by WangBoying** [codalab/codalab-competitions#2932]
I tried to upload our zip file, but the website kept showing that the upload failed.

**Comment by Chamindabandara** [comment]
I'm also experiencing the same thing...

**Comment by jabanto22** [comment]
Same here, been trying to upload 6KB zip file for hours and it keeps on failing.

**Comment by z-x-yang** [comment]
Same here.

**Comment by christianayala10** [comment]
Same here

**Comment by WangBoying** [comment]
@Didayolo

**Comment by L-Hugh** [comment]
Same here.

**Comment by lilaspourpre** [comment]
Same here

**Comment by Didayolo** [comment]
Hi all,

It seems to be resolved now.
