### ISSUE TITLE
Sorry, failed to upload file.

### ISSUE THREAD

**Issue by coder-people** [codalab/codalab-competitions#2934]
I can't submit my results to platform to get scores about Leaf Segmentation Challenge (LSC)

**Comment by sappy5678** [comment]
I submit to https://competitions.codalab.org/competitions/20228
and it has same problem

**Comment by Mindful** [comment]
Same issue on the BEA-2019 shared task test set.

**Comment by lilaspourpre** [comment]
same here

**Comment by neeek2303** [comment]
I cant submit to competitions #30517

**Comment by christianayala10** [comment]
same here

**Comment by Didayolo** [comment]
Is this resolved already?
