### ISSUE TITLE
CAp21/Criteo challenge: problems in submitting file

### ISSUE THREAD

**Issue by fgranese** [codalab/codalab-competitions#2936]
Hello,
 
when I try to submit the zip file with the results, the sending status remains on 'Submitting' and when I click on 'Download output from scoring step' I get the error 404.

I had no problems yesterday.

Thanks,
Federica

**Comment by christianayala10** [comment]
same here

**Comment by z-x-yang** [comment]
Same here. It seems that submission problems have happened more frequently in recent days.

**Comment by fgranese** [comment]
Now seems to be working!
