### ISSUE TITLE
Compute worker not recognizing when ingestion program exits

### ISSUE THREAD

**Issue by RobGeada** [codalab/codalab-competitions#2938]
I'm organizing this competition: https://competitions.codalab.org/competitions/29853
As of about a week or two ago, it seems like the competitions-v1-compute-worker is failing to recognize when the ingestion_program finishes. I can monitor the ingestion_program worker, and despite the ingestion_program finishing succesfully and exiting, the compute-worker logs still show:
 `[2021-04-27 12:23:48,486: INFO/Worker-1] Checking process, exit_code = None`.  

A new ingestion program image is then created and runs the next submission, despite the previous submission never transitioning to scoring. Therefore in our submission queue we see a lot of "Running" submissions, none of which score until they time out and fail. For example, submission 868157 ran through the full ingestion program but never transitioned to scoring, and then submission 868170 began running before ingestion was completed. Is there a change that happened to CodaLab in the last few weeks that could have caused this? Our entire competition has broken despite running fine beforehand. 

Thanks,
Rob

**Comment by RobGeada** [comment]
Here's the log of our compute worker. We have some successful submissions, a failed submission, and then the next submission after the failed one exhibits this problem where the scoring program never starts. 
[nascomp_logfile.txt](https://github.com/codalab/codalab-competitions/files/6384895/nascomp_logfile.txt)

**Comment by Didayolo** [comment]
Hi, thank you for reporting this bug.

* It is systematic? In other words, do you have this problem for every submission?
* Can you confirm that you didn't change anything in your challenge before the issue begins to occur?

**Comment by RobGeada** [comment]
Hi Adrien,

The issue occurs seemingly at random, but never when there is only a single submission in the queue. That is, when the submission being ingested is the only non-failed submission in the queue, it exits succesfully. When there are other submissiosn in the queue, the next submission begins to ingest before the original one scores.

We tried to shift the competition to a different queue, which is when we started noticing issues.  Switching back to the original queue did not resolve the issue, nor did restarting the worker in either queue.

**Comment by Didayolo** [comment]
Thanks for the precision. I had the same issue with a recent competition I organized
We'll investigate this problem.

**Comment by RobGeada** [comment]
We've tried the second one a couple of times, both restarting the actual machine as well as the docker images. I can try the first one later today.

**Comment by RobGeada** [comment]
Trying to create a small clone of the competition, and I'm currently unable to create a competition dump, upload a new competition, or submit anything to my current competition. Is this a known issue at the moment?

**Comment by Didayolo** [comment]
> Trying to create a small clone of the competition, and I'm currently unable to create a competition dump, upload a new competition, or submit anything to my current competition. Is this a known issue at the moment?

I think the server was over-used and therefore slow down last week, it should be better now.

**Comment by Didayolo** [comment]
This bug is very hard to reproduce and never occurred, as far as I know, on the [new Python3 server](https://codalab.lisn.fr/).

The problem seems to be linked with "huge" submissions that needs a lot of time to compute.

Hopefully we won't see it again in the future. If it's the case, let's re-open this issue.
