### ISSUE TITLE
Unable to submit run

### ISSUE THREAD

**Issue by Gautamshahi** [codalab/codalab-competitions#2939]
Hello,

I have created a competition https://competitions.codalab.org/competitions/31238.

But task 3A is closed, and no submission is allowed; please have a look at  https://competitions.codalab.org/competitions/31238#participate-submit_results.

![image](https://user-images.githubusercontent.com/3966230/116775301-f4d37780-aa7f-11eb-9f13-35acae5fe951.png)

The end date for both tasks is May 8, 2021, 9:59 a.m. UTC.

How should I resolve the issue?

Any help will be highly appreciated. 

Regards,
Gautam

**Comment by Didayolo** [comment]
Hi,

I've just requested to enter the challenge so I can see the "Submit / View Results" page.

> The end date for both tasks is May 8, 2021, 9:59 a.m. UTC.

I guess the start date is also well set up?

**Comment by Didayolo** [comment]
By looking at your competition, it seems to be solved.
