### ISSUE TITLE
wizard not working with 404 error

### ISSUE THREAD

**Issue by ShuangjunLiu** [codalab/codalab-competitions#2941]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant:
-----------------------------------
1. This Github repository is about the **platform** itself.  -> yes 
2. If you problem is specific to a competition, **please contact directly its organizers**.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` and `tthomas63` as admins to your competition so they may access it.
2. Please post a link to your competition.

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
chrome version 90.0.4430.93 (Official Build) (64-bit)
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://chalab.lri.fr/

reproduce:
click login, 404 error.

**Comment by Didayolo** [comment]
Hi, 
Sorry I think this wizard is out of date.
To create a competition, please refer to [Codalab's Wiki](https://github.com/codalab/codalab-competitions/wiki), section 2.
