### ISSUE TITLE
What python packages are available in the default docker image? How to check?

### ISSUE THREAD

**Issue by ShuangjunLiu** [codalab/codalab-competitions#2942]
I plan to write a score program yet not sure what packages are available.  

> "Default docker: if not special docker is specified, submissions are run in codalab/codalab-legacy the default docker, which can be found on Github." (https://github.com/codalab/codalab-competitions/wiki)

There are several images in that repo (py, py3, py37, pygpu, py-env...), which one is the "default" docker image? 

If I would like to read a json file contains the result, is json available in your docker? 
In case a pkg is not available, how can I know that? Is there error message I can check when run on your instance? 

If this is not a good place to ask these questions, is there a forum where we can learn these details?

**Comment by Didayolo** [comment]
Hi,

I think be default the image is `codalab/codalab-legacy:latest`.

You can specify by yourself in the EDIT menu or YAML file of your competition another docker image (field named `competition docker image`). I suggest you try `codalab/codalab-legacy:py37`.

You can check what's inside a docker image by using `docker run` command to enter the environment and check for yourself. If you don't know how Docker works, please refer to Docker's documentation.
You can also "fork" this image to add whatever library you want and save it as a new docker image under your own DockerHub account.

> If this is not a good place to ask these questions, is there a forum where we can learn these details?

No problem, it's a good place to ask.

**Comment by ShuangjunLiu** [comment]
Thanks.  
I checked the docker image that json is included.
