### ISSUE TITLE
Codalab.org not refreshing "Status"

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#2943]
Suddenly (this morning) when competitors are submitting entries the status is not refreshing. The system seems to be frozen. 

See e.g. https://competitions.codalab.org/competitions/30686#participate-submit_results

**Comment by olyerickson** [comment]
Perhaps it is just insanely slow...A student's submission from hours ago finally showed up.

**Comment by Didayolo** [comment]
I just realized that 8 workers got shut down. I'll set up new workers later in the day and the problem should be solved.

**Comment by Didayolo** [comment]
I already add one new worker and the queue is not congested anymore. I'll add more soon.
