### ISSUE TITLE
nginx 504 gateway timeout on all Competition pages

### ISSUE THREAD

**Issue by alexlascelles** [codalab/codalab-competitions#2944]
Is anyone else showing 504 Gateway Time-Out on the competitions URL and for any sub-URLs like for my personal competitions https://competitions.codalab.org/  and https://competitions.codalab.org/competitions/30937 ?

I am seeing this on Chrome on windows and android phone

**Comment by 2ndpic** [comment]
showing 504 Gateway on the competitions URL too, but worksheetsURL works fine,what happends
