### ISSUE TITLE
Jobs stuck in "Submitting", main queue is congested

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#2947]
Codalab's main queue is currently congested, and as a results all submissions are stuck in "Submitting" status.

Please avoid submitting again while the problem persists. We are trying to solve it as soon as possible.

**Comment by priyas1729** [comment]
Submission failed. Kindly allow me to resubmit.

**Comment by Didayolo** [comment]
> Submission failed. Kindly allow me to resubmit.

No problem, you can use the platform normally.
