### ISSUE TITLE
why my submission status is always 'Submitted'?

### ISSUE THREAD

**Issue by qingzhiwu** [codalab/codalab-competitions#2950]
hi, Excuse me,
I submitted my results to codalab yesterday, but the status is still 'Submitted'.  

Is the bug fixed? 
 Is my submission still valid and will be evaluated?

**Comment by Didayolo** [comment]
I think it was because a queue congestion. It is working now?

**Comment by rosenhahn** [comment]
My submission has the status "submitted" since 12th May.
