### ISSUE TITLE
two subtask in one competitions 

### ISSUE THREAD

**Issue by aliebi** [codalab/codalab-competitions#2951]
I have created a new competition, and I want to have two subtasks with two different datasets so that participants can participate for whichever they like.
And the final results are displayed in two leaderboard columns.
Is it possible? I did not find anything in the document, please help

**Comment by Didayolo** [comment]
Hi,

Yes, it is totally doable. You need to setup this behavior in the `competition.yaml` file (and in the ingestion and/or scoring program as well).

You can find an example here: [Leaderboard configuration](https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard)
And here: [YAML configuration](https://github.com/codalab/codalab-competitions/wiki/Organizer_Codalab-competition-YAML-definition-language)

I hope this helps.

**Comment by aliebi** [comment]
thanks!

**Comment by chiyuzhang94** [comment]
Hi @aliebrahiiimi ,

Did you successfully achieve this function? If so, could you share your bundle with me?
Thanks! 

Best,
Chiyu
