### ISSUE TITLE
Add columns to leaderboard / Detailed results not showing

### ISSUE THREAD

**Issue by svc2021bida** [codalab/codalab-competitions#2952]
Hello,
I want to add 2 new columns to my leaderboard but I see that using the editor is impossible.
Could you help me to add those 2 columns?
The competition I have created is this one:

[https://competitions.codalab.org/competitions/27295](url)

Since I have not been able to add those 2 columns, I would like to be able to activate the DETAILED RESULTS option.
I have tried to add it through code and the file is generated correctly together with the scores.txt file but when I click on the link nothing is shown.

**Comment by Didayolo** [comment]
Hi,

Indeed, unfortunately to edit the leaderboard columns you need to re-upload the bundle.

Regarding detailed results, this problem has been reported recently (#2887, #2961). We'll try to look into it soon.

**Comment by svc2021bida** [comment]
But is it possible for you to do anything if I give you administrator permission?

**Comment by Didayolo** [comment]
Unfortunately it is a new bug that, as it seems, was introduced recently and I don't know how to fix it yet.
