### ISSUE TITLE
Update column labels in leaderboard

### ISSUE THREAD

**Issue by jbehley** [codalab/codalab-competitions#2953]
I currently try to update the column labels of the leaderboard of already created competition:

![image](https://user-images.githubusercontent.com/11506664/118494157-2441df80-b722-11eb-88cc-4f8573715aca.png)

But the change is unfortunately not reflected in the leaderboard:

![image](https://user-images.githubusercontent.com/11506664/118494257-420f4480-b722-11eb-9580-89a16403f6bc.png)

Thanks in advance!

**Comment by Didayolo** [comment]
Hi,

Yes, unfortunately this is a known bug... basically everything can be easily updated through the editor expect the leaderboard (column names, scores, etc.).

You may need to re-upload the bundle with an updated YAML file.

**Comment by shreyashampali** [comment]
Hi @Didayolo ,
1. Could you please tell me how to re-upload the bundle in an existing competition as I couldnt find this option?
2. Does reuploading the bundle remove all the participants or delete the leaderboard entries?
thanks!
