### ISSUE TITLE
systematic failures with a python2.7 message starting May 17th

### ISSUE THREAD

**Issue by oddskool** [codalab/codalab-competitions#2954]
Hello,

We notice on our competition systematic failures starting today May 17th.

The error message is always the following:

`Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 164, in get_bundle
    metadata = yaml.load(mf)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/lib/python2.7/site-packages/yaml/reader.py", line 165, in update
    exc.encoding, exc.reason)
ReaderError: 'utf8' codec can't decode byte #xb1: invalid start byte
  in "/tmp/codalab/tmpVA0cMc/run/input/ref/metadata", position 12
`

The competition is this one: https://competitions.codalab.org/competitions/31485

We thought it was related to some change on our side, but after changing the docker image it doesn't fix so we suspect it is related to Codalab platform.

(And btw, thanks for this wonderful platform !)

**Comment by oddskool** [comment]
I've added  `pavao` and `tthomas63` as admins fwiw.

**Comment by Didayolo** [comment]
Hi,

* Is the error systematic? (i.e. happening on every submission)
* Are you using the default worker queue?

Thanks for the kind words!

**Comment by oddskool** [comment]
Yes it is systematic.

We used to have the default queue.

We changed to a private queue this afternoon but it didn't fix anything.

-------- Message d'origine --------

**Comment by oddskool** [comment]
So I think we found the problem: a new reference bundle with additional data was uploaded and its filename didn't end in ".zip"
Probably the code didn't guess that it should be unzipped.

**Comment by oddskool** [comment]
We also configured a new queue so as not to congest the default.
Closing issue for now.
