### ISSUE TITLE
IoU in evaluate program shows 0.00 as result whereas locally with same data it shows 0.65

### ISSUE THREAD

**Issue by anjukgp** [codalab/codalab-competitions#2957]
I am making a codalab bundle and following the evaluate program i wrote for handling results.But the problem is that IoU in evaluate program shows 0.00 as result with the codalab whereas locally with same data and code it shows 0.65

#!/usr/bin/env python
import sys
import os
import os.path
import numpy as np

'''
Takes result and reference images in '.npy' format.
Use np.save and np.load to save and load the images.
Use it for showing results of your neural networks in ML/DL projects. 
After calculating IoU of result versus true answer a IoU is calculated and put in the scores section
'''

def intersection_of_union(im1, im2):
    i = np.logical_and(im1, im2)
    u = np.logical_or(im1, im2)
    return i.sum() / u.sum()
    

input_dir = sys.argv[1]
output_dir = sys.argv[2]

submit_dir = os.path.join(input_dir, 'res')
truth_dir = os.path.join(input_dir, 'ref')

if not os.path.isdir(submit_dir):
    print "%s doesn't exist" % submit_dir

if os.path.isdir(submit_dir) and os.path.isdir(truth_dir):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    output_filename = os.path.join(output_dir, 'scores.txt')
    output_file = open(output_filename, 'w')

    truth_file = os.path.join(truth_dir, "ref_imgds.npy")
    #truth = open(truth_file).read()
    submission_answer_file = os.path.join(submit_dir, "out_imgds.npy")
    x_train=[]
    im = np.load(submission_answer_file)
    ref = np.load(truth_file)
    im = np.array(im)
    ref = np.array(ref)
    x_train.append(im)
    imgset=np.array(im)
    refset=np.array(ref)
    iou = intersection_of_union(imgset,refset)
    output_file.write("IoU:%f \r\n" % (intersection_of_union(imgset,refset)))
    output_file.close()

**Comment by Didayolo** [comment]
Hi,

In your `competition.yaml` file, is your leaderboard configured to consider the score labeled "IoU"?

It would be something like this:
```yaml
# Leaderboard
leaderboard:
  columns:
    IoU:
      label: Intersection of union
      leaderboard: *id001
      numeric_format: 4
      rank: 1
leaderboards:
  Results: *id001
```

**Comment by Abajpai1** [comment]
I have changed the docker image to python 3 then it is giving correct results else it was giving Floor value of division so always 0.
