### ISSUE TITLE
Different columns in leaderboards for different phase

### ISSUE THREAD

**Issue by yinanhe** [codalab/codalab-competitions#2963]
Hello, I have created a new competition, and I want to have three phases with different task so that participants can participate for whichever they like. And the final results with different columns (like "AUC" in phase1 while "Accuracy" in phase2)  are displayed in three leaderboard columns.
Is it possible? I found the document in https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard , but it seems the columns of three phases should be same.
Looking for your reply~

**Comment by loicsarrazin** [comment]
Hi @yinanhe  
Based from the architecture of a competition, there is no way to do that. You need the same results label for each phase.

**Comment by zhuanjiao2222** [comment]
Hi,
Now is it possible to implement different leaderboards (with different columns) for different phases?
