### ISSUE TITLE
Unable to connect to competitions-test.codalab.org to run test submission

### ISSUE THREAD

**Issue by christianjans** [codalab/codalab-competitions#2964]
Hello,

I am currently trying to test my scoring program on CodaLab with a test submission. I found https://codalab-competitions.readthedocs.io/en/latest/Drills/ which seems to provide a way in which I can submit a test submission and view the scores on the leaderboard. In step 3 of these instructions, I try to connect to http://competitions-test.codalab.org/competitions/NNN#participate-submit_results (where I replace NNN with 33327, my competition number), but I am unable to connect to this site.

1. What browser and version are you using? Google Chrome 91.0.4472.114
2. What is the URL of the problem? http://competitions-test.codalab.org/competitions/NNN#participate-submit_results 

Also, are there other ways, or new ways now, to try out your scoring program?

Let me know if I can provide any more information.

Thanks so much for your help!

**Comment by Didayolo** [comment]
I think the URL [http://competitions-test.codalab.org](http://competitions-test.codalab.org) just represents any CodaLab instance.

You can just test your competition on the main instance of CodaLab, which is [https://competitions.codalab.org](https://competitions.codalab.org). You can keep your competition private if wanted.

I hope this helps!

**Comment by christianjans** [comment]
Oh sorry yes, it works from the main instance of CodaLab. Thank you!
