### ISSUE TITLE
Cannot assign admins to competition

### ISSUE THREAD

**Issue by rjbruin** [codalab/codalab-competitions#2966]
When I try to save the competition after editing in admins, the admins are not saved. When I click edit again, the names are gone. There doesn't seem to be anything wrong with the name selection itself: I can type a partial name, then click the name in the dropdown, and everything looks okay.

EDIT: [This is the competition](https://competitions.codalab.org/competitions/33420), but I've had the same issue with other competitions I'm running in parallel. I ran the same competitions last year, and didn't have this issue. Also, the other changes *are* saved.

**Comment by Didayolo** [comment]
Hi,

This is a surprising issue. 

Can you _try_ to add me as an administrator? My ID is `pavao`.

Of course it may not work... In that case:
- Can you provide me your Codalab ID?
- Do you mind if I enter the competition and the settings to have a look? (I won't change anything without asking first)

**Comment by rjbruin** [comment]
Hi,

For some reason, today, it works. :\ I can add any user I want, and now they are saved.

I don't know what is different today...

**Comment by Didayolo** [comment]
That's strange indeed. Thank you for reporting.
