### ISSUE TITLE
I receive failed submission status for QET 2021 Tasks 1 and 2

### ISSUE THREAD

**Issue by bicici** [codalab/codalab-competitions#2978]
I am a competition participant at QET 2021 tasks 1 and 2:
Task 1 Sentence-level Direct Assessment (https://competitions.codalab.org/competitions/33411)
Task 2 Sentence-level Post-Editing Effort (https://competitions.codalab.org/competitions/33412)

I contacted the organizers however the issue is not resolved and I still come across failed submissions.

RTM.zip is the attached file for the submission for Task1 en-zh
[RTM.zip](https://github.com/codalab/codalab-competitions/files/6916289/RTM.zip)
submitted at https://competitions.codalab.org/competitions/33411#participate-submit_results.

Thank you for your help.

**Comment by Didayolo** [comment]
Hello,

Could you solve this issue?

What is the bug encountered?

**Comment by bicici** [comment]
Hi Adrien,
The issue is not solved yet. All of my submissions returned "failed" status
for all subtasks I participated at QET 2021:

   - Task 1 Sentence-level Direct Assessment
   <https://competitions.codalab.org/competitions/33411>
   - Task 2 Sentence-level Post-Editing Effort
   <https://competitions.codalab.org/competitions/33412>
   - Task 3 Sentence-level Critical Error Detection
   <https://competitions.codalab.org/competitions/33414>

My results are not shown among the results tab and I am able to obtain the
scores by looking at the output.txt for the submission under the
participate tab (e.g. Download output from scoring step
<https://competitions.codalab.org/my/competition/submission/973301/output.zip>
).


Best Regards,
Ergun

**Comment by Didayolo** [comment]
Did you have a look at the logs of the submission?
Especially "scoring error" and "ingestion error" logs in case of a code submission challenge?

**Comment by bicici** [comment]
I checked the error logs.

############################################################################################################

stderr.txt (View scoring error log
<https://competitions.codalab.org/my/competition/submission/973280/stderr.txt>
,
https://competitions.codalab.org/my/competition/submission/973280/stderr.txt)
shows a warning:
WARNING: Your kernel does not support swap limit capabilities or the cgroup
is not mounted. Memory limited without swap.

############################################################################################################
stdout.txt (View scoring output log
<https://competitions.codalab.org/my/competition/submission/973280/stdout.txt>
,
https://competitions.codalab.org/my/competition/submission/973280/stdout.txt
) does not report any error (
https://competitions.codalab.org/competitions/33412#participate-submit_results
):
Loading goldlabels...
done.
Loading your predictions...
done.
Computing scores...
Computed the scores in 0.00749 seconds.
Writing in output file...
----
disk_footprint:61203283968
model_params:380
pearson:0.204601249121
pearson => better than baseline? no
mae:0.155808951218
rmse:0.228879652519
----
Done!

############################################################################################################

scores.txt in output_file.zip (
https://competitions.codalab.org/my/competition/submission/973280/output.zip)
shows scores:
disk_footprint:61203283968
model_params:380
pearson:0.204601249121
mae:0.155808951218
rmse:0.228879652519


Best Regards,
Ergun

Ergun Biçici
http://bicici.github.com/ <http://ergunbicici.blogspot.com/>

**Comment by Didayolo** [comment]
It is weird as the submission seem to work flawlessly. Did you contact the organizers?

**Comment by bicici** [comment]
Yes; the organizers are aware of the issue.

Best Regards,
Ergun

**Comment by Didayolo** [comment]
The issue is open again.

However it is really unclear that the problem comes from the code of CodaLab itself and not the competition's scoring program or the submission.

If I understand correctly, basically everything works fine but the submission is tagged as "Failed"?

**Comment by bicici** [comment]
My submissions are not shown among the results tab and they are not
included in the rankings and receive failed status. Competition's scoring
program appears to be without error according to the logs. The submission
file and the evaluation program appear to work fine but all of my
submissions this year are tagged as "Failed".

Resubmitting and testing with a submission of mine might help identify the
error. To check whether this is an issue related to my account, I
downloaded and re-submitted the same file for the competition in 2020
(expecting the same scores):
- ro-en,
https://competitions.codalab.org/competitions/24447#participate-submit_results,
35th submission
- en-de,
https://competitions.codalab.org/competitions/24515#participate-submit_results,
41th submission
- en-zh,
https://competitions.codalab.org/competitions/24515#participate-submit_results,
54th submission
However, I received "Submitted" status for all the three submissions.

Therefore, this appears to be a Codalab issue with not only on results in
the competition in 2021 but also now extending to the competition in 2020.

Best Regards,
Ergun

**Comment by bicici** [comment]
I obtained the same scores and "Finished" status for all three submissions
to the competition in 2020. Thus, submissions to previous year's challenge
are correctly graded.

Best Regards,
Ergun

**Comment by Didayolo** [comment]
Sorry that we couldn't help you more with your problem. Any update on this?

**Comment by bicici** [comment]
Nope. No new updates. Same issue dangling.

Best Regards,
Ergun
