### ISSUE TITLE
Password recovery error

### ISSUE THREAD

**Issue by tocodo** [codalab/codalab-competitions#2979]
When I used the password recovery functionality from https://codalab.lisn.fr/accounts/password/reset/, I get this error:

![image](https://user-images.githubusercontent.com/7440668/128192898-99544f44-ccae-4eab-9bbc-469d3b9c37ab.png)

My email address used is: nrjmobile.fluctuant@aleeas.com

**Comment by Didayolo** [comment]
Hello,

[https://codalab.lisn.fr/](https://codalab.lisn.fr/) instance is still under deployment.

The current public instance of CodaLab is [https://competitions.codalab.org/](https://competitions.codalab.org/).
