### ISSUE TITLE
Exception: Program command is not specified.

### ISSUE THREAD

**Issue by MADAOtea** [codalab/codalab-competitions#2980]
Good morning everyone! 
I want to submit my result on CVPPP2017 on [this page](https://competitions.codalab.org/competitions/18405#participate-submit_results), but I get the eror message:

**Traceback (most recent call last):
  File "/worker/worker.py", line 361, in run
    raise Exception("Program command is not specified.")
Exception: Program command is not specified.**

Does anyone know how to solve this problem or what happen on this massage?

Thank you!

**Comment by coder-people** [comment]
I meet identical problems

**Comment by Didayolo** [comment]
Hello,

Sorry for the late reply. Do you still need help with this problem?
