### ISSUE TITLE
AutoML challenge: solutions and dataset descriptions?

### ISSUE THREAD

**Issue by Yura52** [codalab/codalab-competitions#2982]
Hi! I am a Deep Learning researcher in the field of Supervised Learning on Tabular Data (classification and regression tasks).

I am trying to extend the benchmark I use to compare different models (Neural Networks, Gradient Boosted Trees etc.) and [the AutoML challenge](https://automl.chalearn.org/data) looks very relevant. However, there are two problems:
- most of the datasets are missing labels for the validation and test parts
- it looks like the datasets are all "anonymized", so there is no information about features and targets
 
Is it possible to publish labels and dataset descriptions? It will be so helpful for the field! Unfortunately, UCI, libsvm, OpenML and other repositories do not always offer enough datasets for some specific problems related to the field of Tabular Data.

**Comment by Didayolo** [comment]
Hello,

I think you can find more detailed documentation in this paper: [https://hal.archives-ouvertes.fr/hal-01906197/document](https://hal.archives-ouvertes.fr/hal-01906197/document)

I hope this helps!

Note that, more recently, the AutoDL Challenge Series took place with new datasets and tasks: [https://autodl.chalearn.org/](https://autodl.chalearn.org/)
