### ISSUE TITLE
MSCOCO2019-testdev bboxes  evaluation platform always raise “Sorry, failed to upload file.”

### ISSUE THREAD

**Issue by lji72** [codalab/codalab-competitions#2985]
1. What browser and version are you using?
   Google chrome
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://competitions.codalab.org/competitions/20794#participate

**Comment by lji72** [comment]
@Didayolo @emersion  please help to solve this issue. Thanks in advance.

**Comment by juliojj** [comment]
We are facing the same "Sorry, failed to upload file" problem in our ICCV Challenges (https://competitions.codalab.org/competitions/31584). I have also observed Codalab a bit unstable a few days ago. Hope it gets normalized soon ;)

**Comment by hanjiale** [comment]
We are facing the same "Sorry, failed to upload file" problem in https://competitions.codalab.org/competitions/27980 .

**Comment by zijinxuxu** [comment]
The same error occured and when i download previously submitted file, it shows "The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."

**Comment by gaetanbahl** [comment]
I am facing the same issue with COCO Detection Challenge (Segmentation Mask).

**Comment by lji72** [comment]
Thanks for the authors' hard work.
Good news！the website works fine now. @juliojj @hanjiale @zijinxuxu @gaetanbahl

**Comment by jiarenyf** [comment]
facing the same issue
facing the same issue
facing the same issue
facing the same issue
