### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmp7aaMxa/run/input/res/pred_vid_result.json'

### ISSUE THREAD

**Issue by wulala-source** [codalab/codalab-competitions#2988]
Error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 283, in
area = eval(truth_dir,submit_dir)
File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 253, in eval
pred_vid_result = json.load(open(osp.join(pred_dir, 'pred_vid_result.json')))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmp7aaMxa/run/input/res/pred_vid_result.json'

**Comment by wulala-source** [comment]
> Error:
> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
> Traceback (most recent call last):
> File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 283, in
> area = eval(truth_dir,submit_dir)
> File "/tmp/codalab/tmp7aaMxa/run/program/eval_detection.py", line 253, in eval
> pred_vid_result = json.load(open(osp.join(pred_dir, 'pred_vid_result.json')))
> IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmp7aaMxa/run/input/res/pred_vid_result.json'

The zip file you upload containing a pred_part_result.json and a pred_vid_result.json should contain without any folder.

**Comment by Didayolo** [comment]
Thanks for posting your fix.
