### ISSUE TITLE
Security vulnerabilities on several urls

### ISSUE THREAD

**Issue by dtuantran** [codalab/codalab-competitions#2989]
Public user can access to some critical data (e.g: secret key) or modify a competition even without logging in and not being the competition's owner. These vulnerabilities affect all codalab versions in general. Here is the list of URLs:

api/competition/<id>
/api/competition/<pk>/phases/ 
/api/competition/<pk>/phases/<phasenumber>
/competitions/<id>/results/<phase>
/competitions/<id>/results/<phase>/data
/competitions/<id>/results_complete/<phase>/data

**Comment by tocodo** [comment]
@Tthomas63 Hi Tyler, I've opened this issue for tracing.

**Comment by dtuantran** [comment]
These vulnerabilities are fixed.
