### ISSUE TITLE
MSCOCO2019-testdev bboxes evaluation platform always raise “Sorry, failed to upload file.” Again

### ISSUE THREAD

**Issue by lji72** [codalab/codalab-competitions#2990]
What browser and version are you using?
Google chrome
What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
https://competitions.codalab.org/competitions/20794#participate

**Comment by Callidior** [comment]
Happens for other competitions as well, e.g.: https://competitions.codalab.org/competitions/33214

**Comment by Callidior** [comment]
Seems to be resolved now.

**Comment by litian1045** [comment]
Seems still a problem for https://competitions.codalab.org/competitions/32478

**Comment by sliwy** [comment]
The same problem here: https://competitions.codalab.org/competitions/33427

**Comment by z-x-yang** [comment]
@acletournel Waiting for your solution. Thanks in advance!

It seems the upload problem happens more and more frequently. Is the current problem still related to a resource shortage?

**Comment by runzeer** [comment]
I saw the maintenance is during 9th and 14th. So it means we can not upload any file? So will you remedy another 5 days after the maintenance?

**Comment by zhulf0804** [comment]
I can't submit the result for more than 8 hours on the MVP Challenge (https://competitions.codalab.org/competitions/33430#participate-submit_results). And the deadline for the public submission is on Sep. 12. 

@acletournel Waiting for your solution. Thanks in advance!

**Comment by loicsarrazin** [comment]
As mentionned elsewhere by @acletournel:  


> Hello,
> We are preparing a new storage solution for weeks (new hardware, distributed minio etc ...), but we keep being disturbed by incidents on the production storage in between. Several github issues have been opened on the topic again since end of August.
> The maintenance operation of 9th September is finished, and storage should be up again. Some more maintenance interruptions will still be planned in the next days / weeks. We would also like upgrading the application to python 3 soon. We will keep you informed as much as possible via front page or google group.
> Thanks for you comprehension.
> Regards,

**Comment by jiarenyf** [comment]
facing the same issue
facing the same issue
facing the same issue
facing the same issue
