### ISSUE TITLE
Problem uploading the competition bundle

### ISSUE THREAD

**Issue by aniket-agarwal1999** [codalab/codalab-competitions#2991]
Hi,
I am trying to create a competition and for the same I have created a competition bundle to upload on the site. However when I am trying to upload the same, I am just getting the notif of 'Sorry, unable to upload the file'. There should be no problem with the created bundle since I used pretty much the same thing earlier around 2 days back as well and it worked great.
Is it due the maintenance notice listed on the website or some other issue?

**Comment by acletournel** [comment]
Yes, this is due to maintenance, longer than expected. Sorry for inconvenience.

**Comment by Didayolo** [comment]
It should be working by now.
