### ISSUE TITLE
Why did I submit an error when I submitted LITS2017. The specific description is as follows:

### ISSUE THREAD

**Issue by DreamOneYou** [codalab/codalab-competitions#2993]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpuXP34H/run/program/evaluate.py", line 67, in 
    "Missing volume: {}".format(submission_volume_path))
ValueError: Submission volume not found - terminating!
Missing volume: /tmp/codalab/tmpuXP34H/run/input/res/test-segmentation-0.nii

**Comment by Didayolo** [comment]
Hello,

Is this still happening?
