### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. Traceback (most recent call last):   File "/tmp/codalab/tmpocPHvY/run/program/evaluate.py", line 118, in      m_iou,iou,m_acc = evaluate_iou(pred_files,target_files)   File "/tmp/codalab/tmpocPHvY/run/program/evaluate.py", line 93, in evaluate_iou     assert (target_files[i] in pred_files) AssertionError

### ISSUE THREAD

**Issue by LucyZhu0919** [codalab/codalab-competitions#2994]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpocPHvY/run/program/evaluate.py", line 118, in 
    m_iou,iou,m_acc = evaluate_iou(pred_files,target_files)
  File "/tmp/codalab/tmpocPHvY/run/program/evaluate.py", line 93, in evaluate_iou
    assert (target_files[i] in pred_files)
AssertionError

when I submit my results, then the error showing above occurred. I don't know why

**Comment by Didayolo** [comment]
Hello,

You can ignore this part of the error message, which is common:
```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
```

So your error is here:

```
File "/tmp/codalab/tmpocPHvY/run/program/evaluate.py", line 93, in evaluate_iou
assert (target_files[i] in pred_files)
AssertionError
```

When calling the `assert` function. If you are writing `evaluate.py` on your own, then it's just a matter of debugging your code.
