### ISSUE TITLE
Submission view : phases drop down menu has no items if competition has ended

### ISSUE THREAD

**Issue by loicsarrazin** [codalab/codalab-competitions#2998]
I was able to identify this bug from the submission view:   
![image](https://user-images.githubusercontent.com/83833966/134742668-ac22e61c-03ec-4fc7-96b7-45b7958873a0.png)

Where no phase show in the dropdown menu of the phase selector only if the competition is over.  
  
 It seems that the submissions.html file incorporates a scripts that makes this request : 
                         async get_phases() {
                            try {
                                const resp = await $.get(`/api/competition/${COMPETITION_ID}/phases/`)
                                this.phases = resp[0].phases
                                this.loading = false
                            } catch (e) {
                                console.log(e)
                                console.log(e.response)
                            }

Where the GET requests return : 
[]  
  
if the competition end date is passed. 
If not, it returns : 
  
  [
    {
        "end_date": null,
        "phases": [
            {
                "competition": 2,
                "description": null,
                "phasenumber": 1,
                "label": "First phase",
                "start_date": "2013-06-30",
            ...
            }
        ]
    }
]

**Comment by Didayolo** [comment]
Merged.
