### ISSUE TITLE
Update scoring program after the competition is launched

### ISSUE THREAD

**Issue by rangsimanketkaew** [codalab/codalab-competitions#3000]
Hi All,

Is it possible to update a scoring program after the competition is launched and re-calculate scores of all submissions of participants again using a new scoring program?

Here is a link to my competition leaderboard (phase 1): https://competitions.codalab.org/competitions/34540#results

Best,
Rngsiman

**Comment by Didayolo** [comment]
Yes, see [https://github.com/codalab/codalab-competitions/wiki/User_Dataset-Management](https://github.com/codalab/codalab-competitions/wiki/User_Dataset-Management)
A scoring program is like a "dataset". It can be uploaded in "My Datasets" and then selected with the editor. Choose a recognizable name.
