### ISSUE TITLE
About modifying username

### ISSUE THREAD

**Issue by GuilinPang** [codalab/codalab-competitions#3005]
For some reasons, we want to modify our account and user name. How can we achieve it?

**Comment by Didayolo** [comment]
Hi,

Please send an email to [info@codalab.org](mailto:info@codalab.org).

Make sure to:
- Use the email address linked to your CodaLab account to send the request
- Provide your current username
- Provide the desired username (and possibly alternatives in the case it's already taken)

**Comment by Didayolo** [comment]
Hi,
Sorry for the inconvenience. This should be working again now. Can you please retry to send your email?
Thanks.

**Comment by GuilinPang** [comment]
Hi,
Okay, I have sent the email again.
![image](https://user-images.githubusercontent.com/66616243/138214552-19037d92-bea9-4d71-972a-2ba4ada86d31.png)
Best wishes for you.

**Comment by yahooo-m** [comment]
I also sent an email to change username.
