### ISSUE TITLE
Why the django service runs slower after a long period of time?

### ISSUE THREAD

**Issue by liwantingcamille** [codalab/codalab-competitions#3014]
Hello, I have two questions when developing from your project.
When the django container runs for a long period of time, the service always becomes slower and slower. If I restart it, the access to the website will be normal. Which factor may cause this problem，such as the continuous consumption of resource and cache？Is there any solutions to maintain the efficient usage of them?

Another question is, if I want to modify the interface of codalab, should I cite something specially to indicate your excellent  work?

Thanks!I am looking forward to receiving your reply.

**Comment by Didayolo** [comment]
CodaLab Competitions is released under the Apache License 2.0 (the "License"); you may not use the software except in compliance with the License.

The text of the Apache License 2.0 can be found online at: http://www.opensource.org/licenses/apache2.0.php
