### ISSUE TITLE
The 'all submissions view' is empty

### ISSUE THREAD

**Issue by tahasaf** [codalab/codalab-competitions#3015]
Hi,

The 'all submissions view' is empty! (even if the submissions metadata view is ok)

I added pavao and tthomas63 to the competition:
https://codalab.lisn.upsaclay.fr/competitions/51?secret_key=e6e8352b-3120-4a53-ac1a-80adb1a40334

Thanks a lot for codalab

**Comment by Didayolo** [comment]
@tahasaf 
The problem should have been solved by #3043.
By looking at your competition, indeed the "All Submissions" panel is now working.
Feel free to re-open the issue if needed.
