### ISSUE TITLE
Leaderboard sorted by the 5th metric 

### ISSUE THREAD

**Issue by aliannejadi** [codalab/codalab-competitions#3017]
I am running a competition on scoring only setup. We have 6 metrics. I noticed that the results are sorted by the metric with "order: 5" and I cannot figure out how to force the table to be sorted by the first metric. 
The issue might be because the fifth metric appears first in the YAML file. Is there any way to fix this on the "Edit" page of the competition? 

Thanks,
Mohammad

**Comment by Didayolo** [comment]
Hi,

Indeed it is not really clear how to select the "sorting" metric.

Are you in a situation where you can't re-upload the bundle? (e.g. the competition is already running)

By looking at one of my own competition, I think you are right. In the YAML file, `rank` defines the position of the column in the leaderboard (then it's `order` in the EDIT menu) ; but the ordering is done according to the first column mentioned in the YAML file.

**Comment by Didayolo** [comment]
I close the issue here as it is staling, and already merged into #2686
