### ISSUE TITLE
Feature Request: remaining upload indicator

### ISSUE THREAD

**Issue by JRMeyer** [codalab/codalab-competitions#3022]
Hello!

It would be helpful to add a progress bar or spinning wheel for bundle uploads, so the user/organizer knows things are progressing.

Using the public instance, uploading both competition bundles and submission bundles take longer than expected, and it's not obvious when it's a connection issue.

**Comment by Didayolo** [comment]
Hello,

This would indeed be an useful feature. I think some browsers show a percentage in the bottom corner, but a real progress bar would be great, also when uploading files in the "My Datasets" page.

By the way, let me remind you that CodaLab is an open-source and collaborative project. For simple additions like this, you could take the time to make a pull request by yourself if you wish, it would be greatly appreciated.

**Comment by Didayolo** [comment]
Merged.
