### ISSUE TITLE
Competition Bundle Upload - No Reference data supplied

### ISSUE THREAD

**Issue by ihsaan-ullah** [codalab/codalab-competitions#3024]
I am uploading a competition bundle without reference data and I get the following error
<img width="1126" alt="Screenshot 2021-11-04 at 4 40 26 PM" src="https://user-images.githubusercontent.com/13259262/140364593-dccae365-9fc1-49b6-8a54-84a5c163624e.png">

Is there any way to upload a bundle without reference data. I am planning to uploading the data later and then link it to the competition in the settings.

**Comment by Didayolo** [comment]
I think you should check your `competition.yaml` file, you may be referencing to an unexisting reference data file in it.

Also, as a work-around, you can provide an empty `reference_data.zip`.

**Comment by ihsaan-ullah** [comment]
Thank you for the solution. The empty `reference_data.zip` worked
