### ISSUE TITLE
Submitting scores leads to no such file or directory error.

### ISSUE THREAD

**Issue by TalitaAnthonio** [codalab/codalab-competitions#3025]
Hello, 

I am trying to upload to the trial phase on my competition page: 
https://competitions.codalab.org/competitions/35210#participate-submit_results
(see submitted file).  The uploaded file contains a directory with two subdirectories 
[answers.zip](https://github.com/codalab/codalab-competitions/files/7476288/answers.zip)
. 

I constantly get this error: 
OSError: [Errno 2] No such file or directory: '/tmp/codalab/tmplecnLA/run/input/res/classification'

In my evaluation script i putted the following: 

 
submit_dir = os.path.join(input_dir, 'res')
 truth_dir = os.path.join(input_dir, 'ref')

This used to work but now it doesn't.  Does anyone know what the problem is?

**Comment by Didayolo** [comment]
It is strange that it used to work and doesn't work anymore.

Usually we don't include directory structures inside the ZIP submission file.
But this maybe could be handled by the scoring program itself.

Still you can try to zip the files without directory structure, or to review and update your scoring program.

**Comment by Didayolo** [comment]
Have you been able to solve the issue?
Maybe you should create your competition on the [new server](https://codalab.lisn.fr/)
I close the issue for now, feel free to re-open it if needed.

**Comment by serenayj** [comment]
Hi, I was wondering what will be the solution to this problem. I had the same issue where the "res" and "ref" folders do not exist. Thank you!
