### ISSUE TITLE
Covid-19 Infection Percentage Estimation Competition Cant download datasets

### ISSUE THREAD

**Issue by ibrahim810** [codalab/codalab-competitions#3028]
Hi,
![image](https://user-images.githubusercontent.com/50838748/140656917-6576d636-7c06-4d81-a24c-eb1d1f5730a4.png)
as you can see in the image 
there is a problem when i try to download the dataset (both train & validate) of the Competition 
(Covid-19 Infection Percentage Estimation)
https://competitions.codalab.org/competitions/35575#learn_the_details
it says :

404
Could not find the page you requested.

If you are the challenge organizer and this URL previously pointed to a valid competition and it is now missing please contact us at info@codalab.org for more information.
If this is in error, please file a bug report. For more information about CodaLab, check out the wiki. 

what should i do ?
(((links and version below)))
thanks...

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
---               Firefox 94.0.1 (64-bit)
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
---        https://drive.google.com/drive/folders/1vPYMrL_IwC_wOxff3wX_Rg1iIJyNl2Dc?usp=sharing
             and
             https://drive.google.com/drive/folders/18V_u6Vo75a_A5RlUH80UcXh3i0rc5keE?usp=sharing

**Comment by Didayolo** [comment]
Hi,

I did not fully get the issue. 

- Are you the organizer of this competition?
- Did you try to upload the ZIP files in the "My Datasets" section, and then to select them as "Public Data" using the "EDIT" menu?

**Comment by ibrahim810** [comment]
> 
> 
> Hi,
> 
> I did not fully get the issue.
> 
>     * Are you the organizer of this competition?
> 
>     * Did you try to upload the ZIP files in the "My Datasets" section, and then to select them as "Public Data" using the "EDIT" menu?

No, I'm a participant..
Anyway, I figured it out, there is an issue in re-directing from the website to google drive so I just copied the link and paste it manually also, the problem occurs when using a browser with ad-block.
Thanks anyway...

**Comment by Didayolo** [comment]
Oh OK. I was confused because I could access the data from your links.

Glad to hear that you could download the data. I just got accepted into the competition and indeed I have the same redirection problem. Thank you for reporting it!
