### ISSUE TITLE
SemanticKitti Competition - IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by TangZJ** [codalab/codalab-competitions#3029]
SemanticKitti Single Scan Semantic Segmentation:

https://competitions.codalab.org/competitions/20331#participate

Under user: MPT
submission attempt 5 (Single Scan)

Failed submission due to error:

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

Request to fix this and delete submission attempt

**Comment by Didayolo** [comment]
Hi,

I guess one of the worker of the main queue is ill. I'll check this asap.

In the meantime, just re-submitting the job should work.

**Comment by HenryJunW** [comment]
Hello, the same error pops up again just now. Would you mind checking it? Thanks!

**Comment by Didayolo** [comment]
> Hello, the same error pops up again just now. Would you mind checking it? Thanks!

Thanks for the message. I think I've retrieve your failing submission (made 2 hours ago), and the associated worker.

**Comment by HenryJunW** [comment]
Got it. Really appreciate it very much!

**Comment by HenryJunW** [comment]
Hello @Didayolo, for the competition https://competitions.codalab.org/competitions/20331, currently I am not able to submit the results. Can you check it? Thanks!

**Comment by HenryJunW** [comment]
It's working now! Thanks!

**Comment by dlinzhao** [comment]
Hello @Didayolo, for the SemanticKitti Single Scan Semantic Segmentation: [https://competitions.codalab.org/competitions/20331#participate](https://competitions.codalab.org/competitions/20331#participate), the error `IOError: [Errno 28] No space left on device` appears once again.  Can you check it and delete submission (username: codalab_dlz) attempt? Thanks!
