### ISSUE TITLE
Submission status is "running" for a long time and all submission view is empty

### ISSUE THREAD

**Issue by nyokoya** [codalab/codalab-competitions#3034]
I am the organizer of the following competition:
https://codalab.lisn.upsaclay.fr/competitions/234?secret_key=631417b0-1962-4154-8f32-2a469713d52b

I have the following two issues:
1) Submission status is "running" for a long time for participants but I (organizer) cannot reproduce this issue.
2) All submission view is empty.

I have already added `pavao` and `tthomas63` as admins to my competition.
Many thanks for your help!

**Comment by dalision** [comment]
the same issue

**Comment by Didayolo** [comment]
Hi,

1. About the submission status, we will check the queue because it seems to be a general problem. Maybe the job queue is flooded.

2. About the "all submissions" view, there is another problem related (#3027). @loicsarrazin maybe you could have a look at this when you have time? As you have already made contributions to this page (#3031).

**Comment by loicsarrazin** [comment]
Hi @nyokoya, would you please add me as a competition admin? My username is loic.sarrazin.  
  
 Thank you!

**Comment by nyokoya** [comment]
@loicsarrazin I wonder if you could have time to take a look at the issue mentioned above

**Comment by Didayolo** [comment]
@loicsarrazin is actively looking into it

**Comment by loicsarrazin** [comment]
@nyokoya I think there might be a problem with the actual scoring, I suggest you change your scoring program's score with something else than "Prediction:None", because I suspect there is an error with the submission, and then a problem on our side with the parsing of a "None" results.  
  
 You can see in this example https://github.com/codalab/competition-examples/blob/master/basic-competition-bundles/Iris/iris_competition_bundle/scoring_program/score.py that "-1" is used.  
   
  I'll be giving updates on wether there is a problem on our side and when it's corrected

**Comment by Didayolo** [comment]
About this side of the bug: "All submission view is empty", here are the error logs:

```
django            | 2021-11-25 16:03:35,866 INFO Calculating sub size for submission: 2454
django            | 2021-11-25 16:03:35,985 INFO Calculating sub size for submission: 2447
django            | 2021-11-25 16:03:36,080 INFO Calculating sub size for submission: 2446
django            | 2021-11-25 16:03:36,172 INFO Calculating sub size for submission: 2146
django            | 2021-11-25 16:03:36,181 ERROR Internal Server Error: /api/competition/234/submissions/
django            | Traceback (most recent call last):
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 41, in inner
django            |     response = get_response(request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 187, in _get_response
django            |     response = self.process_exception_by_middleware(e, request)
django            |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 185, in _get_response
django            |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
django            |     return view_func(*args, **kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 103, in view
django            |     return self.dispatch(request, *args, **kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 483, in dispatch
django            |     response = self.handle_exception(exc)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 443, in handle_exception
django            |     self.raise_uncaught_exception(exc)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in dispatch
django            |     response = handler(request, *args, **kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 48, in list
django            |     return Response(serializer.data)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 765, in data
django            |     ret = super(ListSerializer, self).data
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 262, in data
django            |     self._data = self.to_representation(self.instance)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 682, in to_representation
django            |     return [
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 683, in <listcomp>
django            |     self.child.to_representation(item) for item in iterable
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 527, in to_representation
django            |     ret[field.field_name] = field.to_representation(attribute)
django            |   File "/usr/local/lib/python3.8/site-packages/rest_framework/fields.py", line 1855, in to_representation
django            |     return method(value)
django            |   File "/app/codalab/apps/api/serializers.py", line 117, in get_size
django            |     return instance.size
django            |   File "/app/codalab/apps/web/models.py", line 1449, in size
django            |     size = get_submission_size(self) or 0
django            |   File "/app/codalab/apps/web/utils.py", line 211, in get_submission_size
django            |     total += get_filefield_size(submission, 'file', aws_attr='s3_file', s3direct=True)
django            |   File "/app/codalab/apps/web/utils.py", line 226, in get_filefield_size
django            |     size = obj_summary.size
django            |   File "/usr/local/lib/python3.8/site-packages/boto3/resources/factory.py", line 339, in property_loader
django            |     self.load()
django            |   File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 86, in object_summary_load
django            |     response = self.meta.client.head_object(
django            |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
django            |     return self._make_api_call(operation_name, kwargs)
django            |   File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
django            |     raise error_class(parsed_response, operation_name)
django            | botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

```

**Comment by nyokoya** [comment]
@loicsarrazin Many thanks for your suggestion! I have changed the scoring program and replaced "None" with 9999. I wonder if you can stop/delete all submissions with the status of "running".

**Comment by Didayolo** [comment]
> @loicsarrazin I wonder if you can stop/delete all submissions with the status of "running".

Actually it is something that you are supposed to be able to do from the "All submissions" view as a competition organizer.
Unfortunately, as the view is not working with your competition, you won't be able to do it I guess...
So we basically need to solve your issue!

**Comment by Didayolo** [comment]
https://github.com/codalab/codalab-competitions/blob/ba51fa6c616d94504002cfd1dd3943fb4f0b1121/codalab/apps/web/utils.py#L226

Add a try/catch here?

**Comment by Didayolo** [comment]
Actually,

https://github.com/codalab/codalab-competitions/blob/ba51fa6c616d94504002cfd1dd3943fb4f0b1121/codalab/apps/web/utils.py#L225

This condition is wrong.

**Comment by loicsarrazin** [comment]
File has indeed not been uploaded. I suggest we try testing it's existence before querying its size  
  
  Something like  
    
    s3 = boto3.resource('s3')

try:
    s3.Object('my-bucket', 'dootdoot.jpg').load()
except botocore.exceptions.ClientError as e:
    if e.response['Error']['Code'] == "404":
        # The object does not exist.
        ...
    else:
        # Something else has gone wrong.
        raise
else:
    # The object does exist.
    ...

**Comment by Didayolo** [comment]
@nyokoya 

It should be solved now :-)

**Comment by Didayolo** [comment]
Feel free to re-open the issue if you are still facing it.
