### ISSUE TITLE
Display 'Sorry, failed to upload file.' but .zip has been saved in the data storage when creating a competition

### ISSUE THREAD

**Issue by sqhan-Husky** [codalab/codalab-competitions#3040]
Hello, I find a problem when l deploy Codalab on another cloud storage, namely Ucloud S3 which also supports a compatible S3.
  
The URL format of the US3 is `my_bucket_name.endpoint` instead of `endpoint/my_bucket_name`. l found **there's no effect if l change the calling format from `OrdinaryCallingFormat` to `VHostCallingFormat`** in `.env` . 

The requested URL is still the original format with a `200` status response when creating a competition.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/45597101/142820130-50d43332-52fa-4173-b983-919a4861d873.png">

Surprisingly, the zip file can be saved successfully onto the cloud storage:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/45597101/142819248-4d05b5b7-696b-4965-99dc-feaccc00dd8b.png">

However, the process of creating competition was corrupted with the alert 'Sorry, failed to upload file.'.

I have tried to locate the error in the project, but there are no clues.
I really wonder about the relationship between these URLs when requesting, uploading, and responding.

This situation also happens when l apply Minio before.

Hope to your reply!

Best,
Siqi

**Comment by sqhan-Husky** [comment]
Thank you for your reply. @Didayolo 

l'm using the `develop` branch and l have cloned it months ago to my WSL.
Should l have to clone your project again after your new merge?
Since l just re-write the `.env` file with two new lines  about `AWS_S3_ADDRESSING_STYLE`, and re-build the docker containers, there's no actual change ( still `Sorry, failed to upload file.`)

**Comment by dtuantran** [comment]
Hello @sqhan-Husky,
Have you tried to add these lines below in ```.env``` ?
```
AWS_S3_ADDRESSING_STYLE=path
S3DIRECT_URL_STRUCTURE=https://{0}/{1}               #{0} = AWS_S3_HOST; {1} = bucket
```

**Comment by sqhan-Husky** [comment]
Hello @dtuantran,
I haven't updated Codalab with the new merge so that it still used `boto`, not `boto3.`
Actually, l think the original code  `AWS_S3_CALLING_FORMAT=boto.s3.connection.OrdinaryCallingFormat` in `boto` is equivalent to the two new lines in `boto3` you showed.
It failed when uploading too.

**Comment by sqhan-Husky** [comment]
Hi, @Didayolo   @dtuantran 
I have updated my codalab instance and retried the process of creating competition via another cloud storage.
I followed the network in F12 when clicking the upload button, and the URL format has successfully been set as `my_bucket_name.endpoint`. Also, the zip file has been saved on the storage.

However, the website still alerted me with  'Sorry, failed to upload file'.  
I check the logs of `worker_site` container that it hasn't received a `apps.web.tasks.create_competition` task. 

l really wonder in which step the process failed.

**Comment by sqhan-Husky** [comment]
@Didayolo @dtuantran   Sorry to disturb you frequently again. 
Because l try my codalab instance with minio, following your updated wiki, something went wrong:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/45597101/144069529-190d60c1-b68e-4632-891d-c84b7d8b73d2.png">

It seems that a special CORS policy needs to be set.

**Comment by sqhan-Husky** [comment]
@dtuantran @Didayolo 
Hi, l noticed that the `django-s3direct` the codalab installed is very old (0.4.1), and the latest version is up to 1.1.8, which has stronger functionalities and compatibility.
The gap between the version might lead to my problem on applying another cloud storage, which has been verified usable via the latest version. Also, the `boto3` has a newest version.

Do you have a plan to update them in the future?

**Comment by dtuantran** [comment]
> @Didayolo @dtuantran Sorry to disturb you frequently again. Because l try my codalab instance with minio, following your updated wiki, something went wrong: <img alt="image" width="573" src="https://user-images.githubusercontent.com/45597101/144069529-190d60c1-b68e-4632-891d-c84b7d8b73d2.png">
> 
> It seems that a special CORS policy needs to be set.
> 
> The curent `Cors Allow Origin` of minio: ![image](https://user-images.githubusercontent.com/45597101/144159857-32ae855d-543a-4ddf-b6c5-4fafc8fe1792.png)

Hello @sqhan-Husky,

In your image, your url isn't in correct format ```http://11 s3_create_competition:13.31.147.179```. Let's try to verify your configuration in .env file. I haven't seen the CORS error before, maybe it depends on the browser ? I'm trying to reproduce it. Maybe this article can help : https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9.

For your question about updating the package to latest versions, sorry that I work close to infrastructure, not dev, then I can't tell anything. Please give us updates if you successes to make Codalab working properly.

Regards,

**Comment by sqhan-Husky** [comment]
@dtuantran Thank you.  I have solved the problem on Minio(https://github.com/codalab/codalab-competitions/issues/3051#issue-1068456996).

Also, l modify some of the source code about the S3direct and update the latest boto3. 
It can work with our Ucloud S3 now.
