### ISSUE TITLE
Failed to load static resource.

### ISSUE THREAD

**Issue by sqhan-Husky** [codalab/codalab-competitions#3046]
Hello, 
I have cloned and deployed the latest `codalab-competitions` and all 8 dockers have been created successfully.
However, when l visit the `myIP:8000` website, all the static resources, like css and js, are lost:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/45597101/143803812-ca6bc0ad-1f0b-49d8-a1cd-ea500aece286.png">
And the error messages are:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/45597101/143803867-2eff8b40-23d2-4e29-8539-5452def743b9.png">

I don't change any files in the source directory except the `.env` file. 
It's really weird.
Please tell me how can l fix this problem. Thank you all.

**Comment by Didayolo** [comment]
Hi,

Can you share the logs of your containers? `docker-compose logs -f`

It is indeed weird as the static resources are directly inside the repository.

**Comment by sqhan-Husky** [comment]
@Didayolo 
The logs of Django docker are here:
  Copying '/usr/local/lib/python3.8/site-packages/tinymce/static/django_tinymce/init_tinymce.js' 
  .......
  Copying '/usr/local/lib/python3.8/site-packages/debug_toolbar/static/debug_toolbar/js/redirect.js'
  
  2000 static files copied to '/app/codalab/static', 2 unmodified.
  Operations to perform:
    Apply all migrations: account, admin, auth, authenz, captcha, contenttypes, coopetitions, customizer, forums, guardian, health, jobs, newsletter, oauth2_provider, queues, sessions, sites, socialaccount, teams, web
  Running migrations:
    Applying contenttypes.0001_initial... OK
    Applying contenttypes.0002_remove_content_type_name... OK
    Applying auth.0001_initial... OK
    Applying auth.0002_alter_permission_name_max_length... OK
    Applying auth.0003_alter_user_email_max_length... OK
    Applying auth.0004_alter_user_username_opts... OK
    Applying auth.0005_alter_user_last_login_null... OK
    Applying auth.0006_require_contenttypes_0002... OK
    Applying auth.0007_alter_validators_add_error_messages... OK
    Applying auth.0008_alter_user_username_max_length... OK
    Applying authenz.0001_initial... OK
    Applying account.0001_initial... OK
    Applying account.0002_email_max_length... OK
    Applying admin.0001_initial... OK
    Applying admin.0002_logentry_remove_auto_add... OK
    Applying captcha.0001_initial... OK
    Applying teams.0001_initial... OK
    Applying queues.0001_initial... OK
    Applying web.0001_initial... OK
    Applying coopetitions.0001_initial... OK
    Applying coopetitions.0002_auto_20200716_1850... OK
    Applying customizer.0001_initial... OK
    Applying customizer.0002_configuration_only_competition... OK
    Applying forums.0001_initial... OK
    Applying forums.0002_forum_competition... OK
    Applying forums.0003_auto_20210513_1705... OK
    Applying guardian.0001_initial... OK
    Applying health.0001_initial... OK
    Applying health.0002_storagedatapoint... OK
    Applying jobs.0001_initial... OK
    Applying newsletter.0001_initial... OK
    Applying oauth2_provider.0001_initial... OK
    Applying oauth2_provider.0002_08_updates... OK
    Applying oauth2_provider.0003_auto_20160316_1503... OK
    Applying oauth2_provider.0004_auto_20160525_1623... OK
    Applying sessions.0001_initial... OK
    Applying sites.0001_initial... OK
    Applying sites.0002_alter_domain_unique... OK
    Applying socialaccount.0001_initial... OK
    Applying socialaccount.0002_token_max_lengths... OK
    Applying socialaccount.0003_extra_data_default_dict... OK
    Applying teams.0002_auto_20200716_1850... OK
    Applying web.0002_submissioncomputedscore_weights... OK
    Applying web.0003_auto_20201022_0527... OK
    Applying web.0004_auto_20201113_2031... OK
  Installed 28 object(s) from 2 fixture(s)
  2021-11-29 12:39:58,114 ERROR Invalid HTTP_HOST header: ':80'. The domain name provided is not valid according to RFC 1034/1035.
  2021-11-29 13:01:38,153 ERROR Invalid HTTP_HOST header: ':80'. The domain name provided is not valid according to RFC 1034/1035.
  2021-11-29 13:01:46,486 ERROR Invalid HTTP_HOST header: ':80'. The domain name provided is not valid according to RFC 1034/1035.
  Waiting for database connection...
  WEB IS RUNNING
  up to date in 0.434s
  /usr/local/bin/lessc -> /usr/local/lib/node_modules/less/bin/lessc
  + less@4.1.2
  updated 1 package in 4.825s
  
  > codalab@1.0.0 build-css /app/codalab
  > lessc apps/web/static/less/imports.less > apps/web/static/css/imports.css
  
  Copying '/app/codalab/apps/web/static/css/imports.css'
  
  1 static file copied to '/app/codalab/static', 2001 unmodified.
  Operations to perform:
    Apply all migrations: account, admin, auth, authenz, captcha, contenttypes, coopetitions, customizer, forums, guardian, health, jobs, newsletter, oauth2_provider, queues, sessions, sites, socialaccount, teams, web
  Running migrations:
    No migrations to apply.
    Your models have changes that are not yet reflected in a migration, and so won't be applied.
    Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
  Installed 28 object(s) from 2 fixture(s)

Another 7 dockers seem to run normally. The logs are too long, if you need more detailed logs, l will present them.
Thank you!

**Comment by loicsarrazin** [comment]
You're accessing directly the django service. Try accessing via the NGINX port, which would be something like YourIP:80, or just YourIP, or something else depending on your .env

**Comment by sqhan-Husky** [comment]
@loicsarrazin   Thank you, it takes effect.
I try to sign up for an account on the new codalab, however, l don't receive the verified email for a long time even in the spam folder.  And l cannot log in.

Is this a useful message?
`2021-11-30 INFO Settings not found for Mailchimp endpoint and API. Please add these to your Django settings file. This task will be run again in 60 minutes.`
What should l do if l don't want to use the email verification?

**Comment by Didayolo** [comment]
> I try to sign up for an account on the new codalab, however, l don't receive the verified email for a long time even in the spam folder. And l cannot log in.

What is your username?

> What should l do if l don't want to use the email verification?

I am a bit confused. Are you talking about your own instance, or the codalab.lisn.fr instance?

**Comment by sqhan-Husky** [comment]
@Didayolo    Thank you!   I have found the information l need in the Django logs.
