### ISSUE TITLE
Stuck in Submitted or Submitting 

### ISSUE THREAD

**Issue by ankitagr01** [codalab/codalab-competitions#3049]
Hello, some of the tasks are stuck in submitted or submitting status as you can see from the image below. 
![image](https://user-images.githubusercontent.com/45555218/144111518-4895eea1-db2d-4757-826b-26e99a84dc48.png)

1. What browser and version are you using? 
     Chrome
2. What is the URL of the problem? 
     https://competitions.codalab.org/competitions/20127#participate-submit_results
     Username:: ankit.agrawal

**Comment by Didayolo** [comment]
Hi,

Thanks for reporting.

This is a clone of #3045 so I'll close it.

We are actively trying to solve the problem.
