### ISSUE TITLE
Blocked by CORS Policy with the newly-updated minio storage

### ISSUE THREAD

**Issue by sqhan-Husky** [codalab/codalab-competitions#3051]
Hi, 
l followed your updated [minio wiki](https://github.com/codalab/codalab-competitions/wiki/Minio-storage) to deploy the storage of my Codalab instance.
However, something went wrong:
![image](https://user-images.githubusercontent.com/45597101/144247798-926840b7-555d-4db0-b1ca-c4cf50d8aa67.png)
It seems that a special CORS policy needs to be set.

Here's my settings of `.env` of codalab and the `docker-compose.yml` for minio:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/45597101/144247982-37e3811a-1a4b-4f0c-a63a-818fcb810058.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/45597101/144248166-15210594-41c8-4234-8152-1fa72eb9dbca.png">
A little difference in the `docker-compose.yml` is that l set `9000` as console-address to avoid a dynamic listening port.

**Comment by dtuantran** [comment]
Hello @sqhan-Husky
You should use your port 9090 for your ```.env```. Because the port 9000 in your Minio configuration is for the console admin and codalab can't access to your files.

**Comment by sqhan-Husky** [comment]
@dtuantran
l have tried port as 9090. 
It seems that the process are still failed because the problem of cross-region.
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/45597101/144388046-a1629206-18a2-4dc3-95f3-95540a735d5b.png">

**Comment by loicsarrazin** [comment]
@sqhan-Husky have you specified the policy of your minio buckets?  
https://github.com/codalab/codalab-competitions/wiki/Minio-storage#:~:text=Using%20the%20minio%20client%2C%20configurate%20the%20buckets%20policies

**Comment by loicsarrazin** [comment]
Also, @sqhan-Husky, make sure your env follow these setting :   

https://github.com/codalab/codalab-competitions/wiki/Minio-storage#:~:text=Modify%20your%20codalab%2Dcompetition%27s%20.env%20to%20use%20the%20settings%3A  
  
 Refer in the host and endpoint to your minio container (minio) instead of your IP, especially if you are using WSL, and make sur they are both on the same network (both docker compose in the same folders, or configure network within them)

**Comment by sqhan-Husky** [comment]
@loicsarrazin 
I re-install the minio in accordance with newest wiki and the minio container name has been configured in my hosts:

Here's the log of the minio docker:
![image](https://user-images.githubusercontent.com/45597101/144539111-03caf4eb-eb63-4797-bd24-aacd05582573.png)

I try to specifiy the policy. I'm not sure about the difference between the ip of `http://172.17.0.1` in your template and `http://172.18.0.2` in my logs . Both of them fail in the step of setting policy.
![image](https://user-images.githubusercontent.com/45597101/144537864-d20f15c8-3f9e-4194-9a45-fba4d66111e0.png)

![image](https://user-images.githubusercontent.com/45597101/144538786-ff1b7f9e-2e4a-47db-9c22-487b90fbe92c.png)

**Comment by sqhan-Husky** [comment]
@loicsarrazin  
l just ignored the previous error and retry to create a competition.
Surprisingly, it succeeds.
It seems normal in the process of submitting a test too.

Actually, I'm wondering which step affects the current result......

**Comment by loicsarrazin** [comment]
I think it has to do with an image being pulled for the first time. Good to know you could make it work.  
  
I'm closing but feel free to re-open if you have another related problem.
