### ISSUE TITLE
The file cannot be uploaded on the codalab server

### ISSUE THREAD

**Issue by Junjue-Wang** [codalab/codalab-competitions#3053]
The file cannot be uploaded on the codalab server
![image](https://user-images.githubusercontent.com/27996790/144418812-dad0f9d9-eafc-40db-b1da-e942677591bd.png)

**Comment by yoonseok312** [comment]
Same issue happening as well in MIND News Recommendation competition.

**Comment by Didayolo** [comment]
Hello,

What are the size of the submissions you are trying to upload?

**Comment by ankitagr01** [comment]
same with me as well. 
size of file 60MB, 
competition: https://competitions.codalab.org/competitions/20127#participate-submit_results

**Comment by Junjue-Wang** [comment]
> 

The competition url: https://codalab.lisn.upsaclay.fr/competitions/424
The submitted zip (5.79 M) is also attached:
[submit_test.zip](https://github.com/codalab/codalab-competitions/files/7646037/submit_test.zip)

**Comment by LJOVO** [comment]
same here in other competition: https://competitions.codalab.org/competitions/17136#participate

**Comment by yoxu515** [comment]
same in https://competitions.codalab.org/competitions/19544#participate-submit_results
file size is around 60M

**Comment by Didayolo** [comment]
Dear all,

You can follow the status here: https://groups.google.com/g/codalab-competitions/c/O6QINjImN7A

> Dear Codalab users,
> 
> After the successful migration from py2 to py3, we have now a new stable instance py3. Please do use this instance from now, you won't face any problem !
> 
> Beside this operation, we also need to migrate completely our storage solution, which could not grow anymore, to a bigger one. We will also add more rules in a near future to help you keeping a sensible use of our courtesy resource, to prevent that some greedy competitions are penalizing the whole community.
> 
> After the migration yesterday, we are facing some difficulties, please stop sending submissions until the storage is back. We will inform you here. We will flush the submission queue when the problem will be solved, otherwise the platform might crash.
> 
> Please be patient, we are working actively on the issue. We are really sorry for the inconvenience.
> 
> Don't forget you are always welcome to join our developers community to help keeping this platform healthy, using state of the art technologies and operational for our scientific needs.
> 
> Best regards,
> 
> AC.Letournel - Codalab team

**Comment by dmlan** [comment]
faild to upload file!
https://competitions.codalab.org/competitions/36050#participate-submit_results
![image](https://user-images.githubusercontent.com/29965978/144627726-4eeec1e6-c248-48bf-b927-b49aef825e26.png)

I try to change to new site(https://codalab.lisn.upsaclay.fr/) . but I can't find "XMRec WSDM Cup".

**Comment by dtuantran** [comment]
Hello,
It seems that our reverse-proxy is misconfigured, then the upload file is limited at 1 MB. When you have a bigger file, you will get this error. Unfortunately, our admin is off work now. Please be patient until Monday.
Regards,

**Comment by dtuantran** [comment]
Dear all,
We have fixed the configuration. Your submissions shouldn't have this blocking error from now. Please re-try and tell us if you still have any issue.
Thank for your comprehension.
Bests,

**Comment by marcevrard** [comment]
Hello,
It does not seem to process the upload on https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition
I've tried to upload the Aerial Image Recognition (~380 MB zip).

**Comment by unilight** [comment]
Same as @marcevrard, I am failing to upload new competitions to the new server again.
I can successfully upload to the old server (https://competitions.codalab.org/).
Is there a storage issue again?
Thanks!

**Comment by Didayolo** [comment]
@marcevrard @unilight I just tried and it worked. Is it working now for you too?

**Comment by marcevrard** [comment]
It worked for me when I used the connection from the lab, which is much faster, but not from home.
