### ISSUE TITLE
SemanticKITTI Semantic Segmentation Competition submission is not finished for a long time

### ISSUE THREAD

**Issue by snuffle-PX** [codalab/codalab-competitions#3055]
SemanticKitti Single Scan Semantic Segmentation:
https://competitions.codalab.org/competitions/20331#participate-submit_results

User: yhzhao
Submission attempt 4 (Single scan)

Problem description:
This submission is submitted 4 days ago, but its status is still _Submitting_.

The [stdoutput log](https://competitions.codalab.org/my/competition/submission/1034826/stdout.txt) shows:
`404
Could not find the page you requested.
If you are the challenge organizer and this URL previously pointed to a valid competition and it is now missing please contact us at info@codalab.org for more information.

If this is in error, please file a bug report. For more information about CodaLab, check out the wiki.`

Is this a server bug?

**Comment by Josh00-Lu** [comment]
same!!!

**Comment by dtuantran** [comment]
Hello,
Last week, we had some problems with the storage migration. Maybe your issue is related, we reverted back the migration and Codalab should works well as normal since week-end. You can retry again your submissions again.
Regards,

**Comment by snuffle-PX** [comment]
> Hello, Last week, we had some problems with the storage migration. Maybe your issue is related, we reverted back the migration and Codalab should works well as normal since week-end. You can retry again your submissions again. Regards,

I submitted again and it works, thank you!
