### ISSUE TITLE
Lits challenge

### ISSUE THREAD

**Issue by jiangllll** [codalab/codalab-competitions#3056]
The committed ZIP file remains committed！
![image](https://user-images.githubusercontent.com/35950110/144550355-41477ecc-754d-4b14-8955-86e6e5cefeaa.png)

**Comment by Didayolo** [comment]
Hi,

I think this is due to the current storage migration. We are doing our best to solve it quickly.

To stay informed, follow: https://groups.google.com/g/codalab-competitions/c/O6QINjImN7A

Sorry for the inconvenience.

**Comment by jiangllll** [comment]
I think you are right,thanks.


 
---Original---
From: "Adrien ***@***.***&gt;
Date: 2021/12/3 19:01:14
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [codalab/codalab-competitions] Lits challenge (Issue #3056)




 
Hi,
 
I think this is due to the current storage migration. We are doing our best to solve it quickly.
 
To stay informed, follow: https://groups.google.com/g/codalab-competitions/c/O6QINjImN7A
 
Sorry for the inconvenience.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
