### ISSUE TITLE
Submission running for 20h + unable to upload files

### ISSUE THREAD

**Issue by marialeyvallina** [codalab/codalab-competitions#3058]
Yesterday at 15h server time I uploaded a submission in https://competitions.codalab.org/competitions/34623. It went to "running" status immediately and it stayed like that until now. Previous submissions did not take this long, so this is definitely unusual. Moreover, I tried making a new submission, and I get an "unable to upload file" error.

**Comment by acletournel** [comment]
You can follow the incident here: https://groups.google.com/forum/#!forum/codalab-competitions

**Comment by Didayolo** [comment]
Related to 
- #3053
