### ISSUE TITLE
Competition description cannot be changed

### ISSUE THREAD

**Issue by norahollenstein** [codalab/codalab-competitions#3059]
Hi,
I'm an organizer of this competition: https://competitions.codalab.org/competitions/36415
I would like to change the description, but it does not update even though I see it changed in the editor.

Could you please help me fix this?
Thanks!

Nora

<img width="1185" alt="Screenshot 2021-12-03 at 09 53 29" src="https://user-images.githubusercontent.com/17772234/144574001-bf433ff2-da4a-44f3-89c2-774831443d22.png">
<img width="1305" alt="Screenshot 2021-12-03 at 09 54 31" src="https://user-images.githubusercontent.com/17772234/144574058-8e9c1484-50f0-4b41-a020-dae023f6d571.png">

**Comment by Didayolo** [comment]
Hi,

Maybe this is related to #3053 ?

**Comment by norahollenstein** [comment]
Maybe, although I edited directly in the editor, didn't try to upload any new files.

**Comment by norahollenstein** [comment]
Hi, are there any news about this? I still cannot update the description.
Thanks,
Nora

**Comment by Didayolo** [comment]
Hello,

Could you please add me as an admin of the competition? My ID is `pavao`.
It may not be possible if the changes don't get saved of course.

If no changes get saved (not specifically the description), then it could be linked to the second part of this issue: #2686
Usually in this case, there is a problem preventing from saving but no clear error message is given.

**Comment by norahollenstein** [comment]
Hi,
I've added you as an admin.
Thanks!

**Comment by Didayolo** [comment]
Hi,

It is working well. I could add "TEST" at the beginning of the description:

![issue-codalab](https://user-images.githubusercontent.com/11784999/146035726-6d1c7d77-4482-4ef9-8f03-1f716a8f9eb7.png)

Maybe it was due to the on going migrations. I've put back the old description to avoid changing your work.
Let me know if you face any issue.

**Comment by norahollenstein** [comment]
Thank you!
