### ISSUE TITLE
 Some questions about UAVid2020 Benchmark submitting

### ISSUE THREAD

**Issue by youyi-jia** [codalab/codalab-competitions#3063]
I would like to ask a question about UAVid2020 Benchmark submitting. I encountered an unsolved problem in the process of submitting the results. After submitting the results, I was always reminded that I lacked the predicted results of a certain graph. The following error message is  :
`AssertionError: Prediction incomplete, cannot find prediction: /tmp/codalab/tmpVBHQOA/run/input/res/seq21/Labels/000600.png`
        But I double-checked and found that this image exists in my.zip file. Behinds, I checked each sequence and found that the file was complete, 15 sequences, 150 graphs. In addition, I just wrote a little bit of code to compare the Example Submission given by the official website with mine, and found that the path and name of the file in my result folder and Example Submission on the official website were exactly the same
        However, there will always be an error after Submission, and I will also be prompted with this error when I copy my file into the file addition of Example Submission and then submit it after compression. I don't know the reason, can you tell me that?
        Finally, is there any requirement for submitting the result? Besides the path, does it have any requirements on the compression mode of the submitted compression package?

**Comment by Didayolo** [comment]
Hello,

Sometimes it is needed that the files are zipped directly, without directory structure.

Is the example submission working well for you?

Anyway, this problem seems to be linked with the UAVid2020 challenge, not the platform in itself. You should contact the competition organizers.

**Comment by youyi-jia** [comment]
已收到
