### ISSUE TITLE
Failed to submit multiple ZIP files in multiple Windows at the same time!

### ISSUE THREAD

**Issue by longmalongma** [codalab/codalab-competitions#3066]
Failed to submit multiple ZIP files in multiple Windows at the same time! I checked that the ZIP file was correct, sometimes it failed and sometimes it succeeded

![image](https://user-images.githubusercontent.com/40291722/147189064-e4a020f0-0482-490b-ae76-753a740ff571.png)

**Comment by Didayolo** [comment]
Hello,

When you try to upload just one file at a time in one window allow, does it work?

**Comment by Didayolo** [comment]
I close this issue because it's staling.
