### ISSUE TITLE
(Submission) Failed, competition phase is being migrated, please try again in a few minutes

### ISSUE THREAD

**Issue by marcevrard** [codalab/codalab-competitions#3068]
The competition has 2 phases, and the second phase is starting soon (January 1, 2022, at 00:01).
However, 1st phase submissions are failing with this message for about 2 days now: 
`Failed, competition phase is being migrated, please try again in a few minutes`

Competition link: https://codalab.lisn.upsaclay.fr/competitions/573
(`pavao` and `tthomas63` have been added as admins)

**Comment by Didayolo** [comment]
Hello Marc,

The submissions are failing before even trying to compute, right?

Because in the submissions panel, everything seems fine. I'll have a deeper look at it soon.
