### ISSUE TITLE
compute queues are congested and failed to submit results

### ISSUE THREAD

**Issue by dalision** [codalab/codalab-competitions#3070]
Hi, Codalab maintainers, it seems that the platform has had some problems since afternoon. Participants failed to submit results while everything went well before and we didn't change any settings. It seems that computation containers are in the congestion status because the page responds following warnings "Warning: The compute queues are congested, please wait for existing jobs to process before submitting more. Thanks for your patience!". However, it still didn't work after a long time waiting. I would be appreciated it if you'd like to check the platform.

**Comment by EugenioTL** [comment]
Same issue for me in competition 621 where 477 participants are involved.

**Comment by Vigilans** [comment]
Same problem. Although now the congested warning disappeared, the problem still exists (Stuck on submitting and failed for a short time). Maybe it's because of this stuck issue that the compute queues are congested.

**Comment by EugenioTL** [comment]
Thank you @Didayolo. We are waiting for your news as soon as possible. If you need some kind of external feedback just let us know it!

**Comment by Didayolo** [comment]
Thank you. It seems that custom queues are failing too. We are currently working on solving the problem.

**Comment by lilaspourpre** [comment]
> Thank you. It seems that custom queues are failing too. We are currently working on solving the problem.

Dear @Didayolo ,

Yes, for some reason, we are not able to upload submission files to our queue called `toxic` ([competition 642](https://codalab.lisn.upsaclay.fr/competitions/642)) Submitted files stuck on `Submitting` and then are changed to `Failed` for a short time too. Interestingly, the file size is 155 bytes and they are not properly uploaded. 

Moreover, `View predict error log`, `Download output from prediction step`, `Download output from scoring step`, `Download private output from scoring step` return the 404 page.

![img](https://i.ibb.co/2cf3SPY/s.jpg)

**Comment by Didayolo** [comment]
Nice catch. It seems to begin to work again. However, the size displayed are still a bit too small.

**Comment by Didayolo** [comment]
@All please try to submit to see if it's working now

**Comment by EugenioTL** [comment]
I have tried 3 times, but still failed

**Comment by lilaspourpre** [comment]
For me, it is stuck on `Submitted` now with 0 bytes, @Didayolo 

![image](https://i.ibb.co/fGjTkqR/j.jpg)

**Comment by EugenioTL** [comment]
Any idea @Didayolo? Isn't it possible to empty the queue and hard reset? Being the most popular competition with more than 450 participants stuck for 5 days, it would be preferable to lose the sent data and restart as soon as possible rather than other options. Tell us if we can help, but we must restart the competition as soon as possible. Thanks.

**Comment by lilaspourpre** [comment]
@Didayolo finally, my submit from 11 hours ago is `finished` !!! And now again, my new submit is currently `Running`. Apparently, everything is working now on custom queues! Thanks!

**Comment by EugenioTL** [comment]
I have just tried another submission, still failed :/

**Comment by Didayolo** [comment]
@all
Current situation:
- Everything is **solved** in the Python3 server [codalab.lisn.fr](codalab.lisn.fr)
- The queue is **not congested** anymore on the old server [competitions.codalab.org](competitions.codalab.org)
- Submission takes longer than usual to start being compute on the old server
