### ISSUE TITLE
Upload dataset failure

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#3071]
This issue concerns:
https://codalab.lisn.upsaclay.fr/

When uploading a new dataset (file size 2.5 MB), an error occurs" The Codalab site is currently unavailable". The dataset did NOT get uploaded.

<img width="1145" alt="Screen Shot 2022-01-08 at 2 44 54 PM" src="https://user-images.githubusercontent.com/7594063/148646521-7ed99b63-99a4-4f9d-b7bc-90658536e580.png">
<img width="1149" alt="Screen Shot 2022-01-08 at 2 09 48 PM" src="https://user-images.githubusercontent.com/7594063/148646593-96b36581-5dd9-4a9f-951b-1b443fba6a24.png">
<img width="1024" alt="Screen Shot 2022-01-08 at 2 44 18 PM" src="https://user-images.githubusercontent.com/7594063/148646653-156e044b-2a39-4307-8110-b626f1a14e22.png">

**Comment by Didayolo** [comment]
I just tried and it worked, even if the uploading was a bit slow.

**Comment by dtuantran** [comment]
Hi,
We had a power outage of some storage servers last weekend. Then, our storage were in read-only mode. That why the uploading actions were unavailable. Our storage returned back to normal, this issue should be resolved.

**Comment by Didayolo** [comment]
It is now working perfectly fine.
