### ISSUE TITLE
Is it still possible to download NTIRE 2020 Spectral image dataset?

### ISSUE THREAD

**Issue by bsun0802** [codalab/codalab-competitions#3072]
1. This was a completed competition, but I would like to research with the dataset. Would it be possible to download the dataset?
2. This is the URL to the challenge https://competitions.codalab.org/competitions/22225 and https://competitions.codalab.org/competitions/22226 which I would like to access the data. It need register in the "participate" tab, and I did it. But I don't know if it will work because the competition has closed.

**Comment by Didayolo** [comment]
Hi,

Please contact the competition organizers directly. 
Their emails can be found here [https://competitions.codalab.org/competitions/22226#learn_the_details](https://competitions.codalab.org/competitions/22226#learn_the_details)
