### ISSUE TITLE
No such file or dictionary

### ISSUE THREAD

**Issue by ground-truth** [codalab/codalab-competitions#3073]
When I submit results in TVC Evaluation, I get the error as follows:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpxbvhjU/run/program/evaluate.py", line 177, in 
    start_eval()
  File "/tmp/codalab/tmpxbvhjU/run/program/evaluate.py", line 161, in start_eval
    file_paths[split_name]["solution"])
  File "/tmp/codalab/tmpxbvhjU/run/program/evaluate.py", line 64, in __init__
    self.prediction = self.load_captions(prediction_path, is_ground_truth=False)
  File "/tmp/codalab/tmpxbvhjU/run/program/evaluate.py", line 70, in load_captions
    captions = load_jsonl(filename)
  File "/tmp/codalab/tmpxbvhjU/run/program/evaluate.py", line 23, in load_jsonl
    with open(filename, "r") as f:
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpxbvhjU/run/input/res/tvc_val_submission.jsonl'

But my res.zip actually contains two files: tvc_test_public_submission.jsonl and tvc_val_submission.jsonl.

**Comment by Didayolo** [comment]
Can you please provide:
- The URL of the competition
- The submission zip file

Also, did you zip your files directly or did you include a directory structure?

**Comment by ground-truth** [comment]
Thanks for your replay!
This is my URL of the competiton: https://competitions.codalab.org/competitions/23109#participate-submit_results
This is my submission file:
[res.zip](https://github.com/codalab/codalab-competitions/files/7838582/res.zip)

I zip my files with python and code is:
 with zipfile.ZipFile("res.zip", mode="w") as f:
    f.write("res/tvc_test_public_submission.jsonl")
    f.write("res/tvc_val_submission.jsonl")
And there are only two files in the .zip

**Comment by Didayolo** [comment]
I think that the directory `res` is part of the architecture of CodaLab. You should try to zip directly your files in the root of the ZIP file, without a `res` directory.

**Comment by ground-truth** [comment]
I replace res with first_submit and zip the file in command line, but the same error occurs.
[first_submit.zip](https://github.com/codalab/codalab-competitions/files/7838993/first_submit.zip)

**Comment by Didayolo** [comment]
Try to remove the folder instead of renaming it.

**Comment by ground-truth** [comment]
Yes, I "mv first_submit submit_test" and "zip -r submit_test.zip submit_test", but the same error

**Comment by Didayolo** [comment]
What I mean is that you do directly:

```
zip -r submit_test.zip tvc_val_submission.jsonl tvc_test_public_submission.jsonl
```

**Comment by Didayolo** [comment]
I close for now, feel free to re-open the issue if you still need help.
