### ISSUE TITLE
Access denied when downloading leaderboard CSV

### ISSUE THREAD

**Issue by iabufarha** [codalab/codalab-competitions#3074]
Hi, 

I keep getting an access denied message when trying to download the leaderboard CSV file. Is it related to the issues with submission queues? 
<img width="750" alt="Screenshot 2022-01-13 at 2 41 34 pm" src="https://user-images.githubusercontent.com/33257671/149350881-42ccf4f6-9342-4972-ad54-92046d6147e9.png">
.

**Comment by Didayolo** [comment]
Hi,

Indeed we have a general problem right now, I think it is linked. Thank you for your useful input. We are currently working on it.

**Comment by dtuantran** [comment]
Hi,
Could you provide your competition URL, please ?
Thanks

**Comment by iabufarha** [comment]
Hi, it is still private and this one is just for testing that everything is working fine. I will be deleting it later, but here is the link:
https://codalab.lisn.upsaclay.fr/competitions/1023?secret_key=e3d05954-48f5-4063-8c89-d84e762dd911

**Comment by Didayolo** [comment]
Can you please retry?

We have solved the recent problems. Maybe this one is gone too.

**Comment by iabufarha** [comment]
Hi,
Now it takes me to a blank page and nothing is being downloaded.

**Comment by Didayolo** [comment]
Can you please add me as an admin of the competition so I can try?
I won't change any setting.

My CodaLab ID is `pavao`

**Comment by iabufarha** [comment]
I just added you

**Comment by Didayolo** [comment]
You are trying to use the `Download CSV` button in the `Results` page, right?

For me it's working, I can download the CSV. However, it doesn't contain any value, only the text "Not allowed, phase is blind".
I think you need to edit the setting to put the leaderboard in public mode before downloading. But the downloading seems to work.

**Comment by iabufarha** [comment]
For me, it is a blank page when using safari and an 'Access denied' page when using chrome.
There are 2-3 submissions for one of the phases (subtasks) and that's the one I am using for testing.
I tried setting the leaderboard for that specific 'phase' to default, but the issue is still there.

**Comment by Didayolo** [comment]
I'm using Firefox and I can download the CSV leaderboard for all phases (even if the CSV is empty because the phases are blinds).

**Comment by iabufarha** [comment]
Considering that you are admin now, shouldn't this make the leaderboards visible to you? 
I just tested firefox and the same issue is still there, nothing is being downloaded when clicking 'Download CSV '.
 If you check 'Task A - English', the leaderboard is not empty.
Also, I just noticed that there is an issue with the 'Teams' tab too. It says 'The CodaLab site is currently unavailable'.

**Comment by Didayolo** [comment]
Yes, the leaderboard is visible to me. However, it seems that the option of having a blind leaderboard prevents the CSV to be filled up.

However I still can download the CSV. I don't know what's wrong on your side.

> Also, I just noticed that there is an issue with the 'Teams' tab too. It says 'The CodaLab site is currently unavailable'.

Good catch, it's indeed not working. I'll investigate that.

**Comment by iabufarha** [comment]
I tested downloading the leaderboard using Safari, Brave,FireFox, Chrome. All of them of give a blank page except chrome, which gives the 'access denied' message. I tried with another copy of the competition and I still have the same issue.

**Comment by Didayolo** [comment]
I'm sorry I can't reproduce your bug.

**Comment by iabufarha** [comment]
Hi, I started my official competition. The same issue is still persistent there. Also, the participants are getting the 'access denied message' when trying to download the scoring program error log.

**Comment by Didayolo** [comment]
I've just requested to participate in the competition (ID: `pavao`) in order to try by myself.

**Comment by iabufarha** [comment]
I just added you. Personally, I didn't have this issue while testing, but one of the participants was complaining about it. For me, the persistent issue is the downloading the leaderboard as CSV😅.

**Comment by Didayolo** [comment]
> For me, the persistent issue is the downloading the leaderboard as CSVsweat_smile.

Strange! Did you try (at least on the test competition) to make the leaderboard public (instead of hidden) and then re-try to download?

**Comment by iabufarha** [comment]
I tried that and I am still getting the same message.

**Comment by Didayolo** [comment]
In issue #2490, a new comment said:

> When we tried to open any of the links "View scoring output log, Download output from scoring step, Download private output from scoring step", we got "Access to codalab.lisn.upsaclay.fr was denied".

It seems to be the same issue. The issue seems to be occurring when the leaderboard is private. I'll dig into it.

**Comment by iabufarha** [comment]
Hi,
Yes, I checked with the participants. It seems that they thought it is an issue because they didn't get any results (we have the leaderboard and results set to private)
I was wondering if there are any updates regarding this issue?

**Comment by Didayolo** [comment]
For record: @hyejwon got the same error.

> I was wondering if there are any updates regarding this issue?

No big news for now, we are trying to make progress on this.

**Comment by mmvr-neurips** [comment]
I keep seeing a white screen when I try and download csv

**Comment by juliojj** [comment]
Hi,
same problem here when trying to download the .csv file from the leaderboard (as organizer) -> resulting in a white page (using Firefox) or "Access to codalab.lisn.upsaclay.fr was denied" using Chrome.
Best

**Comment by Didayolo** [comment]
I also noted that I can't `wget` to download the leaderboard as CSV from command line. However, it works on the [old server](https://competitions.codalab.org/).

**Comment by fchuffar** [comment]
Dears, 

First of all thank you for your work around the codalab platform. It is a wonderful tool that I use for teaching and research.

On the old server I can dowload the leaderbord to: 
https://competitions.codalab.org/competitions/28931?secret_key=156ec53c-3ae2-4788-ac69-1eb11c467910

On the new server I have the same issue as described:
 https://codalab.lisn.upsaclay.fr/competitions/8696?secret_key=3f32bbfc-9942-4e60-b241-bd10300d1bce

I am interested about a solution.

Best regards,

**Comment by dtuantran** [comment]
Dear all,

This issue is due to our access control. You aren't added as **Admin** of your competition automatically event you created it. Once you add your account into **Admins** field of your competition **Edit** page, you can download your leaderboard CSV.
For example:
![image](https://user-images.githubusercontent.com/7440668/233010580-4d055b28-e7ee-47fa-979d-c818a6cdea54.png)

Please tell us if you still have some issue.
Regards,
