### ISSUE TITLE
Uploading an image to codalab

### ISSUE THREAD

**Issue by rafariva** [codalab/codalab-competitions#3076]
Is there a way to upload an image in png format and use skimage with opencv in the installed python. how to use or install the aforementioned libraries?

**Comment by Didayolo** [comment]
Hi,

Are you a competition organizer or participant?

Where/when exactly do you want to upload?

Do you wish to have the library used during the evaluation of submissions?

**Comment by Didayolo** [comment]
Basically if you wish to customize the environment in which the submissions are evaluated, you just need to set a "competition Docker image" that contains all the libraries needed.

You can use an existing Docker image, fork one and update it (e.g. `codalab/codalab-legacy:py37`) or create your own from scratch (harder).

I hope this helps. If you still need help, feel free to re-open this issue or to create a new one providing more details.
