### ISSUE TITLE
Remove `.env_production_sample`

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#3078]
I think `.env_production_sample` is obsolete, and we want to have only one sample configuration file (`.env_sample`).

We need to clarify this and keep only one file.

**Comment by Didayolo** [comment]
@bbearce Hi, I mention you here in case you are interested in figuring out the differences between `.env_sample` and `.env_production_sample`, as you are already working with the environment file.

**Comment by bbearce** [comment]
I work with this weekly. I can merge these into a final .env_sample. Let me look into it. I'll make a branch on my fork for this and mess with it and then submit a PR.
