### ISSUE TITLE
Unable to show method name on leaderboard

### ISSUE THREAD

**Issue by yizhou-wang** [codalab/codalab-competitions#3080]
Method meta information is able to submit but the method names are not shown on the leaderboard. It would be very helpful if the method name can be shown on the leaderboard for results comparisons. Hope this component can be available in the future. Thanks a lot!

**Comment by yizhou-wang** [comment]
Hi @Didayolo 

I mean that during submission, participants can input their method name, descriptions, URL, etc. But that information is not available on the leaderboard. I think it would be better to also show the method name instead of the user name only on the leaderboard for each submission. 

I believe the above functionality must set "Enable per submission metadata" right? Thanks!

**Comment by taeinkwon** [comment]
Hi,
I also wonder if we can show meta information on the leaderboard.
Thank you.

**Comment by Didayolo** [comment]
Merged into the bigger issue.
