### ISSUE TITLE
MISP Challenge 2021(Task1)

### ISSUE THREAD

**Issue by hyejwon** [codalab/codalab-competitions#3087]
my competition: https://codalab.lisn.upsaclay.fr/competitions/887#participate-submit_results
The following error message appears when submitting the file.
![image](https://user-images.githubusercontent.com/71366457/150621958-8ced0ed9-f566-4aef-8052-422868527473.png)

error
![image](https://user-images.githubusercontent.com/71366457/150621973-eadcb343-c21a-4659-9030-3e77bd109b3f.png)

I failed submission

**Comment by hyejwon** [comment]
The format of my file is a zip file in which the txt file is compressed, and it is the same as the submission format of the competition.

**Comment by Didayolo** [comment]
Hello,

> Plus, The format of my file is a zip file in which the text file is compressed, and it is the same as the submission format of the competition.

What do you mean? Do you have a submission that works and one that does not work?

I don't think the warning you mentioned is related with the error (indeed it's a common warning). You should try to read more logs (click on the `+` button and look up for "scoring error logs", etc.)

**Comment by Didayolo** [comment]
I close this issue now.

If needed, re-open it or create a new issue with more details, especially after looking at the detailed logs as suggested.

**Comment by ssbilakeri** [comment]
i also face same issue. any solution ?
