### ISSUE TITLE
Haven't received verification email when signing up

### ISSUE THREAD

**Issue by GabrielaReyna** [codalab/codalab-competitions#3088]
Hi,

I signed up to the webapp on saturday and haven't received the verification email. I already checked the junk/spam folder and it is not there. I used my university email when registering. 

I would appreciate if you can help me with this matter.

Best,
Ana

**Comment by Didayolo** [comment]
Hi,

This is strange. When I try it works for me, but someone else has reported a similar issue: 
* #3083

He/she was also using an University mailing service.

Are you trying to sign up in [codalab.lisn.fr](https://codalab.lisn.fr/)?

**Comment by GabrielaReyna** [comment]
Hi,

Yes, that is the server I signed up for. What can I do about this? 

Best,
Ana

**Comment by Didayolo** [comment]
Have you tried contacting your email providers?

On my side I'll check if I can find a way to confirm accounts by hand.

**Comment by GabrielaReyna** [comment]
Hi there,

No, I haven't contacted my email provider. I contacted the competition organizers and they allowed me to use my personal email to register (gmail) which worked.

Best,
Ana

**Comment by Didayolo** [comment]
OK, so should I consider this issue as resolved?

I guess our email bot is working, but most University mailing services as strong filters.

**Comment by Didayolo** [comment]
Post-it: I've updated the Wiki with the administrator procedure to accept an email address "by hand" :

https://github.com/codalab/codalab-competitions/wiki/Dev_Administrator-Procedures
