### ISSUE TITLE
Submissions not processing for competition

### ISSUE THREAD

**Issue by sorensenjs** [codalab/codalab-competitions#3089]
If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` and `tthomas63` as admins to your competition so they may access it.
2. Please post a link to your competition.

We are showing a backlog of about 16 incomplete submissions in the "Submitting" state.
https://competitions.codalab.org/my/competition/34175/submissions/?page=48&phase=54851

**Comment by shervin64** [comment]
Also seeing this for another competition.

Is there an issue with the system?

**Comment by 763337092** [comment]
https://competitions.codalab.org/competitions/34175

**Comment by TimotheeMickus** [comment]
We've encountered a similar issue with our competition as well (https://competitions.codalab.org/competitions/34022).

**Comment by Perez-AlmendrosC** [comment]
Hi, 
It's also the same in our competition (https://competitions.codalab.org/competitions/34344). Any help with this?

**Comment by yjin990** [comment]
Hi there,

I have encountered the same situation in this competition (https://competitions.codalab.org/competitions/24122). Any help would be appreciated!

**Comment by xujunrt** [comment]
Hi,
It's also the same in our competition (https://competitions.codalab.org/competitions/27320). Any help with this?

**Comment by jerbarnes** [comment]
Here too: [https://competitions.codalab.org/competitions/33556](https://competitions.codalab.org/competitions/33556)

**Comment by WangZX-0630** [comment]
Plus one: https://competitions.codalab.org/competitions/18467

**Comment by tepanee** [comment]
another one: https://competitions.codalab.org/competitions/26537

**Comment by Didayolo** [comment]
Hi,

Indeed, the old server is completely stuck. We are looking into this problem.

If this solution can be useful and possible for any of you, I advice you to move the competitions to the [new server](https://codalab.lisn.fr/) as it is more stable and up-to-date.

**Comment by Didayolo** [comment]
> Dump creation is also not working, so migration to new server is currently infeasible.

Thank you for this useful additional information.

**Comment by merryjanejian** [comment]
here too :https://competitions.codalab.org/competitions/36425

**Comment by JialianW** [comment]
Can you help with this: https://competitions.codalab.org/competitions/20128

**Comment by Didayolo** [comment]
Dear @all,

The platform worker seems to be taking up jobs again. Hopefully all pending jobs (submissions and dumps) will be absorbed soon. It might take some time. 

Sorry for the inconvenience.

**Comment by Didayolo** [comment]
The platform worker has finally caught up all pending jobs. The dumps should have been created now.

Regarding the submissions, now, the compute workers still need some time to process everything but it is progressing.

**Comment by Didayolo** [comment]
Last update: everything got computed.

**Comment by 763337092** [comment]
Stuck again in https://competitions.codalab.org/competitions/34175
