### ISSUE TITLE
Sign up with Specific mailbox-For Verify-No email received

### ISSUE THREAD

**Issue by dongzhiwu** [codalab/codalab-competitions#3096]
Hello，
  We wanted to register for the competition using our email address @chinatelecom.cn, but we found that we could not receive the verification email after registering on the new version of Codalab（old version √）.
The competition requires us to use the company email address @chinatelecom.cn, not @qq.com.
Any solotutions？
Thanks

**Comment by Didayolo** [comment]
Hello,

Thanks for reporting. We are currently looking into this.

**Comment by Didayolo** [comment]
For some reason we struggle to get confirmation email on some mailing services (from companies or universities).

@dongzhiwu 
In order to work-around the issue and accept your account, please send an email to [info@codalab.org](mailto:info@codalab.org) using the same email address you've registered with.

**Comment by dongzhiwu** [comment]
Hello,Thanks for your help  @Didayolo 
I have sent the email as prompted using the same email address we 've registered with.
waiting for the feedback

**Comment by Didayolo** [comment]
Done and answered! Please close this issue if it works.

> Note that your experience of CodaLab may be altered: as you didn't receive the confirmation email, it is likely that you will not receive future emails from CodaLab (notifications, etc.).
> We are trying to solve this problem. In the meantime at least you should be able to log in and join the competition.

**Comment by dongzhiwu** [comment]
Thanks！！
