### ISSUE TITLE
When registering an account, I cannot receive emails. No mail blocked, no mail in mail spam. 

### ISSUE THREAD

**Issue by caicai0352** [codalab/codalab-competitions#3097]
When registering an account, I cannot receive emails. No mail blocked, no mail in mail spam.

**Comment by Didayolo** [comment]
Hello,

Thanks for reporting. We are currently looking into this.

**Comment by Didayolo** [comment]
@caicai0352 
I've seen that you've close the issue. Could you solved the problem?

**Comment by caicai0352** [comment]
I can't。I saw that a colleague submitted the same issue, so I closed it.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adrien ***@***.***&gt;; 
发送时间: 2022年2月8日(星期二) 晚上11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codalab/codalab-competitions] When registering an account, I cannot receive emails. No mail blocked, no mail in mail spam.  (Issue #3097)





 
@caicai0352
 I've seen that you've close the issue. Could you solved the problem?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Didayolo** [comment]
OK. If you wish that your email is confirmed "by hand", please send a request to [info@codalab.org](mailto:info@codalab.org).
