### ISSUE TITLE
Email not received on company/university mailbox

### ISSUE THREAD

**Issue by Didayolo** [codalab/codalab-competitions#3099]
In the new server, [codalab.lisn.fr](https://codalab.lisn.fr/), some users do not receive emails.
It seems to happen specifically on mailing services from universities and companies.
The problem is new to the Python3 version.
Example issues:

- #3096
- #3088 
- #3083 
- #3097

**Comment by dtuantran** [comment]
This issue could be caused by the email configurations of Codalab LISN which is for Codalab ORG :
```
EMAIL_HOST=smtps.codalab.org
DEFAULT_FROM_EMAIL=Codalab <noreply@codalab.lisn.upsaclay.fr>
SERVER_EMAIL=noreply@codalab.lisn.upsaclay.fr
```
I've fixed to `@codalab.org`. Let's see if the problem is resolved.

**Comment by Didayolo** [comment]
@dtuantran Any update on this?

**Comment by dtuantran** [comment]
Issue resolved with some DMARC configurations.
