### ISSUE TITLE
BadZipFile and dump error

### ISSUE THREAD

**Issue by rafariva** [codalab/codalab-competitions#3105]
I am an organizer and i having problem hosting an competition (published with participants). 
https://codalab.lisn.upsaclay.fr/competitions/1322

When participants try to upload their results, they are getting the following error.

---------------
Traceback (most recent call last):
File "/worker/worker.py", line 313, in run
bundles = get_bundle(root_dir, 'run', bundle_url)
File "/worker/worker.py", line 173, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 132, in get_bundle
with ZipFile(bundle_file.file, 'r') as z:
File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
self._RealGetContents()
File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
----------------------

also, when trying to create a dump file from the web, its said 'fail' error (no feedback). 

I already reupload reference and scoring database. still the problem. I recreate a second 'test' competition for testing with the same bundle, and it work fine. Also read similars error on the forum without success.

I had add `pavao` and `tthomas63` as admins to my competition so they may access it.
(@Didayolo  & @Tthomas63)

**Comment by Didayolo** [comment]
Hello,

Can you please provide a submission file?

**Comment by rafariva** [comment]
Hi, looks that not really matter the submission file, any zip file with any content raise this error. I attach to this post a submission testfile. 

[evaluation000.zip](https://github.com/codalab/codalab-competitions/files/8064378/evaluation000.zip)


Thanks for your help. dont know that else to do.

**Comment by rafariva** [comment]
Dear @Didayolo 
could you be able to test the submission. See in the submission that the error still appearing.

**Comment by rafariva** [comment]
When i submit again this same bundle, for a new competition, it work fine. Its any way to migrate the registered participants?

**Comment by rafariva** [comment]
seems that the "solution" is to create a new competition (without option to migrate the participants on the Publish competition). 
Looks like this BadZipFile error has years without a right solution.

**Comment by Didayolo** [comment]
> Looks like this BadZipFile error has years without a right solution.

Yes, that's a shame. We didn't manage to understand this issue yet.
