### ISSUE TITLE
About modifying username

### ISSUE THREAD

**Issue by XiaoqiangZhou** [codalab/codalab-competitions#3108]
Sir,

Could you please help me to change my username in codalab?

Current username: Xiaoqiang_Zhou
Account email: [13436433445@126.com](mailto:13436433445@126.com)
Desired username: Alex_Zhou
Alternative desired uernames: 1. Mr.Bai 2. Mr_Bai 3. Mr.XXB 4. Mr_XXB

Thanks

I have just sent an email to the 'info@codalab.org' with my email address 13436433445@126.com

**Comment by Didayolo** [comment]
Hi,

Thank you for the detailed request. Unfortunately, for some reason, I can't find your email. Can you please double check this?

By the way, is the account on [competitions.codalab.org](https://competitions.codalab.org/) or [codalab.lisn.fr](https://codalab.lisn.fr/) ?

**Comment by XiaoqiangZhou** [comment]
[](url)@Didayolo  Thanks for your reply.
My account is on codalab.lisn.fr . 
I did have sent an email to info@codalab.org. The email screenshot is here:
![捕获](https://user-images.githubusercontent.com/28076886/154873582-4a4f7581-7538-419a-b224-5d8710499121.PNG)

**Comment by Didayolo** [comment]
Done! It should be effective right now.
Best regards

**Comment by XiaoqiangZhou** [comment]
@Didayolo Thanks for your help! My username has been modified successfully!
