### ISSUE TITLE
Cannot submit the results

### ISSUE THREAD

**Issue by qing-xue** [codalab/codalab-competitions#3110]
NTIRE 2022 Efficient Super-Resolution Challenge Forum

"I tried to submit my work three times. However, (compressed 100 images which were gotten by my model) + (the same as first try, but added the readme.txt in it) + (the same as second try, but added my model in it), all the tries submitted on the workshop didn't work."

"I am facing the same issue plus the limit of the zip file seems 30Mb however 100 Super Resolved Image is about 350Mb"

**Comment by Didayolo** [comment]
I think the hard limit for submission is currently 300MB.

There is no error message when trying to upload the submission?

**Comment by qing-xue** [comment]
Think you! It works now.

**Comment by Booooooooooo** [comment]
I am trying to submit my results. Every time I try, the submit button goes gray for a couple of minutes, and I get "Sorry, fail to upload file". I retried a few times but got the same results. I think there may be some problem with the server?

**Comment by Didayolo** [comment]
> I am trying to submit my results. Every time I try, the submit button goes gray for a couple of minutes, and I get "Sorry, fail to upload file". I retried a few times but got the same results. I think there may be some problem with the server?

Hi, can you please provide more details?
- What is the competition in question?
- What file are you trying to submit?
- Did it work in the past?
- ...

Thanks.

**Comment by Booooooooooo** [comment]
> 

I am trying to submit for the NTIRE 2022 Efficient Super-Resolution Challenge. It requires a .zip file containing 100 images. I cannot submit it before because there is a maximum submission limit of 30M, which is now been removed. But I still cannot submit my .zip file (about 285M).

**Comment by wangzheyuan-666** [comment]
How did you solve it??

**Comment by Didayolo** [comment]
> Is the issue still happening?

@wangzheyuan-666 @Booooooooooo 

Thank you in advance
