### ISSUE TITLE
Can't submit in NTIRE 2022 Perceptual Image Quality Assessment Challenge Track 2 No-Reference

### ISSUE THREAD

**Issue by TianheWu** [codalab/codalab-competitions#3111]
When submmit the submission.zip, it reports:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpV_zwkd/run/program/evaluate.py", line 71, in 
    raise NotImplementedError("Check Alignment")
NotImplementedError: Check Alignment

**Comment by Didayolo** [comment]
Hello,

It seems that this error is returned by the scoring program of the competition.

You should contact the organizers directly. I think they should be aware of this problem as it is a `NotImplementedError`.
