### ISSUE TITLE
Stucked submission cannot download error log

### ISSUE THREAD

**Issue by afperezm** [codalab/codalab-competitions#3114]
I was submitting my results to the following competition:

https://competitions.codalab.org/competitions/18467

Suddenly it got stucked in "submitting" status and an alert message appeared informing about an error.

Tried submitting again the same file and now I got two submissions stucked on "submitting".

I tried to look at the scoring output log, scoring error log and downloading output from scoring step to see if I could find the problem and I obtain an error page.

This does not happen for my previous submissions for which I can see the scoring logs, so I think there is a problem with the platform.

**Comment by Didayolo** [comment]
Hello,

Sorry for the late reply, we had several bugs at once. Maybe they were linked.

Is this issue still happening?

**Comment by afperezm** [comment]
Thanks for the reply, despite those two unsubmitted submissions which remained in "submitting" state it is now allowing me to submit again. Seems it was related with those other bugs you mentione.
