### ISSUE TITLE
After the registration, the verification mail does not come 

### ISSUE THREAD

**Issue by esaruhann** [codalab/codalab-competitions#3115]
https://medici-codalab-main.eastus.cloudapp.azure.com/competitions/23

Even though I registered via this link, the verification mail is not coming. I tried 2 different mails but the result is the same.

**Comment by Didayolo** [comment]
Hello,

We are not in charge of this instance of CodaLab ([https://medici-codalab-main.eastus.cloudapp.azure.com/](https://medici-codalab-main.eastus.cloudapp.azure.com/)).

Try to contact directly the people in charge of this instance (probably the organizers of the challenges it hosts).

Thank you for your comprehension.
