### ISSUE TITLE
Can not download the test set from the link of Efficient Super-Resolution Challenge

### ISSUE THREAD

**Issue by House-Leo** [codalab/codalab-competitions#3116]
Can not download the DIV2K test set from https://codalab.lisn.upsaclay.fr/my/datasets/download/41913366-a5fc-4b27-a567-fbb2cab9103f
Get 404 warning in the page.

**Comment by Didayolo** [comment]
No news... I close this issue now.

#3121 has been solved, so most likely the link you provide is just wrong. Please contact directly the challenge organizers.

If you still need help, you can open a new issue with more details.
