### ISSUE TITLE
"Download Competition Bundle" doesn't work

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#3118]
When we click on DOWNLOAD COMPETITION BUNDLE we see an http error (see attached) 

![Screenshot from 2022-03-15 10-41-35](https://user-images.githubusercontent.com/358649/158414224-70ad8e58-254e-4042-b1f9-9bb8ce14ed1a.png)

When we instead `wget` the download URL we appear to get the HTML for a login page (see attached) --- but `wget` or `curl` specifying username/password doesn't get us our download. 

![Screenshot from 2022-03-15 10-46-30](https://user-images.githubusercontent.com/358649/158414624-4860891e-d933-4b50-a839-688d381cd2f3.png)

**Comment by Didayolo** [comment]
May be linked to #3121

**Comment by Didayolo** [comment]
I just realized this is specific to your instance. Which branch of the project are you running? `develop`? 

I suggest you log into the web server and:
```
cd codalab-competitions
git pull
docker-compose down
docker-compose up -d
```

**Comment by Didayolo** [comment]
Hello John,

I close this issue for now as it is staling, feel free to re-open it if needed!

Adrien
