### ISSUE TITLE
Impossible to get the outputs from the participants submissions

### ISSUE THREAD

**Issue by valbarriere** [codalab/codalab-competitions#3119]
Hello, 
Competition: https://codalab.lisn.upsaclay.fr/my/competition/834/ on Codalab. 
When trying to look at the output from the evaluation script of any participant submission on https://codalab.lisn.upsaclay.fr/my/competition/834/submissions/

I obtain an error 404

**Comment by Didayolo** [comment]
I tried and it seems to be solved now. Please re-open or create a new issue if you face the problem again.
