### ISSUE TITLE
IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by RenYang-home** [codalab/codalab-competitions#3120]
Hi,

I am the organizer of the competition https://codalab.lisn.upsaclay.fr/forums/1497.

Some participants meet the following problem "IOError: [Errno 28] No space left on device" when submitting files, as follows

Traceback (most recent call last):
File "/worker/worker.py", line 313, in run
bundles = get_bundle(root_dir, 'run', bundle_url)
File "/worker/worker.py", line 173, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 173, in get_bundle
metadata[k] = get_bundle(bundle_path, k, v)
File "/worker/worker.py", line 133, in get_bundle
z.extractall(bundle_path)
File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
self.extract(zipinfo, path, pwd)
File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
return self._extract_member(member, path, pwd)
File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
shutil.copyfileobj(source, target)
File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
fdst.write(buf)
IOError: [Errno 28] No space left on device

Could you please help to check what happened?

Thank you very much.

**Comment by Didayolo** [comment]
@RenYang-home 

By the way, how much space does one submission requires in your competition?

**Comment by RenYang-home** [comment]
Thanks for the reply. I think we just used the default queue. One submission requires about 500 Mb space. This error only occasionally occurs, according to the complaint from the participants. (Actually, when I tried to submit an example, I did not meet this error.) So I appreciate your help to check what leads to the problem?

Thanks a lot.

**Comment by Didayolo** [comment]
I think one of the compute workers of the default queue of CodaLab might have a problem (disk full, maybe not flushing the docker images/containers).

As each submission gets randomly assigned to one of the compute workers, each submission has some chance of failing. We will check the compute workers to spot the problem. In the meantime, you can simply re-run failed submissions.

**Comment by RenYang-home** [comment]
Thank you very much!
