### ISSUE TITLE
Cannot upload bundle competition in Codalab

### ISSUE THREAD

**Issue by tanouch** [codalab/codalab-competitions#3121]
Hello, 

We want to create a new competition hosted on Codalab. We tried and upload a new competition bundle here (https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition) but it does not seem to be working. When clicking on the button "Upload competition bundle", we get the following error:

![codalab_upload_bundle](https://user-images.githubusercontent.com/25816479/158614449-0ce0bfce-1623-42b6-9ab9-8f38e5b20360.PNG)

This error has been obtained on Chrome, Firefox, Opera and Microsoft Edge.

My user id is utanielian,
Thanks in advance,

**Comment by yael1994** [comment]
I have the same problem either. there is solution for this problem?

**Comment by oddskool** [comment]
Same here. Looks like a general bug.

Here is my stack trace in FF console:

`Uncaught TypeError: $.post(...).success is not a function
    <anonymous> https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:182
    jQuery 8
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:169
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    setTimeout handler*test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    <anonymous> https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:174
    jQuery 2
s3_create_competition:182:15
    <anonyme> https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:182
    jQuery 8
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:169
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    (Asynchrone : setTimeout handler)
    test_if_done https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:171
    <anonyme> https://codalab.lisn.upsaclay.fr/competitions/s3_create_competition:174
    jQuery 2
`

**Comment by Didayolo** [comment]
Update: nothing is shown when trying to upload a bundle but the competitions actually get created (you can check in "My Competitions" page).

**Comment by oddskool** [comment]
Inmy case I can't see the competition:

![Capture d’écran du 2022-03-17 15-22-05](https://user-images.githubusercontent.com/805252/158827366-307ab658-d3af-4aeb-850c-4eed2b9388cc.png)

**Comment by tanouch** [comment]
Hi @Didayolo 
Thanks for your time !
It does not appear in the tab "Competitions I'm in" neither...
Are we missing something ?

**Comment by Harvey5678** [comment]
Hi @Didayolo 
The competition didn't appear on my browser either. Could you fix that ASAP?

**Comment by yael1994** [comment]
Hi @Didayolo
It is still not show the competition in 'competitions I'm running' tab

**Comment by Didayolo** [comment]
It should be working again now. Let me know if you are still facing any issue (and let me know if it works too!)

**Comment by oddskool** [comment]
I was able to create a competition successfully right now.

Thanks for your time and effort in maintaining the platform :)

**Comment by Didayolo** [comment]
Thank you for your feedback and kind words!
