### ISSUE TITLE
Feature Request: When a competition bundle upload is successful, TELL THE USER

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#3125]
The title says it all: When uploading a competition bundle actually works, inform the user!

You do a great job with errors, but success is indistinguishable from the server ignoring our upload!

Thanks...

**Comment by Didayolo** [comment]
Hello,

Normally the system tells the user when the upload works. It is just a temporary error (see #3121).

I close this issue to keep track of everything in #3121.
