### ISSUE TITLE
Docker: no space left on device.

### ISSUE THREAD

**Issue by ychfan** [codalab/codalab-competitions#3128]
We meet the error for all submissions in https://codalab.lisn.upsaclay.fr/competitions/3296
Thanks!

**Comment by Didayolo** [comment]
Hello,

The problem seems to occur only on this competition. 

What space is required to compute your submissions?

**Comment by ychfan** [comment]
Hello, our docker needs 2GB space https://hub.docker.com/layers/ychfan/codalab-youtubevos/latest/images/sha256-d36ff0987b08fd702c9be53b0daa03bfd5af7b239b1b47ba2cec2876bf26eed8?context=repo

**Comment by ychfan** [comment]
But I'm not sure how much additional space is needed after decompressing the docker image.

**Comment by Didayolo** [comment]
OK but the submission in themselves, are they big? If I remind correctly it is a super resolution competition?

> We meet the error for all submissions in https://codalab.lisn.upsaclay.fr/competitions/3296

For some reason the URL does not work.

**Comment by Didayolo** [comment]
Issue staling, and URL pointing to 404 error.

I close this issue now.
