### ISSUE TITLE
Cannot import cv2 while using previous codalab-legacy:gpu

### ISSUE THREAD

**Issue by samsara-ku** [codalab/codalab-competitions#3130]
Hi, I just wanted to open my competition so I read carefully some information for making a competition.

But I got a serious problem for running my scoring program.

As you can see the screenshot, I can't import "cv2" library although I set a docker image as "codalab/codalab-legacy:gpu" which has opencv-python installation procedure.

So how can I import cv2 library in my competition?

Thanks.

![image](https://user-images.githubusercontent.com/59246456/159921018-2f151e5d-ad17-4340-97a7-00249f327277.png)

**Comment by samsara-ku** [comment]
I also followed your instruction adding admins, so I think you can access my test competition.

**Comment by Didayolo** [comment]
I think you should do some testing inside a container of the docker image `codalab/codalab-legacy:gpu`.

Try to run Python and import cv2 inside the container. If the Docker image does not suit well your competition, you can fork it, update it, and use your own version of the image in the competition (see https://github.com/codalab/codalab-competitions/wiki/User_Docker).

**Comment by Didayolo** [comment]
@samsara-ku Thank you for the update.

Before I close the issue, I was wondering: do you think we need to install these packages (`libgl1-mesa-glx` and `libglb2.0-0`) inside the `codalab/codalab-legacy:gpu` image to prevent future problems with cv2?

**Comment by samsara-ku** [comment]
Hi, @Didayolo.

Sorry, it was typo.

The correct code is `apt-get install libglib2.0-0`, not the `apt-get install libglb2.0-0`.

I missed a letter 'i' in the package name.
