### ISSUE TITLE
Unable to find image locally

### ISSUE THREAD

**Issue by Harvey5678** [codalab/codalab-competitions#3132]
***This is a template, please remove any non-relevant details to your issue***

I was going to use my own docker for the competition, however, I got this error message:

Unable to find image 'wangharvey/testserver:latest' locally
latest: Pulling from wangharvey/testserver
11323ed2c653: Pulling fs layer
bfc754d8d8c5: Pulling fs layer
c945df2bbd3a: Pulling fs layer
4f4fb700ef54: Pulling fs layer
c2791f2ed31d: Pulling fs layer
0a63f2d32c45: Pulling fs layer
ac653a4d2f00: Pulling fs layer
22d471fa01e9: Pulling fs layer
972931ebcc1c: Pulling fs layer
e8d2e3a29904: Pulling fs layer
6c7f5fbbf820: Pulling fs layer
d691393f1960: Pulling fs layer
1f9fc5d64294: Pulling fs layer
4769595ec472: Pulling fs layer
d988fcc37c30: Pulling fs layer
5c6e7513b586: Pulling fs layer
11d535e08519: Pulling fs layer
08595d42a8d2: Pulling fs layer
2a9f051b9eee: Pulling fs layer
972931ebcc1c: Waiting
e8d2e3a29904: Waiting
6c7f5fbbf820: Waiting
d691393f1960: Waiting
1f9fc5d64294: Waiting
4769595ec472: Waiting
d988fcc37c30: Waiting
5c6e7513b586: Waiting
11d535e08519: Waiting
08595d42a8d2: Waiting
2a9f051b9eee: Waiting
c2791f2ed31d: Waiting
0a63f2d32c45: Waiting
ac653a4d2f00: Waiting
22d471fa01e9: Waiting
4f4fb700ef54: Waiting
c945df2bbd3a: Verifying Checksum
c945df2bbd3a: Download complete
4f4fb700ef54: Download complete
11323ed2c653: Verifying Checksum
11323ed2c653: Download complete
0a63f2d32c45: Verifying Checksum
0a63f2d32c45: Download complete
ac653a4d2f00: Verifying Checksum
ac653a4d2f00: Download complete
11323ed2c653: Pull complete
bfc754d8d8c5: Verifying Checksum
bfc754d8d8c5: Download complete
22d471fa01e9: Verifying Checksum
22d471fa01e9: Download complete
e8d2e3a29904: Verifying Checksum
e8d2e3a29904: Download complete
6c7f5fbbf820: Verifying Checksum
6c7f5fbbf820: Download complete
d691393f1960: Verifying Checksum
d691393f1960: Download complete
1f9fc5d64294: Download complete
4769595ec472: Download complete
d988fcc37c30: Verifying Checksum
d988fcc37c30: Download complete
972931ebcc1c: Verifying Checksum
972931ebcc1c: Download complete
5c6e7513b586: Download complete
11d535e08519: Verifying Checksum
11d535e08519: Download complete
08595d42a8d2: Verifying Checksum
08595d42a8d2: Download complete
2a9f051b9eee: Verifying Checksum
2a9f051b9eee: Download complete
c2791f2ed31d: Verifying Checksum
c2791f2ed31d: Download complete
bfc754d8d8c5: Pull complete
c945df2bbd3a: Pull complete
4f4fb700ef54: Pull complete
c2791f2ed31d: Pull complete
0a63f2d32c45: Pull complete
ac653a4d2f00: Pull complete
22d471fa01e9: Pull complete
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/python3.6/dist-packages/opencv_python.libs/libavcodec-58f5339d.so.58.106.100: no space left on device.
See 'docker run --help'.

What could be the problem?
This is the link to my challenge:
https://codalab.lisn.upsaclay.fr/competitions/3087?secret_key=f88541e1-876e-4e74-b898-5accb44fabc7

I've made pavao and tthomas63 the admins. It will be awesome if you can access my competition and help me to debug.

Thank you

**Comment by Didayolo** [comment]
I think it is a common error when using a competition docker image for the first time.

Usually, re-submitting solve it.

**Comment by Harvey5678** [comment]
Hi

I got a new error message:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "python": executable file not found in $PATH: unknown.

I think the path is not correct. In my docker, on /build directory I use 

python3 -m service.LocalEvaluation --ref-data PATH/TO/REFERENCE --user-data PATH/TO/USER_INPUT --out ./report.json

to run my evaluation code. How could I set up the metadata file to let codaLab execute my evaluation program inside my own docker?

Thank you for your help

**Comment by Didayolo** [comment]
Hi,

The default metadata file looks like this:

```
command: python $program/score.py $input $output
description: Compute scores for the competition
```

https://github.com/codalab/competition-examples/blob/master/basic-competition-bundles/Iris/iris_competition_bundle/scoring_program/metadata

You can maybe edit this file to fit your case. Or maybe you just need to work on the `score.py` file of your scoring program. To simulate the functioning of CodaLab inside your Docker, I think you can run the `score.py` script.

**Comment by Didayolo** [comment]
I close this issue because it is staling. Please open a new issue with more details if you need more help.
