### ISSUE TITLE
Sorry, failed to upload file

### ISSUE THREAD

**Issue by xuzhuang1996** [codalab/codalab-competitions#3136]
hello, I'm taking part in a competition, and I'm having a problem uploading the ZIP, the error info says "Sorry, failed to upload file"

![image](https://user-images.githubusercontent.com/24559901/160598535-42d89201-0928-4a58-b77c-9a7f70626e08.png)

This seems to be CodaLab's problem. Can you tell me why？

the competition is https://codalab.lisn.upsaclay.fr/competitions/865#participate
Thanks！

**Comment by Didayolo** [comment]
Hello,

Is this issue still happening?

Did you contact the organizers?

It seems that they did not let me in the competition to do some testing. Also, I can see that some participants managed to make submissions. So I am not sure if there is really a problem or not.

**Comment by xuzhuang1996** [comment]
> Hello,
> 
> Is this issue still happening?
> 
> Did you contact the organizers?
> 
> It seems that they did not let me in the competition to do some testing. Also, I can see that some participants managed to make submissions. So I am not sure if there is really a problem or not.

Do you mean that there are other people who can submit zip to this competition ? 

The organizers thought it might be Codalab.

I'm not sure if my zip was intercepted
