### ISSUE TITLE
Test custom docker container locally

### ISSUE THREAD

**Issue by mariusbrinkmann** [codalab/codalab-competitions#3139]
I want to test a custom docker container that runs locally on my machine before I switch to Azure.

So far, I successfully run the ingestion program locally on the machine. However, if I add the `BROKER_URL` from the competition's queue or if I use the entire `.env` file, starting the docker container yields the same messages as if the container was started without the environment variables. No error messages appear.

If I submit something on the competition website, the status remains at `Submitted` and nothing appears in the docker log. Is there any way to check if the docker container is connected to the competition? There is a chance that my firewall is blocking the connection but without any error messages, I don't know how to localize the error.

**Comment by Didayolo** [comment]
Hello,

You are trying to setup a compute worker?
It should be perfectly doable. Maybe the `.env` configuration needs to be different, e.g. not including `BROKER_USE_SSL=True`.

To create the container, are you using the command from this wiki page? https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers

What do you obtain then when running `docker logs -f compute_worker` after creating the container?

**Comment by mariusbrinkmann** [comment]
Hello,

I tried running the docker container according to your wiki page using `docker run` and according to [https://codalab-competitions.readthedocs.io/en/latest/1.%20Setup%20Guide%20-%20Docker/](https://codalab-competitions.readthedocs.io/en/latest/1.%20Setup%20Guide%20-%20Docker/) using `docker-compose`. With `docker-compose` I can access the login page of RabbitMQ.

Do I have to start RabbitMQ when just using the `docker run` command? I cannot access `localhost:5555` with the following parameters:
```
RABBITMQ_HOST=rabbit
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672
```

Also, is there another way of checking if the docker container is running properly? If I submit something in my codalab.org competition, nothing appears in the docker logs. However, I don't know if it's my firewall which is blocking the connection, if I have to setup something else like RabbitMQ, or if the docker container itself is not running properly.

**Comment by mariusbrinkmann** [comment]
I just realized that there is a `.env_sample` and a `.env_production_sample`. Where is the difference and which file do I have to use?

**Comment by mariusbrinkmann** [comment]
Yes, I just want to run a compute worker. I think I mixed up the tutorials.

I tried running the following command on both, my computer as well as on an Ubuntu VM on Microsoft Azure.
```
docker run \
    -e "BROKER_URL=<broker url>" \
    -e "BROKER_USE_SSL=True" \
    --name compute_worker \
    -d --restart unless-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/codalab:/tmp/codalab \
    codalab/codalab-legacy:py37
```

In both cases, nothing happens when uploading a submission to the competition. The status of the submissions remains "Submitted" while it finishes with the default queue. Is there any way to check if any message is received on the queue?

**Comment by Didayolo** [comment]
Hello,

Please refer to this documentation page to setup a compute worker :
https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers

Here is the right command:
```
docker run \
    --env-file .env \
    --name compute_worker \
    -d \
    --restart unless-stopped \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/codalab:/tmp/codalab \
    codalab/competitions-v1-compute-worker:1.1.5
```

Don't change the docker image `codalab/competitions-v1-compute-worker:1.1.5`. `codalab/codalab-legacy` is a **competition** docker image, which means that it should just be linked to competition, not to the setup of compute workers.

Once you've run the command, use the following command to check if the compute workers is well connected to the queue:

```
docker logs -f compute_worker
```
