### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by dlinzhao** [codalab/codalab-competitions#3145]
Hello, for the SemanticKitti Single Scan Semantic Segmentation: [https://competitions.codalab.org/competitions/20331#participate](https://competitions.codalab.org/competitions/20331#participate), the error `IOError: [Errno 28] No space left on device` appears once again.  Can you check it and delete submission (username: codalab_dlz) attempt? Thanks!

**Comment by Didayolo** [comment]
Thanks for reporting this issue

**Comment by Didayolo** [comment]
We have spotted the issue. It should be fully resorbed in around 30 minutes.
