### ISSUE TITLE
Submission have been disabled by admins

### ISSUE THREAD

**Issue by seventy7796** [codalab/codalab-competitions#3146]
Why do i get the return  "Submission have been disabled by admins" when submitting a zip file? It may be caused by the commit "ac5c3ec26326dbe5fdc9e567bd8b266e9cf0011d" but i don't know the condition of blocking my submission.

Thanks in advance.

**Comment by Didayolo** [comment]
Hello,

Sorry for the inconvenience. It is due to a recent feature that we have pushed that actually causes some issues. We are looking into it.

**Comment by Didayolo** [comment]
@seventy7796 Do you have this error every time you try to make a submission?

**Comment by seventy7796** [comment]
@Didayolo  No, i dont. It didn't occur in the next day.

**Comment by seventy7796** [comment]
@Didayolo  Do you make some limitation if somebody submit two jobs in a short time? I summitted two eval jobs one by one while it is okay in the Youtube-2021 submission page. (It is Youtube 2022 now)

**Comment by Didayolo** [comment]
@seventy7796 No, there is no such limitation.

We are currently implementing a feature that can be used to block all submissions of the platform, but it seems that there is an issue with it. You should be able to submit two jobs in a short time.

**Comment by Didayolo** [comment]
Fixed by #3154
