### ISSUE TITLE
Can't access to CodaLab competitions - new server

### ISSUE THREAD

**Issue by yael1994** [codalab/codalab-competitions#3156]
I am trying to access to codalab competition and I get an error:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/45081145/163972869-b9183e5c-d911-4583-ade0-120f1fdf8ff2.png">

**Comment by jlee24282** [comment]
I am having the same problem. :(

**Comment by JohnPFL** [comment]
Me too...

**Comment by Didayolo** [comment]
Hi,

We are currently working on it. Sorry for the inconvenience.

**Comment by Didayolo** [comment]
Solved!

**Comment by juliojj** [comment]
Hi, I am getting "The connection has timed out" error when accessing https://codalab.lisn.fr/, but https://codalab.lisn.upsaclay.fr/ is working. What is the official link of the new server?
