### ISSUE TITLE
Personal registration questions

### ISSUE THREAD

**Issue by cjq4368** [codalab/codalab-competitions#3157]
I used the education mailbox to register, but I have not passed, when will I be able to pass to participate in the competition, thank you!

**Comment by dtuantran** [comment]
Hello @cjq4368 ,

Do you mean that you don't receive the validation email for the account registration ? If it's the case, thank to check your spam folder and send us your email address to info@codalab.org.

Bests,

**Comment by MarenFrederike** [comment]
I have the same problem, I tried to sign up, but never got the verification email. I also tried the fix proposed on the website, and tried logging in 5 minutes later, but this didnt help either. Can you help me?
