### ISSUE TITLE
new competition server official link?

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#3158]
Hi, I am getting "The connection has timed out" error when accessing https://codalab.lisn.fr/ (the link shown in https://codalab.org/), but https://codalab.lisn.upsaclay.fr/ is working. What is the official link of the new codalab competitions server?

**Comment by Didayolo** [comment]
Hello Julio,

https://codalab.lisn.fr/ actually simply redirects to https://codalab.lisn.upsaclay.fr/

When I click on your link (https://codalab.lisn.fr/) it is working fine for me.
