### ISSUE TITLE
Download results CSV is not working

### ISSUE THREAD

**Issue by mariusbrinkmann** [codalab/codalab-competitions#3162]
Hello,

I'm the organizer of a private CodaLab competition and it is not possible to download the results CSV. When clicking on "Download CSV", a error 403 page is shown "Access to codalab.lisn.upsaclay.fr was denied. You don't have authorization to view this page.".

However, downloading the submissions on the leaderboard works.

**Comment by dtuantran** [comment]
Hello,

Could you please give us the url of your competition and CSV result in error ?

Regards,

**Comment by mmvr-neurips** [comment]
I am also experiencing this error.
