### ISSUE TITLE
Website is not avaliable

### ISSUE THREAD

**Issue by a1salem** [codalab/codalab-competitions#3164]
Hello, 

I wanted to download the training data so I tried to signup for the website but it always shows the following messages:

"The CodaLab site is currently unavailable.
Sorry, the page you are looking for is currently unavailable.
Please try again later."
The URL: [https://miccai.westus2.cloudapp.azure.com/accounts/login/](url). And the dataset page  [http://miccai2020-data.eastus.cloudapp.azure.com/](url) is always not found.

Is there a way to fix that? or, if you can provide a way to download the dateset without the need to signup, that would be much appreciated.  

Thanks,

**Comment by dtuantran** [comment]
Dear @a1salem ,

Does your issue related to competitions.codalab.org or codalab.lisn.fr ? We've not noticed any downtime of the service.

Regards,

**Comment by crockwell** [comment]
Hi,

I'm having the same issue. I'm trying to download https://competitions.codalab.org/competitions/32377#participate 

When I try to sign in using my existing account it says "The login and/or password you specified are not correct."; when I try to forget password it says "The e-mail address is not assigned to any user account" and finally when I try to create a new account it says "The CodaLab site is currently unavailable." This has been the case all week. Can someone please assist? I just need to download the dataset.

Thanks,
Chris
