### ISSUE TITLE
[urgent] python 3 submission not working 

### ISSUE THREAD

**Issue by rajatmodi62** [codalab/codalab-competitions#3165]
hi, 
we are organizing a cvpr 2022 competition this year.
my competitions bundle's scoring program uses python3.
i am setting the docker imagae in the edit window as codalab/codalab-legacy:py37

my metadata file looks like this:
```
command: /usr/bin/python3  $program/hello.py
```
hello.py :
```
import os 
print("hello")
```
obviously, this is not a genuine scoring program, but the scoring output should yield this print statement. however, i get:
```
/usr/bin/python3: can't find '__main__' module in '' when i try to submit. 
```
could anyone please guide on what i might be doing wrong, 
this is a simple error, which seems to be a codalab issue.... 

once someone is kind enough to help with this, i will be able to run my own evaluation code in a similar way. 
thanks 
rajat

**Comment by dtuantran** [comment]
Dear @rajatmodi62 ,

We've not had any issue of this kind from other organizers. Please make sure to follow correctly our guide here : https://github.com/codalab/codalab-competitions/wiki/ and here https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers for using your own compute workers.
Hoping that these guides can help !

Regards,

**Comment by rajatmodi62** [comment]
fixed now.. thx
