### ISSUE TITLE
Hide hidden reference data for ingestion program

### ISSUE THREAD

**Issue by rsasdf** [codalab/codalab-competitions#3166]
Hello,

I'm using an ingestion program for the code submissions. Looking at [https://github.com/codalab/competitions-v1-compute-worker/blob/master/worker.py](https://github.com/codalab/competitions-v1-compute-worker/blob/master/worker.py), the competition worker creates a docker volume for the hidden reference data directory (`'-v', '{0}:{0}'.format(hidden_ref_dir)` in line 586).

Is it possible to make the hidden reference data unavailable for the ingestion program? The ingestion program only requires access to the input data. In my case, the hidden reference data should only be accessed by the scoring program.

If not, is there a Dockerfile for the competition worker, so I can create my own custom competition worker?

**Comment by Didayolo** [comment]
Sorry for the very late reply...

> the competition worker creates a docker volume for the hidden reference data directory ('-v', '{0}:{0}'.format(hidden_ref_dir) in line 586).

I think the `hidden_ref_dir` is mounted in the Docker but not necessarily used.

> Is there a Dockerfile for the competition worker, so I can create my own custom competition worker?

Yes, the Dockerfile and more can be found here: see https://github.com/codalab/competitions-v1-compute-worker.
Also, you can directly "fork" the Docker image `codalab/competitions-v1-compute-worker:1.1.5`

I hope this helps.
