### ISSUE TITLE
Icevision for code submissions

### ISSUE THREAD

**Issue by mathiaszinnen** [codalab/codalab-competitions#3168]
Hi,

we are organizing an object detection challenge (https://codalab.lisn.upsaclay.fr/competitions/1939) and are trying to add icevision (https://airctic.com/0.12.0/) as a dependency to our code submission to enable easy inference. 

This is the dummy project that we are using to set up the code submission before changing it in the actual competition:
https://codalab.lisn.upsaclay.fr/competitions/1605?secret_key=5fed26e7-020a-4f45-9893-4fe9be7fc98a

I tried to create a custom docker image and use that in the competition settings (https://hub.docker.com/r/mathiaszinnen/codalab-icevision). 
However, the codalab runtime seems not to be able to pull that image (importing torch in a test submission fails for example).

The image is quite big (c. 4.4gb), might that be the reason?

This is the Dockerfile that was used to create the image:

```
FROM codalab/codalab-legacy:py37
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install tqdm
RUN pip3 install pycocotools==2.0.4
RUN pip3 install icevision[all]

```

Thank you in advance,

Mathias

**Comment by Didayolo** [comment]
Hello,

> I tried to create a custom docker image and use that in the competition settings

In the setting, just put the DockerHub name, not the URL (`mathiaszinnen/codalab-icevision` here).

> However, the codalab runtime seems not to be able to pull that image (importing torch in a test submission fails for example).

What is the error you get? It is `docker pull` that fails or do you have a `torch not found` error?

> The image is quite big (c. 4.4gb), might that be the reason?

That should not be the problem. We usually have 10GB+ Docker images that work well.

> This is the Dockerfile [...]

What you can do is to "fork" the Docker image `codalab/codalab-legacy:py37` to add your libraries to it. Maybe something is missing in your own image. ([see here](https://github.com/codalab/codalab-competitions/wiki/User_Docker) for interactive modification)

I hope this helps!
