### ISSUE TITLE
SBD metric in the competition Leaf Segmentation Challenge (LSC) changed

### ISSUE THREAD

**Issue by coder-people** [codalab/codalab-competitions#3171]
Hello dear organizers,
I found that the SBD metric in the competition Leaf Segmentation Challenge (LSC) changed at the end of 2021. I would like to know what is the difference between the two calculation methods before and after。

**Comment by Didayolo** [comment]
Hello,

This repository is about the platform itself. Please contact directly the organizers of the challenge you are referring to.

Best regards
