### ISSUE TITLE
How to check the results when the leaderboard mode is 'hide results'?

### ISSUE THREAD

**Issue by skynbe** [codalab/codalab-competitions#3175]
If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` and `tthomas63` as admins to your competition so they may access it.
2. Please post a link to your competition.
https://codalab.lisn.upsaclay.fr/competitions/3282

I'd like to let the participants to check their results internally although the leaderboard mode is 'hide results'. However, it seems that there is no way to do this, so could you let me know how to do?

**Comment by Didayolo** [comment]
Participants can check their results in the "Participate" > "Submit / View results" tab.

**Comment by Didayolo** [comment]
Sorry for the late answer by the way. If this does not solve your issue, please re-open it and give more details.
