### ISSUE TITLE
cannot find scoring script for under display camera Image Restoration

### ISSUE THREAD

**Issue by jhtwosun** [codalab/codalab-competitions#3177]
URL: https://codalab.lisn.upsaclay.fr/my/datasets/download/d4f3a813-3ae9-4e6d-8fa0-64196a005cde

cannot find scoring script for under display camera (https://codalab.lisn.upsaclay.fr/competitions/4874#learn_the_details-overview)

**Comment by Didayolo** [comment]
Hi,

This repository concerns the platform itself. Please contact the competition organizers for any competition-specific problem.

> If you have any questions, please feel free to post threads on 'Forum' tab and discuss related topics. You could also contact us by sending an email to organizers [mipi.challenge@gmail.com](mailto:mipi.challenge@gmail.com) with title 'UDC Challenge Inquiry'.
