### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by BryantGao** [codalab/codalab-competitions#3180]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpmcsGgt/run/program/evaluate_half_test.py", line 22, in 
    organize_input_half.process(input_dir)
  File "/tmp/codalab/tmpmcsGgt/run/program/organize_input_half.py", line 47, in process
    "Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.

But when I view my submited results and test list,it is not one-to-one matches to the test set?

3.7.3
/tmp/codalab/tmpk7iB4i/run/input
========results_video_names========
Counter({'v_-9kabh1K8UA_c008': 1, 'v_-9kabh1K8UA_c009': 1, 'v_-hhDbvY5aAM_c005': 1, 'v_-hhDbvY5aAM_c008': 1, 'v_-hhDbvY5aAM_c009': 1, 'v_-hhDbvY5aAM_c011': 1, 'v_1UDUODIBSsc_c001': 1, 'v_1UDUODIBSsc_c004': 1, 'v_1UDUODIBSsc_c015': 1, 'v_1UDUODIBSsc_c055': 1, 'v_1UDUODIBSsc_c067': 1, 'v_1UDUODIBSsc_c090': 1, 'v_1UDUODIBSsc_c111': 1, 'v_1UDUODIBSsc_c601': 1, 'v_1UDUODIBSsc_c603': 1, 'v_1UDUODIBSsc_c609': 1, 'v_2BhBRkkAqbQ_c002': 1, 'v_2ChiYdg5bxI_c044': 1, 'v_2ChiYdg5bxI_c046': 1, 'v_2ChiYdg5bxI_c058': 1, 'v_2ChiYdg5bxI_c072': 1, 'v_2ChiYdg5bxI_c135': 1, 'v_2ChiYdg5bxI_c136': 1, 'v_2ChiYdg5bxI_c600': 1, 'v_2ChiYdg5bxI_c601': 1, 'v_2ChiYdg5bxI_c602': 1, 'v_2Dnx8BpgUEs_c003': 1, 'v_2Dnx8BpgUEs_c005': 1, 'v_2Dw9QNH5KtU_c012': 1, 'v_42VrMbd68Zg_c003': 1, 'v_42VrMbd68Zg_c011': 1, 'v_42VrMbd68Zg_c012': 1, 'v_6OLC1-bhioc_c001': 1, 'v_6OLC1-bhioc_c005': 1, 'v_6OLC1-bhioc_c009': 1, 'v_6OLC1-bhioc_c013': 1, 'v_6OLC1-bhioc_c014': 1, 'v_6oTxfzKdG6Q_c004': 1, 'v_7FTsO8S3h88_c006': 1, 'v_7FTsO8S3h88_c007': 1, 'v_7FTsO8S3h88_c008': 1, 'v_82WN8C8qJmI_c003': 1, 'v_82WN8C8qJmI_c004': 1, 'v_82WN8C8qJmI_c014': 1, 'v_8rG1vjmJHr4_c005': 1, 'v_8rG1vjmJHr4_c006': 1, 'v_8rG1vjmJHr4_c010': 1, 'v_9p0i81kAEwE_c008': 1, 'v_9p0i81kAEwE_c010': 1, 'v_9p0i81kAEwE_c015': 1, 'v_9p0i81kAEwE_c018': 1, 'v_A4OJhlI6hgc_c001': 1, 'v_BdD9xu0E2H4_c003': 1, 'v_BdD9xu0E2H4_c011': 1, 'v_BdD9xu0E2H4_c013': 1, 'v_DjtFlW2eHFI_c614': 1, 'v_aAb0psypDj4_c006': 1, 'v_aAb0psypDj4_c008': 1, 'v_aAb0psypDj4_c009': 1, 'v_aVfJwdQxCsU_c007': 1, 'v_aVfJwdQxCsU_c015': 1, 'v_bQNDRprvpus_c001': 1, 'v_bhWjlAEICp8_c003': 1, 'v_bhWjlAEICp8_c004': 1, 'v_bhWjlAEICp8_c006': 1, 'v_bhWjlAEICp8_c009': 1, 'v_bhWjlAEICp8_c018': 1, 'v_czYZnO9QxYQ_c002': 1, 'v_czYZnO9QxYQ_c005': 1, 'v_czYZnO9QxYQ_c008': 1, 'v_czYZnO9QxYQ_c012': 1, 'v_czYZnO9QxYQ_c014': 1, 'v_czYZnO9QxYQ_c016': 1, 'v_czYZnO9QxYQ_c020': 1, 'v_foGDoBblREI_c002': 1})
========test_video_list========
Counter({'v_-9kabh1K8UA_c008': 1, 'v_-9kabh1K8UA_c009': 1, 'v_-hhDbvY5aAM_c005': 1, 'v_-hhDbvY5aAM_c008': 1, 'v_-hhDbvY5aAM_c009': 1, 'v_-hhDbvY5aAM_c011': 1, 'v_1UDUODIBSsc_c001': 1, 'v_1UDUODIBSsc_c004': 1, 'v_1UDUODIBSsc_c015': 1, 'v_1UDUODIBSsc_c055': 1, 'v_1UDUODIBSsc_c067': 1, 'v_1UDUODIBSsc_c090': 1, 'v_1UDUODIBSsc_c111': 1, 'v_1UDUODIBSsc_c601': 1, 'v_1UDUODIBSsc_c603': 1, 'v_1UDUODIBSsc_c609': 1, 'v_2BhBRkkAqbQ_c002': 1, 'v_2ChiYdg5bxI_c044': 1, 'v_2ChiYdg5bxI_c046': 1, 'v_2ChiYdg5bxI_c058': 1, 'v_2ChiYdg5bxI_c072': 1, 'v_2ChiYdg5bxI_c135': 1, 'v_2ChiYdg5bxI_c136': 1, 'v_2ChiYdg5bxI_c600': 1, 'v_2ChiYdg5bxI_c601': 1, 'v_2ChiYdg5bxI_c602': 1, 'v_2Dnx8BpgUEs_c003': 1, 'v_2Dnx8BpgUEs_c005': 1, 'v_2Dw9QNH5KtU_c012': 1, 'v_42VrMbd68Zg_c003': 1, 'v_42VrMbd68Zg_c011': 1, 'v_42VrMbd68Zg_c012': 1, 'v_6OLC1-bhioc_c001': 1, 'v_6OLC1-bhioc_c005': 1, 'v_6OLC1-bhioc_c009': 1, 'v_6OLC1-bhioc_c013': 1, 'v_6OLC1-bhioc_c014': 1, 'v_6oTxfzKdG6Q_c004': 1, 'v_7FTsO8S3h88_c006': 1, 'v_7FTsO8S3h88_c007': 1, 'v_7FTsO8S3h88_c008': 1, 'v_82WN8C8qJmI_c003': 1, 'v_82WN8C8qJmI_c004': 1, 'v_82WN8C8qJmI_c014': 1, 'v_8rG1vjmJHr4_c005': 1, 'v_8rG1vjmJHr4_c006': 1, 'v_8rG1vjmJHr4_c010': 1, 'v_9p0i81kAEwE_c008': 1, 'v_9p0i81kAEwE_c010': 1, 'v_9p0i81kAEwE_c015': 1, 'v_9p0i81kAEwE_c018': 1, 'v_A4OJhlI6hgc_c001': 1, 'v_BdD9xu0E2H4_c003': 1, 'v_BdD9xu0E2H4_c011': 1, 'v_BdD9xu0E2H4_c013': 1, 'v_DjtFlW2eHFI_c616': 1, 'v_aAb0psypDj4_c006': 1, 'v_aAb0psypDj4_c008': 1, 'v_aAb0psypDj4_c009': 1, 'v_aVfJwdQxCsU_c007': 1, 'v_aVfJwdQxCsU_c015': 1, 'v_bQNDRprvpus_c001': 1, 'v_bhWjlAEICp8_c003': 1, 'v_bhWjlAEICp8_c004': 1, 'v_bhWjlAEICp8_c006': 1, 'v_bhWjlAEICp8_c009': 1, 'v_bhWjlAEICp8_c018': 1, 'v_czYZnO9QxYQ_c002': 1, 'v_czYZnO9QxYQ_c005': 1, 'v_czYZnO9QxYQ_c008': 1, 'v_czYZnO9QxYQ_c012': 1, 'v_czYZnO9QxYQ_c014': 1, 'v_czYZnO9QxYQ_c016': 1, 'v_czYZnO9QxYQ_c020': 1, 'v_foGDoBblREI_c002': 1})

**Comment by Didayolo** [comment]
Hello,

This issue seems to be competition specific. It is most likely due to your submission (`"Uploaded results are not one-to-one matches to the test set."`). 

If you think the error is not on your side, please contact the competition organizers.
