### ISSUE TITLE
Is the website down?

### ISSUE THREAD

**Issue by zhipeng-fan** [codalab/codalab-competitions#3184]
Hello,

Somehow I cannot access the https://competitions.codalab.org/. It always shows "This site can’t be reached, competitions.codalab.org refused to connect." to me.

I tried both the Google Chrome Version 101.0.4951.64 (Official Build) (x86_64) and Safari Version 15.0 (15612.1.29.41.4, 15612). Neither of them could connect to the website.

Thanks!

**Comment by dtuantran** [comment]
Hello,
The website is up already.
Regards,

**Comment by zhipeng-fan** [comment]
Thanks for the quick fix!
