### ISSUE TITLE
Unable to submit & download submissions

### ISSUE THREAD

**Issue by caganselim** [codalab/codalab-competitions#3186]
Hi,

Is there a scheduled maintenance to the **old** website? I am not able to submit new results or download my previous submissions to The 2nd Large-scale Video Object Segmentation Challenge, my username is cscoban

**Comment by chiangliu** [comment]
I came across the same issue

**Comment by caganselim** [comment]
The old website does not accept for other challenges as well

**Comment by CatchBeliF-TAT** [comment]
I came across the same issue too, how can I submit my results on OXUVA test to get the score.

**Comment by CatchBeliF-TAT** [comment]
Is there a new website here?

**Comment by keskin-oguzhan** [comment]
I am facing the same issue.

**Comment by Shallow2000** [comment]
I came across the same issue too.

Thanks!

**Comment by dtuantran** [comment]
Hello,
We got a storage issue last week-end. It's resolved already. Sorry for this inconvenient.
Best regards,

**Comment by Two222** [comment]
现在还不能提交结果吗？
