### ISSUE TITLE
"Max submissions total" not working

### ISSUE THREAD

**Issue by juliojj** [codalab/codalab-competitions#3187]
Hi,
we organized a few competition tracks where we set the "Max submissions total" to be 3 at the test phase. However, for some participants it was not working and they were able to make more submissions than allowed.

here we have one participant with 10 submissions
https://codalab.lisn.upsaclay.fr/competitions/4198#results

here we have multiple participants with more than 3 submissions:
https://codalab.lisn.upsaclay.fr/competitions/4272?secret_key=7f359468-945e-46e1-877e-6b070b6ddcbb#results

same here:
https://codalab.lisn.upsaclay.fr/competitions/4273?secret_key=02ffda8d-b16e-4d70-8d13-23b0014cea01#results

and here:
https://codalab.lisn.upsaclay.fr/competitions/4276?secret_key=3b3b79dd-4857-41d2-bc86-bb8d30afdf6b#results

Can you check if this is a codalab bug or any mistake we did?
Thanks

**Comment by juliojj** [comment]
Hi,
I guess I understand the source of the "problem" now... it seems codalab does not count the failed submissions. Please correct me if I am wrong.
Best

**Comment by juliojj** [comment]
@JYueqi, this is what I observed (still need some confirmation from codalab developers). Just take into account that the organizers of the challenge you are participating may consider (or not) failed submissions. It may be important you can get a reply from them to avoid any problem.
Best

**Comment by Didayolo** [comment]
Interesting. Maybe the "number of entries" showed on the leaderboard should count only the successful submissions to avoid confusion.
