### ISSUE TITLE
Submitting results failed

### ISSUE THREAD

**Issue by Cynthiacoding** [codalab/codalab-competitions#3195]
Hi，I'm a contestant in an old competition： The 2nd Large-scale Video Object Segmentation Challenge - Track 2: Video Instance Segmentation. Recently I wanted to submit some new results, but mostly encountered failures for no reason.
![image](https://user-images.githubusercontent.com/43644268/178208638-b1064d75-326a-496a-87b6-9e3c3100c260.png)

**Comment by Didayolo** [comment]
Hello,

More information are needed to debug this.

- What is the URL of the competition?
- Click on "View scoring output log" and "View scoring error log"
- What can you see in the logs?
- Did you follow the right format? Do you have a sample competition to test if it works?

**Comment by Cynthiacoding** [comment]
Thanks for your quick response！

- The URL of the competition is “https://competitions.codalab.org/competitions/20128”
-  Click on "View scoring output log" and "View scoring error log"
![image](https://user-images.githubusercontent.com/43644268/178522839-39ddbba7-161f-40ef-ba94-c2d75c2dd9d7.png)

- I guess my format is correct because sometimes for the same file it returns me the correct result.

**Comment by l412198735** [comment]
I've been facing this problem since yesterday. Have you solved it?
![image](https://user-images.githubusercontent.com/24469194/178953876-6c476e71-412b-4657-96a1-82ed23a1ee7a.png)

**Comment by Cynthiacoding** [comment]
> I've been facing this problem since yesterday. Have you solved it? ![image](https://user-images.githubusercontent.com/24469194/178953876-6c476e71-412b-4657-96a1-82ed23a1ee7a.png)

No, I haven't solved it yet, in fact I started having this problem frequently since last Friday.

**Comment by Didayolo** [comment]
@l412198735 @Cynthiacoding 

Did you contact the competition organizers?

**Comment by YaoxinZhuo** [comment]
I faced the same "Failed" results for YouTube VIS 2019 challenge (https://competitions.codalab.org/competitions/20128#participate). I tried to contact the organizers. But they provided me the link here (codalab forums).

**Comment by phdfar** [comment]
hi. this competition link changed:
Go this link:
https://codalab.lisn.upsaclay.fr/competitions/6064

**Comment by Didayolo** [comment]
@phdfar and is it working fine now?

**Comment by phdfar** [comment]
> @phdfar and is it working fine now?

yes

**Comment by Cynthiacoding** [comment]
> hi. this competition link changed: Go this link: https://codalab.lisn.upsaclay.fr/competitions/6064

Thanks for your reply!
