### ISSUE TITLE
Submitting results failed

### ISSUE THREAD

**Issue by ubbp** [codalab/codalab-competitions#3196]
Hi，I'm a contestant in an old competition：Real-Time Image Super-Resolution Challenge.
we encountered this error when uploading the results of the match.
![image](https://user-images.githubusercontent.com/48211482/178403306-77749d6a-fb16-4b33-9a0b-78c86dc42ae2.png)
Hope you can help us.

**Comment by Didayolo** [comment]
Hello,

It seems that the problem comes from your submission. Did you ensure that it has the right format? Do you have any sample submission to test?

**Comment by ubbp** [comment]
> 你好
> 
> 问题似乎来自您的提交。您是否确保它具有正确的格式？您有任何样品提交进行测试吗？
Thank you for your answer.
It requires a .zip file containing 100 images，but I cannot submit it  because there is a maximum submission limit of 30M,

**Comment by ubbp** [comment]
> Hello,
> 
> It seems that the problem comes from your submission. Did you ensure that it has the right format? Do you have any sample submission to test?

Think you! It works now. Our results have been submitted.
