### ISSUE TITLE
is it really required to use an object storage system?

### ISSUE THREAD

**Issue by carandraug** [codalab/codalab-competitions#3203]
The documentation suggest that an object storage system is required, either AWS (or compatible) or Azure. See https://github.com/codalab/codalab-competitions/wiki/Storage:

> At this stage, Codalab gives you the option of using either AWS or Azure as your storage of choice.

Which is followed by documentation on setting up AWS, Azure, and Minio. However, in `codalab/settings/base.py` there is

```
    DEFAULT_FILE_STORAGE = os.environ.get('DEFAULT_FILE_STORAGE', 'django.core.files.storage.FileSystemStorage')
    USE_AWS = DEFAULT_FILE_STORAGE == 'storages.backends.s3boto3.S3Boto3Storage' or DEFAULT_FILE_STORAGE == 'apps.web.utils.CodalabS3BotoStorage'
```

So, is it possible to setup a codalab competitions instance that uses the file system instead of an object storage? I've grepped the wiki/doc and found no mention of `django.core.files.storage.FileSystemStorage` even though it is the default.

**Comment by Tthomas63** [comment]
We depend a lot on some form of cloud/object storage in order to distribute signed URLs instead of binary files for things like communication with the worker. At this point in time I don't think it's possible without a thorough refactor because of how tightly coupled our logic is to that.

I could be wrong, but this might've been something in mind for v2, Codabench.
https://github.com/codalab/codabench

**Comment by carandraug** [comment]
This is fine. I was just surprised when I saw `DEFAULT_FILE_STORAGE` defaulting to `django.core.files.storage.FileSystemStorage` but I guess what this means is that local storage is used for other things besides competitions and results?

I am not asking for filesystem storage to be implemented as an alternative to object storage (but wouldn't mind), I was asking about the logic on that code.

**Comment by Didayolo** [comment]
Just in case it is not clear, you can setup MinIO on your own computer or VM to avoid having to rely on a cloud service.

The storage is basically used for everything related to competitions and submissions. User accounts on the other hand are in the postgres database directly in the main CodaLab server.

Please re-open this issue if you still have questions.
