### ISSUE TITLE
An unexpected error occurred.

### ISSUE THREAD

**Issue by qiguming** [codalab/codalab-competitions#3212]
I am in "The 2st Occluded Video Instance Segmentation (OVIS) Challenge in conjunction with ECCV 2022", however, the codalab shows the error as follows when i submit results:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/31810368/184571493-204ecb51-5d48-469b-9570-a1ad1a4b56f8.png">

**Comment by Didayolo** [comment]
Hi,

Can you please give more information about your problem?

- The URL of the competition
- The submission you are trying to upload
- Is the template / starting kit submission working?
- Do other participants have the same problem?
- Did you contact the competition organizers?

Thanks

**Comment by Didayolo** [comment]
I close this issue because it is staling. Please re-open it with the needed information if needed.
