### ISSUE TITLE
Cannot access https://competitions.codalab.org

### ISSUE THREAD

**Issue by jzhang38** [codalab/codalab-competitions#3215]
Hi, I somehow cannot access https://competitions.codalab.org. Everything was fine 2 hours ago. Seems that the website is down. I notice that CodaLab is moving to the new website https://codalab.lisn.upsaclay.fr/. But I can not find the competition I am looking for (FewRel) there. I am adding some supplementary experiments to my EMNLP rebuttal that is due tomorrow. Appreciate it if someone could provide some help!

**Comment by whai362** [comment]
I also cannot access https://competitions.codalab.org. Hope the website will be restored soon.

**Comment by axuan731** [comment]
I have the same problem😭

**Comment by AlberTgarY** [comment]
I have the same issue..........................

**Comment by acletournel** [comment]
Hello everybody,
The problem has been solved.
