### ISSUE TITLE
How to apply for an exemption of hosting the competition on old server

### ISSUE THREAD

**Issue by QingyongHu** [codalab/codalab-competitions#3216]
![a0e1a091882cf1f5a4c5c3b630015c5](https://user-images.githubusercontent.com/29670234/187165109-f3e9bffe-a487-47dc-aec3-dccc571344c6.png)

Dear codalab organizers, 

I'm an organizer of a [competition](https://competitions.codalab.org/competitions/31519), which has been hosted for over three months and is about to end in two months. As such, I would like to ask if it's possible to apply for an exemption to continue running the competition on the old server, and how to apply for this exemption.

Many thanks!

**Comment by dtuantran** [comment]
Hello @QingyongHu,
You can send an email to info@codalab.org in which you can explain in detail about your competition and your motivation. The team leaders will give decision then.
Regards,
