### ISSUE TITLE
Upload new submission in old website

### ISSUE THREAD

**Issue by axuan731** [codalab/codalab-competitions#3219]
I wanna submit a result in a competition which the new website don't have, is that mean I'll never submit results in the old website 🥲

**Comment by blessingforever** [comment]
I have the same question.

**Comment by YellowPuppy** [comment]
I have the same question.

**Comment by HB-X** [comment]
I have the same question.

**Comment by Didayolo** [comment]
Hello everybody,

Indeed, it is not possible anymore to submit submissions on the old website.

The good news is that transferring a competition from the old to the new server is easy for the organizers (see [dumping a competition](https://github.com/codalab/codalab-competitions/wiki/User_Running-a-Competition)). You can ask organizers to do the transfer and to leave the new link to the competition in the documentation of the old one.

Thank you for your comprehension and sorry for the inconvenience.

**Comment by andreasvlachos** [comment]
Hi, Is there a good way of transferring previous submissions from the old site to the new one, so that we can have our leaderboard on the new website?
Thanks,
Andreas

**Comment by Didayolo** [comment]
Hi,

Unfortunately, I don't think there is any good way of doing this. Sorry for the inconvenience.

**Comment by andreasvlachos** [comment]
Sorry for re-opening, but I have a related question: what is the best way to transfer some of the submissions, say the top 10?

**Comment by Didayolo** [comment]
I don't know how this can be done, sorry.

**Comment by acletournel** [comment]
Submissions are related to a user in the database. Only the owner of a submission is able to upload his own submissions from the old site and get them replayed on the new on the migrated competition if available. He needs previously to create a new account on the new site and register to the competition. This is the reason why this cannot be done automatically. I hope this clarifies a bit.

A feature could be to impersonize a fake generic competition's user, and to make the migration of the top-ten submissions out of the old site to replay them on the new. The feature could be available at organizer's level. But this feature is not implemented.
