### ISSUE TITLE
Sincere request for youtube vos 2018 competition transfer

### ISSUE THREAD

**Issue by Shallow2000** [codalab/codalab-competitions#3223]
Hi! I want to evaluate on youtube vos 2018 (https://competitions.codalab.org/competitions/28988) , but it is not allowed to submit results on the old website. Moreover, this competition is not available on the new website. 
  Many influential works use it as a golden benchmark and it is pretty significant.  If the old website is not available in the future, could you please transfer old competitions to the new website to provide us a way to evaluate results?
  Thank you very much!!!

**Comment by Shallow2000** [comment]
Sorry, the competition link is https://competitions.codalab.org/competitions/19544

**Comment by Didayolo** [comment]
Hello,

Transferring a competition to the new website is quick and easy for the organizers. It is just needed to dump the bundle and re-upload it (see here https://github.com/codalab/codalab-competitions/wiki/User_Running-a-Competition).

We let the organizers decide whether they want to update their competition to the new server. You can try to reach them directly if it is important to you. Thank you for your comprehension.
