### ISSUE TITLE
Can't find the competition "Microsoft COCO Image Captioning Challenge" on the new website.

### ISSUE THREAD

**Issue by Nobelvictory** [codalab/codalab-competitions#3228]
I wanna submit a result in a competition "Microsoft COCO Image Captioning Challenge", which the new website don't have. Is that mean I'll never submit results in the old website? From the previous issues, I find a possible solution by asking organizers to do the transfer and to leave the new link to the competition. For  the competition "Microsoft COCO Image Captioning Challenge", who should I contact? Thanks very much!

**Comment by WangLanxiao** [comment]
I have the same question~

**Comment by Didayolo** [comment]
Hello everyone,

- COCO Image Captioning Challenge: https://codalab.lisn.upsaclay.fr/competitions/7404
- COCO Detection Challenge: https://codalab.lisn.upsaclay.fr/competitions/7383

I've just found the links in the description of the old challenges.

Is there any competitions that are still missing? Please put the URL of the competition you are referring to.

**Comment by Nobelvictory** [comment]
> Hello everyone,
> 
> * COCO Image Captioning Challenge: https://codalab.lisn.upsaclay.fr/competitions/7404
> * COCO Detection Challenge: https://codalab.lisn.upsaclay.fr/competitions/7383
> 
> I've just found the links in the description of the old challenges.
> 
> Is there any competitions that are still missing? Please put the URL of the competition you are referring to.

Dear Didayolo,

I just submitted a file (result.zip) to the new site for testing, which kept the same format as before. However, the status shows that it failed. There is no error in the error log. I don't know what the problem is. Could you please help to check it?

**Comment by Nobelvictory** [comment]
> Hello everyone,
> 
> * COCO Image Captioning Challenge: https://codalab.lisn.upsaclay.fr/competitions/7404
> * COCO Detection Challenge: https://codalab.lisn.upsaclay.fr/competitions/7383
> 
> I've just found the links in the description of the old challenges.
> 
> Is there any competitions that are still missing? Please put the URL of the competition you are referring to.

Dear Didayolo,

I just submitted a file (result.zip) to the new site https://codalab.lisn.upsaclay.fr/competitions/7404 for COCO Image Captioning Challenge, which kept the same format as before. However, the status shows that it failed. There is no error in the error log. I don't know what the problem is. Could you please help to check it?

**Comment by WINGS-999** [comment]
> 大家好，
> 
> * COCO 图像字幕挑战：[https ://codalab.lisn.upsaclay.fr/competitions/7404](https://codalab.lisn.upsaclay.fr/competitions/7404)
> * COCO 检测挑战：[https ://codalab.lisn.upsaclay.fr/competitions/7383](https://codalab.lisn.upsaclay.fr/competitions/7383)
> 
> 我刚刚在旧挑战的描述中找到了链接。
> 
> 是否还有一些比赛仍然缺席？请输入您所指的比赛的网址。
COCO Keypoint detection competitions

**Comment by WangLanxiao** [comment]
I meet the error about "Invalid file type ()" when i submit the result.zip thanks a lot

**Comment by Nobelvictory** [comment]
@Didayolo Thanks very much! There is another question. I just submitted a file (result.zip) to the new site https://codalab.lisn.upsaclay.fr/competitions/7404 for COCO Image Captioning Challenge, which kept the same format as before. However, the status shows that it failed. There is no error in the error log. I don't know what the problem is. Could you please help to check it?

**Comment by Didayolo** [comment]
@Nobelvictory 

I think this is discussed here #3220

Basically, I think the organizers need to correct the settings of their competition.

Here is my message on this other issue:

I think these problems are linked to the settings of the competitions. COCO organizers can change that easily using the competition editor.

> The competition of "RVC Challenge: COCO Detection (Bounding Box)" on "test-dev2022(bbox)"(https://codalab.lisn.upsaclay.fr/competitions/6420#participate-submit_results) still can not evaluate results. It is claimed that "This phase of the competition is closed."

I guess the dates of the phases are not right.

> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
    /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
    warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
    Execution time limit exceeded!

I guess the time limit is not right.

Please contact directly COCO organizers so they are aware of these problems.

**Comment by TXH-mercury** [comment]
![image](https://user-images.githubusercontent.com/38175683/192237201-0c8f8197-5ebf-4639-8ee9-399b6cd3a53f.png)
@Didayolo  hi， i have meet this bug when evaluating mscoco caption

**Comment by Didayolo** [comment]
> @Didayolo hi， i have meet this bug when evaluating mscoco caption

Hi, you can follow this issue here:

- #3263

It should be resolved soon.
