### ISSUE TITLE
HTML Image not showing

### ISSUE THREAD

**Issue by abumafrim** [codalab/codalab-competitions#3229]
Hello,

In one of the html files in my competition page, I want to include an image but it's not displaying. I have changed the source to point to a GitHub file, but it is still not showing.

Below is how I added the image file.

`<p><img alt="Dataset Example" src="https://github.com/afrisenti-semeval/afrisent-semeval-2023/blob/main/dataset.png" /></p>`

Please help.

**Comment by dtuantran** [comment]
Hello,
It seems that your link isn't the good one. Could you try this `https://github.com/afrisenti-semeval/afrisent-semeval-2023/blob/91d0c496775e874a4beca8b7f55e35937ddeece6/dataset.png`?
Regards,
