### ISSUE TITLE
Can't find the competition Leaf Segmentation Challenge (LSC)

### ISSUE THREAD

**Issue by piper-h** [codalab/codalab-competitions#3233]
I want to submit a result in a competition "Leaf Segmentation Challenge (LSC)" and can't find it on the new website.
Who can help me please?

**Comment by Didayolo** [comment]
We let the organizers of each competition transfer the competition to the new website if they wish.

It is an easy procedure, they can simply dump and re-upload the challenge, and put the new link in the old one's documentation.

Please contact directly the Leaf Segmentation Challenge organizers.

**Comment by Didayolo** [comment]
> Thank you for your answer.
Unfortunately I wasn’t able to contact the organizers of the competition.
Is the any way you can assist me with that?

Here is the name of the organizers:
Hanno Scharr, Massimo Minervini, Andreas Fischbach and Sotirios A. Tsaftari.

I can't really help more than that.
