### ISSUE TITLE
Sign in error

### ISSUE THREAD

**Issue by alanWXZ** [codalab/codalab-competitions#3235]
Hello, when I use the new codalab server https://codalab.lisn.fr/),  an error occur 'The e-mail address and/or password you specified are not correct.' However, I can use the same e-mail address and password to sign in the old server.

**Comment by Didayolo** [comment]
Hello @alanWXZ,

Unfortunately, the database is not shared between the two servers. You therefore need to create a new account.
Sorry for the inconvenience.
