### ISSUE TITLE
Liver Tumour Segmentation (LiTS) challenge not available on the new website

### ISSUE THREAD

**Issue by MohamadZeina** [codalab/codalab-competitions#3236]
I am trying to submit to this competition on the old website (https://competitions.codalab.org/competitions/17094). 

However I’m not able to - clicking submit suggests I go to the new website, but I can’t find this competition on the new website no matter what I search. I’ve got in touch with the organisers but haven’t heard back. Just wondering if there is any way to submit to this? The graph at the bottom shows lots of submissions leading up to 1/9/22 - is there some way to submit that I’m missing? Or does this coincide with when the old website came offline?

Any help or advice is appreciated.

**Comment by Didayolo** [comment]
We let the organizers of each competition transfer the competition to the new website if they wish.

It is an easy procedure, they can simply dump and re-upload the challenge, and put the new link in the old one's documentation.

Please contact directly the Leaf Segmentation Challenge organizers.

**Comment by Didayolo** [comment]
So indeed it is not allowed to submit on the old server.
