### ISSUE TITLE
Cannot evaluate results on The 4th Large-scale Video Object Segmentation - Track 3: Referring Video Object Segmentation

### ISSUE THREAD

**Issue by bo-miao** [codalab/codalab-competitions#3252]
Hi,

I tried to evaluate the results as usual on https://codalab.lisn.upsaclay.fr/competitions/3282. But there is something wrong with the evaluation system of the 4th large-scale VOS, track3 RVOS. Not sure what happened, but the bug below started yesterday.

Thanks.

-------------------------------------------------------------------------------------------------------

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:71: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  annotation = annotation.astype(np.bool)
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:72: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  segmentation = segmentation.astype(np.bool)
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:27: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  seg = seg.astype(np.bool)
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:71: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  annotation = annotation.astype(np.bool)
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:72: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  segmentation = segmentation.astype(np.bool)
/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py:27: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  seg = seg.astype(np.bool)
Traceback (most recent call last):
  File "/tmp/codalab/tmp0Pw2HH/run/program/evaluate.py", line 240, in 
    output_file.write('Overall: {}\n'.format(overall))
TypeError: a bytes-like object is required, not 'str'

**Comment by Didayolo** [comment]
Hello,

I merge this issue with #3263.
