### ISSUE TITLE
The status of the submitted HO3D_v2 result is Failed.

### ISSUE THREAD

**Issue by Strive9881** [codalab/codalab-competitions#3253]
![image](https://user-images.githubusercontent.com/51118126/191981048-6c64d36e-ee3c-46f4-8658-b67ea37bc8c4.png)

**Comment by Strive9881** [comment]
The competition is available at https://codalab.lisn.upsaclay.fr/competitions/4318

**Comment by karta2155802** [comment]
still cannot evaluate the results

**Comment by Strive9881** [comment]
> 
Yes, I just submitted the result and it still says failed.

**Comment by Strive9881** [comment]
> still cannot evaluate the results

Are you experiencing the same problem?

**Comment by karta2155802** [comment]
Yes. Same error message.

**Comment by Didayolo** [comment]
Hello,

I merge this issue with #3263
