### ISSUE TITLE
Cannot evaluate results on The 4th Large-scale Video Object Segmentation - Track 1: VOS (migrated server)

### ISSUE THREAD

**Issue by Seek2Find** [codalab/codalab-competitions#3254]
Hi,

I tried to evaluate the results as usual on https://codalab.lisn.upsaclay.fr/competitions/6066. But there is something wrong with the evaluation system. Maybe it is caused by the possible python version update of your server? I've checked that the server has scored all my submitted answers in the stdout but just failed to write down the summing-up score. The error information is like:

Traceback (most recent call last):
  File "/tmp/codalab/tmpuqtkK1/run/program/evaluate.py", line 224, in 
    output_file.write('Overall: {}\n'.format(overall))
TypeError: a bytes-like object is required, not 'str'

Thanks.

**Comment by Didayolo** [comment]
Hello,

I merge this issue with #3263
