### ISSUE TITLE
mscoco image captioning evaluation bug!

### ISSUE THREAD

**Issue by TXH-mercury** [codalab/codalab-competitions#3256]
![image](https://user-images.githubusercontent.com/38175683/192137416-6d55a7a2-a7c7-4653-b1f3-a02178bae6cd.png)

**Comment by TXH-mercury** [comment]
and if could move all results  from different users of the old websites to the new websites, cause the new website leaderboard is empty.

**Comment by qianrenmao** [comment]
we have met the same bug!!
