### ISSUE TITLE
It seems that we cannot connect to the codalab website.

### ISSUE THREAD

**Issue by Shallow2000** [codalab/codalab-competitions#3264]
Could you please check the website connection?  Thank U!!!

**Comment by yingkaining** [comment]
Same problem!

**Comment by ady-yu** [comment]
I have the same problem. I can't attach the https://codalab.lisn.fr/ website

**Comment by lzhbrian** [comment]
+1

**Comment by dtuantran** [comment]
Dear,

We got an electricity accident then all of our services were in outage. (see more here : https://groups.google.com/g/codalab-competitions/c/kAaf-p1emF8)
The website returned back to normal.
Thank you for your understanding.

Best regards,
