### ISSUE TITLE
Unable to edit leaderboard columns after launching

### ISSUE THREAD

**Issue by dmollaaliod** [codalab/codalab-competitions#3265]
I tried to change the columns of the leaderboard after launching the competition. I used "Edit" and changed the "key" and "label" values of the "leaderboard" section, but the columns in the leaderboard don't change.

The competition is running now and people are submitting their runs. Is it possible to change the leaderboard columns when the competition is running?

Here is the competition url: https://codalab.lisn.upsaclay.fr/competitions/6935 (how do I add `pavao` and `tthomas63` as admins to the competition?)

**Comment by Didayolo** [comment]
Hello,

Unfortunately, it is a known bug that still haven't been fixed. See #2686.
