### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities

### ISSUE THREAD

**Issue by czyssrs** [codalab/codalab-competitions#3267]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Hi,

I use the chrome browser Version 105.0.5195.125 (Official Build) (x86_64)
The competition is: 
https://codalab.lisn.upsaclay.fr/competitions/4138

It gives the following error these days, which have not happened before:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  File "/tmp/codalab/tmph1_8EL/run/program/evaluation.py", line 13
    print os.listdir(submit_dir)
          ^
SyntaxError: invalid syntax

<img width="916" alt="image" src="https://user-images.githubusercontent.com/12695059/193132224-e9267949-fadb-4605-b5e4-6f15786e4d03.png">

Could anyone help? Thanks! 

Zoey

**Comment by Didayolo** [comment]
Hi,

This is the reason: 
- #3263

It should be fixed now.
