### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

### ISSUE THREAD

**Issue by Foltt** [codalab/codalab-competitions#3272]
Hello, the problem that was fixed half a month ago has reappeared.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/53162663/196592119-dc545d20-20ae-4f19-b9c0-2df46a291b84.png">
The competition is ：https://codalab.lisn.upsaclay.fr/competitions/395
Could you please fix it again？
Thanks！
@Didayolo

**Comment by Didayolo** [comment]
Hello,

Are you a participant or organizer of the competition?

The competition docker image is still `codalab/codalab-legacy:py2`.

- Was the submission a new upload or a re-run from admin interface?
- Maybe the organizers have updated the scoring program?

**Comment by Foltt** [comment]
I am a participant and the error happened when I make a new submissiom.
By the way, it can work now!

**Comment by Didayolo** [comment]
OK, nice to hear. I close the issue as it is working.
