### ISSUE TITLE
Change the username

### ISSUE THREAD

**Issue by giovaz94** [codalab/codalab-competitions#3273]
Good evening. 
Is there any options for updating the username of my CodaLab account? 

My current username is antonioni.giovanni and I want to change it, if aviable, to Fano14  while maintaining the other account informations. 

Thanks for your attention and help.

**Comment by Didayolo** [comment]
Hello,

We do not accept username changes anymore because it can be problematic for challenge organizers.

Sorry for the inconvenience.

**Comment by giovaz94** [comment]
Hello @Didayolo, thank you for your feedback. 
Is there any chance to delete the account then?

**Comment by Didayolo** [comment]
@giovaz94 If you have a good reason to rename your account, I can perform the change. Are you participating in any competition?

**Comment by giovaz94** [comment]
Hello @Didayolo, yes I need to change the account username for participating to the competition hosted by my university.

**Comment by Didayolo** [comment]
Sorry I just saw your message. Did you work-around or do you still need the username change?
