### ISSUE TITLE
COCO Panoptic Segmentation on the new server

### ISSUE THREAD

**Issue by sborse3** [codalab/codalab-competitions#3277]
Hi, please coould you upload the test_dev competition for COCO panoptic segmentation on the new server. I can't find it, thanks!

**Comment by Didayolo** [comment]
Hello,

We let the organizers transfer the competitions by themselves to the new server. It is a quite easy procedure (dump + upload).

Try to contact COCO challenge organizers directly to ask them to transfer the competition to codalab.lisn.fr

Thank you for your comprehension.
