### ISSUE TITLE
Questions about MinneApple Fruit Segmentation Challenge

### ISSUE THREAD

**Issue by plainzzj** [codalab/codalab-competitions#3278]
hello！
I tried to submit the results of the MinneApple Fruit Segmentation Challenge
https://competitions.codalab.org/competitions/21694#participate
pop-up notification:
Submission upload has been disabled. See the new instance at: https://codalab.lisn.upsaclay.fr/

But I can't find any information about this competition on the new website.
Can I still participate in this competition now？
thank you very much！

**Comment by Didayolo** [comment]
Hello,

We let the organizers transfer the competitions by themselves to the new server. It is a quite easy procedure (dump + upload).

Try to contact MinneApple challenge organizers directly to ask them to transfer the competition to codalab.lisn.fr

Thank you for your comprehension.
