### ISSUE TITLE
Dockerfile uses repository path for RUN

### ISSUE THREAD

**Issue by robostoneDK** [codalab/codalab-competitions#3280]
Dockerfile
RUN pip install --upgrade pip  # make things faster, hopefully
RUN pip install -r codalab/requirements/requirements.txt

When trying to pip install the requirements.txt, you are using the repository path.
You need to copy the requirements file into the container environment, and run using some local path e.g

COPY codalab/requirements/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

Beyond this little fix, I still face issued when trying to setup a local Codalab instance:

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 5/8
 ⠿ Network codalab-competitions_default  Created                                                                                                                             0.1s
 ⠿ Container memcached                   Created                                                                                                                             0.1s
 ⠿ Container postgres                    Created                                                                                                                             0.1s
 ⠿ Container rabbit                      Created                                                                                                                             0.1s
 ⠋ Container django                      Creating                                                                                                                            0.1s
 ⠋ Container worker_compute              Creating                                                                                                                            0.1s
 ⠿ Container flower                      Created                                                                                                                             0.1s
 ⠋ Container worker_site                 Creating    
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/robostoneDK/codalab-competitions/var/logs/worker_site

**Comment by Didayolo** [comment]
Hello,

This is actually a change we had done recently:

https://github.com/codalab/codalab-competitions/commit/107edf11bd4050b06f948b8be3a3fc73caadaa20

From 

```
COPY codalab/requirements/common.txt requirements.txt
RUN pip install -r requirements.txt
```

To

```
RUN pip install -r codalab/requirements/requirements.txt
```

Is that a problem? Do you have any error logs of a bug due to this?

**Comment by Didayolo** [comment]
Indeed when docker-compose locally, I obtain the following error:

```
 => ERROR [codalab-competitions-worker_site 5/6] RUN pip install -r codalab/requirements/requirements.txt
```

Let's come back to the old behaviour
