### ISSUE TITLE
COCO Keypoint Challenge val2017 closed

### ISSUE THREAD

**Issue by manchen1995** [codalab/codalab-competitions#3281]
Hi,

The COCO Keypoint Challenge val2017 (keypoint) is closed: https://codalab.lisn.upsaclay.fr/competitions/7403#participate-submit_results. I want to use the server to make sure my json results are in correct format. Could you please take a look at it?

**Comment by Didayolo** [comment]
Hello,

It is easy for the competition organizers to change the end date so the competition remains open (using the "Edit" menu).

However, as administrators of the platform, we can't take this decision for them as we don't know if they closed it on purpose or not. Please reach directly COCO's organizers.

Thank you for your comprehension.
