### ISSUE TITLE
New submission on Codalab: SemEval 2021 Task 11: NLPContributionGraph

### ISSUE THREAD

**Issue by 92Komal** [codalab/codalab-competitions#3297]
I have participated in the competition on codalab:  [SemEval 2021 Task 11: NLPContributionGraph](https://competitions.codalab.org/competitions/25680#participate)  and now we would like to submit a new submission. It seems that this competition was not moved to the [new server](https://codalab.lisn.upsaclay.fr/my/). How can we submit? 

We are looking forward to hearing from you soon!

Thank you in advance

**Comment by Didayolo** [comment]
We let the organizers transfer their competition to the new server by themselves. 

It is an easy procedure:
- Download the competition as a bundle using the "Dump" feature
- Upload the bundle on the new server 
- _A link to the new location can be given in the old competition's documentation_

You can try to contact the SemEval organizers by yourself to ask them to perform this transfer.

Thank you for your comprehension.
