### ISSUE TITLE
 Questions about results submission

### ISSUE THREAD

**Issue by LALBJ** [codalab/codalab-competitions#3298]
Dear codalab:

After I submitted the results, the Submit to Leaderboard button and the Make your submission public did not appear when I clicked the Refresh button. And I can't open the output log, when I open it, it prompts the error as shown below.
Here is the link to the contest：https://codalab.lisn.upsaclay.fr/competitions/8087
I look forward to hearing from you!
![image](https://user-images.githubusercontent.com/40877073/207228671-4be113a4-9a6b-4434-83cc-dcd9345a600e.png)
<img width="854" alt="image" src="https://user-images.githubusercontent.com/40877073/207228694-e2a82b42-a27f-4c3c-a1c3-d25e22eed9bf.png">

error output:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

**Comment by LALBJ** [comment]
This problem has been solved. Because the results I uploaded before were in the private leaderboard.

**Comment by Didayolo** [comment]
> This problem has been solved. Because the results I uploaded before were in the private leaderboard.

Nice to hear. I close the issue then. If you still need help, feel free to re-open the issue (and to give more details e.g. username, date of submission, ...).
