### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

### ISSUE THREAD

**Issue by diouck** [codalab/codalab-competitions#3302]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpoASpW3/run/program/evaluate.py", line 153, in 
    mIou, ious = generate_miou(truth_dir, submit_dir)
  File "/tmp/codalab/tmpoASpW3/run/program/evaluate.py", line 50, in generate_miou
    return mIou, ious
UnboundLocalError: local variable 'mIou' referenced before assignment

**Comment by diouck** [comment]
For competition : FLAIR #1: Semantic segmentation and domain adaptation

Do you know how to solve this problem in submissions
 Thank you

**Comment by Didayolo** [comment]
Hello,

Given the error `UnboundLocalError: local variable 'mIou' referenced before assignment`, I think the bug comes from the scoring program (`evaluate.py`). 

If you are the organizer of the competition, you should edit this file and re-upload the scoring program.

**Comment by diouck** [comment]
Hello and Thank you In fact I am not the organizer of the contest but just a participant

**Comment by agarioud** [comment]
It appears that you are submitting predictions on the toy dataset (consisting of 50 patches) while predictions on the test set (15,700 patches) are expected.
As the toy dataset patches are not present in the test dataset, no metrics can be calculated which raises this error.

**Comment by Didayolo** [comment]
I consider this issue solved. Feel free to re-open if needed.
