### ISSUE TITLE
BadZipfile: File is not a zip file 

### ISSUE THREAD

**Issue by Jiaxin-Pei** [codalab/codalab-competitions#3303]
Hello,

I am running Multilingual Tweet Intimacy Analysis on codalab (link: https://codalab.lisn.upsaclay.fr/competitions/7096) and I'm getting the BadZipfile: File is not a zip file error when I'm testing the scoring program. 
The only error message I got is:
```
Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 132, in get_bundle
    with ZipFile(bundle_file.file, 'r') as z:
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```
I have checked existing discussions about this error, and have made sure that all the reference data and scoring programs are submitted as a zip file. However, I'm still getting this error, even when I'm using the reference data and scoring program from the example projects. 

Would it be possible for you to take a look? I have added both `pavao` and `tthomas63` as admins to my competition.

Thanks a lot!

**Comment by Didayolo** [comment]
Hello,

It is strange, indeed the submission file does not seems corrupted.

> However, I'm still getting this error, even when I'm using the reference data and scoring program from the example projects.

When you try this, you also try to upload the example submission?

**Comment by Jiaxin-Pei** [comment]
yes, I also tried to upload the example submission, and it also failed

**Comment by Jiaxin-Pei** [comment]
Another weird issue is: I tried to create a new competition (https://codalab.lisn.upsaclay.fr/competitions/9608) as suggested in this issue (https://github.com/codalab/codalab-competitions/issues/3105). It worked at the beginning, however, the same submission files failed one day after.

**Comment by Didayolo** [comment]
It seems that the errors on your new competition are not related to the initial "BadZipFile" error.

The errors seems to be due to the use of the wrong Python version.

Select the right "competition docker image" (this can be done through the editor). Some suggestions:
- `codalab/codalab-legacy:py2` for Python2, the old default image
- `codalab/codalab-legacy:py37` or `codalab/codalab-legacy:py39` for Python3

**Comment by Jiaxin-Pei** [comment]
Thanks a lot @Didayolo! However, I am still getting an BadZipFile error after trying all the python docker images. 
Another weird thing is happening in this new codalab competition: it worked one day but not on the day after, with the exactly same submission files.

**Comment by Didayolo** [comment]
> it worked one day but not on the day after, with the exactly same submission files.

This typically indicates a change in the configuration of the competition (e.g. docker image)
