### ISSUE TITLE
Display Image in CodaLab HTML Page

### ISSUE THREAD

**Issue by blahner** [codalab/codalab-competitions#3304]
I am a competition organizer trying to insert an image in one of the CodaLab html pages. In html, I type:
`<img style="vertical-align: middle;" src="images/equation_1.png" alt="equation 1" width="360" height="106">`

However, the image does not display, only the "alt" tag. The image is located in "/images/equation_1.png", where the "images" folder is at the same level as the html files and competition .yaml file inside the competition bundle.

Opening the appropriate html page outside of CodaLab in a web browser correctly displays the image. It just does not work inside CodaLab.

My question is: how do I display an image in the CodaLab html pages? If the competition bundle alters the directory structure (e.g. so /images/equation_1.png is not the correct path), what is it? 
Thank you!

**Comment by Didayolo** [comment]
Hi,

That is a good question. Are you sure the images were uploaded with the bundle in the first place? And that the path corresponds between the `competition.yaml` file and the folder? Maybe it has something to do with the way it is zipped (for instance for datasets and scoring programs, they should be zipped without the directory structure).

When I look the HTML pages of previous competitions I organized, I usually use an URL in the HTML tag (like `<img src="https://[...]/">`). In some cases I've hosted the images directly on Github. This is a work-around that you can use, but of course the issue remains.
