### ISSUE TITLE
Request for approvement of the SemanticKITTI registration

### ISSUE THREAD

**Issue by kebijuelun** [codalab/codalab-competitions#3306]
***This is a template, please remove any non-relevant details to your issue***

If you are competition participant:
-----------------------------------

We submitted an account application last Friday, but we haven't received any approval information yet.
  We are very anxious to submit a version of test results on Semantic KITTI（SSC） recently. Please help us approve it as soon as possible.

Thanks for your help.

**Comment by Didayolo** [comment]
Hello,

You should address this request to the Semantic KITTI competition organizers.

**Comment by kebijuelun** [comment]
Ok, I have solved the problem, thank!
