### ISSUE TITLE
Making leaderboard private, but allowing participants to view their own submissions

### ISSUE THREAD

**Issue by jspenmar** [codalab/codalab-competitions#3312]
Hi, 

Thanks for the great work! 

I'm looking to create a follow up competition to one we recently ran (https://codalab.lisn.upsaclay.fr/competitions/7811). For this edition, we wanted to make the leaderboard for the 'test' split completely private (i.e. the participants can't see their own submissions). Meanwhile, the leaderboard for the 'val' split should also be private, but we would like the participants to be able to see only their own submissions. 

I've managed to make the leaderboards completely private and anonymous by using the Edit -> Leaderboard Mode interface in the website. However, I was wondering if this can be done directly from the competition yaml file. So far I've tried
```
phases:
  1:
    leaderboard: private
   # or 
   # leaderboard_mode: private
   # hide_leaderboard: true
   # hide_results: true
```

Finally, if a leaderboard were to be made anonymous, it is possible for the organizers to see the author of each submission?

Kind regards and thank you,
Jaime

**Comment by Didayolo** [comment]
Hi,

From [this documentation page](https://github.com/codalab/codalab-competitions/wiki/Organizer_Codalab-competition-YAML-definition-language), I can read:

> Some phase properties cannot be specified in the YAML file. However, they are available from the editor:
> Leaderboard Mode: The mode "Hide Results" makes the leaderboard results invisible to non organizers ("private leaderboard").

Indeed, it seems to be editable only from the editor.

I think it is always possible for the organizers to have all information about the submissions, in the "Submissions" panel.

**Comment by jspenmar** [comment]
Okay, I'll make sure to configure it manually from the editor then.

Thank you!
