### ISSUE TITLE
DanceTrack Competition Refresh Status Issue

### ISSUE THREAD

**Issue by Jubi-Hwang** [codalab/codalab-competitions#3315]
![Capture Image](https://user-images.githubusercontent.com/83354628/217251748-ad4898f2-e948-4f2e-9dd0-64c17679acd3.jpg)

As you can see in the picture, my submission status has not changed over time. How can I check the results of the test dataset?

**Comment by Didayolo** [comment]
Hi, the queue of jobs to compute was congested because some competitions are very demanding right now.

We are regulating it so it should come back to normal.
