### ISSUE TITLE
Metadata file query?

### ISSUE THREAD

**Issue by kaustubh14jr** [codalab/codalab-competitions#3318]
Dear Team,

I was trying to execute grep using the metadata file for eg:

command: $program/evaluate.py $input $output
command: grep 'OVERALL' $output/der_score.txt | awk 'print{$4}' > score.txt
and I am getting an error executing these commands.

The question: is it possible to execute commands like grep through the metadata file or one can only execute the evaluate.py?

Thanks...

**Comment by Didayolo** [comment]
Hi,

I think the content of this command is quite free. However, the command you are trying to run may be problematic (e.g. in terms of path).

What is the error that you are getting?

You can learn more about the paths and environnement variables used here: https://github.com/codalab/codalab-competitions/wiki/User_Building-an-Ingestion-Program-for-a-Competition#result-submission-challenges
