### ISSUE TITLE
User cannot leave a competition upon joining

### ISSUE THREAD

**Issue by aghand0ur** [codalab/codalab-competitions#3320]
Upon joining a competition, the user has no choice to leave that competition

**Comment by Didayolo** [comment]
Yes, the only way is to have the access revoked by the competition organizers.

**Comment by aghand0ur** [comment]
shall u consider adding that option at the user side?

**Comment by Didayolo** [comment]
Indeed, it is an interesting idea. I think it is mentioned here:
- #2692
