### ISSUE TITLE
Old Codalab Page - Security Certificate expired

### ISSUE THREAD

**Issue by parthpatwa** [codalab/codalab-competitions#3321]
The security certificate of the old codalab page has expired and it is no longer https. 
I am unable to approve participants in my competetions that are hosted on the old website. 

I am using google chrome browser. The same issue is there on firefox browser.

**Comment by Didayolo** [comment]
Thanks for reporting this issue. We are working on it.

**Comment by acletournel** [comment]
This error has been solved
