### ISSUE TITLE
failed to upload file

### ISSUE THREAD

**Issue by zhenghao977** [codalab/codalab-competitions#3323]
Hello, there seems to be a problem with the server, I cant upload my results file to the server(#6064,4763,). Could you help me?

**Comment by zhenghao977** [comment]
It cannot work... How to solve it

**Comment by rafariva** [comment]
same here. when uploading any result file, appears 0 byte.

**Comment by zhenghao977** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Didayolo** [comment]
@zhenghao977 @rafariva 

Can you describe the symptoms with more details please?

**Comment by zhenghao977** [comment]
@Didayolo Sure, thanks for your reply. I was trying to submit my result on this competition(https://codalab.lisn.upsaclay.fr/competitions/6064#participate-submit_results), but after serval minutes got "sorry, failed to upload your file" message. I have tried the Google chrome, Safiri and firefox , it all did not work. I can download the .zip file submitted successfully two days ago, but there is no a new submission. I also submitted my results to competition(#7680,#4763), and I got the same failed message. My platform is MacOS 12.03.
<img width="1238" alt="截屏2023-02-17 19 16 02" src="https://user-images.githubusercontent.com/46239371/219636076-25cf63dc-c19e-4535-b3e8-5bd6db7b67c4.png">

**Comment by buaawangyu** [comment]
hello ,i meet the same problem in 'NTIRE 2023 Bokeh Effect Transformation' ,have you solved it?

**Comment by Didayolo** [comment]
I cannot reproduce this bug

**Comment by zhenghao977** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
