### ISSUE TITLE
Submission Error "WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."

### ISSUE THREAD

**Issue by MinwooMin** [codalab/codalab-competitions#3324]
I am using Codalab to evaluate my results.
But the server is not working for some like below. 
I mailed the challenge organizer, and they said that it will work soon, so re-try the submission later.
But the same error message comes again...

<img width="826" alt="image" src="https://user-images.githubusercontent.com/125635022/219701800-e6dfe962-53c1-4dd4-88c4-08e40758847d.png">

**Comment by Didayolo** [comment]
> I mailed the challenge organizer, and they said that it will work soon, so re-try the submission later.

I guess they are still in the process of solving the problem.

It seems to be a problem related to Python version, or to the path.

Maybe they should check their competition docker image (https://github.com/codalab/codalab-competitions/wiki/User_Docker#default-docker-image).

If you or the organizers need help, please provide more information (competition URL, etc.)
