### ISSUE TITLE
download of leaderboard submissions does not include zip files

### ISSUE THREAD

**Issue by carandraug** [codalab/codalab-competitions#3327]
I'm organizer of this competiton https://competitions.codalab.org/competitions/26215 (in the old Codalab server)

I'm trying to download the leaderboard submissions but all  submission files are not correctly generated. For each submission in the download `-results.zip`, there should be one `-submission.zip` file. However, instead of zip files I'm getting XML files (with the zip file extension), that have a content like so:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>uploads/submissions/f0b0fcdd-b6d6-45ea-be11-e95dd66c4088/resnet34_epoch120_evalframes400.zip</Key>
  <BucketName>prod-private</BucketName>
  <Resource>/prod-private/uploads/submissions/f0b0fcdd-b6d6-45ea-be11-e95dd66c4088/resnet34_epoch120_evalframes400.zip</Resource>
  <RequestId>1747B5038B5B6A47</RequestId>
  <HostId>768b42c4-0504-41fc-9410-a8657a97cbcf</HostId>
</Error>
```

How can I download the results?

**Comment by carandraug** [comment]
Oh! That was unexpected. Are the files in question stored somewhere else? Can they be retrieved/recovered?

**Comment by Didayolo** [comment]
@carandraug 

To give you some context, when we had issues with the storage (disks filling up quickly) a while ago, we set a new infrastructure for the storage: a distributed MinIO. We saved the buckets of the competitions.codalab.org server there (like a backup). This server, competitions.codalab.org, is still using the old buckets (not in the distributed MinIO) and we had to remove some content to avoid having the disks full.

For these reasons, we believe that the files you are looking for are somewhere in the distributed MinIO. We are investigating this and we'll come back to you.

**Comment by Didayolo** [comment]
@carandraug 

If you wish that we send you all submissions from your leaderboard (and possibly other objects), please list the keys of all missing files. 

Example of the previous key you sent:

```
/prod-private/uploads/submissions/f0b0fcdd-b6d6-45ea-be11-e95dd66c4088/resnet34_epoch120_evalframes400.zip
```

We can also resolve that by email if it's more convenient.

**Comment by Didayolo** [comment]
Resolved by email. Soon in the future, we'll merge the old MinIO in the MinIO distributed.
