### ISSUE TITLE
Submission Failed when evaluating in test-dev COCO Detection Challenge (Segmentation Mask)

### ISSUE THREAD

**Issue by wangxiaoming1886** [codalab/codalab-competitions#3330]
Hi, 

My submission failed when evaluating in test-dev COCO Detection Challenge (Segmentation Mask).

The competition is:
https://codalab.lisn.upsaclay.fr/competitions/7383

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Could anyone help? Thanks!

**Comment by Didayolo** [comment]
Hi,

The logs that you are showing are just warning, and are similar when the submissions work.

Try to check the format of your submission. Is there any difference with an example working submission? Do you zip the prediction file directly, or do you zip an extra folder structure? Is the number of lines correct?

**Comment by wangxiaoming1886** [comment]
Hi,

My submission on val set in the competition succeed and the format of my test-dev submission is  the same as the val submission, so I think the format is fine.

However, the size of test-dev submission is about 300M, which is much bigger than the val submission(about 80M). Is it possible that the file is too big thus cause submission failure?

**Comment by Didayolo** [comment]
> Is it possible that the file is too big thus cause submission failure?

Yes, usually the size limit is 300MB.

**Comment by Qibear** [comment]
> Hi,
> 
> My submission on val set in the competition succeed and the format of my test-dev submission is the same as the val submission, so I think the format is fine.
> 
> However, the size of test-dev submission is about 300M, which is much bigger than the val submission(about 80M). Is it possible that the file is too big thus cause submission failure?

I tested on the test set and wrote the results into a json file, but the file size is 2G, why did you write it so that the file size is 300M
