### ISSUE TITLE
Stuck at running

### ISSUE THREAD

**Issue by kyillene** [codalab/codalab-competitions#3331]
Link to the challenge: https://codalab.lisn.upsaclay.fr/competitions/10962#participate-submit_results

Description of the problem: We can get the calculated scores via the [View scoring output log] button however the submissions are stuck on running (for more than 12 hours now) and the calculated scores are not published on the leaderboard as a result. 

Example output of the submission scoring output log. Keys and labels of these parameters are exactly the same in competition leaderboard.

PLCC:  0.014275977810007431
SROCC:  0.019515674357383397
Diff_Sim_AUC:  0.5120298106020695
Better_Worse_CC:  0.5227722772277228

Could you please direct me on how to resolve this issue?

**Comment by Didayolo** [comment]
Hi,

- Are you the competition organizer?
- Is there anything in the scoring program that could prevent it from finishing?
- Is the scoring program supposed to compute other scores, or only the four mentioned?
- Try to add some prints in the scoring program to identify where it get stuck

**Comment by kyillene** [comment]
Hi, thanks for the swift response.
Here answers to your questions and additional information:

- Yes, I am one of the competition organizers.
- I don't think so. (See below for the code)
- it is supposed to compute only the four scores I have listed in the first comment.
- I will do that immediately.

Here is the whole evaluate.py script.

```
# Reading arguments of input and output directories 
input_dir = sys.argv[1]
output_dir = sys.argv[2]

# creating submission path
submit_dir = os.path.join(input_dir, 'res')
# creating reference path 
truth_dir = os.path.join(input_dir, 'ref')

# verifying submission directory 
if not os.path.isdir(submit_dir):
    print ("%s doesn't exist" % submit_dir)

# verifying submission and refrence directories  
if os.path.isdir(submit_dir) and os.path.isdir(truth_dir):
    # creating output directory 
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # creating outfile ( scores.txt)
    output_filename = os.path.join(output_dir, 'scores.txt')
    output_file = open(output_filename, 'w')

    # creating path to reference data 
    gt_mos = pd.read_csv(os.path.join(truth_dir, 'mos_generic_highrange_validation.csv'))
    gt_signf = pd.read_csv(os.path.join(truth_dir, 'signf_generic_highrange_validation.csv'))

    # creating path to submmision data
    submission_answer_file = os.path.join(submit_dir, "predictions.csv")

    # reading and merging data
    pred = pd.read_csv(submission_answer_file)
	
    # Claculate metrics : Pearson_corr (plcc), spearman_rank_corr (srocc), root_mean_squared_error (rmse)
    SROCC, PLCC, Diff_Sim_AUC, Better_Worse_CC = get_metric_performance(pred, gt_signf, gt_mos)
    
    print('PLCC:' ,PLCC)
    print('SROCC:' ,SROCC)
    print('Diff_Sim_AUC:', Diff_Sim_AUC)
    print('Better_Worse_CC:', Better_Worse_CC)

    # Write to output file 
    if(np.isnan(PLCC)):
        PLCC = 0
    output_file.write("PLCC:{}".format(PLCC))

    if(np.isnan(SROCC)):
        SROCC = 0
    output_file.write("SROCC:{}".format(SROCC))

    if(np.isnan(Diff_Sim_AUC)):
        Diff_Sim_AUC = 0
    output_file.write("Diff_Sim_AUC:{}".format(Diff_Sim_AUC))

    if(np.isnan(Better_Worse_CC)):
        Better_Worse_CC = 0
    output_file.write("Better_Worse_CC:{}".format(Better_Worse_CC))

    # Closing file stream 
    output_file.close()
```

**Comment by kyillene** [comment]
![image](https://user-images.githubusercontent.com/32650583/222713878-6668fcca-baac-4e46-a0f0-d493a4b76103.png)


In addition, this is how it looks for PLCC on the Edit Competition page. The rest are the same except selection default=0

**Comment by kyillene** [comment]
As you recommended, I lightly edited the evaluate.py script and printed out some stuff to know where it gets stuck.
I moved the writing to scores.txt part towards the end of the script and made some modifications as you can find below:

```
    # Write to output file
    if(np.isnan(PLCC)):
        PLCC = 0
    if(np.isnan(SROCC)):
        SROCC = 0
    if(np.isnan(Diff_Sim_AUC)):
        Diff_Sim_AUC = 0
    if(np.isnan(Better_Worse_CC)):
        Better_Worse_CC = 0

    print('checked for nans in scores')
    # creating outfile ( scores.txt)
    output_filename = os.path.join(output_dir, 'scores.txt')
    output_file = open(output_filename, 'w+')
    print('opened output file')
    # writing
    output_file.write("PLCC:{}".format(PLCC))
    output_file.write("SROCC:{}".format(SROCC))
    output_file.write("Diff_Sim_AUC:{}".format(Diff_Sim_AUC))
    output_file.write("Better_Worse_CC:{}".format(Better_Worse_CC))
    print('assigned each criteria')
    # Closing file stream
    output_file.close()
    print('closed file')
```
with these modifications, I can see that we are actually reaching to the end of the script, stdout is as follows:

PLCC: 0.014275977810007424
SROCC: 0.019515674357383397
Diff_Sim_AUC: 0.5120298106020695
Better_Worse_CC: 0.5227722772277228
checked for nans in scores
opened output file
assigned each criteria
closed file

**Comment by kyillene** [comment]
Okay, I resolved the issue.
We made a stupid mistake by not moving to a new line.
Thanks for your time.
