### ISSUE TITLE
Editing LeaderBoard label after competition started

### ISSUE THREAD

**Issue by kyillene** [codalab/codalab-competitions#3333]
I am one of the organizers of the challenge linked below:
https://codalab.lisn.upsaclay.fr/competitions/10962

original yaml file displays the leaderboard info and leaderboard columns as follows:

![image](https://user-images.githubusercontent.com/32650583/223039847-1ddf7d3e-505a-41c9-805d-afa110d26a04.png)

I can change the column information freely on the edit panel however I dont see any option to change the leaderboard label.
![image](https://user-images.githubusercontent.com/32650583/223040236-aeeeadf3-fed3-4c02-a1e9-c6e225972bbc.png)

Is this intended? if there is any other way to change the leaderboard label after the competition is created, where and how?

Thanks,

**Comment by Didayolo** [comment]
Hi,

I think the option to change it should be the field "Label" (see in your screenshot).

However, I think there are known bugs about editing the leaderboard after the creation of the competition, bugs that were never fixed... Please confirm if it works or not by changing the field "Label".

**Comment by kyillene** [comment]
Hi,
I think "Label" allows to change the name of individual metrics (or Keys in the previous screenshot). In our case, changing the Label doesn't affect the leaderboard. 

Additionally, my question is actually about changing the leaderboard title rather than individual labels. See the screenshot below. I marked the area where I want to edit.
![image](https://user-images.githubusercontent.com/32650583/224708249-0a43cd29-46b7-4edf-9997-56edba7031c7.png)

Thanks

**Comment by Didayolo** [comment]
Oh, OK. Unfortunately, I think you need to re-upload the bundle to change the leaderboard label. Usually, you can edit everything from the editor, except the leaderboard columns, keys and labels. Sorry for the inconvenience.
