### ISSUE TITLE
Can the organizer restrict players to submit trained models and set up scripts for automatic scoring?

### ISSUE THREAD

**Issue by zjzser** [codalab/codalab-competitions#3335]
we are a research institution and we would like to initiate an audio forgery detection competition However, we are facing difficulties in setting up the allowed submission formats and custom evaluation metrics:

1：We would like participants to submit their trained models (e.g., .pt, .ckpt) rather than a single line of predictions or code. We know that executable code, predictions, or classes are allowed to be submitted, but we wonder if trained models can be submitted?
2：We would like to build our own custom script to evaluate participants' trained models.
Yes, evaluate the trained model in the first point

Can Codalab meet our needs in the above two points? What are the specific steps or guidelines that we need to follow, or what resources can you provide to help us?

**Comment by Didayolo** [comment]
Hi @zjzser,

> we wonder if trained models can be submitted?

Yes, trained model can be submitted. You need to have an ingestion program (the program that reads code submission), and to have submission looking like this:
```
submission.zip
│   model.py
│   trained_model.ckpt
|   metadata  
```

The metadata file can be left empty, it just indicates that it is a code submission. Loading the trained model can be done by the submitted code (model.py here).

> We would like to build our own custom script to evaluate participants' trained models.

It is possible. You can edit the ingestion program and the scoring program to your needs.

Some useful resources:
- https://github.com/codalab/codalab-competitions/wiki/Organizer-guide
- [https://github.com/codalab/competition-examples/tree/master/codalab/Iris](Iris competition bundle), in which you can see the programs (mainly [ingestion.py](https://github.com/codalab/competition-examples/blob/master/codalab/Iris/iris_competition_bundle/ingestion_program/ingestion.py) and [score.py](https://github.com/codalab/competition-examples/blob/master/codalab/Iris/iris_competition_bundle/scoring_program/score.py))
- https://github.com/codalab/codalab-competitions/wiki/User_Building-an-Ingestion-Program-for-a-Competition
- https://github.com/codalab/codalab-competitions/wiki/User_Building-a-Scoring-Program-for-a-Competition

If it's the first time your play with CodaLab Competitions and competition creation, I suggest you have a look at the following tutorial:
- https://github.com/codalab/codalab-competitions/wiki/Create-your-first-competition

**Comment by Didayolo** [comment]
Feel free to re-open the issue, or to send a question to info@codalab.org if you need more help.
