### ISSUE TITLE
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

### ISSUE THREAD

**Issue by DangTranQL** [codalab/codalab-competitions#3344]
Competition: GT-RAIN

I got this error when I submit a zip file consists of readme.txt and derained images. I have already tried several formats:
1. zip
        - GT-RAIN_val (contain folders of images)
        - GT-RAIN_test (contain folders of images)
        - readme.txt
 2. zip
       - readme.txt
       - Folders of images
 3. zip
       - readme.txt
       - Images
None of them works and I got that exactly same errors. All images with their folder have correct name

**Comment by ShreyasSR** [comment]
Hi, I'm a participant and facing the same error.
Competition: [UAVid Semantic Segmentation](https://codalab.lisn.upsaclay.fr/competitions/7302)
The log is as follows:


```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/codalab/tmpHm8WBu/run/program/addToConfusionMatrix.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ./program/addToConfusionMatrix.c:716:
/opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
Traceback (most recent call last):
  File "/tmp/codalab/tmpHm8WBu/run/program/evaluate.py", line 29, in <module>
    IOUs, mIOU, acc = evaluateFromDirectories(truth_dir, submit_dir)    
  File "/tmp/codalab/tmpHm8WBu/run/program/evaluate_dir.py", line 120, in evaluateFromDirectories
    cm = getConfusionMatrixfromDirectory(gt_home, pred_home)
  File "/tmp/codalab/tmpHm8WBu/run/program/evaluate_dir.py", line 100, in getConfusionMatrixfromDirectory
    assert osp.exists(pred_path), 'Prediction incomplete, cannot find prediction: %s'%(pred_path)
AssertionError: Prediction incomplete, cannot find prediction: /tmp/codalab/tmpHm8WBu/run/input/res/seq21/Labels/000600.png
```


There is an example submission [here](https://drive.google.com/file/d/1pI2oi-763PgR9IUk_jF4CKuZ4pmItQsl/view), and my submission matches the format.

**Comment by DangTranQL** [comment]
> 

Link: https://codalab.lisn.upsaclay.fr/competitions/7988#learn_the_details
I'm a participant

Ok, I think I figure it out. Some images have wrong size, just submitted again and got passed

**Comment by ShreyasSR** [comment]
In my case, all the images are matching the dimensions specified in the example submission.

**Comment by Didayolo** [comment]
If the example submission works but not yours, you should double-check your submission.

**Comment by xrr20001218** [comment]
> In my case, all the images are matching the dimensions specified in the example submission.

Have you solved this problem,？I have the same problem as you, how to solve it?
