### ISSUE TITLE
Submission upload has been disabled    VQA Real Image Challenge

### ISSUE THREAD

**Issue by codewithFlycat** [codalab/codalab-competitions#3345]
https://competitions.codalab.org/competitions/6961#participate-submit_results
When I submitted the VQA Real Image Challenge result file, the following information was prompted:
”Submission upload has been disabled.See the new instance at: https://codalab.lisn.upsaclay.fr/“
But I went to the new website suggested above, and there is no VQA challenge. Does this challenge no longer provide online tests?

**Comment by Didayolo** [comment]
Hi,

We made the choice of letting competition organizers transfer their competitions to the new server by themselves, so they keep everything under control.

It is a simple procedure (dump, download and then reupload).

Please reach directly VQA organizers to ask them to transfer their competition to [codalab.lisn.fr](https://codalab.lisn.fr).

**Comment by Didayolo** [comment]
I close this issue as it is clarified. Feel free to open a new issue if needed.
