### ISSUE TITLE
How to display the results from scoring program

### ISSUE THREAD

**Issue by YaoZhang93** [codalab/codalab-competitions#3352]
Hi,

I am developing a scoring program for an unpublished competition. Several metrics are calculated, and I want to know how to show the results on the result pages. Here is the [result page](https://codalab.lisn.upsaclay.fr/competitions/11866#results) from the Iris template:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/58619665/229557135-7fce1013-782f-41f0-b131-7226a1a0de5c.png">

Best regards,
Yao

**Comment by Didayolo** [comment]
Hi,

Let's take the Iris challenge as an example.

In the file [competition.yaml](https://github.com/codalab/competition-examples/blob/master/codalab/Iris/iris_competition_bundle/competition.yaml), the key of the score is defined. In this example, the key of "Prediction score" is `set1_score` (line 74).

The score output from the [scoring program](https://github.com/codalab/competition-examples/blob/master/codalab/Iris/iris_competition_bundle/scoring_program/score.py) needs to be written in a `score.txt` file, with the key `set1_score`. So, after the run, the score.txt file should contain something like `set1_score: 0.78`. See lines 75 and 114.

I hope this helps.

**Comment by YaoZhang93** [comment]
Thanks for your crystal clear instrution.
I have already start a competition by uploadling the template competition bundle. My score.txt is like this:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/58619665/229791550-e8838edd-7222-43b2-b758-8e734c89d577.png">
And I tried to show "Tumo_DSC", "Tumor_NSD", "Organ_DSC", and "Organ_NSD" in the result page. So I tried to edit the yaml file following your instruction like this:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/58619665/229790830-493b54f8-1a72-44ec-9683-e90442a09680.png">
However, the result page remained like this:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/58619665/229791223-f9349e37-dcb5-483b-8d7b-3681d66d7009.png">
Did I missing something?

**Comment by Didayolo** [comment]
> Did I missing something?

No, actually it is a known bug that the editor fails to edit leaderboard keys and labels... Sorry for the inconvenience.

You may need to re-upload the competition bundle, with the right keys and labels in the `competition.yaml` file.

**Comment by Didayolo** [comment]
(see #2686)

**Comment by YaoZhang93** [comment]
OK, I see. Is there any way to download the revised competition bundle? I found a button to download the original bundle but I have updated much information based on the original bundle. It will take too much time if I have to start again from the original bundle.

**Comment by YaoZhang93** [comment]
Goit it. Many thanks.
