### ISSUE TITLE
MVA2023 Small Object Detection issue

### ISSUE THREAD

**Issue by fayaz21** [codalab/codalab-competitions#3354]
Hello, I am facing problem with MMDetection Framework, openmmlab has recently updated there framework and modules,mmcv, my code which was running fine 24 hours ago is not running due to the altercations made, what do I do??

**Comment by Didayolo** [comment]
Hello,

This repository concerns the CodaLab Competition platform. If you need help on a problem linked to the platform, please describe your problem with more precision.
