### ISSUE TITLE
zipfile size

### ISSUE THREAD

**Issue by Yaobink** [codalab/codalab-competitions#3355]
Why is it that when I submitted my results for the MIND News Recommendation Competition, the size of my compressed file was 100MB, but the size displayed on the submission page was only 157750Bytes?

**Comment by Didayolo** [comment]
Hi,

Can you please give more information?
- The URL to the competition
- The submission file
- Your CodaLab ID

**Comment by dtuantran** [comment]
Hi,
As far as I know, the size showed on the submissions table isn't the size of your zip file. It's perhaps the sum of processed files in your submission bundle (i.e: result, output log, output error,...).
