### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by davideresta** [codalab/codalab-competitions#3357]
Looking for the LiTS Liver Tumor Segmentation Challenge I found this url among Google results:
https://codalab.lisn.upsaclay.fr/competitions/12089
which results in a “Page not found” message. Will the LiTS challenge (open leaderboard) be made available again in the future?
Thank you.

**Comment by Didayolo** [comment]
Hi,

As CodaLab platform administrators and developpers, we did nothing regarding the status of this competition. Please contact the LiTS organizers directly.

**Comment by davideresta** [comment]
Hi, thank you for your answer, I will.
