### ISSUE TITLE
Cannot Deny Participant

### ISSUE THREAD

**Issue by gholste** [codalab/codalab-competitions#3360]
1. If possible, please add `pavao` and `tthomas63` as admins to your competition so they may access it.
Done
2. Please post a link to your competition.
https://codalab.lisn.upsaclay.fr/competitions/12599

A participant has registered for my competition requiring my approval. I want to deny their request, but receive this error: "There was a problem processing this request for this competition." This happens in both Firefox and Chrome browsers.

<img width="1174" alt="Screen Shot 2023-04-21 at 5 07 28 PM" src="https://user-images.githubusercontent.com/26631259/233742120-b332f781-8b73-4745-81a5-176870f622a4.png">

**Comment by gholste** [comment]
@Didayolo @Tthomas63 Any idea what the problem is here? Participants are trying to join my competition, but I cannot respond to them... Am I doing something wrong? I'm just choosing "Deny" and then clicking "Process".

**Comment by Didayolo** [comment]
@gholste 

When I tried I could not reproduce the problem, it is working fine. Can you please retry?

By the way, when testing, I've approved `souryadipta` in your competition, please review if you want to accept this person or not in your competition.

**Comment by gholste** [comment]
@Didayolo Is there a tight word or character limit in the "Reason" field? I finally got this to work by shortening my text to one short sentence...

**Comment by Didayolo** [comment]
@gholste Yes indeed, I've done some tests and the problem seems to be related with the presence of special characters.

**Comment by gholste** [comment]
@Didayolo Can you elaborate on this? I still get the error message even if my response just contains English letters and periods. Is a period considered a "special character"?
