### ISSUE TITLE
Clicking on "View" in "Results" page displays blank panel

### ISSUE THREAD

**Issue by olyerickson** [codalab/codalab-competitions#3362]
In the "Results" page for any of our competitions on https://codalab.lisn.upsaclay.fr/ , clicking on a "View" link brings up essentially a blank page. 

One example: https://codalab.lisn.upsaclay.fr/competitions/11454#results

Clicking on any of the "View" links brings us to:

![image](https://user-images.githubusercontent.com/358649/234096070-ac510b70-7d06-4f07-9831-1556469bce2a.png)

**Comment by dtuantran** [comment]
It's probably because your result is empty.

**Comment by Didayolo** [comment]
This button leads to a HTML file written by the scoring program called `detailed_results.html`. It is optional. If the scoring program does not put text inside this file, it remains blank. You can disable this option in the editor ("enable detailed results").
