### ISSUE TITLE
Submission failed for COCO Detection Challenge

### ISSUE THREAD

**Issue by yaw91** [codalab/codalab-competitions#3364]
Hello all,

I get this error "codalab.lisn.upsaclay.fr  Sorry, failed to upload file." when I try to upload my results to COCO Detection Challenge (Bounding Box) (https://codalab.lisn.upsaclay.fr/competitions/7384#participate-submit_results)

I have tried uploading from both Chrome and Firefox but still get the same error.

Any help will be greatly appreciated.

**Comment by Didayolo** [comment]
Hi,

What is the size of your submission zip file?

**Comment by yaw91** [comment]
It's 134.5 MiB.

**Comment by Didayolo** [comment]
Were you able to make submissions in the past?

**Comment by yaw91** [comment]
Yes, I did.

**Comment by Didayolo** [comment]
And your submission files that were working in the past are not working anymore? Do you have any input from the organizers if they changed anything in the meantime?

**Comment by yaw91** [comment]
No, the previous submission are not working either. And there is nothing on
page that suggests there has been a change since my last successful
submissions. Do you know how I could contact the organizer?

**Comment by Didayolo** [comment]
I guess you can find their contact on the website: https://cocodataset.org/#home

**Comment by yaw91** [comment]
Thank you. But from
https://codalab.lisn.upsaclay.fr/competitions/7384#participate-submit_results
the organizer is Richardaecn and the person is not on the list of
organizers on https://cocodataset.org/#home.
