### ISSUE TITLE
Submissions stuck in "submitted" status

### ISSUE THREAD

**Issue by TOOFACK** [codalab/codalab-competitions#3367]
In a competition I'm running there are a number of submissions which aren't being run: they are stuck at the "Submitted" status for a long time. The competition is this one: https://codalab.lisn.upsaclay.fr/competitions/642#learn_the_details

**Comment by Didayolo** [comment]
I see that your competition is using a custom queue.

Did you connect your compute workers to the queue as explained here?
https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers

If you go to the compute workers and run `docker logs -f compute_worker`, what logs do you see?

**Comment by TOOFACK** [comment]
Seems like queue was full, now submissions start to run, anyway thanks!
