### ISSUE TITLE
Unexpected error submitting new zip file

### ISSUE THREAD

**Issue by AlbertoAlgarra** [codalab/codalab-competitions#3369]
I am trying to upload a zip file to a competition but the system keeps returning: "An unexpected error occurred." and fails to create the new submission, there are no error logs because it fails to create..
I have contacted the organizers and they have tried to upload my file and they did not get any error.
I have tried to do it from different browsers, Chrome, Mozilla and Safari, but in all of them it constantly returns the same error.

**Comment by Didayolo** [comment]
Hi,

Your problem is quite disconcerting, especially as the organizers were able to submit your file.

In the past, were you able to submit any submission to any competition? Or do you always have this problem?

**Comment by AlbertoAlgarra** [comment]
Hi Adrien, Thanks for your response. You can check the forum https://codalab.lisn.upsaclay.fr/forums/10990/1741/ where the user pughrob found a solution to submit the results. The problem seems to be in the form you have to fill to submit the results. Thank you so much. Regards, Enviado desde mi teléfono Huawei-------- Mensaje original --------De: Adrien Pavão ***@***.***>Fecha: lun., 22 may. 2023 13:04Para: codalab/codalab-competitions ***@***.***>Cc: AlbertoAlgarra ***@***.***>, Author ***@***.***>Asunto: Re: [codalab/codalab-competitions] Unexpected error submitting new zip file (Issue #3369)
Hi,
Your problem is quite disconcerting, especially as the organizers were able to submit your file.
In the past, were you able to submit any submission to any competition? Or do you always have this problem?

**Comment by igorkf** [comment]
I was getting the same error.
What I did to solve it was to submit the zip file without writing anything in the form. You can go to your last submission and update the description later to keep track of what this submission was about.
