### ISSUE TITLE
Wrong file format for submission?

### ISSUE THREAD

**Issue by yuge2648474909** [codalab/codalab-competitions#3371]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpjBSaH0/run/program/cocoEvalCapCoda.py", line 59, in 
    res = json.load(open(resFile))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpjBSaH0/run/input/res/captions_test2014__results.json'

**Comment by Didayolo** [comment]
Hi,

It seems that a file is missing either in the submission or in the reference data (the ground truth).

Please contact the competition organizers for help. If you need further assistance from the administrators, please provide more information (URL of the competition, description of the problem, submitted file, if it worked in the past, etc.)
