### ISSUE TITLE
Downloading submission fails

### ISSUE THREAD

**Issue by Attila94** [codalab/codalab-competitions#3375]
I'm trying to download a submission of an old competition I have organized, but keep getting the following error:

````
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
uploads/submissions/83c61d96-e6ea-469d-b471-d88f78054ba1/submission.zip
</Key>
<BucketName>py3-private</BucketName>
<Resource>
/py3-private/uploads/submissions/83c61d96-e6ea-469d-b471-d88f78054ba1/submission.zip
</Resource>
<RequestId>176269DBB0BEF4D3</RequestId>
<HostId>016731cd-3863-432e-a55a-b6fcd5a9d447</HostId>
</Error>
````

This error only occurs for the submission made by oskayhan on 7/1/2022, 12:18:39 PM, submission ID 148352.

Any help would be appreciated. Thanks!

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` and `tthomas63` as admins to your competition so they may access it.
> Done
2. Please post a link to your competition.
> https://codalab.lisn.upsaclay.fr/competitions/4696

If you are having trouble using the site:
-----------------------------------------

1. What browser and version are you using?
> Safari Version 16.0 (17614.1.25.9.10, 17614)
2. What is the URL of the problem? Codalab is an open source project, we may not be supporting the instance you are using!
> https://miniodis-rproxy.lisn.upsaclay.fr/py3-private/uploads/submissions/83c61d96-e6ea-469d-b471-d88f78054ba1/submission.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20230525%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230525T144002Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=5b93913ceb4e44aa657341ab0715b383a9f00eac9789497ca2aa75ae11ed10db

**Comment by Didayolo** [comment]
Same problem as:
- #3327

**Comment by dtuantran** [comment]
Sorry that somehow this file is no longer in the MinIO database. We are investigating what happened ?
