### ISSUE TITLE
Unable to update Competition docker image field

### ISSUE THREAD

**Issue by shreyashampali** [codalab/codalab-competitions#3376]
hi @Tthomas63  / pavao

I am organizing the H2O3D competition and I want to use the docker image: codalab/codalab-legacy:py2
Unfortunately, I am not able to successfully update the Competition docker image field in the competition. After I update and reload the page, the field is reset to blank and the submissions are still using python3.9 which is the default image. Can you please help in updating the docker image for this competition? I have added both of you are the admins.

regards,
Shreyas

**Comment by Didayolo** [comment]
Hi,

- What is the URL to your competition?

- When you save the changes from the editor, does it come back to your competition homepage?

- The default image uses python3.7

**Comment by dqj5182** [comment]
The URL of competition is https://codalab.lisn.upsaclay.fr/competitions/4897

**Comment by shreyashampali** [comment]
@Didayolo ,

- The website is https://codalab.lisn.upsaclay.fr/competitions/4897 (sorry, forgot to mention earlier)
- No, after saving it is still in the 'edit' page. Also I just noticed I cant add you as admin as well. After adding your id and submitting, the field is empty again. "Competition docker image" field is not empty at this point, but it will be erased out if I go to some other page and come back to the edit page.
- Yes, but I would like to use python2

**Comment by Didayolo** [comment]
So, when you save changes, you are supposed to be redirected to the homepage of the competition. When you get back to the editor, it means that an error prevents you to save the changes.

Usually, in this case, you can scroll down and try to spot an red error message. It is not very convenient, but I was able to find this in your case:



The submission size limit for the whole platform is 300 MB right now. If you wish the we, as administrator of the public instance codalab.lisn.fr, increase the limit of your competition, you need to discuss the dimension of the competition with us (what size of submissions? how many participants? etc.)

**Comment by shreyashampali** [comment]
Thanks for helping with this @Didayolo 

Unfortunately, even after the update the evaluation code seems to be using the newer docker image (python3.9). Here is the error message which is same as earlier:
`Traceback (most recent call last):
  File "/tmp/codalab/tmpgjYYXa/run/program/evaluate.py", line 22, in <module>
    import open3d as o3d
  File "/opt/conda/lib/python3.9/site-packages/open3d/__init__.py", line 9, in <module>
    from open3d.linux import *
  File "/opt/conda/lib/python3.9/site-packages/open3d/linux/__init__.py", line 7, in <module>
    globals().update(importlib.import_module('open3d.linux.open3d').__dict__)
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.9/site-packages/open3d/linux/open3d.so: undefined symbol: _Py_ZeroStruct`

Not sure, why it isn't using the 'codalab/codalab-legacy:py2' !

**Comment by shreyashampali** [comment]
thanks @Didayolo it works now :)

**Comment by Didayolo** [comment]
Nice to hear :-)
