### ISSUE TITLE
About adding members during the competition

### ISSUE THREAD

**Issue by Acie7J** [codalab/codalab-competitions#3379]
Before I add a member to my team, does that member need to complete the CodaLab registration?Or can I just write his name in Settings?

**Comment by Didayolo** [comment]
Hi,

I think the member need to be registered to the platform.

Feel free to continue the discussion if you have more questions.

**Comment by Acie7J** [comment]
I still have some questions that I haven't figured out. If I create a team, enter the team name and member information. Later if a member registers for the contest, does he need to manually enter our team name and other members' information?
