### ISSUE TITLE
failed to upload file

### ISSUE THREAD

**Issue by kyxxc** [codalab/codalab-competitions#3382]
What browser and version are you using?
Hello, I kept prompting for file upload failure when submitting a competition project

**Comment by Didayolo** [comment]
Hi,

Please be more specific.

- You are trying to upload a bundle on codalab.lisn.fr ?
- What error message do you get ?
- Any useful information to help you

**Comment by kyxxc** [comment]
Hello, when I submitted the evaluation of the HO-3D dataset, it displayed 'failed to upload file', and my file submission format is correct.

I would like to ask how to solve this problem

**Comment by Didayolo** [comment]
- Do you have the same problem with the example submission provided by the organizers (if any)?
- Do other participants face the same issue?
- Did you contact the organizers of the challenge?
- Was it working fine in the past?

**Comment by kyxxc** [comment]
hello


At present, I am unable to contact the organizer as there are precedents of successful submissions in the competition in the past

The following image is publicly available by the organizer







X
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "codalab/codalab-competitions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [codalab/codalab-competitions] failed to upload file (Issue #3382)





  
Do you have the same problem with the example submission provided by the organizers (if any)?
 
Do other participants face the same issue?
 
Did you contact the organizers of the challenge?
 
Was it working fine in the past?
