### ISSUE TITLE
Do I need to change my username to the team name, and will the honors involve the names of each team member?

### ISSUE THREAD

**Issue by achuansztu** [codalab/codalab-competitions#3383]

**Comment by Didayolo** [comment]
I don't think this is possible. A solution may be to create an account for your team.

**Comment by achuansztu** [comment]
Thank you for your answer!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adrien ***@***.***&gt;; 
发送时间: 2023年6月21日(星期三) 晚上9:14
收件人: ***@***.***&gt;; 
抄送: " ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [codalab/codalab-competitions] Do I need to change my username to the team name, and will the honors involve the names of each team member? (Issue #3383)





 
I don't think this is possible. A solution may be to create an account for your team.

**Comment by achuansztu** [comment]
Will the honors involve the names of each team member? Best wishes

**Comment by Didayolo** [comment]
Hi, this is a question for the challenge organizers.
