### ISSUE TITLE
Facing issues as disk quota exceeded for SQuaD 2.0 leaderboard submission

### ISSUE THREAD

**Issue by sidarora1990** [codalab/codalab-competitions#3386]
As per the instructions mentioned for SQuaD 2.0 leaderboard ([https://worksheets.codalab.org/worksheets/0x8212d84ca41c4150b555a075b19ccc05/]), each user would be provided a 10GB of disk space. But, it seems I am getting just 100 MB of disk space(PFA - squad_disk_issue.jpg, squad_disk_issue2.jpg). As of now, I am unable to upload anything on Codalab. So, I humbly request you to please help me out in resolving this issue.

Codalab Information

Your username: sidarora1990
UUID of worksheet where problem occurred: Squad_exp1
Error message received from Codalab (if applicable): User Disk Quota exceeded (PFA)

Expected behavior
As per the instructions on SQuad 2.0 leaderboard submission, 
![squad_disk_issue](https://github.com/codalab/codalab-competitions/assets/13280479/e2e58d48-36a7-4a33-9d2e-19e97206af7f)
each user should be given a disk space of 10 GB which I am not getting currently (PFA-squad_disk_allot.png).
![squad_disk_allot](https://github.com/codalab/codalab-competitions/assets/13280479/332f64d0-5f97-4fe4-801e-58ce0893f6e1)

![squad_disk_issue2](https://github.com/codalab/codalab-competitions/assets/13280479/fe2dffc2-ddd6-43c0-9257-3c14a2e0940e)

**Comment by Didayolo** [comment]
Hi @sidarora1990,

Please transfer your issue into the following repository: 

https://github.com/codalab/codalab-worksheets

Indeed, your problem concerns CodaLab Worksheets, which is a separated project from CodaLab Competitions. 
Thank you for your comprehension.
