### ISSUE TITLE
Not enough disk space in account, unable to upload bundle

### ISSUE THREAD

**Issue by sywf13** [codalab/codalab-competitions#3390]
I have **only 100mb of disk space** in my account instead of the Default 10gb mentioned in Squad 2.0 Submission Guide, as a result I'm unable to upload files in my worksheet. **I have to upload around 400mb of data for a model of around 10gb**.

**Codalab Information**
- *username*: sywf
- *UUID of worksheet where problem occurred*: home-sywf
- *UUID of problem bundle (please don't delete)*: couldn't upload bundle due to disk size
- *Error message received from Codalab (if applicable)*:  UsageError: Upload failed: Can't save bundle, bundle size 435715964 greater than user's disk quota left: 104624334.0
 - *OS (if on CLI)*: Windows 11
 - *Codalab CLI Version (if on CLI)*:  CodaLab CLI version 1.6.3
 - *Browser (if on Web)*; NA

**To Reproduce**
Steps to reproduce the behavior :
Screenshot of error and command attached below.

**Expected behavior**
The file should have uploaded Successfully.

**Screenshots**
![codalab_error_cmd](https://github.com/codalab/codalab-worksheets/assets/137287199/b678d63a-6254-4e82-b588-b263d34f82b2)

**Additional context**
NA

**Comment by Didayolo** [comment]
Hello,

I think your problem concerns [CodaLab Worksheets](https://github.com/codalab/codalab-worksheets), not CodaLab Competitions. It is two independant projects. This repository concerns CodaLab Competitions.

Please re-open your issue here:
https://github.com/codalab/codalab-worksheets/issues
