### ISSUE TITLE
Cannot Create New Page on CodaLab Competition

### ISSUE THREAD

**Issue by gholste** [codalab/codalab-competitions#3392]
I want to add a new page to my CodaLab competition and cannot do so. Here are the steps I'm following: click "Edit" under "Organizer features", then click "Add Page" under "Web Pages", then enter my desired content, and click "Submit". When I do this, no matter the content (**even if I name the page "Test" and input "Test" as the main content**), the Edit Competition page hangs for 5-10 seconds, then returns me to the top of the Edit Competition page. The changes are not reflected on the competition website and there is no error message indicating what went wrong.

If you are an organizer and have problem hosting your competition:
------------------------------------------------------------------

1. If possible, please add `pavao` as admin to your competition so they may access it.
Done
2. Please post a link to your competition.
https://codalab.lisn.upsaclay.fr/competitions/12599

**Comment by Didayolo** [comment]
Unfortunately, it seems to be a known bug of the platform: #3090

As your competition is already on-going, I guess the only work-around is too add any information you wish into existing pages.

Sorry for the inconvenience.
