### ISSUE TITLE
Access to codalab.lisn.upsaclay.fr was denied when trying to download competition CSV

### ISSUE THREAD

**Issue by malteschwerin** [codalab/codalab-competitions#3395]
I was trying to download the CSV results from different competition (e.g., https://codalab.lisn.upsaclay.fr/competitions/7680#results), but always get an access denied error. Edge and Chrome show the actual error page saying that I don't have the user rights to view the page, Firefox just shows an empty page.

I'm new to CodaLab, so I'm not sure if I'm actually supposed to be able to download these files. However, the UI gives me the impression that I should.

For context: I'm not looking for data from a specific competition, but in general for raw data (performance of each competitor for each problem instance) from various competitions to examine this data.

**Comment by Didayolo** [comment]
You are supposed to be able to download this CSV files. Unfortunately, this is actually an error we have since the Python3 update. I am interested in solving it too.

> For context: I'm not looking for data from a specific competition, but in general for raw data (performance of each competitor for each problem instance) from various competitions to examine this data.

I am actually interested in such analysis too! May I ask what is your goal there?

**Comment by malteschwerin** [comment]
Thanks for the quick reply! Is there any plan to fix this in the near future?

**Comment by malteschwerin** [comment]
@Didayolo from what I've seen we're working on similar things, namely researching different ranking methods for competitions.

**Comment by KnowledgeGarden** [comment]
The problem persists:
https://codalab.lisn.upsaclay.fr/competitions/14596/results/23409/data
is an empty page for me.

**Comment by KnowledgeGarden** [comment]
Same for the practice data
https://codalab.lisn.upsaclay.fr/competitions/14596/results/23407/data
In fact - and this seems strange, all of the linked datasets - both Spanish and English - return empty pages.
What am I missing?

**Comment by Didayolo** [comment]
The problem being an "access denied", it should not be too hard to solve. I'll discuss it with my colleagues.

@malteschwerin Nice to see that we are working on similar topics. It is rare to find people working on the methodology of competitions! If you wish to discuss it more, feel free to reach me by email.

**Comment by Didayolo** [comment]
When you are organizer of the competition, the button works. But not if you are a regular participant. We are looking into the problem.

We can see that the button is simply a link to the `/data` URL of the competition's phase:

https://github.com/codalab/codalab-competitions/blob/68036d9b06272ce23572d121c85b3c00ee49a21a/codalab/apps/web/templates/web/competitions/_results_page.html#L30

**Comment by Didayolo** [comment]
It should be fixed now.
