### ISSUE TITLE
Questions about leaderboard

### ISSUE THREAD

**Issue by kszpxxzmc** [codalab/codalab-competitions#3409]
1. If I want to use different leaderboards in different phases, what should I do?
2. If I only want to use one metric as the standard for ranking in the leaderboard, what other operations besides "operation: Avg" could be used to calculate the ranking?

**Comment by Didayolo** [comment]
Hello,

> If I want to use different leaderboards in different phases, what should I do?

If you want to use the same scores and leaderboard structure, but re-do it from scratch for each phase, then you have nothing to do. It is the default behavior. If you want different leaderboard structures for each phase, you'll need to declare several leaderboards in the competition.yaml file.

See:
- https://github.com/codalab/codalab-competitions/wiki/Organizer_Codalab-competition-YAML-definition-language
- https://github.com/codalab/codalab-competitions/wiki/Organizer_Leaderboard

> If I only want to use one metric as the standard for ranking in the leaderboard, what other operations besides "operation: Avg" could be used to calculate the ranking?

The operations are useful if you want to combine several columns from the leaderboard. For only one main metric, you don't need to use operations. You can specify the metrics you want by customizing the scoring program.

See:
- https://github.com/codalab/codalab-competitions/wiki/User_Building-a-Scoring-Program-for-a-Competition

I hope this helps.

**Comment by Didayolo** [comment]
Feel free to re-open the issue if you have more questions.

**Comment by kszpxxzmc** [comment]
Thanks !
