### ISSUE TITLE
Submission ingestion failing after 10 minutes

### ISSUE THREAD

**Issue by ch-shin** [codalab/codalab-competitions#3415]
Hello! We're running the AutoML Cup competition and we are finding that jobs are getting stuck after ~10 minutes. A competitor ran an experiment that just set a timer that prints progress confirming that it indeed seems to get stuck. We've run our own experiments confirming this issue, but we are also finding the timings to be inconsistent:

<Submission failing case 1 --- Participant's submission>
![image](https://github.com/codalab/codalab-competitions/assets/28736511/17a4fd6a-748f-4934-ae88-3d256f963394)

This participant noticed submissions were getting suck around 10 minutes and did their own experiment by adding a for-loop
which sleeps for 1 minute and prints the passed time. It reveals that it get stucks after ~10 minutes, without any error msg.

<Submission failing case 2 --- Our reproduce>
![image](https://github.com/codalab/codalab-competitions/assets/28736511/ec103048-e45d-4e95-9f22-5f20a311c094)
We observed the similar bug --- the training is supposed to run until epoch=10, but it gets. stuck around epoch 5 and just move to  next task.

Relatively short ones don't have such problems, e.g.
![image](https://github.com/codalab/codalab-competitions/assets/28736511/6dee8b93-5870-4dd3-b371-d71ab66d2c11)
--- which took ~2mins and terminated normally.

We are wondering if ingestion itself has a time limit or it is a bug. Could you look into this? Thanks!

Competition links (All have the same issue)
* https://www.codabench.org/competitions/984/
* https://www.codabench.org/competitions/1158/
* https://www.codabench.org/competitions/1232/

**Comment by Didayolo** [comment]
Hello,

Are you using the default queue?

If so, I think your problem is this one:
- #3413

which affects unfortunately both codalab.lisn.fr and codabench.org

**Comment by Didayolo** [comment]
If you are using your own queue:

- Try to fetch the logs of the compute worker. Go inside one of the workers and run `docker logs compute_worker`. Paste here any errors or strange logs.

- Was the submissions in question working before? When? Did you changed something in between?

**Comment by Didayolo** [comment]
With no response, I assume it is working now.
