### ISSUE TITLE
Feature - Asking admin when "re-run all submissions" if there are too many submissions

### ISSUE THREAD

**Issue by dtuantran** [codalab/codalab-competitions#3417]
## Context
When an organizer "**re-run all submissions**" of some competition having **hundreds or thousands submissions**, our default queue will be congested.

## Proposal
Checking if the submissions number is too big (e.g: > 200) and the competition is using the default queue, then do not allow the organizer to re-run all submission, ask the organizer to request Codalab Admin by email info@codalab.org. Or the organizer can change to other queue with their own compute worker to avoid blocking other competitions.

**Comment by Didayolo** [comment]
I think the button "Re-run all submissions" is clickable only if you are admin of the platform (on CodaLab Competitions).
