### ISSUE TITLE
Error: Failed, competition phase is being migrated, please try again in a few minutes.

### ISSUE THREAD

**Issue by Tsing27** [codalab/codalab-competitions#3418]
Hello, I am a participant in the 2023 IEEE VIP Cup. For the past three days, I have been receiving an error message stating "Failed, competition phase is being migrated, please try again in a few minutes" every time I try to upload a file.  I would like to enquire if there is an issue with my account and what could be done to successfully upload my file.

**Comment by Didayolo** [comment]
Hello,

- Where you able to make successful submissions in the past?
- Do other participants report the same problem?
- Did you try to contact the challenge organizers?

**Comment by Patchwork53** [comment]
Hello, I am a participant in 2023 IEEE VIP Cup as well. I have the same problem and I was able to submit before 11 August.

**Comment by Tsing27** [comment]
> 

Thank you for your reply.

- I was able to successfully upload the results in the same way before, but four days ago it displayed this error message and failed to do so.

- It seems that I am not the only one experiencing this.

- I've tried emailing the organisers but haven't had a reply yet.
