### ISSUE TITLE
Output results is nan

### ISSUE THREAD

**Issue by lseventeen** [codalab/codalab-competitions#3420]
Hello, I submitted the test results to the platform and soon the results were shown as nan and could not display the correct score.

The scoring error log:
/usr/local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by lseventeen** [comment]
> Hello,
> 
> * Are you a participant or a competition organizer?
> * What is the URL of the competition?
> * Are you submitting a base submission provided by the organizers or your own submission?
> * The error suggests that you have invalid values in your submission

Thank you for your reply. 

I am a participant. The URL of the competition is https://codalab.lisn.upsaclay.fr/competitions/12239. I am submitting our own submission. Previous successful submissions also output nan. 
![image](https://github.com/codalab/codalab-competitions/assets/48872641/bafe9412-04a1-462e-aa82-a56e0944569e)

**Comment by Didayolo** [comment]
Can you please try to re-submit a submission that was working before? Typically "fsl_w1_1_dice[...].zip"

**Comment by lseventeen** [comment]
The same problem can also arise. 

![image](https://github.com/codalab/codalab-competitions/assets/48872641/00f059e4-6639-4321-abcc-5f91e82340d5)

**Comment by lseventeen** [comment]
I don't know what happened, but it can be submitted normally.

**Comment by Didayolo** [comment]
I think we had connection errors in the compute workers, and it is getting more stable.
