### ISSUE TITLE
Where to find sourcecode

### ISSUE THREAD

**Issue by wasalm** [codalab/codalab-competitions#3421]
Dear admin,

Where can I find the source code of **competitions-v2-compute-worker**?
I only found the repository of the v1 version. As its main branch is very outdated, I don't know where to find the latest code.

**Comment by Didayolo** [comment]
The code of `competitions-v2-compute-worker` can be found here:

https://github.com/codalab/codabench/tree/develop/compute_worker

Note that the "v2" compute workers are compatible only with [Codabench](https://www.codabench.org/), not with [CodaLab Competitions](https://codalab.lisn.fr/).

For compute workers linked to CodaLab Competitions, you should use v1 compute worker. The latest version is stable and not considered outdated.

If you are interested in testing the new, modernized, version of CodaLab, I invite you to try out Codabench.
