### ISSUE TITLE
"Failed, competition phase is being migrated, please try again in a few minutes"

### ISSUE THREAD

**Issue by prithwijitc** [codalab/codalab-competitions#3422]
This problems has been reoccurring for the past couple of days. I have removed the "auto-migration" options between phases as well as deleted all "failed" and "running" submissions. However this problem still persists.

Competition: https://codalab.lisn.upsaclay.fr/competitions/14006

**Comment by Didayolo** [comment]
Hi,

Do you have the error for all submissions? Or sometimes it works and sometimes it fails?

Did you change something from the last time it was working fine?

**Comment by Didayolo** [comment]
Are you using the default queue of CodaLab, or a custom queue with your own compute workers?

**Comment by Didayolo** [comment]
I merged this issue with a more general one: #3426
