### ISSUE TITLE
CodaLab competitions website down

### ISSUE THREAD

**Issue by mmazeika** [codalab/codalab-competitions#3424]
The CodaLab competitions website ([codalab.lisn.upsaclay.fr](url)) has been down for the past half-day. Is this being fixed? Is there an email address I can contact to find out more? (With the website down, I'm not sure who exactly to contact.)

**Comment by bkkm78** [comment]
I am having the same issue

**Comment by touhid314** [comment]
I cannot access the website too.

**Comment by AliRajaei95** [comment]
Same problem.

**Comment by agarioud** [comment]
Same observation, echoed by several participants. @Didayolo , @dtuantran , for your information.

**Comment by llw2012** [comment]
Same problem, too

**Comment by chiyuzhang94** [comment]
I am facing same issue. Cannot access any competition.

**Comment by Didayolo** [comment]
Thank you for reporting. https://www.codabench.org/ is down too.

We'll investigate the problem as soon as possible.

**Comment by Didayolo** [comment]
To resume the service, we may need a physical access to the machines. Unfortunately, our laboratory is closed until Monday morning.

**Comment by Didayolo** [comment]
@mmazeika @bkkm78 @chiyuzhang94 @llw2012 @agarioud @hyeonminkim0625 @MSiam @AliRajaei95 @nicoladicicco

Good news! Finally we were able to log into the servers remotely. The servers are back to life:

- https://codalab.lisn.fr/
- https://www.codabench.org/

Have a nice week-end.

**Comment by shourya01** [comment]
I am facing an issue wherein any submission returns the error: "Failed, competition phase is being migrated, please try again in a few minutes", similar to #3422 .


Submissions were working fine before the server went down. So I am wondering if this issue is due to the downtime?

**Comment by Didayolo** [comment]
@shourya01 Thank you for reporting.

@dtuantran Do you think this could be linked to the minio-dis problems?
