### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools' error while evaluating  

### ISSUE THREAD

**Issue by dongseop-kim** [codalab/codalab-competitions#3428]
Hi,
I want to participate in the 7916, but an error message occurs after submitting the results to the evaluation server.

> https://codalab.lisn.upsaclay.fr/competitions/7916

the error message is 

> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpNE4Z4T/run/program/evaluate.py", line 4, in 
    from pycocotools.coco import COCO
ModuleNotFoundError: No module named 'pycocotools'

**Comment by Didayolo** [comment]
Hi,

You should contact the organizers of the competition, and ask them to add `pycotools` inside the competition docker image.

Thank you for your comprehension.
