### ISSUE TITLE
bad gateway

### ISSUE THREAD

**Issue by parthpatwa** [codalab/codalab-competitions#3429]
using google hrome 
url: https://competitions.codalab.org/

I get "bad gateway"

**Comment by dtuantran** [comment]
Hi @parthpatwa 
We are investigating this issue and are trying to make the service available as soon as possible. Sorry for any inconvenient.

**Comment by dtuantran** [comment]
Our infrastructure had an incident about 12 a.m 10/09. We've restored the services.
