### ISSUE TITLE
Technical Problem: Got stuck while submitting result files.

### ISSUE THREAD

**Issue by HELLORPG** [codalab/codalab-competitions#3433]
When I try to upload my result files to a competition on CodaLab, the site seems stuck in the submission process for several hours, like:

<img width="817" alt="image" src="https://github.com/codalab/codalab-competitions/assets/41836383/1a53814f-840f-4457-b225-a63376700d4d">

I also logged in with my friend's account but got the same problem. I changed into another competition but still.

**Comment by agarioud** [comment]
@Didayolo @dtuantran 

As a competition organizer, I've noticed that all submissions have been stuck since 4 AM, as described above.

**Comment by meidachen** [comment]
Same here, and this is the last day of the competition. Please help.

**Comment by melexi** [comment]
My runs have also been stuck in the 'Submitting' phase for over 2 hours now, which is quite unusual. Normally it takes at most 2 minutes to reach another status. I would greatly appreciate it if that problem could be resolved.

**Comment by zgp123-wq** [comment]
My runs have also been stuck in the 'Submitting' phase for over 10 hours now, which is quite unusual. Normally it takes at most 2 minutes to reach another status. I would greatly appreciate it if that problem could be resolved.

**Comment by hyxie2023** [comment]
I'm having the same issue and have very few days remaining in my competition. I'd like to know when the system will be back to normal.

**Comment by Jack-bo1220** [comment]
same question！

**Comment by hanzifan** [comment]
same issue here

**Comment by hxwork** [comment]
Same issue.

**Comment by lvyuchen2018** [comment]
+1

**Comment by HaoshuaiXu** [comment]
Same issue.

**Comment by louisreberga** [comment]
+1

**Comment by dtuantran** [comment]
Dear all,

One of our container (worker_site) was crash this week-end, therefore all submissions was blocking. We've restarted the service and it's going working. Please be patient few hours for processing the blocking submissions. Sorry for every inconvenient.

Best regards,

**Comment by Didayolo** [comment]
The congestion is almost completely absorbed.
