### ISSUE TITLE
Resquest to change my username on CodaLab

### ISSUE THREAD

**Issue by QQQHY** [codalab/codalab-competitions#3438]
Dear CodaLab Team,

I would like to change my Codalab username because of a typo.

My current username is: G220564K
I would like it to be changed to: G2205164K

Thanks for your help.

**Comment by dtuantran** [comment]
Dear,
Sorry that we can't validate your request. How we can verify that you are this account's owner ? How it will affect the leader boards of the competitions which you participated in ?

**Comment by Didayolo** [comment]
Dear user,

We generally do not accept username change request. If you think you have a valid reason for such request, please write an email to info@codalab.org, using your CodaLab account email, so we can ensure it is indeed your account.

Best regards
