### ISSUE TITLE
Submissions are failing with error elapsedTime（MSCOCO competition segmentation mask）

### ISSUE THREAD

**Issue by xlim1996** [codalab/codalab-competitions#3441]
I'm using  detectron2 and got the result.json from my model, which is 1.2GB. I can only compress it to 380MB with zip. And when I submitted it to https://codalab.lisn.upsaclay.fr/competitions/7383. Submissions are constantly failing with error elapsed time.
If you can help me to solve the problem, I will appreciate it.

error detail:
elapsedTime: 174.19653415679932
exitCode: 137
ingestionExitCode: 0

**Comment by Didayolo** [comment]
Hello,

Your problem is specific to MSCOCO competition. Please contact the organizers or use the competition forum.

An error "elapsed time" probably mean that your submission exceed the given time limit. Try to submit a lighter submission to see if it solves the problem.

**Comment by xlim1996** [comment]
Ok. Thanks a lot.
