### ISSUE TITLE
Can scoring program run on python>=3.10?

### ISSUE THREAD

**Issue by gorkamunoz** [codalab/codalab-competitions#3444]
Hi, is it possible to run the scoring program in the server in Python >= 3.10? I have seen that currently it is running in 3.9, but I need some packages that only run in above 3.10. Is there a workaround to this?

Thanks!

**Comment by Didayolo** [comment]
Hello, yes, it is possible to change it.

The scoring program runs inside a Docker container. The image used is a competition setting.

As an **organizer**, you can change this setting either in the "Edit" ("competition Docker image") or in the `competition.yaml` file ("competition_docker_image" field).

The default image is `codalab/codalab-legacy:py37`, any other Docker image can be used using its DockerHub tag.

If you are a competition **participant**, please reach the organizers for any request about the Docker environment of the competition.

**Comment by gorkamunoz** [comment]
Hi, thanks for the answer. I am the organizer of a competition. I understand that if I want python 3.10 I need to create my own Docker container?

**Comment by Didayolo** [comment]
Yes. You can use any image on DockerHub, including your own.

The most recent image proposed by CodaLab uses Python 3.9: https://github.com/codalab/codalab-dockers.

You can either create an image from scratch, or "fork" an existing `codalab-legacy` image.

**Comment by gorkamunoz** [comment]
Thanks, we will go for our custom Docker.
