### ISSUE TITLE
No Space left on device

### ISSUE THREAD

**Issue by Xiangxu-0103** [codalab/codalab-competitions#3445]
Hi, when I submit my files to SemanticKITTI challenges: https://codalab.lisn.upsaclay.fr/competitions/6280#participate-submit_results

It will raise an error that `No Space left on device`.

**Comment by Didayolo** [comment]
This is surprising. I checked the compute workers of the default queue and they have free space.

Is this competition intensive in terms of memory / storage usage?

Does the issue happen on every submission or is it only raised randomly?

**Comment by Xiangxu-0103** [comment]
I think this issue is raised randomly and it has been submitted successfully for now.
