### ISSUE TITLE
Accessing results of previous submissions from the scoring_program

### ISSUE THREAD

**Issue by gorkamunoz** [codalab/codalab-competitions#3446]
Hi, we are interested in creating a "dynamic" leaderboard that takes into account the accuracies of previous submissions.  Is it possible to access that (or even leaderboard) from the scoring_program?

Or, is it possible to get the scoring program to read and write in a file which is then update every time a submission is performed and the scoring program is run?

Thanks!

**Comment by Didayolo** [comment]
Hi, this is a very interesting idea, however I don't think it is doable currently.

Each submission is run from scratch in an independent container and does not access previous scores or submissions.

I think you'll need to compute this as a post-challenge analysis, after having downloaded all scores.
