### ISSUE TITLE
Is the website crashed?

### ISSUE THREAD

**Issue by HELLORPG** [codalab/codalab-competitions#3447]
Is the [website ](https://codalab.lisn.upsaclay.fr/) crashed?🤔 
I can't access it. It gives me a `502 Bad Gateway`.

**Comment by acletournel** [comment]
There is a planned maintenance running today, potentially until 5pm CET. It has been announced on the front page since last week.
We are sorry for inconvenience and keep you informed.

**Comment by HELLORPG** [comment]
Ohhhhhh, I'm sorry that I didn't notice this, my fault.

THANK YOU for your reply.

Have a nice day~~
