### ISSUE TITLE
Warning: The compute queues are congested, please wait for existing jobs to process before submitting more. Thanks for your patience!

### ISSUE THREAD

**Issue by M-leng** [codalab/codalab-competitions#3454]
As the title, for the competition, the url is "https://codalab.lisn.upsaclay.fr/competitions/4318#participate-submit_results" . There is the warning. 
![图片](https://github.com/codalab/codalab-competitions/assets/15032403/52edfb1f-5256-4e9b-b19e-2f77bb3c7f5e)

![图片](https://github.com/codalab/codalab-competitions/assets/15032403/d8c470e3-601c-4a08-851d-13b33b797e1d)

**Comment by dtuantran** [comment]
Yes, we're having too many submissions submitted which are waiting for processing. Please consider using your own compute worker or asking your organizer, see more at : https://github.com/codalab/codalab-competitions/wiki/User_Using-your-own-compute-workers
