### ISSUE TITLE
Status stuck at the submitted phase, no further results

### ISSUE THREAD

**Issue by delaprada** [codalab/codalab-competitions#3456]
Hi, I am using codalab to submit my results. But the status is stuck at submitted phase and does not show any futher results. I was able to use it normally this morning but right now it shows up the above error.

![image](https://github.com/codalab/codalab-competitions/assets/40078051/81e173aa-f8de-44c8-ac76-7280f6badf4f)

This is the my competition link: https://codalab.lisn.upsaclay.fr/competitions/4318#participate

Thank you for your help!

**Comment by Didayolo** [comment]
Hi,

- Is this still happening?
- Are you a competition participant or organizer?
- Is the competition running on the default queue or on a custom queue?

**Comment by delaprada** [comment]
> Hi,
> 
> * Is this still happening?
> * Are you a competition participant or organizer?
> * Is the competition running on the default queue or on a custom queue?

Hi, thanks for your reply. This is fixed right now.
