### ISSUE TITLE
Some submissions get stuck on "submitted"

### ISSUE THREAD

**Issue by ffcarina** [codalab/codalab-competitions#3465]
Hi! I'm one of the organizers of [ECAC@SemEval -2024 competition](https://codalab.lisn.upsaclay.fr/competitions/16141), some participants have reported that it takes a long time for their submissions to be successfully `Finished`. How can this issue be resolved?

> After I submitted the file,  the submission state is "submitted" and I can't see the score of the submission. How long will the state be the finished? 

> I had the same problem. Yesterday I submitted 3 files, one of them was finished successfully after 2 hours. Other two failed.

**Comment by Didayolo** [comment]
Hi @ffcarina,

Are you using the default queue for computation, or you own compute workers?

**Comment by bdthanh** [comment]
Hi, 
I encountered the same problem here for ASVspoof5 competition.

**Comment by Didayolo** [comment]
I close this issue as it is staling.
