### ISSUE TITLE
Hugging face "evaluate" not working on codalab

### ISSUE THREAD

**Issue by jd-coderepos** [codalab/codalab-competitions#3466]
We try to test our scoring program and see the error msg below

```
Traceback (most recent call last):
  File "/tmp/codalab/tmpuunN5o/run/program/score.py", line 13, in <module>
    import evaluate
ModuleNotFoundError: No module named 'evaluate'
```

Essentially, the program imports `evaluate` which is the huggingface library. We tried to copy the src code for evaluate in the program zip file which we upload to codalab. This seems to work, but then huggingface `evaluate` has dependency to another package called `datasets`. The error msg we saw then is below

```
Traceback (most recent call last):
  File "/tmp/codalab/tmpswpuKf/run/program/score.py", line 13, in 
    import hf_evaluate
  File "/tmp/codalab/tmpswpuKf/run/program/evaluate/__init__.py", line 29, in 
    from .evaluation_suite import EvaluationSuite
  File "/tmp/codalab/tmpswpuKf/run/program/evaluate/evaluation_suite/__init__.py", line 7, in 
    from datasets import Dataset, DownloadConfig, DownloadMode, load_dataset
ModuleNotFoundError: No module named 'datasets'
```

we could certainly try by bringing the `datasets` src code to the scoring program zip folder. But we are afraid there may be other further dependencies to resolve. So long description short question:

Can you install the huggingface `evaluate` package to codalab? Or what else would you suggest we do? 

Thank you in advance for your reply. 

@SchenbergZY

**Comment by jd-coderepos** [comment]
hi,

we managed to solve the issue by adding the install function in the header of our scoring program. See code snippet below.
```

import subprocess
import sys

def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Dynamically install the 'evaluate' package
install("evaluate")

# Now, import 'evaluate' and use it
import evaluate
```

**Comment by Didayolo** [comment]
@jd-coderepos 

Glad to hear that you could solve your problem.

Another way is to select a different "competition docker image" that contains the desired libraries.

You can update an existing docker image for this. See: https://github.com/codalab/codalab-competitions/wiki/User_Docker
