### ISSUE TITLE
Status not change : Running

### ISSUE THREAD

**Issue by ghost** [codalab/codalab-competitions#3472]
Hi
as picture below, my 11st submission status is Running and it does not change
Bigger problem is that when new submission is made, it keep give me submission error

can you solve the server status?

thanks

 
![image](https://github.com/codalab/codalab-competitions/assets/8009654/3a73d436-11c3-47db-aedb-911d53826038)

**Comment by Didayolo** [comment]
Hi @hellobwjung,

Are the submissions supposed to take a long time? Is it results submissions or code submissions?

> Bigger problem is that when new submission is made, it keep give me submission error

What error do you encounter exactly? I am not able to reproduce this problem.

**Comment by ghost** [comment]
Hi @Didayolo 
Submission should take more than a week?

My status is exactly same as the picture. 
and wherever I try to make another submission, 
it seems to be processing but finally give me file uploading error
can you cancel my submission #11? so I can upload my files?

**Comment by ghost** [comment]
#11 status not changed, but I found I still can upload files. thanks for your support
