### ISSUE TITLE
widgets are not working

### ISSUE THREAD

**Issue by DeepDuke** [codalab/codalab-competitions#3474]
Hi, it seems the widgets are not working.  I want to paste the `iframe` code to my site to show the leaderboard. But it showed nothing. 
```
<iframe src="http://codalab.lisn.upsaclay.fr/competitions/leaderboard_widget/18028/" style="height: 500px; width: 100%; border: none;"></iframe>
```

**Comment by Didayolo** [comment]
Thank you for reporting. Isn't this issue a duplicate of  #3305 ?

**Comment by DeepDuke** [comment]
Sorry. It's indeed duplicated.

**Comment by Didayolo** [comment]
No problem!
