### ISSUE TITLE
AssertionError: Prediction incomplete, cannot find prediction: /tmp/codalab/tmpHX66LE/run/input/res/seq21/Labels/000600.png

### ISSUE THREAD

**Issue by xrr20001218** [codalab/codalab-competitions#3478]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/codalab/tmpHX66LE/run/program/addToConfusionMatrix.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ./program/addToConfusionMatrix.c:716:
/opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
Traceback (most recent call last):
  File "/tmp/codalab/tmpHX66LE/run/program/evaluate.py", line 29, in 
    IOUs, mIOU, acc = evaluateFromDirectories(truth_dir, submit_dir)    
  File "/tmp/codalab/tmpHX66LE/run/program/evaluate_dir.py", line 120, in evaluateFromDirectories
    cm = getConfusionMatrixfromDirectory(gt_home, pred_home)
  File "/tmp/codalab/tmpHX66LE/run/program/evaluate_dir.py", line 100, in getConfusionMatrixfromDirectory
    assert osp.exists(pred_path), 'Prediction incomplete, cannot find prediction: %s'%(pred_path)
AssertionError: Prediction incomplete, cannot find prediction: /tmp/codalab/tmpHX66LE/run/input/res/seq21/Labels/000600.png

How to solve it?

**Comment by Didayolo** [comment]
The error indicates that your submission is incomplete (a file is missing).

Please check your submission. Try the example submission of the competition. If the problem persists, contact the organizers (this github repository concerns the platform itself).
