### ISSUE TITLE
[BUG] Error of username validation on username

### ISSUE THREAD

**Issue by P-atch** [codalab/codalab-competitions#3479]
Hi,
I probably found a bug creating my account with the symbol 'æ' in the username.
Creation was successful, but I got a raw `500` error when trying to login after email confirmation.

Hope a solution will be found,
Thanks

**Comment by Didayolo** [comment]
Hi @Ptchw0rk,

If you confirmed your email, I guess you are not able to re-create an account nor to login into it?

What is your username? I can replace the `æ` to `ae` to unblock it if you want.

**Comment by P-atch** [comment]
I recreated an account with a valid username and another email, this was just to report the bug.
Thanks
