### ISSUE TITLE
Cannot receive verification email

### ISSUE THREAD

**Issue by ayiyayi** [codalab/codalab-competitions#3480]
Hi,

I recently registered for the EPIC-KITCHENS-100 Action Recognition Competition using my school email. However, it's been 8 days since I signed up and I still haven't received the verification email. I've checked my spam folder, but it's not there either.  I've received verification emails for other challenges without any issues.

I would greatly appreciate it if you could assist me with this matter.

Best regards,
Ayiyayi

**Comment by Didayolo** [comment]
@ayiyayi 

Hi! Sometimes institute emails filter out CodaLab emails.

Two solutions:
- We activate your account manually. However, future emails may get filtered too.
- You re-create an account using a different email address.

Sorry for the inconvenience.

**Comment by ayiyayi** [comment]
Thanks for your reply! I resent the email and receive verification email successfully.
