### ISSUE TITLE
error for submission

### ISSUE THREAD

**Issue by cgz6498** [codalab/codalab-competitions#3481]
When I submit my dataset to HO3Dv2 and H2O3D, I encounter the following error:

```python
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
You are using pip version 9.0.1, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Didayolo** [comment]
@cgz6498 This looks like simple warnings. Are your submissions computed correctly?

**Comment by cgz6498** [comment]
<img width="359" alt="mmexport86a7eada146513742d7a315bc63cdf36_1714125352806" src="https://github.com/codalab/codalab-competitions/assets/77420384/5158f559-e35c-41c6-a69d-de11acbbba42">
Yes, the display submission is correct, but the message is incorrect

**Comment by Didayolo** [comment]
Can you be more specific? What is incorrect? What issue are you encountering?

**Comment by cgz6498** [comment]
For example, after I compress the trained .json file into a zip file and submit it to Ho3dv2 (https://codalab.lisn.upsaclay.fr/competitions/4318#participate), it shows that the submission was successful, as in the first image. However, when I check for errors, as in the second image, it reports an error. The error message is as follows.
![Uploading 1bc014bc0854c5f10c685b18daf8828.png…]()
![Uploading 325936980-5158f559-e35c-41c6-a69d-de11acbbba42.png…]()

**Comment by cgz6498** [comment]
For example, after I compress the trained .json file into a zip file and submit it to Ho3dv2 (https://codalab.lisn.upsaclay.fr/competitions/4318#participate), it shows that the submission was successful, as in the first image. However, when I check for errors, as in the second image, it reports an error. The error message is as follows.
<img width="761" alt="1bc014bc0854c5f10c685b18daf8828" src="https://github.com/codalab/codalab-competitions/assets/77420384/bfc3f5d8-f297-4759-8b18-eff1372e52fe">

<img width="359" alt="325936980-5158f559-e35c-41c6-a69d-de11acbbba42" src="https://github.com/codalab/codalab-competitions/assets/77420384/98328019-b2e6-4deb-9b6c-fe00281ac1bf">

**Comment by cgz6498** [comment]
For example, after I compress the trained .json file into a zip file and submit it to Ho3dv2 (https://codalab.lisn.upsaclay.fr/competitions/4318#participate), it shows that the submission was successful, as in the first image. However, when I check for errors, as in the second image, it reports an error. The error message is as follows.
<img width="761" alt="1bc014bc0854c5f10c685b18daf8828" src="https://github.com/codalab/codalab-competitions/assets/77420384/d5646c10-97c6-4c97-a225-a4c81ce4221e">

<img width="359" alt="325936980-5158f559-e35c-41c6-a69d-de11acbbba42" src="https://github.com/codalab/codalab-competitions/assets/77420384/eb3c17a9-ec47-4b1a-b7de-1f1b047a7536">

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
You are using pip version 9.0.1, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by Didayolo** [comment]
It is a simple warning. The submission is being handled correctly and returns a score, so there is no problem.

If you are the competition organizer, you can consider using an up-to-date docker image to avoid this kind of warnings, but it is not mandatory.

If you are a participant, then you are all set.

I mark this issue as resolved, but feel free to pursue the discussion if needed.

**Comment by cgz6498** [comment]
But I didn't receive an error.
