### ISSUE TITLE
ImportError: No module named open3d

### ISSUE THREAD

**Issue by hxwork** [codalab/codalab-competitions#3485]
Hi,

After submitting the zip file on the HO3D (version 2) competition website, the status becomes "Failed" and here is the information,
<img width="1313" alt="image" src="https://github.com/codalab/codalab-competitions/assets/46584121/6c507e0f-3889-4711-8dc5-6e024fd90596">

Could you please help check this problem? Thanks in advance!

**Comment by hxwork** [comment]
Hi, @Didayolo 

Sorry to bother you. Could you please help check this issue? I think this problem happened previously, and it should be easy to solve on your side. Really appreciate your help.

**Comment by M-leng** [comment]
I also had this problem now. 

The competition is HO3D (version 2) (https://codalab.lisn.upsaclay.fr/competitions/4318#learn_the_details)

Error:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
  Could not find a version that satisfies the requirement open3d-python (from versions: )
No matching distribution found for open3d-python
  Could not find a version that satisfies the requirement open3d-python (from versions: )
No matching distribution found for open3d-python
Traceback (most recent call last):
  File "/tmp/codalab/tmpj21I43/run/program/evaluate.py", line 22, in 
    import open3d as o3d
ImportError: No module named open3d

**Comment by donghaoye** [comment]
Same issue.

**Comment by zhangy76** [comment]
Same here

**Comment by Didayolo** [comment]
@hxwork 

> Sorry to bother you. Could you please help check this issue? I think this problem happened previously, and it should be easy to solve on your side. Really appreciate your help.

Are you the competition organizer? Did you change the competition Docker image?

**Comment by hxwork** [comment]
I am not the organizer, but just a participant.

**Comment by hxwork** [comment]
> @hxwork
> 
> > Sorry to bother you. Could you please help check this issue? I think this problem happened previously, and it should be easy to solve on your side. Really appreciate your help.
> 
> Are you the competition organizer? Did you change the competition Docker image?

I am not the organizer, but just a participant.

**Comment by Didayolo** [comment]
Please report the problem to the competition organizers. As administrators of the platform, we do not manage individual competitions.

They may have changed the scoring program or the competition Docker image.

**Comment by hxwork** [comment]
> Please report the problem to the competition organizers. As administrators of the platform, we do not manage individual competitions.
> 
> They may have changed the scoring program or the competition Docker image.

OK. I reported this problem a few days ago, https://github.com/shreyashampali/HOnnotate/issues/37, but got no response.

**Comment by hxwork** [comment]
> Please report the problem to the competition organizers. As administrators of the platform, we do not manage individual competitions.
> 
> They may have changed the scoring program or the competition Docker image.

Is this issue related to [the previous one](https://github.com/codalab/codalab-competitions/issues/3263)?

**Comment by hxwork** [comment]
The competition organizer helps to solve this problem. Thanks.

**Comment by zhangy76** [comment]
The same issue also appears to HO3D_v3 challenge. After the fixing, it becomes:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment. warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') Execution time limit exceeded!

I open an issue to the author but also continue the post here for seeking the possible kind help from the competition server side.

Thanks!
