### ISSUE TITLE
Uavid AssertionError: Prediction incomplete, cannot find prediction

### ISSUE THREAD

**Issue by xrr20001218** [codalab/codalab-competitions#3486]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/codalab/tmp2Dy79i/run/program/addToConfusionMatrix.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1960,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ./program/addToConfusionMatrix.c:716:
/opt/conda/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
Traceback (most recent call last):
  File "/tmp/codalab/tmp2Dy79i/run/program/evaluate.py", line 29, in 
    IOUs, mIOU, acc = evaluateFromDirectories(truth_dir, submit_dir)    
  File "/tmp/codalab/tmp2Dy79i/run/program/evaluate_dir.py", line 120, in evaluateFromDirectories
    cm = getConfusionMatrixfromDirectory(gt_home, pred_home)
  File "/tmp/codalab/tmp2Dy79i/run/program/evaluate_dir.py", line 100, in getConfusionMatrixfromDirectory
    assert osp.exists(pred_path), 'Prediction incomplete, cannot find prediction: %s'%(pred_path)
AssertionError: Prediction incomplete, cannot find prediction: /tmp/codalab/tmp2Dy79i/run/input/res/seq21/Labels/000600.png

my prediction is complete,how to solve it

**Comment by Didayolo** [comment]
- How are you sure your submission is complete?
- Do other participants have the same problem?
- Is there a baseline submission that works?
- Did it work in the past?
- Have you reported the problem to the competition organizers?
