### ISSUE TITLE
Disappearing submissions + stuck submissions

### ISSUE THREAD

**Issue by dr-tariq-n-ahmad** [codalab/codalab-competitions#3487]
https://codalab.lisn.upsaclay.fr/competitions/17730#participate-submit_results

Many of my submissions get stuck on "Running". There was one yesterday that was stuck, and today it has completely dissappeared.

I emailed info@codalab.org only to get a "This is the mail system at host smtps.codalab.org."

What is going on?

**Comment by Didayolo** [comment]
Hi @dr-tariq-n-ahmad 

Can you please give more information?

- What is your CodaLab username?
- Was the submissions running fine before?
- What is the normal duration of a submission?
- Can you share the IDs of some of the stuck submissions (obviously not the disappearing ones)?

> I emailed [info@codalab.org](mailto:info@codalab.org) only to get a "This is the mail system at host smtps.codalab.org."

That is surprising, we are investigating this problem.

**Comment by dr-tariq-n-ahmad** [comment]
Hi

Username is drt.

My submissions worked I think 3 times during the training phase, the problem appeared when the evaluation phase started I believe. Normally submission takes around 5mins. I am not sure where to get the IDs from, see attachments please.

Many thanks.

________________________________

**Comment by Didayolo** [comment]
I can't see the attachment, neither on Github or by email.

Maybe it is normal that the evaluation takes longer in this phase? Have you been in touch with the competition organizers? Do other participants experience the problem?

**Comment by dr-tariq-n-ahmad** [comment]
No evaluation can't be taking hours.

Here's links to the images:

https://www.dropbox.com/scl/fi/uo6udac5ifksaylgr70ol/Screenshot_20240517-082924_Chrome.jpg?rlkey=aatxhckcy6557g29kicd9reec&dl=0

https://www.dropbox.com/scl/fi/al79yg6deuqb9v47bd091/Screenshot_20240517-083211_Chrome.jpg?rlkey=4dqziwck268ez28j48wlo3lf4&dl=0

No ide about anyone else.

I thought you were the organisers???


________________________________

**Comment by dr-tariq-n-ahmad** [comment]
???

**Comment by Didayolo** [comment]
> I thought you were the organisers???

We manage the platform itself, organizers are independant.

You can contact all organizers of the shared task at [exalt-wassa2024@googlegroups.com](mailto:exalt-wassa2024@googlegroups.com)

See: https://codalab.lisn.upsaclay.fr/competitions/17730#learn_the_details-organizers
