### ISSUE TITLE
IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by willemeng** [codalab/codalab-competitions#3488]
Please fix the issue with semantickitti ssc task. thanks.

**Comment by jxLiang666** [comment]
I also met the issue in semantickitti mos task, please try to fix it  @Didayolo

**Comment by Didayolo** [comment]
Hi,

- What is the URL of the competition?
- Did you contact the organizers?
- Organizers: are you using the default queue or a custom queue?

**Comment by willemeng** [comment]
https://codalab.lisn.upsaclay.fr/competitions/7170#participate-submit_results

**Comment by jxLiang666** [comment]
> Hi,
> 
> * What is the URL of the competition?
> * Did you contact the organizers?
> * Organizers: are you using the default queue or a custom queue?

1. the url is https://codalab.lisn.upsaclay.fr/competitions/7088
2. I have sent an email to the organizer, he said that the issue is the side of codalab
3. I don't know about queue, perhaps the default queue? because there is no way to choose

**Comment by Didayolo** [comment]
Dear all,

I confirm that the competition is running on the default queue (so the problem is indeed on our side).

We just updated compute workers, which created this problem. We are working on it to solve it as soon as possible. Sorry for the inconvenience.

**Comment by Didayolo** [comment]
@willemeng @jxLiang666 @blue-531 @ccyyu2

The problem should be solved. Please report it if you face it again.
