### ISSUE TITLE
"[Errno 28] No space left on device" in semantic scene completion competition

### ISSUE THREAD

**Issue by blue-531** [codalab/codalab-competitions#3489]
I'm currently working on a semantic scene completion competition. There occurs a "[Errno 28] No space left on device" error. same as #3488 . This error occurs every time I try to participate, and it is still not fixed. 
It will be a great help if it is fixed.

**Comment by Didayolo** [comment]
Thank you for reporting the issue. I close this one to keep everything on #3488.
