### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by yahooo-m** [codalab/codalab-competitions#3492]
I sent an email to info@codalab.org. I want to know whether the finished competition show my new name or not?

**Comment by Didayolo** [comment]
Hi, I'm not sure if I received your email. What is the new username you asked?

> I want to know whether the finished competition show my new name or not?

Yes, the new username will be reflected everywhere in the platform.

**Comment by yahooo-m** [comment]
Could you please help me?

**Comment by yahooo-m** [comment]
I appreciate to receive your reply.
