### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by yahooo-m** [codalab/codalab-competitions#3493]
Hi, I sent an email. But the username has not changed.
<img width="392" alt="change_username" src="https://github.com/codalab/codalab-competitions/assets/27918565/369b41dc-f71e-4c07-bdf4-781b64f4542b">

**Comment by Didayolo** [comment]
Hi @yahooo-m,

Sorry, it seems that sometimes the email to info@codalab.org does not get redirect correctly to my email.

I successfully changed your username to PCL_MDS.

Best regards
