### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by junjun621** [codalab/codalab-competitions#3494]
Hello, I encountered this problem, how can I deal with it?

`docker: failed to register layer: write /usr/share/perl5/Dpkg/Source/Package/V2.pm: no space left on device.`

https://codalab.lisn.upsaclay.fr/competitions/7170#participate-submit_results

**Comment by Didayolo** [comment]
Thank you for reporting the problem. It seems to be linked with the new workers on our public queue.

We are going to investigate this as soon as possible.

**Comment by Didayolo** [comment]
The problem should be solved. Feel free to re-open the issue if needed.
