### ISSUE TITLE
Links to participants submissions, detailed results, etc... are broken

### ISSUE THREAD

**Issue by gorkamunoz** [codalab/codalab-competitions#3500]
Since a couple of days, there seems to be an problem with the links whenever to try to get the Detailed Results of the participant's submissions from the leaderboard, or access their submissions, outputs, ... etc from the Submissions tab. The message we get is like this:

It looks like the webpage at https://miniodis-rproxy.lisn.upsaclay.fr/py3-private/submission_detailed_results/eb1ebe43-c5f4-4c63-90a1-32d9c9a9bec3/detailed_results_file.html?response-content-type=text%2Fhtml&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=EASNOMJFX9QFW4QIY4SL%2F20240627%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240627T140353Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=921da9c9cb780f98cb6a3ea682424721d6c916e9bc1cd5ba9ea06dbcc184f938 might be having issues, or it may have moved permanently to a new web address.

Any clue on what is happening? Thanks!

**Comment by Didayolo** [comment]
Hi @gorkamunoz,

The link you provided works perfectly on my side. What are the symptoms you observe?

**Comment by gorkamunoz** [comment]
Hi! Yes, there seems to be some fluctuations. They stopped working two days ago, then they were back. Yesterday when I wrote the Issue they were down again and now they are working again...
