### ISSUE TITLE
ParserError: Metadata, parser.py

### ISSUE THREAD

**Issue by connahKendrickMMU** [codalab/codalab-competitions#3502]
Hi, I’m struggling to get my scoring program to work with the submission system (https://codalab.lisn.upsaclay.fr/competitions/19459). I have tried a few corrections and changes but I can’t narrow down where the error is coming from as the code runs and outputs on my local machine. 

The error is:

```python
Traceback (most recent call last):
  File "/worker/worker.py", line 323, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 180, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 171, in get_bundle
    metadata = yaml.load(mf)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
ParserError: expected '', but found ''
  in "/tmp/codalab/tmpLRnkx2/run/program/metadata", line 5, column 1
```

But my original metadata file is only two lines:

```yaml
command: python $program/evaluate.py $input $output
description: Example competition evaluation program.
```

I have adjusted the scoring program and that did change the error from line 7 to 5, but I can’t narrow down the error. I cant seem to adjust the metadata, and have looked at similar issues:

- #2419
- #2143

 Any advice?

**Comment by Didayolo** [comment]
Hi,

I think that the `run/program/metadata` file is related to the submission. What does you submission contain? Is there a metadata file there (code submission)?

**Comment by connahKendrickMMU** [comment]
Hi Adrien,

I hope you are well,

Apologies for the delay,

The submission is a file of 200 black-and-white images in a zip file, there should be no code submission inside, I have attached the reference data and an example submission, so if this is submitted we will get perfect scores. Does the system auto-unzip files?

Do you think it could be my loading functions?

The line of the meta-data does change

Once we have this working, I can't share the images publicly, but I'd happily put them in a different format so we can share an image task in the example projects.

Many thanks for your help it is greatly appreciated.

Cheers,

Connah

**Comment by Didayolo** [comment]
I can't see the attachment. Please send it by email to info@codalab.org

**Comment by Didayolo** [comment]
Also, it is important to zip files directly, without directory structures

**Comment by connahKendrickMMU** [comment]
I have sent the file over

I have played about and to help narrow down the error I striped the scoring program down to a file that just has the base imports, print and writes to a file in (attached), I got the same error still,

I am running a docker image, so it could be I'm on the wrong Python version, I'll try updating the image to my Python version.

Thanks again for all your help and support with this 🙂




________________________________

**Comment by andrzejbro** [comment]
Has the problem been solved? I am trying to submit a .zip file with images and get the same error.

**Comment by Didayolo** [comment]
@connahKendrickMMU

Your command in the metadata file is:

```yaml
command: python $program/evaluate.py $input $output
```

However the file you sent me is called `evaluate.py.txt`. You should rename it `evaluate.py` and re-upload your scoring program.

**Comment by ayushnangia** [comment]
@connahKendrickMMU @Didayolo 
Hey guys we are trying to submit the zip file for the testing phase. Let us know if your resolve the failing issue and please update this github issue thread.
