### ISSUE TITLE
Wait too long to submit too

### ISSUE THREAD

**Issue by yahooo-m** [codalab/codalab-competitions#3504]
When I submit my file to the competition, the button is always grey and my results have never been submitted.

My name is PCL_MDS
The competition is https://codalab.lisn.upsaclay.fr/competitions/10703#participate-submit_results and https://codalab.lisn.upsaclay.fr/competitions/6812#participate-submit_results

**Comment by yahooo-m** [comment]
Need Help!! 
I must submit rebuttal file!

**Comment by Didayolo** [comment]
I close this issue to follow it here: #3503
