### ISSUE TITLE
SemanticKITTI: Moving Object Segmentation- Error: Execution time limit exceeded!

### ISSUE THREAD

**Issue by ccyyu2** [codalab/codalab-competitions#3506]
Hello, I am a participant in the SemanticKITTI: Moving Object Segmentation competition. I have ensured that the .zip file I submitted is correct, but my submissions often fail with the following error message: "Error: Execution time limit exceeded!"

**Comment by Didayolo** [comment]
Hi,

Did you try contacting the organizers of the competition? This repository concerns the platform itself.

- Do other participants face the same issue?
- Was it working in the past?
- Is it results submission or code submission?

**Comment by jbehley** [comment]
I think I could resolve it, but this is happening for multiple competitions and I had to increase the execution time limit.  Therefore, the issue seems to be resolved for now.
