### ISSUE TITLE
Cannot submit results at all. Button is grayed out after submission but nothing happens.

### ISSUE THREAD

**Issue by jonaden94** [codalab/codalab-competitions#3507]
Dear Codalab team,

I am unsure whether this is a platform or competition specific issue but it seems that the former might be the case so I am writing here to receive any potential feedback. I am trying to submit results to the dancetrack MOT challenge (https://codalab.lisn.upsaclay.fr/competitions/5830#participate) and only see a grayed out button when I submit results. Nothing happens afterwards. Other participants have experienced the same issue (see this forum post: https://codalab.lisn.upsaclay.fr/forums/5830/2647/)

Do you know where this issue might originate from?

Browser version: Google Chrome Version 127.0.6533.120 
Link to challenge: https://codalab.lisn.upsaclay.fr/competitions/5830#participate

**Comment by Didayolo** [comment]
Same as #3503.

A work-around before it get resolved is to use Firefox instead of Chrome.

Sorry for the inconvenience. I close this issue to keep track of the problem in #3503.
