### ISSUE TITLE
How to submit my results on the OVIS datasets？

### ISSUE THREAD

**Issue by CoveLSwallow** [codalab/codalab-competitions#3509]
Hello,

I am currently experiencing an issue where clicking the “submit” button does not produce any response when submitting results. 
The file being submitted is named: submission.zip. Could you please provide a solution? Thanks！

Browser version: Google Chrome (Version 127.0.6533.120)

Dataset: Occluded Video Instance Segmentation (OVIS)
URL: https://codalab.lisn.upsaclay.fr/competitions/4763#participate-submit_results

As shown in follows：
![image](https://github.com/user-attachments/assets/c14ed370-56aa-4a27-932a-032d2624aff7)

**Comment by Didayolo** [comment]
I think you are experiencing this problem: #3503

Try to use Firefox to see if it resolve the problem.

**Comment by zsz00** [comment]
I use Firefox to submit , get a error:
An unexpected error occurred.
It was good the day before yesterday.

@Didayolo

**Comment by Didayolo** [comment]
@zsz00 You get this error at the moment you try to submit? And the submission never starts?

**Comment by zsz00** [comment]
at the moment I  submit some times success.

**Comment by molu-fhv** [comment]
I have exactly the same problem. I've tried different browsers (Firefox, Chrome, Opera, and Edge) as well as multiple laptops, but the problem persists. Does anybody have a solution to that?

**Comment by molu-fhv** [comment]
It seems to be working for me now. My solution was to increase the ZIP compression level. Initially, I had it set to 0%, but after raising the compression (resulting in smaller files), the submission system started working fine!

**Comment by Didayolo** [comment]
I close this issue to keep track only in #3503
