### ISSUE TITLE
Submissions stuck in "subbmit" status

### ISSUE THREAD

**Issue by EdenSSR** [codalab/codalab-competitions#3511]
Hi, Im running UAVid Challenge competition (Link: https://codalab.lisn.upsaclay.fr/competitions/7302)
But, When I click the submit button, it only turns gray and has no response，look this
![image](https://github.com/user-attachments/assets/a2a2a822-2087-4108-af31-a510491abbf5)

**Comment by zsz00** [comment]
Im running MOSE Challenge competition, get same problem ,  with Firefox ..

**Comment by EdenSSR** [comment]
> Im running MOSE Challenge competition, get same not response, with Firefox ..

I using Chrome and Edge, also get same not response. Even i using other computer, get same. But i haven't try to change another account, maybe it useful?

**Comment by lxp991108** [comment]
I run FCGEC competition, also get no response.

**Comment by szjzdmy** [comment]
I had the same problem with the ADD2023 competition interface.

**Comment by EdenSSR** [comment]
I trying to submit today, but alse no response......

**Comment by EdenSSR** [comment]
It work! I just download Firefox and can submit my data!
