### ISSUE TITLE
can download the data  of   AIM 2019 Demoireing Challenge - Track 1: Fidelity

### ISSUE THREAD

**Issue by UNrelike** [codalab/codalab-competitions#3512]
![image](https://github.com/user-attachments/assets/47be7f28-ac75-4b4a-86dc-2f4676a4f9c7)
https://data.vision.ee.ethz.ch/timofter/AIM19demoire/Training.zip  This link seems to be dead

**Comment by SongYan888** [comment]
I had the same problem

**Comment by Didayolo** [comment]
Hi,

Please reach the organizers of the competition directly to inform them that the link is dead.

As administrators and developers of the platform, we can't help with that. Thank you for your comprehension.
