### ISSUE TITLE
No verification email received

### ISSUE THREAD

**Issue by Otpid** [codalab/codalab-competitions#3513]
I am trying to sign up with a new account for SemEval 2025, but I cannot seem to get the verification email. 

I have: 

- Tried both websites: https://competitions.codalab.org/ and https://codalab.lisn.upsaclay.fr/
- Tried setting up two different accounts with two different email addresses (outlook and gmail).
- Checked my spam/junk folders in both. 

No luck so far. Any help will be appreciated. Thanks!

**Comment by Didayolo** [comment]
Hi,

Sorry for the inconvenience. Can you please share your username?

**Comment by Otpid** [comment]
Thanks for getting back to me! I received the verification email last night
(around 10-12 hours later). Might have been some problem with the server. I
was able to log in after that.
Thanks for the support.
