### ISSUE TITLE
No verification email received

### ISSUE THREAD

**Issue by vtphatt2** [codalab/codalab-competitions#3514]
Hi, I have been waiting for 3 hours but I didn't receive any verification email from Codalab. I really want to create an account right away because I am about to join in a competition organized by my school.

My username : vtphatt2
My email : thinhphat***@gmail.com

**Comment by Didayolo** [comment]
Hi,

I close this issue to keep track of the problem here: https://github.com/codalab/codabench/issues/1579

It should have been fixed by now. Feel free to comment [here](https://github.com/codalab/codabench/issues/1579) if you still can't receive emails.
