### ISSUE TITLE
No verification Email received 

### ISSUE THREAD

**Issue by SushovitNanda** [codalab/codalab-competitions#3516]
I have tried setting up my account on both the Codalab and Codabench websites through different emails and usernames, but I haven't received the verification link in any of them. 
My username has been - sushovit , sushovit21
registered emails - sushovit.nanda@gmail.com , sushovit21@iiserb.ac.in

**Comment by Didayolo** [comment]
Hi,

I close this issue to keep track of the problem here: https://github.com/codalab/codabench/issues/1579

It should have been fixed by now. Feel free to comment [here](https://github.com/codalab/codabench/issues/1579) if you still can't receive emails.
