### ISSUE TITLE
Codalab is down for urgent maintenance (Maintenance is done)

### ISSUE THREAD

**Issue by ObadaS** [codalab/codalab-competitions#3520]
Due to urgent maintenance, the website will be taken offline for a few hours today (September 10, 2024, 12:00(PM) Noon CEST)

**Comment by embar111** [comment]
Hello, when will the maintenance be over?

**Comment by ObadaS** [comment]
We are doing some internal tests before bringing the website back online. 
It might take a few hours, but hopefully it won't take too much time.
Thank you for your patience.

**Comment by ObadaS** [comment]
@embar111 The instance is back online. Hopefully, there won't be any problems.

**Comment by Decem-Y** [comment]
Is it currently being shut down for maintenance again?

**Comment by ObadaS** [comment]
@Decem-Y  Hello, there was an unexpected problem with the server, but everything is back to normal now.
