### ISSUE TITLE
page 504 

### ISSUE THREAD

**Issue by zsz00** [codalab/codalab-competitions#3521]
https://www.codabench.org/
https://codalab.lisn.fr/
https://codalab.lisn.upsaclay.fr/

504 Gateway Time-out

![image](https://github.com/user-attachments/assets/79640de0-8814-4d32-92f8-6c0c57d9cdc7)

![image](https://github.com/user-attachments/assets/d7dae404-82cf-49ea-aecb-b01b229e10b8)

**Comment by Didayolo** [comment]
@zsz00 Are you still experiencing the issue? I see no problem on my side.

**Comment by zsz00** [comment]
It's alright now
