### ISSUE TITLE
New runs don't submit

### ISSUE THREAD

**Issue by aliannejadi** [codalab/codalab-competitions#3522]
I'm using Chrome Version 127.0.6533.119 (Official Build) (arm64). When I submit a new run zip file, the Submit button gets disabled and it remains in that state forever. I waited for very long and tried multiple times with different instances of competition but it's all the same.

**Comment by Didayolo** [comment]
Hi, you are encoutering the following issue: #3503

The current work-around is to use Firefox instead of Chrome.

**Comment by Didayolo** [comment]
I close this issue to keep track of it on #3503
