### ISSUE TITLE
Uploaded results are not one-to-one matches to the test set.

### ISSUE THREAD

**Issue by cwh912** [codalab/codalab-competitions#3524]
I uploaded 150 txt files and the error is as follows:
Traceback (most recent call last):
  File "/tmp/codalab/tmpZrXJvo/run/program/evaluate_full_test.py", line 22, in <module>
    organize_input_full.process(input_dir)
  File "/tmp/codalab/tmpZrXJvo/run/program/organize_input_full.py", line 63, in process
    "Uploaded results are not one-to-one matches to the test set.")
Exception: Uploaded results are not one-to-one matches to the test set.

**Comment by Didayolo** [comment]
Hi @cwh912,

Are you participant of the given competition? It looks like the issue you are encoutering is specific to this competition and to your submission file. Maybe you don't have the right number of lines in your prediction, or added a blank line, or something like this.

If you are not able to solve it, please reach the organizers of the competition you are participating in. This Github repository is managed by the administrators of the platform, of which competition organizers are independent. Thank you for your comprehension.

Feel free to re-open the issue if needed.
