### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Jaywxy** [codalab/codalab-competitions#3527]
planned maintenance running today?

[https://codalab.lisn.upsaclay.fr/](https://codalab.lisn.upsaclay.fr/ )is broken

**Comment by ObadaS** [comment]
Hello,
Yes, there was a planned maintenance on the October 9 from 7h30 CEST until 17h30 CEST.
The maintenance finished around 16h30 CEST

**Comment by Jaywxy** [comment]
thanks for the reply, but I am not able to submit the file to this contest  right now[https://codalab.lisn.upsaclay.fr/competitions/6280](https://codalab.lisn.upsaclay.fr/competitions/6280) , I made sure that my internet is fine, is there any other possibility please?

**Comment by Didayolo** [comment]
@Jaywxy What exactly prevent the submission? Could be #3503

**Comment by Jaywxy** [comment]
> @Jaywxy What exactly prevent the submission? Could be #3503

[https://github.com/codalab/codalab-competitions/issues/3503#issuecomment-2268982551](https://github.com/codalab/codalab-competitions/issues/3503#issuecomment-2268982551)
[https://github.com/codalab/codalab-competitions/issues/3503#issuecomment-2270851836](https://github.com/codalab/codalab-competitions/issues/3503#issuecomment-2270851836)

thanks!!good reply!!! solve problem！
