### ISSUE TITLE
competitions.codalab.org server is down

### ISSUE THREAD

**Issue by pomota** [codalab/codalab-competitions#3531]
if you are having trouble using the site:
-----------------------------------------
Hello.
I am trying to join and download dataset from old competition named LiTS challenge (liver tumor segmentation)
I am unable to access the link of the competition. 
I want to check if the server is unavailable.
I have written the details below.
Thank you.

1. What browser and version are you using? Chrome, 129.0.6668.90, mobile safari
2. What is the URL of the problem?
https://competitions.codalab.org/competitions/17094

**Comment by Didayolo** [comment]
Thank you for reporting the problem. Indeed, the old production server (competitions.codalab.org) is down.

It may be due to recent floods at the University. @ObadaS any thought on this?

**Comment by Didayolo** [comment]
Solved.
