### ISSUE TITLE
NTIRE 2020 RWSR dataset

### ISSUE THREAD

**Issue by fe-jpg** [codalab/codalab-competitions#3532]
gretting，dear organizer
Hello, sorry to disturb you，the link of dataset download [NTIRE 2020 RWSR dataset](https://competitions.codalab.org/competitions/22220#participate) is out of date，i try a lot to find the dataset but failed，
i will be so gratitude for you helping me to download the dataset
thanks a lot for your help！

**Comment by Didayolo** [comment]
Hi, thank you for reporting this issue. It is not just this link that is unvailable, but the whole server is currently down:

- #3531

We are working to resuming it as soon as possible. Thank you for your comprehension.
