### ISSUE TITLE
Unable to Upload Submission to Codalab

### ISSUE THREAD

**Issue by phanben110** [codalab/codalab-competitions#3533]
I have been trying to upload my submission to Codalab today, but I am repeatedly encountering issues. Despite multiple attempts, I have not been able to successfully upload my submission.

**Comment by Didayolo** [comment]
Hi, you are probably encountering this issue:

- #3503

We need to upgrade the software as soon as possible.

**Comment by phanben110** [comment]
> Hi, you are probably encountering this issue:
> 
> * [Submission not working with Chrome - Wait too long to submit #3503](https://github.com/codalab/codalab-competitions/issues/3503)
> 
> We need to upgrade the software as soon as possible.

Thank you for answering my question. I will update the software. I also tried using a different browser, Safari, and it worked fine.

**Comment by Didayolo** [comment]
> I will update the software.

Sorry for the confusion, I mean that we, as administrators of the platform, need to perform some upgrades to maintain the project working on all browsers. Glad I could help anyway.

**Comment by phanben110** [comment]
> > I will update the software.
> 
> Sorry for the confusion, I mean that we, as administrators of the platform, need to perform some upgrades to maintain the project working on all browsers. Glad I could help anyway.

Many thanks!
