### ISSUE TITLE
Can we use Bash for scoring?

### ISSUE THREAD

**Issue by cainesap** [codalab/codalab-competitions#3534]
Hello and thank you for running Codalab.
A question about the [scoring program](https://github.com/codalab/codalab-competitions/wiki/User_Building-a-Scoring-Program-for-a-Competition) : does it have to be a Python script, can it be a Bash script (which calls more than one Python script) ?
thanks, Andrew

**Comment by Didayolo** [comment]
Hi, it can be any kind of script. I think you'll need to update the `metadata` file inside the scoring program to specify another command to launch it. And code the scripts the way you want.

Feel free to re-open this issue if you were not able to make it, and could not find the answers you needed in the Wiki.
