### ISSUE TITLE
"SCORE" value at https://codalab.lisn.upsaclay.fr/competitions/7384#participate-submit_results

### ISSUE THREAD

**Issue by hjin200** [codalab/codalab-competitions#3538]
The value displayed in "SCORE" column at https://codalab.lisn.upsaclay.fr/competitions/7384#participate-submit_results is not mAP. It seems it displays the value of AR_large in scores.txt, which reports results on COCO val, not COCO test.
I would also like to verify that results on COCO test is included in stdout.txt, and scores.txt extracted from output_file.zip has the results on COCO val. This is great. It's nice to have both results as the task is indicated as "test-dev (bbox)".

**Comment by Didayolo** [comment]
Dear @hjin200,

You are reaching the maintainers of the platform. Please reach directly COCO organizers to report any problem with their competition. Thank you for your comprehension.
