### ISSUE TITLE
ntire daset download link is out of date(new)

### ISSUE THREAD

**Issue by fe-jpg** [codalab/codalab-competitions#3540]
gretting，dear organizer
Hello, sorry to disturb you，the two link of dataset download [NTIRE 2020 RWSR dataset] and[[NTIRE div8k dataset]](https://competitions.codalab.org/competitions/22220#participate) (https://data.vision.ee.ethz.ch/timofter/AIM19ExtremeSR/trainHR_1401to1500.zip) is out of date，i try a lot to find the dataset but failed，
i will be so gratitude for you helping me to download the dataset
thanks a lot for your help！

**Comment by Didayolo** [comment]
Hi @fe-jpg, you are reaching the maintainers of the platform. Please reach directly NTIRE organizers. Thank you for your comprehension.

**Comment by fe-jpg** [comment]
@Didayolo i tried to reach the organizers but get no reply recently,could you please tell me other way to deal with that problem,thanks a lot for your help!!
