### ISSUE TITLE
Submission issue with daemon

### ISSUE THREAD

**Issue by duquesnoykevin** [codalab/codalab-competitions#3541]
Hello, 

when submitting my files to my competition i have trouble with both safari and chrome, where the submission was not able to pass into the competition. Then, suddenly it got submitted twice and generated the following error for me, which seems to me like a server side issue, not a client side issue. 

Unable to find image 'codalab/codalab-legacy:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

1. What browser and version are you using?
both safari (16.6) and chrome (130.0.6723.117)

**Comment by Didayolo** [comment]
Hello,

- Are you organizer or participant of the competition?
- What is the URL of the competition?
- Is it using the default queue or a custom queue of compute workers?

**Comment by duquesnoykevin** [comment]
Thank you for your response. I am a participant, the organizer has resolved my issue but i am not aware how exactly. 
Can be closed!
