### ISSUE TITLE
Haven't received verification mail when signing in.

### ISSUE THREAD

**Issue by gap10** [codalab/codalab-competitions#3542]
I created an account yesterday. And as I am trying to sign in, it says "Verify your email address". I haven't received any such mail (I checked my spam folder). Also, the "resend confirmation mail" option doesn't seem to work either. I am using my personal email for signing in. Please resolve this issue.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change addresses the issue of users not receiving verification emails and improves the user experience during the signup process. We'll modify the signup view to resend the verification email if needed, add a resend button on the verification sent page, and improve the email templates.

You can review changes in this commit: https://github.com/jacks-sam1010/codalab-codalab-competitions-3542/commit/9e99427ff7998cc61703882273b0ce616a796947.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ObadaS** [comment]
Hello, we are currently having some problems sending emails towards Gmail accounts.
In the meantime, if you give me your account username (or send it to info@codalab.org if you are not comfortable sharing it here) we can activate your account for you.

**Comment by gap10** [comment]
My mail: [gpadole100@gmail.com](url)
Thanks!

**Comment by ObadaS** [comment]
I need your username to activate your account, not your email

**Comment by gap10** [comment]
Username: GauravPadole
Thanks!

**Comment by ObadaS** [comment]
Thank you. 
You should be able to log in now, I manually verified your account

**Comment by gap10** [comment]
I am now able to login. Thanks!

**Comment by gozdeozdil** [comment]
Could you please activate also my account? I could not receive verification email. My username is gozde.ozdil

@ObadaS

**Comment by ObadaS** [comment]
Hello @gozdeozdil , I have just activated your account

**Comment by chenjoachim** [comment]
Having the same verification email issue here. Could I also get manual verification? 
My username is FocusedRoboticsforAutonomousNavigationandKnowledge
Thank you!

**Comment by ObadaS** [comment]
Hello @chenjoachim, I activated your account, you should be able to sign in now

**Comment by StevenOufanHai** [comment]
Hi @ObadaS , could you please activate my account as well?
username: stevehai

**Comment by ObadaS** [comment]
Hello @StevenOufanHai, I just activated your account, you can now log in.
