### ISSUE TITLE
Verification Issues

### ISSUE THREAD

**Issue by krissimbolon** [codalab/codalab-competitions#3543]
I plan to be a competition participant. Previously, I had already registered on the Codalab Worksheet and encountered no issues up until the login process. Then, I attempted to create an account on Codalab (codalab.lisn.upsaclay.fr) using the same email address as the one used on the Codalab Worksheet. However, I did not receive a verification email in my inbox, despite trying multiple times.

When I tried logging in directly, the website stated that I needed to verify my email first, but there was no verification email in my inbox. I also attempted to register with a different email address, but the same issue occurred. This is now the fourth day I have been trying. Recently, I also tried using the 'forgot password' option, but the result was the same—no email was sent to my inbox. As a note, both accounts with the two usernames I entered during the first two attempts are succesfully registered (proven by the fact that both unique usernames that I made exist). The issue is that the platform does not send me any emails, whether for email verification or password recovery.

Does anyone know what I might be doing wrong and how to resolve this issue? Thank you.

**Comment by ObadaS** [comment]
Hello, we are currently having some problems sending emails towards some email providers.
In the meantime, if you give me your account username (or send it to [info@codalab.org](mailto:info@codalab.org) if you are not comfortable sharing it here) we can activate your account for you.

**Comment by krissimbolon** [comment]
Thank you for your kind response. I noticed that the verification email has been delivered to my inbox, and it seems the issue with email delivery has been resolved. Thank you very much.
