### ISSUE TITLE
Phases yaml  accept a start_date with minutes but break on render. 

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-competitions#461]
start_date is loosely parsed and that's great but if you add in min and seconds the rendered template cuts off important information. 

![phase_min](https://cloud.githubusercontent.com/assets/123099/3207235/254353ec-edd9-11e3-93d1-6129b1cec11e.png)

excerpt from yaml file that cuases problem

````yaml
phases:
  0:
    label: my phase label
    max_submissions: 100
    phasenumber: 0
    reference_data: reference_data.zip
    scoring_program: scoring_program.zip
    start_date: 2014-06-07 00:16:58.872229

**Comment by ErickWa** [comment]
Over-specified. No need to add seconds.
