### ISSUE TITLE
Participant profile info

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#511]
Currently participants only have a username, it'd be nice if we could have some more information.

Profile form with:
- Full name
- Biography
- School
- Photo

Viewing profile detail:
- What competitions they compete in
- How they rank in those competitions, maybe average rank overall?

Write some tests for this!
- Profile detail works
- Profile update works

Bonus: Wall of Fame page

**Comment by ErickWa** [comment]
Needs a developer to be assigned.
