### ISSUE TITLE
Organizers can validate entries and annotate them (competitions)

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#520]
For competitions with result submission for which the organizers verify the code "by hand" instead of having the code run on Codalab, we need a means of validating the submissions.
The could be achieved by adding to the submission table
![image](https://cloud.githubusercontent.com/assets/7594063/3634010/87448254-0f0e-11e4-8df1-552ee784af2b.png)
a check box "validated". 
Validated entries would appear with a check mark in the leaderboard (results table)
![image](https://cloud.githubusercontent.com/assets/7594063/3634015/c86226e2-0f0e-11e4-9cef-4bcc56e907a5.png)

As per issue https://github.com/codalab/codalab/issues/424, the submissions should have a name and a description (given by the participant). It would be nice to also let the organizers attach comments having to do with the validation process (explaining how it was done, why it failed, etc.). In general, it would be good it the participants could attach comments and files to a submission already made. Those could include published papers, graphs, etc.

**Comment by ErickWa** [comment]
Needs a developer to be assigned.

**Comment by madclam** [comment]
We'll revisit that when we scope chagrade for V2.
