### ISSUE TITLE
Add menu in editor for datasets showing up in "Get data" page

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#583]
In the "Get data" page, at the bottom, you can download datasets specified in the YAML file. This is how it looks like:

![image](https://cloud.githubusercontent.com/assets/7594063/3859904/58c4f9fc-1f1e-11e4-90c8-fb4a3d4910aa.png)

and here is how the corresponding part in the YAML file looks like:

![image](https://cloud.githubusercontent.com/assets/7594063/3859946/0999c6f4-1f1f-11e4-8a7d-2f361748722a.png)

With the new "My datasets" page, it is possible to get URLs of datasets and include them in the YAML file under "datasets" by 
- right clicking on the Download button
- copying the URL
- and it in the "url:" field.

![image](https://cloud.githubusercontent.com/assets/7594063/3859997/8c3ccbf6-1f1f-11e4-8a2d-fc1f6b680fc0.png)

But, there is no way to edit the YAML file from the editor. A pull down menu would be nice:

![image](https://cloud.githubusercontent.com/assets/7594063/3860037/f0e75b66-1f1f-11e4-8b02-daafdd408e3e.png)

Note: this is different from "Input data", which refers to the data that is made available to code uploaded to the participants. However, for the AutoML challenge purpose, it is actually the same data, so we could consider merging the two concepts, if Simon and other users agree.

This is related to:
https://github.com/codalab/codalab/issues/446

**Comment by abmnv** [comment]
Hi. I was wondering if this issue has been solved. There is still no way to add or modify dataset url in the competition editor. thanks.
