### ISSUE TITLE
Installing packages in the virtual environment of worker roles of codalab.org and codalabtest.cloudapp.net to support graphs as results 

### ISSUE THREAD

**Issue by prags** [codalab/codalab-competitions#592]
matplotlib, numpy and tcl packages need to be installed in the virtual environment of worker roles to be able to test the "detailed results" option which includes graphs and plots. The graphs in the html report (issue #581) were created using matplotlib python package.

I can help with the installation of the packages. As I don't have access to these two servers, I can't install them myself.

**Comment by FlavioAlexander** [comment]
It seems solved.
