### ISSUE TITLE
Change in "style" to see more in each page (competitions)

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#603]
Fonts, tabs, spaces are too big. We do not fit enough in a page and need to scroll down to see results.
Examples are shown below.

![image](https://cloud.githubusercontent.com/assets/7594063/4033456/8c5cb592-2c7b-11e4-80b7-36c115a5da71.png)

![image](https://cloud.githubusercontent.com/assets/7594063/4033468/c462085c-2c7b-11e4-92e2-0e3204f5e8ae.png)

**Comment by FlavioAlexander** [comment]
The layout has changed since this ticket was created.
