### ISSUE TITLE
New wireframes for Competition Landing Page

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab-competitions#775]

**Comment by ErickWa** [comment]
Feedback received - will pass spec to Flavio for costing

**Comment by ErickWa** [comment]
![codalabcompetitioncta2](https://cloud.githubusercontent.com/assets/4361560/11252182/a066d6fa-8de9-11e5-8b69-08043896122b.PNG)

**Comment by ErickWa** [comment]
Isabelle to try and record a video by May.

**Comment by FlavioAlexander** [comment]
@ErickWa I think we can close this issue, I just wanted to confirm with you before hitting the button
