### ISSUE TITLE
Sort competitions in order of "recency"

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#791]
In the competition list show the most recent competitions at the top.
![image](https://cloud.githubusercontent.com/assets/7594063/5401342/969991d4-8148-11e4-9914-d9cd065a2ab8.png)

**Comment by lr292358** [comment]
I also found this problem.
\+ the same is needed (the reverse order) for 'My datasets'

**Comment by FlavioAlexander** [comment]
Closing this issue since ordering is already in place
