### ISSUE TITLE
 Prevent multiple people from editing and clobbering changes: if

### ISSUE THREAD

**Issue by Raisins** [codalab/codalab-competitions#828]
Prevent multiple people from editing and clobbering changes: if start editing, and in the meantime someone already saved the worksheet, then try to save, system should throw an error rather than clobber their changes: this is already done on the CLI (remember not to throw away the changes in the text box!)

**Comment by Raisins** [comment]
this comment was on wrong issue

Traced though this. I am calling the same functions as the cli in the same order not getting the UsageError There is something deeper with saving going on. This will take more time then originally thought.

**Comment by ErickWa** [comment]
Dependencies on CLI behavior - need Percy's help - moving to April

**Comment by FlavioAlexander** [comment]
Closed here https://github.com/codalab/codalab-worksheets/issues/7
