### ISSUE TITLE
Submit frozen worksheets to competitions

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#847]
We would like to support the submission of worksheets to competitions are participant submissions in
https://www.codalab.org/competitions/xxxx#participate-submit_results

This could be done by referencing a bundle reference locator.

We also want to be able to specify the locator of a regular competition bundle that can be uploaded to https://www.codalab.org/my/datasets/ and would be executed like a regular code submission.

**Comment by madclam** [comment]
We want to revisit soon when we start working on life long learning.
1) Integration competition-worksheets in 2 ways:
    * submit "frozen" worksheets in the submission panel of a competition (ie pull a worksheet in a competition)
    * submit results produced by a worksheet to a competition (ie push a worksheet to a competition)
2) Have a variety of types of submissions in competitions (code, results, data, worksheets).

**Comment by FlavioAlexander** [comment]
I don't think this issue applies anymore; hence, I am closing this
