### ISSUE TITLE
Add end date to "Phases" page on competition detail

### ISSUE THREAD

**Issue by ckcollab** [codalab/codalab-competitions#849]
Currently phases only show the start date, not the end date of the phase.

Also, `CompetitionPhase` model needs an `end_date` field and the competition form.

**Comment by ErickWa** [comment]
Current Behavior: once one Phase is terminated, the next Phase begins, and competitors cannot make submissions to the prior Phase.

Variation: Would it be possible for us to not specify and end date for a given Phase, which would allow participants to continue to evaluate code in an early phase even after the bulk of the competition has moved on to later phases? Phase Migrations should continue to function as they do now, but prior (now closed) Phases, should still allow users to upload and play with code?
